### ISSUE TITLE
Remove PANAMA code

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#10377]
Historically, the OpenJ9 project worked to include functionality to support the goals of OpenJDK's Panama project (see https://openjdk.org/projects/panama/). That work was done under the control of a build flag. That flag was originally defined in `j9.flags` and later mirrored for CMake builds in `j9cfg.h.in`. In both build systems, the result is a macro (`J9VM_OPT_PANAMA`) in the derived artifact `j9cfg.h`, defined or not depending on whether or not the flag is enabled.

As we have not built with that flag enabled for quite some time, and because newer work relating
to Foreign Function & Memory API (see https://openjdk.org/jeps/424) is tied to the version of Java instead of the flag, many things related to, or conditional upon, that flag have simply become dead code.

The native code paths protected by `J9VM_OPT_PANAMA` and the Java code protected by `PANAMA` are stale: that code should be removed along with the configuration options.

The definition of, and references to, `opt_panama` in UMA builds no longer have any value. Likewise, the definition of `J9VM_OPT_PANAMA` for CMake builds is useless.

This issue seeks to clean up all that historical baggage.

**Comment by ohbus** [comment]
Hi @keithc-ca, I would like to work on this issue.

It would be great if you could please guide me to the documentation where I would find relevant information regarding this, or you may also point me to the code that requires the necessary amendments for this issue to be resolved successfully.

**Comment by keithc-ca** [comment]
Hi, @ohbus, thanks for the offer to help. Hopefully the following will clarify the intent of this issue.

In C/C++ code:
* Remove referenes to `J9VM_OPT_PANAMA`. For example, we would just remove [these lines](https://github.com/eclipse/openj9/blob/master/runtime/jcl/common/stdinit.c#L78-L80) in `stdinit.c`.

For the CMake build system:
* Remove `J9VM_OPT_PANAMA` from `options.cmake` and the reference in `j9cfg.h.in`.

For the UMA build system:
* Remove flags `graph_enableTesting_Panama` and `opt_panama` from `j9.flags`.
* Remove references to those flags from `*.spec`, `*.xml` files. For example, [these lines](https://github.com/eclipse/openj9/blob/master/runtime/jcl/uma/se9_exports.xml#L67-L69) in `se9_exports.xml` would just be removed.
* Remove support for `*_panama` SPECs.

Remove references to Panama from documentation and test infrastructure.

In each situation, the change should assume the flag is false or the preprocessor macro is not defined.

**Comment by callmetushar123** [comment]
@keithc-ca I am new to open source, I want to take up the issue can you please guide me a bit

**Comment by BamaCharanChhandogi** [comment]
> @keithc-ca I am new to open source, I want to take up the issue can you please guide me a bit
I am also new to open source . please guide me a bit.

**Comment by keithc-ca** [comment]
@BamaCharanChhandogi, are you still interested in helping with this?

**Comment by BamaCharanChhandogi** [comment]
Yeah, I am Interested.

**Comment by prajwalbandak** [comment]
Hi @keithc-ca, if this issue is still open, can you assign it to me?

**Comment by keithc-ca** [comment]
Thanks for the offer, @prajwalbandak.

**Comment by prajwalbandak** [comment]
Hey @keithc-ca had a small doubt, FFITypeHelpers.hpp for this class, 
#ifdef J9VM_OPT_PANAMA  this condition is there, Should we remove the only declaration part or remove from LINE 23 to LINE 173?

**Comment by prajwalbandak** [comment]
and In this folder buildspecs there are file called .spec, every file we should change it right? Example : buildspecs\linux_aarch64_cmprssptrs_cross.spec

**Comment by prajwalbandak** [comment]
Thanks for the update, working on it.
