### ISSUE TITLE
Refactor Valhalla tests to avoid dependencies between test methods

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse-openj9/openj9#10419]
Currently, Valhalla tests are structured so that dependencies between various tests exist, resulting in certain tests having to be run before other ones. In most cases, the dependencies are caused by certain tests performing some setup work that's also needed by other tests. To make the tests easier to work with, the tests should be refactored so that any kind of prerequisite work is done in special setup methods. Moving code in this way is likely to require splitting up the test methods across a few test classes. The benefits will be: 
1. being able to run test method individually without having to worry about figuring out which other tests need to be run first
2. it should become possible to run all tests multiple times while only running the necessary setup once

**Comment by theresa-m** [comment]
This should be resolved when we transition to the src_lw5 version of ValueTypeTests which does not rely as heavily on asm. See https://github.com/eclipse-openj9/openj9/pull/18558.
fyi @hangshao0 I think this can be closed.
