### ISSUE TITLE
JEP 338: Vector API (Incubator)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#10627]
See https://openjdk.java.net/jeps/338

also https://github.com/eclipse/openj9/issues/8076 and https://github.com/eclipse/openj9/issues/2220

**Comment by pshipton** [comment]
fyi @tajila @gita-omr

**Comment by DanHeidinga** [comment]
To confirm - are we running any tests related to the Vector API?  fyi @llxia

**Comment by tajila** [comment]
@llxia the tests can be found here, https://github.com/ibmruntimes/openj9-openjdk-jdk/tree/30a060cd4a7edfdb083e1ad7b8b899467f9f68b3/test/jdk/jdk/incubator/vector

**Comment by llxia** [comment]
Thanks @tajila . It looks like we do not have `jdk_vector` added in our openjdk playlist. I will add the target.

**Comment by llxia** [comment]
|platform|Grinder|
|--|--|
|x86-64_linux| https://ci.eclipse.org/openj9/job/Grinder/1525/|
|ppc64le_linux| https://ci.eclipse.org/openj9/job/Grinder/1526/|
|ppc64_aix| https://ci.eclipse.org/openj9/job/Grinder/1527/|
|x86-64_mac| https://ci.eclipse.org/openj9/job/Grinder/1528/|
|s390x_linux| https://ci.eclipse.org/openj9/job/Grinder/1529/|

**Comment by pshipton** [comment]
Looks like they have passed except for AIX which is still running. Lan, what is the best way to run these tests all the time for jdk16+? Can we add them to sanity.openjdk for jdk16+?

**Comment by smlambert** [comment]
These tests are added to extended level for a couple of reasons (and so will run weekly at Adopt):
- the target takes ~45min to run on xlinux (so not a quick set) 
- we matched sanity.openjdk to be equivalent to openjdk's tier1 tests and jdk_vector sits in tier3

**Comment by llxia** [comment]
All tests in https://github.com/eclipse/openj9/issues/10627#issuecomment-777801473 passed.

**Comment by pshipton** [comment]
It's too late to put additional changes into the 0.25 release, moving this forward.

**Comment by pshipton** [comment]
Moving forward again.

**Comment by tajila** [comment]
@gita-omr Can we close the older jep issues and keep only the latest for tracking purposes?

**Comment by pshipton** [comment]
See https://github.com/eclipse-openj9/openj9/issues/13623#issuecomment-1032898049
