### ISSUE TITLE
Remove support for `jextract -interactive`

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#10764]
It is replaced by `jdmpview`.

**Comment by dsouzai** [comment]
Not that `trprint` is great, but can you run `trprint` from `jdmpview?

**Comment by pshipton** [comment]
> can you run trprint from jdmpview

@dsouzai no, it was never ported to DDR. I don't think trprint works any more. You can try `jextract -interactive` on a core file and see trprint help, but it doesn't seem functional.

**Comment by dsouzai** [comment]
I had cleaned it up years ago; last I heard it could still print out the IL but would run into issues dealing with trying to print out what the comp threads were currently compiling. From a compilation control pov, I can make do without trprint because of other debugging tools (jdmpview included), but I don't know if the IL printing functionality is still used; @liqunl might be able to speak more on that.

**Comment by liqunl** [comment]
I tried trprint this week on x86 linux jdk11, it doesn't work. But early last year when I tried it (probably on java8 IBM build), it worked. 

It's good to have a tool to print a node or IL passing it the node address, especially in investigation of low failure rate crashes. There are times when the nodes causing the problem haven't been added to the trees, and times when we failed to generate a jitdump, or the jitdump is not generated in the right context. To be able to print other things like inlining table can also be helpful.

**Comment by pshipton** [comment]
@liqunl can you please give an IBM Java 8 build a try. I suspect it won't work either. Given that it doesn't work and nobody noticed until we raised this issue, it doesn't seem often used.

**Comment by liqunl** [comment]
> @liqunl can you please give an IBM Java 8 build a try. I suspect it won't work either. Given that it doesn't work and nobody noticed until we raised this issue, it doesn't seem often used.

Sorry for the late reply. I tried jextract on an IBM java 8 build, it is also broken. It is rarely used, maybe once a year for me. I notice that some of its functions can be found in other tools such as kca. Maybe it's ok for it to go

**Comment by TheMarvelFan** [comment]
Hi, is anyone working on this issue? If not then I would like to be work on this. I can submit a PR right away as well.

**Comment by dsouzai** [comment]
Hi @TheMarvelFan, no feel free to work on this. The `trprint` stuff in the JIT was removed years ago anyway.

**Comment by keithc-ca** [comment]
@TheMarvelFan We look forward to your contribution.

**Comment by TheMarvelFan** [comment]
Please review the PR and suggest changes if applicable

**Comment by keithc-ca** [comment]
Fixed via https://github.com/eclipse-openj9/openj9/pull/18230. Thanks, @TheMarvelFan.
