### ISSUE TITLE
Consider changing the default javasharedresources directory directly in $HOME

### ISSUE THREAD

**Issue by rubin55** [eclipse-openj9/openj9#11417]
I noticed that since 0.16 the shared cache is on by default (great!) but also that the default directory for the cache has been changed from /tmp/javasharedresources to $HOME/javasharedresources, for understandable reasons.

I and possibly many other Linux desktop users using OpenJ9 don't expect to find this directory directly in their home folder and I would ask to consider moving this directory to one of these locations:

    $HOME/.cache/javasharedresources
    $HOME/.local/share/javasharedresources

This way, the usage of this feature (now on by default) does not clutter up the users' home directory.

**Comment by pshipton** [comment]
@hangshao0 fyi

**Comment by hangshao0** [comment]
I am fine changing the default SCC directory to be a hidden directory, probably `$HOME/.javasharedresources` (avoid adding additional sub-directories). 

Another question is whether we want to do the same on Windows. I guess using `$HOME/.javasharedresources` on Windows should also be fine.

**Comment by hangshao0** [comment]
> Another question is whether we want to do the same on Windows...

Please ignore my Windows comment. The default SCC directory is different there.

**Comment by nicolaimainiero** [comment]
Will this change backported to be included in Release 0.26 for Java 8?

**Comment by pshipton** [comment]
Not sure it's high enough priority. @tajila
It's also an incompatible change which will abandon older caches files and require manual cleanup, although I expect that is just a release note.

We should consider adding a new variable that can be used in the cacheDir parameter. I note that variables like `%u` don't work there, only in the cacheName. Another variable like `%h` which expands to the home directory would allow users to specify different sub-directories.

**Comment by Mailaender** [comment]
Please adhere to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html which is using `$XDG_CACHE_HOME`.

**Comment by pshipton** [comment]
Moving forward.

**Comment by rubin55** [comment]
Just noticed 0.35 was released (read about it on Phoronix, congrats). But why is this issue not picked up? It's almost two years later! Would be rather great if this tidyness issue would get fixed sometime.

**Comment by hangshao0** [comment]
I will go ahead to change the default cache directory to a hidden directory. If the PR is merged, we need to include the change in the release note and update our documentation.
