### ISSUE TITLE
Enable Global Lock Reservation by Default

### ISSUE THREAD

**Issue by gita-omr** [eclipse-openj9/openj9#11424]
Currently, Global Lock Reservation can be enabled using -XX:+GlobalLockReservation and is not on by default. We would like to enable it by default on POWER.

**Comment by gita-omr** [comment]
@IBMJimmyk @vijaysun-omr @zl-wang  fyi

**Comment by 0xdaryl** [comment]
@gita-omr : will this still be happening for 0.25?  If not, let's move to 0.26.

**Comment by IBMJimmyk** [comment]
I'm actively working on this and currently in the middle of testing. Assuming nothing goes horribly wrong, this is still being targeted for 0.25.

**Comment by pshipton** [comment]
It's too late for 0.25 now, moving this forward.

**Comment by pshipton** [comment]
Is there any update on this? It's getting late to make big changes to the 0.26 release. Can we move this forward? Last update I see there was a problem identified with lock reservation enabled https://github.com/eclipse/openj9/pull/12125#issuecomment-792968917
@IBMJimmyk @zl-wang

**Comment by IBMJimmyk** [comment]
The problem hanging issue identified was fixed recently: https://github.com/eclipse/openj9/pull/12257

But, since there isn't a strong pressing need to enable GLR by default in 0.26, the plan is to wait until the next release to make the change instead of rushing it in.
