### ISSUE TITLE
Test Results for OpenJ9 JDK15/JDK16 with OpenJDK MethodHandles

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11458]
### 1. Instructions to build OpenJ9 JDK16 with OpenJDK MethodHandles

Get the JDK16 extensions repo: https://github.com/ibmruntimes/openj9-openjdk-jdk16 (default `openj9` branch)

Then, revert the commit from https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/9:
```
git revert 5d554a114d64937d59f432c5e0ac3b4e6e691531
```

Get the following OpenJ9 branch: https://github.com/babsingh/openj9/commits/ojdk_jsr292_final

Commits, from the **following unmerged PRs and branches**, are included in the above OpenJ9 branch:
1. ~https://github.com/eclipse/openj9/pull/10690~ (merged)
2. https://github.com/eclipse/openj9/pull/11261
3. ~https://github.com/eclipse/openj9/pull/11372~ (merged)
4. ~https://github.com/eclipse/openj9/pull/11371~ (replaced with https://github.com/eclipse/openj9/pull/11827)
5. ~https://github.com/eclipse/openj9/pull/11367~ (merged)
6. ~https://github.com/eclipse/openj9/pull/10607~ (merged)
7. ~https://github.com/eclipse/openj9/pull/11588~ (merged)
8. ~https://github.com/eclipse/omr/pull/5739~ (merged)

**Unaddressed issues:**
1. https://github.com/eclipse/openj9/pull/11715 ~https://github.com/eclipse/openj9/pull/11599~ (may be amended for the JIT; not critical for JDK16 since it is needed for JIT performance)
2. https://github.com/eclipse/openj9/issues/11580 (disable OpenJ9 VarHandle code; this should be quick; not critical since it will just be dead code if enabled)
3. https://github.com/eclipse/openj9/issues/11528 (HCR support; this will be important for functionality)

#### Build Commands:
```
bash ./configure --with-freemarker-jar=/root/freemarker.jar --enable-openjdk-methodhandles
make clean
make images
```

### 2. Download OpenJ9 JDK15 with OpenJDK MethodHandles for Linux x64

https://ibm.box.com/shared/static/1ge4sry9y1h2mg81ilpjcwpnrvqgdwyq.zip

### 3. Instructions to run sanity functional tests

**Test Reference:** https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

#### Test commands:
```
cd openj9/test
git clone https://github.com/AdoptOpenJDK/TKG.git
cd TKG
export TEST_JDK_HOME=<path to JDK directory that you wish to test>
export BUILD_LIST=functional
make compile
make _sanity.regular EXTRA_OPTIONS="-Xshare:off"
```

### 4. OpenJ9 JDK15 sanity.functional test results

**Log file** with the full sanity.functional test output: [test_sanity_regular_Xjit_shareoff_11Dec20.log](https://github.com/eclipse/openj9/files/5681585/test_sanity_regular_Xjit_shareoff_11Dec20.log).

#### Viewing errors in the log file:
```
grep -A10 FAILED: test_sanity_regular_Xjit_shareoff_11Dec20.log | less
```

The tests were run with the:
- **JIT enabled**
- **SCC disabled** `-Xshare:off` because corrupt bytecodes were encountered for hidden classes

#### Summary:
```
TOTAL: 191   EXECUTED: 137   PASSED: 110   FAILED: 27   DISABLED: 0   SKIPPED: 54
```

#### Failed test targets:
```
FAILED test targets:
        jit_jitt_0 [FIXED]
        jit_jitt_1 [FIXED]
        jit_jitt_2 [FIXED]
        jit_jitt_3 [FIXED]
        jit_jitt_openj9_none_SCC_0 [FIXED]
        jit_jitt_openj9_none_SCC_1 [FIXED]
        jit_jitt_openj9_none_SCC_2 [FIXED]
        jit_jitt_openj9_none_SCC_3 [FIXED]
        CondyPrimitive_1 [FIXED]
        Jep334Tests_0 [FIXED]
        JEP358NPEMessageTests_0 [FIXED]
        JEP358NPEMessageTests-noDebugInfo_0 [FIXED]
        jsr335_interfacePrivateMethod_1 [OLD]
        JCL_Test_0 [OLD]
        JCL_Test_1 [OLD]
        JCL_Test_2 [OLD]
        JCL_Test_none_SCC_0 [OLD]
        JCL_Test_none_SCC_1 [OLD]
        JCL_TEST_Java-Security_0 [OLD]
        jsr335tests_1 [OLD]
        jsr335tests_3 [OLD]
        jsr335tests_5 [OLD]
        jsr335tests_none_SCC_1 [OLD]
        jsr335tests_none_SCC_3 [OLD]
        jsr335tests_none_SCC_5 [OLD]
        cmdLineTester_CryptoTest_0 [OLD]
        ShareClassesCML_1 [OLD]
        cmdLineTester_GCRegressionTests_2 [NEW]
        cmdLineTester_GCRegressionTests_3 [NEW]
        testSCCMLModularity_1 [NEW]
```
#### Common error types:
1. `java.lang.AssertionError: expected [true] but found [false]`: incorrect test output.
2. The exception was thrown with the wrong message.
3. `java.lang.NoSuchMethodException` was thrown instead of `IllegalAccessException`.
4. Unexpected `java.lang.ArrayIndexOutOfBoundsException`. 
    - **Fix:** https://bugs.openjdk.java.net/browse/JDK-8259922
5. Unexpected `java.lang.IndexOutOfBoundsException: bad index: *`. 
    - **Fix:** https://bugs.openjdk.java.net/browse/JDK-8259922
6. Unexpected `java.lang.NoClassDefFoundError`.
7. Unexpected `java.lang.IllegalAccessException`.
8. Seg. faults seen during `jit_jitt_*` variants and `CondyPrimitive_1`.

**Comment by babsingh** [comment]
fyi @nbhuiyan @fengxue-IS @liqunl @DanHeidinga @tajila @0xdaryl @pshipton

**Comment by babsingh** [comment]
Thanks to @pshipton, we have a dry run for the OpenJ9 JDK15 nightly build with OpenJDK `MethodHandles` enabled:

https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-Personal/8

It uses the custom JDK15 extension and OpenJ9 branches; runs the `ppc64le_linux_ojdk292` SPEC, and `extended.functional` and `sanity.openjdk` test targets.

**Note:** Earlier, I had manually run the `_sanity.functional` test target.

**Comment by pshipton** [comment]
We won't be able to run too many of these builds. Because of all the test failures there are diagnostic files created and archived. It will eat up all the disk space if we run them nightly. Or we'll have to manually? clean up the artifacts from these builds periodically. @AdamBrousseau

**Comment by pshipton** [comment]
and actually https://ci.eclipse.org/openj9/computer/ub16p8j91/ ran out of space after running the openjdk tests and trying to zip up the results.

**Comment by AdamBrousseau** [comment]
I was thinking we could look at disabling the test archive for these specs temporarily. I will take a look at it.

**Comment by nbhuiyan** [comment]
The following failed targets are JIT-related as far as I know:
```
jit_jitt_0
jit_jitt_1
jit_jitt_2
jit_jitt_3
jit_jitt_openj9_none_SCC_0
jit_jitt_openj9_none_SCC_1
jit_jitt_openj9_none_SCC_2
jit_jitt_openj9_none_SCC_3
CondyPrimitive_1
```

All these failure happens due to the same reason - an illegal memory access in the VM when resolving invokedynamic. As a temporary solution around this problem while we work on fixing it, you may run the tests with this `-Xjit` option excluded from the command-line options: `rtResolve`.

**Comment by AdamBrousseau** [comment]
>disabling the test archive

Looks like the test script either upload to Jenkins or Artifactory
https://github.com/AdoptOpenJDK/openjdk-tests/blob/314dc7c35260354d60bf0455c54f9728be7aef12/buildenv/jenkins/JenkinsfileBase#L645-L651

Could be added but I don't think the test team wants another param. I haven't seen the OSU Art space increasing so is this needed or are we not running much yet?

**Comment by harryyu1994** [comment]
@babsingh Hi Babneet, I'm trying to get a build going to test my method handle AOT support code. The build instruction isn't very clear to me. It seems that this repo https://github.com/ibmruntimes/openj9-openjdk-jdk15/commits/ojdk_jsr292 is missing a lot things. How do you extend the changes in there to openj9-openjdk-jdk15?

**Comment by babsingh** [comment]
> @babsingh Hi Babneet, I'm trying to get a build going to test my method handle AOT support code. The build instruction isn't very clear to me. It seems that this repo https://github.com/ibmruntimes/openj9-openjdk-jdk15/commits/ojdk_jsr292 is missing a lot things. How do you extend the changes in there to openj9-openjdk-jdk15?

Discussed with @harryyu1994 via DM. The [builds instructions](https://github.com/eclipse/openj9/issues/11458#issue-762908255) are correct. They were misinterpreted.

**Comment by harryyu1994** [comment]
"SCC disabled -Xshare:off because corrupt bytecodes were encountered for hidden classes"
Does this mean I currently can't test MethodHandle AOT support?

**Comment by babsingh** [comment]
> SCC disabled -Xshare:off because corrupt bytecodes were encountered for hidden classes

https://github.com/eclipse/openj9/issues/11582 tracks the above issue. Currently, it only impacts `VarHandles` for which precompiled bytecodes are used. SCC works for `MethodHandles/VarHandles` for which bytecodes are generated during runtime. Instead of `-Xshare:off`, you can use `-Djava.lang.invoke.VarHandle.VAR_HANDLE_GUARDS=false` (alternate solution), which will prevent the usage of precompiled `VarHandle` bytecodes. The alternate solution will allow you to enable SCC with OJDK `MethodHandles/VarHandles` without any bytecode corruption.

**Comment by babsingh** [comment]
Built [openj9-openjdk-jdk16](https://github.com/ibmruntimes/openj9-openjdk-jdk16) with OJDK MH enabled.

The following `Jep334Tests_0` testcases pass, and NO longer fail with an **AssertionError**:
```
FAILED: testVarHandleDescribeConstableArray
FAILED: testVarHandleDescribeConstableInstanceField
FAILED: testVarHandleDescribeConstableStaticField
FAILED: testVarHandleHashCode
FAILED: testVarHandleDescResolveConstantDesc
```

**Comment by babsingh** [comment]
All the `[Array|]IndexOutOfBoundsExceptions` happen due to a bug in OJDK's [MethodHandles.collectArguments](https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/e5d124f5b22c2706a592002f304dbb749bc0da87/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L5731-L5758):
```
FAILED: test_CollectArgumentsNegative
FAILED: test_VoidCollectArgumentsNegative
```
As per the Javadoc for [MethodHandles.html#collectArguments](https://download.java.net/java/early_access/jdk16/docs/api/java.base/java/lang/invoke/MethodHandles.html#collectArguments(java.lang.invoke.MethodHandle,int,java.lang.invoke.MethodHandle)), an `IllegalArgumentException` should be thrown if `pos is not between 0 and the target's arity`.

OpenJ9's implementation of [MethodHandles.collectArguments](https://github.com/eclipse/openj9/blob/a6756ee754d759604d2163f5daa65a4f9c2beed2/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L3664-L3692) correctly throws the `IllegalArgumentException`. But, OJDK MH code throws an `[Array|]IndexOutOfBoundsException`. This also happens in the RI. @tajila To address this bug, do we need to open an issue in https://bugs.openjdk.java.net?

**Comment by babsingh** [comment]
> The exception was thrown with the wrong message: expected "Cannot invoke "java.lang.invoke.MethodHandle.invoke\(java.lang.String\)"" but got "null

The below testcases are failing because `the correct exception was thrown but with the wrong message`:

```
FAILED: test_MHinvoke
FAILED: test_MHinvokeExact
FAILED: test_invokehandle
FAILED: test_invokehandlegeneric
```

`RI`, `OpenJ9` and `OpenJ9 with OJDK MH enabled`: All throw a NPE without a message. So, the above testcases should be updated to avoid the `exception message check`.

**Comment by babsingh** [comment]
@JasonFengJ9 Referring to https://github.com/eclipse/openj9/issues/11458#issuecomment-757020239, what changes will be required to get [JEP358](https://github.com/eclipse/openj9/issues/8450) to work with OJDK MHs?

**Comment by tajila** [comment]
> To address this bug, do we need to open an issue in https://bugs.openjdk.java.net?

Yes, we will need to do that.

**Comment by JasonFengJ9** [comment]
> Referring to #11458 (comment), what changes will be required to get JEP358 to work with OJDK MHs?

@babsingh `OJDH MHs` seem work differently, it will need some investigation to determine how to generate proper `NPE` message in this scenario.

**Comment by nbhuiyan** [comment]
These were the failing test targets due to the JIT:
```
jit_jitt_0
jit_jitt_1
jit_jitt_2
jit_jitt_3
jit_jitt_openj9_none_SCC_0
jit_jitt_openj9_none_SCC_1
jit_jitt_openj9_none_SCC_2
jit_jitt_openj9_none_SCC_3
CondyPrimitive_1
```
All these failed test targets have been fixed via #11638 and updates in #10607.

**Comment by JasonFengJ9** [comment]
Updates about NPE message failure:

> The exception was thrown with the wrong message: expected "Cannot invoke "java.lang.invoke.MethodHandle.invoke(java.lang.String)"" but got "null

For a testcase code snippet
```
String msg = null;
MethodHandle mh = MethodHandles.lookup().findVirtual(String.class, "length", MethodType.methodType(int.class));
mh.invoke(msg);
```

Current `OpenJ9` NPE message output:
```
java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.invoke(java.lang.String)"
	at a.se.java_lang_npe.TestMHNPE.testAll(TestMHNPE.java:18)
```

`RI` output:
```
java.lang.NullPointerException
	at a.se.java_lang_npe.TestMHNPE.testAll(TestMHNPE.java:18)
```
Note it throws NPE without a message even with `-XX:+ShowCodeDetailsInExceptionMessages`.

OpenJ9 JDK15 with OpenJDK MethodHandles has following output:
```
java.lang.NullPointerException:
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
	at a.se.java_lang_npe.TestMHNPE.testAll(TestMHNPE.java:18)
```
Note an NPE is thrown without the message, also there are extra stack frames.

The NPE occurred at `10 JBinvokestatic 9 java/lang/invoke/MethodHandle.linkToVirtual(Ljava/lang/Object;Ljava/lang/invoke/MemberName;)I`, it was not expected that `JBinvokestatic` will cause NPE hence no message generated.
The code in question is https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/0e6bc58a452ae30017ccc132cc1767c70a762782/src/java.base/share/classes/java/lang/invoke/MethodHandle.java#L573
@gacholio expect the NPE was thrown internally without modifying the stack, so it appears to be coming from the `invokestatic`. So this will crash if the calling method above is jitted (Verified that `-Xjit:count=0` indeed crashed with this testcase).
fyi @babsingh @fengxue-IS 

On the other hand, adding NPE message generation for `JBinvokestatic` can give a message
```
java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, java.lang.invoke.MemberName)" because "<parameter1>" is null
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke_MT(LambdaForm$MH)
	at a.se.java_lang_npe.TestMHNPE.testAll(TestMHNPE.java:18)
```

**Comment by JasonFengJ9** [comment]
Further update:

Created a branch [1] `ojdk_jsr292_final_npe` from [2], added two commits, one was cherry-picked from https://github.com/eclipse/openj9/pull/11646, the other is newly introduced for `ojdk_jsr292_final` to adjust the expected NPE test message.
Verified that `JEP358NPEMessageTests_0` passes with `ojdk_jsr292_final_npe` build.

fyi @babsingh  

[1] https://github.com/JasonFengJ9/openj9/tree/ojdk_jsr292_final_npe
[2] https://github.com/babsingh/openj9/commits/ojdk_jsr292_final

**Comment by harryyu1994** [comment]
```
git clone git@github.com:ibmruntimes/openj9-openjdk-jdk15.git
git checkout ojdk_jsr292
bash get_source.sh
cd openj9
git remote add babsingh git@github.com:babsingh/openj9.git
git fetch babsingh
git checkout ojdk_jsr292_final
cd ../
cd omr
git checkout 99816ca57e98cad096119d606a9a2ea6148cb1bc
cd ../
bash ./configure --with-freemarker-jar=/root/freemarker.jar --with-boot-jdk=/root/bootjdk14 --enable-openjdk-methodhandles
make clean
make images
cd openj9/test
git clone https://github.com/AdoptOpenJDK/TKG.git
cd TKG
export TEST_JDK_HOME=/root/Harry_MethodHandle/openj9-openjdk-jdk15/build/linux-x86_64-server-release/images/jdk
export BUILD_LIST=functional
make compile
make _sanity.regular EXTRA_OPTIONS="-Xshare:off"
```
- here are the steps that I tried. During `make compile` I'm seeing the following crash. So the javac compiler is crashing I'm guessing?
```
Unhandled exception
Type=Segmentation error vmState=0x000501ff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FDF7D059F30 Handler2=00007FDF7C438860 InaccessibleAddress=0000000000000000
RDI=00007FDF2040B000 RSI=0000000000207600 RAX=0000000000000000 RBX=00007FDF58FE3FE0
RCX=00007FDF2040B0B0 RDX=00007FDF2040B0B0 R8=0000000000000000 R9=0000000000000000
R10=0000000000000002 R11=0000000000000001 R12=00007FDF204A8730 R13=0000000000000001
R14=0000000000000000 R15=00007FDF7711D710
RIP=00007FDF76662D9C GS=0000 FS=0000 RSP=00007FDF58FE2CE0
EFlags=0000000000010206 CS=0033 RBP=0000000000000000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
xmm0 0100240c000829a6 (f: 534950.000000, d: 7.355288e-304)
xmm1 0000026801000c00 (f: 16780288.000000, d: 1.307158e-311)
xmm2 000829ba0002026e (f: 131694.000000, d: 1.135204e-308)
xmm3 03000000000829d4 (f: 534996.000000, d: 3.131513e-294)
xmm4 0100000000082996 (f: 534934.000000, d: 7.291122e-304)
xmm5 0000000101000c00 (f: 16780288.000000, d: 2.130286e-314)
xmm6 0000000000000003 (f: 3.000000, d: 1.482197e-323)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 00007fdf2050dbb0 (f: 542170048.000000, d: 6.946380e-310)
xmm9 00007fdf2050e7f0 (f: 542173184.000000, d: 6.946380e-310)
xmm10 00007fdf2050fb70 (f: 542178176.000000, d: 6.946380e-310)
xmm11 00007fdf20540d50 (f: 542379328.000000, d: 6.946380e-310)
xmm12 00007fdf20543d10 (f: 542391552.000000, d: 6.946380e-310)
xmm13 00007fdf20501510 (f: 542119168.000000, d: 6.946380e-310)
xmm14 00007fdf20502c30 (f: 542125120.000000, d: 6.946380e-310)
xmm15 00007fdf20503770 (f: 542128000.000000, d: 6.946380e-310)
Module=/root/Harry_MethodHandle/openj9-openjdk-jdk15/build/linux-x86_64-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
Module_base_address=00007FDF76462000

Method_being_compiled=java/lang/reflect/AccessibleObject.checkAccess(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;I)V
Target=2_90_20210113_000000 (Linux 4.4.0-197-generic)
CPU=amd64 (8 logical CPUs) (0x2eeeaf000 RAM)
----------- Stack Backtrace -----------
(0x00007FDF76662D9C [libj9jit29.so+0x200d9c])
(0x00007FDF76664E88 [libj9jit29.so+0x202e88])
(0x00007FDF7665229B [libj9jit29.so+0x1f029b])
(0x00007FDF766533E7 [libj9jit29.so+0x1f13e7])
```

**Comment by nbhuiyan** [comment]
@harryyu1994 , when you posted the comment, Babneet's `ojdk_jsr292_final` branch was not up to date with the latest JIT fixes that should have prevented that crash. I think it has since been updated. @babsingh , correct me if I am wrong.

**Comment by babsingh** [comment]
@nbhuiyan I have DM'ed @harryyu1994. The latest `ojdk_jsr292_final` was probably not used. I have also suggested using [JDK16 extensions repo](https://github.com/ibmruntimes/openj9-openjdk-jdk16), which was newly created, since we plan to enable OJDK MH/VH in JDK16. Today, I successfully compiled the `functional tests` using JDK16 + the latest `ojdk_jsr292_final`.

**Comment by babsingh** [comment]
In regards to [Update NPE message for OpenJ9 with OpenJDK MethodHandles](https://github.com/JasonFengJ9/openj9/commit/0a3ca4463d72e7338344b203d16aa17190e0a7f2), 
```
/* OpenJ9 MH */ @Test(expectedExceptions = NullPointerException.class, expectedExceptionsMessageRegExp = "Cannot invoke \"java.lang.invoke.MethodHandle.invokeExact\\(java.lang.String\\)\"")
/* OJDK MH   */ @Test(expectedExceptions = NullPointerException.class, expectedExceptionsMessageRegExp = "Cannot invoke \"java.lang.invoke.MethodHandle.linkToVirtual\\(java.lang.Object, java.lang.invoke.MemberName\\)\" because \"<parameter1>\" is null")
```

In the `@Test` annotation, the `expectedExceptionsMessageRegExp` attribute accepts a regex. So, `expectedExceptionsMessageRegExp="<OPENJ9_MSG>|<OJDK_MSG>` will work with both OpenJ9 and OJDK MHs. @JasonFengJ9 Can we merge the above test changes by converting them into a regex? 

@llxia Is there an example where a regex is used in the `expectedExceptionsMessageRegExp` attribute of the `@Test` annotation?

**Comment by JasonFengJ9** [comment]
> Can we merge the above test changes by converting them into a regex?

Yeah, that's an option to accommodate both `master` and `ojdk_jsr292_final` branches. Will create a PR for it.

Just a side note https://github.com/eclipse/openj9/issues/11458#issuecomment-759525175, there are extra stack frames for `ojdk_jsr292` enabled JVM though the test message can be updated according to late `ojdk_jsr292` changes if required.

**Comment by fengxue-IS** [comment]
Closing this issue as all test failures mentioned in this issue has been resolved or tracked under a separate issue. The build instructions described in the issue detail no longer apply as OJDK MH is enabled by default in Java 16 master branch and openj9-staging branch for Java 17
