### ISSUE TITLE
jdk_security3 test failed with error `Could not sign data`

### ISSUE THREAD

**Issue by LongyuZhang** [eclipse-openj9/openj9#11500]
jdk_security3 failed subtest `SignatureTestPSS` and `SignatureTest2` on openj9 both 8 and 11, with the error of `Could not sign data`. These two tests passed for hotspot.
- SignatureTestPSS on openj9 failure link: [here](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5513/testReport/junit/sun_security_rsa_pss_SignatureTestPSS/java/SignatureTestPSS/)
- SignatureTest2 on openj9 failure link: [here](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5513/testReport/junit/sun_security_rsa_pss_SignatureTest2/java/SignatureTest2/)
- SignatureTestPSS on hotspot pass link:[here](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5511/testReport/sun_security_pkcs11_Signature_SignatureTestPSS/)
- SignatureTest2 on hotspot pass link:[here](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5511/testReport/sun_security_rsa_pss_SignatureTest2/)

Failure output (captured from console output):
```
     -classpath /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16081465941565/jdk_security3_0/work/classes/0/sun/security/rsa/pss/SignatureTestPSS.d:/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/test/jdk/sun/security/rsa/pss:/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16081465941565/jdk_security3_0/work/classes/0/test/lib:/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/jtreg.jar \
14:47:13          SignatureTestPSS 1025
14:47:13  STDERR:
14:47:13  java.lang.RuntimeException: java.security.SignatureException: Could not sign data
14:47:13  	at SignatureTestPSS.lambda$test$1(SignatureTestPSS.java:103)
14:47:13  	at SignatureTestPSS$$Lambda$449/0x0000000000000000.accept(Unknown Source)
14:47:13  	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
14:47:13  	at SignatureTestPSS.lambda$test$2(SignatureTestPSS.java:96)
14:47:13  	at SignatureTestPSS$$Lambda$448/0x0000000000000000.accept(Unknown Source)
14:47:13  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
14:47:13  	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
14:47:13  	at SignatureTestPSS.lambda$test$3(SignatureTestPSS.java:95)
14:47:13  	at SignatureTestPSS$$Lambda$447/0x0000000000000000.accept(Unknown Source)
14:47:13  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
14:47:13  	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
14:47:13  	at SignatureTestPSS.test(SignatureTestPSS.java:94)
14:47:13  	at SignatureTestPSS.main(SignatureTestPSS.java:88)
14:47:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:47:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:47:13  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:47:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
14:47:13  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
14:47:13  	at java.base/java.lang.Thread.run(Thread.java:836)
14:47:13  Caused by: java.security.SignatureException: Could not sign data
14:47:13  	at java.base/sun.security.rsa.RSAPSSSignature.engineSign(RSAPSSSignature.java:374)
14:47:13  	at java.base/java.security.Signature$Delegate.engineSign(Signature.java:1404)
14:47:13  	at java.base/java.security.Signature.sign(Signature.java:713)
14:47:13  	at SignatureTestPSS.checkSignature(SignatureTestPSS.java:172)
14:47:13  	at SignatureTestPSS.lambda$test$1(SignatureTestPSS.java:98)
14:47:13  	... 18 more
14:47:13  Caused by: javax.crypto.BadPaddingException: RSA private key operation failed
14:47:13  	at java.base/sun.security.rsa.NativeRSACore.crtCrypt_Native(NativeRSACore.java:149)
14:47:13  	at java.base/sun.security.rsa.NativeRSACore.rsa(NativeRSACore.java:91)
14:47:13  	at java.base/sun.security.rsa.RSACore.rsa(RSACore.java:149)
14:47:13  	at java.base/sun.security.rsa.RSAPSSSignature.engineSign(RSAPSSSignature.java:371)
14:47:13  	... 22 more
14:47:13  
14:47:13  JavaTest Message: Test threw exception: java.lang.RuntimeException
14:47:13  JavaTest Message: shutting down test
```

Related Issue: https://github.com/eclipse/openj9/issues/10757

**Comment by pshipton** [comment]
@LongyuZhang can you please try running the test (and any other crypto failures) with `-Djdk.nativeCrypto=false` to see if the failure is caused by the OpenSSL supported added in the extensions repos.

**Comment by LongyuZhang** [comment]
@pshipton The test passed with adding `-Djdk.nativeCrypto=false` on xlinux with jdk11 openj9, Internal_Grinder 12787 (the other two failures are for both hotspot and openj9, in another [issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2123)). I will test more on other platforms, and for other security tests too. Thanks a lot!

**Comment by pshipton** [comment]
Note there are other related issues being fixed already https://github.com/eclipse/openj9/issues/11391 https://github.com/eclipse/openj9/issues/11390, not sure if that fix will resolve these failures.
@ashbm5 @samasri fyi

**Comment by pshipton** [comment]
Actually those others are jdk16 related and this is jdk11 so I expect it's a different problem.

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by ashbm5** [comment]
@shanchao95 please have a look

**Comment by vij-singh** [comment]
@pshipton As discussed, is 0.26.0 more appropriate?

**Comment by pshipton** [comment]
It's always more desirable to fix problems sooner rather than later, and there is still some time for lower risk changes in 0.25. The problem is not yet understood so the severity is unclear. That said, there is no indication this problem is a regression and may have always occurred.

**Comment by pshipton** [comment]
It's too late for 0.25, moving this forward.

**Comment by ashbm5** [comment]
@pshipton please move to next release, we have the code for it but still require a security evaluation before we can commit.

**Comment by samasri** [comment]
The error was happening in the verification step at the end of the RSADP operation. Specifically, we were calling `OSSL_RSA_public_decrypt`, which pads the result in certain cases. This padded result would not match the original message.

To solve this we replace that verify operation with new code that operates directly on the BIGNUMs where there is no padding.

**Comment by pshipton** [comment]
@samasri @ashbm5 is there any outlook for porting https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/404 to other versions?

**Comment by samasri** [comment]
Yes, I will port it on ibmruntimes/openj9-openjdk-jdk, ibmruntimes/openj9-openjdk-jdk8, and ibmruntimes/openj9-openjdk-jdk16.

**Comment by pshipton** [comment]
The fix is delivered for all versions.
