### ISSUE TITLE
Balanced gc can not auto expansion region size

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#11548]
Java -version output
--------------------

```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Windows 7 amd64-64-Bit Compres
sed References 20201022_871 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10)
```

Summary of problem
------------------
Set " javaw -Xmx1G -Xgcpolicy:balanced -Xverbosegclog -verbose:gc -jar HMCL-3.3.170.jar" ,This [Launcher](https://github.com/huanghongxun/HMCL) can not show background picture.  When I set -Xmx2G or -Xgc:regionSize=2M, The Launcher can show background picture.
When user set -Xmx1G (no -Xms1G),maybe The GC do not try expansion region size. 
Set -Xgc:regionSize=8M can improve gc pause time When lancher minecraft and set balanced gc.

Diagnostic files
----------------
GClog:
[(-Xmx2g)verbosegc.20201229.113619.8276.zip](https://github.com/eclipse/openj9/files/5749525/-Xmx2g.verbosegc.20201229.113619.8276.zip)
[[set regionSize and 1G Xmx] verbosegc.zip](https://github.com/eclipse/openj9/files/5749526/set.regionSize.and.1G.Xmx.verbosegc.zip)
[[-Xmx1g]verbosegc.20201229.113726.10348.zip](https://github.com/eclipse/openj9/files/5749527/-Xmx1g.verbosegc.20201229.113726.10348.zip)

**Comment by dmitripivkine** [comment]
@amicic FYI

**Comment by 1a2s3d4f1** [comment]
![20201231141613469](https://user-images.githubusercontent.com/40121560/103399053-37d91900-4b7a-11eb-944e-fece12c20b01.jpg)
balanced gc
![20201231142113714](https://user-images.githubusercontent.com/40121560/103399073-4cb5ac80-4b7a-11eb-932f-64821e8a51d4.jpg)
g1gc or bananced gc set"-Xgc:regionSize=16M"

Hotspot G1GC log:
[gc.zip](https://github.com/eclipse/openj9/files/5756677/gc.zip)

**Comment by dmitripivkine** [comment]
@1a2s3d4f1 
Thank you for using OpenJ9!
Balanced GC selects default region size based on maximum heap size. The criteria is to have between 1024 to 2048 regions, but region size can not be smaller than 512k. 
The reason for lower performance with smaller region size most likely relates with need to use Discontiguous Arrays (aka Arraylets) for objects with size large than region size (so I guess there is a significantly lower number of arrays size exceeds 8m bytes vs 1m bytes)
We are working on this problem. Currently we do have an experimental solution for latest versions of Linux and OSX (but not Windows unfortunately). I would expect universal solution for all platforms in a few months time.
Also we are working on number of performance improvements for Balanced GC. This goal is to improve performance for Balanced GC by 15-20% in average in the Year 2021

**Comment by 1a2s3d4f1** [comment]
I try use balanced gc on large modpack, Maybe it is not region size problem. 

Large modpack gclog:

5mb region size:
[verbosegc.20210109.150515.6168.txt.gz](https://github.com/eclipse/openj9/files/5790294/verbosegc.20210109.150515.6168.txt.gz)

default region size:
[verbosegc.20210109.133755.3616.txt.gz](https://github.com/eclipse/openj9/files/5790295/verbosegc.20210109.133755.3616.txt.gz)

_Now that we have selected our desired GC policy and sized our heap, we need to tune the behavior of the garbage collector. Since we are using gencon, the heap will be divided up into a nursery space and a tenured space. For Minecraft, we need to take maximum advantage of the nursery space because Minecraft allocates lots of very short-lived objects, and collecting it is quite cheap compared to the full GC that is required to collect the tenured space.

The first major set of flags to concern ourselves with is the size of the nursery, controlled by -Xmns to set the initial size and -Xmnx for the maximum size. By default, -Xmns is 25% of -Xms and -Xmnx is 25% of -Xmx. As I said earlier, you will be setting -Xms and -Xmx to the same value. This means that by default, the nursery will never grow. Since Minecraft tends to allocate lots of very short-lived objects, this will result in very frequent garbage collections and will tenure garbage objects more often, degrading server performance.      form  https://steinborn.me/posts/tuning-minecraft-openj9 _

When I try set a big edan size ,The gc time is longer than default set(-Xmnx=25%Xmx).
Test on minecraft server.

Server gc log:
[verbosegc.20210109.154812.5592.txt.gz](https://github.com/eclipse/openj9/files/5790315/verbosegc.20210109.154812.5592.txt.gz)
1mb region size:
[verbosegc.20210109.155259.7028.txt.gz](https://github.com/eclipse/openj9/files/5790316/verbosegc.20210109.155259.7028.txt.gz)
512mb edan size:
[verbosegc.20210109.160100.4464.txt.gz](https://github.com/eclipse/openj9/files/5790318/verbosegc.20210109.160100.4464.txt.gz)
