### ISSUE TITLE
TestIBMJlm terminate() pid didn't work, manual cleanup required

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#11557]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_xl_Nightly_testList_1/29
TestIBMJlmRemoteClassNoAuth_SE80_Linux_0
I don't see anything useful in the diagnostics.
```
STF 00:38:22.479 - Killing processes: LT2
STF 00:38:22.479 -   o Process LT2 pid 31070 stop()
STF 00:38:32.483 -   o Process LT2 pid 31070 terminate()
STF 00:38:42.490 -   o Process LT2 terminate() pid 31070 didn't work, manual cleanup required
**FAILED** at step 8 (Stop LT2 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../TKG/test_output_16097328052738/TestIBMJlmRemoteClassNoAuth_SE80_Linux_0/20210104-003753-TestIBMJlmRemoteClassNoAuth/execute.pl line 307.
STF 00:38:42.698 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.system_x86-64_linux_Release_testList_0/8 - cent7-x64-4
TestJlmRemoteThreadAuth_1
```
STF 04:22:33.910 - +------ Step 6 - Stop LT1 process
STF 04:22:33.910 - | Kill running processes
STF 04:22:33.910 - |   Processes: [LT1]
STF 04:22:33.910 - |
STF 04:22:33.910 - Killing processes: LT1
STF 04:22:33.910 -   o Process LT1 pid 8432 stop()
STF 04:22:43.969 -   o Process LT1 pid 8432 terminate()
STF 04:22:53.973 -   o Process LT1 terminate() pid 8432 didn't work, manual cleanup required
**FAILED** at step 6 (Stop LT1 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk16_j9_sanity.system_x86-64_linux_Release_testList_0/openjdk-tests/TKG/../TKG/output_16174306475047/TestJlmRemoteThreadAuth_1/20210403-041550-TestJlmRemoteThreadAuth/execute.pl line 193.
STF 04:22:54.341 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.system_x86-64_linux_Nightly_testList_1/8
TestJlmRemoteClassAuth_0
```
STF 05:33:27.692 - +------ Step 10 - Stop LT2 process
STF 05:33:27.692 - | Kill running processes
STF 05:33:27.692 - |   Processes: [LT2]
STF 05:33:27.692 - |
STF 05:33:27.693 - Killing processes: LT2
STF 05:33:27.693 -   o Process LT2 pid 5362 stop()
STF 05:33:37.698 -   o Process LT2 pid 5362 terminate()
STF 05:33:47.702 -   o Process LT2 terminate() pid 5362 didn't work, manual cleanup required
**FAILED** at step 10 (Stop LT2 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk16_j9_sanity.system_x86-64_linux_Nightly_testList_1/openjdk-tests/TKG/../TKG/output_16221914797427/TestJlmRemoteClassAuth_0/20210528-052203-TestJlmRemoteClassAuth/execute.pl line 345.
STF 05:33:47.776 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly_testList_1/172
TestJlmRemoteClassNoAuth_0

```
STF 02:48:56.573 - +------ Step 8 - Stop LT2 process
STF 02:48:56.573 - | Kill running processes
STF 02:48:56.573 - |   Processes: [LT2]
STF 02:48:56.573 - |
STF 02:48:56.573 - Killing processes: LT2
STF 02:48:56.573 -   o Process LT2 pid 15351 stop()
STF 02:49:06.647 -   o Process LT2 pid 15351 terminate()
STF 02:49:16.650 -   o Process LT2 terminate() pid 15351 didn't work, manual cleanup required
**FAILED** at step 8 (Stop LT2 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../TKG/output_16418814365093/TestJlmRemoteClassNoAuth_0/20220111-023809-TestJlmRemoteClassNoAuth/execute.pl line 315.
STF 02:49:16.701 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly_testList_1/204
TestIBMJlmRemoteClassAuth_SE80_0 `-Xjit -Xgcpolicy:gencon -Xnocompressedrefs`

```
STF 05:53:31.655 - +------ Step 6 - Stop LT1 process
STF 05:53:31.655 - | Kill running processes
STF 05:53:31.655 - |   Processes: [LT1]
STF 05:53:31.655 - |
STF 05:53:31.655 - Killing processes: LT1
STF 05:53:31.655 -   o Process LT1 pid 16908764 stop()
STF 05:53:41.656 -   o Process LT1 pid 16908764 terminate()
STF 05:53:51.656 -   o Process LT1 terminate() pid 16908764 didn't work, manual cleanup required
**FAILED** at step 6 (Stop LT1 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly_testList_1/aqa-tests/TKG/../TKG/output_16442961383884/TestIBMJlmRemoteClassAuth_SE80_0/20220208-055320-TestIBMJlmRemoteClassAuth/execute.pl line 195.
STF 05:53:51.700 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

tail 3.LT1.stdout
```
05:53:25.307 - Starting thread. Suite=0 thread=16
05:53:25.334 - Starting thread. Suite=0 thread=17
05:53:25.376 - Starting thread. Suite=0 thread=18
05:53:25.379 - Starting thread. Suite=0 thread=19
05:53:25.379 - Starting thread. Suite=0 thread=20
05:53:25.380 - Starting thread. Suite=0 thread=21
05:53:25.380 - Starting thread. Suite=0 thread=22
05:53:25.382 - Starting thread. Suite=0 thread=23
05:53:25.385 - Starting thread. Suite=0 thread=24
05:53:25.388 - Starting thread. Suite=0 thread=25
05:53:25.388 - Starting thread. Suite=0 thread=26
05:53:25.389 - Starting thread. Suite=0 thread=27
05:53:25.389 - Starting thread. Suite=0 thread=28
05:53:25.390 - Starting thread. Suite=0 thread=29
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_x86-64_linux_Nightly_testList_2/209
TestIBMJlmRemoteMemoryNoAuth_0
```
STF 00:54:00.703 -   o Process LT2 pid 14356 terminate()
STF 00:54:10.707 -   o Process LT2 terminate() pid 14356 didn't work, manual cleanup required
**FAILED** at step 8 (Stop LT2 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_linux_Nightly_testList_2/aqa-tests/TKG/../TKG/output_16457627147917/TestIBMJlmRemoteMemoryNoAuth_0/20220225-004203-TestIBMJlmRemoteMemoryNoAuth/execute.pl line 319.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_0/7
TestIBMJlmRemoteClassNoAuth_0 `-Xjit -Xgcpolicy:gencon -Xnocompressedrefs`

```
STF 15:07:20.951 -   o Process LT1 pid 16712098 terminate()
STF 15:07:30.951 -   o Process LT1 terminate() pid 16712098 didn't work, manual cleanup required
**FAILED** at step 4 (Stop LT1 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/../TKG/output_16461430206704/TestIBMJlmRemoteClassNoAuth_0/20220301-150643-TestIBMJlmRemoteClassNoAuth/execute.pl line 180.
STF 15:07:30.997 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly_testList_1/223
TestIBMJlmRemoteClassAuth_0
```
STF 12:06:19.986 - Killing processes: LT2
STF 12:06:19.986 -   o Process LT2 pid 16580716 stop()
STF 12:06:29.987 -   o Process LT2 pid 16580716 terminate()
STF 12:06:39.987 -   o Process LT2 terminate() pid 16580716 didn't work, manual cleanup required
**FAILED** at step 10 (Stop LT2 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly_testList_1/aqa-tests/TKG/../TKG/output_16467384818357/TestIBMJlmRemoteClassAuth_0/20220308-120546-TestIBMJlmRemoteClassAuth/execute.pl line 349.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_1/16/
TestIBMJlmRemoteClassNoAuth_1
```
STF 10:09:30.081 -   o Process LT2 pid 14876960 terminate()
STF 10:09:40.081 -   o Process LT2 terminate() pid 14876960 didn't work, manual cleanup required
**FAILED** at step 8 (Stop LT2 process). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_1/aqa-tests/TKG/../TKG/output_16469905907432/TestIBMJlmRemoteClassNoAuth_1/20220311-100901-TestIBMJlmRemoteClassNoAuth/execute.pl line 319.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly_testList_2/180
TestIBMJlmRemoteClassAuth_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly_testList_0/241/ - [p8-java1-ibm10](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm10)
TestIBMJlmRemoteClassAuth_SE80_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly/184 - [p8-java1-ibm09](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm09)
TestIBMJlmRemoteClassAuth_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_1/36
TestIBMJlmRemoteClassNoAuth_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly_testList_1/201
TestIBMJlmRemoteClassNoAuth_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly_testList_2/202
TestIBMJlmRemoteClassAuth_1

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly_testList_0/202
TestIBMJlmRemoteClassNoAuth_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_1/47 - [p8-java1-ibm11](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm11)
TestIBMJlmRemoteClassNoAuth_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_1/52
TestIBMJlmRemoteClassAuth_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly_testList_2/211
TestIBMJlmRemoteClassAuth_1

**Comment by pshipton** [comment]
@Mesbah-Alam is there anything that can be done to improve this, it occurs a lot on AIX.
@llxia fyi

**Comment by Mesbah-Alam** [comment]
This error is thrown from STF [here](https://github.com/adoptium/STF/blob/master/stf.core/scripts/stf/Commands.pm#L729) after the `kill` command to clean up sub-processes fails. 

All JLM tests under [aqa-systemtest](https://github.com/adoptium/aqa-systemtest/tree/master/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm) and [openj9-systemtest](https://github.com/eclipse-openj9/openj9-systemtest/tree/master/openj9.test.jlm/src/test.jlm.ibm/net/openj9/test/jlm) invoke the kill command via [test.doKillProcesses()](https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteClassAuth.java#L190). 

So, just excluding a particular JLM test (e.g. `TestIBMJlmRemoteClassAuth`) from playlist for AIX doesn't really make sense, as the same error can/should occur in other JLM tests on the AIX machines where `kill` isn't working. 

--- 

Looking at the result file in https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_2/56 didn't give any clue as to why the kill command fails so often on AIX in particular. 

I will investigate if there is a better way to kill a process on AIX than `kill`.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_1/59
TestIBMJlmRemoteClassAuth_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly_testList_0/274
TestIBMJlmRemoteClassNoAuth_0

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_2/69
TestIBMJlmRemoteClassAuth_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly_testList_2/283
TestIBMJlmRemoteClassAuth_1

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly_testList_0/73/
TestIBMJlmRemoteClassNoAuth_0

**Comment by Mesbah-Alam** [comment]
Since the failures are mostly on jlm class tests on AIX , it makes sense to exclude the related targets. Created PR for the exclude: https://github.com/adoptium/aqa-tests/pull/3722.

**Comment by Mesbah-Alam** [comment]
Made a change to stf (in my [branch](https://github.com/adoptium/STF/pull/128/files)) to make 5 attempts (instead of 1) at cleaning up sub-processes before giving up. Started a 20x grinder on [hyc Jenkins](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24475) - but it did not reproduce the failure scenario where `kill` fails. 

---

Hi @pshipton , Could we please start a [openj9-jenkins Grinder](https://openj9-jenkins.osuosl.org/job/Grinder) with similar inputs as the one [above](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24475/parameters)? We need following inputs: 

```
STF_OWNER_BRANCH=Mesbah-Alam:fix-kill-on-aix
PLATFORM=ppc64_aix
BUILD_LIST=system
TARGET=TestIBMJlmRemoteClassNoAuth_0
LABEL=p8-java1-ibm04 (or any previously failing machine) 
ITERATIONS=20
```

I am looking to reproduce the failing case where `kill` fails on attempt # 1 - and see if it works on any of the next 4 attempts.

**Comment by pshipton** [comment]
Created https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/865
20x on 4 machines (all that are free ATM)

**Comment by Mesbah-Alam** [comment]
Thanks @pshipton ! 

We have a case where the second attempt at cleaning up the child process worked while attempt # 1 failed: https://openj9-jenkins.osuosl.org/job/Grinder_iteration_1/64/console

```
16:19:02  STF 20:15:14.933 - Killing processes: LT2
16:19:02  STF 20:15:14.933 -   o Process clean up attempt 1 for LT2 pid 17498508
16:19:02  STF 20:15:14.933 -   o Process LT2 pid 17498508 stop()
16:19:12  STF 20:15:24.934 -   o Process LT2 pid 17498508 terminate()
16:19:24  STF 20:15:34.935 -   o Process clean up attempt 2 for LT2 pid 17498508
16:19:24  STF 20:15:34.935 -   o Process LT2 pid 17498508 stop()
16:19:26  STF 20:15:38.935 -   o Process LT2 pid 17498508 killed
16:19:26  STF 20:15:38.936 - EXECUTE stage completed
16:19:26  STF 20:15:39.218 - 
16:19:26  STF 20:15:39.218 - ====================   T E A R D O W N   ====================
16:19:26  STF 20:15:39.218 - Running teardown: perl /home/jenkins/workspace/Grinder_iteration_1/aqa-tests/TKG/../TKG/output_16542008891973/TestIBMJlmRemoteClassNoAuth_0/20220602-201450-TestIBMJlmRemoteClassNoAuth/tearDown.pl
16:19:26  STF 20:15:39.324 - TEARDOWN stage completed
16:19:26  STF 20:15:39.335 - 
16:19:26  STF 20:15:39.335 - =====================   R E S U L T S   =====================
16:19:26  STF 20:15:39.335 - Stage results:
16:19:26  STF 20:15:39.336 -   setUp:     pass
16:19:26  STF 20:15:39.336 -   execute:   pass
16:19:26  STF 20:15:39.336 -   teardown:  pass
16:19:26  STF 20:15:39.336 - 
16:19:26  STF 20:15:39.336 - Overall result: PASSED
16:19:26  
16:19:26  TestIBMJlmRemoteClassNoAuth_0_PASSED
```

**Comment by pshipton** [comment]
This should be resolved by https://github.com/adoptium/STF/pull/128, closing.
