### ISSUE TITLE
Add -Xtrace option to turn assertions into crashes

### ISSUE THREAD

**Issue by gacholio** [eclipse-openj9/openj9#11562]
This would be useful both when running the VM under a debugger and in the field.

Probably requires some interaction with OMR.

**Comment by pshipton** [comment]
@keithc-ca fyi

I'm not sure, perhaps this is already supported for specific asserts. You can use the `trigger` keyword to cause an `abort` or `sigsev` for specific tracepoints (`tpnid`), but not sure if an assertion qualifies.

https://www.eclipse.org/openj9/docs/xtrace/#trigger

**Comment by keithc-ca** [comment]
https://github.com/eclipse/openj9/issues/11562 fixes the documentation: the suboption is `segv`, not `sigsev`.

**Comment by gacholio** [comment]
@keithc-ca I think you posted an incorrect link above.
