### ISSUE TITLE
VarHandle MethodType lookup table not needed for OJDK MH

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11580]
`VarHandle MethodType lookup table` is stored in the `J9ROMClass`.

The code related to the `VarHandle MethodType lookup table` should be wrapped with `J9VM_OPT_METHOD_HANDLE` or an identical flag so that it stays disabled for OJDK MH.

The code related to the `VarHandle MethodType lookup table` is mentioned in the following comments:
1. https://github.com/eclipse/openj9/pull/11566#pullrequestreview-561367547
2. https://github.com/eclipse/openj9/pull/11566#issuecomment-754855484

**Comment by babsingh** [comment]
fyi @DanHeidinga @fengxue-IS @tajila
This issue needs to be tagged with `project:MH`.

**Comment by EricYangIBM** [comment]
I am unsure what to do for https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/optimizer/VarHandleTransformer.cpp#L295. That method is accessing the varhandlemethodtypelookuptable so I think some changes are necessary when ojdk method handles are enabled.

**Comment by fengxue-IS** [comment]
The first link code should be never used with ojdk MH enabled, so you should be able to ifdef the code block with `J9VM_OPT_METHOD_HANDLE`.
@nbhuiyan can you confirm that `VarHandleTransformer` functions are not used with ojdk MH, and if it is possible to ifdef them out when ojdk mh is enabled

for second link, you don't need to do anything as the code is already ifdef with `J9VM_OPT_OPENJDK_METHODHANDLE`

**Comment by nbhuiyan** [comment]
Yes, this is not used with ojdk MHs. We can safely ifdef out the entire body of `TR_VarHandleTransformer::perform()` (except return 0) in ojdk MH builds.
