### ISSUE TITLE
Missing break or fall through statements 

### ISSUE THREAD

**Issue by qarmin** [eclipse-openj9/openj9#11741]
There is no break so `isIndirectCall` is reassigned
https://github.com/eclipse-openj9/openj9/blob/8394cffecaf5ea67e60c837a3b8f27e8c7d5c290/runtime/compiler/optimizer/InterpreterEmulator.cpp#L444-L449

Also unlike here
https://github.com/eclipse-openj9/openj9/blob/a1cfdc2866fe91f5eb5d775ff58a47bd7687a723/runtime/compiler/p/codegen/J9TreeEvaluator.cpp#L8982-L8997
there is no break in this code
https://github.com/eclipse-openj9/openj9/blob/a1cfdc2866fe91f5eb5d775ff58a47bd7687a723/runtime/compiler/p/codegen/J9TreeEvaluator.cpp#L9540-L9554

**Comment by pshipton** [comment]
@0xdaryl fyi

**Comment by 0xdaryl** [comment]
There are two potential problems here in different areas of code.  @zl-wang, could you have someone look at the issue in the Power codegen?  @nbhuiyan : please look at the interpreter emulator code.

**Comment by nbhuiyan** [comment]
The `isIndirectCall` re-assignment issue in `InterpreterEmulator` was fixed through #13671.

**Comment by 0xdaryl** [comment]
This should be fixed for 0.38, awaiting testing for PR #16471 which slipped through the cracks.

**Comment by 0xdaryl** [comment]
I believe all testing has completed successfully with this one and it can be closed.

**Comment by 0xdaryl** [comment]
Closing per my previous comment.
