### ISSUE TITLE
Useless ternary operator in J9BCDTreeEvaluator.cpp

### ISSUE THREAD

**Issue by qarmin** [eclipse-openj9/openj9#11744]
https://github.com/eclipse-openj9/openj9/blob/a1cfdc2866fe91f5eb5d775ff58a47bd7687a723/runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp#L3921

**Comment by pshipton** [comment]
@joransiu fyi

**Comment by joransiu** [comment]
@VermaSh : fyi.

**Comment by VermaSh** [comment]
Thanks @qarmin for pointing this out. I have made the suggested edits [1]. Along with the suggested changes, the branch also includes few other improvements for those evaluators. I am testing the changes now, I'll open a PR once the tests pass [2]. 

[1] https://github.com/eclipse-openj9/openj9/compare/master...VermaSh:openj9:daa_suggested_improvements?expand=1 "Suggested changes"
[2] view/OpenJ9 - Personal/job/Pipeline-Build-Test-Personal/15220/ "Internal test build"

**Comment by 0xdaryl** [comment]
@VermaSh : is there an outlook on creating a PR for this for 0.38?

**Comment by VermaSh** [comment]
same as https://github.com/eclipse-openj9/openj9/issues/11745#issuecomment-1457055113
