### ISSUE TITLE
Always true expression in J9BCDTreeEvaluator.cpp

### ISSUE THREAD

**Issue by qarmin** [eclipse-openj9/openj9#11745]
https://github.com/eclipse-openj9/openj9/blob/cef51dfd748a15b6f8ceb9be065d8a9eb8389a6b/runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp#L7569

Every value is bigger than 0 and lower than 31.
`||` should be replaced with `&&`

**Comment by qarmin** [comment]
Still happens in master
https://github.com/eclipse-openj9/openj9/blob/7cafd4be861328726aee0f7666d683a2eb93ac84/runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp#L6363

**Comment by pshipton** [comment]
@0xdaryl fyi

**Comment by pshipton** [comment]
Rather, @joransiu fyi.

**Comment by joransiu** [comment]
@VermaSh : fyi.

**Comment by VermaSh** [comment]
Posted progress here https://github.com/eclipse-openj9/openj9/issues/11744#issuecomment-1370930433

**Comment by 0xdaryl** [comment]
@VermaSh : is there an outlook on this for 0.38?  Or should it be pushed out?

**Comment by VermaSh** [comment]
The personal build passed without failures. I just need to generate a trace log to verify that vector instructions are being generated. Should be able to verify by tomorrow end

**Comment by keithc-ca** [comment]
> Every value is bigger than 0 and lower than 31.

I don't understand that comment: that's what the assertion says, but in general a signed 32-bit value isn't confined to that range. I'm not sure what the author of this issue expects; I think this should just be closed.

**Comment by qarmin** [comment]
Condition is `(shiftAmount >=0 || shiftAmount <= 31)`

Let's use `int shiftAmount -100`, this returns true because `shiftAmount <= 31`
Let's use `int shiftAmount 11`, this returns true because `shiftAmount <= 31` and `shiftAmount >=0`
Let's use `int shiftAmount 33`, this returns true because `shiftAmount >=0`

**Comment by keithc-ca** [comment]
Yes, you're right, I didn't read the code carefully. I agree the condition should use `&&`:
```c
 TR_ASSERT((0 <= shiftAmount) && (shiftAmount <= 31)),"unexpected TR::pdshr shift amount of %d\n",shiftAmount); 
```
