### ISSUE TITLE
Assume TR::Compiler->cls.classesOnHeap() is always true

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#11791]
There are a number of places in the JIT guarded with `TR::Compiler->cls.classesOnHeap()`.  This query is hardcoded to always return `true`.  J9 classes have resided on the heap for many years now and this is unlikely to change.  I doubt this flexibility is still needed.

Assume `TR::Compiler->cls.classesOnHeap()` is always `true` and fold and remove code as necessary.

Leave the `classesOnHeap()` query in `env/J9ClassEnv.hpp` for now.  There is some re-work that needs to happen in the OMR project before it can be removed.

**Comment by 0xdaryl** [comment]
@gacholio @tajila : Just confirming that classes-on-heap is always true these day and the non-heap paths can be folded away in the JIT.  If not, we probably have JIT bugs lurking...

**Comment by gacholio** [comment]
Confirmed.

**Comment by gacholio** [comment]
For the record (flags in the core feature can not be overriden):

https://github.com/eclipse/openj9/blob/fb8c08c7db2038da0422689e8acf7e9191ec0aa6/buildspecs/core.feature#L50

**Comment by AhwiniMirajkar** [comment]
Can I work on this

**Comment by AhwiniMirajkar** [comment]
I'm new to open source contribution 
Could you help me 
How can I start the work and next steps

**Comment by gacholio** [comment]
Hopefully all of the instructions are here:

https://github.com/eclipse/openj9

**Comment by tajila** [comment]
@AhwiniMirajkar I would specifically look at:

https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V11.md#linux
https://github.com/eclipse/openj9/blob/master/test/README.md

That will give you instructions on how to build and test. Once you have implemented and tested your changes you'll look at the following to prepare your PR.

https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md
https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php

**Comment by singh264** [comment]
I think the caller method of the classesOnHeap method in the omr repository could be relevant https://github.com/singh264/omr/blob/refactor_classesOnHeap/compiler/compile/OMRSymbolReferenceTable.cpp#L1345.
