### ISSUE TITLE
Enable MethodHandlesPermuteArgumentsTest once OJDK MHs are enabled

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#11822]
[MethodHandlesPermuteArgumentsTest](https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/f28951c83db05bb661d5dbeef4684f47a4c44d61/test/jdk/java/lang/invoke/MethodHandlesPermuteArgumentsTest.java#L200-L228) passes with OJDK MHs enabled in OpenJ9. So, it should be enabled once OJDK MHs are officially enabled in OpenJ9. 

Related: https://github.com/eclipse/openj9/pull/11697#issuecomment-763282951

To enable the test, the line corresponding to `MethodHandlesPermuteArgumentsTest` should be removed from https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk16-openj9.txt.

**Comment by JasonFengJ9** [comment]
Verified that this test passes w/ recent JDK16/17 build
`Test_grinder/job/Grinder/17548`
```
11:20:02  openjdk version "16.0.2-internal" 2021-07-20
11:20:02  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.jenkins.BuildJDK16x86-64linuxPersonal)
11:20:02  Eclipse OpenJ9 VM (build master-b49892b0b23, JRE 16 Linux amd64-64-Bit Compressed References 20210813_281 (JIT enabled, AOT enabled)
11:20:02  OpenJ9   - b49892b0b23
11:20:02  OMR      - ac3ab4821a5
11:20:02  JCL      - 44316ee515b based on jdk-16.0.2+7)
```
`Test_grinder/job/Grinder/17549`
```
11:21:43  openjdk version "17-internal" 2021-09-14
11:21:43  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxPersonal)
11:21:43  Eclipse OpenJ9 VM (build master-b49892b0b23, JRE 17 Linux amd64-64-Bit Compressed References 20210813_41 (JIT enabled, AOT enabled)
11:21:43  OpenJ9   - b49892b0b23
11:21:43  OMR      - ac3ab4821a5
11:21:43  JCL      - b40e984c3a1 based on jdk-17+35)
```
Created PR (https://github.com/adoptium/aqa-tests/pull/2821) to re-enable the test.

closing..
