### ISSUE TITLE
OpenJDK jdk16 java/foreign/TestLibraryLookup.java expected [1] but found [0]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#11838]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_mac_Nightly/11
java/foreign/TestLibraryLookup.java
osx1014-x86-1
```
08:39:41  test TestLibraryLookup.testInvalidSymbolLookup(): failure
08:39:41  java.lang.AssertionError: expected [1] but found [0]
08:39:41  	at org.testng.Assert.fail(Assert.java:94)
08:39:41  	at org.testng.Assert.failNotEquals(Assert.java:496)
08:39:41  	at org.testng.Assert.assertEquals(Assert.java:125)
08:39:41  	at org.testng.Assert.assertEquals(Assert.java:372)
08:39:41  	at org.testng.Assert.assertEquals(Assert.java:382)
08:39:41  	at TestLibraryLookup.testInvalidSymbolLookup(TestLibraryLookup.java:84)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Nightly/13
cent7-x64-6
```
01:46:48  test TestLibraryLookup.testInvalidSymbolLookup(): failure
01:46:48  java.lang.AssertionError: expected [1] but found [0]
01:46:48  	at org.testng.Assert.fail(Assert.java:94)
01:46:48  	at org.testng.Assert.failNotEquals(Assert.java:496)
01:46:48  	at org.testng.Assert.assertEquals(Assert.java:125)
01:46:48  	at org.testng.Assert.assertEquals(Assert.java:372)
01:46:48  	at org.testng.Assert.assertEquals(Assert.java:382)
01:46:48  	at TestLibraryLookup.testInvalidSymbolLookup(TestLibraryLookup.java:84)
```

**Comment by pshipton** [comment]
@tajila someone should look at this intermittent failure

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this

**Comment by JasonFengJ9** [comment]
Sure, will look into this.

**Comment by JasonFengJ9** [comment]
It is ~2/100 failure rate.

**Comment by JasonFengJ9** [comment]
**Update:**

The intermittent failure is not related to native library loading or symbol lookup. 
This is a keepAlive problem. OpenJ9 aggressively allows objects to be GC'd when they are no longer referenced in the method.
Adding `Reference.reachabilityFence(lookup)`[1] within the test code passes 300x grinder while the failure rate was ~2/100.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/14/files

**Comment by pshipton** [comment]
Let's deliver that change to jdk16 and jdknext, and we can ask Andrew to contribute it to OpenJDK.

**Comment by ChengJin01** [comment]
Close this issue as this jtreg test suite was removed since JDK17 with all related APIs updated.
