### ISSUE TITLE
Mac libj9gc29.dylib: DW_DLE_VMM (9) dwarf format/library version mismatch

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#11834]
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_mac_OpenJDK/393
osx1014-x86-2
```
01:42:47  [100%] Generating /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/build/macosx-x86_64-server-release/vm/ddr_info/sets/j9ddr.macros
01:42:47  [100%] Generating /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/build/macosx-x86_64-server-release/vm/runtime/j9ddr.dat, /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/build/macosx-x86_64-server-release/vm/superset.dat
01:42:49  Error: /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/omr/ddr/lib/ddr-scanner/dwarf/DwarfScanner.cpp:1622 scanFile - Failed to initialize libDwarf scanning /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/build/macosx-x86_64-server-release/vm/runtime/libj9gc29.dylib.dSYM/Contents/Resources/DWARF/libj9gc29.dylib: DW_DLE_VMM (9) dwarf format/library version mismatch
```

**Comment by pshipton** [comment]
Happened again in the next build, guess it's not intermittent. A side affect of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/277 or something that changed in OpenJDK.
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_mac_OpenJDK/394

**Comment by pshipton** [comment]
Or likely caused by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/276. Created https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/278 to check.

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/278 didn't help.

**Comment by keithc-ca** [comment]
Expecting that the problem was related to a change in the format of the output of `dwarfdump-classic` (or `dwarfdump`) for `libj9gc29`, I did a build on an internal machine so I could examine `DWARF/libj9gc29.dylib` manually. That build succeeded, so I tried again on `osx1014-x86-2`; that build also succeeded. The same code paths are exercised (as far as DDR is concerned) for other Java versions which haven't failed this way. It's not clear what can be done until we have a copy of the offending library to inspect more closely.

**Comment by pshipton** [comment]
If nothing else, the script that gathers files for the diagnostics.tar.gz can be modified, and we can run the build again.

**Comment by keithc-ca** [comment]
> If nothing else, the script that gathers files for the diagnostics.tar.gz can be modified, and we can run the build again.

See #11847.

**Comment by keithc-ca** [comment]
`ddrgen` is choking on lines like this:
```
0x00045224:         Unknown DW_TAG constant: 0x48 [111]
```
It should probably just ignore them.

**Comment by keithc-ca** [comment]
Longer term we should add support and prefer to use the new `dwarfdump` utility because the compiler appears to be using tags introduced in DWARF version 5. The following contrasts the old and new presentations of the same tag from the same file.

`dwarfdump-classic`:
```
0x0004520f:     TAG_subprogram [110] *
                 AT_low_pc( 0x0000000000002b70 )
                 AT_high_pc( 0x00000009 )
                 AT_frame_base( rbp )
                Unknown DW_AT constant: 0x7a( true )
                 AT_name( "__cxa_pure_virtual" )
                 AT_decl_file( "/Users/jenkins/workspace/Build_JDKnext_x86-64_mac_Personal/openj9/runtime/util/cpplink.c" )
                 AT_decl_line( 38 )
                 AT_external( true )
                 AT_APPLE_optimized( true )

0x00045224:         Unknown DW_TAG constant: 0x48 [111]
                    Unknown DW_AT constant: 0x7f( {0x000451fa} )
                    Unknown DW_AT constant: 0x7d( 0x0000000000000009 )
```
`dwarfdump`:
```
0x0004520f:   DW_TAG_subprogram
                DW_AT_low_pc    (0x0000000000002b70)
                DW_AT_high_pc   (0x0000000000002b79)
                DW_AT_frame_base        (DW_OP_reg6 RBP)
                DW_AT_call_all_calls    (true)
                DW_AT_name      ("__cxa_pure_virtual")
                DW_AT_decl_file ("/Users/jenkins/workspace/Build_JDKnext_x86-64_mac_Personal/openj9/runtime/util/cpplink.c")
                DW_AT_decl_line (38)
                DW_AT_external  (true)
                DW_AT_APPLE_optimized   (true)

0x00045224:     DW_TAG_call_site
                  DW_AT_call_origin     (0x000451fa)
                  DW_AT_call_return_pc  (0x0000000000000009)
```
