### ISSUE TITLE
Consolidate definition of snprintf

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#11884]
There are several .cpp files that do
```
#if defined (_MSC_VER) && (_MSC_VER < 1900)
#define snprintf _snprintf
#endif
```
This is particularly frustrating because it means that anytime a new `snprintf` is added somewhere, the dev has to remember to add this definition. This should really be put in a single header somewhere that's visible to everyone.

**Comment by dsouzai** [comment]
jenkins test sanity win jdk8

**Comment by keithc-ca** [comment]
Perhaps we should consider using `omrstr_printf`?

**Comment by dsouzai** [comment]
Interesting, I'll look into that. Thanks @keithc-ca
