### ISSUE TITLE
Propagate workaround for #9416

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#11961]
This issue was created primarily as a reminder.

Unless #9416 is resolved in time for 0.25, the workaround that has been used in the previous two releases should be ported to the 0.25 release (see #11431).

Also, the diagnostic code added in #11871 should be reverted.

**Comment by Leonardo2718** [comment]
Note the changes from #11871 were reverted in https://github.com/eclipse/openj9/commit/a80e4fe10b when the branch was created.

**Comment by 0xdaryl** [comment]
Workaround delivered to 0.26.  Moving this to 0.27.

**Comment by 0xdaryl** [comment]
No longer required as failing compilation was made the permanent solution in master in #12259.
