### ISSUE TITLE
Add jit compile time helper to detect @stable annotation

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#11990]
The @stable (java/lang/invoke/Stable) annotation is used an indicator to the JIT that the first non-NULL value stored may be treated as a constant thus enabling constant folding. It behaves similar to final. One difference is that it can also be applied to arrays, meaning that all array elements may be constant folded as well. Currently the only usage of this annotation is in trusted (core JDK) code.

We will introduced a compile time jithelper to so the JIT can query if the field is annotated with @stable or not.

First we will add a VMHelper

//@param clazz, the class that own the field
//@param the cpindex of the field to query
//@return true, if stable, false otherwise
BOOLEAN
isFieldStable(J9Class clazz, UDATA cpIndex);

Take a look at `dumpAnnotationInfo` in rcdump.c to see how to look up field annotations.
To find the name of the field given a cpIndex `romFieldRef = (J9ROMFieldRef *)&clazz->ramConstantPool->romConstantPool[cpIndex];`

Compile time helpers are stored in cthelpers.cpp

Note: if the static type of the field is an array, then that means all the array elements are considered to be stable. The VM will not do anything special for this. The JIT can recognize this by looking at the static type info.

**Comment by tajila** [comment]
@gita-omr ^^

**Comment by sharon-wang** [comment]
I'll take a look at this!
