### ISSUE TITLE
Add jit compile helper time to detect @ForceInline annotation

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#11993]
The @ForceInline (jdk.internal.vm.annotation.ForceInline) will be used to notify the JIT that the method will benefit from inlining. 

We will introduce a compile time jithelper to so the JIT can query if the method is annotated with @ForceInline or not.

First we will add a VMHelper

//@param clazz, the class that own the field
//@param the cpindex of the method to query
//@return true, if forceinline, false otherwise
BOOLEAN
isMethodTaggedForForceInline(J9Class clazz, UDATA cpIndex);

Take a look at dumpAnnotationInfo in rcdump.c to see how to look up method annotations.
To find the name of the field given a cpIndex romFieldRef = (J9ROMMethodRef *)&clazz->ramConstantPool->romConstantPool[cpIndex];

Compile time helpers are stored in cthelpers.cpp

**Comment by tajila** [comment]
@gita-omr ^^

**Comment by sharon-wang** [comment]
I'll take a dive into this

**Comment by fjeremic** [comment]
See related #2076 which talks about `@HotSpotIntrinsicCandidate`. I would love to see this made available as well.

**Comment by fjeremic** [comment]
Also unfortunate for @forceinline 😅 I wonder how often he gets accidentally tagged in issues.

**Comment by r30shah** [comment]
> See related #2076 which talks about @HotSpotIntrinsicCandidate. I would love to see this made available as well (perhaps @OpenJ9IntrinsicCandidate?). Also may I suggest a slight change to the name:

I am experimenting with certain methods which are tagged with `@IntrinsicCandidate` and was adding those to list of methods calls for which I can skip HCR guards in the compiled code. It would be nice if we have jit compiler helper that can process such tags as well. I would make JIT compiler code cleaner.

**Comment by gita-omr** [comment]
@tajila could we resume the discussion on what exactly is needed to implement this?

**Comment by tajila** [comment]
We would need to know the defining class and the method name (or moethodref). Essentially, we need to know which implementation the JIT is referring to.

The challenge is that in polymorhpic callsites there is no way to determine this statically.

**Comment by gita-omr** [comment]
Right. I was thinking that sometimes we try to de-virtualize a call but not necessarily inline in it. At this point, we could check the annotation. Then, we could provide the exact class of the object on which we are invoking the method(might not be the one that have the method implementation though, but some of its parents would).

**Comment by gita-omr** [comment]
Not sure we can find the defining class... I think it might be derived class that uses definition of some parent class...

**Comment by gita-omr** [comment]
@tajila Please see my previous comment

**Comment by tajila** [comment]
for @forceinline we know that the annotation is always going to be on a final or static method. This means that if you devirtualize a callsite you can always know query the correct method

**Comment by forceinline** [comment]
> Also unfortunate for @forceinline 😅
> I wonder how often he gets accidentally tagged in issues.

too often 😔

**Comment by tajila** [comment]
sorry about that

**Comment by gita-omr** [comment]
> or `@forceinline` we know that the annotation is always going to be on a final or static method. This means that if you devirtualize a callsite you can always know query the correct method. If pass the VM the implemenation method then we will always be able to respond with the correct answe

Ok,  will need to double check, but let's assume that for now.
