### ISSUE TITLE
win2012-x86-4 offline again

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12014]
@jdekonin

**Comment by jdekonin** [comment]
System is online and cleaned up.

**Comment by pshipton** [comment]
and win2012-x86-4 is offline again.

**Comment by jdekonin** [comment]
Cleaned up and rebooted, its online again in jenkins and taking jobs.

**Comment by pshipton** [comment]
@jdekonin it needs a reboot again, it's hung. This machine seems fairly useless.
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_OMR/840/console

**Comment by jdekonin** [comment]
From the job history the last job running on this system was this one.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_Nightly/313/console

It is marked as aborted and I'm guessing at the stage this test job was at maybe its not cleaning up correctly???

Attempting to access the workspace folder hangs the session.  There is still a curl process running as well.  Attempting manual cleanup failed so I rebooted then cleaned up.

**Comment by jdekonin** [comment]
Machine appears to be pretty solid for the past 2 months.  Closing.
