### ISSUE TITLE
AArch64: Implement allocation prefetching

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#12068]
Implement support for prefetching subsequent lines of the TLH during an inlined allocation (new, anewarray, newarray).  This would be enabled via `enableTLHPrefetching`.  This will benefit applications with a high rate of allocations.

Estimated performance improvement to be about 2%.

**Comment by knn-k** [comment]
I think this issue can be closed now.
#12348 enabled allocation prefetching on AArch64.
