### ISSUE TITLE
AArch64: Implement fast System.arraycopy

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#12122]
Implement a primitive and reference version of `System.arraycopy` that does not involve calling the Java JNI native.

Consider optimizations such as inlining constant length copies in JITed code to improve performance.

**Comment by knn-k** [comment]
Related Issue: #6438

**Comment by knn-k** [comment]
Primitive and reference arraycopy has been implemented and enabled for AArch64.
