### ISSUE TITLE
ValueTypes: checkcast behaviour

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#12130]
The following bytecodes trigger NoClassDef exception on J9. However on the RI it throws an NPE.

```    
Code:
       0: aconst_null
       1: checkcast     #54                 // class "QClassDoesNotExist;"
       4: areturn
```

We need to change the behaviour so it matches RI, we also need to make sure we do the right thing when classref is ` "QClassDoesNotExist;"` and reciever is not NULL

**Comment by gacholio** [comment]
Are we sure the RI behaviour is correct?

**Comment by theresa-m** [comment]
This can be closed since Q types are gone.
