### ISSUE TITLE
Failures caused by "Unable to find image 'adoptopenjdk-example-test:latest' locally"

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#12150]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.external_s390x_linux/2`
rebuild the failed tests in one link:
23:05:50  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=external&PLATFORM=s390x_linux_mixed&TARGET=testList%20TESTLIST=example-test_0,tomee_test_j9_0,quarkus_quickstarts_test_0,openliberty_microprofile_tck_jdk8_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:05:36  { itercnt=1; \
23:05:36  mkdir -p "/home/jenkins/workspace/Test_openjdk8_j9_sanity.external_s390x_linux/openjdk-tests/TKG/../TKG/output_1615003533246/example-test_0"; \
23:05:36  cd "/home/jenkins/workspace/Test_openjdk8_j9_sanity.external_s390x_linux/openjdk-tests/TKG/../TKG/output_1615003533246/example-test_0"; \
23:05:36  docker run --rm -v /home/jenkins/workspace/Test_openjdk8_j9_sanity.external_s390x_linux/openjdkbinary/j2sdk-image:/opt/java/openjdk adoptopenjdk-example-test:latest ; \
23:05:36  		if [ $? -eq 0 ] ; then echo ""; echo "example-test_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk8_j9_sanity.external_s390x_linux/openjdk-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk8_j9_sanity.external_s390x_linux/openjdk-tests/TKG/../TKG/output_1615003533246/example-test_0"; else echo ""; echo "example-test_0""_FAILED"; echo ""; fi; \
23:05:36  		docker rmi -f adoptopenjdk-example-test; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk8_j9_sanity.external_s390x_linux/openjdk-tests/TKG/../TKG/output_1615003533246/TestTargetResult";
23:05:36  Unable to find image 'adoptopenjdk-example-test:latest' locally
23:05:37  docker: Error response from daemon: pull access denied for adoptopenjdk-example-test, repository does not exist or may require 'docker login'.
23:05:37  See 'docker run --help'.
23:05:37  
23:05:37  example-test_0_FAILED
23:05:37  
23:05:37  Error: No such image: adoptopenjdk-example-test
```

There were multiple failures caused by this.
It appears an infra issue.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin fyi

**Comment by AdamBrousseau** [comment]
@llxia where does `adoptopenjdk-example-test:latest` come from?
It appears the machine has docker installed based on the output.
Also, I noticed this is from the external bucket which was just disabled because it is unstable. Perhaps we can ignore it for now.

**Comment by smlambert** [comment]
example-test can be ignored, it will shortly be removed

**Comment by jdekonin** [comment]
Reopen or open new when this is of importance.
