### ISSUE TITLE
Add ConstantPool reflection tests

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#12157]
https://github.com/eclipse/openj9/issues/12016 exposed differences between the behaviour of J9 and RI in regards to the resolution behaviour of the ConstantPool API. 

We need to find out if there are any existing tests in OpenJDK to verify the behaviour. Otherwise, we need to add tests that ensure static/instance fields, methods and class refs behave in accordance with the RI.

**Comment by DanHeidinga** [comment]
There's one test I'm aware of - jdk.internal.reflect.constantPool.ConstantPoolTest

**Comment by tajila** [comment]
Looks like it is already included as part of jdk_lang

**Comment by tajila** [comment]
We will need to add new tests to verify the <clinit> behaviour
