### ISSUE TITLE
AArch64: Preserve vector registers across JIT helpers

### ISSUE THREAD

**Issue by alvee-unb** [eclipse-openj9/openj9#12179]
Vector registers need to be preserved like it is being done in PowerPC.

A few clarifications:
- There are 32 VRs, with 16-bytes long, the alignment required for preserving them is 16-bytes in AArch64.
- All the VRs overlap with the FPRs.
- For load/store instructions, `vldrimmq` & `vstrimmq` are used respectively.

**Comment by alvee-unb** [comment]
Hi @gacholio , just wanted to let you know about this beforehand. We may proceed with this after issue#11752 is resolved.

**Comment by 0xdaryl** [comment]
@gita-omr FYI

**Comment by alvee-unb** [comment]
Hi @gacholio , as the issue #11752 is now closed, we would appreciate if you please proceed with this issue. Thank you.

**Comment by gacholio** [comment]
I have no plans to implement this.

**Comment by Akira1Saitoh** [comment]
Hi @gacholio, we need to complete this for Vector API support. Can you please implement it?
As described in https://github.com/eclipse-openj9/openj9/issues/12179#issue-828087594,
All ARMv8 processors have 32 SIMD & FP registers (v0-v31) which are 16-bytes long.  The lower half of v0-v31 are used as the FPRs.

**Comment by gacholio** [comment]
No, this is a job for the ARM team. I will happily help with and review the changes, but I will not be implementing it.

**Comment by Akira1Saitoh** [comment]
Okay, I will implement this.

Can you confirm if my understanding about required changes is correct?
- Whole 128-bit of vector registers must be saved when calling out to non-method invocation helpers.
- We do not need to save vector registers on method invocation helpers because they are volatile in private linkage. Instead, we need to save parameter FPRs for decompilation.
- Method invocation helpers are:
    - jitLookupInterfaceMethod
    - jitResolveInterfaceMethod
    - jitResolveSpecialMethod
    - jitResolveStaticMethod
    - jitResolveVirtualMethod
    - jitInduceOSRAtCurrentPC
    - jitInduceOSRAtCurrentPCAndRecompile
    - jitRetranslateMethod
    - jitStackOverflow
- The FPR save area (jitFPRs of J9CInterpreterStackFrame) can be simply expanded to cover whole 128-bit vector registers. We can still use it to save the parameter FPRs.
- No need to change functions in MethodMetaData.c.

**Comment by gacholio** [comment]
At a glance, that seems correct. I suggest following one of the other platform examples that distinguish which helpers need the extra vector work (please use the same macro names for helper declarations to keep things simple).

**Comment by Akira1Saitoh** [comment]
I've got a question regarding the registers saved in `c_cInterpreter`. Are they callee saved registers in system ABI? If so, this function does not need to be changed as vector registers are caller saved registers.
https://github.com/eclipse-openj9/openj9/blob/cfef96b343fe73a3dd444504bd871a351d1f88f3/runtime/vm/arm64cinterp.m4#L27-L38

**Comment by gacholio** [comment]
Yes, those are saving the callee-preserved registers in the ABI, so I think you're correct that no change need be made here.

**Comment by Akira1Saitoh** [comment]
Thanks. I opened https://github.com/eclipse-openj9/openj9/pull/14506.
