### ISSUE TITLE
Disable impdep1 for OJDK MHs

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#12251]
### `impdep1` is OpenJ9 MH specific
https://github.com/eclipse/openj9/blob/cef51dfd748a15b6f8ceb9be065d8a9eb8389a6b/runtime/vm/MHInterpreter.inc#L673-L678

### `impdep1` should not be invoked for OJDK MHs
https://github.com/eclipse/openj9/blob/02c278ac36df5551991fab60fbbd42c95e72b050/runtime/vm/BytecodeInterpreter.hpp#L8624-L8628

### Disable `impdep1` for OJDK MHs
This can be accomplished by wrapping the `impdep1` code with `!defined(J9VM_OPT_OPENJDK_METHODHANDLE)`.

### Related Source Code: `impdep1`
https://github.com/eclipse/openj9/search?q=impdep1

**Comment by babsingh** [comment]
@DanHeidinga Is disabling `impdep1` code for OJDK MHs the correct approach?

**Comment by gacholio** [comment]
It's unnecessary but correct - the bytecode will never be invoked in OpenJDK MH.

**Comment by DanHeidinga** [comment]
What Gac said - eventually it can be made mapped to `unimplementedBytecode`

**Comment by fengxue-IS** [comment]
@EricYangIBM Can you take a look at this
