### ISSUE TITLE
jdk16 git clone fatal: destination path '.' already exists and is not an empty directory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12267]
https://ci.eclipse.org/openj9/job/Build_JDK16_x86-64_windows_Nightly/47/console - win2012-x86-6
https://ci.eclipse.org/openj9/job/Build_JDK16_x86-64_windows_Nightly/48/console - win2012-x86-3
```
20:56:12  + git clone -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk16.git . --reference /home/jenkins/openjdk_cache
20:56:12  fatal: destination path '.' already exists and is not an empty directory.
```

**Comment by pshipton** [comment]
@AdamBrousseau any ideas? This started Sunday night, and happened again tonight.

**Comment by pshipton** [comment]
Seems ok on restart
https://ci.eclipse.org/openj9/job/Build_JDK16_x86-64_windows_Nightly/49 - win2012-x86-3

**Comment by AdamBrousseau** [comment]
Can this be closed?

**Comment by pshipton** [comment]
Haven't seen it since.
