### ISSUE TITLE
Add jython hello world to sanity.functional suite

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12284]
See https://github.com/eclipse/openj9/issues/12238 for the details.

**Comment by llxia** [comment]
@OscarQQ Could you help with this issue? Thanks

**Comment by pshipton** [comment]
As per https://github.com/eclipse/openj9/pull/12287#issuecomment-816016575 I think we should add the testing to the 0.26 release branch as well.

**Comment by llxia** [comment]
The test is added. Pending task: add mode 616

**Comment by llxia** [comment]
mode616 is added in PR https://github.com/eclipse-openj9/openj9/pull/12929
