### ISSUE TITLE
Add a new option for jextract so that it does not bundle the system core file.

### ISSUE THREAD

**Issue by manqingl** [eclipse-openj9/openj9#12344]
Very often in Service, we have received system core files from customers without the native libraries, and we have to go back to customer asking them to do jextract again. 

The jextracted files can be huge (and often a few GB) and it is not easy for customer to upload the huge file.  If jextract provides a special option (such as "-excludeCore") to exclude the system core file from the jextract result, then the jextract file normally only a few MB. This would make it much easier for customers to upload the jextract result.

If the system core file is excluded from the jextract result, it would be better if we can add a text file which documents the system core file filename, target system info (something similar to the output from jdmpview command "info sys").  This will avoid confusions.

Of course, this new option should be off by default.  And this option is to be used only after we have had the un-jextracted system core file from customer.  Unfortunately this scenario is very common in service world.

**Comment by manqingl** [comment]
@pshipton @keithc-ca @tajila FYI

**Comment by keithc-ca** [comment]
I propose the new option be `-x` (all existing options are single letters).

**Comment by keithc-ca** [comment]
What I have so far excludes the core file and instead adds a file called `excluded-files.txt` which will contain information like this:
```
Files omitted from archive
==========================
core.20210713.161309.32284.0001.dmp
```
Changing the filename or the wording within is easy if anyone has suggestions.

Adding the equivalent to `info sys` would be a significant amount of work. I think we should see whether that is really necessary.
