### ISSUE TITLE
Add fcmpl/fcmpg evaluators

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#12366]
Tracking OMR issue eclipse/omr#5895 in OpenJ9.

The following evaluators are missing on AArch64:

fcmpl/fcmpg
dcmpl/dcmpg

**Comment by knn-k** [comment]
What are these opcodes used for in OpenJ9?

**Comment by 0xdaryl** [comment]
It may not be possible to generate these IL opcodes directly with bytecodes produced from `javac` (i.e., from Java source).  This is because the IL generator will fold a `fcmpXX` bytecode that is followed immediately by an `ifYY` bytecode into an `ifcmpYY` opcode, and I'm not sure it is possible to generate a sequence that doesn't follow that pattern from Java code.

However, for valid bytecode that is generated automatically (say by a tool or by a bytecode manipulation library) it is possible to see `fcmpXX`s that aren't followed by `ifYY`s.  In those cases, the `fcmpXX` needs to be evaluated.

**Comment by knn-k** [comment]
To be clear, opcodes such as `fcmplt` and `dcmpge` return 0 or 1, and their evaluators are available for AArch64 in OMR.

Opcodes `fcmpl/fcmpg/dcmpl/dcmpg` are different.  They can return 3 values (-1, 0, 1) as shown below: 
https://github.com/eclipse/omr/blob/2ccbf5e8ce2cc1f7b0888e562ca9ee11e712f5d9/compiler/arm/codegen/FPTreeEvaluator.cpp#L2428-L2429
https://github.com/eclipse/omr/blob/2ccbf5e8ce2cc1f7b0888e562ca9ee11e712f5d9/fvtest/compilertriltest/CompareTest.cpp#L873-L889

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/6026 for this.

**Comment by knn-k** [comment]
This can be closed now.
