### ISSUE TITLE
Support for scaling JITServer down to 0

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#12375]
If the load on the JITServer deployment completely disappears, Kubernetes my shutdown all of the JITServer instances (if allowed to). When the JIT compilation activity resumes, there could be a large delay until Kubernetes launches a first JITServer instance and the compilation request from the client may timeout. The compilation will be carried out locally (by the client), but we want to avoid an OOM scenario due to an expensive compilation. Thus, if the free physical memory is low, it's probably better to downgrade these local compilations to cold optimization level. Moreover, we should use a lower scratch space limit. Cold compilations could be upgraded later-on based on sampling (or on GCR if we want to be more aggressive).

**Comment by dmitry-ten** [comment]
There is a `TODO` comment here:
https://github.com/eclipse-openj9/openj9/blob/945e979a9a33c6f5b0da6a6af5c6ca3514ccb5d7/runtime/compiler/control/CompilationThread.cpp#L8825-L8835
If we are going to lower the required lower memory bound for local cold client compilations, might as well do it for non-JITServer compiles as well. I'm not qualified to say whether the same should be done for JNI and thunk compilations, but we could it for them as well.

**Comment by mpirvu** [comment]
> 2. lower the scratch space lower bound

I would leave this the way it is now.

> 3. Upgrades

Separate queue is the best approach because it gives full control when the upgrades are processed. As an experiment we can try with GCR, which is enabled by default for cold compilations.

> 4. New option to guard the changes.

Always a good idea if something goes wrong with the new queue or anything else that we cannot anticipate.

> "CHTable must be empty"

Alexey has a solution, but does not have to deliver at the moment.
