### ISSUE TITLE
Improve DDR compatibility story for fields

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12370]
There was some discussion in https://github.com/eclipse/openj9/issues/12357#issuecomment-814395603 about improving the DDR compatibility story for fields, somewhat similar to the work done for constants via https://github.com/eclipse/openj9/pull/12210.

One idea is to limit generation of methods for new fields at build time, requiring them to be added to a compatibility file. The compatibility file contains instructions to developers that use of fields added to the file need to handle NoSuchFieldError / NoSuchMethodError since the field doesn't exist in older core files. Adding to the compatibility file is also a reminder to reviewers to ensure that new fields are handled properly for compatibility.

Another idea is for the code generated for newer fields to throw a checked Exception that needs to be handled by callers. This ensures that callers added either when the field is added or later need to think about it and handle the exception. Reviewers would see the exception handling and know to check the fields are handled properly for compatibility.

**Comment by manqingl** [comment]
I thought we used to have a mechanism which will check the version of the data structure in the blob and then match it to the parser (user).

**Comment by keithc-ca** [comment]
We still have [AlgorithmVersion](https://github.com/eclipse/openj9/blob/master/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/AlgorithmVersion.java), but the plan here is to make it a less manual process to decide when that mechanism needs to be used.

**Comment by keithc-ca** [comment]
To illustrate my proposed solution, here is the pair of methods for `SH_CacheMap._ccTail` currently generated by `PointerGenerator`:
```
  public SH_CompositeCacheImplPointer _ccTail() throws CorruptDataException {
    return SH_CompositeCacheImplPointer.cast(getPointerAtOffset(SH_CacheMap.__ccTailOffset_));
  }

  public PointerPointer _ccTailEA() throws CorruptDataException {
    return PointerPointer.cast(nonNullFieldEA(SH_CacheMap.__ccTailOffset_));
  }
```
That is a field that was introduced relatively recently. To make it clear that not all VMs will produce core files with that field, the new pattern will be:
```
  public SH_CompositeCacheImplPointer _ccTail() throws CorruptDataException, NoSuchFieldException {
    try {
      return SH_CompositeCacheImplPointer.cast(getPointerAtOffset(SH_CacheMap.__ccTailOffset_));
    } catch (NoSuchFieldError e) {
      throw new NoSuchFieldException();
    }
  }

  public PointerPointer _ccTailEA() throws CorruptDataException, NoSuchFieldException {
    try {
      return PointerPointer.cast(nonNullFieldEA(SH_CacheMap.__ccTailOffset_));
    } catch (NoSuchFieldError e) {
      throw new NoSuchFieldException();
    }
  }
```
The class generated dynamically by `BytecodeGenerator` would contain the equivalent of the following for a core where the field exists (the offset of `_ccTail` is 48 for 64-bit platforms):
```
  public SH_CompositeCacheImplPointer _ccTail() throws CorruptDataException, NoSuchFieldException {
    return SH_CompositeCacheImplPointer.cast(48);
  }

  public PointerPointer _ccTailEA() throws CorruptDataException, NoSuchFieldException {
    return PointerPointer.cast(nonNullFieldEA(48);
  }
```
and this when the field does not exist those methods would be reduced to:
```
  public SH_CompositeCacheImplPointer _ccTail() throws CorruptDataException, NoSuchFieldException {
    throw new NoSuchFieldException();
  }

  public PointerPointer _ccTailEA() throws CorruptDataException, NoSuchFieldException {
    throw new NoSuchFieldException();
  }
```

**Comment by pshipton** [comment]
@keithc-ca can this be closed? If not, what is left to do?

**Comment by keithc-ca** [comment]
I started writing a document, but recent developments mean it should change. I was leaving this open until the documentation is done.

**Comment by pshipton** [comment]
I'm going to remove it from the milestone plan.

**Comment by keithc-ca** [comment]
Documentation contributed via #13187.
