### ISSUE TITLE
Enable JitDump support on JITServer

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse-openj9/openj9#12394]
We need to be able to produce JitDumps when a crash occurs during a compilation on JITServer.
There are 2 main steps that take place when creating a JitDump:
1. Tracing IL of the crashed method - doesn't require any additional work on JITServer, we already generate IL during a regular remote compile, so this isn't any different.
2. Queuing recompilation of the crashed method on the diagnostic thread - this part will require more work. 

- First, `jitDumpRecompileWithTracing` will be modified to use front-end queries to access members of `J9Method` and `J9Class` instead of using macros. This will allow NLS print statement to correctly output the class/name/signature of the method being compiled. Front-end queries should still be able to write to the client and receive a response, because client hasn't been informed that the compilation has failed and the communication stream should still be valid.
- Next, the crashed thread will schedule a compilation on the diagnostic thread using `compInfo->compileMethod`. This is the tricky part to implement, because the server doesn't support compilations being scheduled with  `compInfo->compileMethod`, since it's otherwise only called on the client side. Normally, we add a method to the compilation queue by using `compInfo->addOutOfProcessMethodToBeCompiled(stream)`. This will create a dummy `MethodToBeCompiled` entry or reuse an old one and put it into the compilation queue. The compilation thread will then take the entry from the queue and populate it with the information received from the client.  However, this will not work for our purposes, because client won't know that it's supposed to resend the compilation request.
- The easiest solution to the above problem seems to be:
- 1.  Inside `jitDumpRecompileWithTracing`, retrieve `MethodToBeCompiled` entry of the failed compilation and replace its method details with `JitDumpMethodDetails`, leave everything else the same.
- 2.  Add the modified entry back to the compilation queue.
- 3.  Modify `TR::CompilationInfoPerThreadRemote::processEntry` to check if the `MethodToBeCompiled` entry it's currently processing is non-empty. If that's the case it should proceed to compile the method, instead of reading compilation request from the client.

The above solution should work under the assumption that client doesn't realize that the server has crashed and fail the compilation before it's rescheduled.  I think this should be a reasonable assumption to make, but I guess we'll have to see if this works. 
Alternative solution would be for the crashed thread to inform the client that compilation has failed, and then client would schedule a remote jitdump compilation.

**Comment by dmitry-ten** [comment]
@mpirvu do you think this would work? 
@fjeremic fyi.

**Comment by fjeremic** [comment]
> Alternative solution would be for the crashed thread to inform the client that compilation has failed, and then client would schedule a remote jitdump compilation.

This would seem like a cleaner approach I would think. Would this involve more work? The steps you outline seem like bandaids to the problem.

**Comment by dmitry-ten** [comment]
Hm, thinking about it, it wouldn't be significantly more work per se, I think we'd need to add a new JITServer message type that would indicate that a JitDump compilation needs be queued. Once the method is inserted in the queue, we'd need to fail the current compilation and client needs to continue compiling locally.

**Comment by mpirvu** [comment]
The crashing thread at the server is a compilation thread and it knows the stream used to communicate with the client.
In theory it should be possible to use the same stream to send an error code to the client which will resend the same compilation request with some additional tracing options. The diagnostic compilation will be performed by any available compilation thread at the server.
I don't know yet what to do with the crashing thread. If the intent is to kill the server after performing the diagnostic compilation, then the crashing thread can be suspended/blocked/disabled.

Can a JVM survive

**Comment by dmitry-ten** [comment]
I think that the way it works now, the crashing thread will suspend until the diagnostic compilation finishes, then it will finish writing JitDump and JVM will terminate.
