### ISSUE TITLE
Javacores need timezone information for the 1TIDATETIME field

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#12397]
The `1TIDATETIME` field in javacores currently looks like this:

```
1TIDATETIME    Date: 2021/04/09 at 10:32:26:106
```

This information is presented in the local timezone at the OS level, which is absolutely fine, but we have no way of knowing what that timezone is, unless it has been set explicitly in an environment variable such as `TZ`. When troubleshooting, this can make it tricky to correlate javacores with other data, which may have timestamps presented in different timezones.

So it would be very useful if the `1TIDATETIME` field included the timezone, or perhaps a new field specifically for the timezone would be more appropriate (to avoid breaking anyone who parses the `1TIDATETIME` field).

**Comment by keithc-ca** [comment]
How about another line that presents the date and time in UTC?

**Comment by paulcheeseman** [comment]
A timestamp in UTC would probably be sufficient for correlating logs, although it might still be useful to know the OS's timezone for other reasons. I don't how easy it is to get that information in a platform independent way.

**Comment by keithc-ca** [comment]
I'll try to include both UTC time and timezone, if the information is available.

**Comment by keithc-ca** [comment]
Here are some examples of the updated section:
```
1TIDATETIME    Date: 2021/04/09 at 16:43:56:283
1TIDATETIMEUTC Date: 2021/04/09 at 20:43:56:283 (UTC)
1TITIMEZONE    Timezone: EST/EDT
```
With `TZ=PST8PDT` in the environment:
```
1TIDATETIME    Date: 2021/04/09 at 13:44:23:177
1TIDATETIMEUTC Date: 2021/04/09 at 20:44:23:177 (UTC)
1TITIMEZONE    Timezone: PST/PDT
```
With `TZ=UTC` in the environment:
```
1TIDATETIME    Date: 2021/04/09 at 20:47:48:178
1TIDATETIMEUTC Date: 2021/04/09 at 20:47:48:178 (UTC)
1TITIMEZONE    Timezone: UTC
```
Feedback?

**Comment by pshipton** [comment]
I'd put 1TIDATETIMEUTC first so the 1TIDATETIME and 1TITIMEZONE are together.

**Comment by keithc-ca** [comment]
> I'd put 1TIDATETIMEUTC first so the 1TIDATETIME and 1TITIMEZONE are together.

Done:
```
1TIDATETIMEUTC Date: 2021/04/12 at 13:49:35:857 (UTC)
1TIDATETIME    Date: 2021/04/12 at 09:49:35:857
1TITIMEZONE    Timezone: EST/EDT
```
I still have to sort out z/OS build problems.

**Comment by paulcheeseman** [comment]
Actually, this is still ambiguous:

`1TITIMEZONE    Timezone: EST/EDT`

Can we not determine whether the OS is using EST or EDT?

**Comment by keithc-ca** [comment]
I think 'ambiguous' overstates, the problem, but I should be able to determine which is in effect.

**Comment by paulcheeseman** [comment]
Just to clarify my use of the word "ambiguous", most places that use EST do switch to EDT in the summer, but there are a couple of exceptions. Maybe those would show as just `EST` instead of `EST/EDT`?

Generally speaking, timezone rules are a complete mess and they're constantly changing, so the fewer assumptions we have to make the better! It would definitely be nicer to display the specific timezone that's in use right now if that's possible.

**Comment by pshipton** [comment]
Instead of using timezone names, is it possible to use something like "GMT-4", which is not "ambiguous".

**Comment by keithc-ca** [comment]
I think the offset can easily be computed by comparing the UTC and local times.

Note that not all timezone offsets are multiples of an hour (for example, our friends in Newfoundland), and that 'GMT' is deprecated in favour of 'UTC'.

If people feel strongly about not using timezone names, the example would be 'UTC-0400' (or 'UTC-400').

**Comment by keithc-ca** [comment]
In Newfoundland:
```
1TIDATETIMEUTC Date: 2021/04/12 at 23:32:42:891 (UTC)
1TIDATETIME    Date: 2021/04/12 at 21:02:42:891
1TITIMEZONE    Timezone: UTC-2:30
```
In Ottawa:
```
1TIDATETIMEUTC Date: 2021/04/12 at 23:33:48:258 (UTC)
1TIDATETIME    Date: 2021/04/12 at 19:33:48:258
1TITIMEZONE    Timezone: UTC-4
```

**Comment by keithc-ca** [comment]
Windows seems to be particularly stubborn. A previous approach using `_tzname` reported `PDT` even though the system was configured for the Eastern time zone. My current code does this if `TZ=UTC` is in the environment:
```
1TIDATETIMEUTC Date: 2021/04/14 at 14:10:54:984 (UTC)
1TIDATETIME    Date: 2021/04/14 at 10:10:54:984
1TITIMEZONE    Timezone: UTC
```
Worse than omitting the information is including incorrect information: I'm considering just reporting the timezone is unavailable on Windows.

**Comment by keithc-ca** [comment]
A sample of the final version:
```
1TIDATETIMEUTC Date: 2021/04/20 at 18:53:22:275 (UTC)
1TIDATETIME    Date: 2021/04/20 at 14:53:22:275
1TITIMEZONE    Timezone: UTC-4 (EDT)
```

**Comment by pshipton** [comment]
The changes are merged so closing this.
