### ISSUE TITLE
Descriptions of release semantics are wrong in javadoc for VarHandle methods

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse-openj9/openj9#12429]
`releaseFence` ensures that loads/stores before the fence will not be reordered with stores after the fence, but javadoc states differently.
https://github.com/eclipse/openj9/blob/1e99073506816bc24da835e4185ea78bd218d6c6/jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java#L885-L892

Similarly, `setRelease` sets the value using `release` semantics, which ensures that preceding loads/stores will not be reordered after the store, but javadoc states differently.
https://github.com/eclipse/openj9/blob/1e99073506816bc24da835e4185ea78bd218d6c6/jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java#L985-L993

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@babsingh Can you take a look at this. If its just doc changes we should be able to do this fairly quickly
