### ISSUE TITLE
cmdLineTester_GCCheck test not working properly 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12463]
There is a failure creating a core file when running cmdLineTester_GCCheck in an internal build. The failure output shows the following failure to find the main class org.openj9.test.nogc.Main. This doesn't cause the test to fail, but the test is not running as intended.
```
Running command: "/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xmx256m -cp /home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_Personal_testList_0/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_Personal_testList_0/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/gcCheck/gcCheck.jar -Xdump:system:file=j9core.dmp,events=vmstop,request=exclusive+compact org.openj9.test.nogc.Main
Time spent starting: 13 milliseconds
Time spent executing: 6629 milliseconds
Test result: FAILED
Output from test:
 [ERR] Error: Could not find or load main class org.openj9.test.nogc.Main
 [ERR] Caused by: java.lang.ClassNotFoundException: org.openj9.test.nogc.Main
 [ERR] JVMDUMP039I Processing dump event "vmstop", detail "#0000000000000001" at 2021/04/17 12:31:08 - please wait.
 ...
```

@llxia fyi

**Comment by pshipton** [comment]
It seems the build.xml is building the wrong class.
```
			<include name="${TEST_ROOT}/functional/Java8andUp/src/org/openj9/test/nogc/Allocator.java"/>
```

**Comment by pshipton** [comment]
I see gcCheck.jar contains Main.java, not Main.class and not Allocator.class either.
```
    1658  Defl:N      762  54% 04-17-2021 19:43 acaf1ada  org/openj9/test/nogc/Main.java
```

**Comment by pshipton** [comment]
When this is fixed, we should add a print at the end of Main.java and make finding the print in the output a success condition.

**Comment by LongyuZhang** [comment]
Run 50x grinder on multiple machines, but all passed:
- on p10 machine `p10rhel005`: hyc-jenkins/job/Grinder/19354
- plinux machine `ub20lert-1-7` hyc-jenkins/job/Grinder/19435
- plinux machine `ub20lert-1-1` hyc-jenkins/job/Grinder/19434

**Comment by pshipton** [comment]
@LongyuZhang the problem is not a test failure. The problem is that `Error: Could not find or load main class org.openj9.test.nogc.Main` always occurs, but it doesn't cause the test to fail. It does cause the test to be less useful (perhaps useless), as it's not testing what is intended.

1) fix the test so it can locate this class and run as intended
2) fix the test so it fails when the class is not found

**Comment by llxia** [comment]
@LongyuZhang is this issue resolved?

**Comment by LongyuZhang** [comment]
@llxia Yes, I think we can close this issue. Thanks.

**Comment by llxia** [comment]
Thanks @LongyuZhang
