### ISSUE TITLE
java/util/Random default constructor behaviour in snapshot mode

### ISSUE THREAD

**Issue by vijaysun-omr** [eclipse-openj9/openj9#12490]
Restoring from a given snapshot that has a java/util/Random seeded with the same value will result in the same sequence of random numbers generated when using the `nextInt` API as one example (there are others). This is guaranteed by the API doc at : https://docs.oracle.com/javase/8/docs/api/java/util/Random.html

This makes the behaviour of java/util/Random tricky for the default constructor API that says:

`Creates a new random number generator. This constructor sets the seed of the random number generator to a value very likely to be distinct from any other invocation of this constructor.`

This can cause issues from an end user perspective in that a seed chosen during the snapshot run is reused in every run based on a restore from a given snapshot. Note that the non-default constructor that passes in a seed expects the same sequence of random numbers to be generated from this class. 

So we need to examine what can be done to preserve the necessary determinism for the non-default constructor case while still preserving the desired random-ness for the default constructor case when running in snapshot mode.

**Comment by vijaysun-omr** [comment]
This is part of issue [16384](https://github.com/OpenLiberty/open-liberty/issues/16384)

**Comment by tajila** [comment]
@JasonFengJ9 Can you look at this next?

We need to reseed all the j.u.Random instances. Random has a `AtomicLong` "seed" which contains the seed value, `random->seed->value`.

The new seed value needs to be based on something on something unique about the process, that way if we restore N JVMs they will all have different seeds. Perhaps you can reseed them based on the CPU nanosecond clock.

Before this is done, we will need an internal hooking mechanism, similar to the Java one `J9InternalCheckpointHookAPI`. You dont need to worry about priority for this, we will just use explicit ordering. 

Here is the kind of API we need
```
At checkpoint time, this will iterate the heap and track all instances of type `instanceType`. If restore is set to FALSE it will run the hooks at checkpoint, otherwise at restore. If a hook returns FALSE then the hooks should throw an exception.


@param currentThread vmThread token
@param instanceType J9Class of type that we will perform a heap walk on
@param hook The routine that will be applied to each instance of that tpe
@param restore True if the hook needs to be applied on restore, FALSE if it needs to be applied at checkpoint
@return void
void addInternalHook(J9VMThread *currentThread, J9Class *instanceType, BOOLEAN (*hook)(J9VMThread *currentThread, void *userData, j9object_t obj), BOOLEAN restore);

@param user vmThread token
@param userData data for hook, can be NULL
@param obj heap instance where hook will be applied
@return TRUE if operation sucessful, FALSE if any failure
BOOLEAN (*hook)(J9VMThread *currentThread, void *userData, j9object_t obj)
```

The hooks will be run in criuhelpers.cpp. Internal checkpoint hooks should be run last (after java hooks), restore hooks first (before java hooks).

**Comment by tajila** [comment]
This issue depends on https://github.com/eclipse-openj9/openj9/issues/14251

**Comment by JasonFengJ9** [comment]
This was addressed via https://github.com/eclipse-openj9/openj9/pull/14365 & https://github.com/eclipse-openj9/openj9/pull/14573
