### ISSUE TITLE
AArch64: Enable supportsInliningOfIsInstance

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#12518]
Inlining the `java/lang/Class.isInstance` needs to be enabled on AArch64.  It is gated by the CodeGenerator flag `supportsInliningOfIsInstance()`.  Investigate what needs to be done to enable it.

**Comment by Akira1Saitoh** [comment]
Looks like we can inline `java/lang/Class.isInstance` if `supportsInliningOfIsInstance` returns true.
Cast class may not be known at compile time, but we already handle that case correctly. 
When the cast class is unknown at compile time, the depth of the cast class needs to be loaded at runtime for `SuperClassTest`.
https://github.com/eclipse-openj9/openj9/blob/29631a27572649ee2dad254e8ca79c8ff686aeee/runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp#L1091-L1099

**Comment by Akira1Saitoh** [comment]
Opened https://github.com/eclipse/omr/pull/6004

**Comment by Akira1Saitoh** [comment]
Closed https://github.com/eclipse/omr/pull/6004 and opened https://github.com/eclipse-openj9/openj9/pull/12680

**Comment by knn-k** [comment]
I think this issue can be closed now.  #12680 enabled `supportsInliningOfIsInstance()`.
