### ISSUE TITLE
Discussion: Remove DebugExt

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#12520]
DebugExt is short for Debugger Extensions. However, unlike something like DDR that knows how to read VM structures based on symbols / the blob information, DebugExt essentially reuses compiler routines to print out the structures, rather than say symbols from the DLL. This is not sustainable because when the compiler changes some structure, one has to just know whether DebugExt is affected - in order to reuse the compiler routines, DebugExt has to copy remote pointers (ie pointers from the coredump) into local memory (ie malloc'd memory); because the compiler is written in C++, this involves doing all sorts of hacks in order to ensure that the VFT is not a remote pointer, etc. FWIW I don't know if it currently works.

Currently the only way to get access to this is via `jextract --interactive <coredump>` (the precursor to `jdmpview`). However, I don't know if this tool is even being used anymore. Therefore, it might be better to just remove this.

The unfortunate consequence of our IL not being an array of tuples is that there is no way to print out the IL from a coredump in a way that looks pretty close to the trace log. However, with symbols from the dll and a basic debugger extension, it should be possible to at least print out the trees with some basic information.

**Comment by dsouzai** [comment]
@JamesKingdon @klangman could you guys give a service perspective on this?

**Comment by JamesKingdon** [comment]
I haven't used the debug extensions in many years. They were unreliable at best in my experience.

**Comment by klangman** [comment]
I also haven't used the debugger extensions in a long time. But I would say we don't have a great solution for dumping IL from a core file currently.

**Comment by fjeremic** [comment]
I've tried to use them many years ago but it was broken at that time. JitDump largely solves this problem though by printing the IL from within the same running process. I'm in favor of deprecating it.

**Comment by 0xdaryl** [comment]
I used to use the debugger extensions many years ago (before open source), but found that they were somewhat fragile and relied on developers keeping the dumping functions up-to-date.  I think they will need some work to get them in shape to be useful, and then there is an ongoing maintenance cost to keep them current.  I'm in favour of deprecating too.
