### ISSUE TITLE
SharedClasses.SCM23.MultiThreadMultiCL_1 segfault JIT compiled method vmState=0x00000000

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12557]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.system_s390x_linux_Nightly_testList_1/74
ub16-390-2
SharedClasses.SCM23.MultiThreadMultiCL_1

https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk16_j9_extended.system_s390x_linux_Nightly_testList_1/74/system_test_output.tar.gz
```
Step 6 - Start java processes using LoaderSlaveMultiThreadMultiCL
...
MTM4 03:59:10 >> Loaded 14000 classes...
MTM4 03:59:10 >> --> Threads 14040 to 14160 <--
MTM5 03:59:10 >> --> Threads 15720 to 15840 <--
MTM4 03:59:11 >> --> Threads 14160 to 14280 <--
MTM5 03:59:11 >> --> Threads 15840 to 15960 <--
MTM4 03:59:11 >> --> Threads 14280 to 14400 <--
MTM4 03:59:12 >> --> Threads 14400 to 14520 <--
MTM4 stderr Unhandled exception
MTM4 stderr Type=Segmentation error vmState=0x00000000
MTM4 stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=0080cac0 Signal_Code=00000001
MTM4 stderr Handler1=000003FF801C6900 Handler2=000003FF800B2190 InaccessibleAddress=000003FE00000000
MTM4 stderr gpr0=0000000000000000 gpr1=0000000093D2F670 gpr2=000003FE00000000 gpr3=0000000000130B00
MTM4 stderr gpr4=000003FF5F7196F0 gpr5=0000000001221818 gpr6=0000000093D2F680 gpr7=0000000000000010
MTM4 stderr gpr8=0000000000000000 gpr9=0000000093D2F670 gpr10=0000000093D2F628 gpr11=0000000093D45820
MTM4 stderr gpr12=0000000093D2F458 gpr13=0000000000270C00 gpr14=000003FF5F7196F0 gpr15=000003FF5C1FE4A8
MTM4 stderr psw=000003FF5F710E34 mask=0705000180000000 fpc=00080000 bea=000003FF5F711A0E
MTM4 stderr fpr0 3e6bee70e0000000 (f: 3758096384.000000, d: 5.202631e-08)
MTM4 stderr fpr1 4a6c366400000000 (f: 0.000000, d: 3.298605e+50)
MTM4 stderr fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM4 stderr fpr3 3e63abbf00000001 (f: 1.000000, d: 3.663988e-08)
MTM4 stderr fpr4 4a6c3664c8000000 (f: 3355443200.000000, d: 3.298606e+50)
MTM4 stderr fpr5 41400000a000c000 (f: 2684403712.000000, d: 2.097153e+06)
MTM4 stderr fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM4 stderr fpr7 3f2ab87900000000 (f: 0.000000, d: 2.038620e-04)
MTM4 stderr fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
MTM4 stderr fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM4 stderr fpr10 000003ff5c1c0000 (f: 1545338880.000000, d: 2.171565e-311)
MTM4 stderr fpr11 000003ffd9ffef20 (f: 3657428736.000000, d: 2.172609e-311)
MTM4 stderr fpr12 000003ff7c457b88 (f: 2084928384.000000, d: 2.171832e-311)
MTM4 stderr fpr13 000003fffd57c848 (f: 4250388480.000000, d: 2.172902e-311)
MTM4 stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM4 stderr fpr15 000003fff8d7e378 (f: 4174897920.000000, d: 2.172864e-311)
MTM4 stderr 
MTM4 stderr Compiled_method=net/openj9/test/sc/LoaderSlaveMultiThreadMultiCL$LoaderThread.run()V
MTM4 stderr Target=2_90_20210424_75 (Linux 4.4.0-201-generic)
MTM4 stderr CPU=s390x (4 logical CPUs) (0x1f7231000 RAM)
MTM4 stderr ----------- Stack Backtrace -----------
MTM4 stderr (0x000003FF5F710E34 [<unknown>+0x0])
```

**Comment by pshipton** [comment]
@fjeremic fyi, there should be a jit dump

**Comment by fjeremic** [comment]
10 job grinder:
https://ci.eclipse.org/openj9/job/Grinder/1765/

**Comment by pshipton** [comment]
The grinder failed 3/10. This seems a regression, so I'm setting as a blocker.

Another failure in the nightly builds.
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.system_s390x_linux_Nightly_testList_2/54/
ub18-390-2
SharedClasses.SCM23.MultiThreadMultiCL_1

https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk16_j9_extended.system_s390x_linux_Nightly_testList_2/54/system_test_output.tar.gz
```
MTM5 stderr Unhandled exception
MTM5 stderr Type=Segmentation error vmState=0x00000000
MTM5 stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=445bce70 Signal_Code=00000001
MTM5 stderr Handler1=000003FFA5F46900 Handler2=000003FFA5E32190 InaccessibleAddress=000003FE00000000
MTM5 stderr gpr0=0000000000000000 gpr1=000000008E609B70 gpr2=000003FE00000000 gpr3=0000000006FDDB00
MTM5 stderr gpr4=000000007AF81820 gpr5=0000000008E6DF18 gpr6=000000008E609B80 gpr7=0000000000000000
MTM5 stderr gpr8=000003FE00000010 gpr9=000000008E609B70 gpr10=000000008E609B28 gpr11=000000008E609B70
MTM5 stderr gpr12=000000008E6A17E0 gpr13=000000000714BA00 gpr14=000003FF7F4AC190 gpr15=000003FFA457E4A0
MTM5 stderr psw=000003FF7F4A105A mask=0705000180000000 fpc=0008fe00 bea=000003FF7F4A24F2
MTM5 stderr fpr0 3e8f9ea360000000 (f: 1610612736.000000, d: 2.355850e-07)
MTM5 stderr fpr1 4a30e03400000000 (f: 0.000000, d: 2.466400e+49)
MTM5 stderr fpr2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM5 stderr fpr3 3b30337700200020 (f: 2097184.000000, d: 1.340118e-23)
MTM5 stderr fpr4 4a30e03468000000 (f: 1744830464.000000, d: 2.466401e+49)
MTM5 stderr fpr5 3e924951a000c000 (f: 2684403712.000000, d: 2.724886e-07)
MTM5 stderr fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM5 stderr fpr7 3e3a336d00000000 (f: 0.000000, d: 6.100368e-09)
MTM5 stderr fpr8 0000000006ef0390 (f: 116327312.000000, d: 5.747333e-316)
MTM5 stderr fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM5 stderr fpr10 0000000006ef05a8 (f: 116327848.000000, d: 5.747359e-316)
MTM5 stderr fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM5 stderr fpr12 000003ffa04480c8 (f: 2688844032.000000, d: 2.172130e-311)
MTM5 stderr fpr13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM5 stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM5 stderr fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM5 stderr 
MTM5 stderr Compiled_method=net/openj9/test/sc/LoaderSlaveMultiThreadMultiCL$LoaderThread.run()V
MTM5 stderr Target=2_90_20210426_77 (Linux 3.10.0-1062.18.1.el7.s390x)
MTM5 stderr CPU=s390x (4 logical CPUs) (0x1ec1c5000 RAM)
MTM5 stderr ----------- Stack Backtrace -----------
MTM5 stderr (0x000003FF7F4A105A [<unknown>+0x0])
MTM5 stderr ---------------------------------------
```

**Comment by fjeremic** [comment]
@r30shah could you please help take a look? The only recent change I'm aware of is the PMR fix from @klangman in #12523. I looked over the change again and it seems ok, though from Peter's latest comment:

```
InaccessibleAddress=000003FE00000000
```

That's a bit suspect.

**Comment by r30shah** [comment]
@fjeremic  Can you launch a grinder for me to get the log file, `-Xjit:"{net/openj9/test/sc/LoaderSlaveMultiThreadMultiCL\$LoaderThread.run()V}{very-hot}(traceCG,log=methodLog)"` ?

**Comment by fjeremic** [comment]
Not 100% sure I specified the options correctly but let's give it a try:
https://ci.eclipse.org/openj9/job/Grinder/1766/console

**Comment by r30shah** [comment]
From the core-dump downloaded from job mentioned in https://github.com/eclipse/openj9/issues/12557#issuecomment-827295286 , here is how the failing sequence looks like. 
```
0x3ff7f4a103a +12864 |    c019fefa5bb0 iilf      %r1, 0xfefa5bb0
0x3ff7f4a1040 +12870 |    eb011000006a asi       0(%r1), 1
0x3ff7f4a1046 +12876 |    b9040019     lgr       %r1, %r9
0x3ff7f4a104a +12880 |    1700         xr        %r0, %r0 0 -> Clearing out 32-63 bits of GPR0
0x3ff7f4a104c +12882 |    1820         lr        %r2, %r0 -> Loading 32-63 bit from GPR0 to GPR2 , Effectively clearing lower half of GPR2
0x3ff7f4a104e +12884 |*   ec28004f007c cgije     %r2, 0, 0x3ff7f4a10ec C>> +13042 // PMR Fix was to change this from cije
0x3ff7f4a1054 +12890 ||   e3301000003a llzrgf    %r3, 0(%r1)
0x3ff7f4a105a +12896 ||   e3b02000003a llzrgf    %r11, 0(%r2) -> Dereferencing GPR2 causing segmentation fault. 
0x3ff7f4a1060 +12902 ||   e3e030580004 lg        %r14, 0x58(%r3)
```

Clearly, bits `32-63` of `GPR2` was loaded with `NULL` by instruction at `0x3ff7f4a104c` but upper half was kept untouched which in this case previously holding an address. When we performed NULL test at instruction  `0x3ff7f4a104e` we compared full 64-Bit registers, so even though it should have taken branch to wbStore , test failed and continued with sub-sequent code generated for ArrayStoreCHK and failed with segmentation fault at instruction `0x3ff7f4a105a`.

With this initial analysis, I re-ran test manually and was able to get the `traceCG` log of the method from one of the failing run. Above set of instructions were generated for following trees. 
```
------------------------------
 n297038n  (  0)  ArrayStoreCHK [#43] (sharedMemory )                                                  [     0x3fea3ad5ec0] bci=[153,50,84] rc=0 vc=3946 vn=- li=979 udi=- nc=1 flg=0x20
 n297037n  (  1)    awrtbari  <array-shadow>[#254  Shadow] [flags 0x80000607 0x0 ] (cannotOverflow sharedMemory storeAlreadyEvaluated )  [     0x3fea3ad5e70] bci=[153,50,84] rc=1 vc=3946 vn=- li=979 udi=- nc=3 flg=0x1020
 n297036n  (  0)      aladd (X>=0 internalPtr sharedMemory )                                           [     0x3fea3ad5e20] bci=[153,50,84] rc=0 vc=3946 vn=- li=979 udi=- nc=2 flg=0x8100
 n296998n  (  0)        ==>l2a (in &GPR_13460) (X!=0 unneededConv sharedMemory )
 n297035n  (  0)        lsub                                                                           [     0x3fea3ad5dd0] bci=[153,50,84] rc=0 vc=3946 vn=- li=979 udi=- nc=2
 n297033n  (  0)          ==>lshl (in GPR_13474)
 n297010n  (  0)          ==>lconst -16
 n330310n  (  0)      iconst 0 (in GPR_13480)                                                          [     0x3fe9d99fed0] bci=[153,49,84] rc=0 vc=3946 vn=- li=- udi=- nc=0
 n296998n  (  0)      ==>l2a (in &GPR_13460) (X!=0 unneededConv sharedMemory )
------------------------------
```

In instruction selection, when generating instruction for `ArrayStoreCHK` we simply evaluate child of the node before generating rest of the code for the node [1]  and it generates instruction for `iconst 0` that only clears out the lower half of the register. 

There are three main things that causes us to reach the failure. 
1. We could not optimize that particular ArrayStoreCHK node for storing constant NULL object to Array of Objects. Either globalVP or localVP identifies such cases and convert such node to regular store node as arrayStore check can be skipped while storing NULL object to array. [2]
2. Somewhere while lowering trees before instruction selection (May be at [3]) , we converted `aconst NULL` child to `iconst 0` 
3. We generated 64-bit comparison for NULL test in ArrayStoreCHK node for compressedrefs configuration assuming the child would be decompressed.


I was able to generate same trees and instructions with Unit test with `disableGlobalVP` and `disableLocalVP` JIT option,

```
	private BigInteger createBigIntegerObject() {
		if (type == 0)
			return null;
		return new BigInteger("112233");
		
	}


	public BigInteger[] unitTest(int length) {
		BigInteger[] returnArray = new BigInteger[length];
		for (int i=0; i<length; i++) {
			returnArray[i] = createBigIntegerObject();
		}
		return returnArray;
		
	}
```

Simple fix for this is to introduce a fast path in ArrayStoreCHK when the object to be stored in array is known constant NULL. Looking into try out the fix. 

[1]. https://github.com/eclipse/openj9/blob/e4b66d30983c1ada33f5d28a8ca543f584e49329/runtime/compiler/z/codegen/J9TreeEvaluator.cpp#L5254-L5275
[2]. https://github.com/eclipse/omr/blob/7638a6a5a09bbb4a7f6dcb28380ef6b6f3dc09d8/compiler/optimizer/VPHandlers.cpp#L12390-L12413
[3]. https://github.com/eclipse/openj9/blob/e4b66d30983c1ada33f5d28a8ca543f584e49329/runtime/compiler/codegen/J9CodeGenerator.cpp#L430-L478

I was able to get the `traceCG` log from the failing run by manually running the test. Fr

**Comment by fjeremic** [comment]
> Simple fix for this is to introduce a fast path in ArrayStoreCHK when the object to be stored in array is known constant NULL. Looking into try out the fix.

This doesn't sound like the correct fix. IMO the true problem here is that we have an `iconst` where we should have had an `aconst`. That transformation which changed this tree is illegal. Had the node stayed as `aconst` we would have generated a 64-bit `XGR` and the problem would not happen.

We need to find out where exactly the `aconst` got changed and why we thought it was correct to do so.

**Comment by joransiu** [comment]
I'm expecting that due to compressedrefs mode, the 2nd child is the `awrtbari` is the value to be updated into the array element and would be the full compression sequence as its subtree.  i.e. The subtree would have `l2i` w/ potential `lushr` as child (for non-zero shift) w/ `a2l` anchoring the actual `aXXX` node, containing the object reference to be stored.   With an `aconst NULL`, that probably all got reduced down to `iconst 0`
