### ISSUE TITLE
[OJDK MH] Investigate if @FrameIteratorSkip bit can be claimed for perf

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#12599]
Ref: https://github.com/eclipse-openj9/openj9/pull/12515#discussion_r617043576
> RI tags methods with `@PolymorphicSignature` annotation during ClassFile parsing. So, they only have to do a bit test for identifying polymorphic methods in native code. On the other hand, OJ9 has to compare class and method names for identifying polymorphic methods since it does not have extra bits to tag methods. The above `MethodHandleNatives.init` string comparisons will be repeated from `MemberName`'s constructor: https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/a6d3f24ce5f8ec72bf3172f24833c2108ebc0dce/src/java.base/share/classes/java/lang/invoke/MemberName.java#L585-L608. OJ9 will do the `strcmps` twice, which can be improved in the future.

Ref: https://github.com/eclipse-openj9/openj9/pull/12515#discussion_r617174728
> The `@FrameIteratorSkip` is only used by the OJ9 implementation of MH. Can we reclaim the `@FrameIteratorSkip` annotation and its associated bit for use by `@PolymorphicSignature` methods? This will lead to better performance.

**Comment by fengxue-IS** [comment]
closing this as the `J9AccMethodFrameIteratorSkip` is reused in OpenJDK MH for skip methods with `@Hidden` annotation in #12716
