### ISSUE TITLE
Refactor ValueType code

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#12615]
Move `areValueTypesEnabled` from jvminit.c to valuetypehelpers.cpp

**Comment by Umang228** [comment]
Assign me this...

**Comment by Umang228** [comment]
Plz check PR https://github.com/eclipse-openj9/openj9/pull/12618

**Comment by Umang228** [comment]
PR https://github.com/eclipse-openj9/openj9/pull/12623.......Tell me what should I do now
