### ISSUE TITLE
Automatically retry builds when github.com is not accessible

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12631]
Looking at the following builds last night, they all failed because github.com could not be contacted. Over time, I've seen quite a few builds fail due to this problem. If this failure can be automatically restarted, after a delay, that would be much better than relying on somebody to notice and manually restart the job.
`stderr: fatal: unable to access 'https://github.com/eclipse-openj9/openj9.git/': Could not resolve host: github.com`

Over time, I've seen quite a few builds fail the same way. Possibly it's happening more often lately, although I haven't kept track.

https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_Nightly/723/
https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64le_linux_Nightly/715/
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/719/
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_linux_Nightly/710/

@AdamBrousseau fyi

**Comment by pshipton** [comment]
Not exactly the same, but parts of parallel test jobs tests can also fail, such as the following. It would also be useful to automatically restart these.

https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.functional_x86-64_mac_Nightly_testList_1/82/console

**Comment by jdekonin** [comment]
For this particular case (Build* jobs), I believe this would simply require a new try block checking/blocking on a $SCM_REPO connectivity check.  Reusing `retry_and_delay` which is numRetries = 3, waitTime = 60s as default would likely resolve most of the failure cases.  What would you want to happen if the retry/delay completed and github.com was still unavailable?

https://github.com/eclipse-openj9/openj9/blob/a35b83d0ef1e650851401a9b33adefa3012e1c14/buildenv/jenkins/jobs/pipelines/Pipeline-Initialize.groovy#L33

**Comment by AdamBrousseau** [comment]
I think the test side requires a test change. If we retry_and_delay after 3 times with 1 minute intervals I think we should fail as usual. The option to manually restart form the parent will still be there if someone is watching.

**Comment by AdamBrousseau** [comment]
The problem is at this point we don't have access to retry_and_delay. So we either need to move that def here, or just use simple retry or see if the scm step has some kind of retry option.

**Comment by pshipton** [comment]
> What would you want to happen if the retry/delay completed and github.com was still unavailable?

As Adam suggested, it can continue to do what it does now: fail and allow the user to retry. If we see the 3x 60sec retry doesn't work, we can play with the values to try and find something that does work.

**Comment by AdamBrousseau** [comment]
#12636 
Untested but I think this achieves the same as `retry_and_delay`.
@pshipton Have you seen clones fail in other places?

**Comment by pshipton** [comment]
> Have you seen clones fail in other places?

Not sure, I didn't keep track. We can try your fix and see what else pops up.
