### ISSUE TITLE
Automatically retry tests that fall over due to infra issues

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12637]
Parts of parallel test jobs tests can fail, such as the following. It would be useful to automatically restart these.

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_Nightly_testList_2/59/console
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.functional_x86-64_mac_Nightly_testList_1/82/console

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_0/264/
```
14:03:18  get functional test material...
14:03:18  git clone --depth 1 -b master https://github.com/eclipse/openj9.git
14:03:49  update to openj9 sha: a35b83d0ef1e650851401a9b33adefa3012e1c14
14:03:49  git fetch -q --unshallow
14:04:12  Cannot contact osx1011-x86-1: java.lang.InterruptedException
14:06:32  Note: checking out 'a35b83d0ef1e650851401a9b33adefa3012e1c14'.
14:06:32  
14:06:32  You are in 'detached HEAD' state. You can look around, make experimental
14:06:32  changes and commit them, and you can discard any commits you make in this
14:06:32  state without impacting any branches by performing another checkout.
14:06:32  
14:06:32  If you want to create a new branch to retain commits you create, you may
14:06:32  do so (now or later) by using -b with the checkout command again. Example:
14:06:32  
14:06:32    git checkout -b <new-branch-name>
14:06:32  
14:06:32  HEAD is now at a35b83d0e Merge pull request #12247 from gza060625/cg-marking-verbose
14:06:32  check OpenJ9 Repo sha
14:06:32  /Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_0/openjdk-tests/TKG/scripts/getSHA.sh --repo_dir /Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_0/openjdk-tests/openj9 --output_file /Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_0/openjdk-tests/TKG/SHA.txt
14:06:32  Check sha in /Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_0/openjdk-tests/openj9 and store the info in /Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_0/openjdk-tests/TKG/SHA.txt
14:06:32  ================================================
14:06:32  timestamp: 20210505-140631
14:06:32  repo dir: /Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_0/openjdk-tests/openj9
14:06:32  git repo: 
14:06:32    Fetch URL: https://github.com/eclipse/openj9.git
14:06:32  sha:
14:06:32  a35b83d0ef1e650851401a9b33adefa3012e1c14
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
14:06:35  $ ssh-agent -k
14:06:35  kill: No such process
[Pipeline] // sshagent
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
terminateJavaProcesses iteration: 1
[Pipeline] echo
PROCESSCATCH: Checking for any leftover java processes on the machine
[Pipeline] sh
+ ps -fu jenkins
+ grep java
+ egrep -v 'remoting.jar|agent.jar|grep'
  501 10680 10679   0  6:43AM ??         1:47.73 java -jar slave.jar
[Pipeline] echo
PROCESSCATCH: There are rogue processes still on the machine as per the list above
[Pipeline] echo
PROCESSCATCH: Removed processes - here is what is remaining:
[Pipeline] sh
+ ps -fu jenkins
+ grep java
+ egrep -v 'remoting.jar|agent.jar|grep'
  501 10680 10679   0  6:43AM ??         1:47.78 java -jar slave.jar
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
[WS-CLEANUP] done
[Pipeline] sh
+ find /cores -name '*core*' -print -exec rm -f '{}' ';'
/cores
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
ERROR: Failed to run ssh-agent -k
```

**Comment by pshipton** [comment]
I guess this needs to be handled via the test pipeline code? @llxia @AdamBrousseau 

There is https://github.com/adoptium/aqa-tests/pull/2530 to disable machines, but I don't think these issues are the same, they are just temporarily network problems.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/660/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Personal_testList_0/257/console
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Personal_testList_1/257/console

These are `Could not resolve host: github.com`, but I assume this needs to be retried in the test pipelines and not the build pipelines?

**Comment by AdamBrousseau** [comment]
Ideally on the test side imo. Does it seem to be machine specific or just intermittent network issues?

**Comment by llxia** [comment]
Personally, I would prefer to fix the underline issue if possible. Even with auto-retry, the retriggered test builds may fail again due to the network problem. 
FYI @smlambert

**Comment by pshipton** [comment]
> I would prefer to fix the underline issue if possible

As would we all, but not sure it's possible, and probably out of our control. A side affect of having machines around the world in various places.

In all the cases listed I don't think there is any lasting machine issue. The machines are remain online (or re-attach) and continue to run other jobs successfully.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/37/console

**Comment by smlambert** [comment]
That does not look like retry will help... that is not a temporary network error. 

```
12:28:40  Failed sending usage report to Artifactory: java.io.IOException: Usage report is not supported on targeted Artifactory server.
12:28:40  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/37/openjdk_test_output.tar.gz
[Pipeline] publishBuildInfo
12:28:42  Deploying build info to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
12:28:42  Failed sending usage report to Artifactory: java.io.IOException: Usage report is not supported on targeted Artifactory server.
12:28:43  Deploying build descriptor to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
12:28:43  Build successfully deployed. Browse it in Artifactory under https://140-211-168-230-openstack.osuosl.org/artifactory/webapp/builds/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/37
12:28:43  Sending request for build retention, deleting build artifacts, max number of builds to store: 20.
[Pipeline] echo
12:28:43  Test output artifactory URL:'https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/37/'
[Pipeline] }
```

**Comment by smlambert** [comment]
Also in the case above in https://github.com/eclipse-openj9/openj9/issues/12637#issuecomment-833923282, it would be extremely inefficient to retry the entire test build due to some failure to upload results.  I think this is a common scenario.  I am not in favour of blind restarts, as they would not be a good use of resources and as @llxia said, they mask the underlying problems and much worse introduce new problems that would need to be solved and maintained (including managing multiple test results from originals and retries, ensuring the results were monitored/stored/displayed properly in TRSS, etc.).

Let's step back and assess each of the common failures to see if there are better, more efficient actions to take, instead of merely restarting an entire test run.  I have some ideas on this, but I'd like to annotate each of these examples first and look at the patterns of failure.

**Comment by AdamBrousseau** [comment]
I agree we don't want to retry entire jobs. Building retries around certain problematic steps however could be beneficial. Particularly things that reach out to the network where we have no control over intermittent problems. Git clones, artifact pulls, artifact uploads etc.

**Comment by pshipton** [comment]
@smlambert I think you are looking at the wrong thing, look higher in the build, it failed due to
```
12:28:02       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/jtreg/jtreg-4.2.0-tip.tar.gz
12:28:27       [exec] curl: (18) transfer closed with 459781 bytes remaining to read
```

**Comment by pshipton** [comment]
Everything I've linked here failed before the testing ever started. They could all be retried in some fashion. I agree we don't want to automatically restart something that got all the way or part of the way through the testing.

**Comment by AdamBrousseau** [comment]
Not to take away from this issue but that Jtreg failure is being tracked in https://github.com/adoptium/aqa-tests/issues/2484

**Comment by smlambert** [comment]
Right, I see.  https://github.com/adoptium/aqa-tests/issues/2484 should address this issue.  And previously we had put a [5x retry on the curl task](https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L57) related to https://github.com/adoptium/aqa-tests/issues/1748.

**Comment by AdamBrousseau** [comment]
I'm not convinced that curl --retry 5 is working. The silent flag is on so there is no output but it spends 25 seconds after the echo before the error is reported which isn't much time.
```
00:07:11.517       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/jtreg/jtreg-4.2.0-tip.tar.gz
00:07:36.095       [exec] curl: (18) transfer closed with 459781 bytes remaining to read
```

**Comment by smlambert** [comment]
re: https://github.com/eclipse-openj9/openj9/issues/12637#issuecomment-834405963 - expect it to spend ~30 seconds retrying:
1sec + 2sec + 4sec + 8sec + 16sec 

Not sure what version of curl on machines, but later versions are 'smarter' about the retry...

```
--retry <num>

If a transient error is returned when curl tries to perform a transfer, it will retry this number of times before giving up. Setting the number to 0 makes curl do no retries (which is the default). Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408 or 5xx response code.

When curl is about to retry a transfer, it will first wait one second and then for all forthcoming retries it will double the waiting time until it reaches 10 minutes which then will be the delay between the rest of the retries. By using --retry-delay you disable this exponential backoff algorithm. See also --retry-max-time to limit the total time allowed for retries.

Since curl 7.66.0, curl will comply with the Retry-After: response header if one was present to know when to issue the next retry.

If this option is used several times, the last one will be used.

Added in 7.12.3.
```

**Comment by pshipton** [comment]
Just note this issue is not just about curl. I think only the last failure was related to curl.

**Comment by llxia** [comment]
https://github.com/adoptium/aqa-tests/issues/2484 is resolved and we should not have jtreg jar download issue anymore.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/690/console
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_Nightly/669/console

**Comment by llxia** [comment]
The problem happened when copying artifacts. The fact that we cannot copy artifacts from another Jenkins job [test.getDependency](https://ci.eclipse.org/openj9/job/test.getDependency/) makes me think that Jenkins master stopped responding during that time. @AdamBrousseau is this similar to the internal copyArtifacts issue?

```
00:17:49.775  Cannot run copyArtifacts from test.getDependency. Skipping copyArtifacts...
[Pipeline] sh
00:17:49.778  ub16x64j91 was marked offline: Connection was broken: java.util.concurrent.TimeoutException: Ping started at 1620961336263 hasn't completed by 1620961576264
00:17:49.778  	at hudson.remoting.PingThread.ping(PingThread.java:134)
00:17:49.778  	at hudson.remoting.PingThread.run(PingThread.java:90)
00:17:49.778  
```

**Comment by llxia** [comment]
I think we should add `openjdk-jenkins-helper` library in openj9 Jenkins configuration so that the child test job gets generated only if it does not exist. This will help to reduce memory usage on Jenkins during nightly runs.

**Comment by pshipton** [comment]
Might be faster as well. You can see certain steps before the tests start running can take quite some time, depending on the mcahine and I think especially if there is a lot going on at once.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR/818/console

**Comment by llxia** [comment]
Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573548

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly/709/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly_testList_0/14/console
```
02:05:50  get functional test material...
02:05:50  git clone --depth 1 -b master https://github.com/eclipse-openj9/openj9.git
02:06:09  fatal: unable to access 'https://github.com/eclipse-openj9/openj9.git/': Empty reply from server
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_0/13/console
```
03:01:11  get testKitGen...
03:01:11  git clone -b master https://github.com/AdoptOpenJDK/TKG.git
03:02:33  fatal: unable to access 'https://github.com/AdoptOpenJDK/TKG.git/': Failed to connect to github.com port 443: A remote host did not respond within the timeout period.
```

**Comment by llxia** [comment]
We have added retry cmd and I believe this issue is resolved.
