### ISSUE TITLE
Mixedrefs build not switching to nocompressedrefs automatically based on -Xmx

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12683]
Use any latest build, or the 0.26 release.
`java -Xmx300g` gives an error `VMJ9GC028E Option too large: '-Xmx'`
`java -Xnocompressedrefs -Xmx300g` works fine.

Since there is only one JVM in the package, I don't think it's a problem with the redirector. It seems the VM is missing logic outside the redirector to check the -Xmx value and NOT set the J9_EXTENDED_RUNTIME2_COMPRESS_OBJECT_REFERENCES flag.

@dmitripivkine @tajila fyi

**Comment by dmitripivkine** [comment]
If we want to support automatic selection CR/Full an extra logic should be added.
An equivalent code in redirector.c in `chooseJVM()` does:
1) Check can Compressed Refs (CR) be run in this environment and which maximum shift value is possible:
 - ZOS only: machine low memory allocation OS feature installed:
      `ZOS64_VMEM_ABOVE_BAR_GENERAL` - no support, CR can not be run, switch size to Full-64 bit at 0GB
      `ZOS64_VMEM_2_TO_32G` - CR 3-bit shift maximum, switch size to Full-64 bit at 25GB
      `ZOS64_VMEM_2_TO_64G` - CR 4-bit shift maximum, switch size to Full-64 bit at 57GB
 - selected GC Policy is Metronome - supports CR 3-bit shift maximum, switch size to Full-64 bit at 25GB, all other GC policies support CR 4-bit shift
 2) Check if `-Xmx` value is smaller or equal  than supported switch size to Full-64 bit use Compressed References can be used

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this issue?

**Comment by JasonFengJ9** [comment]
Sure, will do.
