### ISSUE TITLE
OJDK MH builds break with #12660

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#12705]
OJDK MH builds break with #12660: **Disable impdep1 handling for OpenJDK MHs**.

There are compilation failures, which prevents me to build OpenJ9 JDK16 or JDK17 with OJDK MHs enabled.

```
[Error1] swalk.c:923 unused variable J9JavaVM

[Error2] MHInterpreter.hpp:340:29: error: 'J9JavaVM {aka struct J9JavaVM}' has no member named 'impdep1PC'
   _currentThread->pc = _vm->impdep1PC;
```

There may be more errors.

**Comment by babsingh** [comment]
fyi @EricYangIBM @gacholio

**Comment by babsingh** [comment]
@fengxue-IS `MHInterpreter.hpp` is still being built with OJDK MHs enabled.

**Comment by gacholio** [comment]
Ah, I tested the wrong new JDK. MHInterpreter* needs to be excluded from the new builds (and for good measure, stop including the hpp file in the interpreter to be sure).
