### ISSUE TITLE
pltest failing j9vmem_testFindValidPageSize on AIX due to 64K page

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12706]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_1/276/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_OMR_testList_1/273
cmdLineTester_pltest_aix_0
```
02:09:04   [ERR] 1: j9vmem_testFindValidPageSize(64K large page size)
02:09:04   [ERR] 	/home/jenkins/workspace/Build_JDK11_ppc64_aix_OMR/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x1000, pageFlags: 0x1, but found pageSize: 0x10000, pageFlags: 0x1
02:09:04   [ERR] 
02:09:04   [ERR] 		LastErrorNumber: -108
02:09:04   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
02:09:04   [ERR] 
02:09:04   [ERR] 2: j9vmem_testFindValidPageSize(64K and 16M large page size)
02:09:04   [ERR] 	/home/jenkins/workspace/Build_JDK11_ppc64_aix_OMR/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x1000, pageFlags: 0x1, but found pageSize: 0x10000, pageFlags: 0x1
02:09:04   [ERR] 
02:09:04   [ERR] 		LastErrorNumber: -108
02:09:04   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
02:09:04   [ERR] 
02:09:04   [ERR] 3: j9vmem_testFindValidPageSize(all possible page sizes)
02:09:04   [ERR] 	/home/jenkins/workspace/Build_JDK11_ppc64_aix_OMR/openj9/runtime/tests/port/j9vmemTest.c line 1916: Expected j9vmem_find_valid_page_size() to return pageSize: 0x1000, pageFlags: 0x1, but found pageSize: 0x10000, pageFlags: 0x1
02:09:04   [ERR] 
02:09:04   [ERR] 		LastErrorNumber: -108
02:09:04   [ERR] 		LastErrorMessage: A file or directory in the path name does not exist.
```

Introduced by https://github.com/eclipse/omr/pull/5995

**Comment by pshipton** [comment]
@singh264 @zl-wang this is blocking the OMR acceptance build

**Comment by fjeremic** [comment]
@singh264 @zl-wang any updates on this? Have we confirmed whether eclipse/omr#5995 is the culprit? If we can't resolve by EOD can you please submit a PR to back out the change?

**Comment by singh264** [comment]
@fjeremic @pshipton it seems very likely my recent [OMR commit](https://github.com/eclipse/omr/pull/5995) is the culprit.

I will submit a PR to back out my OMR changes if I am unable to resolve the issue before EOD.

**Comment by singh264** [comment]
@pshipton seeking guidance

openj9 - fix_cmdLineTester_pltest_aix_0
omr - openj9
build - https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/9205/

openj9 - fix_cmdLineTester_pltest_aix_0
omr - fix_aix_xlpcodecachetests
build - https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/9212/

openj9 - fix_aix_xlpcodecachetests
omr - fix_aix_xlpcodecachetests
build - https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/9214/

openj9 - all_64k_pagesize_tests_fix
omr - fix_aix_xlpcodecachetests
build - https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/9217/

---

openj9:fix_cmdLineTester_pltest_aix_0 - https://github.com/eclipse-openj9/openj9/pull/12715
omr:fix_aix_xlpcodecachetests - https://github.com/eclipse/omr/pull/6032
openj9:fix_aix_xlpcodecachetests - https://github.com/eclipse-openj9/openj9/pull/12669
openj9:all_64k_pagesize_tests_fix - https://github.com/eclipse-openj9/openj9/pull/12778

**Comment by pshipton** [comment]
Your changes below look good, the only issue I see is a bad machine, for which I created internal issue infrastructure/issues/5540.

openj9 - all_64k_pagesize_tests_fix
omr - fix_aix_xlpcodecachetests
build - https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/9217/

**Comment by pshipton** [comment]
The OMR change should be merged first, and I'll take care of the rest.
