### ISSUE TITLE
zlinux pltest j9mmap_test9, 10 failing on Ubuntu 20.04

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12719]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR_testList_1/272
cmdLineTester_pltest_0
Failing on ub16-390-1, which is just upgraded to Ubuntu 20.04
```
23:53:28   [ERR] Starting test j9mmap_test9
23:53:28   [ERR]   Writing to readonly region - we should crash
23:53:28   [ERR]    A crash occured, signal handler invoked (type = 0x18)
23:53:28   [ERR] /home/jenkins/workspace/Build_JDK8_s390x_linux_OMR/openj9/runtime/tests/port/j9mmapTest.c line 1541: j9mmap_test9 Modified string does not match in updated buffer
23:53:28   [ERR] 
23:53:28   [ERR] 		LastErrorNumber: -108
23:53:28   [ERR] 		LastErrorMessage: No such file or directory
23:53:28   [ERR] 
23:53:28   [ERR] Ending test j9mmap_test9
23:53:28   [ERR] 
23:53:28   [ERR] Starting test j9mmap_test10
23:53:28   [ERR]   Page size is reported as 4096
23:53:28   [ERR]   Written out the buffer 64 times to fill two pages
23:53:28   [ERR]   File mapped at location -1574961152
23:53:28   [ERR]   Protecting first page
23:53:28   [ERR]   Writing to readonly region - we should crash
23:53:28   [ERR]    A crash occured, signal handler invoked (type = 0x18)
23:53:28   [ERR]   Writing to page two region - should be ok
23:53:28   [ERR] /home/jenkins/workspace/Build_JDK8_s390x_linux_OMR/openj9/runtime/tests/port/j9mmapTest.c line 1760: j9mmap_test10 Modified string does not match in updated buffer
23:53:28   [ERR] 
23:53:28   [ERR] 		LastErrorNumber: -108
23:53:28   [ERR] 		LastErrorMessage: No such file or directory
23:53:28   [ERR] 
23:53:28   [ERR] Ending test j9mmap_test10
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by fjeremic** [comment]
FYI starting to see this issue more often on PR testing.

**Comment by tajila** [comment]
@mikezhang1234567890 can you please take a look at this

**Comment by mikezhang1234567890** [comment]
Looking into this.

**Comment by fjeremic** [comment]
Reproduction here as well on ub20-390-2 which I assume is Ubuntu 20.04 judging by the name:
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Personal_testList_0/82/consoleText

**Comment by 0xdaryl** [comment]
Given how frequently this fails in PR builds and blocks OMR Acceptance, at the very least I'd like to see this triaged as soon as possible.  I'll target it to 0.28.0 until convinced otherwise.

**Comment by tajila** [comment]
@mikezhang1234567890 Any update on this?

**Comment by mikezhang1234567890** [comment]
Looks to be an issue with how OpenJ9 is setting the protections on Ubuntu 20 on Z. The file isn't being updated even after we change the protections back to writeable and writing to the mmap'd memory. Setting the protections and writing using the Linux functions directly (`mprotect`) seems to be fine.

**Comment by mikezhang1234567890** [comment]
Never mind, it does fail using native functions on s390x Ubuntu 20.04.

If you have something like the below, which is similar to j9mmap_test9:
```C
mapPtr = mmap(NULL, FILE_LEN, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);

mprotect(mapPtr, FILE_LEN, PROT_READ);
strcpy(mapPtr, modifiedText); /* with a sig handler to deal with or ignore the SIGSEGV */

mprotect(mapPtr, FILE_LEN, PROT_READ | PROT_WRITE);
strcpy(mapPtr, modifiedText); 
```
the second write will not actually update the file being mapped.

However, if you add a read while the pointer is read-only, or a write before it is read-only, the last write will work:
```C
mapPtr = mmap(NULL, FILE_LEN, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);

strcpy(mapPtr, modifiedText2); /* insert this and the last write will work */

mprotect(mapPtr, FILE_LEN, PROT_READ);
memcpy(myBuffer, mapPtr, 4); /* insert this and the last write will work */
strcpy(mapPtr, modifiedText); /* with a sig handler to deal with or ignore the SIGSEGV */

mprotect(mapPtr, FILE_LEN, PROT_READ | PROT_WRITE);
strcpy(mapPtr, modifiedText); 
```
In this case, the file will be updated with the contents of  `modifiedText` at the end.

**Comment by pshipton** [comment]
> if you add a read while the pointer is read-only

@mikezhang1234567890 Are you working on a fix? Can we update the j9mmap_protect() implementation with this workaround? i..e. If the flags are set to read, immediately do a small read from the memory.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin do the zlinux UB20 machines have the latest updates installed?

**Comment by jdekonin** [comment]
ub20-390-2 has changed requiring a reboot to make active. I have rebooted the machine and made 100% current as the reboot was blocking a small number of updates.

ub20-390-1 is in the same state.  Do you want me to update both or leave one in the current state for comparisons?

**Comment by pshipton** [comment]
Might as well update both, we already get regular failures on these machines, and we'll need to work on the latest.

**Comment by jdekonin** [comment]
Both have been upgraded and rebooted.  There are 4 packages ( build-essential, gcc, g++ and cpp ) blocked for upgrade for reasons I am not certain on.  @rajdeepsingh1 can you please follow up with them?

**Comment by mikezhang1234567890** [comment]
Yes, trying to implement a workaround to this issue, however adding a small read after `mprotect` sets the protections to read only in `port/unix/protect_helpers.c` doesn't seem to fix the test.

**Comment by pshipton** [comment]
Assuming it still happens after the machine updates, we could just modify the test itself, at least that would stop the failures in the builds.

**Comment by pshipton** [comment]
Now the machines are unusable, related to `gcc: Command not found`, I've disabled them.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/99
```
23:56:37  build-natives-unix:
23:56:37       [echo] make -C /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native SRCDIR=/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native JAVA_HOME=/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/openjdkbinary/j2sdk-image/jre OUTDIR=/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native
23:56:37       [exec] make[2]: Entering directory '/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native'
23:56:37       [exec] OS is linux
23:56:37       [exec] mkdir -p /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native
23:56:37       [exec] chmod 755 /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native
23:56:37       [exec] mkdir -p /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux
23:56:37       [exec] chmod 755 /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux
23:56:37       [exec] gcc -D_JNI_IMPLEMENTATION_ -D_TRIVIAL_AGENT -O0 -g3 -pedantic -c -Wall -std=c99 -fPIC -fno-omit-frame-pointer -static-libgcc -o /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux/sharedClasses.o -I. -I/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/openjdkbinary/j2sdk-image/jre/../include -I/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/openjdkbinary/j2sdk-image/jre/../include/linux -I/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/openjdkbinary/j2sdk-image/jre/include -I/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/openjdkbinary/j2sdk-image/jre/include/linux -I/usr/include /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native/sharedClasses.c
23:56:37       [exec] make[2]: Leaving directory '/home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native'
23:56:37       [exec] make[2]: gcc: Command not found
23:56:37       [exec] make[2]: *** [Makefile:195: /home/****/workspace/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_2/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/bin/native/linux/sharedClasses.o] Error 127
```

**Comment by rajdeepsingh1** [comment]
Downgrading `libc6` and upgrading it again seems to have resolved - dependencies fulfilled
> ( build-essential, gcc, g++ and cpp ) blocked for upgrade

Re-enabled machines in Jenkins.

**Comment by pshipton** [comment]
@rajdeepsingh1 they are still failing with `gcc: Command not found1`, I've disabled them again.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_2/102/console

**Comment by pshipton** [comment]
It may only be ub20-390-1 failing, I've only disabled this one for now.

**Comment by pshipton** [comment]
@mikezhang1234567890 pltest is still failing after the updates, so we still need a workaround.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_0/102/

**Comment by pshipton** [comment]
@rajdeepsingh1 ub20-390-2 has a different problem now (and it's disabled again).
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_0/103/console
```
23:39:44       [exec] /home/****/workspace/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_0/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native/sharedClasses.c:27:10: fatal error: string.h: No such file or directory
23:39:44       [exec]  #include <string.h>
23:39:44       [exec]           ^~~~~~~~~~
23:39:44       [exec] compilation terminated.
```

**Comment by tajila** [comment]
Since we have a workaround Ill move this up

**Comment by pshipton** [comment]
Ya, this just remains open now to resolve the infra issue, since we've been discussing it here.

**Comment by rajdeepsingh1** [comment]
`ub20-390-1` gcc dependancy issue resolved, enabled in Jenkins. 

```
ubuntu@openj901:~$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by rajdeepsingh1** [comment]
> @rajdeepsingh1 ub20-390-2 has a different problem now (and it's disabled again). https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_0/103/console
> 
> ```
> 23:39:44       [exec] /home/****/workspace/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_0/aqa-tests/system/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native/sharedClasses.c:27:10: fatal error: string.h: No such file or directory
> 23:39:44       [exec]  #include <string.h>
> 23:39:44       [exec]           ^~~~~~~~~~
> 23:39:44       [exec] compilation terminated.
> ```

`ub20-390-2` has also been fixed, dependency issue resolved:

Successful
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_0/112/console


@pshipton

**Comment by rajdeepsingh1** [comment]
Fix implemented on both machines:

**Comment by pshipton** [comment]
Thanks. Closing assuming fixed.
