### ISSUE TITLE
jdk17 openj9-staging OMH failing to compile

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12734]
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_mac_OpenJDK/462
```
08:46:31  /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/openj9/runtime/compiler/optimizer/J9TransformUtil.cpp:2501:12: error: 1036 enumeration values not handled in switch: 'FirstOMRMethod', 'FirstJ9Method', 'org_apache_harmony_luni_platform_OSMemory_putByte_JB_V'... [-Werror,-Wswitch]
08:46:31     switch (rm)
08:46:31             ^
08:46:31  /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_OpenJDK/openj9/runtime/compiler/optimizer/J9TransformUtil.cpp:2501:12: note: add missing switch cases
08:46:31     switch (rm)
08:46:31             ^
```

**Comment by babsingh** [comment]
The default case is missing from the below switch case:
https://github.com/eclipse-openj9/openj9/blob/142f75ec2784195923da8f9db8f4f02be9bada52/runtime/compiler/optimizer/J9TransformUtil.cpp#L2501-L2507

The fix should be similar to https://github.com/eclipse-openj9/openj9/pull/12644/commits/a5c73e5aab0787bab4e3eedba1029121c29a0a53, which was part of https://github.com/eclipse-openj9/openj9/pull/12644.

**Comment by pshipton** [comment]
This was broken since May 14, but I didn't notice since there were other problems.

https://github.com/eclipse-openj9/openj9-omr/compare/092787cd681...c58ed85788a
https://github.com/eclipse/omr/pull/5984

**Comment by babsingh** [comment]
Created https://github.com/eclipse-openj9/openj9/pull/12737 to address the issue.
