### ISSUE TITLE
Get wrong gc information on JDK16

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#12754]
Java -version output
--------------------

```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Windows 7 amd64-64-Bit Compressed References 20210421_24 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)

```

Summary of problem
-------------------
I get wrong gc information by using [spark](https://github.com/lucko/spark) .This problem happen on JDK11_openj9 and JDK16_openj9.
![2021-05-22_14 53 06](https://user-images.githubusercontent.com/40121560/119218104-2dabbd00-bb11-11eb-8f7d-f4a32b8c0355.jpg)

Diagnostic files
----------------

Part spark GC Monitoring print(using JDK8):
```
[14:50:42] [spark-fabric-async-worker/INFO]: [CHAT] [??] GC monitor enabled.
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT] [??] Young Gen GC lasting 7 ms. (cause = collect due to normal GC activity)
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]   2.1 MB moved to tenured-SOA
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]     282.7 MB → 284.8 MB
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]   2.6 MB freed from nursery-survivor
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]     19.1 MB → 16.6 MB (13%)
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]   5.9 KB freed from JIT code cache
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]     15.2 MB → 15.2 MB (0%)
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]   124.9 MB freed from nursery-allocate
[14:50:43] [spark-fabric-async-worker/INFO]: [CHAT]     129.6 MB → 4.7 MB (96%)
```
GC Monitoring print(Using JDK16):
```
[14:52:45] [spark-fabric-async-worker/INFO]: [CHAT] [?] Young Gen GC lasting 5 ms. (cause = collect due to normal GC activity)
[14:52:45] [spark-fabric-async-worker/INFO]: [CHAT]   307.8 KB moved to class storage
[14:52:45] [spark-fabric-async-worker/INFO]: [CHAT]     281.8 MB → 282.1 MB
[14:52:45] [spark-fabric-async-worker/INFO]: [CHAT]   1.8 MB freed from nursery-survivor
[14:52:45] [spark-fabric-async-worker/INFO]: [CHAT]     14.4 MB → 12.7 MB (12%)
[14:52:45] [spark-fabric-async-worker/INFO]: [CHAT]   110.3 MB freed from tenured-LOA
[14:52:45] [spark-fabric-async-worker/INFO]: [CHAT]     112.2 MB → 1.9 MB (98%)

```

**Comment by pshipton** [comment]
@dmitripivkine

**Comment by dmitripivkine** [comment]
@1a2s3d4f1 Would you please explain what exactly the problem is? The only difference on GC side is default `-Xmx` value - 512m for Java 8 or 25% of available RAM for higher versions (11 and 16)

**Comment by 1a2s3d4f1** [comment]
In higher version(11 and 16),Spark mod get wrong heap name, But it can get real heap name on hotspot.   Spark GC Monitoring get wrong gc heap name in hightly version. such as nursery-allocate heap named tenured-LOA ,tenured-SOA named class storage. 

Get wrong gc heap name problem only happen on JDK11-openj9 or higher version.

**Comment by dmitripivkine** [comment]
I believe the concern is memory pool names in report are mismatched for Java 11 and higher for OpenJ9 (and correct for HotSpot): 
- `tenured-LOA` instead of expected `nursery-allocate`
- `class storage` instead of expected `tenured-SOA`
I think there is no Java version related difference on GC side for MX Bean reporting implementation.
@LinHu2016 and @JasonFengJ9 Would you please check this API works correctly in Java 11 and higher?
@tajila FYI

**Comment by JasonFengJ9** [comment]
A quick try with test code snippet
```
		for (GarbageCollectorMXBean bean : ManagementFactory.getGarbageCollectorMXBeans()) {
			System.out.println("bean name : " + bean.getName());
			for (String poolName : bean.getMemoryPoolNames()) {
				System.out.println("    memory pool name : " + poolName);
			}
		}
```

`OpenJ9 JDK8/11/16` have same results:

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210421_909 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)

bean name : scavenge
    memory pool name : nursery-allocate
    memory pool name : nursery-survivor
bean name : global
    memory pool name : tenured-SOA
    memory pool name : tenured-LOA
    memory pool name : nursery-allocate
    memory pool name : nursery-survivor
```

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210421_957 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)
bean name : scavenge
    memory pool name : nursery-allocate
    memory pool name : nursery-survivor
bean name : global
    memory pool name : tenured-SOA
    memory pool name : tenured-LOA
    memory pool name : nursery-allocate
    memory pool name : nursery-survivor
```

```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Mac OS X amd64-64-Bit Compressed References 20210421_24 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)
bean name : scavenge
    memory pool name : nursery-allocate
    memory pool name : nursery-survivor
bean name : global
    memory pool name : tenured-SOA
    memory pool name : tenured-LOA
    memory pool name : nursery-allocate
    memory pool name : nursery-survivor
```

We might need a testcase to reproduce the issue reported.
Note: the initial problem was on `Windows` (will find a machine to run the testcase and update the result here).

**Comment by LinHu2016** [comment]
As @dmitripivkine mentioned above, there is no Java version related difference on GC side for MX Bean reporting implementation. if you retrieve memorypools, which are managed by GarbageCollectorMXBeans, there should be no non-Heap memory pools(such as "class storage"), @1a2s3d4f1 Could you please point where is trying to retrieve memorypools in source code? I did not see related memorypool populating  in https://github.com/lucko/spark/blob/da2b2e3d948e7533379f039a6686d2b5e3722047/spark-common/src/main/java/me/lucko/spark/common/monitor/memory/GarbageCollectorStatistics.java, thanks

**Comment by 1a2s3d4f1** [comment]
This code is print gc report part.
https://github.com/lucko/spark/blob/master/spark-common/src/main/java/me/lucko/spark/common/monitor/memory/GarbageCollectionMonitor.java

**Comment by LinHu2016** [comment]
@1a2s3d4f1 Hi I have checked src codes(GcMonitoringModule.java), apparently it retrieved memoryUsages from GarbageCollectionNotificationInfo->gcInfo, 
first of all,  return Map<String,MemoryUsage> for getMemoryUsageAfterGc()/getMemoryUsageBeforeGc() does not guarantee memory pool orders cross platforms.
second of all, the monitor code does not print information if there is no usage change for the memory pool.
third of all,  the monitor code does not check if memory pool is managed by the GC(nor checking non-heap memory pool).
so for certain gc, there are no usage change for some memory pools, so you would not see the related memory pools output for that GC.

**Comment by anuragagarwal561994** [comment]
Hello, not sure if the issue is related but I am reading wrong tenured-LOA value after upgrading to java-11 in GC Notification.

This is java-8 same code:

<img width="1138" alt="Screenshot 2022-03-08 at 4 44 26 AM" src="https://user-images.githubusercontent.com/6075379/157135572-62ea5c0a-46d6-42dd-9231-d34cff72bc99.png">

This is java-11 same code:

<img width="1138" alt="Screenshot 2022-03-08 at 4 56 15 AM" src="https://user-images.githubusercontent.com/6075379/157135621-624deb13-6322-4e6e-b4c2-0e88d81e49c2.png">

The usage is only coming in case of gc notification, else when I am just fetching the tenured-loa the used space is 0

<img width="1372" alt="Screenshot 2022-03-08 at 4 56 39 AM" src="https://user-images.githubusercontent.com/6075379/157135520-b8c5ac9a-4f82-4013-8ae4-c0292957ce6d.png">

I am using micrometer to get these metrics.

https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-binders%2Fsrc%2Fmain%2Fjava%2Fio%2Fmicrometer%2Fbinder%2Fjvm%2FJvmGcMetrics.java

Here since the promoted bytes = (tenured-soa + tenured-loa) [before - after]

I am getting this as -ve and thus not able to record the right allocation and promotion.

While on the other hand as showed in the graphs above:

https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-binders%2Fsrc%2Fmain%2Fjava%2Fio%2Fmicrometer%2Fbinder%2Fjvm%2FJvmMemoryMetrics.java

Gives the correct usage which is 0.

As of now I have tested this only in java-11 and problem has started happening since java-11 I guess.

**Comment by 1a2s3d4f1** [comment]
@anuragagarwal561994 It a relate issue. @LinHu2016 Could you see that isssue?

**Comment by LinHu2016** [comment]
Thanks @anuragagarwal561994 @1a2s3d4f1 , I will double check the difference, BTW Do you mean that promoted bytes = (tenured-soa + tenured-loa) [**after gc - before gc**] for scavenge?

**Comment by anuragagarwal561994** [comment]
So from https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-binders%2Fsrc%2Fmain%2Fjava%2Fio%2Fmicrometer%2Fbinder%2Fjvm%2FJvmGcMetrics.java

promotedBytes is a counter which is incremented as `final long delta = longLivedAfter - longLivedBefore`

longLivedAfter & longLivedBefore is calculated as `tenured-soa (used) + tenured-loa (used)`

**Comment by 1a2s3d4f1** [comment]
@LinHu2016 I find other heap size problem in [anuragagarwal561994](https://github.com/anuragagarwal561994)`s reply.  There are examples.

- class storage instead of expected tenured-SOA

- JIT data cache instead of expected miscellaneous non-heap storage

Spark get wrong memory pool size on java11 or high java version. This heap "JIT code cache" show size of heap "nursery-allocate".  GC Notification may have some problem on java11 or high java version. I try to run with -Xnoloa flag, but it not solve my problem.
Get information on java11:
```
[14:13:57] [spark-fabric-async-worker/INFO]: [CHAT] [⚡] Young Gen GC lasting 6 ms. (cause = collect due to normal GC activity)
[14:13:57] [spark-fabric-async-worker/INFO]: [CHAT]   111.8 MB freed from JIT code cache
[14:13:57] [spark-fabric-async-worker/INFO]: [CHAT]     115.2 MB → 3.4 MB (97%)
[14:13:57] [spark-fabric-async-worker/INFO]: [CHAT]   43.4 KB freed from nursery-allocate
[14:13:57] [spark-fabric-async-worker/INFO]: [CHAT]     15.4 MB → 15.4 MB (0%)
```
This is test on java8:
```
[14:09:56] [spark-fabric-async-worker/INFO]: [CHAT] [⚡] Young Gen GC lasting 12 ms. (cause = collect due to normal GC activity)
[14:09:56] [spark-fabric-async-worker/INFO]: [CHAT]   10.3 KB freed from JIT code cache
[14:09:56] [spark-fabric-async-worker/INFO]: [CHAT]     14.6 MB → 14.6 MB (0%)
[14:09:56] [spark-fabric-async-worker/INFO]: [CHAT]   107.9 MB freed from nursery-allocate
[14:09:56] [spark-fabric-async-worker/INFO]: [CHAT]     115.2 MB → 7.3 MB (93%)
```

**Comment by LinHu2016** [comment]
Hi @anuragagarwal561994 @1a2s3d4f1, I have updated the code, but there is still puzzle why it would happen, I also could not reproduce the issue in my local, I have built a personal debug build, which would like you to try on, please let me know which platform you are using(I guess it is windows), Thanks

**Comment by anuragagarwal561994** [comment]
Hi @LinHu2016 I am using MacBook M1, do let me know how can I check the same.

**Comment by LinHu2016** [comment]
Hi @anuragagarwal561994, here is the link for the debug build for Java 11, https://na.artifactory.swg-devops.com/artifactory/sys-rt-generic-local/hyc-runtimes-jenkins.swg-devops.com/Build_JDK11_aarch64_mac_Personal/7/OpenJ9-JDK11-aarch64_mac-20220324-093610.tar.gz, please check output on server side, there would be error messages if any mix order issue happens. Thanks

**Comment by pshipton** [comment]
Note that aarch64 mac is new and in early access with known limitations. See the limitations in the release notes for the upcoming release https://github.com/eclipse-openj9/openj9/blob/master/doc/release-notes/0.32/0.32.md

**Comment by pshipton** [comment]
@LinHu2016 I believe you have provided an internal IBM link.

**Comment by LinHu2016** [comment]
Hi @anuragagarwal561994, I have shared the debug builds with you via https://ibm.box.com/s/gtbgs9ut9dzkex0dlx9torz6hyhcl4f1, there are one for JDK8 x86-64, one for JDK11 x86-64 and one for JDK 11 aarch64, as @pshipton mentioned in [comment 4](https://github.com/eclipse-openj9/openj9/issues/12754#issuecomment-1077919840), JDK 11 aarch64 is early access with known limitations and all of builds are unsigned, so you might have security issue to run with them depends on your OSX version (I can not run on my own macbook macOS Monterey), if you can run the builds, please check if there are error messages about memorypool order issue on server side. Thanks

**Comment by anuragagarwal561994** [comment]
@LinHu2016 I am not able to access the same, I am not part of the IBM box and in my personal account I am not able to use it.

**Comment by pshipton** [comment]
If the sharing permissions are set correctly you should be able to access the files. I can't access the folder either.

**Comment by LinHu2016** [comment]
Hi @anuragagarwal561994,

please try the below the links

https://ibm.box.com/s/cnrh00pltdg3i1h17xie9jdsedr6u6ns
https://ibm.box.com/s/6rs8rvtavlvqd70fj6hju3sx18gdxe3h
https://ibm.box.com/s/zex40jj3xc4nehrlfc90lcqn9i9jigcv

**Comment by anuragagarwal561994** [comment]
I am not able to build this on my local, mac doesn't allow saying that it is not from a verified source
