### ISSUE TITLE
JEP 306 Restore Always-Strict Floating-Point Semantics

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12759]
See https://openjdk.java.net/jeps/306

**Comment by pshipton** [comment]
@tajila @0xdaryl fyi

**Comment by DanHeidinga** [comment]
@0xdaryl will this be complete for the code split date of Aug 9th?  I understood only the JIT took advantage of relaxed fp-semantics

**Comment by DanHeidinga** [comment]
Plus testing concerns @llxia

**Comment by 0xdaryl** [comment]
I don't think there is any functional work required here for correctness, only cleanup.  On x86 (the only platform where strictfp made a difference) OpenJ9 has long required running on a processor that supported SSE2 and the x87 paths could not be exercised.  In fact, I believe OpenJ9 won't even start up on x86 if it doesn't detect a processor that supports SSE2.

Recently, we began dismantling and surgically removing the x87 support from the JIT to simplify things for the new Vector API.  There is more work to be done there (it isn't just a matter of deleting code as some of the x87 logic is wrapped within the SSE/AVX logic which requires careful consideration to remove).  There is still code that mentions strictfp in the JIT and those places will be cleaned up as part of this effort for Vector.

As mentioned in the JEP, this affects x86/x87 only.  None of the other architectures should be affected.

**Comment by BradleyWood** [comment]
I am working on this

**Comment by tajila** [comment]
@BradleyWood What is the status on this work? Is https://github.com/eclipse/omr/pull/6132/ the only pending PR?

**Comment by BradleyWood** [comment]
@tajila Sorry I missed your comment. eclipse/omr#6132 is the only remaining PR, I suppose it is ready for review.

**Comment by DanHeidinga** [comment]
@BradleyWood Is there a timeline on getting this completed?  Do we need the remaining OMR PR to complete this JEP for the 0.27 release?

**Comment by BradleyWood** [comment]
@DanHeidinga I believe the work we did to remove x87 satisfies JEP 306. Eclipse/omr#6132 is cleanup work with non-functional changes. I don't think it's critical to merge it now and @0xdaryl hasn't finished reviewing yet.

**Comment by 0xdaryl** [comment]
We did the work to verify that the floating point semantics are correctly followed by the JIT for JDK17 for all the processor architectures OpenJ9 supports. There is cleanup work required to remove legacy strictFP paths from the JIT. I don't plan on forcing the cleanup work into JDK17.

**Comment by DanHeidinga** [comment]
Given the JEP is complete in 0.28, should this item be closed and a new item for the JIT cleanup work be opened?  Otherwise this gives the impression the JEP work is incomplete

**Comment by 0xdaryl** [comment]
Yes.  I will create an issue to track the cleanup work shortly.

**Comment by DanHeidinga** [comment]
> Yes. I will create an issue to track the cleanup work shortly.

@0xdaryl  Any progress on this?  It would be good to get it out of the 0.28 (Java 17) plan

**Comment by 0xdaryl** [comment]
Issue #13541 opened to track strictfp path cleanup.

Since strictfp is deprecated in JDK 17 these paths are no longer required and should be eliminated.  There is only a functional difference between strictfp and non-strictfp when Intel X87 floating point was used, and those paths have been disabled for years.  Semantically, OpenJ9 meets the floating point requirements for JDK 17 and earlier.  Closing this issue.
