### ISSUE TITLE
functional test suite build fails on hotspot jdk8

### ISSUE THREAD

**Issue by lumpfish** [eclipse-openj9/openj9#12756]
Ref: https://github.com/adoptium/aqa-tests/issues/2586

Is this something openj9 can fix or should these tests somehow avoid being compiled and run on a hotspot build?

**Comment by smlambert** [comment]
This issue and #12755 could have been combined into a single issue. 

FYI @llxia

**Comment by lumpfish** [comment]
> 
> This issue and #12755 could have been combined into a single issue?
> 
The cause of the build failure is different in the two releases as far as I can tell.

**Comment by llxia** [comment]
[J9security](https://github.com/eclipse-openj9/openj9/blob/master/test/functional/cmdLineTests/J9security/playlist.xml) contains tests for openj9/ibm only. 
@OscarQQ could you update[ build.xml](https://github.com/eclipse-openj9/openj9/blob/master/test/functional/cmdLineTests/J9security/build.xml#L109) to compile this test for openj9/ibm only? Thanks

**Comment by llxia** [comment]
compile J9security for ibm/openj9 only #12771 is delivered. Close this issue.
