### ISSUE TITLE
functional test suite build fails on hotspot jdk17

### ISSUE THREAD

**Issue by lumpfish** [eclipse-openj9/openj9#12755]
Ref: https://github.com/adoptium/aqa-tests/issues/2587

Is this something openj9 can fix or should these tests somehow avoid being compiled and run on a hotspot build?

**Comment by smlambert** [comment]
FYI @llxia

**Comment by llxia** [comment]
Jsr335 contains tests for openj9/ibm only.
@OscarQQ could you update build.xml to compile this test for openj9/ibm only? Thanks

**Comment by llxia** [comment]
compile Jsr335 for ibm/openj9 only #12770 is delivered. Close this issue.

**Comment by smlambert** [comment]
I am still seeing failures in this job: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.functional_aarch64_linux/44/console

**Comment by llxia** [comment]
I think this issue is fixed.
