### ISSUE TITLE
Shared class cache name and number of connected users not available through APIs

### ISSUE THREAD

**Issue by gvnmlln** [eclipse-openj9/openj9#12784]
Requirement for the current JVM's resolved shared class cache name and number of connected users to be added to the MemoryMXBean and SharedClass APIs (com.ibm.oti.shared.SharedClassStatistics and  com.ibm.oti.shared.SharedClassUtilities) so this information can be recorded in CICS JVM server statistics reports.

The resolved shared class cache name is not available today in the openJ9 SharedClass APIs or the MemoryMXBean. Only the unresolved shared class cache name is obtainable through the Java system API, via the -Xshareclasses:name=<> JVM option. The resolved cache name is valuable as CICS is unable to resolve the symbols that can be specified in the cache name. 

The number of users connected to the SCC is already available from the openJ9 java core, but it is not available from the SharedClass APIs. This limits CICS from capturing this information and reporting it in its statistics report. This information is valuable as it allows customers to confirm if the class cache is being shared by other JVMs, which would prevent the cache from being deleted until the connected JVMs are stopped.

**Comment by hangshao0** [comment]
> Requirement for the current JVM's resolved shared class cache name and number of connected users to be added to the MemoryMXBean and SharedClass APIs



If we want to add such info, they could be added in package `com.ibm.oti.shared`. 

We may not want to add them into MemoryMXBean. Information like the cache name and number of connected users does not sound like memory information.

**Comment by PhilWakelin** [comment]
This issue will become more important with Java 11, as the usage of the SCC defaults to on.

**Comment by pshipton** [comment]
@PhilWakelin I've implemented a possible solution which adds new APIs to com.ibm.oti.shared.SharedClassStatistics, numberAttached( ) and cachePath(). The next step is to test it out and see if it's sufficient for your purposes. Are you able to evaluate this if I give you a build? Do you want jdk8, jdk11 or both?

https://github.com/eclipse-openj9/openj9/pull/13925

**Comment by PhilWakelin** [comment]
@pshipton yes I can test this out. Its probably easier to test at Java 8, as I don't have a Java 11 build environment, and I presume I need to write an app to report on the new API.

**Comment by pshipton** [comment]
@PhilWakelin here you go https://ibm.box.com/s/q5eazvc1s55zu12zera31l01csf7hvfu

**Comment by PhilWakelin** [comment]
I tested out the z/OS driver, using a standalone program on z/OS to test the following two methods
`SharedClassStatistics.numberAttached();`
`SharedClassStatistics.cachePath();`
The `numbertAttached()` method worked correctly for 2 users of the cache.
The `cachePath()` returned the full path of one of the control files i.e.  `/tmp/javasharedresources/C290M4F1A64_memory_cics.IYK2Z32_G43L00`, however, it would probably be best to just return the directory patch i.e. `/tmp/javasharedresources`
However, the resolved cache name i.e the value of -`Xshareclasses:name=<>` was not available, which is what this issue was raised to request.

**Comment by pshipton** [comment]
I kept the existing API and added cacheDir() and cacheName(). I've send you the new builds privately.

**Comment by PhilWakelin** [comment]
Thanks, I downloaded and now the cache name and cache directory work as expected, here's the output of my test case ```Thread(1) 12/17/21 13:21:15:577 Shared class cache cics.test free space: 11M/15M users: 1 path:/tmp/javasharedresources```

**Comment by pshipton** [comment]
@PhilWakelin is this sufficient or is MXBean support also required?

**Comment by pshipton** [comment]
You can expect the changes you previewed in 8.0.7.6 (if one is created), and later builds.

**Comment by PhilWakelin** [comment]
> @PhilWakelin is this sufficient or is MXBean support also required?

I chatted with Paul Cooper, and he agreed the current API was sufficient, although the MXBean would be a neater solution but not something we require.

**Comment by pshipton** [comment]
I'll go ahead and close this then.
