### ISSUE TITLE
J9 failed to throw NoClassDefFoundError in synthetic accessor method of outer class

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#12804]
### Summary
We found that J9 failed throw NoClassDefFoundError when method of undefined class was invoked in synthetic accessor method. The simplified test case can be found in the attachment. 

To simply,  If we insert an undefined class declaration statement in the synthetic accessor method, both J9 and hotspot failed throw any exception, this can be verified by executing src1.Outer in the attachment. However, if a method of an undefined class is called, the behavior between hotspot and J9 is different. On hotspot, NoClassDefFoundError will be thrown, on J9, still, nothing was thrown, this can be verified by executing src2.Outer in the attachment.

However, the main difference between the two classes is whether the methods of the undefined class are called.
```
src1.Outer
static synthetic Method access$000:"()Ljava/lang/Object;":
...
new	class UndefinedClass;
dup;
invokespecial	Method UndefinedClass."<init>":"()V";
pop;
...

src2.Outer
static synthetic Method access$000:"()Ljava/lang/Object;":
...
new	class UndefinedClass;
dup;
invokespecial	Method UndefinedClass."<init>":"()V";
astore_1;
aload_1;
invokevirtual	Method java/lang/Object.clone:"()Ljava/lang/Object;";
pop;
...
```

### How to reproduce?
[https://drive.google.com/file/d/1MSVQmFzQg_iroKzZRu8N0ncMgyxFEJFE/view?usp=sharing](attachment)
Follow the commands in readme.

### Affected version
macOS
java -version
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

```
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```

```
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment AdoptOpenJDK (build 10.0.2+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 10.0.2+13, mixed mode)
```

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

Windows 10
```
java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@JavaTailor was this closed intentionally?

**Comment by tajila** [comment]
Closed based on https://github.com/eclipse-openj9/openj9/issues/12828#issuecomment-854363250
