### ISSUE TITLE
Remove obsolete J9VMJavaLangClassNativesCDLC

### ISSUE THREAD

**Issue by jsoref** [eclipse-openj9/openj9#12818]
https://github.com/eclipse-openj9/openj9/blob/4feda5f0a1010425f491ff7928412c610d757423/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9ClassHelper.java#L403

Per https://en.wikipedia.org/wiki/Connected_Limited_Device_Configuration, this reference is to an obsolete something.

**Comment by keithc-ca** [comment]
I expect the reference ought to have referred to `J9VMJavaLangClassNativesCLDC`, not `J9VMJavaLangClassNativesCDLC` (CLDC, not CDLC).
