### ISSUE TITLE
Some bytecodes in the class file are not executed 

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#12819]
### Summary
We found a test case where some bytecodes in the class files are not executed. The simplified test case can be found in the attachment. 

To simply,  we inserted a print statement before the main function exits, as shown below. 
The correct execution should output "Success" on the console. However, executing this test case on J9 did not output any information.

```
 public static Method main:"([Ljava/lang/String;)V"
stack 5 locals 6
 {
	...
	...
	getstatic	Field java/lang/System.out:"Ljava/io/PrintStream;";
	ldc	String "Success";
	invokevirtual	Method java/io/PrintStream.println:"(Ljava/lang/String;)V";
	return;
 }
```

### How to reproduce?
[Test1.zip](https://github.com/eclipse-openj9/openj9/files/6585686/Test1.zip)

Follow the commands in readme.

### Affected versions
macOS:
```
macOS Big Sur
Version 11.2.3 (20D91)
Processor 2.3 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3
```

Java -version output under macOS
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201022_737 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10)
```

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210120_897 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
```

Windows 10:
```
Microsoft Windows 10 Professional
10.0.16299 Build 16299
Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz 2.90 GHz
Memory 8 GB
```

Java -version output under Windows 10
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Windows 10 x86-32-Bit 20201112_759 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - b52d2ff7ee based on jdk8u275-b01)
```

**Comment by gacholio** [comment]
The problem is in the JIT compilation of the main method. Works at noopt, but fails at anything higher:
```
java -Xjit:limit={*.main*} TestCase
<no output>

java -Xjit:limit={*.main*},noopt TestCase
Success
```

**Comment by gacholio** [comment]
As this is the main method, the compilations are going to be via DLT.
```
java -Xjit:count=0,limit={*.main*} TestCase
Success

java -Xjit:count=1,limit={*.main*} TestCase
<no output>
```

**Comment by gacholio** [comment]
@0xdaryl @vijaysun-omr Completely reproducible.

**Comment by 0xdaryl** [comment]
@BradleyWood : would you mind investigating this please?

**Comment by BradleyWood** [comment]
Entire block after outer-loop seems to be optimized out. At some point it is flagged as unreachable.

```
<optimization id=23 name=localValuePropagation method=TestCase.main([Ljava/lang/String;)V>
Performing 23: localValuePropagation
[    76] O^O VALUE PROPAGATION: Removing rest of block after ResolveAndNULLCHK [00007F480F0809B0]
[    77] O^O VALUE PROPAGATION: Removing unreachable block_8 at [00007F480F050EF0]
```

More investigation needed.

**Comment by vijaysun-omr** [comment]
Thanks Brad. 

Usually "Removing rest of block..." message at an exception check node happens because VP believes that the check is guaranteed to fail. You could see what you get with traceLocalVP,traceFull and if you need help understanding something, please reach out.

**Comment by fjeremic** [comment]
Also we have excellent documentation courtesy of Vijay for the Value Propagation optimization in case you may not be familiar with its inner workings:

https://github.com/eclipse/omr/blob/master/doc/compiler/optimizer/ValuePropagation.md

**Comment by BradleyWood** [comment]
The optimizer (VPHandlers.cpp at constrainCheckcast & constrainInstanceOf) believes the checkcast is guaranteed to fail. Local variable index 0 begins a String[], however it is overwritten with the ArrayList. The problem is that the local variable map is not updated and the instance check compares String[] with List instead of ArrayList with List.

```
public static Method main:"([Ljava/lang/String;)V"
	stack 5 locals 6
{
  new	class java/util/ArrayList;
  dup;
  invokespecial	Method java/util/ArrayList."<init>":"()V";
  astore_0;                                     // stores ArrayList
  ...
  aload_0;                                      // loads ArrayList
  checkcast	class java/util/List; // compares String[] with List
  ...
}
```

**Comment by vijaysun-omr** [comment]
I think the problem may be that local value propagation is taking the declared type of the parameter as the type for all loads of the parm symbol in question. This is valid in the typical case when the parm symbol is not stored to in the body of the method. However, if the parm symbol is stored to as seems to be the case in this method we cannot use the declared type of the parm symbol obtained from the signature of the method. 

This code checks for such non-invariant parms and ought to prevent the parm symbol type info from being used in cases like the one that you mentioned : https://github.com/eclipse/omr/blob/b7eb963361371cd01db67dbd0bb523afe9ed24ee/compiler/optimizer/ValuePropagationCommon.cpp#L188

So you may want to look into why that sort of checking was not able to avert the bug that you are seeing in this case, i.e. maybe this code does not run (or runs but not at the right time).

**Comment by pshipton** [comment]
@vijaysun-omr is this fix safe enough, and do you think it's important to get the fix into the 0.27 release?

**Comment by vijaysun-omr** [comment]
It is a safe fix in my opinion. The problem is not new (has been there since we implemented DLT many years ago basically). 
Given that an external user opened this issue, it is worth considering for 0.27.

**Comment by pshipton** [comment]
I've tentatively set the target for 0.27 and we can see how the acceptance and other builds go before porting the change to this release.

**Comment by pshipton** [comment]
OMR acceptance is blocked atm, hopefully not because of this change. See https://openj9.slack.com/archives/CDS7QE9HB/p1624427315028000

**Comment by pshipton** [comment]
OMR is promoted now.

**Comment by fjeremic** [comment]
Sorry misread the previous comment. Acceptance is fine but we still would like to port the fix.

**Comment by 0xdaryl** [comment]
@BradleyWood : please prepare a 0.27 PR for this fix.
