### ISSUE TITLE
Increase maximum number of compilation threads at JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#12847]
The maximum number of compilation threads at JITServer is 63 (1 thread is the diagnostic thread) and this limit was arbitrarily chosen. When the network latency is large the server could benefit from a larger number of compilation threads to avoid sitting idle.
The default number of compilation threads could remain 63, but the user should be given the choice (through command line options) of using more compilation threads if he wanted to.

**Comment by mpirvu** [comment]
`MAX_SERVER_USABLE_COMP_THREADS` should be increased to 255 or something like that.
`TR::CompilationInfo::updateNumUsableCompThreads(int32_t &numUsableCompThreads)` should be updated to set the desired number of compilation threads (bounded by 1 and `MAX_SERVER_USABLE_COMP_THREADS`). If the `numUsableCompThreads` parameter is out of bounds, a value of `DEFAULT_SERVER_USABLE_COMP_THREADS` should be used (this should be set to 63 to keep the current behavior)

**Comment by AlexeyKhrabrov** [comment]
I actually already have an implementation of this, as well as changes needed to increase the number of client threads. I can submit a PR some time in the next few days.

**Comment by mpirvu** [comment]
I would prefer to have the server solution independent of the client solution (2 PRs)
