### ISSUE TITLE
Crash on generating javacore files.

### ISSUE THREAD

**Issue by manqingl** [eclipse-openj9/openj9#12851]
The issue happened when a non-Java thread (so J9VMThread is NULL) is used as the currentThread to generate the javacore files and walk all the Java threads.

This is the native stack trace:

`(dbx) where
.() at 0x0
jswalk.walkLiveMonitorSlots(??, ??, ??, ??, ??), line 1792 in "jswalk.c"
jitGetOwnedObjectMonitors(??), line 1708 in "jswalk.c"
getOwnedObjectMonitorsIterator(??, ??), line 128 in "ownedmonitors.c"
walkFrame(??), line 486 in "swalk.c"
jitWalkStackFrames(??), line 249 in "jswalk.c"
walkStackFrames(??, ??), line 334 in "swalk.c"
getOwnedObjectMonitors(??, ??, ??, ??), line 91 in "ownedmonitors.c"
JavaCoreDumpWriter::getOwnedObjectMonitors(J9VMThread*,J9ObjectMonitorInfo*)(??, ??, ??), line 5225 in "javadump.cpp"
protectedGetOwnedObjectMonitors(??, ??), line 5723 in "javadump.cpp"
omrsig_protect() at 0x9000000057f86b0
JavaCoreDumpWriter::writeThread(J9VMThread*,J9PlatformThread*,unsigned long,unsigned long,unsigned long,J9Object*,J9VMThread*)(0x9001000a0ffa688, 0x9001000a104aa88, 0x100101ee2a8, 0x4, 0x100101f1130, 0x1f900000000, 0x100101ee280, 0x0), line 4405 in "javadump.cpp"
JavaCoreDumpWriter::writeThreadsWithNativeStacks()(??), line 2365 in "javadump.cpp"
protectedWriteThreadsWithNativeStacks(??, ??), line 5759 in "javadump.cpp"
omrsig_protect() at 0x9000000057f86b0
JavaCoreDumpWriter::writeThreadSection()(??), line 1929 in "javadump.cpp"
protectedWriteSection(??, ??), line 399 in "javadump.cpp"
omrsig_protect() at 0x9000000057f86b0
JavaCoreDumpWriter::JavaCoreDumpWriter(const char*,J9RASdumpContext*,J9RASdumpAgent*)(??, ??, ??, ??), line 511 in "javadump.cpp"
runJavadump(??, ??, ??), line 5956 in "javadump.cpp"
doJavaDump(??, ??, ??), line 933 in "dmpagent.c"
protectedDumpFunction(??, ??), line 2902 in "dmpagent.c"
omrsig_protect() at 0x9000000057f86b0
runDumpFunction(??, ??, ??), line 2878 in "dmpagent.c"
runDumpAgent(??, ??, ??, ??, ??, ??), line 2804 in "dmpagent.c"
triggerDumpAgents(??, ??, ??, ??), line 1045 in "trigger.c"
sigQuitHandler(??, ??), line 123 in "sigquit.c"
omrsig_protect() at 0x9000000057f86b0
sigQuitWrapper(??, ??, ??, ??), line 152 in "sigquit.c"
runHandlers() at 0x9000000057fc250
asynchSignalReporter() at 0x9000000057fc4d8
thread_wrapper() at 0x90000000578eb20
(dbx)`

The crash happened when we tried to de-reference the NULL currentThread to get the j9javavm pointer from the following call in method `jswalk.walkLiveMonitorSlots` :

`vmFuncs->objectIsBeingWaitedOn(currentThread, targetThread, obj)`

**Comment by pshipton** [comment]
@tajila fyi

**Comment by gacholio** [comment]
The code is always passing NULL for the vmThread from `sigQuitHandler`.

**Comment by gacholio** [comment]
Note `protectedGetOwnedObjectMonitors` - why is the crash being reported instead of being caught?

**Comment by gacholio** [comment]
@manqingl Does the locks section ever work when SIQQUIT is injected? Wondering if I missed a path in the code where it gets the current thread.

If the section is always empty (i.e. crash on NULL is caught) then the problem may be in the signal protection somehow.

None of this explains why the crash is not caught.

**Comment by manqingl** [comment]
@gacholio I can easily repeat the issue with the following test case, even though it would be a different spot which called method objectIsBeingWaitedOn():

public class Hang {
        public static void main(String [] args) {
                Hook hook = new Hook();
                System.out.println("adding hook ... ");
                Runtime.getRuntime().addShutdownHook(hook);
                System.out.println("Exiting ... ");
        }

        private static class Hook extends Thread {
                public void run() {
                        while(true) {
                                try {
                                        System.out.println("Sleep inside Hook ....");
                                        Thread.sleep(10000);
                                } catch (InterruptedException e) {
                                        e.printStackTrace();
                                }
                        }
                }
        }
}

**Comment by gacholio** [comment]
Does this occur without the shutdown hook (just looping in main for instance)?

**Comment by tajila** [comment]
@dmitripivkine the issue is only seen when the JVM signal handler is disabled.

This means that the only issue here is what to do about `vmFuncs->objectIsBeingWaitedOn(currentThread, targetThread, obj)` when called on a non-VM thread (cases where currentThread is NULL)

`objectIsBeingWaitedOn` is defined as:

```
BOOLEAN
objectIsBeingWaitedOn(J9VMThread *currentThread, J9VMThread *targetThread, j9object_t obj)
{
	BOOLEAN rc = FALSE;
	if (J9_ARE_ANY_BITS_SET(targetThread->publicFlags, J9_PUBLIC_FLAGS_THREAD_WAITING)) {
		rc = (obj == J9VMTHREAD_BLOCKINGENTEROBJECT(currentThread, targetThread));
	}
	return rc;
}

#define J9VMTHREAD_BLOCKINGENTEROBJECT(vmThread, object) J9VMTHREAD_JAVAVM(vmThread)->memoryManagerFunctions->j9gc_objaccess_readObjectFromInternalVMSlot((vmThread), (j9object_t*)&((object)->blockingEnterObject))
```

The question is can `j9gc_objaccess_readObjectFromInternalVMSlot` take in a javaVM instead? This will involve refactoring some GC APIs

**Comment by dmitripivkine** [comment]
@amicic Any thoughts?

**Comment by gacholio** [comment]
To me, it seems reasonable that you not be allowed access to java objects on a non-java thread. The javacore writer eventually gets the class from the object to print - it uses APIs that take a VM.

If the dump code gets exclusive (from external thread in this case), this operation should be safe.

**Comment by gacholio** [comment]
What is the nature of the SATB work? Could we simply skip it if the current thread is NULL (given my comment above about only the class really needing to be valid)?

**Comment by dmitripivkine** [comment]
> What is the nature of the SATB work? Could we simply skip it if the current thread is NULL (given my comment above about only the class really needing to be valid)?

Object is stored in a VM thread owned fragment of sATBBarrierRememberedSet. This action can not performed if current thread in NULL obviously.

**Comment by RSalman** [comment]
>The question is can j9gc_objaccess_readObjectFromInternalVMSlot take in a javaVM instead? This will involve refactoring some GC APIs

As Dmitri mentioned, VM thread should be passed, it's required for the Metronome barrier.

```
mm_j9object_t
MM_RealtimeAccessBarrier::readObjectFromInternalVMSlotImpl(J9VMThread *vmThread, j9object_t *srcAddress, bool isVolatile)
{
	mm_j9object_t object = *srcAddress;
	rememberObjectIfBarrierEnabled(vmThread, object);
	return object;
}
```
 Outside of metronome, there's no need for the thread. If the thread is NULL, we don't have perform the barrier specific action for the thread.

**Comment by gacholio** [comment]
Maybe the answer is to return NULL on metronome if currentThread is NULL given that a correct answer cannot be returned. This would result in some inaccurate information rather than the outright crash. The crash is usually caught by the javacore code, so we're already not getting useful information in that section.

**Comment by gacholio** [comment]
We can change anywhere that's taking current and target thread to fetch the VM from the target to allow for NULL current.

**Comment by dmitripivkine** [comment]
There is no reason to call barrier code with current thread NULL. So NULL check can be added inside `j9gc_objaccess_readObjectFromInternalVMSlot` or outside it on caller side (in the macro). I think the return value can be NULL in this case - it depends what caller is expected

**Comment by gacholio** [comment]
Right, we'll need to verify that a NULL return is handled in the callers (i.e. no assumptions are being made about a VM slot not being NULL based on other flags, etc).

**Comment by amicic** [comment]
I think that it's reasonable to assume that any non trivial operation under blockingEnterObject and that GC is expected to do something about this  is only if really target is the current running thread, 

So, a solution for me is at the level of the macro:
if current == target, do same as before,
otherwise return plain target->blockingEnterObject

**Comment by gacholio** [comment]
That sounds ideal - we're generating a javacore, so this is meant to be a strictly read-only operation. We don't want to be updating remembered sets and such.

**Comment by gacholio** [comment]
So it might be safer to check current for NULL rather than equality with the target.

**Comment by amicic** [comment]
I'm ok with null check against current, too. although 'm wondering why would one thread mess with other threads blocking monitor (but I don't have full understanding of blockingEnterObject)

At least, current == target holds in current code (othen java dumping):

![image](https://user-images.githubusercontent.com/18264984/121244227-9b274f80-c86c-11eb-8f30-4daa10dcc415.png)

**Comment by gacholio** [comment]
The code is walking all stacks and attempting to match up lock information with the frames, so it inevitably targets threads other than the current.

**Comment by gacholio** [comment]
I'm going ahead with the NULL check in the GC and using the target thread to fetch the VM in the macros.
