### ISSUE TITLE
copyright check is a bit silly

### ISSUE THREAD

**Issue by jsoref** [eclipse-openj9/openj9#12867]
The copyright check insisted that I write:

> # Copyright (c) 2021, 2021 Josh Soref

It really shouldn't make me do this. I'm not even sure that's technically valid.

**Comment by fjeremic** [comment]
I think the intent is for left number being the year the file was introduced, and right number being the last date it was modified. In this case if you created a new file it will be 2021, 2021. The first date will not change, and the second one will get updated as changes are made.

**Comment by jsoref** [comment]
Yeah. I get it. It's still wrong.

I can be as lazy as the next developer, if not lazier.

Sure, it's more work to parse things correctly and for the first bump, but I'm law extra words can result in things being thrown out, because if a word didn't belong, it shouldn't be there.

**Comment by mstoodle** [comment]
I know it looks weird, but the legal advice to the project was to make it clear that the file was both created and last modified in the named year. Both dates are relevant in copyright law (just looks funny when they are the same year).

**Comment by jsoref** [comment]
If legal signed-off / encouraged this, then, ok
