### ISSUE TITLE
xlinux builds blocked, extensions jdk8, jdk11 fatal: reference is not a tree

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12881]
The jdk8 and jdk11 xlinux builds are getting the following error since the Sunday night build. The SHAs haven't changed, they were the same for jdk8 in the Friday and Saturday night builds, which worked, and the same since Thursday night for jdk11.

https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_Nightly/18/ - ub16x64j98
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_OMR/18/ - ub16x64j91
```
21:03:16  Checking out Revision f7ae271495720acc3f3f84e7e6d568298ec73ddf (origin/openj9)
21:03:15   > git config remote.origin.url https://github.com/ibmruntimes/openj9-openjdk-jdk8.git # timeout=10
21:03:15   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
21:03:15   > git rev-parse origin/openj9^{commit} # timeout=10
21:03:16   > git config core.sparsecheckout # timeout=10
21:03:16   > git checkout -f f7ae271495720acc3f3f84e7e6d568298ec73ddf # timeout=30
21:03:44  Commit message: "Update OPENJDK_TAG to merged level jdk8u302-b05"
[Pipeline] sh
21:03:46  + git checkout f7ae271495720acc3f3f84e7e6d568298ec73ddf
21:03:46  fatal: reference is not a tree: f7ae271495720acc3f3f84e7e6d568298ec73ddf
```

https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_linux_Nightly/18/ - cent7-x64-2
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_linux_OMR/18/ - ub16x64j97
```
21:12:46  Checking out Revision 1fe213d07da436cd02249a6cd312dfb3eaf9e94b (origin/openj9)
21:12:44   > git config remote.origin.url https://github.com/ibmruntimes/openj9-openjdk-jdk11.git # timeout=10
21:12:44   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
21:12:44   > git rev-parse origin/openj9^{commit} # timeout=10
21:12:47   > git config core.sparsecheckout # timeout=10
21:12:47   > git checkout -f 1fe213d07da436cd02249a6cd312dfb3eaf9e94b # timeout=30
21:13:30  Commit message: "Merge pull request #404 from samasri/fix-11500"
[Pipeline] sh
21:13:32  + git checkout 1fe213d07da436cd02249a6cd312dfb3eaf9e94b
21:13:32  fatal: reference is not a tree: 1fe213d07da436cd02249a6cd312dfb3eaf9e94b
```

@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
My first guess is there is something wrong with the docker image.

**Comment by pshipton** [comment]
Is the clone is running in the container? The job that updates the reference repo probably ran on Saturday. 

In openjdk_cache I've fetched the latest jdk8, jdk11 on cent7-x64-1 to 5, and ub16x64j91 to 98, but it didn't help. The SHA for jdk8 changed today, but the build tonight still failed.
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_Nightly/19/console

If the clone is running in the container, the openjdk_cache in the container needs to be fixed.

**Comment by pshipton** [comment]
Rebuilding a clean cache on  ub16x64j98, I see if I can rebuilt on this machine, or I'll do all the xlinux machines to see if this helps.
https://openj9-jenkins.osuosl.org/view/Infrastructure/job/Update-Reference-Repos/4

**Comment by pshipton** [comment]
This takes forever. Is `git gc --aggressive --prune=all` really worth a little space? We should either remove it or make it optional with a parameter.

**Comment by pshipton** [comment]
After almost 2 hours, the cache is rebuilt, but the problem still occurs on ub16x64j98. Also, I think all the network traffic caused a number of other nightly jobs to fail, so I'll have to restart them all. We really need a better proxy.
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_Nightly/20/console

**Comment by jdekonin** [comment]
The container shouldn't be using the hosts cache at all, as it has its own.  The container hasn't been updated since May 28th and most of the hosts that received the job haven't been updated since the 28th either.  Note that the same container works just fine on the internal build environment which might indicate a plugin update??  Not sure this happened on the weekend though; last good build was June 5th 9pm.

I don't know why this has changed and I am not 100% sure this is the issue, but I think when the `/home/jenkins/workspace/Build_JDK8_x86-64_linux_Nightly` directory is added as a -w parameter by the jenkins plugin the workspace directory is created as owner root.  The container doesn't have a `/home/jenkins/workspace` directory.  I need to test more, but in the quick testing I did I was able to reproduce the same type of error as well as resolve by creating that directory with the correct ownership.

**Comment by jdekonin** [comment]
Something odd on ub16x64j98 which is all 3 of the Build_JDK8_x86-64_linux_Nightly failures.  The group id for jenkins changed to 1001 which doesn't exist.  I've chown'd the directory...going to retest in a bit.  This guest passed a containerize compile prior to June 5th.  No work occurred over the weekend on this system.  But I had modified this system prior to the docker container implementation such that the jenkins id was 1000:1000.  I am double checking all the systems

- [ ] cent7-x64-1
- [ ] cent7-x64-2
- [ ] cent7-x64-3
- [ ] cent7-x64-4
- [ ] cent7-x64-5
- [ ] cent7-x64-6
- [ ] ub16x64j91
- [ ] ub16x64j92
- [ ] ub16x64j94
- [ ] ub16x64j95
- [ ] ub16x64j97
- [ ] ub16x64j98
- [ ] ub18-x86-1
- [ ] ub18-x86-2

**Comment by jdekonin** [comment]
The ub16 and ub18 systems had jenkins uid:gid initially at 1001:1001, which I modified.  It seems something about how I did it wasn't complete on a few of the systems.  Specifically ub16x64j91, ub16x64j97 and ub16x64j98.  There was a failure on cent7-x64-2 and cent7-x64-4 that appears identical, but cent7 systems were not modified for uid/gid, I'll have to dig into those more.

Reviewing these jobs for failing systems
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_Nightly/
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_Personal/
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_OMR/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_linux_Nightly/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_linux_Personal/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_linux_OMR/

Jobs still fail on "fixed" systems...and even on the cent7 systems I didn't modify

**Comment by jdekonin** [comment]
Seems a new container with an updated openjdk_cache works...all the other stuff was just noise.

PR compiles are working
https://github.com/eclipse-openj9/openj9/pull/12900

**Comment by pshipton** [comment]
Closing assuming fixed.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau It's happening again
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_OMR/28/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_linux_OMR/27/

**Comment by AdamBrousseau** [comment]
Not sure this is resolved for openjdk prs
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_linux_Personal/74/console

**Comment by AdamBrousseau** [comment]
Another failure mode

>Docker infrastructure issues building x86 Java 11:
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_linux_Personal/108/console
>
> 09:37:44  + docker pull 428be5833257
 09:37:44  Using default tag: latest
 09:37:44  Error response from daemon: pull access denied for 428be5833257, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
>
>I’ve tried restarting but get the same error.

**Comment by pshipton** [comment]
Haven't see this for a while.
