### ISSUE TITLE
Re-enable NativeGCM lost due to OpenJDK update 8255557: Decouple GCM from CipherCore

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12896]
See https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/323

**Comment by ZainabF92** [comment]
PR [ibmruntimes/openj9-openjdk-jdk17#26](https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/26) fixes this issue

**Comment by vij-singh** [comment]
@ZainabF92 Is there anything else left to do here?

**Comment by pshipton** [comment]
The change is merged now, but got merged into the staging branch so needs to get through an acceptance build. I'll keep an eye on it and help it promote.

**Comment by pshipton** [comment]
Change is promoted and also merged to the 0.28 branch.
