### ISSUE TITLE
JDKnext openj9-staging is failing to build on all platforms

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#12930]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/12/
```
02:56:59  + make all
02:56:59  Building OpenJ9 Java Preprocessor
02:56:59  Building /home/jenkins/workspace/Build_JDKnext_ppc64le_linux_OpenJDK/build/linux-ppc64le-server-release/support/j9tools/jpp.jar
02:57:06  Generating J9JCL sources
02:57:06  Reading preprocess instructions from xml...
02:57:06  No configuration or non-existant configuration specified (Configurations are case sensitive)
02:57:06  PREPROCESS WAS NOT SUCCESSFUL
02:57:06  /home/jenkins/workspace/Build_JDKnext_ppc64le_linux_OpenJDK/closed/GensrcJ9JCL.gmk:49: recipe for target '/home/jenkins/workspace/Build_JDKnext_ppc64le_linux_OpenJDK/build/linux-ppc64le-server-release/make-support/j9jcl.done' failed
02:57:06  gmake[2]: *** [/home/jenkins/workspace/Build_JDKnext_ppc64le_linux_OpenJDK/build/linux-ppc64le-server-release/make-support/j9jcl.done] Error 1
```

Changes https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/1c808c4...da7073a

Likely related to https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/395d1a207c9c5bec124d1c7232fca3f4ef116452

@keithc-ca @JasonFengJ9 fyi

**Comment by pshipton** [comment]
@tajila fyi

**Comment by JasonFengJ9** [comment]
```
DEFAULT_VERSION_FEATURE=17DEFAULT_VERSION_FEATURE=18
```
I think a new JPP flag for JDK18 is needed.
Will look into it.

**Comment by keithc-ca** [comment]
Yes, we need a `JAVA18` configuration in `jpp_configuration.xml`, as should be expected.
We also need a mirror of https://github.com/openjdk/jdk17 to to be used to continue building Java 17.

**Comment by JasonFengJ9** [comment]
> We also need a mirror of https://github.com/openjdk/jdk17 to to be used to continue building Java 17.

This is tracked by `infrastructure/issues/5594`.
