### ISSUE TITLE
XSLT Transform fails silently after many iterations

### ISSUE THREAD

**Issue by jrobichaux** [eclipse-openj9/openj9#12943]
Java -version output
--------------------
OpenJDK Runtime Environment (build 1.8.0_282-b08)
Eclipse OpenJ9 VM (build openj9-0.24.0, JRE 1.8.0 Windows 8.1 amd64-64-Bit Compressed References 20210120_972 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08)

Summary of problem
------------------
We have a process that creates a javax Transformer object from an XSLT file and re-uses that transformer many times against many different XML files. It's all synchronous on a single thread, and it's been running without problem for years on J9 versions back to IBM J9 for Java 1.4 and 1.6.

We recently updated to OpenJDK J9 1.8.0_282-b08 and found that after many iterations of using the transformer over and over, eventually the transformer will stop working properly and no results will be returned. There are no errors and no indication that there was a problem, just an empty result.

I've narrowed it down to some XSLT that uses an <xsl:variable> and I attached a java file that reproduces the issue. I'm just running it using a command line of "java XslTest", nothing fancy.

[XslTest.java.txt](https://github.com/eclipse-openj9/openj9/files/6642769/XslTest.java.txt)

I've also downloaded several recent versions of the Windows 64 version of OpenJDK from https://adoptopenjdk.net and run the XslTest file using each, to see when the problem started happening. 

- jdk8u275 J9: no problem
- jdk8u282 J9: fails after several thousand iterations (usually between 3000 and 4000)
- jdk8u282 Hotspot: no problem
- jdk8u292 J9: no problem (I think)

So I'm only seeing this on J9, and there's a possibility that it got fixed in jdk8u292 but I'm a little nervous about the whole thing because I don't see any tickets that would seem to explain why this suddenly started happening or why it suddenly stopped. I want to say this is fixed, but I'd feel a lot better if I knew why it happened and what fixed it.

If there's any way that someone could take a look and try to figure out the cause and/or confirm the fix, I'd really appreciate it (as would my customers who use this code). Thanks.

**Comment by jrobichaux** [comment]
I guess I should point out that even though the test file takes a few thousand iterations to cause the problem, in real life with a more complex XSLT file processing much larger XML files, the problem can present itself after processing only 10 or 20 XML files. This is what we were seeing.

It also doesn't matter if I call transformer.reset() or if I use javax Templates to create a new Transformer each time. The only way around the problem is to use TransformerFactory to create new Transformers for each run, which is incredibly slow.

**Comment by pshipton** [comment]
I created a jit verbose log and then limited compilations until I found the compilation that causes the failure.
I narrowed it down to `"-Xjit:limitfile=(vlog.txt,418,418)"`. The test case works with the following compilation disabled. It's disabled in the attached log.
```
+ (warm) GregorSamsa.template$dot$0(Lcom/sun/org/apache/xalan/internal/xsltc/DOM;Lcom/sun/org/apache/xml/internal/dtm/DTMAxisIterator;Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;I)V @ 00007F5A5B8BEA28-00007F5A5B8C1782 OrdinaryMethod - Q_SZ=281 Q_SZI=281 QW=1412 j9m=0000000000124608 bcsz=166 GCR compThreadID=0 CpuLoad=261%(65%avg) JvmCpu=291%
```

[vlog.txt](https://github.com/eclipse-openj9/openj9/files/6649173/vlog.txt)

@fjeremic @0xdaryl can someone take a look pls to confirm this problem is resolved in the latest.

**Comment by fjeremic** [comment]
I reproduced the issue locally and took a look at the trace log which I will attach here. One `fail.trace` with 0.24 build and `pass.trace` with 0.26 build. Indeed the issue can be reproduced at IL generation via the following command line:

```
java "-Xjit:limit={GregorSamsa.template*}(traceFull,log=log.trace,lastOptIndex=0,optLevel=noopt,count=1,maskAddresses),disableAsyncCompilation" XslTest
```

Looking at the passing log the following tree is not present in the failing log:

```
n104n     astore  <parm 3 Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;>[#356  Parm] [flags 0x40000107 0x0 ]  [          *Masked*] bci=[-1,117,-] rc=0 vc=0 vn=- li=- udi=- nc=1
n75n        ==>aload
```

This issue has been fixed by #12213. Here is how the trees look like for more context in the passing log:

```
n86n      astore  <parm 3 Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;>[#356  Parm] [flags 0x40000107 0x0 ]  [          *Masked*] bci=[-1,91,-] rc=0 vc=0 vn=- li=- udi=- nc=1
n84n        ==>acalli
n90n      ResolveAndNULLCHK on n84n [#32]                                                     [          *Masked*] bci=[-1,94,-] rc=0 vc=0 vn=- li=- udi=- nc=1
n89n        calli  com/sun/org/apache/xml/internal/serializer/SerializationHandler.startDocument()V[#375  unresolved interface Method] (Interface class) [flags 0x400 0x0 ]  [          *Masked*] bci=[-1,94,-] rc=1 vc=0 vn=- li=- udi=- nc=2
n88n          aloadi  <vft-symbol>[#288  Shadow] [flags 0x18607 0x0 ]                         [          *Masked*] bci=[-1,94,-] rc=1 vc=0 vn=- li=- udi=- nc=1
n84n            ==>acalli
n84n          ==>acalli
n96n      ResolveAndNULLCHK on n92n [#32]                                                     [          *Masked*] bci=[-1,103,-] rc=0 vc=0 vn=- li=- udi=- nc=1
n95n        acalli  com/sun/org/apache/xalan/internal/xsltc/DOM.getNodeNameX(I)Ljava/lang/String;[#376  unresolved interface Method] (Interface class) [flags 0x400 0x0 ] (sharedMemory )  [          *Masked*] bci=[-1,103,-] rc=2 vc=0 vn=- li=- udi=- nc=3 flg=0x20
n94n          aloadi  <vft-symbol>[#288  Shadow] [flags 0x18607 0x0 ]                         [          *Masked*] bci=[-1,103,-] rc=1 vc=0 vn=- li=- udi=- nc=1
n130n           aload  <parm 1 Lcom/sun/org/apache/xalan/internal/xsltc/DOM;>[#354  Parm] [flags 0x40000107 0x0 ]  [          *Masked*] bci=[-1,98,-] rc=1 vc=0 vn=- li=- udi=- nc=0
n92n          aload  <parm 1 Lcom/sun/org/apache/xalan/internal/xsltc/DOM;>[#354  Parm] [flags 0x40000107 0x0 ]  [          *Masked*] bci=[-1,98,-] rc=1 vc=0 vn=- li=- udi=- nc=0
n93n          iload  <parm 4 I>[#357  Parm] [flags 0x40000103 0x0 ]                           [          *Masked*] bci=[-1,99,-] rc=1 vc=0 vn=- li=- udi=- nc=0
n99n      treetop                                                                             [          *Masked*] bci=[-1,107,-] rc=0 vc=0 vn=- li=- udi=- nc=1
n98n        call  com/sun/org/apache/xalan/internal/xsltc/runtime/AbstractTranslet.characters(Ljava/lang/String;Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;)V[#380  final virtual Method -288] (Abstract class) [flags 0x20500 0x0 ] ()  [          *Masked*] bci=[-1,107,-] rc=1 vc=0 vn=- li=- udi=- nc=3 flg=0x20
n91n          aload  <'this' parm LGregorSamsa;>[#353  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [          *Masked*] bci=[-1,97,-] rc=1 vc=0 vn=- li=- udi=- nc=0 flg=0x4
n95n          ==>acalli
n97n          aload  <parm 3 Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;>[#356  Parm] [flags 0x40000107 0x0 ]  [          *Masked*] bci=[-1,106,-] rc=1 vc=0 vn=- li=- udi=- nc=0
n103n     ResolveAndNULLCHK on n100n [#32]                                                    [          *Masked*] bci=[-1,113,-] rc=0 vc=0 vn=- li=- udi=- nc=1
n102n       calli  com/sun/org/apache/xml/internal/serializer/SerializationHandler.endDocument()V[#381  unresolved interface Method] (Interface class) [flags 0x400 0x0 ]  [          *Masked*] bci=[-1,113,-] rc=1 vc=0 vn=- li=- udi=- nc=2
n101n         aloadi  <vft-symbol>[#288  Shadow] [flags 0x18607 0x0 ]                         [          *Masked*] bci=[-1,113,-] rc=1 vc=0 vn=- li=- udi=- nc=1
n100n           aload  <parm 3 Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;>[#356  Parm] [flags 0x40000107 0x0 ]  [          *Masked*] bci=[-1,110,-] rc=2 vc=0 vn=- li=- udi=- nc=0
n100n         ==>aload
n104n     astore  <parm 3 Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;>[#356  Parm] [flags 0x40000107 0x0 ]  [          *Masked*] bci=[-1,117,-] rc=0 vc=0 vn=- li=- udi=- nc=1
n75n        ==>aload
```

We are saving the value of `parm 3` in `n75n` and overwriting this parameter in the subsequent treetop which is `n86n`. We then revert back the original value of `parm 3` with the last store at `n104n`. The code being removed in #12213 was incorrectly removing the store at `n104n` causing the observed problem.

@jrobichaux if you search for "Revert "Skip self-storing stores"" in the [release notes](https://github.com/eclipse-openj9/openj9/releases) you will see this landed in 0.26.0. Hope that helps!

**Comment by fjeremic** [comment]
Sorry forgot to upload. Here they are for future reference:

[pass.txt](https://github.com/eclipse-openj9/openj9/files/6651291/pass.txt)
[fail.txt](https://github.com/eclipse-openj9/openj9/files/6651292/fail.txt)

**Comment by jrobichaux** [comment]
That's amazing, and I can't believe you folks were able to diagnose that so quickly. Thank you **so much** @fjeremic @pshipton .
