### ISSUE TITLE
Implement JITServer version of new frontend query `isStable()`

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#12953]
PR #12893 is going to introduce a new frontend query: 
`virtual bool isStable(int cpIndex, TR_ResolvedMethod *owningMethod, TR::Compilation *comp);`
but the implementation for JITServer is going to be just a stub:
`virtual bool isStable(int cpIndex, TR_ResolvedMethod *owningMethod, TR::Compilation *comp) { return false; } // safe answer, might change in the future`
We need to provide a more detailed implementation which involves sending a message to the client to find the outcome of this call: `bool isStable = jitIsFieldStable(comp->fej9()->vmThread(), fieldClass, cpIndex);`
In the future, if performance requires it, we may implement some caching {ramClass --> {cpIndex --> isStable}}

**Comment by dmitry-ten** [comment]
The PR that introduced this query has been reverted for now: https://github.com/eclipse-openj9/openj9/pull/12972 due to some test failures, so this issue can be delayed until the commit is readded.
