### ISSUE TITLE
CMake cross-compile specs

### ISSUE THREAD

**Issue by dnakamura** [eclipse-openj9/openj9#12963]
Currently the UMA builds maintain separate specs for cross compile builds (eg `linux_aarch64.spec` and `linux_aarch64_cross.spec`). However, for CMake builds the distinction should not be required. I'm currently seeking opinions on if anyone sees a reason for keeping separate cross compile build specs for cmake.

tldr; does anyone have any reasons to maintain separate `*_cross` builds specs in CMake?

**Comment by fjeremic** [comment]
What is the advantage of one vs. the other?

**Comment by dnakamura** [comment]
benefits of cross-compile spec:
- if we ever need cross-compile specific options it provides an obvious place to put them (although they could also be put in the regular config wrapped in an `if()`
- (minor) does not require any changes to the jdk extension code
- ? (possibly something else I'm overlooking, hence opening the issue)

cons:
- Need to specifically add a file for every target we want to cross compile.
- caches folder is cluttered by a bunch of `*_cross.cmake` which are essentially empty

**Comment by gacholio** [comment]
Part of the build requires building and running the constant generator, which has to run on the target platform (in an emulator in the current ARM builds).

**Comment by pshipton** [comment]
Seems we can make do without them. They can always be added later if a reason surfaces.
