### ISSUE TITLE
Functional Test Failure: cmdLineTests ClassTestHelper.java fails always on Hotspot jdk17 and up

### ISSUE THREAD

**Issue by adamfarley** [eclipse-openj9/openj9#13001]
Summary: It looks like [this functional test](https://github.com/eclipse-openj9/openj9/blob/master/test/functional/cmdLineTests/utilshelper/src_110/org/openj9/test/classtests/ClassTestHelper.java) is failing 100% of the time on Hotspot builds across all platforms, but does *not* fail on OpenJ9.

Hotspot JDK16 output:
```
02:07:32      [javac] /home/jenkins/workspace/Test_openjdk16_hs_extended.functional_s390x_linux/aqa-tests/functional/cmdLineTests/utilshelper/src_110/org/openj9/test/classtests/ClassTestHelper.java:52: warning: [removal] defineAnonymousClass(Class<?>,byte[],Object[]) in Unsafe has been deprecated and marked for removal
02:07:32      [javac] 			Class<?> anonclass = unsafe.defineAnonymousClass(hostclass, content, null);
02:07:32      [javac] 			                           ^
```

Hotspot JDK17 Output:
```
02:08:02      [javac] Compiling 3 source files to C:\Users\jenkins\workspace\Test_openjdk17_hs_extended.functional_x86-64_windows\aqa-tests\functional\cmdLineTests\utils2\bin
02:08:03      [javac] C:\Users\jenkins\workspace\Test_openjdk17_hs_extended.functional_x86-64_windows\aqa-tests\functional\cmdLineTests\utilshelper\src_110\org\openj9\test\classtests\ClassTestHelper.java:52: error: cannot find symbol
02:08:03      [javac] 			Class<?> anonclass = unsafe.defineAnonymousClass(hostclass, content, null);
02:08:03      [javac] 			                           ^
02:08:03      [javac]   symbol:   method defineAnonymousClass(Class,byte[],<null>)
02:08:03      [javac]   location: variable unsafe of type Unsafe
```

Could this test be adjusted to work on Hotspot, or to be configured such that it is only run on OpenJ9, please?

Failure link
------------

Link to the failing test: https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk18_hs_extended.functional_x86-64_linux/3/console

Grinder: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=18&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk%2Fjdk-linux-x64-hotspot&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&NUM_MACHINES=3&OPENJDK_SHA=&TRSS_URL=&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=445&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None

Optional info
-------------

- intermittent failure (yes|no): no
- regression or new test:  new JDK version, old test.
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) : N/A

Failure output (captured from console output)
---------------------------------------------
See above.

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
@OscarQQ could you help to exclude the test compilation in the hotspot? Please also check the tests that reference this class. Thanks

**Comment by llxia** [comment]
#13011 is delivered. Close this issue.

**Comment by adamfarley** [comment]
Thanks Lan :)
