### ISSUE TITLE
No response when executing jps and jstack commands

### ISSUE THREAD

**Issue by bdk82924** [eclipse-openj9/openj9#13010]
1. The current Java program is running normally, and the dump file can be generated through kill -3
2. Nothing happens after executing the jps command
3. Nothing happens after executing the jstack command
4. In the Java code, there is no response when VirtualMachine.attach(pid) is executed

**Comment by JasonFengJ9** [comment]
@bdk82924 Can you cleanup the common subdirectory (by default) `.com_ibm_tools_attach` according to the platform [1], and re-try the test?
If the problem is still persistent, please provide Java version output in question. 

[1] https://www.eclipse.org/openj9/docs/attachapi/

**Comment by Wood-Xia** [comment]
I have same issue.
The java version is:
```
OpenJDK Runtime Environment (build 1.8.0_275-b01)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201110_845 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - b52d2ff7ee based on jdk8u275-b01)
```

**Comment by pshipton** [comment]
Is the process with PID 9 running OpenJ9? Does it disable attach API? Does the problem still occur if you use the latest build (jdk8u292)?

You can enable attach API logging, for jps/jstack, and also the process you are trying to attach to. See at the bottom of https://www.eclipse.org/openj9/docs/attachapi/. To apply the options to jps/jstack prepend them with `-J`.

**Comment by Wood-Xia** [comment]
> Is the process with PID 9 running OpenJ9? Does it disable attach API? Does the problem still occur if you use the latest build (jdk8u292)?
> 
> You can enable attach API logging, for jps/jstack, and also the process you are trying to attach to. See at the bottom of https://www.eclipse.org/openj9/docs/attachapi/. To apply the options to jps/jstack prepend them with `-J`.

[Is the process with PID 9 running OpenJ9?] Yes.
[Does it disable attach API?]  No.
[Does the problem still occur if you use the latest build (jdk8u292)?] Will try later.

**Comment by zcz3313** [comment]
> Is the process with PID 9 running OpenJ9? Does it disable attach API? Does the problem still occur if you use the latest build (jdk8u292)?
> 
> You can enable attach API logging, for jps/jstack, and also the process you are trying to attach to. See at the bottom of https://www.eclipse.org/openj9/docs/attachapi/. To apply the options to jps/jstack prepend them with `-J`.

I am on the same team with @Wood-Xia . We are using openj9 in docker. 
We have retry the test and see the log generated as below.
[openj9-diagnostic.zip](https://github.com/eclipse-openj9/openj9/files/6899433/openj9-diagnostic.zip)

`jps/jstack` still hang.

Also we found some strange things, there are multiple files named '9_xx' under directory `.com_ibm_tools_attach`.
![image](https://user-images.githubusercontent.com/8746495/127466775-015a8b92-6c9c-4179-b6e0-c1c3b208472c.png)
The main PID is 9, We are confusing of this.

Any idea would be helpful, thanks.

**Comment by pshipton** [comment]
It looks like some kind of permission problem related to docker. @JasonFengJ9 can you pls take a look.

**Comment by Wood-Xia** [comment]
@JasonFengJ9 Any update?

**Comment by JasonFengJ9** [comment]
Just back from vacation..

A quick experiment at my local `Linux x64` docker image (`MacOS` host) appears work as expected.
![ss-1](https://user-images.githubusercontent.com/17935151/128104043-49d76d57-fe76-48b2-b786-d9ac3d8ba2d9.png)
![ss-2](https://user-images.githubusercontent.com/17935151/128104058-daaff88e-15bf-4d62-bfd4-7267f19d8fb4.png)

The target process runs in one container, the attacher process runs in another container started via `docker exec -it container-id bash`.
The `PPID` of the target process is `PID 1` - `/bin/bash`.

@Wood-Xia can you run `ps -elf` to show the process `PPID`? In addition, could you share the docker launcher command line  for target/attacher processes?

**Comment by zcz3313** [comment]
> @Wood-Xia can you run `ps -elf` to show the process `PPID`? In addition, could you share the docker launcher command line for target/attacher processes?

We tried again.
`jps` hang as below, it couldn't show `jps` itself. Sometimes it couln't show anything even the main process.
![微信截图_20210805111538](https://user-images.githubusercontent.com/8746495/128285756-40907767-9f74-4ef0-8aab-5b3ac62e8f76.png)
the version of openj9 in image is 8u252, still not working.

And this is the `PPID` image as below.
![微信截图_20210805111631](https://user-images.githubusercontent.com/8746495/128285884-c1c933a3-3f34-4845-bb63-ae6d0261cbd6.png)

The `ENTRYPOINT` of our image's Dockerfile is
![entrypoint](https://user-images.githubusercontent.com/8746495/128286505-997f0f97-a27e-41fe-a5ee-371cdce6338a.png)
And the content of `startServer.sh' script is
![image](https://user-images.githubusercontent.com/8746495/128286630-b79f3f1e-df67-4956-9d60-2a1f74b58e8f.png)

As a result, the image will execute a bash script to check dependency and then start java.

**Comment by Wood-Xia** [comment]
@JasonFengJ9 

I'm not familiar with the openj9 attach API  implementation, just due to courious, I have a quick check some code under "jcl/src/java.base/share/classes/openj9/internal/tools/attach/target".

Along with the attach api logs, may I ask one questions?
Why create new target directory togethe with some file for same VM?
Below code snippet from AttachHandler.java, in the method "createFiles", I put one comment/question there.

According the log, looks this cause some timeout when jps trying to attach the target....

![image](https://user-images.githubusercontent.com/4701967/128496968-5d0a9759-5516-4f41-a763-8e3c20cb7d8e.png)

**Comment by JasonFengJ9** [comment]
https://github.com/eclipse-openj9/openj9/blob/d3ef784535a7c9cde53c6be0918432ed5f8b9ed5/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java#L209
`preserveId` is set to `false` here to address the stale IPC directories and files.

> Why create new target directory togethe with some file for same VM?

There is an Attach API doc [1] which provides reasonable description about the implementation.

It appears the docker launching in your environment created single digit process ID like `9` for different processes which caused AttachAPI confusion. I would have to reproduce the error (not yet) then figure out if the AttachAPI can adopt such scenarios.

[1] https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/package-info.java

**Comment by Wood-Xia** [comment]
@JasonFengJ9 

I have found the way to  reporduced this issue :)
If you restart the docker container,  which the java application does not catch the some signals like `SIGTERM` to shutdown gracefully,  then it's possible that leave some stale target file there.

For instance, if your docker entrypoint is one shell script without `exec`, the java application could not receive the `SIGTERM` when do `docker restart`.
Or, kill the java application due to whatever reason but the container still there.

I provided the docker file togethe with some relative scripts, please check at the https://gist.github.com/Wood-Xia/75aea814c6446f7a85437929d6ca2b2a

**Comment by Wood-Xia** [comment]
> @JasonFengJ9
> 
> I have found the way to reproduce this issue :)
> 
> If you restart the docker container(try several times help to reproduce it), which the java application does not catch some signals like `SIGTERM` to shutdown gracefully, then it's possible to leave some stale target file there.
> 
> For instance, if your docker entrypoint is one shell script and it does not start with `exec`, the java application could not receive the `SIGTERM` when do `docker restart`
> Or, kill the java application due to whatever reason but the container still there.
> 
> I provided the docker file togethe with some relative scripts, please check at the https://gist.github.com/Wood-Xia/75aea814c6446f7a85437929d6ca2b2a
> 
> If you have any question, let me know.

BTW, jstack also have some problem or inconvenience due to this, please also have a look.

**Comment by JasonFengJ9** [comment]
> If you restart the docker container(try several times help to reproduce it), which the java application does not catch some signals like SIGTERM to shutdown gracefully, then it's possible to leave some stale target file there.

Is it possible for docker script to remove the stale target file/directory before launching java app?

On the other hand, would you like to try a change
https://github.com/eclipse-openj9/openj9/blob/d3ef784535a7c9cde53c6be0918432ed5f8b9ed5/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java#L209
Invoking `TargetDirectory.createMyDirectory` with `preserveId` setting to `true`.
I can provide a patch for this java class if you can't rebuild the VM.

**Comment by Wood-Xia** [comment]
> > If you restart the docker container(try several times help to reproduce it), which the java application does not catch some signals like SIGTERM to shutdown gracefully, then it's possible to leave some stale target file there.
> 
> Is it possible for docker script to remove the stale target file/directory before launching java app?

Yes, that's  also the WA to my team now.
Adding removing the `/tmp/.com_ibm_tools_attach/*` if exiting, no stale target file/directory aftter restarting the docker now.
> 
> On the other hand, would you like to try a change
> https://github.com/eclipse-openj9/openj9/blob/d3ef784535a7c9cde53c6be0918432ed5f8b9ed5/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/AttachHandler.java#L209
> 
> 
> Invoking `TargetDirectory.createMyDirectory` with `preserveId` setting to `true`.
> I can provide a patch for this java class if you can't rebuild the VM.

Sure, that's also my initial proposal for fixing, and maybe it could be my first contribution to OpenJ9 if it's verified and accepted :)
I will try later and let you now the result.

**Comment by JasonFengJ9** [comment]
> Adding removing the /tmp/.com_ibm_tools_attach/* if exiting, no stale target file/directory aftter restarting the docker now.

Does it fix the issue reported?

> Sure, that's also my initial proposal for fixing, and maybe it could be my first contribution to OpenJ9 if it's verified and accepted :)

Great! please do so as per [1].

[https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md]
