### ISSUE TITLE
NoClassDefFoundError: openj9.dtfj module conflicts with uses of ibmjzos.jar on platforms other than z/OS

### ISSUE THREAD

**Issue by zjavaperf** [eclipse-openj9/openj9#13024]
Hi OpenJ9 team,

on z/OS, the JZOS classes are part of the **ibm.jzos** Java module, just as expected. On platforms other than z/OS, OpenJ9 only contains a stub of the `com.ibm.jzos.ZFile` class, which is part of the **openj9.dtfj** Java module. This leads to problems when JZOS is being used on platforms other than z/OS.

Please note that this is **not** a hypothetical use case - there is at least one customer that I am aware of who actually makes use of some JZOS classes on a non-z/OS operating system.

On OpenJ9 versions up to and including **0.24.0**, the following test works as expected:

```
marc@localhost:~$ jdk-11.0.10+9/bin/java -cp /path/to/ibmjzos.jar com.ibm.jzos.FileFactory
Error: Main method not found in class com.ibm.jzos.FileFactory, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```
Whereas on OpenJ9 versions **> 0.24.0**, the same test leads to an error:

```
marc@localhost:~$ jdk-11.0.11+9/bin/java -cp /path/to/ibmjzos.jar com.ibm.jzos.FileFactory
Error: Could not find or load main class com.ibm.jzos.FileFactory
Caused by: java.lang.ClassNotFoundException: com.ibm.jzos.FileFactory
```

The root cause of this problem seems to be the inclusion of the `com.ibm.jzos.ZFile` class into the **openj9.dtfj** Java module, which dictates the visibility of the `com.ibm.jzos` package.

Is there a way to restore the old behavior?

Cheers,
Marc

**Comment by pshipton** [comment]
I tagged this for 0.28 but if we have a solution ready and tested in master, there is still time to put it into 0.27

**Comment by zjavaperf** [comment]
0.27 would be awesome :+1: Thank you very much for taking care of this one, @keithc-ca and @pshipton!
