### ISSUE TITLE
Documented example to dynamically load ImageFactory doesn't work from a Java module

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#13027]
The documentation has an example of dynamically loading `ImageFactory`: https://www.eclipse.org/openj9/docs/interface_dtfj/#working-with-a-system-dump

Relevant snippet:

```
Class factoryClass = Class.forName("com.ibm.dtfj.image.j9.ImageFactory");
ImageFactory factory = (ImageFactory) factoryClass.newInstance();
image = factory.getImage(f);
```

Simplifying this example to:

```
package com.example;

public class Test {
	public static void main(String... args) throws Throwable {
		System.out.println(Class.forName("com.ibm.dtfj.image.j9.ImageFactory"));
	}
}
```

Using Java 11, this works fine on its own without modules:

```
% java -cp /Users/kevin/work/eclipse/eclipse202103javaee/workspace/TestDTFJ/bin/ com.example.Test         
class com.ibm.dtfj.image.j9.ImageFactory
```

However, if we add `Test` to a Java module with `module-info.java`:

```
module TestDTFJ {
}
```

And then try to run `Test` as a module, it fails with `ClassNotFoundException`:

```
% java --module-path /Users/kevin/work/eclipse/eclipse202103javaee/workspace/TestDTFJ/bin/ --module TestDTFJ/com.example.Test
Exception in thread "main" java.lang.ClassNotFoundException: com.ibm.dtfj.image.j9.ImageFactory
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:337)
	at TestDTFJ/com.example.Test.main(Test.java:5)
```

This seems to be resolved by adding a `requires` statement to the module:

```
module TestDTFJ {
	requires openj9.dtfj;
}
```

A documentation update about the `requires` statement would be useful.

**Comment by kgibm** [comment]
Created draft docs PR: https://github.com/eclipse-openj9/openj9-docs/pull/797

**Comment by pshipton** [comment]
If the only issue is the docs, this issue is better opened at the docs repo https://github.com/eclipse-openj9/openj9-docs/issues

**Comment by kgibm** [comment]
Apologies, this was originally opened because there was a question about whether it was working correctly but then after opening, Keith confirmed it was, so then I edited it to just a doc issue. I'll close this one and open a doc issue.

**Comment by kgibm** [comment]
Opened https://github.com/eclipse-openj9/openj9-docs/issues/798
