### ISSUE TITLE
Windows machines offline in jenkins

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13023]
We had some older issue about this, but I didn't find it.

There are a couple of Windows machines offline in jenkins which didn't come back from sanatize on Saturday night.
https://openj9-jenkins.osuosl.org/computer/win2012-x86-2/
https://openj9-jenkins.osuosl.org/computer/win2012-x86-9/

@AdamBrousseau @jdekonin fyi

**Comment by AdamBrousseau** [comment]
Master was quiet so I issued a restart. Coming back now. I expect the machines will connect once it's back.

**Comment by AdamBrousseau** [comment]
Rebooted number 6, online now
