### ISSUE TITLE
-XX:MaxRAMPercentage=90.0 won't get recognized

### ISSUE THREAD

**Issue by tolgamalachi** [eclipse-openj9/openj9#13057]
Hi,

I think the MaxRAMPercentage option with a decimal point does not get recognized. When I enter `-XX:MaxRAMPercentage=90` everyhting works fine. With `-XX:MaxRAMPercentage=90.0` I get the error `JVMJ9GC027E malformed option: '-XX:MaxRAMPercentage=90.0'`.

I can reproduce this with a simple hello-world-java class:

![grafik](https://user-images.githubusercontent.com/1275311/123318563-a1395380-d52f-11eb-948e-bc7637fff336.png)

### java -version

> payara@90b8e046a330:~$  java -version
> openjdk version "11.0.10" 2021-01-19
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
> Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Linux amd64-64-Bit Compressed References 20210120_910 (JIT enabled, AOT enabled)
> OpenJ9   - 345e1b09e
> OMR      - 741e94ea8
> JCL      - 0a86953833 based on jdk-11.0.10+9)

**Comment by dmitripivkine** [comment]
This is strange. The parameter of `-XX:MaxRAMPercentage` is taken as double (and always was). I just check Java 11 on my machine:
```
jdk-11.0.12+1/bin/java -XX:MaxRAMPercentage=90.0 -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.12+1-202105061821 (build 11.0.12+1-202105061821)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.12+1-202105061821 (build master-0991541a7, JRE 11 Linux amd64-64-Bit Compressed References 20210506_982 (JIT enabled, AOT enabled)
OpenJ9   - 0991541a7
OMR      - d96f2b34f
JCL      - 376b14b921 based on jdk-11.0.12+1)
```

**Comment by dmitripivkine** [comment]
This is output for 0.24.0 release I do have installed already (this is Large Heap version but code is the same):
```
jdk-11.0.10+9//bin/java -XX:MaxRAMPercentage=90.0 -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Linux amd64-64-Bit 20210120_821 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
```

**Comment by dmitripivkine** [comment]
@pshipton Do you have any idea what it might be? This option parameter is parsed as double since option creation. Seems this is German version

**Comment by dmitripivkine** [comment]
This is official release 0.24.0 from AdoptOpenJDK https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9_openj9-0.24.0/OpenJDK11U-jdk_x64_linux_openj9_11.0.10_9_openj9-0.24.0.tar.gz

```
jdk-11.0.10+9/bin/java -XX:MaxRAMPercentage=90.0 -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Linux amd64-64-Bit Compressed References 20210120_910 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
```

@tolgamalachi Would you please try this?

**Comment by dmitripivkine** [comment]
Would using German locale change decimal separator?

**Comment by tolgamalachi** [comment]
hi, thanks for your fast response.
you had the right idea, the locale seems to change the behaviour.

![openj9_maxPercentage_90,0](https://user-images.githubusercontent.com/1275311/123403283-e8aff600-d5a8-11eb-9521-80e05e25d397.PNG)

Changing the point to a comma works and changing the locale from `de_DE.utf8` to `en_US.utf8` enables the point instead of the comma.

Normally we use the Corretto JDK in our company and we wanted to evaluate openj9 so this behaviour seems to be different there. They dont change the behaviour based on the locale or they have a bug I don't know and don't even care about the locale. Our base images are identical with the same german locale.

So my question would be: Was this behaviour intended and maybe should be documented or would you maybe even consider changing it to be like the Corretto behaviour? I personally don't have a preference, just need to know so I can tweak our base images.

Thanks for your help =)

**Comment by dmitripivkine** [comment]
@pshipton @tajila GC parser uses `GET_DOUBLE_VALUE()` looks like locale dependable (expected to use comma instead of period for double value for German locale). Is it intended behaviour for command line option?

**Comment by pshipton** [comment]
The code is using `strtod()` in the end. Matching the reference behavior makes sense to me, in particular since `-XX:MaxRAMPercentage` was added for compatibility. Using locale dependent characters means you can't have a command line what works independent of locale, which is a problem. I'm guessing nobody wants to check the locale first in order to set an appropriate command line. 

Changing it will be a change in behavior if others have found and used the appropriate locale dependent characters, but likely this won't affect many users.

**Comment by pshipton** [comment]
I think there are other GC options which use doubles. Are they affected by the locale, and if not, what do they use to parse the input?

**Comment by dmitripivkine** [comment]
> I think there are other GC options which use doubles. Are they affected by the locale, and if not, what do they use to parse the input?

I believe there are two options only are parsed using double `-XX:MaxRAMPercentage=` and `-XX:InitialRAMPercentage=` and both of them use this helper
