### ISSUE TITLE
Add an option to log JITServer connection events

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse-openj9/openj9#13055]
Both the server and the client should have an option that, when enabled, will output messages indicating a successful connection between the server and the client. Right now if `-Xjit:verbose={JITServer}` is specified, such message will be produced on the server and the client will print a line for each compilation sent to the server. However, the JITServer verbose log prints out a lot of additional information that is not useful to a user who just wants to make sure that client and server were able to connect to each other. Such a scenario is possible for a JITServer workload  running in containerized environment, when the person deploying it wants to check that clients and server established connections successfully.
The option should be disabled by default, because we do not want to print random messages to a Java program's stderr/stdout unprompted.
There are 2 possible ways to implement this option:
1. Create a new `-XX` option, e.g. `-XX:LogJITServerConns`.
2. Add a new verbose tag for printing these messages, e.g. `-Xjit:verbose={JITServerConns}` .

The benefit of the first solution is that a user doesn't have to change `-Xjit` options, which normally shouldn't be modified by users. 
The second solution could take advantage of verbose logs more naturally.

**Comment by dmitry-ten** [comment]
@mpirvu, @EmanElsaban fyi.
There is also a choice between printing a message once per client-server pair, or once per connection created.
I think it makes more sense to print only once per client-server pair.

**Comment by mpirvu** [comment]
I agree that we want to print a message only for the first connect. This is easily done on the server. I am not if the client knows the identity of the server. We may have to add an UUID for server as well which is passed back (from the server to the client) when the server realizes its caches are empty and sends a message to get class unload information and CHTable information.

We should print messages about disconnects as well. I remember we already that, both at client and server.

I think that it's best we implement an XX options that the user can specify, but internally this translates into a specific verbose options. This way, the messages appear naturally to stderr, or to the verbose log if the user has specified one.
