### ISSUE TITLE
ub16x64j95 not enough free space causing test failures

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13074]
Machine disabled.
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_special.system_x86-64_linux_Release_testList_2/3/
```
systemtest-prereqs has been processed, and set to: /home/jenkins/workspace/Test_openjdk16_j9_special.system_x86-64_linux_Release_testList_2/jvmtest/system/systemtest_prereqsRetrieving amount of free space on drive containing /home/jenkins/workspace/Test_openjdk16_j9_special.system_x86-64_linux_Release_testList_2/aqa-tests/TKG/../TKG/output_16247627472849/LambdaLoadTest_special_J9_5m_3
There is 2050 Mb free

Test machine has only 2050 Mb free on drive containing /home/jenkins/workspace/Test_openjdk16_j9_special.system_x86-64_linux_Release_testList_2/aqa-tests/TKG/../TKG/output_16247627472849/LambdaLoadTest_special_J9_5m_3.

There must be at least 3Gb (3072Mb) free to be sure of capturing diagnostics
files in the event of a test failure.
```

@jdekonin @AdamBrousseau fyi

**Comment by AdamBrousseau** [comment]
Workspace, home and tmp look fine.
~25G used by docker images.
Thanks @rajdeepsingh1 for cleaning up.
Machine back online.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin This is the second machine with space problems due to docker. Are we missing some regular cleanup that needs to occur? Otherwise this problem will keep occurring on every machine as they fill up.

**Comment by AdamBrousseau** [comment]
We've had conversations about creating a periodic cleanup. I'll open an infra issue to track.
