### ISSUE TITLE
SharedClassesAPI_0 Windows An error has occurred while opening shared memory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13097]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/38
SharedClassesAPI_0
```
STF 01:38:50.992 - +------ Step 69 - DefaultLocUtilitiesJVMTI: Monitor workload processes
STF 01:38:50.992 - | Wait for processes to meet expectations
STF 01:38:50.992 - |   Processes: [WL1, WL2, WL3, WL4]
STF 01:38:50.992 - |
STF 01:38:50.992 - Monitoring processes: WL1 WL2 WL3 WL4
STF 01:38:51.331 - **FAILED** Process WL3 ended with exit code (1) and not the expected exit code/s (0)
```
67.WL3.stderr
```
JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC662I Error recovery: destroyed semaphore set associated with shared class cache.
JVMSHRC840E Failed to start up the shared cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by pshipton** [comment]
Seems a disk space problem on win2012-x86-1. @jdekonin @AdamBrousseau 

https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/39/ - win2012-x86-1
SharedClassesAPI_0
```
STF 21:44:44.728 - +------ Step 69 - DefaultLocUtilitiesJVMTI: Monitor workload processes
STF 21:44:44.728 - | Wait for processes to meet expectations
STF 21:44:44.729 - |   Processes: [WL1, WL2, WL3, WL4]
STF 21:44:44.729 - |
STF 21:44:44.729 - Monitoring processes: WL1 WL2 WL3 WL4
STF 21:44:45.084 - **FAILED** Process WL1 ended with exit code (1) and not the expected exit code/s (0)
```
64.WL1.stderr
```
JVMSHRC254E Error setting length of shared class cache file
JVMSHRC336E Port layer error code = -105
JVMSHRC337E Platform error message: (112) There is not enough space on the disk.
JVMSHRC231E Error setting shared class cache file length
JVMSHRC336E Port layer error code = -105
JVMSHRC337E Platform error message: (112) There is not enough space on the disk.
JVMSHRC840E Failed to start up the shared cache.
```

**Comment by pshipton** [comment]
I haven't seen it recently.

**Comment by pshipton** [comment]
@AdamBrousseau there is another one on win2012-x86-3. I'm not sure if you did anything to clear space last time?
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_0/151

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_0/158 - win2012-x86-11

67.WL3.stderr
```
JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC662I Error recovery: destroyed semaphore set associated with shared class cache.
JVMSHRC840E Failed to start up the shared cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_1/157 - win2012-x86-3

65.WL1.stderr
```
JVMSHRC254E Error setting length of shared class cache file
JVMSHRC336E Port layer error code = -105
JVMSHRC337E Platform error message: (112) There is not enough space on the disk.
JVMSHRC231E Error setting shared class cache file length
JVMSHRC336E Port layer error code = -105
JVMSHRC337E Platform error message: (112) There is not enough space on the disk.
JVMSHRC840E Failed to start up the shared cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_0/159 - win2012-x86-3

68.WL4.stderr
```
JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC662I Error recovery: destroyed semaphore set associated with shared class cache.
JVMSHRC840E Failed to start up the shared cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by AdamBrousseau** [comment]
Cleaned up a bit on 3. 4.5GB free now. Also rebooted 5 because it wasn't connected.

**Comment by pshipton** [comment]
Thanks. I'll close until it's seen again.

**Comment by pshipton** [comment]
Still a space issue on win2012-x86-11

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_1/162
SharedClassesAPI_0

66.WL2.stderr
```
JVMSHRC254E Error setting length of shared class cache file
JVMSHRC336E Port layer error code = -105
JVMSHRC337E Platform error message: (112) There is not enough space on the disk.
JVMSHRC231E Error setting shared class cache file length
JVMSHRC336E Port layer error code = -105
JVMSHRC337E Platform error message: (112) There is not enough space on the disk.
JVMSHRC840E Failed to start up the shared cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by AdamBrousseau** [comment]
Cleaned up a bit. Free space was at 2.5G now at 5.9G.
For ref, the following are not needed since we use everything out of /cygdrive/f/Users/jenkins:
```
C:\openjdk\openjdk_cache 
/home/jenkins/openjdk_cache
/home/jenkins/bootjdks
/home/jenkins/workspace
```

**Comment by pshipton** [comment]
@AdamBrousseau Windows machines are now failing to build, 3 different machines so I'm guessing they are all affected.
```
13:03:51  + git clone -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk11.git . --reference /home/jenkins/openjdk_cache
13:03:51  Cloning into '.'...
13:03:51  fatal: reference repository '/home/jenkins/openjdk_cache' is not a local repository.
```

https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_windows_OMR/21/
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_windows_OMR/138/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_windows_OMR/139/

**Comment by AdamBrousseau** [comment]
My mistake, `/home/jenkins/openjdk_cache` is needed. It's the one on F that isn't needed. Will update my previous comment and fix the machines.

**Comment by AdamBrousseau** [comment]
Refresh running
https://openj9-jenkins.osuosl.org/job/Update-Reference-Repos/30/console
Builds queued up should work once they get a machine.

**Comment by keithc-ca** [comment]
Perhaps builds should create that cache if it doesn't already exist?

**Comment by AdamBrousseau** [comment]
Could add that. It should only fail on Windows and probably zos. This is because they use git directly rather than the scm pipeline step which will ignore a non existent reference directory. And windows only uses it because of https://issues.jenkins.io/plugins/servlet/mobile#issue/JENKINS-54612
The problem with adding it mid flight is you probably only want to wait for the repo you need rather than all of them which creates an incomplete cache. We already have a job that runs weekly to populate and update all the machines. The reason it failed today was my misunderstanding which led me to remove the cache on disk.

**Comment by keithc-ca** [comment]
I'm satisfied with the automation we have; let's just not have any more misunderstandings. ;-)
