### ISSUE TITLE
TKG failing to run Windows 32-bit testing

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13106]
Windows 32-bit testing failing to run since Wed night. https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK8/53/
Guessing https://github.com/adoptium/TKG/pull/216 is causing the problem.
@renfeiw @smlambert @llxia 
```
22:49:11  Exception in thread "main" java.lang.NullPointerException
22:49:11  	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
22:49:11  	at java.util.regex.Matcher.reset(Matcher.java:309)
22:49:11  	at java.util.regex.Matcher.<init>(Matcher.java:229)
22:49:11  	at java.util.regex.Pattern.matcher(Pattern.java:1093)
22:49:11  	at org.testKitGen.TestInfoParser.checkPlat(TestInfoParser.java:226)
22:49:11  	at org.testKitGen.TestInfoParser.parseVariation(TestInfoParser.java:295)
22:49:11  	at org.testKitGen.TestInfoParser.parse(TestInfoParser.java:93)
22:49:11  	at org.testKitGen.PlaylistInfoParser.parse(PlaylistInfoParser.java:106)
22:49:11  	at org.testKitGen.ParallelGenVisitor.visit(ParallelGenVisitor.java:34)
22:49:11  	at org.testKitGen.DirectoryWalker.traverse(DirectoryWalker.java:77)
22:49:11  	at org.testKitGen.DirectoryWalker.traverse(DirectoryWalker.java:70)
22:49:11  	at org.testKitGen.DirectoryWalker.traverse(DirectoryWalker.java:70)
22:49:11  	at org.testKitGen.DirectoryWalker.traverse(DirectoryWalker.java:70)
22:49:11  	at org.testKitGen.MainRunner.genParallelList(MainRunner.java:54)
22:49:11  	at org.testKitGen.MainRunner.main(MainRunner.java:34)
```
good:
OpenJ9: 09971ec
OMR: ec902f6
OpenJDK8: c0b29ca - openj9-openjdk-jdk8
https://github.com/adoptium/TKG.git 6d2b1c17a2bebc5d1a31be38ae01965704b74da4
https://github.com/adoptium/aqa-tests.git 97830a294fb593edb3486b82fce39c99f18858c3

bad:
OpenJ9: 22de6cd
OMR: 45201fd
OpenJDK8: b75b281 - openj9-openjdk-jdk8
https://github.com/adoptium/TKG.git 7af3fa1ac1a86750bc51c11c842cd537b2d39655
https://github.com/adoptium/aqa-tests.git 97830a294fb593edb3486b82fce39c99f18858c3

https://github.com/eclipse-openj9/openj9/compare/09971ec...22de6cd
https://github.com/eclipse/omr/compare/ec902f6...45201fd - just an aarch64 change
https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/c0b29ca...b75b281
https://github.com/adoptium/TKG/compare/6d2b1c17a...7af3fa1ac1

**Comment by renfeiw** [comment]
I am looking into it now.

**Comment by renfeiw** [comment]
Opened PR to fix this issue: https://github.com/adoptium/TKG/pull/223

**Comment by llxia** [comment]
Windows 32-bit testing is back to normal. Close this issue.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK8/57/
