### ISSUE TITLE
Update jitGetClassInClassloaderFromUTF8 to find hidden classes

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13134]
The JIT currently uses `jitGetClassInClassloaderFromUTF8` to look up classes based on signatures. It is need to get the type of method args. This API uses `hashClassTableAt` to lookup classes, however, if it is looking up a hidden class it returns NULL. 

We need to provide a way for the JIT to find hidden classes.

Given how often `hashClassTableAt` is used we may want to create a new version `hashClassTableAtImpl` that has no HIDDEN_CLASS checks which can be called by the `hashClassTableAt` version.

**Comment by tajila** [comment]
@hangshao0 Please take a look at this

**Comment by tajila** [comment]
FYI @gacholio @r30shah

**Comment by hangshao0** [comment]
> The JIT currently uses jitGetClassInClassloaderFromUTF8 to look up classes based on signatures.

The hidden classes are keyed on the rom address rather than the name. 
https://github.com/eclipse-openj9/openj9/blob/fdeac8f10f26a2532513534d3c526af07f933684/runtime/vm/KeyHashTable.c#L211-L216

Does JIT have access to the romclass ? @r30shah 

If yes, we can remove `J9ROMCLASS_IS_HIDDEN()` check in hashClassTableAt() to let it return hidden classes. Then JIT can use romaddress to find the ramClass.

**Comment by r30shah** [comment]
> Does JIT have access to the romclass ? @r30shah
In the case when JIT is iterating through the list of parameter symbols and if it is class (We inspect signature to check that) [1], at this time we do not know the romClass, and use signature to get the class. 


[1]. https://github.com/eclipse-openj9/openj9/blob/fdeac8f10f26a2532513534d3c526af07f933684/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L5577-L5585

**Comment by hangshao0** [comment]
From JEP 371:

> The hidden class cannot be used directly by bytecode instructions in other classes because it cannot be referenced nominally, that is, by name

**Comment by gacholio** [comment]
So does that mean this is unnecessary as a hidden class can never appear in a method signature?

**Comment by r30shah** [comment]
So providing more context where I am seeing the issue. We build the parameters list in [1] where for non static method, we fill first parameter slot with the signature of the class that method belongs to, so while inlining that method when we build argInfo [2] we simply query the VM to get the class from the signature.
 
FYI @vijaysun-omr  

[1]. https://github.com/eclipse-openj9/openj9/blob/fdeac8f10f26a2532513534d3c526af07f933684/runtime/compiler/env/j9method.cpp#L7008-L7025
[2]. https://github.com/eclipse-openj9/openj9/blob/fdeac8f10f26a2532513534d3c526af07f933684/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L5577-L5585

**Comment by hangshao0** [comment]
> So does that mean this is unnecessary as a hidden class can never appear in a method signature?

That is what I mean. 

How JIT deals with anonymous classes in Java 8 and 11 ? They are not in the hashtable IIRC, `jitGetClassInClassloaderFromUTF8()` won't find them, which is similar to hidden classes here.

**Comment by gacholio** [comment]
I think it would be preferrable for the JIT to special case this in some fashion instead of changing the APIs in the VM to deal with the general case which is only used in this one specific case.

**Comment by tajila** [comment]
> where for non static method, we fill first parameter slot with the signature of the class that method belongs to, so while inlining that method when we build argInfo

If you have the j9method you can get the type of the receiver by j9method->constantPool->ramClass

**Comment by r30shah** [comment]
Thanks a lot @hangshao0  @tajila  and @gacholio  for the help and suggestions. I was able to fix the issue from the JIT side in following pull request.
https://github.com/eclipse-openj9/openj9/pull/13169
