### ISSUE TITLE
Handle unsupported  -Xlog options

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13148]
JDK17 tests are with ` -Xlog:all=warning:stdout`. J9 doesnt fully support this option resulting in `JVMJ9VM085W Malformed option: '-Xlog:all=warning:stdout'` This is causing test failures.

We need to modify the JVM behaviour to ignore this, or provide a workaround that can disable the error message.

**Comment by JasonFengJ9** [comment]
@tajila This also occurred at builds w/o OJDK MH as per https://github.com/eclipse-openj9/openj9/issues/12580.

This message is an unrecognized warning
https://github.com/eclipse-openj9/openj9/blob/54e151112585b88a53b463fc8df96e9418ee8fef/runtime/vm/jvminit.c#L6120-L6126

It seems that the test output containing this warning message actually failed something else [1]
```
18:21:51  >'-1'< not equal to '10'
18:21:51  java.lang.Throwable
18:21:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:554)
18:21:51  	at Basic.fail(Basic.java:2814)
18:21:51  	at Basic.fail(Basic.java:2815)
18:21:51  	at Basic.equal(Basic.java:2821)
18:21:51  	at Basic$12.run(Basic.java:2214)
18:21:51  java.lang.AssertionError: Some tests failed
18:21:51  	at Basic.main(Basic.java:2826)
18:21:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:21:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
18:21:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:21:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
18:21:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
18:21:51  	at java.base/java.lang.Thread.run(Thread.java:883)

18:21:51  >'-1'< not equal to '74'
18:21:51  java.lang.Throwable
18:21:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:554)
18:21:51  	at Basic.fail(Basic.java:2814)
18:21:51  	at Basic.fail(Basic.java:2815)
18:21:51  	at Basic.equal(Basic.java:2821)
18:21:51  	at Basic$12.run(Basic.java:2214)
```
Again, similar failure is observed at `JDK17` internal builds such as `Test_openjdk17_j9_sanity.openjdk_s390x_linux/40`, and is not specific to OJDK MH enabled VM.

[1] https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/2/consoleFull

**Comment by pshipton** [comment]
I don't think it's valid to change the VM to ignore the option, user's expects it to do something which OpenJ9 doesn't support, so the error is valid. We can add a new option like `-XX:+IgnoreUnrecognizedXlog`, or modify the tests. If we need to modify the tests anyway to add `-XX:+IgnoreUnrecognizedXlog`, we might as well just remove the -Xlog option.

**Comment by JasonFengJ9** [comment]
> we might as well just remove the -Xlog option.

Yeah, it passes after removal of following two lines [1][2] containing `-Xlog:all=warning:stdout`.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/8f685d79229761af7b795190e6bc1663799c0d2b/test/jdk/java/lang/ProcessBuilder/Basic.java#L2169
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/8f685d79229761af7b795190e6bc1663799c0d2b/test/jdk/java/lang/ProcessBuilder/Basic.java#L2174

**Comment by pshipton** [comment]
Resolved by https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/12 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/343
