### ISSUE TITLE
test failures - Success condition was not found: [Output match: (java|openjdk) version]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13153]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.functional_x86-64_linux_testList_1/72/`:
```
semeru version "1.8.0_302-internal"
Semeru Runtime Environment (build 1.8.0_302-internal-202107090233-b07)
Eclipse OpenJ9 VM (build master-e56cf3054, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210709_175 (JIT enabled, AOT enabled)
OpenJ9   - e56cf3054
OMR      - bdee22f4b
JCL      - 4b45aeb5 based on jdk8u302-b07)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=testSCCMLExpireAndListALLCaches_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_sanity.functional_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F175%2FSemeru-debugimage_x64_linux_2021-07-09-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F175%2FSemeru-testimage_x64_linux_2021-07-09-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F175%2FSemeru-jre_x64_linux_2021-07-09-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-x64-openj9%2F175%2FSemeru-jdk_x64_linux_2021-07-09-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=104&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-07-09T03:36:03.400Z] Testing: Expire & List 1: Create nonpersistent shared cache
[2021-07-09T03:36:03.400Z] Test start time: 2021/07/08 20:36:02 Pacific Standard Time
[2021-07-09T03:36:03.400Z] Running command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_testList_1/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=ShareClassesCMLTestsNP,nonpersistent -version
[2021-07-09T03:36:03.400Z] Time spent starting: 6 milliseconds
[2021-07-09T03:36:03.400Z] Time spent executing: 304 milliseconds
[2021-07-09T03:36:03.401Z] Test result: FAILED
[2021-07-09T03:36:03.401Z]  [ERR] semeru version "1.8.0_302-internal"
[2021-07-09T03:36:03.401Z]  [ERR] Semeru Runtime Environment (build 1.8.0_302-internal-202107090233-b07)
[2021-07-09T03:36:03.401Z]  [ERR] Eclipse OpenJ9 VM (build master-e56cf3054, JRE 1.8.0 Linux amd64-64-Bit 20210709_175 (JIT enabled, AOT enabled)
[2021-07-09T03:36:03.401Z]  [ERR] OpenJ9   - e56cf3054
[2021-07-09T03:36:03.401Z]  [ERR] OMR      - bdee22f4b
[2021-07-09T03:36:03.401Z]  [ERR] JCL      - 4b45aeb5 based on jdk8u302-b07)
[2021-07-09T03:36:03.401Z] >> Success condition was not found: [Output match: (java|openjdk) version]
[2021-07-09T03:36:03.401Z] >> Failure condition was not found: [Output match: Unhandled Exception]
[2021-07-09T03:36:03.401Z] >> Failure condition was not found: [Output match: Exception:]
```

This is due to the introduction of new product name `semeru` (Welcome **Semeru**!).
The test need to accommodate new product name.

fyi @pshipton @AdamBrousseau

**Comment by JasonFengJ9** [comment]
All tests checking `(java|openjdk) version` failed.

**Comment by llxia** [comment]
@OscarQQ Could you do a search in functional tests (mostly cmdline tests) and update the success condition to include semeru? For example: from `(java|openjdk) version` to `(java|openjdk|semeru) version`

**Comment by JasonFengJ9** [comment]
Note: a PR https://github.com/eclipse-openj9/openj9/pull/13156 is being reviewed.

**Comment by llxia** [comment]
Thanks @JasonFengJ9 . :)
