### ISSUE TITLE
s390 ub18 and ub20 machines can't resolve github.com

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13159]
They must have been fine in the nightly builds last night, but not working this morning. I've disabled them all for now.

Recent examples
https://openj9-jenkins.osuosl.org/job/Grinder_testList_2/6
https://openj9-jenkins.osuosl.org/job/Grinder_testList_2/7
https://openj9-jenkins.osuosl.org/job/Grinder_testList_2/8
https://openj9-jenkins.osuosl.org/job/Grinder_testList_2/9

**Comment by AdamBrousseau** [comment]
I can ping github from ub18-1. It does take about 5 seconds before the pinging starts. I assume it is doing dns.
On ub18-2 the dns fails
on ub20-[1,2] dns fails.
I will get Raj to take a look.

**Comment by rajdeepsingh1** [comment]
I've added github.com manually to /etc/hosts for the following machines, which should resolve the name resolution issues:

ub18-390-1
ub18-390-2 
ub20-390-1
ub20-390-2


@pshipton

**Comment by pshipton** [comment]
I've re-enabled the machines and started some PR testing that should test most of them.

**Comment by AdamBrousseau** [comment]
I think etc/hosts is only a temp solution while the dns problems are resolved. Cindy said there didn't appear to be any issues. I tested removing the entry and all 4 hosts seem fine. Also did a reboot.

**Comment by pshipton** [comment]
More network problems https://github.com/eclipse-openj9/openj9/issues/12673#issuecomment-880861702
