### ISSUE TITLE
"module jdk.attach does not export com.ibm.tools.attach.attacher"

### ISSUE THREAD

**Issue by idlewis** [eclipse-openj9/openj9#13236]
Java -version output
--------------------

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK Client VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode)

Summary of problem
------------------
The code snippet below runs fine on a Hotspot Java 16 VM, but fails on an OpenJ9 Java 16
```
VirtualMachine vm = VirtualMachine.attach(vmd);
vm.toString(); // This works
Class vmClass = vm.getClass();
Method vmMethod = vmClass.getMethod("toString");
String vmString = (String)vmMethod.invoke(vm); // This causes illegal reflective access error
```

The error is:
```
Exception in thread "main" java.lang.IllegalAccessException: class TestVM cannot access class com.ibm.tools.attach.attacher.OpenJ9VirtualMachine (in module jdk.attach) because module jdk.attach does not export com.ibm.tools.attach.attacher to unnamed module @e26aa2a1
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:687)
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)
        at TestVM.main(TestVM.java:16)
```

This is causing me some issues as I have some wrapper code which aims to get the attach API working across multiple Java vendors/versions. It feels like the IBM attach classes should be exported by the jdk.attach module

**Comment by JasonFengJ9** [comment]
_The OpenJ9 implementation of the Attach API is equivalent to the reference implementation (API documentation is available on the Oracle website). However, you can only use the Attach API to connect to another OpenJ9 VM._ [1]

Thanks for trying OpenJ9 Attach API though.

[1] https://www.eclipse.org/openj9/docs/attachapi/

**Comment by JasonFengJ9** [comment]
Closing for now.

**Comment by pshipton** [comment]
I'm reopening this. It appears that while sun.tools.attach isn't exported, it is "open". While com.ibm.tools.attach.attacher is not. So far I haven't figured out how sun.tools.attach comes to be "open".

**Comment by pshipton** [comment]
Tracing shows
```
[0.052s][debug][module] add_module_exports_to_all_unnamed(): package sun/tools/attach in module jdk.attach is exported to all unnamed modules
```
which doesn't correspond to the module-info
```
  requires java.base;
  requires jdk.internal.jvmstat;
  exports com.sun.tools.attach;
  exports com.sun.tools.attach.spi;
  exports sun.tools.attach to
    jdk.jcmd;
  uses com.sun.tools.attach.spi.AttachProvider;
  provides  com.sun.tools.attach.spi.AttachProvider with
    sun.tools.attach.AttachProviderImpl;
}
```

**Comment by JasonFengJ9** [comment]
> [0.052s][debug][module] add_module_exports_to_all_unnamed(): package sun/tools/attach in module jdk.attach is exported to all unnamed modules

Yeah, this is strange, and doesn't match the OpenJDK module `jdk.attach` `module-info`.
I misinterpreted the RI `-version` output of the issue description.
Will have another look.

**Comment by keithc-ca** [comment]
I suggest the proper way to use reflection is via public classes, not the implementation class. This is a common element of dealing with modules. Just one line should change:
```
Class vmClass = VirtualMachine.class;
```

**Comment by pshipton** [comment]
The add_module_exports_to_all_unnamed is a red herring. It only occurs when `--illegal-access=permit` is set, yet the `--illegal-access` setting doesn't affect the behavior of the test case.

**Comment by pshipton** [comment]
The difference is that OpenJ9VirtualMachine implements toString(), while the Hotspot VirtualMachineImpl/HotSpotVirtualMachine classes do not.

**Comment by keithc-ca** [comment]
The fact that OpenJ9VirtualMachine implements toString() is not visible to the sample code. The direct call is using the API defined by VirtualMachine. Limiting the reflection to that class would also allow the reflective call to toString() to work.

**Comment by pshipton** [comment]
You don't think the implementation of OpenJ9VirtualMachine.toString() is causing the difference in behavior when running the test case on OpenJ9? i.e. causing the IllegalAccessException?

We could remove the OpenJ9VirtualMachine.toString() method for compatibility, but that could break existing OpenJ9 users. The default implementation in VirtualMachine prints the provider, colon space id, while OpenJ9 implementation prints the  VirtualMachine instance, semicolon id. I agree with Keith the best solution is what he suggested in https://github.com/eclipse-openj9/openj9/issues/13236#issuecomment-896098627. I'll go ahead and close this.

**Comment by keithc-ca** [comment]
The bytecode of the sample would have no reference to `OpenJ9VirtualMachine`; the direct call is to `VirtualMachine.toString()`. It's only the reflective code that requires access to `OpenJ9VirtualMachine`.
