### ISSUE TITLE
-XX:HeapDumpPath support not documented

### ISSUE THREAD

**Issue by gjdeval** [eclipse-openj9/openj9#13249]
According to https://github.com/eclipse-openj9/openj9/pull/2508  the option -XX:HeapDumpPath is supported by OpenJ9, but it does not appear in the documentation at https://www.eclipse.org/openj9/docs

**Comment by pshipton** [comment]
Can you please re-create this issue in https://github.com/eclipse-openj9/openj9-docs

**Comment by gjdeval** [comment]
done   https://github.com/eclipse-openj9/openj9-docs/issues/812
