### ISSUE TITLE
Extend line endings check

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#13246]
Changes in pull requests are checked for proper line endings: LF for most text files or CR/LF for some Windows-specific text files.

I propose that we extend those checks to ensure that each added or modified line has no trailing whitespace or unnecessary blank lines at EOF.

Since the inception of this project I have yet to see a legitimate need for trailing whitespace in any file. On the other hand, trailing whitespace can lead to some difficult to recognize problems.

Consider this sequence in [jvmtiMethod.c](https://github.com/eclipse-openj9/openj9/blob/master/runtime/jvmti/jvmtiMethod.c#L750-L756):
```
#define FLIP_32BIT(index) \
	do { \
		bytecodes[(index) + 0] = j9Bytecodes[(index) + 3]; \
		bytecodes[(index) + 1] = j9Bytecodes[(index) + 2]; \
		bytecodes[(index) + 2] = j9Bytecodes[(index) + 1]; \
		bytecodes[(index) + 3] = j9Bytecodes[(index) + 0]; \
	} while(0)
```
If the first line had trailing whitespace (after the `\`), `gcc` would complain:
```
jvmtiMethod.c:750:27: error: backslash and newline separated by space [-Werror]
 #define FLIP_32BIT(index) \
```
On the other hand, if a space was present after the second of these lines in [OpenJ9.gmk](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/OpenJ9.gmk#L433-L434):
```
	+BOOT_JDK=$(BOOT_JDK) $(EXPORT_COMPILER_ENV_VARS) OPENJDK_VERSION_NUMBER_FOUR_POSITIONS=$(VERSION_NUMBER_FOUR_POSITIONS) \
		$(MAKE) $(MAKE_ARGS) -C $(OUTPUTDIR)/vm -f $(OPENJ9_TOPDIR)/runtime/buildtools.mk \
```
an UMA build would fail:
```
cc      -o .o
cc: fatal error: no input files
compilation terminated.
<builtin>: recipe for target '.o' failed
```
Not many people will successfully trace that back to the offending space.

**Comment by AdamBrousseau** [comment]
Are there existing 3rd party tools or linters that could replace either the line-endings check or the whitespace check or both? We might get much more value out of implementing something 3rd party than maintaining and expanding our homegrown solution.

Search finds a bunch but here is an example
https://github.com/github/super-linter

More searching suggests there exists linters for linebreak-style and for trailing whitespace.

**Comment by keithc-ca** [comment]
My initial work in this direction can be seen at https://github.com/keithc-ca/openj9/tree/line-endings. Effectively, it just runs two additional commands:
```
git config core.whitespace blank-at-eof,blank-at-eol,cr-at-eol,space-before-tab
git diff --check origin/${ghprbTargetBranch} HEAD
```

**Comment by keithc-ca** [comment]
super-linter seems a rather heavy-weight solution; the latest image is 1.52GB and even the 'slim' version is 1.2 GB according to https://hub.docker.com/r/github/super-linter/tags?page=1&ordering=last_updated.

**Comment by keithc-ca** [comment]
```
$ docker images
REPOSITORY                                TAG       IMAGE ID       CREATED        SIZE
github/super-linter                       latest    a0d462a53698   20 hours ago   4.93GB
[...]
```

**Comment by keithc-ca** [comment]
All the 'lint' tools I found seem to be language-specific and didn't seem to restrict their attention to just added or modified parts of changes; they would seem more suitable for a job more like a 'build'.

**Comment by DanHeidinga** [comment]
I ran across https://pre-commit.com/ today and thought of this issue.  It seems to provide end-of-line checkers among others and though its primary purpose is pre-commit checks, it also integrates into existing CI systems, like github actions, so adding it to our Jenkins workflows should be fairly straightforward.

**Comment by keithc-ca** [comment]
I tried following the installation instructions on my Ubuntu 18.04 system: no luck.
After installing python-pip, I could install the hook in a project, but then running complained that it needed python3. Installing python3-pip didn't work any better (`python3 --version` reported a version newer than what pre-commit claimed it needed).

**Comment by keithc-ca** [comment]
The approach I'm proposing is essentially the same as the sample pre-commit hook you get via `git init` which boils down to using:
```
git diff-index --check --cached
```
