### ISSUE TITLE
ub16x64j97 no space left on device

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13254]
@AdamBrousseau 

Disabled.

https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.system_x86-64_linux_Nightly/58/

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly/51/

```
Running on ub16x64j97 in /home/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: java.nio.file.FileSystemException: /home/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly: No space left on device
```

**Comment by AdamBrousseau** [comment]
Cleaned up workspaces but that only gained us 7.5G. Docker is using 20G. Some of them are old images. Cleaned up, but another  case for https://github.com/eclipse-openj9/openj9/issues/13074#issuecomment-871592361
