### ISSUE TITLE
-Xfuture/-Xverify:all only fails on OpenJ9 with Oracle-JDBC

### ISSUE THREAD

**Issue by bmarwell** [eclipse-openj9/openj9#13266]
Hi everyone.

I started Liberty Profile with `-Xverify:all`, because I wanted to check for future security issues (like expiring certificates which are okay for now, but will not be tolerated in future versions).

But when Using IBM J9 or Eclipse OpenJ9, I get this error:
```
org.opentest4j.AssertionFailedError: Should not happen, -Xfuture leads to this ex
	at de.fi.example.oracle.xfuture.MainTest.testGetConnection(MainTest.java:22)
Caused by: java.lang.NoClassDefFoundError: oracle.security.pki.OracleWallet
	at de.fi.example.oracle.xfuture.MainTest.testGetConnection(MainTest.java:20)

Caused by: java.lang.ClassNotFoundException: oracle.security.pki.OracleWallet
	at de.fi.example.oracle.xfuture.MainTest.testGetConnection(MainTest.java:20)
```

I attached a simple test project. It will only fail on any OpenJ9 / IBM J9 vm, but not on any hotspot VM (OpenJDK or Amazons).

[oracle-xfuture.tar.gz](https://github.com/eclipse-openj9/openj9/files/6908042/oracle-xfuture.tar.gz)

Are the tests stricter than Hotspots? Because this does not happen with recent hotspot versions, I think these checks are in fact too strict or create problems with class loading.

If you remove the `-Xfuture` parameter, the error goes away.

Documentation of `-Xfuture` or `-Xverify:all`:
* https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html
* https://www.eclipse.org/openj9/docs/xfuture/

Thanks!

**Comment by JasonFengJ9** [comment]
fyi @ChengJin01

**Comment by ChengJin01** [comment]
With a simplified test case (to avoid running from maven) on our side, the same exception can be reproduced when `-Xfuture` or `-Xverify:all` is specified on the command line.  
```
import java.lang.reflect.*;
public class Test {
	public static void main(String[] args) throws Throwable {
		Class pcc = Class.forName("oracle.jdbc.driver.PhysicalConnection");
	}
}

$ ../jdk11_openj9_bcv_v1/bin/java  -Xverify:all  -cp .:ojdbc8-21.1.0.0.jar Test

j9rtv_verifierGetRAMClass: Class.Method = oracle/jdbc/driver/PhysicalConnection.getSecretStoreCredentials, 
className = oracle/security/pki/OracleWallet

Exception in thread "main" java.lang.NoClassDefFoundError: oracle.security.pki.OracleWallet
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:338)
	at Test.main(Test.java:5)
Caused by: java.lang.ClassNotFoundException: oracle.security.pki.OracleWallet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1086)
	... 3 more

```
This exception was triggered in verifying `oracle/jdbc/driver/PhysicalConnection.getSecretStoreCredentials()` in which case it attempted to load `oracle.security.pki.OracleWallet` (from `oraclepki.jar`) in `j9rtv_verifierGetRAMClass` that didn't exist any jar file specified in the class path. 
```
(gdb) bt
#0  j9rtv_verifierGetRAMClass (verifyData=0x7ffff0090b10, classLoader=0x7ffff0088d08, className=0x7ffff025ca10 "oracle/security/pki/OracleWallet\004", nameLength=32, reasonCode=0x7ffff7d45ae8) at rtverify.c:125
--> #1  0x00007ffff74139fb in isProtectedAccessPermitted (verifyData=0x7ffff0090b10, declaringClassName=0x7ffff025ca0e, targetClass=2144, member=0x7ffff023fa58, isField=0, reasonCode=0x7ffff7d45ae8) at vrfyhelp.c:997
#2  0x00007ffff740c38d in verifyBytecodes (verifyData=0x7ffff0090b10) at rtverify.c:1775
#3  0x00007ffff74070ab in j9rtv_verifyBytecodes (verifyData=0x7ffff0090b10) at rtverify.c:197
#4  0x00007ffff7401f54 in j9bcv_verifyBytecodes (portLib=0x7ffff7543e80 <j9portLibrary>, clazz=0x26ad00, romClass=0x7ffff023c060, verifyData=0x7ffff0090b10) at bcverify.c:2553
#5  0x00007ffff72cb014 in performVerification (currentThread=0x16700, clazz=0x26ad00) at ClassInitialization.cpp:177
#6  0x00007ffff72cc12d in classInitStateMachine (currentThread=0x16700, clazz=0x26ad00, desiredState=J9_CLASS_INIT_INITIALIZED) at ClassInitialization.cpp:488
#7  0x00007ffff72cb9e4 in initializeClass (currentThread=0x16700, clazz=0x26ad00) at ClassInitialization.cpp:334
#8  0x00007ffff7294777 in VM_BytecodeInterpreterCompressed::initializeClassIfNeeded (this=0x7ffff7d46760, _sp=@0x7ffff7d466d0: 0x15c988, _pc=@0x7ffff7d466d8: 0x3 <error: Cannot access memory at address 0x3>, j9clazz=@0x7ffff7d46160: 0x26ad00) at BytecodeInterpreter.hpp:1113
#9  0x00007ffff729dd69 in VM_BytecodeInterpreterCompressed::inlClassForNameImpl (this=0x7ffff7d46760, _sp=@0x7ffff7d466d0: 0x15c988, _pc=@0x7ffff7d466d8: 0x3 <error: Cannot access memory at address 0x3>) at BytecodeInterpreter.hpp:4393
#10 0x00007ffff72b1468 in VM_BytecodeInterpreterCompressed::run (this=0x7ffff7d46760, vmThread=0x16700) at BytecodeInterpreter.hpp:9880
#11 0x00007ffff7288145 in bytecodeLoopCompressed (currentThread=0x16700) at BytecodeInterpreter.inc:112
#12 0x00007ffff73d3712 in c_cInterpreter () at xcinterp.s:158
#13 0x00007ffff73518d0 in runCallInMethod (env=0x16700, receiver=0x0, clazz=0x15ca70, methodID=0x7ffff02340a8, args=0x7ffff7d46d48) at callin.cpp:1123
...
```
The reason why the exception occurred there is that the protected access check was enabled in `isProtectedAccessPermitted()` with `-Xfuture/-Xverify:all` or `-Xverify:doProtectedAccessCheck`  specified on the command line
```
https://github.com/eclipse-openj9/openj9/blob/master/runtime/bcverify/vrfyhelp.c
UDATA 
isProtectedAccessPermitted(...)
{
...
	/* for performance reasons, don't do protection checks unless -Xfuture or -Xverify:doProtectedAccessCheck is specified */
	if ((0 == (verifyData->vmStruct->javaVM->runtimeFlags & J9RuntimeFlagXfuture)) 
	&& (0 == (verifyData->verificationFlags & J9_VERIFY_DO_PROTECTED_ACCESS_CHECK))
	) {
		return TRUE; <----- simply return when -Xfuture or -Xverify:doProtectedAccessCheck is turned off
	} 
```
`-Xfuture/-Xverify:all` or `-Xverify:doProtectedAccessCheck` needs all classes involved to be loaded during verification which might leads to performance issue in in our implementation. So the check is skipped by default, in which case ` oracle/security/pki/OracleWallet` won't be loaded.

**Comment by ChengJin01** [comment]
Hi @bmarwell,  please download `oraclepki.jar` to verify the test based on the investigation above.

In addition, I don't think `oracle/security/pki/OracleWallet` should be skipped in verifying & loading classes with `-Xfuture/-Xverify:all` specified as this is what the `-Xfuture` or `-Xverify:all` option is supposed to do.

**Comment by bmarwell** [comment]
Thanks @ChengJin01. It is interesting to see that OpenJ9 makes optional dependencies a non-optional dependency. I will ask Oracle support if they consider it an optional dependency and will get back to you.
I have opened a case at IBM for investigation, but thanks for sharing these information here. This might help others with the same issue, thank you!

**Comment by bmarwell** [comment]
For documentation: `PhysicalConnection.class` has an import statement for `oracle.security.pki.OracleWallet`. This makes it really odd that Hotspot JVMs do NOT throw an exception. Rob raised this concern in the IBM case as well. I will investigate further. Will probably close this issue soon. Thanks for your in-depth input!

**Comment by bmarwell** [comment]
Oracle DB confirmed that we should not leave out `oraclepki.jar`, so this is more likely a bug in hotspot.
