### ISSUE TITLE
JDK16 jsr292Test_JitCount0_0_FAILED - Illegal instruction vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13293]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly/65/tapResults/ (`ub20-390-1`)

```
21:45:23  openjdk version "16.0.2-internal" 2021-07-20
21:45:23  OpenJDK Runtime Environment (build 16.0.2-internal+0-adhoc.****.BuildJDK16s390xlinuxNightly)
21:45:23  Eclipse OpenJ9 VM (build master-d3ef784535a, JRE 16 Linux s390x-64-Bit Compressed References 20210805_66 (JIT enabled, AOT enabled)
21:45:23  OpenJ9   - d3ef784535a
21:45:23  OMR      - 45440608cb0
21:45:23  JCL      - ee030f1f047 based on jdk-16.0.2+7)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Nightly&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK16_s390x_linux_Nightly%2F66%2FOpenJ9-JDK16-s390x_linux-20210805-211002.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK16_s390x_linux_Nightly%2F66%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=ci-eclipse-openj9&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=16&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk16.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=d3ef784535a7c9cde53c6be0918432ed5f8b9ed5&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=Dynamic)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test jsr292Test_JitCount0_0 ...
===============================================
jsr292Test_JitCount0_0 Start Time: Fri Aug  6 05:26:24 2021 Epoch Time (ms): 1628227584112
variation: -Xjit:count=0
JVM_OPTIONS:  -Xjit:count=0 

Unhandled exception
Type=Illegal instruction vmState=0x00000000
J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=00000002
Handler1=000003FF8C7C7E10 Handler2=000003FF8C6B2268
gpr0=0000000000000178 gpr1=000000008B564D40 gpr2=0000000000000000 gpr3=0000000000000000
gpr4=000003FF00000000 gpr5=00000000015CE778 gpr6=00000000017DC000 gpr7=0000000000000000
gpr8=0000000000000000 gpr9=0000000000000000 gpr10=0000000000000000 gpr11=0000000000000000
gpr12=0000000000000000 gpr13=00000000014EC700 gpr14=000003FF6BB7BA4C gpr15=000003FF8D6FDB98
psw=0000000000000069 mask=0705200180000000 fpc=0008ff00 bea=000003FF6BB7BA4A
fpr0 0000000000000001 (f: 1.000000, d: 4.940656e-324)
fpr1 48815d008d6fc4d0 (f: 2372912384.000000, d: 1.890695e+41)
fpr2 000003ff8801f114 (f: 2281828608.000000, d: 2.171929e-311)
fpr3 3f336e21dbeabbfe (f: 3689593856.000000, d: 2.964814e-04)
fpr4 48815d0000000000 (f: 0.000000, d: 1.890694e+41)
fpr5 4000000000000000 (f: 0.000000, d: 2.000000e+00)
fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr8 00000000014c67e0 (f: 21784544.000000, d: 1.076299e-316)
fpr9 000002aa13762ca0 (f: 326511776.000000, d: 1.447362e-311)
fpr10 00000000014c6d08 (f: 21785864.000000, d: 1.076365e-316)
fpr11 000003ffc51fa6f0 (f: 3307185920.000000, d: 2.172436e-311)
fpr12 000003ff8813d7c0 (f: 2283001856.000000, d: 2.171930e-311)
fpr13 000002aa11c22938 (f: 297937216.000000, d: 1.447348e-311)
fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Target=2_90_20210805_66 (Linux 5.4.0-77-generic)
CPU=s390x (4 logical CPUs) (0x1f6486000 RAM)
----------- Stack Backtrace -----------
(0x000003FF8C6AE852 [libj9prt29.so+0x2e852])
(0x000003FF8C6B33D6 [libj9prt29.so+0x333d6])
(0x000003FF8C6AE8FC [libj9prt29.so+0x2e8fc])
(0x000003FF8C6AEA16 [libj9prt29.so+0x2ea16])
(0x000003FF8C6B33D6 [libj9prt29.so+0x333d6])
(0x000003FF8C6AE6F8 [libj9prt29.so+0x2e6f8])
(0x000003FF8C7C7D46 [libj9vm29.so+0x47d46])
(0x000003FF8C6B33D6 [libj9prt29.so+0x333d6])
(0x000003FF8C7C7F7C [libj9vm29.so+0x47f7c])
(0x000003FF8C6B24EC [libj9prt29.so+0x324ec])
(0x000003FF8D6FD710 [<unknown>+0x0])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2021/08/06 05:26:52 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16282233419178/jsr292Test_JitCount0_0/core.20210806.052652.1027985.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.1028034.

JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16282233419178/jsr292Test_JitCount0_0/core.20210806.052652.1027985.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16282233419178/jsr292Test_JitCount0_0/javacore.20210806.052652.1027985.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16282233419178/jsr292Test_JitCount0_0/javacore.20210806.052652.1027985.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16282233419178/jsr292Test_JitCount0_0/Snap.20210806.052652.1027985.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16282233419178/jsr292Test_JitCount0_0/Snap.20210806.052652.1027985.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk16_j9_extended.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/output_16282233419178/jsr292Test_JitCount0_0/jitdump.20210806.052652.1027985.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'main' thread 0x00000000014EC700
JVMDUMP013I Processed dump event "gpf", detail "".

jsr292Test_JitCount0_0_FAILED
```

Assigning this to OJDK MH since it is enable by default at JDK16.

**Comment by fengxue-IS** [comment]
Tested with latest JDK17 Nightly, failure not seen in Nightly testing
10/10 pass on s390_linux in `Test_grinder/job/Grinder/17944/`
@JasonFengJ9 can you please confirm if this is observed in any testing, I will close this if no other occurrences.

**Comment by JasonFengJ9** [comment]
> can you please confirm if this is observed in any testing, I will close this if no other occurrences.

There is another `jsr292Test_JitCount0_0` failure at `aarch64_linux` https://github.com/eclipse-openj9/openj9/issues/13430 which is not related to this issue.
No other `jsr292Test_JitCount0_0_FAILED` observed.
Closing..
