### ISSUE TITLE
win2012-x86-5 hung

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13302]
Disabled machine.

I've seen this twice.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_windows_OpenJDK8_testList_0/7/console

First issue I noticed is https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly/67/console

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Took a few reboots and shutting down but it is connected again.
