### ISSUE TITLE
SCC directory of nonpersistent cache on a shared drive is problematic

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#13312]
When JVM creates a non-persistent SCC, there are 4 artifacts:
1. A SysV shared memory. 
2. A SysV semaphore. 
3. A control file for the shared memory. 
4. A control file for the semaphore.

The relationship between the SysV object vs its control file is 1 vs 1. The control files (3 and 4) are in the cache directory. 
However, if the cache directory is on a shared drive (across multiple machines/LPARs), the 1 vs 1 relationship can be broken. (Control file is shared across machines, SysV objects are not)

As the information in the control file can be correct only for one SysV object on one machine, JVMs on other machines could see various kinds of failures, e.g. memory/semaphore id mismatch, traceasssert or corruptcache failures. Also when the control file is destroyed, SysV objects on other machines are leaked. 

The default cache directory of OpenJ9 is user's home. We have user setting home on a shared drive on z/OS and seeing above failures. 
This issue is not limited to z/OS, but it is more frequently seen on z/OS as non-persistent cache is the default there.

**Comment by hangshao0** [comment]
@joransiu is checking with z/OS experts if there is a programmatic way to detect a directory on shared volume.

I don't see `omrfile_stat()` (https://github.com/eclipse/omr/blob/master/port/unix/omrfile.c#L1199) giving us such information on z/OS though.

**Comment by hangshao0** [comment]
I guess if we are not able to detect shared volume, we probably needs to consider changing back to `/tmp`.

**Comment by joransiu** [comment]
Yeah, on z/OS, $HOME directories are not guaranteed to be system specific -- that could be the case on Linux and other platforms too, depending on how things are configured.   `/tmp` and `/var` would generally be system specific, with the latter generally used by the OS for customization.  Given SCC is usually tied with the application being executed, I agree `/tmp` would be the better home if we are not able to detect whether $HOME is shared volume.

**Comment by pshipton** [comment]
On Linux we attempt to detect if the cache location is shared, as persistent caches cannot work on shared volumes.

**Comment by pshipton** [comment]
Well actually on network volumes. We detect network volumes.

**Comment by joransiu** [comment]
We should update our [docs](https://www.eclipse.org/openj9/docs/xshareclasses/#cachedir) to clarify for non-persistent caches.  We currently have the following: 

> For persistent caches, the directory must not be on an NFS mount.

It probably need to be generalized to include the control files for non-persistent caches, along with wording for z/OS -- shared filesystems/volumes mounted across different systems.

> On Linux we attempt to detect if the cache location is shared.

What happens if we detect that's the case on Linux?  Do we default to /tmp, or disable SCC?

**Comment by fjeremic** [comment]
I think the bigger problem here is customers upgrading to Java 11 where we have enabled SCC on by default and encountering issues. At the very least we should be updating the docs and providing a more descriptive error messages when the problem does occur.

**Comment by hangshao0** [comment]
> What happens if we detect that's the case on Linux?

There will be a error message saying that it cannot be on a NFS and the cache won't startup.

**Comment by hangshao0** [comment]
I agree we need documentation change to warn users about this issue explicitly.

**Comment by joransiu** [comment]
I followed up with the z/OS SME.  Unfortunately, there is no good way to detemine if a given filesystem is system-specific.  

In a SYSPLEX environment (specifically `SYSPLEX(YES)` is specified in the `BPXPRMxx` member, which is our best practice and recommendation), there is only one file hierarchy shared among all the systems in the plex (which we call a shared file system environment). That means that all systems can see (access) all the other systems file systems.

Now, certain filesystems are guaranteed to be system-specific.  i.e. `/tmp` is mapped to a `/<systemID>/tmp` which is unique to a system.  However, for other filesystems, there is no definitive way to determine if it's shared across systems or not.  As noted, all systems in the plex will have access to the file hierarchy.  There is no way to determine if the access patterns are being done from one system only, or not.   

Based on the above, I think we'll need move the default SCC directory for Java 11+ to `/tmp` for z/OS.

**Comment by hangshao0** [comment]
Thanks for the update @joransiu 

> I think we'll need move the default SCC directory for Java 11+ to /tmp for z/OS.

I agree.
