### ISSUE TITLE
Liberty app server does not start without value propagation

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#13314]
I was doing some performance investigation and observed that Liberty app server cannot start with `-Xjit:optLevel=noOpt`. I switched to `-Xjit:optLevel=cold`, but ran into the same issue once I added `disableLocalVP`. Further investigation revealed that the problematic method is 
`jdk/internal/misc/Unsafe.copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V>`
Value propagation changes `Unsafe.copyMemory` into arraycopy and this transformation seems to be essential for correctness:
```
[     5] O^O VALUE PROPAGATION: Changing call Unsafe.copyMemory [00007F24DB004510] to arraycopy
```
I don't know if this can be considered a bug, but losing the ability to use optLevel=noOpt, or disable VP is an inconvenience.

**Comment by 0xdaryl** [comment]
fwiw, others can correct me if I'm wrong, but I'm not aware of any reason why the JIT must transform `Unsafe.copyMemory` into an arraycopy for correctness.  Calling the native should always be an option.  I consider this a bug.

**Comment by mpirvu** [comment]
The problem shows very early-on during OpenLiberty start-up so I imagine it will show up even with no app installed on top.

**Comment by gacholio** [comment]
Does it work -Xint? In that case, we're certainly running the native, not an arraycopy.

**Comment by mpirvu** [comment]
It does work when I exclude this method `jdk/internal/misc/Unsafe.copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V>` from compilation.

**Comment by BradleyWood** [comment]
So this issue is not limited to OpenLiberty, in fact, a "Hello, World" application can also be used to demonstrate the issue. It seems to occur when the VM is initializing. With "-Xjit:disableLocalVP" a StackOverflowError (still looking into this) is thrown in Unsafe.copyMemory. Then the VM crashes when iterating the stack trace because the AppClassLoader hasn't been initialized yet.

https://github.com/eclipse-openj9/openj9/blob/df51c203a8b47e8f81df4d0f29c5e1e272771f43/runtime/vm/exceptiondescribe.c#L342-L345

```
Exception in thread "main" java/lang/StackOverflowError
	at jdk/internal/misc/Unsafe.copyMemory (java.base@11/Unsafe.java:1291)
	at sun/nio/fs/NativeBuffers.copyCStringToNativeBuffer (java.base@11/NativeBuffers.java:141)
	at sun/nio/fs/UnixNativeDispatcher.copyToNativeBuffer (java.base@11/UnixNativeDispatcher.java:50)
	at sun/nio/fs/UnixNativeDispatcher.exists (java.base@11/UnixNativeDispatcher.java:494)
	at sun/nio/fs/UnixFileSystemProvider.exists (java.base@11/UnixFileSystemProvider.java:526)
	at java/nio/file/Files.exists (java.base@11/Files.java:2435)
	at jdk/internal/module/ModulePath.scan (java.base@11/ModulePath.java:230)
	at jdk/internal/module/ModulePath.scanNextEntry (java.base@11/ModulePath.java:190)
	at jdk/internal/module/ModulePath.find (java.base@11/ModulePath.java:154)
	at jdk/internal/module/SystemModuleFinders$1.lambda$find$0 (java.base@11/SystemModuleFinders.java:215)
```

**Comment by 0xdaryl** [comment]
FYI, I also see this backtrace on AArch64 with Hello World at noopt.

**Comment by BradleyWood** [comment]
Just for the record, you can use the "disableArrayCopyOpts" option as a temporary fix.

**Comment by 0xdaryl** [comment]
Adding this to the JDK18 milestone (@pshipton).  Fix testing is underway.

**Comment by pshipton** [comment]
@0xdaryl did this (and https://github.com/eclipse-openj9/openj9/pull/13340) get forgotten? I see successful PR testing and then nothing since.

**Comment by pshipton** [comment]
This issue doesn't need to be resolved for Java 18. It's low severity for customers since it only appears in no-opt. I'll move it to the Backlog. @0xdaryl if you want it in another release milestone I'll leave it to you.
