### ISSUE TITLE
JITServer documentation clean-up

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#13310]
The JITServer documentation in the openj9 repo contains some old information which is now obsolete. For instance:
- Since we started using cmake, running `configure` with `--with-freemarker` is no longer needed
- There is a section about building JITServer in dockerfiles. These dockerfiles refer to protobufs library which is no longer needed. Currently there should be nothing JITServer specific in the dockerfiles, so I think we can delete them.

Also, the reference to JITServer AOT cache should be deleted because currently we don't have all the code checked-in.

**Comment by mpirvu** [comment]
Attn @dmitry-ten

**Comment by dmitry-ten** [comment]
We could just add a mention of JITServer to https://github.com/eclipse-openj9/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md (and the same for Java 11 and 16)

**Comment by mpirvu** [comment]
Yes, I think we can simply link to the generic OpenJ9 build instructions and only mention about `--enable-jitserver`. This will avoid the two places falling out-of-sync

**Comment by dmitry-ten** [comment]
We'll need to update all JITServer Dockerfiles as well.

**Comment by mpirvu** [comment]
I was thinking about deleting the jitserver Dockerfiles because they don't bring anything new compared to what OpenJ9 provides.

**Comment by dmitry-ten** [comment]
I guess that's true.
The `buildserver/Dockerfile` builds an image with jitserver preconfigured to run but I guess that's not really important, when such Dockerfile can be easily created from the JITServer OpenJ9 image.

Do you remember why we needed `gcc-7` to build JITServer previously? Was it because of protobuf?

**Comment by mpirvu** [comment]
We may have needed gcc-7 for some JITServer c++11 features, but now we compile with gcc 7.5 anyway, so this is nothing different from what OpenJ9 does.

**Comment by mpirvu** [comment]
Implemented in 
https://github.com/eclipse-openj9/openj9/pull/13317
https://github.com/eclipse-openj9/openj9/pull/13240
https://github.com/eclipse-openj9/openj9/pull/13147
