### ISSUE TITLE
Improve error message when loading an invalid class version 

### ISSUE THREAD

**Issue by Thihup** [eclipse-openj9/openj9#13347]
Current, if we try to run a more recent Java class in an old JVM, we get the following error message:
```
Error: LinkageError occurred while loading main class some.Class
	java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=some/Class, offset=6
```

However, it is not so easily to detect that the class was compiled with a version above the supported by the JVM.Hotspot gives a more informative error message, so maybe it would be possible to improve the message in some way. 

```
Error: LinkageError occurred while loading main class some.Class
	java.lang.UnsupportedClassVersionError: some/Class has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
```

**Comment by AbhigyanSrivastav** [comment]
hey @Thihup I would like to work on this issue could you please help me on how can I get started start with this.

**Comment by Thihup** [comment]
@AbhigyanSrivastav Compiling a class with a newer Java version (like 18) and trying to run on Java 17 should cause this issue

**Comment by pshipton** [comment]
Yes the issue is still relevant.

**Comment by bhonsleaditya1** [comment]
@pshipton Could you guide me on how to proceed?

**Comment by pshipton** [comment]
The error is thrown from https://github.com/eclipse-openj9/openj9/blob/master/runtime/bcutil/cfreader.c#L2555

buildError() is https://github.com/eclipse-openj9/openj9/blob/master/runtime/verutil/cfrerr.c#L139

As you can see it initializes the J9CfrError struct with the error values. You can extend the J9CfrError struct to include the major/minor/max classfile version info, and create a new helper to populate it. The other helpers need to initialize the new fields to a default value like -1.
https://github.com/eclipse-openj9/openj9/blob/master/runtime/oti/j9nonbuilder.h#L324
As long as the J9CfrError struct is smaller than INITIAL_CLASS_FILE_BUFFER_SIZE (4096) there is no issue with overflowing the buffer.

The recorded data is used to create the error message at https://github.com/eclipse-openj9/openj9/blob/master/runtime/bcutil/verifyerrstring.c#L33
Which goes to https://github.com/eclipse-openj9/openj9/blob/master/runtime/verutil/cfrerr.c#L82
and https://github.com/eclipse-openj9/openj9/blob/master/runtime/verutil/cfrerr.c#L38

See the existing NLS message template at https://github.com/eclipse-openj9/openj9/blob/master/runtime/nls/cfre/cfrerr.nls#L74

Add new NLS template(s) at the end of the .nls file with appropriate error messages, and use these templates to create the error messages when the major/minor version error info is populated.

**Comment by bhonsleaditya1** [comment]
#14236 Added PR for this

**Comment by snehaljos** [comment]
Hi, am interested in this issue, @bhonsleaditya1  do you need any help? or can I try?

**Comment by bhonsleaditya1** [comment]
Hi @snehaljos I am planning to take this again on this weekend. Will update after that.

**Comment by snehaljos** [comment]
oh okk

**Comment by mayurstwt** [comment]
Hey maintainer i would like to work on this issue will you please provide me some resources

**Comment by DevanshKariya** [comment]
is this issue still open? I would like to work on it.

**Comment by Thihup** [comment]
@DevanshKariya I think it is still open

**Comment by fengxue-IS** [comment]
@thallium please take a look at this, https://github.com/eclipse-openj9/openj9/issues/13347#issuecomment-1007459785 is a very good guide on what changes are required
