### ISSUE TITLE
Override `TR_J9VMBase::delegatingMethodHandleTarget` for JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#13361]
PR https://github.com/eclipse-openj9/openj9/pull/13354 introduces a new frontend call:
`TR::KnownObjectTable::Index
TR_J9VMBase::delegatingMethodHandleTarget(
   TR::Compilation *comp, TR::KnownObjectTable::Index dmhIndex, bool trace)`
which needs to be overridden for JITServer. Specifically, the code protected by the VMAccess critical section needs to be executed at the client. If there is a new known object index, it needs to be created at the server too.

Attn: @dmitry-ten

**Comment by dmitry-ten** [comment]
This can be closed now.

**Comment by mpirvu** [comment]
Resolved by #13408
