### ISSUE TITLE
NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13371]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_extended.system_x86-64_mac_Nightly_testList_2/76/ - osx1014-x86-1
ObjectTreeLoadTest_5m_0
JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk16_j9_extended.system_x86-64_mac_Nightly_testList_2/76/system_test_output.tar.gz
```
OLT >>> Captured test output >>>
OLT Starting doTest
OLT .
OLT Step 1.
OLT Step 2Test failed:
OLT java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.linkToVirtual(java.lang.Object, long, java.lang.Object, java.lang.invoke.MemberName)" because "java.lang.invoke.LambdaForm$DMH.0x0000000000000000._DATA_DirectMethodHandle_1" is null
OLT 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeVirtual(LambdaForm$DMH)
OLT 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invokeExact_MT(LambdaForm$MH)
OLT 	at net.adoptopenjdk.test.lang.invoke.BasicTest.doTest(BasicTest.java:108)
OLT 	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
OLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
OLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
OLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
OLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
OLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
OLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
OLT 	at java.base/java.lang.Thread.run(Thread.java:883)
OLT <<<
```

**Comment by pshipton** [comment]
@tajila @fengxue-IS fyi

I saw a changed merged which I thought would have fixed this. 
Note this failure occurred in the last jdk16 nightly build this past Sunday night, which has now been disabled in favour of running jdk17 nightly. You can look back in the build history to see how often this occurs. 
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK16/

**Comment by pshipton** [comment]
FYI jdk17 build is https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK17
I don't think we have issues for all the extended.system failures, I'll go through them later today and ensure issues are created.

**Comment by pshipton** [comment]
Technically this is a dup of https://github.com/eclipse-openj9/openj9/issues/13129

**Comment by tajila** [comment]
I think its also a dup of https://github.com/eclipse-openj9/openj9/issues/13305

**Comment by pshipton** [comment]
Close this if you want, I wasn't sure if https://github.com/eclipse-openj9/openj9/pull/13285 was supposed to fix it.
