### ISSUE TITLE
Eclipse OpenJ9 Semeru Builds for Windows contain unsigned exe files

### ISSUE THREAD

**Issue by MNeuling** [eclipse-openj9/openj9#13402]
Since OpenJ9 builds have been offered as the IBM Semeru JVM, the Windows executables are unsigned.
As a result, the Java processes can be blocked by security solutions.

E.g. in the archive ibm-semeru-open-jre_x64_windows_8u302b08_openj9-0.27.0.zip all exe files are unsigned.

**Comment by AdamBrousseau** [comment]
Thanks, @MNeuling for spotting this and opening the issue. It seems that the Windows jre's missed getting signed. The jdk package appears to be fine. I will rectify this for the next release.

**Comment by pshipton** [comment]
@AdamBrousseau is the next release for Windows 0.27.1 or 0.28?

**Comment by AdamBrousseau** [comment]
Next Windows release will be 0.28.0.
0.27.1 will be limited to aix and plinux.

**Comment by AdamBrousseau** [comment]
The changes required have been applied to the build jobs and the jres are now being signed. The next release of windows (0.28/0.29) should contain the fix. Closing this as resolved.
