### ISSUE TITLE
TR_J9VMBase::getClassSignature* does not print value type signature correctly

### ISSUE THREAD

**Issue by a7ehuo** [eclipse-openj9/openj9#13423]
`TR_J9VMBase::getClassSignature*` assumes component class is an identity type and prefix `L` to the class name for the class signature. The component class can be value types and their signature should be prefixed with `Q` .  There might be other places in the code that check `L` when it should be checking or adding `Q`. 
https://github.com/eclipse-openj9/openj9/blob/cfa425a6f993fd950f271c57e891cc8f0ad44ed7/runtime/compiler/env/VMJ9.cpp#L2549-L2553

**Comment by a7ehuo** [comment]
@hzongaro fyi

**Comment by hzongaro** [comment]
>  There might be other places in the code that check L when it should be checking or adding Q

You're right - and there was some old prototype code that took care of some of those places, but it's needs some close examination and updating.  It's described in issue #12237.

**Comment by a7ehuo** [comment]
Close this issue since the same problem is already tracked in #12237.
