### ISSUE TITLE
Enhance javacore output to indicate which options where ignored

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13471]
There are a lot of hotspot args that J9 ignores. These show up in the javacore output. 

ie.
```
2CIUSERARG               -Xloggc:verbosegc.txt
2CIUSERARG               -XX:AdaptiveSizePolicyWeight=90
2CIUSERARG               -XX:CICompilerCount=2
2CIUSERARG               -XX:+ExitOnOutOfMemoryError
2CIUSERARG               -XX:GCTimeRatio=4
2CIUSERARG               -XX:MaxHeapFreeRatio=20
2CIUSERARG               -XX:MinHeapFreeRatio=10
2CIUSERARG               -XX:ParallelGCThreads=8
2CIUSERARG               -XX:+UseParallelOldGC
2CIUSERARG               -XX:CompressedClassSpaceSize=528482304
2CIUSERARG               -XX:InitialHeapSize=2147483648
2CIUSERARG               -XX:MaxHeapSize=5368709120
2CIUSERARG               -XX:MaxMetaspaceSize=536870912
2CIUSERARG               -XX:+PrintGC
2CIUSERARG               -XX:+PrintGCTimeStamps
2CIUSERARG               -XX:+UseCompressedClassPointers
2CIUSERARG               -XX:+UseCompressedOop
```

It will be helpful for service engineers and anyone debugging using a javacore to be able to quickly identify which options the JVM ignored.

**Comment by tajila** [comment]
FYI @keithc-ca

**Comment by keithc-ca** [comment]
Using a couple of the sample ignored options in the description, with my potential change
```
java -Xdump:java:events=vmstop -XX:+UseCompressedOop -XX:CompressedClassSpaceSize=528482304 -version
```
adds after the section
```
1CIUSERARGS    UserArgs:
```
the following
```
1CIIGNOREDARGS Ignored Args:
2CIIGNOREDARG            -XX:+UseCompressedOop
2CIIGNOREDARG            -XX:CompressedClassSpaceSize=528482304
```
The arguments shown are those with `CONSUMABLE_ARG`, but not `ARG_CONSUMED` in `J9CmdLineOption.flags`.

Thoughts, suggestions?

**Comment by pshipton** [comment]
I don't see `-XX:-UseCompressedOops` and `-XX:+UseCompressedOops` in the ignoredOptionTable, they probably need to be added once we fix them https://github.com/eclipse-openj9/openj9/issues/13561

**Comment by Tom-Poe** [comment]
I'm not sure that's the complete list, but there's also `-XX:+HeapDumpOnOutOfMemoryError` 
(or perhaps `-XX:-HeapDumpOnOutOfMemoryError`)
Also others.

**Comment by pshipton** [comment]
They do appear to be consumed.

**Comment by pshipton** [comment]
Note `-XX:[+|-]IgnoreUnrecognizedXXColonOptions` https://www.eclipse.org/openj9/docs/xxignoreunrecognizedxxcolonoptions/ can be used to get an error for unrecognized `-XX:` options.
