### ISSUE TITLE
JEP 400 UTF-8 by Default

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13470]
See https://openjdk.java.net/jeps/400

@tajila fyi

**Comment by JasonFengJ9** [comment]
A recent PR https://github.com/eclipse-openj9/openj9/pull/12340 related to `sun.stderr.encoding` and `sun.stdout.encoding` specified in this JEP.

**Comment by tajila** [comment]
@JasonFengJ9 are we done this?
