### ISSUE TITLE
OSX problems related to creating core files

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13509]
The problems appear to be machine specific.

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_OMR_testList_1/79/ - osx1011-x86-2

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly_testList_0/93/ - osx1011-x86-1

This will have been caused by https://github.com/eclipse/omr/pull/6133

@mikezhang1234567890 @tajila @keithc-ca fyi

**Comment by pshipton** [comment]
Maybe not just 10.11

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_0/98/ - osx1014-x86-2
```
FAILED: testLocal_triggerDumpToFile
java.lang.AssertionError: /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_0/aqa-tests/TKG/output_16316812733782/testOpenJ9DiagnosticsMXBean_0/./local_dumps/core.20057.dmp not found expected [true] but found [false]
```

**Comment by tajila** [comment]
@mikezhang1234567890 can you please take a look at this

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly_testList_0/98/ - osx1011-x86-2
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_Nightly_testList_1/93/ - osx1011-x86-2
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly_testList_0/94/ - osx1011-x86-1

**Comment by pshipton** [comment]
I've disabled the 10.11 machines for now, we'll see if we can get through the builds without them.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_0/99/ - osx1013-x86-3
testOpenJ9DiagnosticsMXBean_0

**Comment by mikezhang1234567890** [comment]
Looks like the issue with `testOpenJ9DiagnosticsMXBean_0` is because the core dump utility isn't following the full path, and just creating the core in the active directory.

**Comment by pshipton** [comment]
`testOpenJ9DiagnosticsMXBean_0` continues to fail in the nightly builds, but I'm not going to keep reporting them all.

**Comment by pshipton** [comment]
@mikezhang1234567890 there is still a problem on the 10.11 machines, are you investigating? The machines have been disabled for some time because of this problem. You can get access to them in order to figure out the problem (open an infra issue). I ran a new build on these machines to get some current results. This build contains the recent OMR change. https://github.com/eclipse-openj9/openj9-omr/commit/1ec11640d497

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal/79

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_1/77
cmdLineTester_GCCheck_4
```
15:58:08  Testing: Run gccheck
15:58:08  Test start time: 2021/10/02 15:58:07 Eastern Standard Time
15:58:08  Running command: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_1/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
15:58:08  Time spent starting: 3 milliseconds
15:58:08  Time spent executing: 294 milliseconds
15:58:08  Test result: FAILED
15:58:08  Output from test:
15:58:08   [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
15:58:08   [OUT] Loading image from DTFJ...
15:58:08   [OUT] 
15:58:08   [OUT] Could not load dump file and/or could not load XML file: Image file '/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_1/aqa-tests/TKG/output_16332046506448/cmdLineTester_GCCheck_4/j9core.dmp' not found.
15:58:08   [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
15:58:08   [OUT] > DDR is not enabled for this core file, '!' commands are disabled
15:58:08   [OUT] > 
15:58:08  >> Success condition was not found: [Output match: Checking HEAP...done]
15:58:08  >> Failure condition was not found: [Output match: gc check]
15:58:08  >> Failure condition was not found: [Output match: unable to read]
15:58:08  >> Failure condition was not found: [Output match: Exception]
```

Also a cmdLineTester_pltest_osx_0 failure.
```
16:18:58   [ERR] FAILURES DETECTED. Number of failed tests: 2
16:18:58   [ERR] 
16:18:58   [ERR] 1: j9dump_test_create_dump_with_name
16:18:58   [ERR] 	/Users/jenkins/workspace/Build_JDK8_x86-64_mac_Personal/openj9/runtime/tests/port/j9dumpTest.c line  205: 
16:18:58   [ERR] j9file_stat call in verifyFileExists() returned -108: No such file or directory
16:18:58   [ERR] 
16:18:58   [ERR] 		LastErrorNumber: -108
16:18:58   [ERR] 		LastErrorMessage: No such file or directory
16:18:58   [ERR] 
16:18:58   [ERR] 2: j9dump_test_create_dump_from_signal_handler
16:18:58   [ERR] 	/Users/jenkins/workspace/Build_JDK8_x86-64_mac_Personal/openj9/runtime/tests/port/j9dumpTest.c line  304: 
16:18:58   [ERR] j9file_stat call in verifyFileExists() returned -108: No such file or directory
16:18:58   [ERR] 
16:18:58   [ERR] 		LastErrorNumber: -108
16:18:58   [ERR] 		LastErrorMessage: No such file or directory
```

The other machine stopped responding during the testing, not sure if this is related. There is at least one similar failure before it stopped responding. If you fix these problems we can re-test, and run the extended testing as well.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_0/77/
```
15:58:50  Testing: Run !printallcallsites
15:58:50  Test start time: 2021/10/02 15:58:49 Eastern Standard Time
15:58:50  Running command: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_0/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
15:58:50  Time spent starting: 3 milliseconds
15:58:50  Time spent executing: 243 milliseconds
15:58:50  Test result: FAILED
15:58:50  Output from test:
15:58:50   [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
15:58:50   [OUT] Loading image from DTFJ...
15:58:50   [OUT] 
15:58:50   [OUT] Could not load dump file and/or could not load XML file: Image file '/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_0/aqa-tests/TKG/output_16332047152348/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp' not found.
15:58:50   [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
15:58:50   [OUT] > DDR is not enabled for this core file, '!' commands are disabled
```

**Comment by pshipton** [comment]
This is resolved now.
