### ISSUE TITLE
Paper server can not patching jar when using balanced gc

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#13569]
Java -version output
--------------------

```
openjdk version "11.0.12" 2021-07-20
IBM Semeru Runtime Open Edition 11.0.12.0 (build 11.0.12+7)
Eclipse OpenJ9 VM 11.0.12.0 (build openj9-0.27.0, JRE 11 Windows 7 amd64-64-Bit Compressed References 20210730_175 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - 21849e2ca0 based on jdk-11.0.12+7)
```

Summary of problem
------------------
[Paper](https://papermc.io/) is a spigot(A type of minecraft server can load plugins.) fork. Balanced gc could break paper patching stage.
Gencon gc have no problem with paper.
Paper sources url:https://github.com/PaperMC/Paperclip/blob/main/java16/src/main/java/io/papermc/paperclip/Paperclip.java

Diagnostic files
----------------
When I use balanced gc,this method (java.io.FilterInputStream.read ()) always used cpu resources. But no patched jar is created. Paper patching well on gencon gc.
Part thread dump(by ViusalVM):
```
"main" - Thread t@1
   java.lang.Thread.State: RUNNABLE
	at java.base@11.0.12/java.util.zip.Inflater.inflateBytesBytes(Native Method)
	at java.base@11.0.12/java.util.zip.Inflater.inflate(Unknown Source)
	- locked <c739b1c2> (a java.util.zip.Inflater$InflaterZStreamRef)
	at java.base@11.0.12/java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.base@11.0.12/java.io.FilterInputStream.read(Unknown Source)
	at app//io.papermc.paperclip.Paperclip.readFully(Paperclip.java:311)
	at app//io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:139)
	at app//io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:95)
	at app//io.papermc.paperclip.Paperclip.main(Paperclip.java:49)

   Locked ownable synchronizers:
	- None
```
There is thread dump(balanced gc):
[threaddump-1632668526407.txt](https://github.com/eclipse-openj9/openj9/files/7231700/threaddump-1632668526407.txt)
Gencon gc:
[threaddump-1632668803327.txt](https://github.com/eclipse-openj9/openj9/files/7231702/threaddump-1632668803327.txt)
[threaddump-1632636052368.txt](https://github.com/eclipse-openj9/openj9/files/7231704/threaddump-1632636052368.txt)

Launch flags:`-Xmx1024M -Xgcpolicy:balanced -Dcom.sun.management.jmxremote.port=19000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -jar paper-1.16.5-788.jar`

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by LinHu2016** [comment]
it was one of known issue related with arraylet and GetPrimitiveArrayCritical()/ReleasePrimitiveArrayCritical() (https://github.com/eclipse-openj9/openj9/issues/702). 
solution : use java option "-Xgc:enableArrayletDoubleMapping" for performance issue.
alternative solution : increase region size to avoid arraylet (such as region size is bigger than compressed file size) use java option "-Xgc:regionSize=16777216 -XXgc:tarokNurseryMaxAge=1 -XXgc:tarokRegionMaxAge=2 ".

**Comment by pshipton** [comment]
Given the response I'll go ahead and close this, since it's a known issue. Hopefully some day resolved by the double mapping feature.

We can reopen if further comments indicate.

**Comment by 1a2s3d4f1** [comment]
Java option "-Xgc:enableArrayletDoubleMapping" only support LINUX system. It will support other system?
-Xgc:regionSize=16777216 is not eoough for patch jar file. I must use "-Xgc:regionSize=128M" to set region size.

**Comment by LinHu2016** [comment]
@1a2s3d4f1 there is new feature off-heap on the way, it would be better solution to fix the issue, but it is still in middle of implementation... -Xgc:regionSize=128M for your case, it means there are only 8 regions totally,be careful to limit thread numbers to avoid the contention.
