### ISSUE TITLE
Add vlog timestamp when jitserver started

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#13563]
When an OpenJ9 JVM starts, it prints into the verbose log (if enabled) the current time. E.g.
```
#INFO:  StartTime: Sep 24 09:09:12 2021
```
It would be useful for jitserver to show similar information. The current time is printed by the sampling thread which jitserver is missing, but we can use the listener thread for the same purpose.

**Comment by mpirvu** [comment]
Attn: @cjjdespres

This is the sequence of code that prints StartTime in vlog: https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/HookedByTheJit.cpp#L5859-L5866

Something similar needs to be done in https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/runtime/Listener.cpp either in `int32_t J9THREAD_PROC listenerThreadProc(void * entryarg)` or at the beginning of `TR_Listener::serveRemoteCompilationRequests(BaseCompileDispatcher *compiler)` which is called only once from listenerThreadProc.

Adding the timezone, like Peter suggested above, is a good idea.

**Comment by cjjdespres** [comment]
It looks like the start time is only set after the listener thread spawns, I think when the statistics thread starts?

https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/runtime/JITServerStatisticsThread.cpp#L83

I could move that so it gets set in `startJITServer`, or in `listenerThreadProc`, which seems like a reasonable place to record the start time of the server.

----

Can I just copy over the time zone code introduced in the commit above?

https://github.com/eclipse-openj9/openj9/blob/master/runtime/rasdump/javadump.cpp#L657-L718

Or maybe that should go in its own function somewhere to be used in both places.

**Comment by mpirvu** [comment]
The listener thread is started very early during JITServer initialization and immediately goes to execute `listenerThreadProc`. Thus, it doesn't matter much where exactly you read the start time (a millisecond less or more doesn't make much of a difference)

**Comment by mpirvu** [comment]
> Can I just copy over the time zone code introduced in the commit above?

I haven't looked in detail, but the indicated code looks more than just a few lines. In this case, rather than copying it, it would be better to create a portlib function that is called in both places.

**Comment by mpirvu** [comment]
Factoring out the code for the time zone may take a bit of time. Hence, you can split the implementation in 3 parts: first deliver one PR with just the date/time; then, create a routine (in OMR) which computes the timezone; Finally, use the new routine in javadump.cpp and in JITServer code.

**Comment by cjjdespres** [comment]
The original time zone code seems to output the text to a stream as it goes. Could the new function live in `port/common/omrstr.c` in OMR and instead write the text it currently outputs to a supplied buffer like the other functions in that file?

**Comment by mpirvu** [comment]
>  Could the new function live in port/common/omrstr.c in OMR and instead write the text it currently outputs to a supplied buffer like the other functions in that file?

Yes, that's exactly what I was thinking of.
