### ISSUE TITLE
Cannot run AArch64 Jenkins jobs

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#13599]
Running Jenkins jobs in PR #13598 fails on cent8-aarch64-2 with the following message:

>[2021-09-30T01:35:23.531Z] + docker ps -a
>[2021-09-30T01:35:23.531Z] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_linux_Personal/111/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_linux_Personal/112/

**Comment by knn-k** [comment]
An AArch64 job works on ub20-aarch64-1 today.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_linux_Personal/113/

**Comment by knn-k** [comment]
I get the following error on cent8-aarch64-2.

https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_linux_Personal/114/
```
08:10:50  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by knn-k** [comment]
The build on cent8-aarch64-3 was successful.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_linux_Personal/115/

**Comment by AdamBrousseau** [comment]
Jenkins user added to docker group. Should be resolved now.
