### ISSUE TITLE
Performance overhead for java.util.ref.Reference.refersTo() in Java 17+

### ISSUE THREAD

**Issue by hzongaro** [eclipse-openj9/openj9#13596]
Java 16 introduced a new `java.util.ref.Reference.refersTo` method.  This method is being used in methods in `java.lang.ThreadLocal$ThreadLocalMap`.  In previous versions of Java, `ThreadLocalMap` used the `Reference.get` method.

It looks like these uses of [`refersTo`](https://github.com/eclipse-openj9/openj9/blob/d5a132c9a90ad8d4d50571e2251db9b335ef1b9c/runtime/jcl/common/java_lang_ref_Reference.cpp#L62-L89) have introduced some overhead for uses of `ThreadLocalMap`.  I'm seeing a large bump in calls to `internalEnterVMForJNI` and `internalExitVMForJNI`.  I'm just crafting a stand-alone test that demonstrates that, but @keithc-ca asked me to open an issue in the meanwhile.

**Comment by tajila** [comment]
@hzongaro Any update on this?

**Comment by hzongaro** [comment]
Sorry - I had put this on the backburner and never made it back to continue investigation.  No further updates yet.

**Comment by vijaysun-omr** [comment]
Are you able to run that test you had previously ? It may be an easier investigation to fixing issues with JDK 17 or 19 in general.

**Comment by hzongaro** [comment]
> Are you able to run that test you had previously?

Yes, I should be able to.  I had forgotten that it existed.  It's a very trivial test, however, targeted toward the situation where this problem first came up - in use of `ThreadLocal.get`

**Comment by vijaysun-omr** [comment]
My interest in it was that it could show more of a difference after this issue is fixed between JDK 19 and JDK 8 for example, i.e. it may be the easiest way to track down other sources of difference (towards the ultimate goal of keeping JDK 19 as close as possible to JDK 8).

**Comment by hzongaro** [comment]
Fixed by pull request #13619
