### ISSUE TITLE
jdknext java/lang/Access.encodeASCII needs impl

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13600]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/110/
```
00:28:29  /home/jenkins/workspace/Build_JDKnext_ppc64_aix_OpenJDK/build/aix-ppc64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:61: error: Access is not abstract and does not override abstract method encodeASCII(char[],int,byte[],int,int) in JavaLangAccess
00:28:29  final class Access implements JavaLangAccess {
00:28:29        ^
00:28:29  /home/jenkins/workspace/Build_JDKnext_ppc64_aix_OpenJDK/src/java.base/share/classes/sun/nio/cs/US_ASCII.java:174: error: variable n is already defined in method encodeArrayLoop(CharBuffer,ByteBuffer)
00:28:29                      int n = encodeASCII(sa,sp,sl-sp,da,dp);
00:28:29                          ^
00:28:29  /home/jenkins/workspace/Build_JDKnext_ppc64_aix_OpenJDK/src/java.base/share/classes/sun/nio/cs/US_ASCII.java:190: error: variable n is already defined in method encodeArrayLoop(CharBuffer,ByteBuffer)
00:28:29                      int n = encodeASCII(sa,sp,dl-dp,da,dp);
00:28:29                          ^
```

**Comment by pshipton** [comment]
Seems there are problems on the OpenJDK side and we should wait until they are resolved to see what we need to do.

**Comment by pshipton** [comment]
I see, there are OpenJ9 "enhancements" to US_ASCII which are now broken.

**Comment by pshipton** [comment]
@vijaysun-omr fyi, OpenJDK added an intrinsic for encodeASCII.

**Comment by JasonFengJ9** [comment]
Created https://github.com/eclipse-openj9/openj9/pull/13603 to address `error: Access is not abstract and does not override abstract method encodeASCII(char[],int,byte[],int,int) in JavaLangAccess`.

`error: variable n is already defined in method encodeArrayLoop(CharBuffer,ByteBuffer)` is caused by `OpenJ9-perf_converter` JCL patch which has to be re-evaluated after latest OpenJDK update.

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/366 fixed the other part.
