### ISSUE TITLE
Z should enable profile directed guarded devirtualization by default like P&X do.

### ISSUE THREAD

**Issue by klangman** [eclipse-openj9/openj9#13606]
https://github.com/eclipse-openj9/openj9/blob/cd91c43547fb752e7a6a7efd9f9db3aeb6fab4c7/runtime/compiler/z/codegen/S390PrivateLinkage.cpp#L1818

**Comment by 0xdaryl** [comment]
That line of code you linked is for "profiled devirtualization", which I don't think is enabled on any platform (or at least this is the only use of this option in the code base).  Is that what you meant?

**Comment by klangman** [comment]
Yes, I should have added "profile directed" in front of guarded devirtualization. P & Z do this opt without checking for the 'enableProfiledDevirtualization' option.
