### ISSUE TITLE
JDK17 `0.29` release : sun/util/logging/PlatformLoggerTest.java - Retrieved backing PlatformLogger level null is not the expected INFO

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13616]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/52/consoleFull`:
```
09:41:48  openjdk version "17-internal" 2021-09-14
09:41:48  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDK17s390xlinuxPersonal)
09:41:48  Eclipse OpenJ9 VM (build v0.29.0-release-828307692e8, JRE 17 Linux s390x-64-Bit Compressed References 20211002_68 (JIT enabled, AOT enabled)
09:41:48  OpenJ9   - 828307692e8
09:41:48  OMR      - e66945e0106
09:41:48  JCL      - 23999d8072a based on jdk-17+35)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_s390x_linux_Personal%2F68%2FOpenJ9-JDK17-s390x_linux-20211002-055634.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK17_s390x_linux_Personal%2F68%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=v0.29.0-release&OPENJ9_SHA=828307692e85aed54add50bfccfddc1ddc62514d&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=4053da8c886fce79a3d2d9077ef46582e5c7b73e&JDK_BRANCH=v0.29.0-release&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
11:12:17  ===============================================
11:12:17  Running test jdk_util_0 ...
11:12:17  ===============================================
11:12:17  jdk_util_0 Start Time: Sat Oct  2 08:12:16 2021 Epoch Time (ms): 1633187536743
11:12:17  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
11:12:17  JVMSHRC005I No shared class caches available
11:12:17  JVMSHRC005I No shared class caches available
11:12:17  cache cleanup done
11:12:17  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
11:12:17  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

11:31:47  --------------------------------------------------
11:31:47  TEST: sun/util/logging/PlatformLoggerTest.java

11:31:47  Oct 02, 2021 8:31:42 AM PlatformLoggerTest testLogMethods
11:31:47  INFO: Test info(String)
11:31:47  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected INFO
11:31:47  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
11:31:47  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
11:31:47  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
11:31:47  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:31:47  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
11:31:47  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:31:47  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
11:31:47  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:31:47  	at java.base/java.lang.Thread.run(Thread.java:884)
11:31:47  
11:31:47  JavaTest Message: Test threw exception: java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected INFO
11:31:47  JavaTest Message: shutting down test
11:31:47  
11:31:47  STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected INFO

11:31:47  --------------------------------------------------
11:31:54  Test results: passed: 885; failed: 1
11:32:02  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/jvmtest/openjdk/report/html/report.html
11:32:02  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/aqa-tests/TKG/output_16331822795544/jdk_util_0/work
11:32:02  Error: Some tests failed or other problems occurred.
11:32:02  
11:32:02  jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
Closing as a dup of the long standing known problem https://github.com/eclipse-openj9/openj9/issues/10759
