### ISSUE TITLE
JEP 417: Vector API (Third Incubator)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13623]
See https://openjdk.java.net/jeps/417

@gita-omr @tajila fyi

**Comment by pshipton** [comment]
> Can we close the older jep issues and keep only the latest for tracking purposes?

@gita-omr maybe we can also close this one for jdk18? It doesn't seem to be used. There will be a new one for jdk19 created after the jdk18 release.

**Comment by gita-omr** [comment]
Sure, please close all the old ones.
