### ISSUE TITLE
Reset all SecureRandom instances on CRIU snapshot/restore

### ISSUE THREAD

**Issue by ashbm5** [eclipse-openj9/openj9#13633]
Add code to ensure SecureRandom objects are re-seeded before execution proceeds on CRIU restore.

**Comment by ashbm5** [comment]
fyi @vijaysun-omr @tajila

**Comment by vijaysun-omr** [comment]
This is part of issue [16384](https://github.com/OpenLiberty/open-liberty/issues/16384)

**Comment by tajila** [comment]
The biggest challenge with this is determining how the SecureRandom instance was created. There are a few constructors

```
public SecureRandom();
public SecureRandom(byte[] seed);
protected SecureRandom(SecureRandomSpi secureRandomSpi, Provider provider);
protected SecureRandom(SecureRandomSpi secureRandomSpi, Provider provider);
```

Depending on how the instance was created the restore behaviour will be different. The naive solution is to simply instrument all constructors and tag the resulting instance, so we know how it was created and how to restore it. This can work if there aren't many instances, the overhead of this approach may be prohibitive if there are many.

**Comment by tajila** [comment]
This is captured in https://github.com/eclipse-openj9/openj9/issues/14662
