### ISSUE TITLE
-XX:+CompactStrings fails in InetAddress.getLocalHost() with Java 17 Milestone 2

### ISSUE THREAD

**Issue by avermeer** [eclipse-openj9/openj9#13655]
Java -version output
--------------------
Eclipse OpenJ9 VM 17.0.0.0-m1 (build openj9-0.28.0-m2, JRE 17 Windows 10 amd64-64-Bit Compressed References 20210916_31 (JIT enabled, AOT enabled)

Summary of problem
------------------

Consider the following small program:

```
package tests;
import java.net.InetAddress;
import java.net.UnknownHostException;

public class TestCompactString {
	public static void main(String[] args) {
		try {
			String hostName = InetAddress.getLocalHost().getHostName();
			System.out.println( "hostName="+hostName );
			String hostName2=new StringBuilder(hostName).append(".localdomain").toString();
			System.out.println( "hostName2="+hostName2 );
			boolean testOK=hostName2.startsWith(hostName);
			System.out.println( "hostName2.startsWith(hostName) returned  "+testOK );
		} catch (UnknownHostException e) {
			e.printStackTrace();
		}
	}
}
```

Run it using IBM Semeru 17 Milestone 2:

- Once with standard options:
   `java.exe tests\TestCompactString.java`
   and see the result, which is expected:
   `hostName=LP5-LAI-ACM`
   `hostName2=LP5-LAI-ACM.localdomain`
   `hostName2.startsWith(hostname) returned true`

- Once with  -XX:+CompactStrings option:
   `java.exe -XX:+CompactStrings tests\TestCompactString.java`
   and see the result, which is failing:
   `hostName=LP5-LAI-ACM`
   `hostName2=LP5-LAI-ACM.localdomain`
   `hostName2.startsWith(hostname) returned false`

It looks like InetAddress.getLocalHost() isn't compatible with -XX:+CompactStrings.

The same scenario works well with Adoptium JDK 17.

Would you please check this ?

Kind regards,
Alexandre

**Comment by tajila** [comment]
I tried the test case with:

```
openjdk version "17" 2021-09-14
IBM Semeru Runtime Open Edition 17.0.0.0-m1 (build 17+35)
Eclipse OpenJ9 VM 17.0.0.0-m1 (build openj9-0.28.0-m2, JRE 17 Linux amd64-64-Bit Compressed References 20210916_37 (JIT enabled, AOT enabled)
OpenJ9   - 12ac773fe
OMR      - 377314cb0
JCL      - 41171df43e2 based on jdk-17+35)
```

And it works as expected. Perhaps this is windows specific.

**Comment by avermeer** [comment]
Hello,

Thanks for your tests, and indeed I don't reproduce on Linux:

```
/mnt/jdk-17+35/bin/java tests/TestCompactString.java
hostName=ip-172-31-44-199.eu-west-1.compute.internal
hostName2=ip-172-31-44-199.eu-west-1.compute.internal.localdomain
hostName2.startsWith(hostName) returned  true
[root@ip-172-31-44-199 mnt]# /mnt/jdk-17+35/bin/java -XX:+CompactStrings tests/TestCompactString.java
hostName=ip-172-31-44-199.eu-west-1.compute.internal
hostName2=ip-172-31-44-199.eu-west-1.compute.internal.localdomain
hostName2.startsWith(hostName) returned  true
```

But I do reproduce on my Windows 10 Professional machine, so that sounds Windows-specific *and* OpenJ9 specific.

If that matters, I took IBM Semeru 17 Milestone 2 binaries from https://github.com/ibmruntimes/semeru17-binaries/releases/tag/jdk-17%2B35_openj9-0.28.0-m2

And I confirm that this issue is OpenJ9 (aka IBM Semeru) specific, on same Windows machine with Adoptium OpenJDK 17, it does not reproduces, see the traces:
```

E:\users\foo>"E:\nosave\install\IBM\Semeru\ibm-semeru-open-jdk_x64_windows_17_35_openj9-0.28.0-m2\jdk-17+35\bin\java.exe" tests\TestCompactString.java
hostName=LP5-AVE-DSY
hostName2=LP5-AVE-DSY.localdomain
hostName2.startsWith(hostName) returned  true

E:\users\foo>"E:\nosave\install\IBM\Semeru\ibm-semeru-open-jdk_x64_windows_17_35_openj9-0.28.0-m2\jdk-17+35\bin\java.exe" -XX:+CompactStrings tests\TestCompactString.java
hostName=LP5-AVE-DSY
hostName2=LP5-AVE-DSY.localdomain
hostName2.startsWith(hostName) returned  false

E:\users\foo>
E:\users\foo>"E:\nosave\install\Adoptium\jdk-17+35\bin\java.exe" tests\TestCompactString.java
hostName=LP5-AVE-DSY
hostName2=LP5-AVE-DSY.localdomain
hostName2.startsWith(hostName) returned  true

E:\users\foo>"E:\nosave\install\Adoptium\jdk-17+35\bin\java.exe" -XX:+CompactStrings tests\TestCompactString.java
hostName=LP5-AVE-DSY
hostName2=LP5-AVE-DSY.localdomain
hostName2.startsWith(hostName) returned  true

```

**Comment by avermeer** [comment]
@tajila , do you imply that Adoptium Java 17's OpenJDK would not comply with Java spec?
And what's the relationship of this idea and the use of -XX:CompactStrings option?

**Comment by avermeer** [comment]
OK thanks for the clarification, so do you agree that it's a bug on OpenJ9 ?

**Comment by avermeer** [comment]
@tajila isn't the actual issue the fact that `InetAddress.getLocalHost()` returns an UTF-16 string on Windows although option `-XX:+CompactStrings` is passed to the JVM ?

That `String.startsWith()` returns false when string have different encoding sounds OK and doesn't seem to me to be the actual root cause of the issue.

Would you agree?

**Comment by pshipton** [comment]
Yes it's some kind of OpenJ9 problem. The weird part is that getLocalHost() comes from the OpenJDK code so should just work. Likley there is a check for compact strings missing in a JNI string creation path.

**Comment by pshipton** [comment]
@avermeer if you want to try the fix, there is a PR build available now https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_x86-64_windows_Personal/74/OpenJ9-JDK17-x86-64_windows-20211130-141737.tar.gz

**Comment by avermeer** [comment]
@pshipton yes, tested with success, many thanks!

 Would it be possible to have a JRE build with this fix to confirm that our issue is solved (as we don't embark the full JDK for this case, but only JRE) ?

**Comment by pshipton** [comment]
I don't have any easy way to do that, other than manually. You should be able to substitute a full JDK for a JRE without any problem other than disk space. Or run jlink on the JDK with the list of modules in the JRE (`java --list-modules`) to create one yourself, which is basically what the build does.

I did put the fix into the 0.29.1 Java 17 release which I hope will be released soon, within the next couple of weeks.

**Comment by pshipton** [comment]
Seems to me that Adoptium decided not to create JREs for Java 17, so the Java 17 Semeru release may not contain them either. Although that decision may be reversed in the future. @AdamBrousseau what is the current status of creating JREs for Java 17?

**Comment by AdamBrousseau** [comment]
IBM decided to proceed with producing jres for Semeru Open Edition for jdk17. Adoptium has since reopened the issue and are likely to produce them as well.

**Comment by pshipton** [comment]
I assume that means the Java 17 GA (0.29.1) Semeru build will contain JREs.
