### ISSUE TITLE
__pthread_mutex_lock: Assertion `mutex->__data.__owner == 0'

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13669]
Maybe a dup of https://github.com/eclipse-openj9/openj9/issues/13469

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_1/11 - ub20-aarch64-2
ParallelStreamsLoadTest_CS_0
-Xgcpolicy:gencon -Xgc:concurrentScavenge

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly_testList_1/11/system_test_output.tar.gz
```
LT  04:24:03.672 - Starting thread. Suite=0 thread=0
LT  04:24:03.673 - Starting thread. Suite=0 thread=1
LT  stderr java: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_aarch64_linux_Release_testList_1/2 - ub20-aarch64-1
ParallelStreamsLoadTest_CS_0

**Comment by pshipton** [comment]
Yup. All the open jdk17 testing is on the 0.29.0 branch atm, and https://github.com/eclipse-openj9/openj9/pull/13676 isn't merged yet. Just recording the failures for future reference.

**Comment by knn-k** [comment]
I ran ParallelStreamsLoadTest_CS_0 with JDK 17 + PR #13676 100 times locally, and got no failures.
