### ISSUE TITLE
[JEP389/JDK17] Unable to load the standard C runtime library in OpenJDK17

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#13679]
The java & native code associated with `LibraryLookup::ofDefault` for library loading (previously works good on AIX in OpenJDK16) were totally removed since OpenJDK17 and replaced with  `Clinker.systemlookup`, in which case it only supports loading `libc.so` but it doesn't work for `libc.a` on AIX at https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/SystemLookup.java
```
    /*
     * On POSIX systems, dlsym will allow us to lookup symbol in library dependencies; the same trick doesn't work
     * on Windows. For this reason, on Windows we do not generate any side-library, and load msvcrt.dll directly instead.
     */
    private static final SymbolLookup syslookup = switch (CABI.current()) {
        case SysV, LinuxAArch64, MacOsAArch64, AIX (doesn't work this way) -> libLookup(libs -> libs.loadLibrary("syslookup"));
        case Win64 -> makeWindowsLookup(); // out of line to workaround javac crash
    };
```
which means the current implementation in OpenJDK17 only supports loading the dynamic libraries created/defined by users but fails to load standard C runtime libraries (e.g. `malloc`, `free`, `strlen`, etc) on AIX.  I suspect we might need to create a custom system lookup (something similar to the code specific to Windows but still not quite sure whether it works even in this way) on AIX but can't get it working until we figure out everything of how it works to load native libraries in OpenJDK17. 

In such case, we need to skip the issue for the moment and come back to address it once we fix up all other issues in downcall & upcall.

FYI: @tajila, @pshipton, @DanHeidinga

**Comment by tajila** [comment]
> OpenJDK17 GA-ed already, right? Adoptium AIX driver is running fine

The openJDK version GA'ed, but I don't think they support AIX. The Openj9 version hasnt GA'ed yet.

> So, this issue is a confusion to me. If it is an existing issue, AIX driver is expected to be fundamentally broken, isn't it?

This issue is specific to Foreign linker, it wont be noticeable unless you run the incubator feature.

**Comment by ChengJin01** [comment]
The issue has been resolved in https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/112, https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/57 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/457.
