### ISSUE TITLE
ValueTypes: Recognize reference types 

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13697]
http://cr.openjdk.java.net/~dlsmith/jep401/jep401-20210702/specs/primitive-objects-jvms.html#jvms-4.3.2

Constant_class descriptors will now recognize the following
LClassName;
QClassName;
[LorQClassName;

**Comment by tajila** [comment]
Yes

**Comment by theresa-m** [comment]
Closing this issue since it is for an old spec version.
