### ISSUE TITLE
ValueTypes: add new java.lang.Class API methods JIT implementation

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#13695]
```
    public Class<?> asPrimaryType();
    public Class<?> asValueType();
    public boolean isPrimaryType();
    public boolean isValueType(); 
    public boolean isPrimitiveClass()
```

See https://github.com/eclipse-openj9/openj9/issues/13615

**Comment by hangshao0** [comment]
A bit update on the APIs: https://github.com/eclipse-openj9/openj9/issues/13615#issuecomment-1024625349

**Comment by theresa-m** [comment]
These methods have mostly been removed (see https://github.com/eclipse-openj9/openj9/pull/19736). The remaining are:
- `Class.isValue`
- `Class.asNullRestrictedType`

**Comment by hangshao0** [comment]
I don't see `Class.asNullRestrictedType` here:

 https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/blob/openj9/src/java.base/share/classes/java/lang/Class.java

Where did you see that ? If it is gone, this can be closed.

**Comment by theresa-m** [comment]
You are right. I'll remove it from OpenJ9's Class.java and close this then.
