### ISSUE TITLE
Testing times out on mac10-x86-1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13718]
Disabled it.

Many examples but here is one https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_0/123/console
```
Running on mac10-x86-1 in /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_0
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
Cancelling nested steps due to timeout
ERROR: Cannot delete workspace :null
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Finished: FAILURE
```

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
These are the 2 mac's we just moved to unb. I've removed the labels for now till we can properly test them.

**Comment by AdamBrousseau** [comment]
san.func running on
mac10-2
[![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Test_openjdk11_j9_sanity.functional_x86-64_mac_Personal&build=100)](https://openj9-jenkins.osuosl.org/view/Test_Functional_Personal/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_Personal/100/)

mac10-1 I rebooted. Still hung doing cleanWs()
https://openj9-jenkins.osuosl.org/view/Test_Functional_Personal/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_Personal/101/console
This will need some more investigation. If 2 is good I'll add back the labels.

**Comment by pshipton** [comment]
@AdamBrousseau We're getting frequent findEnv crashes on https://openj9-jenkins.osuosl.org/computer/osx1011-x86-1/ so I'd like to disable this machine. Before doing so we should have another machine online in the builds.

I'd like to have https://openj9-jenkins.osuosl.org/computer/mac10-x86-1/ working, and/or https://openj9-jenkins.osuosl.org/computer/osx1011-x86-2/ updated to a newer version. I'm hoping if we upgrade it then we won't have the arraycopy crash that occurred frequently on this machine, and it can be used in the builds. Otherwise if we can't update it or it still doesn't work after upgrade then it can be retired as a bad machine.

Similarly for osx1011-x86-1, after it's disabled it can be upgraded if possible and then we can try it again in the builds.

**Comment by AdamBrousseau** [comment]
mac10-1 setup to use semeru 11.0.8 for running the agent. Personal build running now to test compile and sanity.openjdk
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/142/

**Comment by AdamBrousseau** [comment]
Had to add the Artifactory cert to the keystore. Compile passed.
There is also basrc PATH export which adds bash 5 form usr/local. Default bash is 3.19 which is too old for compile.
sanity.openjdk running in a grinder now
[![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Grinder&build=797)](https://openj9-jenkins.osuosl.org/job/Grinder/797/)

**Comment by AdamBrousseau** [comment]
Build passed so I've put the build and test labels back on. Keep an eye on it.

**Comment by AdamBrousseau** [comment]
I also took 1011-1 offline
