### ISSUE TITLE
Another Performance problem of Minecraft when using balanced gc

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#13717]
Java -version output
--------------------
```
openjdk version "11.0.12" 2021-07-20
IBM Semeru Runtime Open Edition 11.0.12.0 (build 11.0.12+7)
Eclipse OpenJ9 VM 11.0.12.0 (build openj9-0.27.0, JRE 11 Windows 7 amd64-64-Bit Compressed References 20210730_175 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - 21849e2ca0 based on jdk-11.0.12+7)
```
Summary of problem
------------------
I use [Sodium](https://github.com/HyperCubeMC/sodium-fabric) to boost fps in modded minecraft. Use balanced gc causing FPS lower than gencon. The FPS drop from 60 to 30. I used visualvm and spark mod to get performance information. When enable balanced gc,"Chunk Render Task Executor" thread use more resource
VisualVM:
![20211016](https://user-images.githubusercontent.com/40121560/137578363-c78f0973-7091-4840-acc6-279a3f36b5db.jpg)
![20211016124341685](https://user-images.githubusercontent.com/40121560/137578606-f3ca2219-e2bd-4a19-b087-c3986b76bd3e.jpg)
In game debug HUD(balanced gc):
![2021-10-16_13 54 22](https://user-images.githubusercontent.com/40121560/137578447-fe97bf6e-7bf0-49e0-b978-945d89e16fe9.png)
Another image(gencon gc)
![gencon](https://user-images.githubusercontent.com/40121560/137578486-5852c29b-37fd-4176-9fca-a2170f140772.png)

Diagnostic files
----------------

Thread dump:https://pastebin.com/5TJWUR3H
Spark report(balanced gc):https://spark.lucko.me/r5P5gUdow2
Spark report(gencon)https://spark.lucko.me/RxVwHDhIx4
Java option:
`-Xmx2800M -Xgcpolicy:balanced -Dcom.sun.management.jmxremote.port=1919 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false`
GC verbose file:
[verbosegc.20211016.134120.7040.zip](https://github.com/eclipse-openj9/openj9/files/7357167/verbosegc.20211016.134120.7040.zip)

**Comment by pshipton** [comment]
@amicic @dmitripivkine
