### ISSUE TITLE
Recognize Windows 11 and Windows Server 2022

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13755]
Running on Windows 11 still identifies as Windows 10. This is the same as Hotspot builds for the builds available from Adoptium now, but need to check the latest release builds, in particular 17.0.1, when it becomes available.
```
os.name = Windows 10
os.version = 10.0
```

**Comment by pshipton** [comment]
@mikezhang1234567890 we can proceed with fixing this now.

**Comment by pshipton** [comment]
I still don't see the ID for Windows 11 in the manifest, but nightly Temurin builds from Adoptium for 11, 17 are showing "os.name = Windows 11" so perhaps they have patched the OpenJDK code.

**Comment by keithc-ca** [comment]
The code I referenced earlier (https://github.com/eclipse-openj9/openj9/issues/13755#issuecomment-951230263) is the same in Adoptium's mirror of jdk11u, so it would appear that the `ID` for Windows 11 is not needed.

Perhaps we should defer to openjdk code to set `os.name` and `os.version`?

**Comment by pshipton** [comment]
> The code I referenced earlier (#13755 (comment)) is the same in Adoptium's mirror of jdk11u, so it would appear that the ID for Windows 11 is not needed.

Yes, this is possible, considering Windows 11 identifies as 10. The OpenJDK change wasn't in the 11.0.13 release but it's in the current jdk11 builds now.

> Perhaps we (OpenJ9) should defer to openjdk code to set os.name and os.version?

If it's feasible to call the OpenJDK native code without negative side affects.

Note we also need to recognize Windows Server 2022.

**Comment by pshipton** [comment]
> Perhaps we (OpenJ9) should defer to openjdk code to set os.name and os.version?
> If it's feasible to call the OpenJDK native code without negative side affects.

It doesn't seem too feasible, and certainly not something we want for the 0.30 release this late in the release cycle. For this release at least, the OMR port library should be updated. It should be updated anyway from an OMR maintenance point of view.

**Comment by pshipton** [comment]
Keep this open until the change is promoted and ported to the 0.30 release.

**Comment by pshipton** [comment]
@mikezhang1234567890 given the pre-testing, promoting shouldn't be an issue, can you please go ahead and cherry pick for the 0.30 release.

**Comment by pshipton** [comment]
The change is promoted and delivered to 0.30 via https://github.com/eclipse-openj9/openj9-omr/pull/131 now.
