### ISSUE TITLE
AIX machines running very slow

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13782]
In the past week or more the AIX machines seem to be running quite slow, causing the occasional timeout, but also dragging out testing and promotion, as it's waiting for the AIX testing to finish.

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Compile jdk11
![image](https://user-images.githubusercontent.com/6430052/140808258-8f079c69-61bc-4e81-80aa-56e875df4986.png)
Sanity functional bucket 1 of 2
![image](https://user-images.githubusercontent.com/6430052/140808336-4eb03751-3872-40b8-8a76-8da30ef06f11.png)

**Comment by pshipton** [comment]
All the AIX machines were replaced and the new machines aren't as slow.
