### ISSUE TITLE
SharedClasses.SCM23.MultiThreadMultiCL_1 Attempt to set readerCount to -1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13837]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_0/135
SharedClasses.SCM23.MultiThreadMultiCL_1 -Xcompressedrefs -Xjit -Xgcpolicy:gencon

No interesting diagnostics, no shared cache, no cores, no crash report.

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_0/135/system_test_output.tar.gz
```
MTM5 stderr JVMSHRC129E Attempt to set readerCount to -1!
MTM5 stderr JVMSHRC129E Attempt to set readerCount to -1!
STF 00:11:05.943 - **FAILED** Process MTM2 ended with exit code (3221225477) and not the expected exit code/s (0)
STF 00:11:07.049 - Monitoring Report Summary:
STF 00:11:07.049 -   o Process MTM1 is still running
STF 00:11:07.049 -   o Process MTM2 ended with exit code (3221225477) and not the expected exit code/s (0)
STF 00:11:07.050 -   o Process MTM3 is still running
STF 00:11:07.050 -   o Process MTM4 is still running
STF 00:11:07.050 -   o Process MTM5 is still running
```

@hangshao0 fyi. 
There was an older similar issue https://github.com/eclipse-openj9/openj9/issues/9893

**Comment by hangshao0** [comment]
We may have to exit the read mutex before taking the segment mutex in `SH_CompositeCacheImpl::updateMetadataSegment()`, then enter the read mutex again after the metadata segment is updated.

**Comment by hangshao0** [comment]
> |--------> calls SH_CompositeCacheImpl::updateMetadataSegment() which tries to enter class segment mutex.

I miss read the code. It is memory segment mutex inside `updateMetadataSegment()`, not class segment mutex.

**Comment by hangshao0** [comment]
The timeout might be caused by reader waiting for the write mutex in `updateRuntimeFullFlags()` after `readerCount` is incremented.
