### ISSUE TITLE
RISC-V support added VAR_CPU_ARCH=riscv

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13863]
**JDK-8199138: Add RISC-V support to Zero [1]**

```
    riscv64)
      VAR_CPU=riscv64
      VAR_CPU_ARCH=riscv
      VAR_CPU_BITS=64
      VAR_CPU_ENDIAN=little
      ;;
```

There was an JCL patch adding `VAR_CPU_ARCH=riscv64` [2], note the OpenJDK changing it to `riscv`.
Though this is a change at the extension repo, I think `OpenJ9` might have to adopt it.

fyi @ChengJin01 

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/7017510e02b1531c611c38a8b0b4d64c8d296626
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/4148fad3676398e526bb7d366f6517c7d685175d/make/autoconf/platform.m4#L123

**Comment by keithc-ca** [comment]
I don't see any uses of `*_CPU_ARCH` that should need to be updated for RISC-V, and so don't expect any changes will be required.

**Comment by JasonFengJ9** [comment]
> I don't see any uses of *_CPU_ARCH that should need to be updated for RISC-V, and so don't expect any changes will be required.

Closing then.
