### ISSUE TITLE
Download API URL

### ISSUE THREAD

**Issue by srbala** [eclipse-openj9/openj9#13862]
Working on a CI/CD build automation which downlods file and its SHA for packaing purposes. Is there any API available similar to `adoptium` below available for `OpenJ9`?

```sh
JDK8_URL="$(curl -s --head https://api.adoptium.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/adoptium | grep 'Location:' | sed 's/Location: //g'| tr -d '\r')"
JDK8_URL_SHA="$JDK8_URL.sha256.txt"
```

```sh
JDK11_URL="$(curl -s --head https://api.adoptium.net/v3/binary/latest/11/ga/linux/x64/jdk/hotspot/normal/adoptium | grep 'Location:' | sed 's/Location: //g'| tr -d '\r')"
JDK11_URL_SHA="$JDK11_URL.sha256.txt"
```

**Comment by srbala** [comment]
Ok, I was able to find some answer from IBM page https://www.ibm.com/support/pages/semeru-runtimes-getting-started/

Needed to adjust my script as below to get Java 11 JDK and JRE as below

```sh
JDK11_URL="$(curl -s --head 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk?project=jdk' | grep 'location:' | sed 's/location: //g'| tr -d '\r')"
JDK11_URL_SHA="$JDK11_URL.sha256.txt"
JRE11_URL="$(curl -s --head 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jre/openj9/normal/adoptopenjdk?project=jdk' | grep 'location:' | sed 's/location: //g'| tr -d '\r')"
JRE11_URL_SHA="$JRE11_URL.sha256.txt"
```

This good enough, closing issue.

**Comment by pshipton** [comment]
Note the best place for these types of questions is https://github.com/ibmruntimes/Semeru-Runtimes/issues

**Comment by AdamBrousseau** [comment]
Copy/paste from the support page here for everyone.

>IBM is working to host a RESTful API server that uses the new Eclipse Adoptium™ OpenAPI definition. Until that is ready we offer the IBM Semeru Runtime Open Edition from the RESTful API provided by the AdoptOpenJDK community, and follow the [AdoptOpenJDK OpenAPI definition](https://api.adoptopenjdk.net/q/swagger-ui/).
