### ISSUE TITLE
JDK 17 semeru17-binaries JRE packages

### ISSUE THREAD

**Issue by srbala** [eclipse-openj9/openj9#13861]
JDK 17 semeru17-binaries releases missing JRE packages.

https://github.com/ibmruntimes/semeru17-binaries/tree/jdk-17.0.1%2B12_openj9-0.29.1-m1

**Comment by pshipton** [comment]
Better to comment in https://github.com/adoptium/temurin-build/issues/2683, or create an issue in https://github.com/ibmruntimes/Semeru-Runtimes/issues. Semeru uses Adoptium pipelines to produce the builds, which don't support creation of JREs for Java 17. This is not an OpenJ9 problem.

**Comment by pshipton** [comment]
Note that it's possible to create a JRE by running the `jlink` tool, and providing the list of modules to be in the JRE.

**Comment by sxa** [comment]
See https://blog.adoptium.net/2021/10/jlink-to-produce-own-runtime/ if you want a guide to doing that.

> Note that it's possible to create a JRE by running the `jlink` tool, and providing the list of modules to be in the JRE.

To anyone reading this, see https://blog.adoptium.net/2021/10/jlink-to-produce-own-runtime/ if you want a guide to doing that :-)
