### ISSUE TITLE
OpenJ9 adds -javaagent JAR to the classpath twice

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#13874]
When running with a javaagent command line option like this:

`-javaagent:agenttest.jar`

The agent JAR will be added to the system class loader's class path so the JVM can find it. With Temurin/Hotspot, the JAR only appears on the class path once, but with a Semeru/OpenJ9 the JAR is added twice.

To reproduce, run the attached testcase like this:

`java -javaagent:agenttest.jar PrintClassPath`

With Hotspot (`OpenJDK8U-jdk_x86-32_windows_hotspot_8u312b07`) I see this result:

```
Agent started
Classpath from java.class.path system property:
        .;agenttest.jar
Classpath from URLClassLoader:
        file:/C:/testcases/agenttest/
        file:/C:/testcases/agenttest/agenttest.jar
```

But with OpenJ9 (`OpenJDK8U-jdk_x86-32_windows_hotspot_8u312b07`) I see this result:

```
Agent started
Classpath from java.class.path system property:
        .;agenttest.jar;agenttest.jar
Classpath from URLClassLoader:
        file:/C:/testcases/agenttest/
        file:/C:/testcases/agenttest/agenttest.jar
        file:/C:/testcases/agenttest/agenttest.jar
```

This has no detrimental effects as far I can tell, but it looks untidy.

[testcase.zip](https://github.com/eclipse-openj9/openj9/files/7496604/testcase.zip)

**Comment by dnakamura** [comment]
Issue appears to be that the  `-javaagent:`  argument is added to the classpath, and then remapped to `-agentlib:instrument=`.
When the `-agentlib:instrument=` argument is parsed, it is also added to the classpath, resulting in the double entries.

**Comment by pshipton** [comment]
Adding to the 0.40 milestone since there is a pending fix.

**Comment by keithc-ca** [comment]
> This has no detrimental effects as far I can tell

It may have a negative effect on performance; it generally takes longer to fail to find a class in a location in the classpath than to find it; failing twice is worse. It may make sense to generalize this to removing all duplicate entries in the classpath, and in other lists like `LD_LIBRARY_PATH` or `PATH`.
