### ISSUE TITLE
j9constantpool doesn't check versions properly

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13871]
### Summary of problem
------------------

`j9constantpool` [1] doesn't check versions properly for `classref`, `fieldref`, and maybe others.

JDK8 doesn't have the class `java.lang.invoke.FilterArgumentsWithCombinerHandle`
https://github.com/eclipse-openj9/openj9/blob/bad687ee7ae3ff98cf547882ba4abb77e19f1b69/runtime/oti/vmconstantpool.xml#L103
However `j9vmconstantpool.h` generated for JDK8 has following
```
#define J9VMCONSTANTPOOL_JAVALANGINVOKEFILTERARGUMENTSWITHCOMBINERHANDLE 80
#define J9VMJAVALANGINVOKEFILTERARGUMENTSWITHCOMBINERHANDLE(vm) J9VMCONSTANTPOOL_CLASS_AT(vm, J9VMCONSTANTPOOL_JAVALANGINVOKEFILTERARGUMENTSWITHCOMBINERHANDLE)
#define J9VMJAVALANGINVOKEFILTERARGUMENTSWITHCOMBINERHANDLE_OR_NULL(vm) (J9VMCONSTANTPOOL_CLASSREF_AT(vm, J9VMCONSTANTPOOL_JAVALANGINVOKEFILTERARGUMENTSWITHCOMBINERHANDLE)->value)
```

Similarly JDK8 doesn't have the field `java.lang.reflect.Field.trustedFinal`
https://github.com/eclipse-openj9/openj9/blob/bad687ee7ae3ff98cf547882ba4abb77e19f1b69/runtime/oti/vmconstantpool.xml#L237
JDK8 `j9vmconstantpool.h` still has following
```
#define J9VMCONSTANTPOOL_JAVALANGREFLECTFIELD_TRUSTEDFINAL 193
#define J9VMJAVALANGREFLECTFIELD_TRUSTEDFINAL_OFFSET(vmThread) J9VMCONSTANTPOOL_FIELD_OFFSET(J9VMTHREAD_JAVAVM(vmThread), J9VMCONSTANTPOOL_JAVALANGREFLECTFIELD_TRUSTEDFINAL)
#define J9VMJAVALANGREFLECTFIELD_TRUSTEDFINAL(vmThread, object) ((void)0, \
        J9OBJECT_U32_LOAD(vmThread, object, J9VMJAVALANGREFLECTFIELD_TRUSTEDFINAL_OFFSET(vmThread)))
#define J9VMJAVALANGREFLECTFIELD_SET_TRUSTEDFINAL(vmThread, object, value) ((void)0, \
        J9OBJECT_U32_STORE(vmThread, object, J9VMJAVALANGREFLECTFIELD_TRUSTEDFINAL_OFFSET(vmThread), (value)))
```

This is the reason why some code not for JDK8 w/o `#if JAVA_SPEC_VERSION >= 11` still compiles.
https://github.com/eclipse-openj9/openj9/blob/bad687ee7ae3ff98cf547882ba4abb77e19f1b69/runtime/vm/MHInterpreter.hpp#L169
A quick search shows there are large number of such code snippet w/o matching `JAVA_SPEC_VERSION` defines.

### Proposed solution

It can be fixed in two stages.
* First stage
  * Fix `j9constantpool` to enforce version check such that no new defines can escape the version range;
  * Remove existing version specification within `vmconstantpool.xml` that have build breakage due to the version check applied above; 
*  Second stage
   * Restore the version specification w/ proper `JAVA_SPEC_VERSION` defines. 

fyi @keithc-ca @pshipton @tajila 

[1] https://github.com/eclipse-openj9/openj9/tree/master/sourcetools/j9constantpool

**Comment by pshipton** [comment]
Is there a user visible problem? Not sure the userRaised label is appropriate.

**Comment by JasonFengJ9** [comment]
There are unanticipated code generated for earlier Java levels but no visible user application problem.

**Comment by keithc-ca** [comment]
I think the notion of 'aliases' has out-lived its usefulness. For example, instead of writing
```
	<fieldref class="java/lang/String" name="value" signature="[B" versions="9-">
		<fieldalias name="value" signature="[C" versions="8"/>
	</fieldref>
```
we could say
```
	<fieldref class="java/lang/String" name="value" signature="[C" versions="8"/>
	<fieldref class="java/lang/String" name="value" signature="[B" versions="9-"/>
```

**Comment by JasonFengJ9** [comment]
> I think the notion of 'aliases' has out-lived its usefulness. 

That will be true if the `versions` checking in this issue is fixed.
