### ISSUE TITLE
JDK11 cmdLineTester_xlogTests_0_FAILED: Failure condition was found: [Output match: verbosegc]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13894]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_2/45/tapResults/` (`ub18-aarch64-10`):
```
22:02:06  "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java" -version
22:02:06  openjdk version "11.0.14-beta" 2022-01-18
22:02:06  IBM Semeru Runtime Open Edition 11.0.14+1-202111090205 (build 11.0.14-beta+1)
22:02:06  Eclipse OpenJ9 VM 11.0.14+1-202111090205 (build master-3f6696680, JRE 11 Linux aarch64-64-Bit Compressed References 20211109_244 (JIT enabled, AOT enabled)
22:02:06  OpenJ9   - 3f6696680
22:02:06  OMR      - ec51e647d
22:02:06  JCL      - 2f7b4f2d31 based on jdk-11.0.14+1)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_2&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_aarch64_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F244%2Fibm-semeru-open-jdk_aarch64_linux_JDK11U_2021-11-09-02-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F244%2Fibm-semeru-open-debugimage_aarch64_linux_JDK11U_2021-11-09-02-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F244%2Fibm-semeru-open-testimage_aarch64_linux_JDK11U_2021-11-09-02-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F244%2Fibm-semeru-open-jre_aarch64_linux_JDK11U_2021-11-09-02-00.tar.gz&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&PLATFORM_AND_MACHINE_HELP_TEXT=&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=106&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test cmdLineTester_xlogTests_0 ...
===============================================
cmdLineTester_xlogTests_0 Start Time: Mon Nov  8 22:40:26 2021 Epoch Time (ms): 1636429226800
variation: NoOptions
JVM_OPTIONS:  

Testing: -Xlog:gc=warning
Test start time: 2021/11/08 22:40:30 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java"   -XX:-LegacyXlogOption -Xlog:gc=warning -version
Time spent starting: 1 milliseconds
Time spent executing: 126 milliseconds
Test result: FAILED
Output from test:
 [ERR] JVMJ9VM007W Command-line option unrecognised: -Xlog:gc=warning

>> Success condition was found: [Output match: (openjdk|java|semeru) version]
>> Required condition was found: [Output match: JVMJ9VM007W]
>> Failure condition was found: [Output match: verbosegc]
>> Failure condition was not found: [Output match: JVMJ9VM085]

Testing: -Xlog:gc=error
Test start time: 2021/11/08 22:40:30 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_2/openjdkbinary/j2sdk-image/bin/java"   -XX:-LegacyXlogOption -Xlog:gc=error -version
Time spent starting: 1 milliseconds
Time spent executing: 124 milliseconds
Test result: FAILED
Output from test:
 [ERR] JVMJ9VM007W Command-line option unrecognised: -Xlog:gc=error

>> Success condition was found: [Output match: (openjdk|java|semeru) version]
>> Required condition was found: [Output match: JVMJ9VM007W]
>> Failure condition was found: [Output match: verbosegc]
>> Failure condition was not found: [Output match: JVMJ9VM085]
```

This is across platforms, and appears a regression.

**Comment by pshipton** [comment]
It's related to https://github.com/eclipse-openj9/openj9/pull/13866, but it's a test mismatch, running the latest tests on older JVMs. I think just a timing problem. The OpenJ9 SHA indicates it's a level before the PR was merged (Nov 8 at 5:46pm). The change was merged Nov 8 at 9:12pm. It didn't occur in the open testing. I'll go ahead and close since it shouldn't happen in the next test runs.
