### ISSUE TITLE
Environment variables that are changed on container restore

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse-openj9/openj9#13908]
* #13545

Tracks our current position on env vars at restore - only reflect new env vars into Java and don't change existing.

This issue is to track the list of env vars that we see changing in containers and to help to quantify the blast radius of each of the changes.

Feel free to add a new comment for each env var and we can expand in the comment on the issues related to it.

**Comment by DanHeidinga** [comment]
Env Var:  HOST_NAME

Blast Radius:
*
*

**Comment by tajila** [comment]
The environment variables that may be an issue in addition to `HOST_NAME` are:

```
LANGUAGE
LANG
LC_ALL
container
SHLVL
_
```

**Comment by DanHeidinga** [comment]
`SHLVL` - shell level.  Is this being used by the class library or java applications?  I think this can move to the unlikely to be an issue list.

`_` - path of the current command.  Again, unlikely to be used by the class libraries or java apps.

**Comment by tajila** [comment]
`LANG`, `LC_ALL` and `LC_CTYPE` are used by jdk.internal.util.SystemProps.Raw via `platformProperties()`

**Comment by vijaysun-omr** [comment]
This is part of issue [16384](https://github.com/OpenLiberty/open-liberty/issues/16384)
