### ISSUE TITLE
NullPointerException thrown in StackTraceElement.hashCode with IBM Semeru runtime 11.0.13

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13941]
Copied from https://github.com/ibmruntimes/Semeru-Runtimes/issues/9#issue-1056233722

StackTraceElement.hashCode throws an unexpected NullPointerException in my application.

I created a simple reproducer app (https://github.com/dynatrace-peterlang/exception-stacktraceelement-npe).
If I run it with IBM Semeru Runtime Open Edition 11.0.13.0 (build 11.0.13+8) my app fails with a NullPointerException.

```
java.lang.NullPointerException
        at java.base/java.lang.StackTraceElement.hashCode(StackTraceElement.java:278)
        at java.base/java.util.HashMap.hash(HashMap.java:340)
        at java.base/java.util.HashMap.get(HashMap.java:553)
        at com.dynatrace.App.main(App.java:32)
```

fyi @dynatrace-peterlang

**Comment by dynatrace-peterlang** [comment]
The exception is created within a lambda function. This produces a StackTraceElement with `<unknown class>.get(Unknown Source)` or more specifically `e.declaringClass==null` and `e.methodName==get`. Finally a NullPointer is thrown in https://github.com/eclipse-openj9/openj9/blob/e1e72c497688c765183573526f7418a6fe891e93/jcl/src/java.base/share/classes/java/lang/StackTraceElement.java#L290 as `declaringClass` is null.

**Comment by JasonFengJ9** [comment]
Is the NPE intermittent? Can it be reproduced w/ `-Xint`?

**Comment by pshipton** [comment]
I expect this is fixed already in the latest by https://github.com/eclipse-openj9/openj9/issues/13759, but we should fix the hashCode impl so it doesn't throw NPE.

**Comment by pshipton** [comment]
Actually I think the code is good as-is. There was a bug, but it's fixed now. Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/13759

https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/StackTraceElement.java#L288-L290
