### ISSUE TITLE
JDK18 OpenJDK test failures

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13946]
All platforms https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/157/

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_linux_OpenJDK/1/#showFailuresLink
    java/foreign/SafeFunctionAccessTest.java.SafeFunctionAccessTest
    java/foreign/SafeFunctionAccessTest.java.SafeFunctionAccessTest
    java/foreign/StdLibTest.java.StdLibTest
    java/foreign/StdLibTest.java.StdLibTest
    java/foreign/TestDowncall.java.TestDowncall
    java/foreign/TestDowncall.java.TestDowncall
    java/foreign/TestIllegalLink.java.TestIllegalLink
    java/foreign/TestIllegalLink.java.TestIllegalLink
    java/foreign/TestIntrinsics.java.TestIntrinsics
    java/foreign/TestIntrinsics.java.TestIntrinsics
    java/foreign/TestNULLAddress.java.TestNULLAddress
    java/foreign/TestNULLAddress.java.TestNULLAddress
    java/foreign/TestNative.java.TestNative
    java/foreign/TestNative.java.TestNative
    java/foreign/TestUpcall.java.TestUpcall
    java/foreign/TestUpcall.java.TestUpcall
    java/foreign/TestUpcallException.java.TestUpcallException
    java/foreign/TestUpcallException.java.TestUpcallException
    java/foreign/TestUpcallHighArity.java.TestUpcallHighArity
    java/foreign/TestUpcallHighArity.java.TestUpcallHighArity
    java/foreign/TestUpcallStructScope.java.TestUpcallStructScope
    java/foreign/TestUpcallStructScope.java.TestUpcallStructScope
    java/foreign/TestVarArgs.java.TestVarArgs
    java/foreign/TestVarArgs.java.TestVarArgs
    java/foreign/malloc/TestMixedMallocFree.java.TestMixedMallocFree
    java/foreign/malloc/TestMixedMallocFree.java.TestMixedMallocFree
    java/foreign/stackwalk/TestAsyncStackWalk.java#default_gc.TestAsyncStackWalk_default_gc
    java/foreign/stackwalk/TestAsyncStackWalk.java#default_gc.TestAsyncStackWalk_default_gc
    java/foreign/stackwalk/TestAsyncStackWalk.java#shenandoah.TestAsyncStackWalk_shenandoah
    java/foreign/stackwalk/TestAsyncStackWalk.java#shenandoah.TestAsyncStackWalk_shenandoah
    java/foreign/stackwalk/TestAsyncStackWalk.java#zgc.TestAsyncStackWalk_zgc
    java/foreign/stackwalk/TestAsyncStackWalk.java#zgc.TestAsyncStackWalk_zgc
    java/foreign/stackwalk/TestStackWalk.java#default_gc.TestStackWalk_default_gc
    java/foreign/stackwalk/TestStackWalk.java#default_gc.TestStackWalk_default_gc
    java/foreign/stackwalk/TestStackWalk.java#shenandoah.TestStackWalk_shenandoah
    java/foreign/stackwalk/TestStackWalk.java#shenandoah.TestStackWalk_shenandoah
    java/foreign/stackwalk/TestStackWalk.java#zgc.TestStackWalk_zgc
    java/foreign/stackwalk/TestStackWalk.java#zgc.TestStackWalk_zgc
    java/foreign/valist/VaListTest.java.VaListTest
    java/foreign/valist/VaListTest.java.VaListTest
    java/foreign/virtual/TestVirtualCalls.java.TestVirtualCalls
    java/foreign/virtual/TestVirtualCalls.java.TestVirtualCalls
    java/lang/StringBuilder/HugeCapacity.java.HugeCapacity
    java/lang/StringBuilder/HugeCapacity.java.HugeCapacity
    java/lang/System/AllowSecurityManager.java.AllowSecurityManager
    java/lang/System/AllowSecurityManager.java.AllowSecurityManager
    java/lang/System/FileEncodingTest.java.FileEncodingTest
    java/lang/System/FileEncodingTest.java.FileEncodingTest
    java/lang/System/SecurityManagerWarnings.java.SecurityManagerWarnings
    java/lang/System/SecurityManagerWarnings.java.SecurityManagerWarnings
    java/lang/Thread/UncaughtExceptionsTest.java.UncaughtExceptionsTest
    java/lang/Thread/UncaughtExceptionsTest.java.UncaughtExceptionsTest
    java/lang/annotation/LoaderLeakTest.java.LoaderLeakTest
    java/lang/annotation/LoaderLeakTest.java.LoaderLeakTest
    java/lang/annotation/typeAnnotations/GetAnnotatedOwnerType.java.GetAnnotatedOwnerType
    java/lang/annotation/typeAnnotations/GetAnnotatedOwnerType.java.GetAnnotatedOwnerType
    java/lang/annotation/typeAnnotations/TestExecutableGetAnnotatedType.java.TestExecutableGetAnnotatedType
    java/lang/annotation/typeAnnotations/TestExecutableGetAnnotatedType.java.TestExecutableGetAnnotatedType
    java/lang/annotation/typeAnnotations/TestObjectMethods.java.TestObjectMethods
    java/lang/annotation/typeAnnotations/TestObjectMethods.java.TestObjectMethods
    java/lang/constant/MethodHandleDescTest.java.MethodHandleDescTest
    java/lang/constant/MethodHandleDescTest.java.MethodHandleDescTest
    java/lang/invoke/7087570/Test7087570.java.Test7087570
    java/lang/invoke/7087570/Test7087570.java.Test7087570
    java/lang/invoke/7157574/Test7157574.java.Test7157574
    java/lang/invoke/7157574/Test7157574.java.Test7157574
    java/lang/invoke/7196190/ClassForNameTest.java.ClassForNameTest
    java/lang/invoke/7196190/ClassForNameTest.java.ClassForNameTest
    java/lang/invoke/7196190/GetUnsafeTest.java.GetUnsafeTest
    java/lang/invoke/7196190/GetUnsafeTest.java.GetUnsafeTest
    java/lang/invoke/8177146/TestMethodHandleBind.java.TestMethodHandleBind
    java/lang/invoke/8177146/TestMethodHandleBind.java.TestMethodHandleBind
    java/lang/invoke/InvokeDynamicPrintArgs.java.InvokeDynamicPrintArgs
    java/lang/invoke/InvokeDynamicPrintArgs.java.InvokeDynamicPrintArgs
    java/lang/invoke/JavaDocExamplesTest.java.JavaDocExamplesTest
    java/lang/invoke/JavaDocExamplesTest.java.JavaDocExamplesTest
    java/lang/invoke/MethodHandlesProxiesTest.java.MethodHandlesProxiesTest
    java/lang/invoke/MethodHandlesProxiesTest.java.MethodHandlesProxiesTest
    java/lang/invoke/callerSensitive/Main.java.Main
    java/lang/invoke/callerSensitive/Main.java.Main
    java/lang/invoke/lambda/InheritedMethodTest.java.InheritedMethodTest
    java/lang/invoke/lambda/InheritedMethodTest.java.InheritedMethodTest
    java/lang/invoke/lambda/MetafactoryArgValidationTest.java.MetafactoryArgValidationTest
    java/lang/invoke/lambda/MetafactoryArgValidationTest.java.MetafactoryArgValidationTest
    java/lang/invoke/lambda/invokeSpecial/InvokeSpecialMethodTest.java.InvokeSpecialMethodTest
    java/lang/invoke/lambda/invokeSpecial/InvokeSpecialMethodTest.java.InvokeSpecialMethodTest
    java/lang/invoke/lookup/ChainedLookupTest.java.ChainedLookupTest
    java/lang/invoke/lookup/ChainedLookupTest.java.ChainedLookupTest
    java/lang/invoke/lookup/SpecialStatic.java.SpecialStatic
    java/lang/invoke/lookup/SpecialStatic.java.SpecialStatic
    java/lang/reflect/DefaultStaticTest/DefaultStaticInvokeTest.java.DefaultStaticInvokeTest
    java/lang/reflect/DefaultStaticTest/DefaultStaticInvokeTest.java.DefaultStaticInvokeTest
    java/lang/reflect/MethodHandleAccessorsTest.java#id0.MethodHandleAccessorsTest_id0
    java/lang/reflect/MethodHandleAccessorsTest.java#id0.MethodHandleAccessorsTest_id0
    java/lang/reflect/MethodHandleAccessorsTest.java#id1.MethodHandleAccessorsTest_id1
    java/lang/reflect/MethodHandleAccessorsTest.java#id1.MethodHandleAccessorsTest_id1
    java/lang/reflect/Parameter/InnerClassToString.java.InnerClassToString
    java/lang/reflect/Parameter/InnerClassToString.java.InnerClassToString
    java/lang/reflect/Proxy/DefaultMethods.java.DefaultMethods
    java/lang/reflect/Proxy/DefaultMethods.java.DefaultMethods
    java/lang/reflect/Proxy/ProxyTest.java.ProxyTest
    java/lang/reflect/Proxy/ProxyTest.java.ProxyTest
    java/lang/reflect/Proxy/nonPublicProxy/DefaultMethodProxy.java.DefaultMethodProxy
    java/lang/reflect/Proxy/nonPublicProxy/DefaultMethodProxy.java.DefaultMethodProxy
    java/lang/reflect/classInitialization/ExceptionInClassInitialization.java.ExceptionInClassInitialization
    java/lang/reflect/classInitialization/ExceptionInClassInitialization.java.ExceptionInClassInitialization
    java/lang/reflect/exeCallerAccessTest/CallerAccessTest.java.CallerAccessTest
    java/lang/reflect/exeCallerAccessTest/CallerAccessTest.java.CallerAccessTest
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id0.GetCallerClassTest_id0
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id0.GetCallerClassTest_id0
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id1.GetCallerClassTest_id1
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id1.GetCallerClassTest_id1
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id2.GetCallerClassTest_id2
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id2.GetCallerClassTest_id2
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id3.GetCallerClassTest_id3
    jdk/internal/reflect/Reflection/GetCallerClassTest.java#id3.GetCallerClassTest_id3

@tajila fyi

**Comment by tajila** [comment]
@ChengJin01 Can please add jdk18 excludes for all the tests that are known to not work

@babsingh Please do the same for MH related tests

**Comment by babsingh** [comment]
@tajila Do we analyze the issues which need to be fixed, and create a standalone issue for each unique failure?

**Comment by tajila** [comment]
> @tajila Do we analyze the issues which need to be fixed, and create a standalone issue for each unique failure?

Yes please

**Comment by ChengJin01** [comment]
It seems there are mainly two type of failures for these FFI related test suites:
1) Only the code in phase 1 (primitive support) was merged to the repo as specified at https://github.com/eclipse-openj9/openj9/issues/12412, while the code in phase 2 & 3 (`struct` support) is still waiting for review, in which case all `struct` related test suites should be excluded for the moment on JDK18.

2) The latest API changes since JDK17 need to be addressed (e.g. the test cases related to `ResourceScope) in the code.
To avoid any conflict in the existing code, we can fix them up on the code in phase 2 & 3 at first. So these test suites also need to be excluded for the moment till the code in phase 2 & 3 is merged.

**Comment by ChengJin01** [comment]
The majority of FFI related to test suites ended up with an assertion as follows in `MemberName.vminfoIsConsistent()`:
```
Caused by: java.lang.AssertionError: 440
	at java.base/java.lang.invoke.MemberName.vminfoIsConsistent(MemberName.java:352)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1099)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3653)
	at java.base/java.lang.invoke.MethodHandles$Lookup.bind(MethodHandles.java:3301)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableInvoker.getBoundMethodHandle(ProgrammableInvoker.java:296)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.CallArranger.arrangeDowncall(CallArranger.java:136)
	at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.linux.LinuxAArch64Linker.downcallHandle(LinuxAArch64Linker.java:80)
	at jdk.incubator.foreign/jdk.internal.foreign.AbstractCLinker.downcallHandle(AbstractCLinker.java:44)
```
against the code at https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/java/lang/invoke/MemberName.java
```
 private boolean vminfoIsConsistent() {
        byte refKind = getReferenceKind();
        assert(isResolved());  // else don't call
        Object vminfo = MethodHandleNatives.getMemberVMInfo(this); <-------
        assert(vminfo instanceof Object[]);
        long vmindex = (Long) ((Object[])vminfo)[0];
        Object vmtarget = ((Object[])vminfo)[1];
        if (MethodHandleNatives.refKindIsField(refKind)) {
            assert(vmindex >= 0) : vmindex + ":" + this;
            assert(vmtarget instanceof Class);
        } else {
            if (MethodHandleNatives.refKindDoesDispatch(refKind))
                assert(vmindex >= 0) : vmindex + ":" + this;
            else
                assert(vmindex < 0) : vmindex;  <-------------------------------------------
            assert(vmtarget instanceof MemberName) : vmtarget + " in " + this;
        }
        return true;
    }
```
The issue was likely introduced by the changes at  https://github.com/eclipse-openj9/openj9/pull/13890 in native at /runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp, which has nothing to with the FFI specific tests.

FYI: @babsingh

**Comment by ChengJin01** [comment]
By disabling the assertion in code above,  the actually results of the FFI specific test suites are as follows with the missing code/exception updated in code (phase 2 & 3 / struct support) at https://github.com/eclipse-openj9/openj9/pull/13315

**[1]** test suites mixed with primitive & struct in downcall (should be excluded for the moment till the code at phase 2 & 3 is merged)
(1)  java/foreign/SafeFunctionAccessTest.java.SafeFunctionAccessTest  [PASSED & fixed missing exception in code]
[SafeFunctionAccessTest.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597318/SafeFunctionAccessTest.jtr.txt)
(2) java/foreign/TestDowncall.java.TestDowncall [PASSED / no code update]
[TestDowncall.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597363/TestDowncall.jtr.txt)
(3) java/foreign/TestIntrinsics.java.TestIntrinsics [PASSED / no code update]
[TestIntrinsics.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597367/TestIntrinsics.jtr.txt)
(4) java/foreign/TestNULLAddress.java.TestNULLAddress [PASSED & fixed the missing exception in code]
[TestNULLAddress.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597377/TestNULLAddress.jtr.txt)
(5) java/foreign/TestNative.java.TestNative [PASSED / no code update]
[TestNative.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597394/TestNative.jtr.txt)
(6) java/foreign/malloc/TestMixedMallocFree.java.TestMixedMallocFree [PASSED / no code update]
[TestMixedMallocFree.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597407/TestMixedMallocFree.jtr.txt)
(7)  java/foreign/virtual/TestVirtualCalls.java.TestVirtualCalls [PASSED  / no code update]
[TestVirtualCalls.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597426/TestVirtualCalls.jtr.txt)

**[2]** upcall related test suites (should be excluded as the development is still underway)
(1)  java/foreign/StdLibTest.java.StdLibTest [PASSED except `test_qsort()` intended for upcall)
[StdLibTest.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597484/StdLibTest.jtr.txt)
(2) java/foreign/TestUpcall.java.TestUpcall
(3) java/foreign/TestUpcallException.java.TestUpcallException
(4) java/foreign/TestUpcallHighArity.java.TestUpcallHighArity
(5) java/foreign/TestUpcallStructScope.java.TestUpcallStructScope

**[3]** VaList related test suites (should be excluded for the moment till the code at phase 2 & 3 is merged)
Note: these test suites are disabled on AIX/PPC64, Linux/PPC64LE, and Linux/s390 as the Valist is not yet implemented in OpenJDK)
(1) java/foreign/TestVarArgs.java.TestVarArgs [PASSED]
[TestVarArgs.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597521/TestVarArgs.jtr.txt)
(2) java/foreign/valist/VaListTest.java.VaListTest [PASSED except tests specific to upcall]
[VaListTest.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597529/VaListTest.jtr.txt)

**[4]** Hotspot related test suites (should be excluded as these tests are specific to the implementation in Hotspot)
(1) java/foreign/TestIllegalLink.java.TestIllegalLink [PASSED / expected exception captured but no need to match the error message expected in Hotspot as we have our own tests covering these cases)
[TestIllegalLink.jtr.txt](https://github.com/eclipse-openj9/openj9/files/7597556/TestIllegalLink.jtr.txt)
(2)  java/foreign/stackwalk/TestAsyncStackWalk.java#default_gc  (specific to the implementation in Hotspot)
(3)  java/foreign/stackwalk/TestAsyncStackWalk.java#shenandoah (specific to the implementation in Hotspot)
(4)  java/foreign/stackwalk/TestAsyncStackWalk.java#zgc (specific to the implementation in Hotspot)
(5) java/foreign/stackwalk/TestStackWalk.java#default_gc  (specific to the implementation in Hotspot)
(6) java/foreign/stackwalk/TestStackWalk.java#shenandoah  (specific to the implementation in Hotspot)
(7) java/foreign/stackwalk/TestStackWalk.java#zgc  (specific to the implementation in Hotspot)

e.g.  java/foreign/stackwalk/TestAsyncStackWalk.java#shenandoah
```
/*
 * @test id=shenandoah
 * @requires (((os.arch == "amd64" | os.arch == "x86_64") & sun.arch.data.model == "64") | os.arch == "aarch64")
 * @requires vm.gc.Shenandoah
 * @library /test/lib
 * @build sun.hotspot.WhiteBox
 * @run driver jdk.test.lib.helpers.ClassFileInstaller sun.hotspot.WhiteBox
 *
 * @run main/othervm
 *   -Xbootclasspath/a:.
 *   -XX:+UnlockDiagnosticVMOptions
 *   -XX:+WhiteBoxAPI
 *   -Djdk.internal.foreign.ProgrammableInvoker.USE_INTRINSICS=true
 *   --enable-native-access=ALL-UNNAMED
 *   -Xbatch
 *   -XX:+UseShenandoahGC
```

I will create a PR at https://github.com/adoptium/aqa-tests to exclude these test suites.

**Comment by babsingh** [comment]
@ChengJin01 Please provide https://github.com/eclipse-openj9/openj9/issues/13993 as the associated issue while disabling the `*StackWalk` tests, which are dependent on `sun.hotspot.WhiteBox`. https://github.com/eclipse-openj9/openj9/issues/13993 contains the reason for disabling these tests.

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/13946#issuecomment-978037496:
> The issue was likely introduced by the changes at #13890 in native 

Does the assertion error go away after reverting https://github.com/eclipse-openj9/openj9/pull/13890/commits/305ee169b621b3a2017bb518f5c415ee6c039ae9?

**Comment by ChengJin01** [comment]
> re [#13946 (comment)](https://github.com/eclipse-openj9/openj9/issues/13946#issuecomment-978037496):
> 
> > The issue was likely introduced by the changes at #13890 in native
> 
> Does the assertion error go away after reverting [305ee16](https://github.com/eclipse-openj9/openj9/commit/305ee169b621b3a2017bb518f5c415ee6c039ae9)?

I didn't try reverting but disable the assertion as it is irrelevant to the foreign specific code.

**Comment by babsingh** [comment]
@ChengJin01 I have opened the following issues:
- #13993
- #13995
- #13996
- #13997
- #13998
- #14001
- #14002

There are more failures to be analyzed. Will open a Github issue for them later.

**Comment by babsingh** [comment]
re #13946 (comment):
>The issue was likely introduced by the changes at #13890 in native

I reverted https://github.com/eclipse-openj9/openj9/commit/305ee169b621b3a2017bb518f5c415ee6c039ae9 and reran one of the failing tests which cause an `AssertionError` at `MemberName.vminfoIsConsistent(MemberName.java:352)`. The `AssertionError` happens even after reverting https://github.com/eclipse-openj9/openj9/commit/305ee169b621b3a2017bb518f5c415ee6c039ae9 from #13890. New OJDK MH changes are probably   the source of the `AssertionError`. We will need to update the OJDK MH support in OpenJ9 to resolve the `AssertionError`.

**Comment by fengxue-IS** [comment]
The `AssertionError` is likely related to different impl of vmindex calculation between OpenJ9 and OJDK where OpenJ9's `J9JNIRef` would have vtable offset for invokespecial in special cases.
I've build https://github.com/fengxue-IS/openj9/commit/ad7aca8c7344b868d11b876ad9fa9e0150483a58 to see if we move the invocation dispatch check early will fix this issue.

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/13946#issuecomment-978133376:

> There are more failures to be analyzed. Will open a Github issue for them later.

### Other failures
- https://github.com/eclipse-openj9/openj9/issues/14082
- https://github.com/eclipse-openj9/openj9/issues/14086
- https://github.com/eclipse-openj9/openj9/issues/14088
- https://github.com/eclipse-openj9/openj9/issues/14089
- https://github.com/eclipse-openj9/openj9/issues/14090
- https://github.com/eclipse-openj9/openj9/issues/14079
- https://github.com/eclipse-openj9/openj9/issues/14080
- https://github.com/eclipse-openj9/openj9/issues/14084
- https://github.com/eclipse-openj9/openj9/issues/14091
- https://github.com/eclipse-openj9/openj9/issues/14092
- https://github.com/eclipse-openj9/openj9/issues/14093
- https://github.com/eclipse-openj9/openj9/issues/14094
- https://github.com/eclipse-openj9/openj9/issues/14095

Out of the 13 unique failures, 5 of them are no longer seen. https://github.com/adoptium/aqa-tests/pull/3164 will exclude the tests related to the remaining 8 unique failures.

**Comment by pshipton** [comment]
We might want to wait until we get https://github.com/eclipse-openj9/openj9/pull/14077 merged so we can run the latest OpenJDK code again, and get an updated list of failures.

**Comment by pshipton** [comment]
We've updated to the latest OpenJDK and the following failures remain
```
java/foreign/TestUpcall.java#async.TestUpcall_async
java/foreign/TestUpcall.java#async.TestUpcall_async
java/foreign/TestUpcall.java#no_scope.TestUpcall_no_scope
java/foreign/TestUpcall.java#no_scope.TestUpcall_no_scope
java/foreign/TestUpcall.java#scope.TestUpcall_scope
java/foreign/TestUpcall.java#scope.TestUpcall_scope
java/foreign/upcalldeopt/TestUpcallDeopt.java.TestUpcallDeopt
java/foreign/upcalldeopt/TestUpcallDeopt.java.TestUpcallDeopt
java/lang/Object/FinalizationOption.java.FinalizationOption
java/lang/Object/FinalizationOption.java.FinalizationOption
java/lang/Object/InvalidFinalizationOption.java.InvalidFinalizationOption
java/lang/Object/InvalidFinalizationOption.java.InvalidFinalizationOption
java/lang/ClassLoader/deadlock/DelegateTest.java.DelegateTest
java/lang/ClassLoader/deadlock/DelegateTest.java.DelegateTest
java/lang/StackTraceElement/WithClassLoaderName.java.WithClassLoaderName
java/lang/StackTraceElement/WithClassLoaderName.java.WithClassLoaderName
java/util/logging/Logger/getLogger/TestInferCaller.java.TestInferCaller
java/util/logging/Logger/getLogger/TestInferCaller.java.TestInferCaller
```

@JasonFengJ9 opened https://github.com/eclipse-openj9/openj9/issues/14131 for the finalization failures, https://github.com/eclipse-openj9/openj9/issues/14133 for DelegateTest, https://github.com/eclipse-openj9/openj9/issues/14132 for WithClassLoaderName, https://github.com/eclipse-openj9/openj9/issues/14136 for TestInferCaller.

We should get all of these tests excluded until they can be fixed so we can run green and use sanity.openjdk in the promotion criteria for accepting further OpenJDK updates.

**Comment by pshipton** [comment]
I don't yet see an issue for java/foreign/upcalldeopt/TestUpcallDeopt.java

**Comment by JasonFengJ9** [comment]
> java/foreign/upcalldeopt/TestUpcallDeopt.java

Included it at https://github.com/eclipse-openj9/openj9/issues/14134#issuecomment-991140516

**Comment by ChengJin01** [comment]
The failing FFI related test suites are new one added in the latest version of Java 18, which should be excluded as well.

**Comment by pshipton** [comment]
@ChengJin01 can you exclude the foreign failures, and @JasonFengJ9 can exclude the others.

**Comment by JasonFengJ9** [comment]
Created https://github.com/adoptium/aqa-tests/pull/3172 to exclude failures other than ` jdk_foreign`.

**Comment by pshipton** [comment]
Actually I'm reopening this as there are failures on other platforms which we still need to deal with.
See the (running) build https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/172/ which covers all platforms.
Some of the failures are excluded by https://github.com/adoptium/aqa-tests/pull/3171 now, but there are other failures which are not.

**Comment by pshipton** [comment]
AIX:
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/util/Collections/RacingCollections.java.RacingCollections
    java/util/Collections/SyncSubMutexes.java.SyncSubMutexes
    java/util/Map/Defaults.java.Defaults
    java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java.SpliteratorTraversingAndSplittingTest
    java/foreign/TestHandshake.java.TestHandshake
    java/foreign/TestHandshake.java.TestHandshake
    java/util/NavigableMap/LockStep.java.LockStep
    java/util/NavigableMap/LockStep.java.LockStep

zlinux:
    java/foreign/TestSegmentCopy.java.TestSegmentCopy
    java/foreign/TestSegmentCopy.java.TestSegmentCopy
    java/foreign/channels/TestAsyncSocketChannels.java.TestAsyncSocketChannels
    java/foreign/channels/TestAsyncSocketChannels.java.TestAsyncSocketChannels
    java/util/NavigableMap/LockStep.java.LockStep

Mac:
    java/foreign/TestSegmentCopy.java.TestSegmentCopy
    java/foreign/channels/TestAsyncSocketChannels.java.TestAsyncSocketChannels
    java/util/ResourceBundle/UTF8Properties/CodePointTest.java.CodePointTest
    java/util/ResourceBundle/UTF8Properties/CodePointTest.java.CodePointTest
    java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java.SpliteratorTraversingAndSplittingTest
    java/lang/System/MacEncoding/MacJNUEncoding.java.MacJNUEncoding
    java/lang/System/MacEncoding/MacJNUEncoding.java.MacJNUEncoding
    java/lang/System/MacEncoding/TestFileEncoding.java.TestFileEncoding
    java/lang/System/MacEncoding/TestFileEncoding.java.TestFileEncoding

Windows:
java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java.SpliteratorTraversingAndSplittingTest
java/foreign/TestHandshake.java.TestHandshake
java/foreign/TestHandshake.java.TestHandshake

**Comment by pshipton** [comment]
Another run with the latest excludes https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK18/1/

AIX:
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/lang/ProcessBuilder/Basic.java#id0.Basic_id0
    java/util/Collections/RacingCollections.java.RacingCollections
    java/util/Collections/SyncSubMutexes.java.SyncSubMutexes
    java/util/Map/Defaults.java.Defaults
    java/util/NavigableMap/LockStep.java.LockStep
    java/util/NavigableMap/LockStep.java.LockStep

plinux:
    java/util/List/SubList.java.SubList
    java/util/NavigableMap/LockStep.java.LockStep
    java/util/NavigableMap/LockStep.java.LockStep
    java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java.SpliteratorTraversingAndSplittingTest

zlinux:
jdk_lang_1 many crashes see https://github.com/eclipse-openj9/openj9/issues/14124#issuecomment-995843612

xlinux:
java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java.SpliteratorTraversingAndSplittingTest

Mac:
    java/lang/System/MacEncoding/MacJNUEncoding.java.MacJNUEncoding
    java/lang/System/MacEncoding/MacJNUEncoding.java.MacJNUEncoding
    java/lang/System/MacEncoding/TestFileEncoding.java.TestFileEncoding
    java/lang/System/MacEncoding/TestFileEncoding.java.TestFileEncoding
    java/util/ResourceBundle/UTF8Properties/CodePointTest.java.CodePointTest
    java/util/concurrent/tck/JSR166TestCase.java.JSR166TestCase

Windows:
    java/lang/StringBuilder/CharAt.java.CharAt
    java/lang/constant/MethodTypeDescTest.java.MethodTypeDescTest
    java/lang/reflect/records/IsRecordTest.java.IsRecordTest

**Comment by pshipton** [comment]
Many of the failures in the last couple of comments have cleared up. We'll handle the remaining failures with individual issues.
