### ISSUE TITLE
JDK18 builds failing on Linux platforms with no particular error

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13950]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/159/

Only the Linux platforms are failing (alinux, plinux, zlinux, xlinux).

Changes https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/d0a9f59b6...26b0e63f4a9
Guessing the problem is related to
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/2c3cce4f63cd658aeb8ff41654440d1e56c2eb56 
and/or 
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/136fb2e689bfe2e75486fcff8a7b19a25616686e

@JasonFengJ9 @keithc-ca fyi

**Comment by keithc-ca** [comment]
I noticed this locally as well (at first I thought it was due to local changes).

What's weird, though, is that the exact command that fails in the build (recorded in `make-support/failure-logs/jdk__optimize_image_exec.cmdline`) succeeds when run from the same shell where `make` was launched.

**Comment by pshipton** [comment]
The changes are related to character encoding, so maybe the encoding is different from inside make and the shell.

**Comment by keithc-ca** [comment]
I think it is `8275007: Java fails to start with null charset if LC_ALL is set to certain locales`:
```
$ jdk/bin/java -version
openjdk version "18-internal" 2022-03-15
OpenJDK Runtime Environment (build 18-internal+0-adhoc.keithc.jdk18)
Eclipse OpenJ9 VM (build main-d03f3b81e47, JRE 18 Linux amd64-64-Bit Compressed References 20211118_000000 (JIT enabled, AOT enabled)
OpenJ9   - d03f3b81e47
OMR      - f76321aa3ba
JCL      - 26b0e63f4a9 based on jdk-18+24)

$ LC_ALL=UTF-8 jdk/bin/java -version
Exception in thread "(unnamed thread)" java/lang/ExceptionInInitializerError
```

**Comment by JasonFengJ9** [comment]
Related to [JEP 400 UTF-8 by Default](https://github.com/eclipse-openj9/openj9/issues/13470).

**Comment by keithc-ca** [comment]
It seems that `String.helpers` is not initialized early enough.
```
 > java/lang/System.<clinit>()V bytecode static method
  > java/lang/System.initEncodings()V bytecode static method
   > java/lang/System.getEncoding(I)Ljava/lang/String; native static method
    > java/nio/charset/Charset.isSupported(Ljava/lang/String;)Z bytecode static method
     > java/nio/charset/Charset.lookup(Ljava/lang/String;)Ljava/nio/charset/Charset; bytecode static method
      > java/nio/charset/Charset.lookup2(Ljava/lang/String;)Ljava/nio/charset/Charset; bytecode static method
       > sun/nio/cs/StandardCharsets.charsetForName(Ljava/lang/String;)Ljava/nio/charset/Charset; bytecode method, this = 0xfff00490
        > sun/nio/cs/StandardCharsets.lookup(Ljava/lang/String;)Ljava/nio/charset/Charset; bytecode method, this = 0xfff00490
         > sun/nio/cs/StandardCharsets.canonicalize(Ljava/lang/String;)Ljava/lang/String; bytecode method, this = 0xfff00490
          > sun/util/PreHashedMap.get(Ljava/lang/Object;)Ljava/lang/Object; bytecode method, this = 0xfff008f0
           > java/lang/String.hashCode()I bytecode method, this = 0xfff00798
            > java/lang/String.hashCodeImplDecompressed([BII)I bytecode static method
             > java/lang/NullPointerException.<init>(Ljava/lang/String;)V bytecode method, this = 0xfff03ac8
```
Why aren't all the methods in `JITHelpers` `static`?

**Comment by gacholio** [comment]
> Why aren't all the methods in `JITHelpers` `static`?

For the same reason as Unsafe - the security is restricting access to the singleton.
