### ISSUE TITLE
testJITServer Assertion failed JITServerHelpers.cpp:322 VMState: 0x0005ffff

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#13967]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Nightly_testList_0/152
testJITServer_1
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Nightly_testList_0/152/functional_test_output.tar.gz

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/152
testJITServer_0
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/152/functional_test_output.tar.gz

Maybe there would be more failures, but fyi https://github.com/eclipse-openj9/openj9/issues/13966

```
//// Assertion failed at /home/jenkins/workspace/Build_JDK8_ppc64le_linux_Nightly/openj9/runtime/compiler/control/JITServerHelpers.cpp:322: ctx._utf8SectionSize == end - ctx._utf8SectionStart
//// VMState: 0x0005ffff
//// 	Missed strings in ROMClass java/lang/Class UTF8 section: 21316 != 21392
//// compiling sun/reflect/Reflection.getCallerClass()Ljava/lang/Class; at level: hot
```

@mpirvu

**Comment by AlexeyKhrabrov** [comment]
This is likely due to #13199 which introduced new UTF8 strings in ROMClasses without visiting them in the ROMClass walk. Any changes to the ROMClass format need to go through JITServer tests to make sure they don't break ROMClass serialization.

**Comment by mpirvu** [comment]
@ChengJin01 would you be able to implement the suggestion from @AlexeyKhrabrov to fix this issue? Thanks

**Comment by ChengJin01** [comment]
I already created changes at https://github.com/ChengJin01/openj9/commit/0310aeea5aabc78baf26eb41f3ba60a57854ac83 and need to launch personal builds to see how it goes with the JITServer tests.

**Comment by AlexeyKhrabrov** [comment]
https://github.com/ChengJin01/openj9/commit/0310aeea5aabc78baf26eb41f3ba60a57854ac83 looks correct and should fix the issue.
