### ISSUE TITLE
Eliminate VM_isString1 messages from JITServer code

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#13988]
A `VM_isString1` message is sent from the implementation of 
```
bool
TR_J9ServerVM::isString(TR_OpaqueClassBlock * clazz)
   {
   JITServer::ServerStream *stream = _compInfoPT->getMethodBeingCompiled()->_stream;
   stream->write(JITServer::MessageType::VM_isString1, clazz);
   return std::get<0>(stream->read<bool>());
   }
```
The non-jitserver implementation is:
```
bool
TR_J9VMBase::isString(TR_OpaqueClassBlock *clazz)
   {
   return (J9Class*)clazz == J9VMJAVALANGSTRING(jitConfig->javaVM);
   }
```
We can avoid sending a message if we cache the value for  `J9VMJAVALANGSTRING(jitConfig->javaVM)` in `ClientSessionData::VMInfo` 
This cached value can change only in HCR extended mode when a class redefinition occurs. Thus, we may want to use NULL as an indication that the value is not available, and fetch the desired value with a dedicated message.

**Comment by mpirvu** [comment]
@cjjdespres Could you please implement this? Thanks

**Comment by cjjdespres** [comment]
> This cached value can change only in HCR extended mode when a class redefinition occurs. Thus, we may want to use NULL as an indication that the value is not available, and fetch the desired value with a dedicated message.

Could you clarify this? I'm not sure when exactly the value will not be available. Do you mean that the cached value of `J9VMJAVALANGSTRING(vmInfo->javaVM)` might be `NULL`, and that we would need to fall back on the currently-existing code in `isString`?

**Comment by mpirvu** [comment]
I was saying that the cached value can have a value of NULL, indicating that the server must go and fetch the correct value from the client.
`J9VMJAVALANGSTRING(vmInfo->javaVM)` cannot be NULL at the client, except in the very early stages of the JVM, but we won't have any compilations so early. Even if  `J9VMJAVALANGSTRING(vmInfo->javaVM)` is NULL at the client, that means the server will cache a NULL value and next time will have to ask the server again (according to the policy from my first sentence).

**Comment by cjjdespres** [comment]
I see. I think I'm confused because it seems like `getOrCacheVMInfo` is always going to fetch a full `vmInfo` from the client, and that's always going to have a non-null `J9VMJAVALANGSTRING(vmInfo->javaVM)` value in it, at least by the time those compilations start happening, as you say.

**Comment by cjjdespres** [comment]
I've been assuming that it would be set like
```
         vmInfo._JavaStringObject = (TR_OpaqueClassBlock*)J9VMJAVALANGSTRING(vmThread->javaVM);
```
at the client, but maybe you had something more in mind?

**Comment by cjjdespres** [comment]
Or do you mean that it may in fact have an early cached NULL, and so we'll have to send a new message to update the cached `vmInfo` with an actual value?

**Comment by mpirvu** [comment]
What I think it should happen at the server is,
- call `getOrCacheVMInfo()`
- if the field corresponding to J9VMJAVALANGSTRING(vmInfo->javaVM) is NULL, send the existing `VM_isString` message to client and use that.
- if the value returned by `VM_isString` message is not NULL, cache it in VMInfo to avoid a new message next time

Moreover, when we enter the extended HCR mode, the corresponding J9VMJAVALANGSTRING(vmInfo->javaVM) field cached at the server needs to be set to NULL, because the old value may be stale now
