### ISSUE TITLE
[JDK18] InternalError: Caller is not annotated as @CallerSensitive

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#13998]
### OpenJDK Tests

```
TEST: jdk/internal/reflect/Reflection/GetCallerClassTest.java#id0
TEST: jdk/internal/reflect/Reflection/GetCallerClassTest.java#id2
TEST: jdk/internal/reflect/Reflection/GetCallerClassTest.java#id1
TEST: jdk/internal/reflect/Reflection/GetCallerClassTest.java#id3
```

### Error

```
[2021-11-17T18:35:06.056Z] testMissingCallerSensitiveAnnotation...
[2021-11-17T18:35:06.056Z] STDERR:
[2021-11-17T18:35:06.056Z] java.lang.InternalError: Caller is not annotated as @sun.reflect.CallerSensitive.
[2021-11-17T18:35:06.056Z]      at java.base/jdk.internal.reflect.Reflection.getCallerClass(Native Method)
[2021-11-17T18:35:06.056Z]      at boot.GetCallerClass.missingCallerSensitiveAnnotation(GetCallerClass.java:35)
[2021-11-17T18:35:06.056Z]      at GetCallerClassTest.testMissingCallerSensitiveAnnotation(GetCallerClassTest.java:118)
[2021-11-17T18:35:06.056Z]      at GetCallerClassTest.main(GetCallerClassTest.java:89)
[2021-11-17T18:35:06.056Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T18:35:06.056Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
[2021-11-17T18:35:06.056Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
[2021-11-17T18:35:06.056Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2021-11-17T18:35:06.056Z]      at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-17T18:35:06.056Z]      at java.base/java.lang.Thread.run(Thread.java:884)
```

Related: https://github.com/eclipse-openj9/openj9/issues/13946

**Comment by babsingh** [comment]
**Test code:** [openjdk-next/GetCallerClassTest.java#L121](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/a046575f4dceeba9a98309c8c67167a4e315830f/test/jdk/jdk/internal/reflect/Reflection/GetCallerClassTest.java#L121)

Test code expects the `InternalError` message to be `CallerSensitive annotation expected`.

OpenJ9's `InternalError` has the following message: `Caller is not annotated as @sun.reflect.CallerSensitive.`

https://github.com/eclipse-openj9/openj9/blob/4d741e5d401d7cf5f091d7f35f69fae8ade6ee92/runtime/nls/j9vm/j9vm.nls#L1322-L1322

This failure can be resolved if the `InternalError` message mismatch between OpenJ9 and test code is fixed.

**Three potential solutions:**
1) Update OpenJDK test code
2) Update OpenJ9 trace point message
3) Similar testing exists in OpenJ9: [openj9/GetCallerClassTests.java](https://github.com/eclipse-openj9/openj9/blob/master/test/functional/cmdline_options_testresources/src_90/com/ibm/j9/getcallerclass/GetCallerClassTests.java). So, we keep the failing OpenJDK tests excluded, and rely upon similar OpenJ9 testing.

@pshipton We have opted for `Solution 3` for similar cases in the past. Do we want to take the same path for this issue?

**Comment by pshipton** [comment]
Although we don't want the patches, the safest approach is to update the OpenJDK test code. I'm concerned we might miss something otherwise with all the changes that are occurring. Although it would be a better solution, I'm concerned copying the OpenJDK message is a license violation.

**Comment by gacholio** [comment]
All of the tests which check for an exact exception message match are invalid. We long ago decided against blindly copying OpenJDK messages. Patching 100s of tests seems unreasonable.

**Comment by babsingh** [comment]
I agree that we should not update OpenJ9 code. I don't think the test in question is invalid.

I also agree that we may miss something critical if we exclude the OpenJDK test.

In this case, we can update the OpenJDK test with a regex so that it accepts both OpenJ9 and OJDK messages. We will need to only update two locations:
1. [openjdk-next...GetCallerClassTest.java#L121](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/a046575f4dceeba9a98309c8c67167a4e315830f/test/jdk/jdk/internal/reflect/Reflection/GetCallerClassTest.java#L121)
2. [openjdk-next...GetCallerClassTest.java#L136](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/a046575f4dceeba9a98309c8c67167a4e315830f/test/jdk/jdk/internal/reflect/Reflection/GetCallerClassTest.java#L136)

@pshipton @gacholio For resolving this issue, shall we proceed with updating the OpenJDK test?

**Comment by gacholio** [comment]
If you mean updating it in the OpenJDK repo, yes. If you mean a local patch, then no I would not approve that.

**Comment by pshipton** [comment]
This is updating in the OpenJDK repo, which I agree with.

**Comment by gacholio** [comment]
It looks like an IBM repo, which is not the OpenJDK repo, so we'll be maintaining patches. This is foolish, but not my problem, I suppose.

**Comment by babsingh** [comment]
In the future, we can encounter conflicts in the extensions repo for our patches. The chances of the test code to be updated are pretty low. So, these patches should have a low risk for a potential conflict.

**Comment by pshipton** [comment]
It seems more foolish to allow a bug to occur because we didn't run the tests and something was missed. While it would be nice to contribute the test fix upstream, it seems unlikely to be accepted. Although we could try.
