### ISSUE TITLE
Request a new label - triage required

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13990]
## Label proposed

triage required

## Target issues

The `test failures` not assigned a component yet.
`userRaised` or any other issues requiring triage to determine the component(s) they belong to (and for further investigation).

This label is needed to separate the issue raising and triage process. It is not alway practical to perform these two tasks together. The triage should be prioritized according to the issue nature and resource availability. 

Assuming the component owner continue the issue investigation after triage is done and the label in question is removed.

fyi @pshipton

**Comment by pshipton** [comment]
`triageRequired` label added.
