### ISSUE TITLE
JDK18 build breakage due to JDK-8275063: Implementation of Foreign Function & Memory API (Second incubator)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14013]
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/f95d3e58d021bfe23848aac5747ad0c30354c5bd removed `jdk.incubator.foreign.CLinker.TypeKind` which is referenced by OpenJ9 https://github.com/eclipse-openj9/openj9/blob/bf11aca8a436c53cd22df7e19c2614f6f442e6b2/jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java#L42-L43

This breaks JDK18 build.
```
=== Output from failing command(s) repeated here ===
* For target jdk_modules_jdk.incubator.foreign__the.jdk.incubator.foreign_batch:
/Users/ivm/ext-merge-conflict/jdk-1125/merge_tmp-test-build/build/macosx-x86_64-server-release/support/j9jcl/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java:41: error: cannot find symbol
import jdk.incubator.foreign.CLinker.TypeKind;
                                    ^
  symbol:   class TypeKind
  location: interface CLinker
/Users/ivm/ext-merge-conflict/jdk-1125/merge_tmp-test-build/build/macosx-x86_64-server-release/support/j9jcl/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java:42: error: cannot find symbol
import static jdk.incubator.foreign.CLinker.TypeKind.*;
                                           ^
  symbol:   class TypeKind
  location: interface CLinker
/Users/ivm/ext-merge-conflict/jdk-1125/merge_tmp-test-build/build/macosx-x86_64-server-release/support/j9jcl/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java:531: error: cannot find symbol
		TypeKind kind = (TypeKind)targetLayout.attribute(TypeKind.ATTR_NAME)
		^
  symbol:   class TypeKind
  location: class ProgrammableInvoker
   ... (rest of output omitted)
```

fyi @ChengJin01 @tajila

**Comment by ChengJin01** [comment]
These are the latest API changes in JDK18 without any document  (not yet updated). I will grab the temp branch from @JasonFengJ9 to investigate what really happened to our implementation and need to need to figure out how to fit with JDK17 and JDK18 in such case.

**Comment by keithc-ca** [comment]
I think the effects are limited to the implementation of `ProgrammableInvoker.validateValueLayoutKind()`.

**Comment by ChengJin01** [comment]
> I think the effects are limited to the implementation of `ProgrammableInvoker.validateValueLayoutKind()`.

More than that, the latest API changes & internal implementation affects all type related code in java & native as to how to deal with the types in our code (e.g. `C_BOOL` firstly introduced in src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/PlatformLayouts.java)
```
        public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
```
