### ISSUE TITLE
Pull Request child jobs not being reflected in PRs

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14024]
For the past day or two or three, the child jobs started by Pull Requests are not being shown in the PRs. Look at the PR for any recent PR build. For example https://github.com/eclipse-openj9/openj9/pull/14023, see in the Details the PR build is shown but not the win32 build job. See it in action in https://github.com/eclipse-openj9/openj9/pull/14017 if you look soon.

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Monday night seems to be the last nightly it worked on. The credential is still there
https://github.com/eclipse-openj9/openj9/blob/323cb8e43e0695fbbb4d32103b34e95fc7bdbf62/buildenv/jenkins/variables/defaults.yml#L97
https://openj9-jenkins.osuosl.org/credentials/store/system/domain/_/credential/github-bot/

I thought maybe a side effect of what I changed here
https://github.com/eclipse-openj9/openj9-docs/pull/864/
But that was done on the 19th.

ok def a side effect of deleting `github-bot-token`. Added back and set global config Github API cred to it.
Working now.
https://openj9-jenkins.osuosl.org/credentials/store/system/domain/_/credential/05d2fa2a-55f1-4203-9fd0-7b37ae4b8851/
