### ISSUE TITLE
SEGV with "-Xjit:verbose,help" option

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#14021]
Running java with an option `-Xjit:verbose,help` causes a SEGV in `TR_Debug::dumpOptions()`.
It is reproducible on Windows, Linux, and macOS.

`entry->msg` is NULL at https://github.com/eclipse/omr/blob/eb9cf8525b7cf8be417c68a880826801acd4080e/compiler/ras/OptionsDebug.cpp#L474

**Comment by knn-k** [comment]
I used the following version:

> openjdk version "11.0.13" 2021-10-19
> IBM Semeru Runtime Open Edition 11.0.13.0 (build 11.0.13+8)
> Eclipse OpenJ9 VM 11.0.13.0 (build openj9-0.29.0, JRE 11 Linux amd64-64-Bit Compressed References 20211022_282 (JIT enabled, AOT enabled)
> OpenJ9   - e1e72c497
> OMR      - 299b6a2d2
> JCL      - 2d83aa3b76 based on jdk-11.0.13+8)

**Comment by BradleyWood** [comment]
Looks like the following options will fail with "-Xjit:verbose" : noregmap, regmap, help

Will also fail with -Xaot

https://github.com/eclipse/omr/blob/6a78dd52f16889ac024381334d912c247afdcf69/compiler/control/OMROptions.cpp#L812-L812

**Comment by knn-k** [comment]
https://github.com/eclipse/omr/pull/6829 fixed this.  Closing.
