### ISSUE TITLE
IdleMicrobenchmark_J9_0_FAILED - sed: -e expression #1, char 1: unknown command: `,'

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14032]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_sanity.perf_x86-64_linux/850/`(`cent7x64-1-10`):
```
java version "11.0.14" 2022-01-18
IBM Semeru Runtime Certified Edition 11.0.14+4 (build 11.0.14+4)
Eclipse OpenJ9 VM 11.0.14+4 (build master-323cb8e43, JRE 11 Linux amd64-64-Bit Compressed References 20211127_233 (JIT enabled, AOT enabled)
OpenJ9   - 323cb8e43
OMR      - eb9cf8525
JCL      - 1077e67ee8 based on jdk-11.0.14+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=IdleMicrobenchmark_J9_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-64_linux&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F233%2Fibm-semeru-certified-jre_x64_linux_JDK11U_2021-11-27-02-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F233%2Fibm-semeru-certified-testimage_x64_linux_JDK11U_2021-11-27-02-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F233%2Fibm-semeru-certified-debugimage_x64_linux_JDK11U_2021-11-27-02-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F233%2Fibm-semeru-certified-jdk_x64_linux_JDK11U_2021-11-27-02-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=3&amp;OPENJDK_SHA=&amp;BUILD_LIST=perf&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-11-27T03:06:30.977Z] variation: -XX:+IdleTuningGcOnIdle -Xtune:virtualized -XX:IdleTuningMinIdleWaitTime=120 -Xmx1024m
[2021-11-27T03:06:30.977Z] JVM_OPTIONS:  -XX:+IdleTuningGcOnIdle -Xtune:virtualized -XX:IdleTuningMinIdleWaitTime=120 -Xmx1024m 

[2021-11-27T03:06:30.981Z] active start: 
[2021-11-27T03:06:30.981Z] active end: 
[2021-11-27T03:06:30.981Z] idle start: 
[2021-11-27T03:06:30.981Z] idle end: 
[2021-11-27T03:06:30.981Z] sed: -e expression #1, char 1: unknown command: `,'
[2021-11-27T03:06:30.981Z] sed: -e expression #1, char 1: unknown command: `,'
[2021-11-27T03:06:30.981Z] ACTIVE MAX: 0
[2021-11-27T03:06:30.981Z] IDLE MIN: 99999999999
[2021-11-27T03:06:30.981Z] TEST FAILED
[2021-11-27T03:06:30.981Z] IDLE Memory is more by 99999999999 MB
[2021-11-27T03:06:30.981Z] 
[2021-11-27T03:06:30.981Z] IdleMicrobenchmark_J9_0_FAILED
```

**Comment by pshipton** [comment]
@llxia

**Comment by llxia** [comment]
Reran the test in [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/19725/console) on another machine and the test passed.

**Comment by llxia** [comment]
I have not seen any failure for the past 11 days and the test passed on [cent7x64-1-10](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.perf_x86-64_linux/856/) on Dec 3rd.

I will close the issue for now. Please reopen if the problem occurs.
