### ISSUE TITLE
JITServer mismatch between message types and message names

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#14040]
`MessageTypes.hpp` includes definitions of all the messages JITServer can send/receive, but also the names for these messages.
Recent SDKs have introduced a mismatch between definitions and names due to the `J9VM_OPT_METHOD_HANDLE` define:
```
enum MessageType : uint16_t
   {
   compilationCode, // Send the compiled code back to the client
   ... 
#if defined(J9VM_OPT_METHOD_HANDLE)
   ResolvedMethod_varHandleMethodTypeTableEntryAddress,
   ResolvedMethod_isUnresolvedVarHandleMethodTypeTableEntry,
#endif /* defined(J9VM_OPT_METHOD_HANDLE) */
   ...
   MessageType_MAXTYPE
   };

static const char *messageNames[] =
   {
   "compilationCode",
   ...
#if defined(J9VM_OPT_METHOD_HANDLE)
   "ResolvedMethod_varHandleMethodTypeTableEntryAddress",
   "ResolvedMethod_isUnresolvedVarHandleMethodTypeTableEntry",
#endif /* defined(J9VM_OPT_METHOD_HANDLE) */
   ...
   };

   static_assert(sizeof(messageNames) / sizeof(messageNames[0]) == MessageType_MAXTYPE,
                 "Invalid number of message type names: possibly missing a name for a newly added message");
```
From the behavior it appears that `J9VM_OPT_METHOD_HANDLE` is defined when looking at the definitions, but undefined when looking at the names. The static_assert at the end does not fire to indicate a mismatch.

**Comment by mpirvu** [comment]
I factored-out the array of message names into a separate MessageTypes.cpp files, but this didn't fix the issue. It appears that the `J9VM_OPT_METHOD_HANDLE` definition is not seen in all the compilation units, which can lead to problems down the road.

Taking the `#if defined(J9VM_OPT_METHOD_HANDLE)` from both the MessageTypes.hpp and MessageTypes.cpp solves the JITServer issue at hand (obviously), but there might be other problems as well.

**Comment by mpirvu** [comment]
@keithc-ca The fact that `J9VM_OPT_METHOD_HANDLE` appears as defined in some compilation units but not in others seems like a build problem to me. Can you guess what could have caused this issue? It started to happen sometime this month.

**Comment by keithc-ca** [comment]
I'll have a look.

**Comment by keithc-ca** [comment]
What version(s) are you trying to build? With which configure options?

**Comment by keithc-ca** [comment]
My first suggestion is that `MessageTypes.hpp` should be including `j9cfg.h` so that `J9VM_OPT_METHOD_HANDLE` is guaranteed to be properly defined (or not).

**Comment by mpirvu** [comment]
I am building Java11 and only use `--enable-jitserver` for the configure step.
I will try including `j9cfg.h`, though we may need to check all the files for possibly missing to include `j9cfg.h`

**Comment by mpirvu** [comment]
Including `j9cfg.h` solves the issue. I'll create a PR soon. Thanks @keithc-ca !
