### ISSUE TITLE
JEP 421: Deprecate Finalization for Removal

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#14049]
See https://openjdk.java.net/jeps/421

```
We propose to:

    Add a command-line option to disable finalization, so that no finalizers are ever scheduled by the GC to run, and
    Deprecate all finalizers, and finalization-related methods, in the standard Java API.

```

**Comment by tajila** [comment]
FYI @dmitripivkine

**Comment by tajila** [comment]
The option will be `--finalization=[enabled|disabled]` it will be enabled by default

**Comment by tajila** [comment]
Its likely we will fail tests once this gets in the jdk18 repo due to the fact that we do not yet recognize the option

**Comment by tajila** [comment]
@JasonFengJ9 Can you take a look at this once it lands

**Comment by pshipton** [comment]
> Its likely we will fail tests once this gets in the jdk18 repo due to the fact that we do not yet recognize the option

It depends how `--finalization` is processed. If it's done by the launcher and turned into a system property, then it may just work.

**Comment by pshipton** [comment]
Well we likely still need to add something to the Object.finalize() method.

**Comment by pshipton** [comment]
I see JVM_IsFinalizationEnabled() added.

**Comment by JasonFengJ9** [comment]
> I see JVM_IsFinalizationEnabled() added.

Okay, will add it.

**Comment by keithc-ca** [comment]
See also #14114.

**Comment by tajila** [comment]
Can this be closed @JasonFengJ9

**Comment by JasonFengJ9** [comment]
I am not aware any outstanding task required by this JEP.

Closing..
