### ISSUE TITLE
Eden space contraction problem

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse-openj9/openj9#14076]
Java -version output
--------------------

```
openjdk version "17.0.1-internal" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1-internal+0-adhoc.jenkins.buildjdk17x86-64windowsnightly)
Eclipse OpenJ9 VM (build master-5afc033b29e, JRE 17 Windows 7 amd64-64-Bit Compressed References 20211205_109 (JIT enabled, AOT enabled)
OpenJ9   - 5afc033b29e
OMR      - 5e9418d
JCL      - 37e7add6580 based on jdk-17.0.1+12)
```

Summary of problem
------------------
Minecraft allocate much short-live objects in launch stage. It could cause balanced gc expand eden size too much. But heap memory is not enough. So It touch off global garbage collect(full gc). Global garbage collect do not contract eden space. Eden space still too big and start more full gc for getting more free space.

Minecraft required java 17.

Diagnostic files
----------------
gc log
[verbosegc.20211207.001221.3792.zip](https://github.com/eclipse-openj9/openj9/files/7662175/verbosegc.20211207.001221.3792.zip)

**Comment by pshipton** [comment]
@dmitripivkine @amicic

**Comment by amicic** [comment]
Observations are mostly correct. We generally do try to rebalance eden and non-eden after global cycles, but it's not so clear why we don't do it here.

Please try to generate trace logs as well: -Xtrace:maximal=j9mm{resize},maximal=j9mm{kickoff},output="trace.log"

Meanwhile you can limit Eden expansion with something like -Xmnx500M (or less)

**Comment by 1a2s3d4f1** [comment]
Trace log:https://mega.nz/folder/TIswRIyR#i2FKXtmnNh0WlcU-HCiXng
Sometime,global garbage collect can change eden size.
[verbosegc.20211207.235349.3876.zip](https://github.com/eclipse-openj9/openj9/files/7673629/verbosegc.20211207.235349.3876.zip)

**Comment by amicic** [comment]
We put a change (https://github.com/eclipse-openj9/openj9/pull/14403) that might resolve this issue. It might not directly resolve the root cause of the problem, but it might prevent the problem (too much Eden expansion) to happen at the first place.
You're welcome to try a recent nightly build.
At some point I'll have another look at it, anyway.

**Comment by 1a2s3d4f1** [comment]
@amicic  This problem (Too much Eden expansion) is not happen on minecraft client. It tested in virtual enviroment(Use VirtualBox).
