### ISSUE TITLE
Request for an out-of-cycle release for AArch64 Linux

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#14099]
The following is a request for the OpenJ9 community to produce an out-of-cycle release to fix a problem found in the 0.29.0 release.

A JIT compiler problem was discovered in the 0.29.0 release that affects AArch64 Linux exclusively.  The problem has been subsequently fixed in the master branch (PR #13927), the 0.30.0 branch (by virtue of a code split), and the 0.29.1 branch (PR #13959).

The problem manifests itself as a crash at runtime.  It is easy to reproduce reliably with many common Java applications by first creating a shared classes cache with AOT compiled methods, and then launching a second JVM that uses that shared classes cache but with a smaller heap size (-Xms/-Xmx).  The error occurs because the AArch64 JIT code generator wrongly considers the heap size to be constant when generating inlined write barriers in AOT compiled methods.  The fix itself is very safe and retrieves the heap size from the J9VMThread struct instead.

A consumer of OpenJ9 has built and deployed an OpenJ9 Java 11 JDK based on the 0.29.0 release.  Because they run Java in an environment with a constrained toolchain, they build their own JDK from OpenJ9 source directly.  They do not use the IBM Semeru binaries except to ensure the OpenJ9 test suite passes when run on the same source release they are building.  Furthermore, their builds are based on source pulled directly from OpenJ9 repos and they do not have a means of maintaining patches or special builds.

The problem was discovered in a testing environment that mimics the deployment scenario for this application.  It was not discovered during any of the release testing at OpenJ9 because such a test scenario does not exist.  Independently, work has begun to produce such a test that will be contributed to OpenJ9 when it is ready.

The problem was found late during deployment testing after already extensive product testing had been completed by the consumer using the 0.29.0 release.  The January 18, 2022 GA of the 0.30.0 release is not an option for them due to the timing of their product delivery plans.

The problem can be worked around by disabling inlined write barriers.  However, doing so incurs an unacceptable performance penalty.  It is also not possible to ensure the heap size between different JVM invocations stays constant.

Will the OpenJ9 community consider producing a 0.29.0.1 release that includes this fix for AArch64 Linux JDK 11?

Thank you.

**Comment by 0xdaryl** [comment]
Given the apparent urgency of this request, perhaps a topic for discussion at the Dec 7 community call.   @pshipton @DanHeidinga @mstoodle

**Comment by pshipton** [comment]
This sets a bad precedent, my vote is no as it opens the door to everyone requesting a new point release with their particular favourite fix. How do we decide who gets one and who doesn't, do we create one for anyone who asks?

Other possible resolutions include:
1) use 0.29.1 which has few changes from 0.29.0 and is already tagged and ready to build
2) the consumer can easily create their own "release" in a fork or clone by starting with 0.29.0 and cherry picking the fix.

For information, I'm providing the list of changes between 0.29.0 and 0.29.1, and note it contains other fixes which may impact the consumer.

OpenJ9:
7d055dfcb7 (0.29.1) j9gc_createJavaLangString() must use Unicode length for Unicode strings Peter Shipton #14046
9a13b0bc7e (0.29.1) AArch64: Load heap size from vmstruct on AOT compilation KONNO Kazuhiro #13959
d9ff2ac6db (0.29.1) Use the dot naming convention in exception stack traces Tobi Ajila #13888
cea999b7ad Reduce ClientStream::INCOMPATIBILITY_COUNT_LIMIT to 1 Marius Pirvu #13845
5458d5ba23 Modify JITServerTest to use a new port for each subtest Dmitry Ten #13843
855de83f9b (0.29.1) Fix unknown class name in stacktraces Tobi Ajila #13768
7786a44775 (0.29.1) Fix potential memory leaks Graham Chapman #13769
854d449f85 (0.29.1) Re-enable disabled tests in jsr292_JitCount0 Nazim Bhuiyan #13787
022a7ba918 (0.29.1) Fix the race condition timing hole for classPathEntries and cpEntryCount Hang Shao #13771
ed73caf9a7 (v0.29.1-release) JVMTI trigger VMStart event according to can_generate_early_vmstart Jason Feng #13747
e4860a638a (0.29.1) Capture the error with outer class in the InnerClasses Attribute Cheng Jin #13736
99e727d2ab (0.29.1) Throw IllegalAccessError (IAE): Lookup.findVirtual Peter Shipton #13738
cf3bc2d97e (0.29.1) Update 0.29 release notes with missing content Peter Shipton #13733
e3bf60057a (0.29.1) Fix handling of interface methods in JIT linkToVirtual() Devin Papineau #13729

OMR:
e30892e2b (0.29.1) Prevent OSR transitions from failed guards Nazim Bhuiyan eclipse/omr#130
3f2734d26 (0.29.1) Avoid combining a regular type bound with a ClassObject location in VP Devin Papineau eclipse/omr#129
0c0df365b (0.29.1) Define TR_jitLookupDynamic[Public]InterfaceMethod JIT helpers Devin Papineau eclipse/omr#128

**Comment by DanHeidinga** [comment]
This was discussed on today's OpenJ9 community call and the outcome of that discussion is that the community isn't ready to commit to a 0.29.0.1 release - we can't contain the release processes, testing, and triage to support an extra release at this time.

> A JIT compiler problem was discovered in the 0.29.0 release that affects AArch64 Linux exclusively. The problem has been subsequently fixed in the master branch (PR #13927), the 0.30.0 branch (by virtue of a code split), and the 0.29.1 branch (PR #13959).

As demonstrated by the fixes inclusion in the upcoming releases, we do strongly believe that this fix is release quality.  We're making this statement to indicate that OpenJ9 builders should feel comfortable backporting this fix to their release branches if they need them for their users.

**Comment by DanHeidinga** [comment]
Closing this as we've determined not to do the release.  See above comments for rationale and @pshipton's suggestion

**Comment by knn-k** [comment]
Thank you for the discussion in the community.
