### ISSUE TITLE
Create the jdk18 repo

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14127]
OpenJDK is created https://github.com/openjdk/jdk18

@AdamBrousseau @JasonFengJ9

**Comment by pshipton** [comment]
It appears to me that the ibmruntimes/jdk repo is a little behind the branch point for jdk18, so I think all we need to do is copy the repo to jdk18 and then update it afterwards to get the later jdk18 changes. To keep the jdk repo in that state I've disabled the merge job that accepts new changes. We can re-enable after we make the copy for jdk18.

Before we copy for jdk18 I'm going to promote the openj9-staging branch, but should happen quite soon.

**Comment by pshipton** [comment]
openj9-staging is promoted now.

**Comment by JasonFengJ9** [comment]
> To keep the jdk repo in that state I've disabled the merge job that accepts new changes. We can re-enable after we make the copy for jdk18.

Agreed. So IBM JDK18 extension repo won't have head stream update after OpenJDK jdk18 creation.

**Comment by AdamBrousseau** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk18
Please take a look. I only pushed the 3 branches.

**Comment by pshipton** [comment]
Looks good to me. @JasonFengJ9 can you pls enable jdk18 staging updates to this repo.

**Comment by JasonFengJ9** [comment]
Extension repo `JDK 18` & `Next` have been updated for `master`/`openj9-staging` branches.
@pshipton please launch abuild for `openj9` update.

**Comment by pshipton** [comment]
> please launch abuild for openj9 update.

It's not worth it, all the changed is the tag. We'll just wait for the next tagged version.
