### ISSUE TITLE
jextract/jpackcore missing from JRE

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse-openj9/openj9#14126]
While trying to assist a user of the Semeru jre we discovered that the jextract/jpackcore utility is not included in the distribution. I downloaded the latest Java11 jre and sdk from https://developer.ibm.com/languages/java/semeru-runtimes/downloads/ and confirmed that the utilities are there in the sdk but not in the jre. Since service relies on the user being able to run this utility to collect the full set of crash data it's a major problem to not have it in the JRE. Please consider adding it.

**Comment by pshipton** [comment]
It means including the openj9.dtfj module. It shouldn't be a big change to add it to the JRE, although it is quite a big module (7.4MB). We should investigate splitting it up in the future if feasible. There is an older issue that can cover this https://github.com/eclipse-openj9/openj9/issues/775.

**Comment by pshipton** [comment]
jdk8 already contains jpackcore in the JRE. I've created PRs to add it to the other versions.

**Comment by pshipton** [comment]
Opened PRs to get these changes into the 0.30 release. This is complete.

**Comment by JamesKingdon** [comment]
Wow, that was fast! Many thanks @pshipton , much appreciated.

**Comment by pshipton** [comment]
Easy change, thanks to @keithc-ca as well for reviewing and merging.
