### ISSUE TITLE
JDK18 java/util/logging/Logger/getLogger/TestInferCaller.java - RuntimeException: Bad class name: expected: TestInferCaller actual: java.lang.reflect.Method

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14136]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Personal/133/consoleFull`:
```
17:51:27  openjdk version "18-internal" 2022-03-22
17:51:27  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDKnextx86-64linuxPersonal)
17:51:27  Eclipse OpenJ9 VM (build master-9f6e55d3a25, JRE 18 Linux amd64-64-Bit Compressed References 20211209_920 (JIT enabled, AOT enabled)
17:51:27  OpenJ9   - 9f6e55d3a25
17:51:27  OMR      - ff2e42cc3e3
17:51:27  JCL      - 742164f41cc based on jdk-18+26)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2FOpenJ9-JDKnext-x86-64_linux-20211209-142128.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=9f6e55d3a25a6da74a76fd2490cc7d84f6296ce6&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.os.cent.6%26%26%21sw.os.rhel.6&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
19:24:55  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
19:24:55  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

19:36:02  --------------------------------------------------
19:36:02  TEST: java/util/logging/Logger/getLogger/TestInferCaller.java

19:36:02  STDERR:
19:36:02  java.lang.RuntimeException: Bad class name: 
19:36:02  	expected: TestInferCaller
19:36:02  	actual:   java.lang.reflect.Method
19:36:02  	at TestInferCaller.assertEquals(TestInferCaller.java:373)
19:36:02  	at TestInferCaller.checkEvent(TestInferCaller.java:380)
19:36:02  	at TestInferCaller.testReflection(TestInferCaller.java:233)
19:36:02  	at TestInferCaller.test3(TestInferCaller.java:210)
19:36:02  	at TestInferCaller.test(TestInferCaller.java:341)
19:36:02  	at TestInferCaller.main(TestInferCaller.java:359)
19:36:02  	at java.lang.invoke.LambdaForm$DMH/0x00000000f8027240.invokeStatic(LambdaForm$DMH)
19:36:02  	at java.lang.invoke.LambdaForm$MH/0x00000000f802aff0.invoke(LambdaForm$MH)
19:36:02  	at java.lang.invoke.LambdaForm$MH/0x00000000f802b510.invokeExact_MT(LambdaForm$MH)
19:36:02  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
19:36:02  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
19:36:02  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
19:36:02  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:36:02  	at java.base/java.lang.Thread.run(Thread.java:884)
19:36:02  
19:36:02  JavaTest Message: Test threw exception: java.lang.RuntimeException: Bad class name: 
19:36:02  	expected: TestInferCaller
19:36:02  	actual:   java.lang.reflect.Method
19:36:02  JavaTest Message: shutting down test
19:36:02  
19:36:02  STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Bad class name: expected: TestInferCaller actual: java.lang.reflect.Method
```

This is due to https://github.com/eclipse-openj9/openj9/issues/13852. I have a draft fix.

**Comment by babsingh** [comment]
This failure is associated to JEP416. It will go away if JEP416 is disabled. This highlights missing JEP416 support in OpenJ9.

This failure is related to the `@CallerSensitiveAdapter` annotation which was introduced for JEP416. Associated extension repo change: https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ed8f09d38f1f29b69a17a3778325143d40d76d11.

@fengxue-IS and I believe that we need to add similar `@CallerSensitiveAdapter` support in our implementation of `j.l.Class` and `j.l.ClassLoader`. At this point, we believe that all the annotation related processing is done in OJDK's Java code. But, we should dig deeper to confirm that no native changes are needed.

**Comment by JasonFengJ9** [comment]
[JEP 416](https://github.com/eclipse-openj9/openj9/issues/13852) uses `java.lang.reflect.Method.invoke(Object obj, Object[] args, Class<?> caller)` instead of `java.lang.reflect.Method.invoke(Object obj, Object... args)` when JEP 416 is not enabled or early Java levels.
Created https://github.com/eclipse-openj9/openj9/pull/14137 to add the new `invoke` method.

fyi @babsingh

**Comment by pshipton** [comment]
Run grinder to test java/util/logging/Logger/getLogger/TestInferCaller.java which passed.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/448/

**Comment by pshipton** [comment]
https://github.com/eclipse-openj9/openj9/pull/14137 is merged so the test can be unexcluded and this issue closed.
