### ISSUE TITLE
Move Semeru Runtime Build Infrastructure as an Project in Perhaps Eclipse Foundation

### ISSUE THREAD

**Issue by sirinath** [eclipse-openj9/openj9#14139]
Please start another project like AdoptOpenJDK / Eclipse Adoptium to build, test and distribute OpenJ9. The infrastructure and test suits might need to be different based on Oracle's agreement with the Adoptium project. Where possible try to share the resources but build, test and distribute OpenJ9 in the open.

Ideally replace Java Class Libraries with and fully open source IBM / Eclipse / J9 implementation.

**Comment by pshipton** [comment]
IBM Semeru already does most of this. Fully open source builds are already provided at https://developer.ibm.com/languages/java/semeru-runtimes/downloads. The Adoptium pipelines are used to build and test the builds, although the builds themselves occur internal to IBM and not in the open. The OpenJ9 project builds and tests in the open as much as possible with the machine resources available. If more machine resources are donated to the project, more open testing could be run.

https://developer.ibm.com/languages/java/semeru-runtimes/blogs/
https://developer.ibm.com/languages/java/semeru-runtimes/

**Comment by mstoodle** [comment]
@sirinath there are no "IBM Java class libraries". There was IBM J9 which ran with proprietary class libraries from OracleJDK (with a few patches). Now there is Eclipse OpenJ9 that runs with open source OpenJDK class libraries. I don't think there's enough to gain from another set of class libraries to make up for the incredible effort that would be required (plus, you probably wouldn't be able to get a license to run the specification tests on it).
