### ISSUE TITLE
JDK18 JEP 421 Deprecate Finalization for Removal - test failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14131]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Personal/133/consoleFull`:
```
17:51:27  openjdk version "18-internal" 2022-03-22
17:51:27  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDKnextx86-64linuxPersonal)
17:51:27  Eclipse OpenJ9 VM (build master-9f6e55d3a25, JRE 18 Linux amd64-64-Bit Compressed References 20211209_920 (JIT enabled, AOT enabled)
17:51:27  OpenJ9   - 9f6e55d3a25
17:51:27  OMR      - ff2e42cc3e3
17:51:27  JCL      - 742164f41cc based on jdk-18+26)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2FOpenJ9-JDKnext-x86-64_linux-20211209-142128.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=9f6e55d3a25a6da74a76fd2490cc7d84f6296ce6&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.os.cent.6%26%26%21sw.os.rhel.6&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
17:54:39  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
17:54:39  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

18:13:51  --------------------------------------------------
18:25:51  TEST: java/lang/Object/FinalizationOption.java

18:25:51  STDOUT:
18:25:51  Finalizer thread.    Expected: true   Actual: (none)   FAILED!
18:25:51  Call to finalize().  Expected: true   Actual: true   Passed.
18:25:51  STDERR:
18:25:51  java.lang.AssertionError: Test failed.
18:25:51  	at FinalizationOption.main(FinalizationOption.java:120)
18:25:51  	at java.lang.invoke.LambdaForm$DMH/0x00000000280075d0.invokeStatic(LambdaForm$DMH)
18:25:51  	at java.lang.invoke.LambdaForm$MH/0x000000002800c160.invoke(LambdaForm$MH)
18:25:51  	at java.lang.invoke.LambdaForm$MH/0x000000002800cf40.invokeExact_MT(LambdaForm$MH)
18:25:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
18:25:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:25:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
18:25:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
18:25:51  	at java.base/java.lang.Thread.run(Thread.java:884)
18:25:51  
18:25:51  JavaTest Message: Test threw exception: java.lang.AssertionError: Test failed.

18:25:51  --------------------------------------------------
18:25:51  TEST: java/lang/Object/InvalidFinalizationOption.java

18:25:51  STDERR:
18:25:51   stdout: [];
18:25:51   stderr: [JVMJ9VM007E Command-line option unrecognised: --finalization
18:25:51  Error: Could not create the Java Virtual Machine.
18:25:51  Error: A fatal exception has occurred. Program will exit.
18:25:51  ]
18:25:51   exitValue = 1
18:25:51  
18:25:51  java.lang.RuntimeException: 'Unrecognized option' missing from stdout/stderr 
18:25:51  
18:25:51  	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
18:25:51  	at InvalidFinalizationOption.main(InvalidFinalizationOption.java:48)
18:25:51  	at java.lang.invoke.LambdaForm$DMH/0x00000000602e9680.invokeStatic(LambdaForm$DMH)
18:25:51  	at java.lang.invoke.LambdaForm$MH/0x00000000e000a720.invoke(LambdaForm$MH)
18:25:51  	at java.lang.invoke.LambdaForm$MH/0x00000000e000ada0.invokeExact_MT(LambdaForm$MH)
18:25:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
18:25:51  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
18:25:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
18:25:51  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
18:25:51  	at java.base/java.lang.Thread.run(Thread.java:884)
18:25:51  
18:25:51  JavaTest Message: Test threw exception: java.lang.RuntimeException
```

Related to https://github.com/eclipse-openj9/openj9/issues/14049

`InvalidFinalizationOption` failure seems a test issue due to OpenJ9 specific error message (a test change is sufficient).

**Comment by JasonFengJ9** [comment]
There are two different failures here, one is addressed by a test change https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/7.
The other requires code change https://github.com/eclipse-openj9/openj9/pull/14307
Re-open, to be closed by that PR.

**Comment by JasonFengJ9** [comment]
The tests have been re-included.
Closing..

**Comment by pshipton** [comment]
@JasonFengJ9 if tests are re-included, can the `test excluded` label be removed? There is no test excluded with this id, so I think yes. I'll leave it to you.

**Comment by JasonFengJ9** [comment]
Ah, removed the `test excluded` label.
