### ISSUE TITLE
JDK18 java/lang/ClassLoader/deadlock/DelegateTest.java - unrecognised: -Xlog:class+load & java timed out

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14133]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Personal/133/consoleFull`:
```
17:51:27  openjdk version "18-internal" 2022-03-22
17:51:27  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDKnextx86-64linuxPersonal)
17:51:27  Eclipse OpenJ9 VM (build master-9f6e55d3a25, JRE 18 Linux amd64-64-Bit Compressed References 20211209_920 (JIT enabled, AOT enabled)
17:51:27  OpenJ9   - 9f6e55d3a25
17:51:27  OMR      - ff2e42cc3e3
17:51:27  JCL      - 742164f41cc based on jdk-18+26)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2FOpenJ9-JDKnext-x86-64_linux-20211209-142128.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=9f6e55d3a25a6da74a76fd2490cc7d84f6296ce6&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.os.cent.6%26%26%21sw.os.rhel.6&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
17:54:39  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
17:54:39  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

18:56:52  --------------------------------------------------
18:56:52  TEST: java/lang/ClassLoader/deadlock/DelegateTest.java

18:56:52  STDERR:
18:56:52  JVMJ9VM007W Command-line option unrecognised: -Xlog:class+load

18:56:52  ACTION: main -- Error. Program `/home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 965429ms).
```

Triage is required to determine if this is a test issue or hang/deadlock.

**Comment by pshipton** [comment]
-Xlog isn't really supported by OpenJ9. There are some cases were it will enable the verbose gc log, but otherwise the option causes warnings or errors. It would be worth trying to validate the test could pass on OpenJ9 if -Xlog was supported, and there isn't a hidden problem.

**Comment by babsingh** [comment]
> Triage is required to determine if this is a test issue or hang/deadlock.

Yes, this is a deadlock. Refer to the diagnostic information below.

The test has not changed since 2017, and OpenJ9 JDK17 do not experience the deadlock. New changes in JDK18 are potentially responsible for the deadlock.

`JVMJ9VM007W Command-line option unrecognised: -Xlog:class+load` is also noticed with OpenJ9 JDK17, and the test still passes. So, it is not the cause of this failure.

### Diagnostic Info

Deadlock is between `Thread-4` and `Thread-5`. Both are trying to acquire monitors which are owned by each other.

```
1LKDEADLOCK    Deadlock detected !!!
NULL           ---------------------
NULL
2LKDEADLOCKTHR  Thread "Thread-5" (0x000000000053E600)
3LKDEADLOCKWTR    is waiting for:
4LKDEADLOCKMON      sys_mon_t:0x00007F75B8A799B8 infl_mon_t: 0x00007F75B8A79A38:
4LKDEADLOCKOBJ      DelegatingLoader@0x00000007FFCA6CE8
3LKDEADLOCKOWN    which is owned by:
2LKDEADLOCKTHR  Thread "Thread-4" (0x000000000053AA00)
3LKDEADLOCKWTR    which is waiting for:
4LKDEADLOCKMON      sys_mon_t:0x00007F7538002088 infl_mon_t: 0x00007F7538002108:
4LKDEADLOCKOBJ      DelegatingLoader@0x00000007FFCA6D68
3LKDEADLOCKOWN    which is owned by:
2LKDEADLOCKTHR  Thread "Thread-5" (0x000000000053E600)


2LKMONINUSE      sys_mon_t:0x00007F7538002088 infl_mon_t: 0x00007F7538002108:
3LKMONOBJECT       DelegatingLoader@0x00000007FFCA6D68: Flat locked by "Thread-5" (J9VMThread:0x000000000053E600), entry count 1
3LKWAITERQ            Waiting to enter:
3LKWAITER                "Thread-4" (J9VMThread:0x000000000053AA00)

2LKMONINUSE      sys_mon_t:0x00007F75B8A799B8 infl_mon_t: 0x00007F75B8A79A38:
3LKMONOBJECT       DelegatingLoader@0x00000007FFCA6CE8: Flat locked by "Thread-4" (J9VMThread:0x000000000053AA00), entry count 3
3LKWAITERQ            Waiting to enter:
3LKWAITER                "Thread-5" (J9VMThread:0x000000000053E600)


3XMTHREADINFO      "Thread-4" J9VMThread:0x000000000053AA00, omrthread_t:0x00007F7530017AC8, java/lang/Thread:0x00000007FFCABA50, state:B, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1B, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x9F0, native priority:0x5, native policy:UNKNOWN, vmstate:B, vm thread flags:0x00000281)
3XMTHREADINFO2            (native stack address range from:0x00007F759F4A1000, to:0x00007F759F4E1000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.053827695 secs, current category="Application"
3XMTHREADBLOCK     Blocked on: DelegatingLoader@0x00000007FFCA6D68 Owned by: "Thread-5" (J9VMThread:0x000000000053E600, java/lang/Thread:0x00000007FFCABAD0)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=146104 (0x23AB8)
1INTERNAL                    Unable to obtain lock context information
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/ClassLoader.loadClassHelper(ClassLoader.java:1183)
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java:1129)
4XESTACKTRACE                at DelegatingLoader.loadClass(DelegatingLoader.java:90)
4XESTACKTRACE                at DelegatingLoader.loadClass(DelegatingLoader.java:84)


3XMTHREADINFO      "Thread-5" J9VMThread:0x000000000053E600, omrthread_t:0x00007F7530525A30, java/lang/Thread:0x00000007FFCABAD0, state:B, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1C, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x9F1, native priority:0x5, native policy:UNKNOWN, vmstate:B, vm thread flags:0x00000281)
3XMTHREADINFO2            (native stack address range from:0x00007F759D649000, to:0x00007F759D689000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.040427184 secs, current category="Application"
3XMTHREADBLOCK     Blocked on: DelegatingLoader@0x00000007FFCA6CE8 Owned by: "Thread-4" (J9VMThread:0x000000000053AA00, java/lang/Thread:0x00000007FFCABA50)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=87800 (0x156F8)
1INTERNAL                    Unable to obtain lock context information
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/ClassLoader.loadClassHelper(ClassLoader.java:1183)
4XESTACKTRACE                at java/lang/ClassLoader.loadClass(ClassLoader.java:1129)
4XESTACKTRACE                at DelegatingLoader.loadClass(DelegatingLoader.java:90)
4XESTACKTRACE                at DelegatingLoader.loadClass(DelegatingLoader.java:84)
```

### Expected Test Ouput from OpenJ9 JDK17

```
Parallel ClassLoader registration: true
DelegatingLoader using URL file:/root/openj9-openjdk-jdk17/JTwork/scratch/
DelegatingLoader using URL file:/root/openj9-openjdk-jdk17/JTwork/scratch/
Spawned thread SA running
Loading local class comSA.Alice
Spawned thread SB running
Delegating class loading for comSA.SupBob
Delegating class loading for comSB.SupAlice
Loading local class comSA.SupBob
Loading local class java.lang.Object
Loading local class java.lang.System
Loading local class java.io.PrintStream
comSA.SupBob loaded
Thread SB terminating
Loading local class comSB.SupAlice
Loading local class java.lang.Object
Loading local class java.lang.System
Loading local class java.io.PrintStream
comSB.SupAlice loaded
comSA.Alice loaded
Thread SA terminating
```

### Deadlock Test Output from OpenJ9 JDK18

```
Parallel ClassLoader registration: false
DelegatingLoader using URL file:/root/openj9-openjdk-jdk17/JTwork/scratch/
DelegatingLoader using URL file:/root/openj9-openjdk-jdk17/JTwork/scratch/
Spawned thread SA running
Loading local class comSA.Alice
Spawned thread SB running
Delegating class loading for comSA.SupBob
Delegating class loading for comSB.SupAlice
Loading local class comSA.SupBob
Loading local class comSB.SupAlice
Timeout refired 120 times
```

**Comment by babsingh** [comment]
In https://github.com/eclipse-openj9/openj9/issues/14133#issuecomment-996725280, the diff between expected and deadlock output is
```
Expected output -- Parallel ClassLoader registration: true

Deadlock output -- Parallel ClassLoader registration: false
```

Test code related to the above output: https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/742164f41ccbae087b64a8f282ff98d610ab3f14/test/jdk/java/lang/ClassLoader/deadlock/DelegatingLoader.java#L60

The above test code invokes `java.lang.ClassLoader.registerAsParallelCapable` through reflection. Due to missing JEP416 support in OpenJ9, it is not invoked correctly.

Potential fix: https://github.com/eclipse-openj9/openj9/pull/14177
