### ISSUE TITLE
JDK18 jdk_foreign java/foreign/TestUpcall.java - UnsatisfiedLinkError: jdk/internal/foreign/abi/ProgrammableUpcallHandler.registerNatives()V 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14134]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Personal/133/consoleFull`:
```
17:51:27  openjdk version "18-internal" 2022-03-22
17:51:27  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDKnextx86-64linuxPersonal)
17:51:27  Eclipse OpenJ9 VM (build master-9f6e55d3a25, JRE 18 Linux amd64-64-Bit Compressed References 20211209_920 (JIT enabled, AOT enabled)
17:51:27  OpenJ9   - 9f6e55d3a25
17:51:27  OMR      - ff2e42cc3e3
17:51:27  JCL      - 742164f41cc based on jdk-18+26)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2FOpenJ9-JDKnext-x86-64_linux-20211209-142128.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F920%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=9f6e55d3a25a6da74a76fd2490cc7d84f6296ce6&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.os.cent.6%26%26%21sw.os.rhel.6&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
20:27:34  variation: Mode150
20:27:34  JVM_OPTIONS:  -XX:+UseCompressedOops 

20:30:40  --------------------------------------------------
20:30:40  TEST: java/foreign/TestUpcall.java#async

20:30:40  STDOUT:
20:30:40  config TestUpcall.setup(): failure
20:30:40  java.lang.UnsatisfiedLinkError: jdk/internal/foreign/abi/ProgrammableUpcallHandler.registerNatives()V
20:30:40  	at jdk.incubator.foreign/jdk.internal.foreign.abi.ProgrammableUpcallHandler.<clinit>(ProgrammableUpcallHandler.java:314)
20:30:40  	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.CallArranger.arrangeUpcall(CallArranger.java:143)
20:30:40  	at jdk.incubator.foreign/jdk.internal.foreign.abi.x64.sysv.SysVx64Linker.upcallStub(SysVx64Linker.java:92)
20:30:40  	at TestUpcall.setup(TestUpcall.java:124)
20:30:40  	at java.lang.invoke.LambdaForm$DMH/0x00000000a00c8870.invokeVirtual(LambdaForm$DMH)
20:30:40  	at java.lang.invoke.LambdaForm$MH/0x00000000a015d160.invoke(LambdaForm$MH)
20:30:40  	at java.lang.invoke.LambdaForm$MH/0x00000000201c5810.invokeExact_MT(LambdaForm$MH)
20:30:40  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
20:30:40  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
20:30:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
20:30:40  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
20:30:40  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
20:30:40  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
20:30:40  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
20:30:40  	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
20:30:40  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
20:30:40  	at org.testng.TestRunner$$Lambda$91/0x00000000a013e618.accept(Unknown Source)
20:30:40  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
20:30:40  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
20:30:40  	at org.testng.TestRunner.run(TestRunner.java:585)
20:30:40  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
20:30:40  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
20:30:40  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
20:30:40  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
20:30:40  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
20:30:40  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
20:30:40  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
20:30:40  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
20:30:40  	at org.testng.TestNG.runSuites(TestNG.java:1069)
20:30:40  	at org.testng.TestNG.run(TestNG.java:1037)
20:30:40  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
20:30:40  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
20:30:40  	at java.lang.invoke.LambdaForm$DMH/0x00000000a0006d00.invokeStatic(LambdaForm$DMH)
20:30:40  	at java.lang.invoke.LambdaForm$MH/0x00000000a000c020.invoke(LambdaForm$MH)
20:30:40  	at java.lang.invoke.LambdaForm$MH/0x00000000a000c540.invokeExact_MT(LambdaForm$MH)
20:30:40  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
20:30:40  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
20:30:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
20:30:40  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
20:30:40  	at java.base/java.lang.Thread.run(Thread.java:884)
20:30:40  test TestUpcall.testUpcalls(0, "f0_V__", VOID, [], []): skip
```

There are lots of similar `UnsatisfiedLinkError`. These tests might not apply to OpenJ9, or require changes to adopt Semeru runtime. I think they can be excluded for now to improve triage.

fyi @ChengJin01

**Comment by ChengJin01** [comment]
As I mentioned at https://github.com/eclipse-openj9/openj9/issues/13946, all foreign specific test suites in jtreg test should be excluded as the whole feature has not yet implemented (including downcall & upcall).

**Comment by ChengJin01** [comment]
I am wondering why https://github.com/adoptium/aqa-tests/pull/3150 didn't exclude these failing test suites. 
FYI: @llxia

**Comment by JasonFengJ9** [comment]
```
20:30:40  --------------------------------------------------
20:31:40  TEST: java/foreign/upcalldeopt/TestUpcallDeopt.java

20:31:40  java.lang.UnsatisfiedLinkError: sun/hotspot/WhiteBox.registerNatives()V
20:31:40  	at sun.hotspot.WhiteBox.<clinit>(WhiteBox.java:68)
20:31:40  	at TestUpcallDeopt.<clinit>(TestUpcallDeopt.java:59)
20:31:40  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
20:31:40  	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
20:31:40  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
20:31:40  	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
20:31:40  	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:192)
20:31:40  	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:719)
20:31:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
20:31:40  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
20:31:40  	at java.base/java.lang.Thread.run(Thread.java:884)
20:31:40  STATUS:Failed.`main' threw exception: java.lang.UnsatisfiedLinkError: sun/hotspot/WhiteBox.registerNatives()V
```
This is another `UnsatisfiedLinkError`.

**Comment by ChengJin01** [comment]
This should be excluded as upcall is not yet implemented.

**Comment by ChengJin01** [comment]
List all failing FFI related test suites found at https://github.com/eclipse-openj9/openj9/issues/13946 as follows so as to be tagged in the exclude file:
```
java/foreign/TestUpcall.java#async.TestUpcall_async
java/foreign/TestUpcall.java#no_scope.TestUpcall_no_scope
java/foreign/TestUpcall.java#scope.TestUpcall_scope
java/foreign/upcalldeopt/TestUpcallDeopt.java.TestUpcallDeopt
```
Please feel free to add if any other FFI related test  suite missing in the list above.

**Comment by llxia** [comment]
Re https://github.com/eclipse-openj9/openj9/issues/14134#issuecomment-991090714, We had [a similar issue before](https://github.com/adoptium/aqa-tests/pull/2796#issuecomment-896088732). Please try to use `java/foreign/TestUpcall.java#async`. For example: 
```
java/foreign/TestUpcall.java#async https://github.com/eclipse-openj9/openj9/issues/13999 generic-all
```

**Comment by JasonFengJ9** [comment]
Moving out the iteration plan since the feature in question hasn't been implemented and the test is excluded.

**Comment by ChengJin01** [comment]
Close this issue as outdated.
