### ISSUE TITLE
[JDK18] The FFI jtreg test failures detected on other platforms

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#14148]
This issue is created to tag all the failing FFI test suites still detected on other platforms at https://github.com/eclipse-openj9/openj9/issues/13946, which are as follows:
```
java/foreign/TestHandshake.java.TestHandshake
java/foreign/TestSegmentCopy.java.TestSegmentCopy
java/foreign/channels/TestAsyncSocketChannels.java.TestAsyncSocketChannels
```

FYI: @tajila, @pshipton, @llxia

**Comment by ChengJin01** [comment]
I notice we already excluded `TestAsyncSocketChannels` on all platforms at https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk18-openj9.txt
```
java/foreign/channels/TestAsyncSocketChannels.java https://github.com/eclipse-openj9/openj9/issues/14134 generic-all
```
but why it still occurred on some platforms.

**Comment by pshipton** [comment]
> I notice we already excluded TestAsyncSocketChannels on all platforms

Did the exclude get merged after build was started? After the latest set of excludes are merged we can run another build to check the latest status.

**Comment by ChengJin01** [comment]
> Did the exclude get merged after build was started? After the latest set of excludes are merged we can run another build to check the latest status.

Yes, It seems https://github.com/adoptium/aqa-tests/pull/3171 (including `TestAsyncSocketChannels`) was merged 3 hours later.  I can remove it from this PR if it is confirmed to be excluded in the latest run.

**Comment by pshipton** [comment]
The PR is merged so I'll try another run.

**Comment by pshipton** [comment]
Looked and the wrong PR. Pls remove it from https://github.com/adoptium/aqa-tests/pull/3185 since it's already excluded. I'll re-run after this PR is merged.

**Comment by ChengJin01** [comment]
Removed the duplicated `TestAsyncSocketChannels` from https://github.com/adoptium/aqa-tests/pull/3185.

**Comment by ChengJin01** [comment]
Close this issue as outdated given JD18 won't be released.
