### ISSUE TITLE
Request: Add standalone argument for -Xjit:perfTool to avoid clobbering pre-existing JIT tuning

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#14157]
The option `-Xjit:perfTool` is [useful during Linux `perf` profiling](https://blog.openj9.org/2019/07/18/inspecting-openj9-performance-with-perf-on-linux-jit-compiled-methods/); however, only the most recent `-Xjit` argument is processed. Therefore, if a customer has some previous JIT tuning, a support engineer might recommend `-Xjit:perfTool` without combining it with the previous tuning and thus end up on a wild goose chase. Here's an example showing the option is overridden:

```
$ podman run --rm ibm-semeru-runtimes:open-17-jdk sh -c "java -Xjit:verbose,exclude={ilog/rules/engine/sequential/generated/*} -Xjit:verbose,perfTool -version 2>&1 | awk '/INFO:  JIT/ {state=1;} state==1 && /options specified/ {state=2;} state==2 && /options in effect/ {state=0;} state==2 {print;}'"
#INFO:  options specified:
#INFO:       verbose,perfTool
#INFO:  

```

It would be nice if `-Xjit:perfTool` was a standalone option such as `-XperfTool` to avoid this situation. An analogy might exist with `-Xjit:compilationThreads`/`-XcompilationThreads` and `-Xjit:codeTotal`/`-Xcodecachetotal`.

**Comment by pshipton** [comment]
@0xdaryl fyi

**Comment by yathamravali** [comment]
@0xdaryl @kgibm - I've started working on this issue.

**Comment by kgibm** [comment]
Thanks!
