### ISSUE TITLE
jdk18 mauve incompatibility HttpURLConnection.requestPropertiesTest

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14168]
Large number of mauve failures in jdk18 testing, showing one example below. I'm guessing the test is incompatible with jdk18.
All the failures at https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK18/1/

https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64le_linux_Nightly_testList_2/1
```
LT  FAIL: gnu.testlet.java.net.HttpURLConnection.requestPropertiesTest: Map properties tests (number 3)
LT  got value but expected value2
...
LT  FAIL: gnu.testlet.java.net.HttpURLConnection.requestPropertiesTest: LowerUpperCase request properties tests (number 9)
```
@Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
Excluding `gnu.testlet.java.net.HttpURLConnection.requestPropertiesTest` solves the issue. 
PR for this : https://github.com/adoptium/aqa-systemtest/pull/473.

**Comment by pshipton** [comment]
https://github.com/adoptium/aqa-systemtest/pull/473 is merged, closing.
