### ISSUE TITLE
win2012-x86-5 online but not responding

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14185]
Disconnected it.

https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_windows_Nightly/121
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_windows_Release/19
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_windows_Release/21
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_OpenJDK/173
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-32_windows_Nightly/183/
```
21:27:57  Running on win2012-x86-5 in F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_Nightly
[Pipeline] {
[Pipeline] timeout
21:27:57  Timeout set to expire in 5 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
02:27:57  Cancelling nested steps due to timeout
```

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Restarted from cloud UI. Seems to be working now
https://openj9-jenkins.osuosl.org/job/Grinder/480
