### ISSUE TITLE
Core settings wrong on aarch64 ub20

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14199]
We're now seeing this problem on aarch64 machines.
```
[ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.3358963.
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_aarch64_linux_Nightly_testList_1/60/

@AdamBrousseau

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_aarch64_linux_Nightly_testList_0/88

**Comment by knn-k** [comment]
The same problem on cent8-aarch64-2:
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Personal/66/

**Comment by pshipton** [comment]
Apparently this was fixed, and I didn't see any failures in the past weekend builds.

**Comment by AdamBrousseau** [comment]
infrastructure/issues/6365
