### ISSUE TITLE
JDK18 sun/util/logging/PlatformLoggerTest.java - RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINE

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14232]
Failure link
------------

From an internal build `job/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Personal/1/consoleFull`(`ub18s390xrt-1-1`):
```
15:08:46  openjdk version "18-internal" 2022-03-22
15:08:46  OpenJDK Runtime Environment (build 18-internal+0-adhoc.jenkins.BuildJDK18s390xlinuxPersonal)
15:08:46  Eclipse OpenJ9 VM (build master-3cf0509e7e0, JRE 18 Linux s390x-64-Bit Compressed References 20220105_1 (JIT enabled, AOT enabled)
15:08:46  OpenJ9   - 3cf0509e7e0
15:08:46  OMR      - b5643d01920
15:08:46  JCL      - 03a0ab353e1 based on jdk-18+29)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_s390x_linux_Personal%2F1%2FOpenJ9-JDK18-s390x_linux-20220105-113358.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK18_s390x_linux_Personal%2F1%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=18&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk18.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=3cf0509e7e001405e2caaa8126282833b542ff40&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=941a48aa82d6c3edfc81323879b2470abc0ec3f2&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=20&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
16:23:34  --------------------------------------------------
16:23:34  TEST: sun/util/logging/PlatformLoggerTest.java

16:23:34  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINE
16:23:34  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
16:23:34  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
16:23:34  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
16:23:34  	at java.lang.invoke.LambdaForm$DMH/0x000000003400e350.invokeStatic(LambdaForm$DMH)
16:23:34  	at java.lang.invoke.LambdaForm$MH/0x0000000034012550.invoke(LambdaForm$MH)
16:23:34  	at java.lang.invoke.LambdaForm$MH/0x0000000034012a70.invokeExact_MT(LambdaForm$MH)
16:23:34  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
16:23:34  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
16:23:34  	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
16:23:34  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
16:23:34  	at java.base/java.lang.Thread.run(Thread.java:884)
16:23:34  
16:23:34  JavaTest Message: Test threw exception: java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINE

16:24:06  jdk_util_0_FAILED

```

50x grinder at `job/Grinder/20120`.

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse-openj9/openj9/issues/10759
