### ISSUE TITLE
CRIU: Implement internal hooks mechanism

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#14251]
We will need an internal hooking mechanism, similar to the Java one `J9InternalCheckpointHookAPI`. 
You dont need to worry about priority for this, we will just use explicit ordering. 

Here is the kind of API we need
```
At checkpoint time, this will iterate the heap (via `j9mm_iterate_all_objects`) and track all instances of type `instanceType`.
 If restore is set to FALSE it will run the hooks at checkpoint, otherwise at restore. If a hook returns FALSE then the hooks
 should throw an exception.

@param currentThread vmThread token
@param instanceType J9Class of type that we will perform a heap walk on
@param includeSubclass If TRUE subclasses of `instanceType` should be included
@param hook The routine that will be applied to each instance of that tpe
@param restore True if the hook needs to be applied on restore, FALSE if it needs to be applied at checkpoint
@return void
void addInternalHook(J9VMThread *currentThread, J9Class *instanceType, BOOLEAN (*hook)(J9VMThread *currentThread, void *userData, j9object_t obj), BOOLEAN restore);

@param user vmThread token
@param userData data for hook, can be NULL
@param obj heap instance where hook will be applied
@return TRUE if operation sucessful, FALSE if any failure
BOOLEAN (*hook)(J9VMThread *currentThread, void *userData, j9object_t obj)
```

The hooks will be run in criuhelpers.cpp. Internal checkpoint hooks should be run last (after java hooks), restore hooks first
 (before java hooks).

The object instances can be held in a data structure off of `J9CRIUCheckpointState`. 

```
struct J9CRIUCheckpointState {
    ...
    J9InternalHookRecord *hooks;
}

struct J9InternalHookRecord {
    J9Class *instanceType;
    BOOLEAN includeSubClass;
    BOOLEAN isRestoreHook;
    BOOLEAN (*hook)(J9VMThread *currentThread, void *userData, j9object_t obj) hook;
    j9object *instances; //not sure what data structure we need here, but something that can be easily iterated
}
```

We will need hold on to exclusive VM access before running the internal hooks so the GC doesnt move the object instances between checkpoint and restore. We may need to split the `jvm[Checkpoint|Restore]Hooks` into java and internal hooks for this to be possible.

**Comment by JasonFengJ9** [comment]
Proposing following internal hooks implementation:

* Added a `J9InternalFunctions` - `addInternalHook`
```
void (*addInternalHook)(struct J9VMThread* currentThread, J9Class* instanceType, BOOLEAN includeSubClass, BOOLEAN (*hookFunc)(struct J9JavaVM* vm, void* userData, j9object_t obj), BOOLEAN isRestoreHook);
```
* The `hookFunc` to be added is as following
```
BOOLEAN (*hookFunc)(struct J9JavaVM* vm, void* userData, j9object_t obj);
```

* A new field `struct J9Pool* hookRecords` is to be added within `J9CRIUCheckpointState`, which has following defines:
```
typedef struct J9InternalHookRecord {
	J9Class* instanceType;
	BOOLEAN includeSubClass;
	BOOLEAN isRestoreHook;
	BOOLEAN (*hookFunc)(struct J9JavaVM* vm, void* userData, j9object_t obj);
} J9InternalHookRecord;
```

* The `hookRecords` is initialized at `Java_org_eclipse_openj9_criu_CRIUSupport_isCRIUSupportEnabledImpl()`
```
vm->checkpointState.hookRecords = pool_new(sizeof(J9InternalHookRecord), 0, 0, 0, J9_GET_CALLSITE(), OMRMEM_CATEGORY_VM, POOL_FOR_PORT(vm->portLibrary))
```

* A `hookRecord` can be added 
```
	J9Class* juRandom = vmFuncs->internalFindKnownClass(currentThread, J9VMCONSTANTPOOL_JAVAUTILRANDOM, J9_FINDKNOWNCLASS_FLAG_EXISTING_ONLY);
	vmFuncs->addInternalHook(currentThread, juRandom, FALSE, iterateInstances, FALSE);
```

* The `iterateInstances` can process `J9InternalHookRecord` accordingly.
```
static BOOLEAN
iterateInstances(J9JavaVM* vm, void* userData, j9object_t obj)
{
	J9InternalHookRecord* hookRecord = (J9InternalHookRecord*)userData;

	return TRUE;
}
```

A draft change is at https://github.com/JasonFengJ9/openj9/tree/criuhooks

**Comment by tajila** [comment]
Perhaps rename `addInternalHook` to `addInternalJVMCheckpointHook` so it can be distinguished from the existing J9HookAPI

I noticed your `J9InternalHookRecord` doesnt include instances, are you planning to track those elsewhere?

**Comment by JasonFengJ9** [comment]
> Perhaps rename addInternalHook to addInternalJVMCheckpointHook so it can be distinguished from the existing J9HookAPI

Sure.

> I noticed your J9InternalHookRecord doesnt include instances, are you planning to track those elsewhere?

`J9InternalHookRecord` includes `instanceType`, `includeSubClass`, `isRestoreHook`, and `hookFunc`, my understanding is that each `addInternalJVMCheckpointHook()` adds a `J9InternalHookRecord`.
When `j9mm_iterate_all_objects` invokes `objectIteratorCallback` for each `objectDesc`, the `hookRecords` is to be iterated and checked against its `instanceType`, `includeSubClass`, `isRestoreHook` and invoke its `hookFunc`.
The `hookRecords` is iterated via following code snippet:
```
static jvmtiIterationControl
objectIteratorCallback(J9JavaVM* vm, J9MM_IterateObjectDescriptor* objectDesc, void* userData)
{
	J9Pool* hookRecords = (J9Pool*)userData;
	pool_state walkState;
	j9object_t object = objectDesc->object;
	J9InternalHookRecord* hookRecord = (J9InternalHookRecord*)pool_startDo(hookRecords, &walkState);
	while (NULL != hookRecord) {
		hookRecord->hookFunc(vm, hookRecord, object);
		hookRecord = (J9InternalHookRecord*)pool_nextDo(&walkState);
	}
	return JVMTI_ITERATION_CONTINUE;
}
```
 Does this meet the initial API requirements?

**Comment by tajila** [comment]
> When j9mm_iterate_all_objects invokes objectIteratorCallback for each objectDesc, the hookRecords is to be iterated and checked against its instanceType, includeSubClass, isRestoreHook and invoke its hookFunc.
The hookRecords is iterated via following code snippet:

 `j9mm_iterate_all_objects` is called once pre-checkpoint but the hooks can be run either at checkpoint or at restore. So for the restore hook instances you'd need a way to save them to avoid doing another heap walk after restore.

**Comment by JasonFengJ9** [comment]
> j9mm_iterate_all_objects is called once pre-checkpoint but the hooks can be run either at checkpoint or at restore. So for the restore hook instances you'd need a way to save them to avoid doing another heap walk after restore.

Added `struct J9Pool *instanceObjects` into `J9InternalHookRecord`, and save the objects matching `instanceType` into it for retrieving at restore. Updated https://github.com/eclipse-openj9/openj9/issues/14251#issuecomment-1015421680 and https://github.com/JasonFengJ9/openj9/tree/criuhooks
