### ISSUE TITLE
JVM does not detect that it runs in container and does not use container resource quotas

### ISSUE THREAD

**Issue by MichaelNesterenko** [eclipse-openj9/openj9#14266]
For some reason jvm does not detect container context and uses host resource quotas

Test command:

```
docker run -m 128m --rm --entrypoint sh adoptopenjdk/openjdk11-openj9:alpine -c "java -Xdump:java:events=vmstart -XX:MinRAMPercentage=20 -XX:MaxRAMPercentage=30 -XX:+UseContainerSupport -version && cat /java*"
```
Excerpt from the output:
```
1CICONTINFO    Running in container : FALSE
```
Full log output:
[jvm-log.txt](https://github.com/eclipse-openj9/openj9/files/7858553/jvm-log.txt)

**Comment by pshipton** [comment]
Perhaps related to https://github.com/eclipse-openj9/openj9/issues/14190#issuecomment-1010122701

**Comment by MichaelNesterenko** [comment]
@pshipton, looks like it, there is another host which uses cgroups v1 and jvm correctly sizes heap there.

**Comment by pshipton** [comment]
Thanks. I'm going to close this as a dup then.
