### ISSUE TITLE
Question: Array shape constants are confusing?

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#14280]
The usuage of Long and Double in array shape differs from the normal usage in the JVM.

```
/* Constants from J9ArrayShapeFlags */
#define J9ArraySizeBytes 0x0 //corresponds to 1byte elements
#define J9ArraySizeDoubles 0x3 //corresponds to 8byte elements
#define J9ArraySizeLongs 0x2 //corresponds to 4byte elements
#define J9ArraySizeWords 0x1 //corresponds to 2byte elements
```

Should these be renamed to be more consistent?

**Comment by tajila** [comment]
@gacholio thoughts?

**Comment by gacholio** [comment]
The "long" name came from the olden days when int was 16 and long was 32. If we were to do anything, I'd be tempted to use:
```
/* Constants from J9ArrayShapeFlags */
#define J9ArraySizeByte 0x0 //corresponds to 1byte elements
#define J9ArraySizeShort 0x1 //corresponds to 2byte elements
#define J9ArraySizeInt 0x2 //corresponds to 4byte elements
#define J9ArraySizeLong 0x3 //corresponds to 8byte elements
```
This may be slightly confusing in that the meaning of `Long` changes, but it should be easier to understand for anyone new.

**Comment by gacholio** [comment]
Alternately, we could use `J9ArrayShape8Bit` etc to avoid any naming confusion.

**Comment by gacholio** [comment]
Another consideration is that DDR knows about these flags. Perhaps the new constant mechanism will make this less onerous than it has been in the past.

**Comment by gacholio** [comment]
Is the stride for VT arrays stored in the RAM array class? If so, it might make more sense to get rid of these values entirely and piggyback on the stride.

**Comment by tajila** [comment]
> Is the stride for VT arrays stored in the RAM array class? 

Yes it is.

> If so, it might make more sense to get rid of these values entirely and piggyback on the stride.

We tried that a while ago but it introduce a startup perf regression as it meant that the GC can't use the `shape << arraysize` optimization when allocating arrays. As a result we split the allocation path between VT arrays nad non-VT arrays.

**Comment by gacholio** [comment]
In that case, I vote to either do nothing, or rename the constants to the explicit bit sizing.
