### ISSUE TITLE
Make JIT compilation more conservative when code cache space is low

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#14299]
Some applications generate many classes (and thus methods) dynamically and after some brief usage, these classes get unloaded.
If the Java heap is relatively large, the GC may not attempt to unload classes that are no longer used. In such a case, the code cache could become full and the JIT may stop compiling because there is no room to store these newly compiled bodies.
Ideally, the GC would trigger unloading based on code cache occupancy, but this issue deals with a complementary solution: when the code cache occupancy becomes large (say 50-75%) the JIT should increase the invocation counts that are set for newly introduced methods.
Current invocation counts are 1000/250 when SCC/AOT, 2000/1000 if SCC/AOT is not used and at least 4 cores are available, or 3000/3000 if less than 4 cores are available. We should use at least 3000/3000 counts for low code cache situations.
Moreover, if free code cache becomes critical (as indicated by CodeCachemanager->lowCodeCacheSpaceThresholdReached()) we could also downgrade compilations at cold to generate smaller compiled bodies.

The amount of used code cache space is given by `TR::CodeCacheManager::instance()->getCurrTotalUsedInBytes()`
The total amount of code cache is stored in `_jitConfig->codeCacheTotalKB`. These two values can be used to compute code cache occupancy.

**Comment by cjjdespres** [comment]
It looks like the initial invocation count is determined by `getInitialCountForMethod` in `j9method.cpp`. Is that right?

**Comment by mpirvu** [comment]
> It looks like the initial invocation count is determined by getInitialCountForMethod in j9method.cpp

It's more complicated than that. The routine that sets initial invocation counts to methods is `jitHookInitializeSendTarget` https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/HookedByTheJit.cpp#L374

**Comment by mpirvu** [comment]
This is an example of how we increase counts after we exited startup mode: https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/control/HookedByTheJit.cpp#L4894-L4928

Maybe we can do something similar. 
JITStateLogic is executed every 0.5 sec, so a couple of `if` statements are not going to add a lot of overhead.
Note that the code may suffer some changes due to https://github.com/eclipse-openj9/openj9/pull/12838

**Comment by mpirvu** [comment]
Since the new code does not depend on the JIT state, it should probably not be integrated into JITStateLogic, but rather put in the caller of JITStateLogic (samplerThreadProc), in the same loop that is executed every 0.5 sec.

**Comment by cjjdespres** [comment]
So after the `jitStateLogic` is run, we can just test for high cache occupancy and set the various initial invocation counts in `TR::Options::getCmdLineOptions()` and `getAOTCmdLineOptions()` directly. What do the various counts (`Count`, `BCount`, `MILCount`) correspond to?

**Comment by mpirvu** [comment]
> So after the jitStateLogic is run, we can just test for high cache occupancy and set the various initial invocation counts

Yes. I believe we don't have to worry about synchronization issues as long as various threads read/write an integer because with all modern processors integer load/store is atomic as long as it is aligned on a natural boundary.
`count` is used for loopless methods
`bcount` is used for method with loops (b stands for backward branches which is what the interpreter checks)
`milcount` was used for "many iterations loops", but it is deprecated so you don't have to worry about it.

**Comment by mstoodle** [comment]
did you consider including in this heuristic some notion of how much time and how many GC cycles have passed since class unloading was performed? i.e. if GCs are happening regularly and dead classes are being unloaded, is it really necessary to raise the thresholds?

**Comment by mpirvu** [comment]
> did you consider including in this heuristic some notion of how much time and how many GC cycles have passed since class unloading was performed?

No, and I wouldn't know how to come with sensible defaults for these. I do believe that the GC should take into consideration the code cache occupancy when deciding whether or not to unload classes. I already raised this issue with GC team.
Even if classes/methods are not unloaded, if we start to run out of code cache, we should become more selective with respect to what gets compiled, hence the increased counts.

**Comment by mstoodle** [comment]
ok, fair enough. I just worry (perhaps overmuch) about heuristics that don't have a competing heuristic in the other direction to provide some balance. But I suppose you could argue that this *is* the competing heuristic against the default counts selecting methods to be compiled into the code cache.
