### ISSUE TITLE
jdk18 crashes running sanity.openjdk

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14304]
Noticed in PR testing, sanity.openjdk on jdk18 started crashing yesterday. Below is the last good / first bad build, and the changes. These original builds were on Windows, but crashes are seen on Mac as well. Likely on other platforms but (open) builds haven't been run.

https://openj9-jenkins.osuosl.org/view/Pull%20Requests/job/PullRequest-OpenJ9/1396/
OpenJ9: 8e5a4fb7f7a
OMR: d406b054407
OpenJDK18: 91f1e7ba7a3 - openj9-openjdk-jdk18

https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK18_x86-64_windows/19/
OpenJ9: 683b76713df
OMR: d406b054407
OpenJDK: 91f1e7ba7a3

https://github.com/eclipse-openj9/openj9/compare/8e5a4fb7f7a...683b76713df

Mac:
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK18/11/
OpenJ9: 4a7e167e63a
OMR: d406b054407
OpenJDK18: 0065094e77b - openj9-openjdk-jdk18

The crashes are in the JIT (fyi @0xdaryl), but 
@tajila I suspect https://github.com/eclipse-openj9/openj9/pull/14282.
I'm going to try a build without this change.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/94/

**Comment by JasonFengJ9** [comment]
JDK18 has segmentation error issues for a while such as https://github.com/eclipse-openj9/openj9/issues/14228 https://github.com/eclipse-openj9/openj9/issues/14230 https://github.com/eclipse-openj9/openj9/issues/14231
These were seen regularly in my personal JDK18 builds (nightly builds were not launched as per `runtimes/infrastructure/issues/6277`).

**Comment by pshipton** [comment]
Ah ok, seems like this is a dup of https://github.com/eclipse-openj9/openj9/issues/14228 then. I guess sometimes you get lucky and there are no seg faults. If the problem is related to the shared cache / AOT, that could explain why some runs are successful and others crash in a random group of tests. I'm setting https://github.com/eclipse-openj9/openj9/issues/14228 a blocker.

**Comment by pshipton** [comment]
For the record, the build without https://github.com/eclipse-openj9/openj9/pull/14282 didn't have any segfaults.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/95/

**Comment by pshipton** [comment]
A re-run of the test on the same JVM produced many seg faults.
https://openj9-jenkins.osuosl.org/job/Grinder/515
