### ISSUE TITLE
openjdk9-openj9 jdk_rmi test failures

### ISSUE THREAD

**Issue by sophia-guo** [eclipse-openj9/openj9#1435]
Test results from the openjdk regression test group run against the nightly openjdk9-openj9 build at AdoptOpenJDK: Test results: Test results: passed: 78; failed: 53

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/consoleFull
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/artifact/jvmtest/openjdk_regression/work/java(sun)/rmi

java/rmi/activation/Activatable/checkActivateRef/CheckActivateRef.java
java/rmi/activation/Activatable/checkAnnotations/CheckAnnotations.java
java/rmi/activation/Activatable/checkImplClassLoader/CheckImplClassLoader.java
java/rmi/activation/Activatable/checkRegisterInLog/CheckRegisterInLog.java
java/rmi/activation/Activatable/createPrivateActivable/CreatePrivateActivatable.java
java/rmi/activation/Activatable/downloadParameterClass/DownloadParameterClass.java
java/rmi/activation/Activatable/elucidateNoSuchMethod/ElucidateNoSuchMethod.java
java/rmi/activation/Activatable/forceLogSnapshot/ForceLogSnapshot.java
java/rmi/activation/Activatable/inactiveGroup/InactiveGroup.java
java/rmi/activation/Activatable/nestedActivate/NestedActivate.java
java/rmi/activation/Activatable/nonExistentActivatable/NonExistentActivatable.java
java/rmi/activation/Activatable/restartCrashedService/RestartCrashedService.java
java/rmi/activation/Activatable/restartLatecomer/RestartLatecomer.java
java/rmi/activation/Activatable/restartService/RestartService.java
java/rmi/activation/Activatable/shutdownGracefully/ShutdownGracefully.java
java/rmi/activation/Activatable/unregisterInactive/UnregisterInactive.java
java/rmi/activation/ActivateFailedException/activateFails/ActivateFails.java
java/rmi/activation/ActivationGroup/downloadActivationGroup/DownloadActivationGroup.java
java/rmi/activation/ActivationSystem/activeGroup/IdempotentActiveGroup.java
java/rmi/activation/ActivationSystem/modifyDescriptor/ModifyDescriptor.java
java/rmi/activation/ActivationSystem/unregisterGroup/UnregisterGroup.java
java/rmi/activation/CommandEnvironment/SetChildEnv.java
java/rmi/dgc/VMID/CheckVMID.java
java/rmi/dgc/dgcAckFailure/DGCAckFailure.java
java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java
java/rmi/dgc/retryDirtyCalls/RetryDirtyCalls.java
java/rmi/registry/classPathCodebase/ClassPathCodebase.java
java/rmi/registry/serialFilter/RegistryFilterTest.java
java/rmi/reliability/benchmark/bench/rmi/Main.java
java/rmi/reliability/juicer/AppleUserImpl.java
java/rmi/server/RMIClassLoader/delegateToContextLoader/DelegateToContextLoader.java
java/rmi/server/RMIClassLoader/downloadArrayClass/DownloadArrayClass.java
java/rmi/server/RMIClassLoader/getClassLoader/GetClassLoader.java
java/rmi/server/RMIClassLoader/loadProxyClasses/LoadProxyClasses.java
java/rmi/server/RMIClassLoader/spi/ContextInsulation.java
java/rmi/server/RMIClassLoader/spi/DefaultProperty.java
java/rmi/server/RMIClassLoader/spi/Installed.java
java/rmi/server/RMIClassLoader/spi/InvalidProperty.java
java/rmi/server/RMIClassLoader/spi/Property.java
java/rmi/server/RMIClassLoader/useCodebaseOnly/UseCodebaseOnly.java
java/rmi/server/RMIClassLoader/useGetURLs/UseGetURLs.java
java/rmi/server/RMISocketFactory/useSocketFactory/activatable/UseCustomSocketFactory.java
java/rmi/server/RMISocketFactory/useSocketFactory/registry/UseCustomSocketFactory.java
java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.java
java/rmi/server/RemoteObject/toStub/ToStub.java
java/rmi/server/RemoteServer/AddrInUse.java
java/rmi/server/RemoteServer/setLogPermission/SetLogPermission.java
java/rmi/server/UnicastRemoteObject/unexportObject/UnexportLeak.java
java/rmi/server/UnicastRemoteObject/serialFilter/FilterUROTest.java
java/rmi/server/UnicastRemoteObject/useDynamicProxies/UseDynamicProxies.java
java/rmi/server/clientStackTrace/ClientStackTrace.java
java/rmi/transport/dgcDeadLock/DGCDeadLock.java
java/rmi/transport/readTimeout/ReadTimeoutTest.java
java/rmi/transport/runtimeThreadInheritanceLeak/RuntimeThreadInheritanceLeak.java
sun/rmi/server/MarshalOutputStream/marshalForeignStub/MarshalForeignStub.java

**Comment by llxia** [comment]
Close this issue as it is obsolete. JDK9 is out of support.
