### ISSUE TITLE
cmdLineTester_GCRotatingVerboseLogTests No such file or directory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14422]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/188/ - cent6-x64-4
cmdLineTester_GCRotatingVerboseLogTests_2 `-Xjit -Xgcpolicy:balanced -Xnocompressedrefs `
cmdLineTester_GCRotatingVerboseLogTests_3 `-XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced `
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly_testList_0/190/ - cent6-x64-5
cmdLineTester_GCRotatingVerboseLogTests_3

```
Executing command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s,5,1 -cp /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s
Test start time: 2022/02/02 00:11:04 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s.005
Time spent starting: 3 milliseconds
Time spent executing: 10 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: foo%s%s%s%s%s%s.005: No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]

Executing command: rm foo*.*

Executing command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s1234567%s%s%s%s%s%s!@%^*%s%s%s%s%s%sabcdef.#,5,1 -cp /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s and other random symbols
Test start time: 2022/02/02 00:11:05 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s1234567%s%s%s%s%s%s!@%^*%s%s%s%s%s%sabcdef.005
Time spent starting: 1 milliseconds
Time spent executing: 5 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: foo%s%s%s%s%s%s1234567%s%s%s%s%s%s!@%^*%s%s%s%s%s%sabcdef.005: No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]

Executing command: rm foo*.*

Executing command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i,5,1 -cp /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s %c %i
Test start time: 2022/02/02 00:11:06 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i.005
Time spent starting: 2 milliseconds
Time spent executing: 5 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i.005: No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]

Executing command: rm foo*.*

Executing command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i1234567!@%^*%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%isabcdef.#,5,1 -cp /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1

Testing: GC rotating verbose log file name contains %s %c %i and other random symbols
Test start time: 2022/02/02 00:11:07 Eastern Standard Time
Running command: cat foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i1234567!@%^*%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%isabcdef.005
Time spent starting: 2 milliseconds
Time spent executing: 4 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: foo%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%i1234567!@%^*%s%s%s%s%s%s%c%c%c%c%c%i%i%i%i%isabcdef.005: No such file or directory
>> Failure condition was found: [Output match: No such file or directory]
>> Success condition was not found: [Output match: </verbosegc>]


---TEST RESULTS---
Number of PASSED tests: 0 out of 4
Number of FAILED tests: 4 out of 4

```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly_testList_0/190/ - cent6-x64-5
cmdLineTester_GCRotatingVerboseLogTests_3

**Comment by pshipton** [comment]
@llxia @LongyuZhang it seems weird this just started failing last night on xlinux in the jdk8 and 11 testing. I didn't see anything that changed which would cause it. Any ideas?

https://github.com/adoptium/aqa-tests/compare/59d77dd5039...5a03ab34317
https://github.com/eclipse-openj9/openj9/compare/3b4b997b371...739de03a5b

**Comment by llxia** [comment]
Reran previously [passed build](https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_1/187/) on [cent6-x64-2](https://openj9-jenkins.osuosl.org/computer/cent6-x64-2) (previously passed machine).  [Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/590/console) failed.
```
02:05:31  OpenJDK Runtime Environment (build 1.8.0_322-internal-_2022_02_01_02_27-b00)
02:05:31  Eclipse OpenJ9 VM (build master-3b4b997, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220201_214 (JIT enabled, AOT enabled)
02:05:31  OpenJ9   - 3b4b997
02:05:31  OMR      - e449b3f
02:05:31  JCL      - cc0e9e2 based on jdk8u322-b06)
```

```
02:06:06  PASSED test targets:
02:06:06  	cmdLineTester_GCRotatingVerboseLogTests_0
02:06:06  	cmdLineTester_GCRotatingVerboseLogTests_1
02:06:06  	cmdLineTester_GCRotatingVerboseLogTests_4
02:06:06  
02:06:06  FAILED test targets:
02:06:06  	cmdLineTester_GCRotatingVerboseLogTests_2
02:06:06  	cmdLineTester_GCRotatingVerboseLogTests_3
```

**Comment by pshipton** [comment]
> Did we have any machine update on Jenkins?

@AdamBrousseau ? Also see https://github.com/eclipse-openj9/openj9/issues/14422#issuecomment-1028474309

We did update jenkins itself, but that was last week.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/189/ - cent7-x64-2
cmdLineTester_GCRotatingVerboseLogTests_3

Spreading to AIX now.

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64_aix_Nightly_testList_1/143 - p8-java1-ibm04
cmdLineTester_GCRotatingVerboseLogTests_0 `NoOptions`

**Comment by LongyuZhang** [comment]
Tested multiple machines on hyc_grinder, all passed. Not sure if openj9-jenkins machine have different settings compared with hyc-jenkins machines.

(50x) xlinux JDK11:  
- [fyrecloud-ubuntu18x86-8295-fqz8](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu18x86-8295-fqz8) (20708)

aix JDK17: 
- [paix911](https://hyc-runtimes-jenkins.swg-devops.com/computer/paix911) (20706) 
- [paix819](https://hyc-runtimes-jenkins.swg-devops.com/computer/paix819) (20705) 
- [paix909](https://hyc-runtimes-jenkins.swg-devops.com/computer/paix909) (20704) 
- [paix910](https://hyc-runtimes-jenkins.swg-devops.com/computer/paix910) (20703) 
- [paix817](https://hyc-runtimes-jenkins.swg-devops.com/computer/paix817) (20702) 
- 
xlinux JDK11: 
- [fyrecloud-ubuntu18x86-8295-98vo](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu18x86-8295-98vo) (20707) 
- [fyrecloud-ubuntu20x86-8298-2ott](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu20x86-8298-2ott) (20696) 
- [fyrecloud-ubuntu20x86-8298-n9rf](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu20x86-8298-n9rf) (20695) 
- [fyrecloud-ubuntu18x86-8295-98vo](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu18x86-8295-98vo) (20694) 
- [fyrecloud-ubuntu18x86-8295-5vr5](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu18x86-8295-5vr5) (20689)

xlinux JDK8: 
- [fyrecloud-ubuntu20x86-8298-pbhk](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu20x86-8298-pbhk) (20700) 
- [fyrecloud-ubuntu18x86-8295-g75q](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu18x86-8295-g75q) (20699) 
- [fyrecloud-ubuntu18x86-8295-nph1](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu18x86-8295-nph1) (20698) 
- [fyrecloud-ubuntu18x86-8295-8n87](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu18x86-8295-8n87) (20697) 
- [fyrecloud-ubuntu20x86-8298-xxzn](https://hyc-runtimes-jenkins.swg-devops.com/computer/fyrecloud-ubuntu20x86-8298-xxzn) (20690)

**Comment by pshipton** [comment]
I'm guessing the command running java isn't working for some reason, but we don't get to see the reason in the test failure output.
```
Executing command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_aot_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:name=cmdLineTester_GCRotatingVerboseLogTests_2 -Xscmx400M -Xscmaxaot256m  -Xjit -Xgcpolicy:balanced -Xnocompressedrefs  -Xint -verbose:gc -Xms8m -Xmx8m -Xverbosegclog:foo%s%s%s%s%s%s,5,1 -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_aot_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/gcRegressionTests/gcRegressionTests.jar com.ibm.tests.garbagecollector.SpinAllocate 1
```

We should change how the test works. It's trying to run java but not checking or providing any output when java doesn't run. Instead of running java as a command, we should run it as a cmdline test and validate that it did run correctly. Then if there is an error we'll get the stderr output.

**Comment by pshipton** [comment]
Actually I have another idea why the test isn't working. It's using `5,1` with -Xverbosegclog meaning output is redirected to 5 files, each containing 1 GC cycles. The test is looking for the 5th file, but if there is only 4 GC cycles then the 5th file won't be created and the test fails.

@dmitripivkine fyi

**Comment by pshipton** [comment]
Looking at the artifact from one of the failures, I see there were only 3 gc log files created for the test which failed.

**Comment by pshipton** [comment]
We're running `SpinAllocate 1` where the 1 is the number of seconds to spin creating garbage. If the machine is doing something else besides running java, 1 second could pass before enough garbage is generated to cause 5 GC cycles. I suggest
a) look for the 3rd file instead of the 5th
b) change the 1 to at least 3 or maybe 5

**Comment by AdamBrousseau** [comment]
Most machines (including cent6x-2) are setup via cron to auto-update everyday at 1am. Let me know if you need me to hunt down details of what happened between those dates.

**Comment by pshipton** [comment]
As per previous comments I think it's a test problem, the test is dependent on timing. The failing machines seem to be running a little slow, but the test needs to be fixed.
