### ISSUE TITLE
AArch64 macOS: Failures with "Cannot create cache of requested size"

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#14434]
Some functional tests on AArch64 macOS fail with the message "Cannot create cache of requested size: Please check your SHMMAX and SHMMIN settings" as shown below.

Failure link
------------
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal/4/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_aarch64_mac_Personal/3/

Failure output (captured from console output)
---------------------------------------------

SCURLClassLoaderNPTests_0:
```
Test result: FAILED
 [ERR] JVMSHRC005I No shared class caches available
 [ERR] JVMSHRC659E An error has occurred while opening shared memory
 [ERR] JVMSHRC336E Port layer error code = -174
 [ERR] JVMSHRC337E Platform error message: Invalid argument
 [ERR] JVMSHRC026E Cannot create cache of requested size: Please check your SHMMAX and SHMMIN settings
 [ERR] JVMSHRC663I Error recovery: destroyed semaphore set with id=2162690 associated with shared class cache.
 [ERR] JVMSHRC840E Failed to start up the shared cache.
 [ERR] JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
 [ERR] Error: Could not create the Java Virtual Machine.
 [ERR] Error: A fatal exception has occurred. Program will exit.
```

testSCCMLTests6_0:
```
Test result: FAILED
 [ERR] JVMSHRC659E An error has occurred while opening shared memory
 [ERR] JVMSHRC336E Port layer error code = -174
 [ERR] JVMSHRC337E Platform error message: Invalid argument
 [ERR] JVMSHRC026E Cannot create cache of requested size: Please check your SHMMAX and SHMMIN settings
 [ERR] JVMSHRC663I Error recovery: destroyed semaphore set with id=65539 associated with shared class cache.
 [ERR] JVMSHRC840E Failed to start up the shared cache.
 [ERR] JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
 [ERR] Error: Could not create the Java Virtual Machine.
 [ERR] Error: A fatal exception has occurred. Program will exit.
```

There are some others with the same error.

**Comment by knn-k** [comment]
The same (?) problem on x86 macOS in the past: #3602, #3790

**Comment by knn-k** [comment]
Note that PR #14425 needs to be merged for running functional tests on AArch64 macOS.

**Comment by pshipton** [comment]
Seems a machine configuration problem them. @AdamBrousseau

**Comment by jdekonin** [comment]
Step appears to have been missed for creating a script for launchctl to load on startup (/Library/LaunchDaemons/openj9.plist).  

mac11-aarch64-1 -> mac11-aarch64-8 now reporting these settings.
```
kern.sysv.shmall: 30722560
kern.sysv.shmmax: 125839605760
kern.coredump: 1
```

Note: these are what we are using for the x86 macs, these settings might need to be altered for aarch64.

Respin of the failed sanity.functional jobs
https://openj9-jenkins.osuosl.org/job/Grinder/599/console

jniargtests_0, jniargtests_1, jniargtests_2 and cmdLineTester_CryptoTest_0 still fail but these are not related to the settings that this issue corrected and are detailed as expected by @knn-k [here](https://github.ibm.com/runtimes/infrastructure/issues/6171#issuecomment-40375418)

**Comment by knn-k** [comment]
Thank you!
