### ISSUE TITLE
jdk19 annotation tests fail due to toString() format changing

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14498]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/233/

Test_Class annotation tests are failing due to toString() format changing. The expected values are hard coded in the test.
See https://github.com/eclipse-openj9/openj9/blob/master/test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java#L2279

https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/b94b711f455fdbc6...526c1101dd7
Guessing:
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/780a046ee2bc25d4 "8281462: Annotation toString output for enum not reusable for source input"

Blocking jdk19 acceptance from passing.

@tajila

**Comment by tajila** [comment]
@mikezhang1234567890 Can you please take a look at this

**Comment by tajila** [comment]
In the short term you can disable the test. Longer term we need to modify the tests to take into account the new behaviour

**Comment by pshipton** [comment]
Should be an easy fix, we just need a table to support jdk19+. Looked like `$` changed to `.`.
