### ISSUE TITLE
Non-tearable value classes

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#14518]
The original ValueTypes has been split into 2 types of classes in the new model:
1. [Value Classes](https://openjdk.java.net/jeps/8277163) (classes with `ACC_VALUE`)
2. [Primitive Classes](https://openjdk.java.net/jeps/401) (classes with both`ACC_VALUE` and `ACC_PRIMITIVE`)

With https://github.com/eclipse-openj9/openj9/issues/14460, OpenJ9 now recognizes value classes. For value classes, it requires atomic read and write, so tearing is not allowed. 

This means flattening can only be done for value classes <= 64 bits (currently OpenJ9 only checks `ACC_VALUE` to set `J9ClassIsFlattened`). As value classes are nullable, if we decide to flatten value classes <= 64 bits, an additional field/bit needs to be added to represent null. Also this means OpenJ9 needs to add/support a new object model. Alternatively, we could disable flattening for value classes.

**Comment by hangshao0** [comment]
@tajila, I guess we could disable flattening for value classes for now ?

**Comment by tajila** [comment]
>  I guess we could disable flattening for value classes for now ?

Yes, flattening should be limited to the primitive valuetypes. Also, optimizations related to layouts need a similar change. Examples are places where we do preloading/pre-init/pre-verification etc. Places where we restrict NULLs, etc.


A good approach would be to look at all the places where we do the `J9_IS_VALUETYPE` and replace with `J9_IS_PRIMITIVE_VALUE_TYPE`. Then after we can identify cases where the behaviour applies to both primitive and valuetype. Essentially, yesterdays value type is todays primitive value type

**Comment by hangshao0** [comment]
FYI @hzongaro @a7ehuo 

With #14763, now the VM code distinguishes between value classes and primitive value classes. As mentioned in https://github.com/eclipse-openj9/openj9/issues/14518#issuecomment-1040770318, yesterdays value type is todays primitive value type.
JIT code currently using `J9_IS_J9CLASS_VALUETYPE(clazz)` might need to split into:
`J9_IS_J9CLASS_VALUETYPE(clazz)` for value classes     
`J9_IS_J9CLASS_PRIMITIVE_VALUETYPE(clazz)` for primitive value classes.
