### ISSUE TITLE
JVM is ignoring LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by ed03875** [eclipse-openj9/openj9#14554]
Java -version output
--------------------

**Output from `java -version`.**
java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)

**Unix version** 
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="[https://www.centos.org/"](https://www.centos.org/%22)
BUG_REPORT_URL="[https://bugs.centos.org/"](https://bugs.centos.org/%22)

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Summary of problem**
------------------
The HotSpot JVM is ignoring LD_LIBRARY_PATH and expecting shared libraries to be one level up from where libjvm.so is loaded.  This differs from J9 and we believe this to be a bug because the library path is ignored when searching for shared libraries

**Diagnostic files**
----------------
**simple C test program**  
javatest.c
```
#include <jni.h>
int main() {
printf("begin..........\n");
JavaVM *jvm; /* denotes a Java VM */
JNIEnv *env; /* pointer to native method interface */
JavaVMInitArgs vm_args; /* JDK/JRE 6 VM initialization arguments */
JavaVMOption* options = new JavaVMOption[1];
char optionString[] = "-Djava.class.path=/home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/bin/classic";
options[0].optionString = optionString;
vm_args.version = JNI_VERSION_1_8;
vm_args.nOptions = 1;
vm_args.options = options;
vm_args.ignoreUnrecognized = false;
/* load and initialize a Java VM, return a JNI interface
* pointer in env */int res = JNI_CreateJavaVM(&jvm, (void**)&env, &vm_args);
printf("result=%d\n", res);
delete options;
/* invoke the Main.test method using the JNI */
// jclass cls = env->FindClass("Main");
// jmethodID mid = env->GetStaticMethodID(cls, "test", "(I)V");
// env->CallStaticVoidMethod(cls, mid, 100);
/* We are done. */
jvm->DestroyJavaVM();
return 0;
}
```
**Test run summary**
Hotspot simply ignores the library path and only works when the library path points to the libjvm.so and one level up contains libjava.so.  Below is proof using the test program above. 

**Tests with results** 
The bin/classic directory contains everything that is in the server directory when we point LD_LIBRARY_PATH to the classic directory the JVM does not find libjava.so because it is in amd/64
```
export LD_LIBRARY_PATH=/home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/bin/classic
./javatest
begin..........
Error occurred during initialization of VM
Unable to load native library: /home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/bin/libjava.so: cannot open shared object file: No such file or directory
```

In the second case test we see the JVM did  not find the libjava.so in amd64 even though it is in the Library path and contains libjava.so. 
```
export LD_LIBRARY_PATH=/home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/bin/classic:/home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/lib/amd64
 ./javatest
begin..........
Error occurred during initialization of VM
Unable to load native library: /home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/bin/libjava.so: cannot open shared object file: No such file or directory
```

The third case works because we meet the requirement of the first entry of the library path pointing to the jvm and one level up contains libjava.so
```
export LD_LIBRARY_PATH=/home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/lib/amd64/server
./javatest
begin..........
result=0
```
Just to prove the ordering doesn't matter this case fails too.
```
export LD_LIBRARY_PATH=/home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/lib/amd64:/home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/bin/classic
./javatest
begin..........
Error occurred during initialization of VM
Unable to load native library: /home/mkarra/sandboxes/hotspotjdk/bin/linux64/bin/jvm/bin/libjava.so: cannot open shared object file: No such file or directory
```

---------------------------------

We have been asking this question in the question section but moved it to here with a simple test program to get a response as to weather you consider this a bug, We have two rather large products that depend on the behavior of the JVM and a great deal of code will need to be changed if you don't see this as a problem. We currently use the J9 approach where we depend on the library path being able to be set to point to shared libraries.  The classic directory you see above is part of the J9 directory structure dating back to IBM where the classic directory contains everything in the server directory.

**Comment by pshipton** [comment]
Is the concern with Hotspot or OpenJ9? It seems your concern is with Hotspot. If you want Hotspot to change behavior you need to engage with the OpenJDK project.
