### ISSUE TITLE
Add testing for `-Xtune:throughput`

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#14551]
PR https://github.com/eclipse-openj9/openj9/pull/14277 introduced a new JVM option, `-Xtune:throughput`, and we need to provide some testing for this new mode.
Attn: @cjjdespres

**Comment by mpirvu** [comment]
I spoke to @llxia and we need to add a new entry into the playlist:  https://github.com/eclipse-openj9/openj9/blob/master/test/functional/Java8andUp/playlist.xml

**Comment by cjjdespres** [comment]
Would that be based on an existing entry?

**Comment by mpirvu** [comment]
I was thinking about this. It's relatively easy to add a new entry into the playlist.xml. The question is what is the application that we want to run? It must be something that creates a fair amount of compilations.
Maybe the best choice is to use this new mode in the same way we test -Xaggressive, but I don't know where that takes place.

**Comment by llxia** [comment]
- In the functional test, we run `-Xaggressive` in https://github.com/eclipse-openj9/openj9/blob/24b14b4743f82a648712bdca71a5b870828e65f9/test/functional/cmdLineTests/reflectCache/playlist.xml#L25

https://github.com/eclipse-openj9/openj9/blob/24b14b4743f82a648712bdca71a5b870828e65f9/test/functional/cmdLineTests/reflectCache/reflectcache_test.xml#L106
https://github.com/eclipse-openj9/openj9/blob/24b14b4743f82a648712bdca71a5b870828e65f9/test/functional/cmdLineTests/reflectCache/reflectcache_test.xml#L106

- It looks like `-Xaggressive` is mostly tested in system tests via [Mode187](https://github.com/adoptium/TKG/blob/07171520f8b0849d922125d35380d45193f9c5bf/resources/modes.xml#L1771)
https://github.com/adoptium/aqa-tests/search?q=Mode187&type=

**Comment by cjjdespres** [comment]
So would it make sense to create a new mode and add it as a variation in the tests where Mode187 is currently used?

It's a bit hard for me to tell what the purpose of the `reflectcache_test` is. Would that be a suitable model?

**Comment by llxia** [comment]
In general, there is no need to add a new mode unless the JVM option can only run on specific platforms. Does `-Xtune:throughput` apply to all platforms? If so, there is no need to add a new Mode for it. We can just add `<variation>-Xtune:throughput</variation>` in playlist.

**Comment by mpirvu** [comment]
yes, `-Xtune:throughput` applies to all platforms. 
If `-Xaggressive` and `-Xquickstart` have their own mode, I would prefer to do the same for `-Xtune:throughput`. `-Xquickstart` is incompatible with `-Xtune:throughput` (or -Xtune:virtualized) and only the right most option will take effect.

**Comment by mpirvu** [comment]
system/mauveLoadTest/playlist.xml  seems like a good choice to me for using the new mode

**Comment by cjjdespres** [comment]
I'm not sure I understand the advantage of the mode over the simple `-Xtune:throughput` in a variation, at least if the only setting is going to be that one option. Is it just for uniformity with the other option testing?

**Comment by mpirvu** [comment]
Yes, it's mostly for uniformity but also I was thinking that it reduces the likelihood of using `-Xtune:throughput` on top of a mode that contradicts it (like -Xquickstart). However, I am ok without a new mode as well.

**Comment by cjjdespres** [comment]
I see. That's fine then. I'll add that to TKG and aqa-tests and open up requests once I've got it working.

**Comment by cjjdespres** [comment]
Is there any significance to the numbering scheme for the modes?

**Comment by mpirvu** [comment]
No, there isn't

**Comment by llxia** [comment]
Just a note, if you add a new Mode, you need to update ottawa.csv. Also, I think we have issues with the new Mode in vmfarm. FYI @renfeiw

**Comment by cjjdespres** [comment]
I've been trying to run the tests to confirm that my commits actually work, and I don't think I've been configuring them correctly. E.g. in [this build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/21517/) I get

```
11:17:00  openjdk version "1.8.0_302-internal"
11:17:00  OpenJDK Runtime Environment (build 1.8.0_302-internal-202105071818-b01)
11:17:00  Eclipse OpenJ9 VM (build master-f06af2d55, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210507_1010 (JIT enabled, AOT enabled)
11:17:00  OpenJ9   - f06af2d55
11:17:00  OMR      - 7bff18ff5
11:17:00  JCL      - e0e56cb2 based on jdk8u302-b01)
11:17:00  STF 08:16:59.814 - 
11:17:00  STF 08:16:59.814 - +------ Step 1 - Run Mauve load test
11:17:00  STF 08:16:59.814 - | Run foreground process
11:17:00  STF 08:16:59.814 - |   Program:     /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java
11:17:00  STF 08:16:59.814 - |   Mnemonic:    LT
11:17:00  STF 08:16:59.814 - |   Echo:        ECHO_ON
11:17:00  STF 08:16:59.814 - |   Expectation: CLEAN_RUN within 1h5m
11:17:00  STF 08:16:59.814 - |
11:17:00  STF 08:16:59.815 - Running command: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -Xdump:system:events=throw,filter=net/adoptopenjdk/loadTest/reporting/MauveTestFailureException,range=1..1,request=exclusive+prepwalk -Xtune:throughput -classpath /home/jenkins/workspace/Grinder/jvmtest/system/STF/stf.load/bin:/home/jenkins/workspace/Grinder/jvmtest/system/STF/stf.core/bin:/home/jenkins/workspace/Grinder/jvmtest/system/systemtest_prereqs/log4j/log4j-api.jar:/home/jenkins/workspace/Grinder/jvmtest/system/systemtest_prereqs/log4j/log4j-core.jar:/home/jenkins/workspace/Grinder/jvmtest/system/systemtest_prereqs/mauve/mauve.jar net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16463242165050/MauveMultiThrdLoad_special_5m_9/20220303-081657-MauveMultiThrdLoadTrc/results -resultsPrefix 1.LT. -timeLimit 5m -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.mauve.inventoryFile /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16463242165050/MauveMultiThrdLoad_special_5m_9/20220303-081657-MauveMultiThrdLoadTrc/results/1.LT.inventory/openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml -suite.mauve.inventoryExcludeFile /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16463242165050/MauveMultiThrdLoad_special_5m_9/20220303-081657-MauveMultiThrdLoadTrc/results/1.LT.inventory/openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml -suite.mauve.threadCount 3 -suite.mauve.selection random -suite.mauve.seed -1 -suite.mauve.repeatCount 1 -suite.mauve.thinkingTime 0ms..0ms
11:17:00  STF 08:16:59.815 - Redirecting stderr to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16463242165050/MauveMultiThrdLoad_special_5m_9/20220303-081657-MauveMultiThrdLoadTrc/results/1.LT.stderr
11:17:00  STF 08:16:59.815 - Redirecting stdout to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16463242165050/MauveMultiThrdLoad_special_5m_9/20220303-081657-MauveMultiThrdLoadTrc/results/1.LT.stdout
11:17:00  STF 08:16:59.821 - Monitoring processes: LT 
11:17:00  LT  stderr JVMJ9VM007E Command-line option unrecognised: -Xtune:throughput
11:17:00  LT  stderr Error: Could not create the Java Virtual Machine.
```

which I think is because openj9 f06af2d55 is too old. But in that build I set the openj9 SHA to 93fef02044fc74ac4ca13f19f597f668963256f0, so I must be doing something wrong.
