### ISSUE TITLE
CRIU: main thread is not guaranteed to be hook thread

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#14568]
In `runInternalJVMRestoreHooks` and `runInternalJVMCheckpointHooks` we are running internal hooks with the `vm->mainThread`. This only works if the mainThread is the thread that triggered the hook. We are not guaranteed this.

```
BOOLEAN
runInternalJVMRestoreHooks(J9JavaVM *vm)
{
	J9VMThread *currentThread = vm->mainThread;
```

**Comment by tajila** [comment]
@JasonFengJ9 Please take a look at this

**Comment by JasonFengJ9** [comment]
@tajila can you try https://github.com/eclipse-openj9/openj9/pull/14573?
