### ISSUE TITLE
Jetbrains IDEs seem to have a separate UI behavior (titlebar is shown)

### ISSUE THREAD

**Issue by ciplogic** [eclipse-openj9/openj9#14581]
Java -version output
--------------------

Output from `java -version`.
Windows/x64 Semeru runtime 11.0.14.1+1 amd64

Summary of problem
------------------
Not sure if it is a problem but distinctively the IntelliJ IDEA would not have a native Windows Title bar, but a draggable "menu bar".

As IDEA allows you to choose a custom JDK runtime, I quite often choose OpenJ9 as it starts faster and it uses smaller memory footprint.

But (not sure from when) the Title Bar of the IDEA products (it should happen also for PyCharm, as I'm using @ work the Rider IDE, and so on), all of them seem to have showing the title bar.

In my understanding, Jetbrains IDEs do use Swing (so maybe it is a bug in the Swing implementation around decorations in OpenJ9 or the OpenJDK code). I didn't see any other behavior changed otherwise. It could be also a bug in the JetBrains IDEs. 

I noticed that this bug doesn't show if choosing other JVM like GraalVM (in JIT mode) and it happens from the first start.

Expectations
------

First of all, I am not sure if it is even a bug with JetBrains or OpenJ9, it could be either, so IMHO it is a low priority. It doesn't block me, the IDE runs fine, and so on. Still, I wanted to have it tracked for the sake of if you find other people complaining, to know that it is there.

The 2nd part: because an IDE is complex, maybe the solution is to report it to JetBrains's bug tracker.

3rd thing: maybe it is happening only on my machine (Win11, 64 bit, latest Idea -both CE and Ultimate, Rider). I feel okay if you don't fix it at all but when other bugs are found around the same runtime.

**Comment by ciplogic** [comment]
If the description is not too clear.

"Before" - JDK based runtimes (including Graal), using IDEA Ultimate

![image](https://user-images.githubusercontent.com/372483/155383292-2e4c6bb1-5b3c-4b80-b494-564320178a44.png)

"After"

![image](https://user-images.githubusercontent.com/372483/155383477-c921c2e0-85b6-4a31-9403-55734c5d0426.png)

I didn't see any other behavior changes and the all other flags (but the runtime) are the same.
I reduced the VM flags to minimum, just to not have anything to distract anyone:
```
-Xmx2048m
```

**Comment by pshipton** [comment]
Does it occur with the 11.0.14.1 Temurin build? https://adoptopenjdk.net/releases.html
If not, does it still occur with Semeru if you add `-Xshareclasses:none`?

**Comment by ciplogic** [comment]
It happens also with Temurin build taken from Adoptiunm (I used same version `11.0,14,1`) and with `-XShareclasses:none`

So it is likely an JetBrains bug?

**Comment by ciplogic** [comment]
I tested also with latest GraalVM (22.0.0.2) and the problem is there too. Sorry, false alarm! :( I was testing with older

So it looks like there is a change, but it is 99% introduced upstream (OpenJDK base code or wherever is the bug - like JetBrain's settings are not read correctly from the whatever library they use) or downstream (JetBrains IDE). I am confident that this bug can be closed, and I will open it back if I can see the bug persisting.

As a note: the JetBrains OpenJDK version is:
```

PS C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2\jbr\bin> java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05, mixed mode, sharing)
```

**Comment by pshipton** [comment]
> So it is likely an JetBrains bug?

JetBrains or OpenJDK, but not OpenJ9.
