### ISSUE TITLE
how can i make gc slow 

### ISSUE THREAD

**Issue by 15838028035** [eclipse-openj9/openj9#14601]
hi , when i use openj9 ,  test make 10 000 000 data，   

how can i make gc slow , cloud you help me ? 
![图片](https://user-images.githubusercontent.com/12193885/155637131-1a263cbc-7ef5-4df4-986b-f10c23e087f1.png)

**Comment by pshipton** [comment]
@dmitripivkine @amicic 
I don't understand the question, but maybe you do.

**Comment by dmitripivkine** [comment]
@15838028035 Sorry, I don't understand your question. Would you please provide more information about your problem? Please attach GC verbose log too

**Comment by dmitripivkine** [comment]
@15838028035 The request to clarify the problem has not been responded. I am closing this request for now. If it is still be a problem please reopen the item and provide clarification.
