### ISSUE TITLE
SDK_RESOURCE needs to be set in the pipeline

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#14616]
Currently, we do not set SDK_RESOURCE in the upstream pipeline and we depend on the test pipeline default values. This default value may not be correct. We should set SDK_RESOURCE explicitly in the pipeline.

- Set SDK_RESOURCE=customized
https://github.com/eclipse-openj9/openj9/blob/68f2d9d26b7918a718f160b9d60ac39bdbd80b38/buildenv/jenkins/common/pipeline-functions.groovy#L248
- Set SDK_RESOURCE=upstream
https://github.com/eclipse-openj9/openj9/blob/68f2d9d26b7918a718f160b9d60ac39bdbd80b38/buildenv/jenkins/common/pipeline-functions.groovy#L252

**Comment by pshipton** [comment]
@AdamBrousseau fyi
@llxia are you fixing this yourself or looking for a fix?

**Comment by llxia** [comment]
Currently, this does not break anything. I am hoping to get some help from the CANOSP students. If not, I will fix it myself.

**Comment by smlambert** [comment]
Does not break anything so is not _urgent_, but does block us from merging a fix for https://github.com/adoptium/aqa-tests/issues/2097 (we had to revert https://github.com/adoptium/aqa-tests/pull/3266).

**Comment by nadeensami** [comment]
I'd like to be assigned to this
