### ISSUE TITLE
AArch64 macOS: Intermittent failure in SC_Softmx_JitAot_0 test

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#14635]
Failure link
------------
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_aarch64_mac_Release/1/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Nightly/2/

Failure output (captured from console output)
---------------------------------------------

Workload process jvm1 terminates unexpectedly at Step 6 in SC_Softmx_JitAot_0.

```
STF 17:35:00.158 - +------ Step 6 - Waiting for jvm1 and jvm2 to finish
STF 17:35:00.158 - | Wait for processes to meet expectations
STF 17:35:00.158 - |   Processes: [jvm1, jvm2]
STF 17:35:00.158 - |
STF 17:35:00.158 - Monitoring processes: jvm1 jvm2
STF 17:35:13.215 - **FAILED** Process jvm1 ended with exit code (255) and not the expected exit code/s (0,1)
STF 17:35:13.215 - Monitoring Report Summary:
STF 17:35:13.215 -   o Process jvm1 ended with exit code (255) and not the expected exit code/s (0,1)
STF 17:35:13.215 -   o Process jvm2 is still running
```

**Comment by pshipton** [comment]
Note the actual failure is in https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Nightly_testList_2/2/

There is an artifact https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.system_aarch64_mac_Nightly_testList_2/2/system_test_output.tar.gz

4.jvm1.stderr shows
```
[-Xshareclasses persistent cache enabled]
[-Xshareclasses verbose output enabled]
JVMSHRC236I Created shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC246I Attached shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC765I Memory page protection on runtime data, string read-write data and partially filled pages is successfully enabled
JVMJITM001W No more space for AOT code in shared class cache. New AOT code will not be generated.


*** Invalid JIT return address 0000000000000000 in 000000013B8BA408
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_aarch64_mac_Nightly_testList_2/3 - [mac11-aarch64-2](https://openj9-jenkins.osuosl.org/computer/mac11-aarch64-2)
SC_Softmx_JitAot_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_extended.system_aarch64_mac_Nightly_testList_2/3/system_test_output.tar.gz

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_aarch64_mac_Nightly_testList_2/5
SC_Softmx_JitAot_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk18_j9_extended.system_aarch64_mac_Nightly_testList_2/5/system_test_output.tar.gz

**Comment by knn-k** [comment]
Reproduced in 20x Grinder job: https://openj9-jenkins.osuosl.org/job/Grinder/699/ (JDK 18)
I also reproduced the failure locally: 2/50.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_aarch64_mac_Nightly_testList_2/7/

Due to the high failure rate we should exclude this test if it can't be fixed soon.

**Comment by knn-k** [comment]
I opened https://github.com/adoptium/aqa-tests/pull/3446 for excluding this test.

**Comment by knn-k** [comment]
I am not sure, but this is possibly related to #14663.

**Comment by knn-k** [comment]
A fix for #14663 has been merged, but this is still reproducible.
I used the following binary from the latest nightly job for my local testing.
```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc.jenkins.BuildJDK11aarch64macNightly)
Eclipse OpenJ9 VM (build master-194ae711901, JRE 11 Mac OS X aarch64-64-Bit 20220408_32 (JIT enabled, AOT enabled)
OpenJ9   - 194ae711901
OMR      - e6cd80693ff
JCL      - cb81fe5aaf0 based on jdk-11.0.15+8)
```

**Comment by knn-k** [comment]
This failure is still reproducible.

**Comment by knn-k** [comment]
PR https://github.com/eclipse-openj9/openj9/pull/15907 seems to fix this issue.

- Grinder job using a recent nightly build: https://openj9-jenkins.osuosl.org/job/Grinder/1277/ (4 failures in 30 runs)
- Grinder job with PR #15907: https://openj9-jenkins.osuosl.org/job/Grinder/1276/ (No failure in 50 runs)

**Comment by knn-k** [comment]
The test was enabled, and it ran successfully in the latest nightly job: https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_aarch64_mac_Nightly/145/

Closing.
