### ISSUE TITLE
CRIU: Address isCheckpointAllowed bootstrapping issues

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#14642]
Current, if one calls `isCheckpointAllowed` before `isCRIUSupportEnabled` this may result in a linkage error.

To fix this we should rename the native to add `impl` and create a new wrapper `isCheckpointAllowed` that calls `isCRIUSupportEnabled` before calling the native.

Also, in `checkpointJVM` we should use `isCheckpointAllowed` instead of `isCRIUSupportEnabled`

**Comment by tajila** [comment]
@JasonFengJ9 can you take a look at this? Not a big change

**Comment by JasonFengJ9** [comment]
sure, will look into it.
