### ISSUE TITLE
jdk19 failing to start, something in constant pool has been removed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14650]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/252/
All platforms failing to run.
```
02:21:03  Compiling 4 files for BUILD_JIGSAW_TOOLS
02:21:03  Optimizing the exploded image
02:21:03  07:20:59.542 0x16f00   j9jcl.520    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDKnext_x86-64_linux_OpenJDK/openj9/runtime/jcl/common/jclcinit.c:328: ((0 ))
```

https://github.com/eclipse-openj9/openj9/blob/master/runtime/jcl/common/jclcinit.c#L328

Something in the constant pool has been removed.

Changes:
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/05bd71c2e61a79a...218a7229e7067aeca8f774

@JasonFengJ9

**Comment by JasonFengJ9** [comment]
Assigning to @keithc-ca since he is working on https://github.com/eclipse-openj9/openj9/pull/14652
