### ISSUE TITLE
JDK17.0.2.0 CE java/lang/StackWalker/DumpStackTest.java RuntimeException: StackTraceElements mismatch at index 3

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14660]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_0/81/consoleFull`:
```
15:00:46  openjdk version "17.0.2" 2022-01-18
15:00:46  IBM Semeru Runtime Certified Edition 17.0.2.0 (build 17.0.2+8)
15:00:46  Eclipse OpenJ9 VM 17.0.2.0 (build openj9-0.30.1, JRE 17 AIX ppc64-64-Bit Compressed References 20220209_94 (JIT enabled, AOT enabled)
15:00:46  OpenJ9   - 9dccbe076
15:00:46  OMR      - dac962a28
15:00:46  JCL      - 316ae6c0611 based on jdk-17.0.2+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_ppc64_aix&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F94%2Fibm-semeru-certified-debugimage_ppc64_aix_17.0.2.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F94%2Fibm-semeru-certified-testimage_ppc64_aix_17.0.2.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F94%2Fibm-semeru-certified-jdk_ppc64_aix_17.0.2.0.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=na.artifactory.swg-devops&USE_JRE=false&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&OPENJ9_BRANCH=v0.30.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.30.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=162&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&TKG_SHA=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:00:46  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
15:00:46  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops 

15:24:18  TEST: java/lang/StackWalker/DumpStackTest.java

15:24:18  STDERR:
15:24:18  java.lang.RuntimeException: StackTraceElements mismatch at index 3. Expected [DumpStackTest.testLambda(DumpStackTest.java)], but get [DumpStackTest$$Lambda$3/0x0000000022c1bc30.accept(Unknown Source)]
15:24:18  	at DumpStackTest.assertEquals(DumpStackTest.java:227)
15:24:18  	at DumpStackTest.assertStackTrace(DumpStackTest.java:219)
15:24:18  	at DumpStackTest.consumeLambda(DumpStackTest.java:147)
15:24:18  	at DumpStackTest.lambda$testLambda$0(DumpStackTest.java:129)
15:24:18  	at DumpStackTest$$Lambda$3/0x0000000022c1bc30.accept(Unknown Source)
15:24:18  	at DumpStackTest.testLambda(DumpStackTest.java:130)
15:24:18  	at DumpStackTest.main(DumpStackTest.java:45)
15:24:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:24:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
15:24:18  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:24:18  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
15:24:18  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:24:18  	at java.base/java.lang.Thread.run(Thread.java:884)
15:24:18  
15:24:18  JavaTest Message: Test threw exception: java.lang.RuntimeException: StackTraceElements mismatch at index 3. Expected [DumpStackTest.testLambda(DumpStackTest.java)], but get [DumpStackTest$$Lambda$3/0x0000000022c1bc30.accept(Unknown Source)]
15:24:18  JavaTest Message: shutting down test
15:24:18  
15:24:18  STATUS:Failed.`main' threw exception: java.lang.RuntimeException: StackTraceElements mismatch at index 3. Expected [DumpStackTest.testLambda(DumpStackTest.java)], but get [DumpStackTest$$Lambda$3/0x0000000022c1bc30.accept(Unknown Source)]
```

This appears a test re-enabled via https://github.com/eclipse-openj9/openj9/issues/6680

**Comment by pshipton** [comment]
> This appears a test re-enabled via https://github.com/eclipse-openj9/openj9/issues/6680

This is a test mismatch then, the fix https://github.com/eclipse-openj9/openj9/pull/3627 is only merged in 0.31 and later so the test is expected to fail on 17.0.2 / 0.30
