### ISSUE TITLE
CRIU: address bootstraping issue

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#14676]
Some CRIU operations are needed very early

```
	private static boolean criuSupportEnabled = false;

	private static native boolean isCRIUSupportEnabledImpl();

	private static native boolean isCheckpointAllowed();

	private static boolean nativeLoaded = false;

	private static boolean initComplete = false;

       private static synchronized void init() {...}
```

The fact that these are all in the criu module means we need to resort to alternative means to access them. 

These essential APIs should be moved to java.base under `jdk.internal.criu` and we can export this package to openj9.criu

**Comment by tajila** [comment]
FYI @jason-hall This will simplify what we are doing for the env vars as well as th security changes

**Comment by JasonFengJ9** [comment]
> These essential APIs should be moved to java.base under jdk.internal.criu

How about `openj9.internal.criu` since CRIU is an OpenJ9 specific feature?

**Comment by tajila** [comment]
> How about openj9.internal.criu since CRIU is an OpenJ9 specific feature?

Thats fine as well
