### ISSUE TITLE
JDK17 java/nio/MappedByteBuffer/ZeroMap.java - IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14731]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/49/`(`ub18-aarch64-8`):
```
openjdk version "17.0.3" 2022-04-19
IBM Semeru Runtime Open Edition 17.0.3.0-m1a (build 17.0.3+4)
Eclipse OpenJ9 VM 17.0.3.0-m1a (build openj9-0.32.0-m1a, JRE 17 Linux aarch64-64-Bit Compressed References 20220316_127 (JIT enabled, AOT enabled)
OpenJ9   - 6dbe50f27
OMR      - c7a356355
JCL      - db1a51b8bdc based on jdk-17.0.3+4)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_nio_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-testimage_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-jre_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-debugimage_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F127%2Fibm-semeru-open-jdk_aarch64_linux_17.0.3_4_openj9-0.32.0-m1a.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=v0.32.0-release&amp;OPENJ9_BRANCH=v0.32.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.32.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-03-16T04:11:41.030Z] variation: Mode150
[2022-03-16T04:11:41.030Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-03-16T04:17:07.948Z] TEST: java/nio/MappedByteBuffer/ZeroMap.java

[2022-03-16T04:17:07.949Z] STDERR:
[2022-03-16T04:17:07.949Z] java.lang.IllegalArgumentException: bound must be positive
[2022-03-16T04:17:07.949Z] 	at java.base/java.util.Random.nextInt(Random.java:322)
[2022-03-16T04:17:07.949Z] 	at ZeroMap.main(ZeroMap.java:40)
[2022-03-16T04:17:07.949Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-03-16T04:17:07.949Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-03-16T04:17:07.949Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-03-16T04:17:07.949Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-03-16T04:17:07.949Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-03-16T04:17:07.949Z] 	at java.base/java.lang.Thread.run(Thread.java:889)
[2022-03-16T04:17:07.949Z] 
[2022-03-16T04:17:07.949Z] JavaTest Message: Test threw exception: java.lang.IllegalArgumentException: bound must be positive
```

50x grinder - `job/Grinder/21750/` - all passed

**Comment by knn-k** [comment]
No failures in the grinder job above.

**Comment by knn-k** [comment]
I ran java/nio/MappedByteBuffer/ZeroMap.java with JDK 17 on AArch64 Linux 40 times, and got no failures.
https://openj9-jenkins.osuosl.org/job/Grinder/1314/

**Comment by JasonFengJ9** [comment]
Closing as works on later builds.
