### ISSUE TITLE
Internal regression 147224

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14738]
https://github.com/eclipse-openj9/openj9/pull/14688 has apparently caused internal regression 147224. Although the regression is initially found on jdk17, the change is included in the 0.31 release so this is assigned to the 0.31 release assuming the change affects this release as well.

**Comment by tajila** [comment]
@fengxue-IS Please take a look

**Comment by fengxue-IS** [comment]
looking into this

**Comment by fengxue-IS** [comment]
updated internal issue.

**Comment by fengxue-IS** [comment]
opened #14782 #14783
