### ISSUE TITLE
Class verification for Value Types

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#14741]
The same as normal classes, we need to perform verification on Value Types. There was a Pull Request #12858 previously merged to make static and runtime verifiers work on Value Types.  There might be cases that are not covered by #12858.

Currently all the value type tests are running with class verification turned off (by `-Xverify:none` in the command line). Eventually we want to remove `-Xverify:none` in all the value type tests.

**Comment by hangshao0** [comment]
@ehrenjulzert, can you look at this ?

**Comment by hangshao0** [comment]
FYI @ChengJin01 @tajila

**Comment by ehrenjulzert** [comment]
There has been some new changes to the value objects spec which I will have to implement in a future PR

**Comment by ChengJin01** [comment]
@ehrenjulzert, as per your query on the verification constraint at `4.10 Verification of class Files` (mostly related to the runtime verification)  in http://cr.openjdk.java.net/~dlsmith/jep401/jep401-20211220/specs/primitive-classes-jvms.html#jvms-4.10,

It seems there are at least two things you might need to figure out what code should be updated to accommodate new changes in the JVM Spec:
[1] The Verification type hierarchy diagram changed in which case the type `null` is no longer a subtype of all reference types with the further clarification as follows:
```
Standard reference types (field descriptors beginning L) correspond to verification types that use the functor class.

isAssignable(reference, X)   :- isAssignable(oneWord, X).
isAssignable(class(_, _), X) :- isAssignable(reference, X).
isAssignable(arrayOf(_), X)  :- isAssignable(reference, X).
isAssignable(null, X) :- isAssignable(reference, X).

The type null is a subtype of all standard and array reference types. <-------
isAssignable(null, class(_, _)).
isAssignable(null, arrayOf(_)).
```
given `isAssignable(primitive(_,_), X) :- isAssignable(reference, X).` (specifically, a primitive class is a subtype of reference) which is in accordance with the explanation in the JEP401 at https://openjdk.java.net/jeps/401
```
Default values and null
Like the basic primitive types (int, boolean, etc.), declared primitive types do not allow null.
```
which means `null` is not a subtype of a primitive class.


Looking at the code of `isClassCompatible` at https://github.com/eclipse-openj9/openj9/blob/master/runtime/bcverify/vrfyhelp.c:
e.g.
```
IDATA 
isClassCompatible(J9BytecodeVerificationData *verifyData, UDATA sourceClass, UDATA targetClass, IDATA *reasonCode)
{ 
...
	/* NULL is magically compatible */
	if( sourceClass == BCV_BASE_TYPE_NULL ) { <----- no longer correct if the target class is a primitive class
		return (IDATA) TRUE;                                         while the source class is null
	}
```
You need to double-check the whole code in `isClassCompatible` plus all its callers in Verifier to ensure it works with the new change for the `null` type.

[2] The Spec at 4.10.1.6 Type Checking Methods says:
```
For the initial type state of an instance method, we compute the type of this and put it in a list. 
The type of this in the <init> method of Object is Object;
 in other <init> methods, the type of this is uninitializedThis; 
the type of this in an instance method of a primitive class is primitive(N, L), where N is the name of the class containing the method and L is its defining class loader;  <------------- newly added for primitive classes
otherwise, the type of this in an instance method is class(N, L) 
```
 against the code of `buildStackFromMethodSignature`  at https://github.com/eclipse-openj9/openj9/blob/master/runtime/bcverify/rtverify.c:
```
BOOLEAN
buildStackFromMethodSignature( J9BytecodeVerificationData *verifyData, UDATA **stackTopPtr, UDATA *argCount)
{
...
		/* In the <init> method of Object the type of this is Object.  In other <init> methods, the type of this is uninitializedThis */
		if ((J9UTF8_DATA(utf8string)[0] == '<')	&& (J9UTF8_DATA(utf8string)[1] == 'i') && (classIndex != BCV_JAVA_LANG_OBJECT_INDEX)) {
			/* This is <init>, not java/lang/Object */
			PUSH(BCV_SPECIAL_INIT | (classIndex << BCV_CLASS_INDEX_SHIFT));
			isUninitializedThis = TRUE;
		} else {
			PUSH(BCV_GENERIC_OBJECT | (classIndex << BCV_CLASS_INDEX_SHIFT));
		}  <---- code missing for primitive classes
```
My understanding is we might need to add code to handle the case of primitive classes specially  given it should be identified in `isClassCompatible`.

FYI: @DanHeidinga

**Comment by ehrenjulzert** [comment]
@tajila I have gotten some of our value type tests working without `-Xverify:none`, but others are still failing. I suspect the reason the others are failing is because they're all generating VTs using `ValueTypeGenerator.generateValueClass` instead of using the new `value` or `primitive` keywords. Since `ValueTypeGenerator.generateValueClass` doesn't take the new value types spec into account, it may be generating VTs that are in violation of the spec. Do you think it would make sense to keep the `Xverify:none` for those tests?

**Comment by tajila** [comment]
> Do you think it would make sense to keep the Xverify:none for those tests?

Could you fix the VTgenerator to take the new spec into account?

**Comment by ehrenjulzert** [comment]
Sure, should I do that before #15053 is merged or does it not matter?

**Comment by hangshao0** [comment]
There are many cases in `ValueTypeTests` that does not need to use `ValueTypeGenerator.generateValueClass` to generated VTs anymore. as the latest javac is already able produce value type (with key word value) and primitive value type (with key word primitive). For example:

https://github.com/eclipse-openj9/openj9/blob/3c82c45fd6053436c6f957015b909b39f0687b38/test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java#L282-L288

can be replaced with:

```
primitive class Point2D {
  int x;
  int y;
  /* other methods like constructor and getter */
}

value class Point2D {
   int x;
   int y;
   /* other methods like constructor and getter */
}
```

Fixing/re-writing the tests can be done separately from https://github.com/eclipse-openj9/openj9/pull/15053.

**Comment by ehrenjulzert** [comment]
One of the ValueTypeTests is failing with verification on because it is throwing a `ClassFormatError` instead of a `VerifyError`. The test generates a value class with synchronized methods that are not static, and then checks if the verifier throws an error. The code for the test is as follows:
```
@Test(priority=1, expectedExceptions=VerifyError.class)
static public void testValueTypeHasSychMethods() throws Throwable {
	String fields[] = {"longField:J"};
	Class valueClass = ValueTypeGenerator.generateIllegalValueClassWithSychMethods("testValueTypeHasSychMethods", fields);
}
```


I don't see anything in the spec specifying which error we need to be throwing in this case, so would it be acceptable to fix this by simply changing the expected result to `ClassFormatError`?

**Comment by hangshao0** [comment]
What is the type of error thrown by RI ?

**Comment by ehrenjulzert** [comment]
It looks like the RI throws a `ClassFormatError` as well

**Comment by ehrenjulzert** [comment]
Once #15542 is merged this issue can be closed

**Comment by hangshao0** [comment]
Closing this as https://github.com/eclipse-openj9/openj9/pull/15542 is merged.
