### ISSUE TITLE
ub18-x86 and ub20-x86 core_pattern problems

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14770]
i.e. https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly_testList_1/232/
```
 [ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.29727.
 [ERR] 
 [ERR] JVMDUMP012E Error in System dump: The core file created by child process with pid = 29727 was not found. Expected to find core file with name "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/output_1648105913688/cmdLineTester_GCCheck_0/core"
```

@AdamBrousseau @vsebe

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_extended.functional_x86-64_linux_Nightly_testList_1/19/

**Comment by AdamBrousseau** [comment]
/proc/sys/kernel/core_pattern
/etc/sysctl.conf
disable apport

- [ ] ub18-390-1
- [ ] ub18-390-2
- [ ] ub18-ppcle-1
- [ ] ub18-ppcle-2
- [ ] ub18-x86-1
- [ ] ub18-x86-2
- [ ] ub20-390-1
- [ ] ub20-390-2
- [ ] ub20-aarch64-1
- [ ] ub20-aarch64-2
- [ ] ub20-x86-1
