### ISSUE TITLE
Reducing memory footprint by disclaiming AOT memory after load

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9#14792]
During a warm run, once the JIT detects that it has exited start-up it will disclaim the AOT region of the shared class cache to reduce memory footprint, since the methods of that region will already have been loaded into the code cache of the JVM. It is possible to reduce the footprint after load, possibly by issuing another disclaim a few minutes after load.

**Comment by cjjdespres** [comment]
Attn @mpirvu.

**Comment by cjjdespres** [comment]
Is the entire AOT region loaded and then disclaimed at start-up? If so then I assume the later disclaim will be for other portions of the SCC that have been loaded subsequently.

**Comment by hangshao0** [comment]
> Is the entire AOT region loaded and then disclaimed at start-up?  If so then I assume the later disclaim will be for other portions of the SCC that have been loaded subsequently.

The AOT are stored together (in mix) with class metadata. They are disclaimed together once the start-up phase is over. The class metadata is used when the class is loaded, but we expect most loading happen in the start-up phase. 

Is there any statistics on how much memory an additional disclaim could save ?

**Comment by cjjdespres** [comment]
@mpirvu Was the layering of the shared class cache you referred to the "supercache list" in the cache map that is dealt with in the current

https://github.com/eclipse-openj9/openj9/blob/4d7ae0972804b296f1613d2472451949b62e0fbd/runtime/shared_common/CacheMap.cpp#L231-L246

I suppose I could use that (or something like it) in `jitStateLogic` to perform a second disclaim without invoking the full phase change code. Are there particular circumstances you had in mind where this would come up that I could use to test the effect of my changes?

**Comment by hangshao0** [comment]
`SH_CacheMap:: _ccHead` is the top layer shared cache, which is readable and writable to the current JVM. `ccToUse->getNext()` gives you a lower layer shared cache. which is read only.

**Comment by mpirvu** [comment]
Yes,  probably the trigger should stay in the jitStateLogic. IIRC for the trigger after startup we have a VM callback. 
I'll have to revisit the code.
I don't have a good idea for when we should trigger the second reclaim. Time alone is not good because the JVM could stay idle for a long time. Maybe time spent in rampup, steady state and deep-steady state.

**Comment by mpirvu** [comment]
`void jvmPhaseChange(J9JavaVM* vm, UDATA phase)` is the callback used when JVM exits start-up.
This calls 
```
j9shr_jvmPhaseChange(J9VMThread *currentThread, UDATA phase)
{
	if (J9VM_PHASE_NOT_STARTUP == phase) {
		J9JavaVM* vm = currentThread->javaVM;

		/* OpenJ9 issue; https://github.com/eclipse-openj9/openj9/issues/3743
		 * GC decides whether to calls vm->sharedClassConfig->storeGCHints() to store the GC hints into the shared cache. */
		storeStartupHintsToSharedCache(currentThread);
		if (J9_ARE_NO_BITS_SET(vm->sharedClassConfig->runtimeFlags, J9SHR_RUNTIMEFLAG_MPROTECT_PARTIAL_PAGES_ON_STARTUP)) {
			((SH_CacheMap*)vm->sharedClassConfig->sharedClassCache)->protectPartiallyFilledPages(currentThread);
		}
		((SH_CacheMap*)vm->sharedClassConfig->sharedClassCache)->dontNeedMetadata(currentThread);
	}
	return;
}
```

**Comment by cjjdespres** [comment]
If time in individual phases is important, perhaps the time at which phase changes occur could be tracked in `J9JavaVM` and updated in the `jvmPhaseChange` functions, to be used by `jitStateLogic`.

**Comment by mpirvu** [comment]
It at all possible I would avoid adding new fields to J9JavaVM that are not going to be used when the JIT is off. Maybe jitConfig is a better place for that, since it is accessible by both the VM and the JIT, but only initialized if JIT is enabled.
If data does not need to be accessed by VM, then compInfo is a better place.

**Comment by cjjdespres** [comment]
Sure. I thought that it might be convenient to have `jvmPhaseChange` set that time when it's called, but I'm not sure if `TR::CompilationInfo` is accessible in `vmphases.c`. If not, then the phase change time could live in a static variable in `HookedByTheJIT`, since it's only relevant there (indeed only in `jitStateLogic`).

**Comment by cjjdespres** [comment]
Oh, sorry, I didn't even notice that it was a `.c` file

**Comment by cjjdespres** [comment]
Just to record what we talked about on Monday: one idea is to have a new JVM phase beyond `J9VM_PHASE_NOT_STARTUP` that the JVM would temporarily enter. This would be used to prompt `j9shr_jvmPhaseChange` to call `((SH_CacheMap*)vm->sharedClassConfig->sharedClassCache)->dontNeedMetadata(currentThread)` again (after setting `_metadataReleased` to `false` in the cache map) in order to disclaim the SCC again.
