### ISSUE TITLE
win2012-x86-2 and win2012-x86-7 are out of space

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14829]
@AdamBrousseau 

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_0/237/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_1/237/
```
There is 0 Mb free

Test machine has only 0 Mb free on drive containing F:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_1/aqa-tests/\TKG\output_16487405435570\DaaLoadTest_all_5m_0.
```

**Comment by AdamBrousseau** [comment]
2,3,7 look fine now.
All online that should be.
Please reopen if there's still a problem.

**Comment by pshipton** [comment]
I think it's https://github.com/adoptium/STF/pull/125#issuecomment-1085929989

**Comment by pshipton** [comment]
Closing as the problem in STF was reverted.
