### ISSUE TITLE
OpenJDK java/foreign/TestUnsupportedPlatform failing on jdk17, jdk18 aix, plinux, zlinux

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#14828]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_s390x_linux_Nightly/31/
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_ppc64le_linux_Nightly/32/
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_ppc64_aix_Nightly/32/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Nightly/193
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/191
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/188
jdk_foreign_0, jdk_foreign_1
java/foreign/TestUnsupportedPlatform.java
```
01:44:21  ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
01:44:21  REASON: User specified action: run testng/othervm --enable-native-access=ALL-UNNAMED TestUnsupportedPlatform 
01:44:21  TIME:   0.889 seconds
01:44:21  messages:
01:44:21  command: testng --enable-native-access=ALL-UNNAMED TestUnsupportedPlatform
01:44:21  reason: User specified action: run testng/othervm --enable-native-access=ALL-UNNAMED TestUnsupportedPlatform 
01:44:21  Mode: othervm [/othervm specified]
01:44:21  Additional options from @modules: --add-modules jdk.incubator.foreign --add-exports jdk.incubator.foreign/jdk.internal.foreign=ALL-UNNAMED
01:44:21  elapsed time (seconds): 0.889
01:44:21  configuration:
01:44:21  Boot Layer
01:44:21    add modules: jdk.incubator.foreign                      
01:44:21    add exports: jdk.incubator.foreign/jdk.internal.foreign ALL-UNNAMED
01:44:21  
01:44:21  STDOUT:
01:44:21  test TestUnsupportedPlatform.testNoInitialization(): failure
01:44:21  org.testng.TestException: 
01:44:21  Method TestUnsupportedPlatform.testNoInitialization()[pri:0, instance:TestUnsupportedPlatform@8fe597f0] should have thrown an exception of type class java.lang.ExceptionInInitializerError
01:44:21  	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
01:44:21  	at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:747)
01:44:21  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)
01:44:21  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
```

https://github.com/ibmruntimes/openj9-openjdk-jdk17/compare/200f904391...aee133f4498
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/23

https://github.com/ibmruntimes/openj9-openjdk-jdk18/compare/e5e014df7c9...61e2dba74c9
https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/3

@tajila @ChengJin01

**Comment by ChengJin01** [comment]
Please note the test is only supported on 32-bit platforms, which should be disabled on all 64-bit platforms.

https://github.com/ibmruntimes/openj9-openjdk-jdk18/blob/openj9/test/jdk/java/foreign/TestUnsupportedPlatform.java
https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9/test/jdk/java/foreign/TestUnsupportedPlatform.java
```
/*
 * @test
 * @requires !(((os.arch == "amd64" | os.arch == "x86_64") & sun.arch.data.model == "64") | os.arch == "aarch64") <---
 * @modules jdk.incubator.foreign/jdk.internal.foreign
 * @run testng/othervm --enable-native-access=ALL-UNNAMED TestUnsupportedPlatform
 */

import jdk.incubator.foreign.CLinker;
import org.testng.annotations.Test;

import static org.testng.Assert.assertNull;

// tests run on 32-bit platforms, which are currently not supported
public class TestUnsupportedPlatform {

    @Test(expectedExceptions = ExceptionInInitializerError.class)
    public void testNoInitialization() {
        CLinker.systemCLinker(); // trigger initialization
    }

}
```
Given the `requires` condition in the test already excludes `x86_64` and `aarch64` (which is why it never occurs on these platforms), we should totally exclude the test on JDK17 & 18 via exclude files at `https://github.com/adoptium/aqa-tests/tree/master/openjdk/excludes`.
