### ISSUE TITLE
VarHandleValues.java:40: error: class is not allowed to extend sealed class: VarHandle (as it is not listed in its permits clause)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14839]
Latest `valhalla/lworld` update caused following build failure:
```
/Users/ivm/ext-valhalla/0404/testbuild/build/macosx-x86_64-server-release/support/gensrc/java.base/java/lang/invoke/VarHandleValues.java:40: error: class is not allowed to extend sealed class: VarHandle (as it is not listed in its permits clause)
    static sealed class FieldInstanceReadOnly extends VarHandle {
                  ^
/Users/ivm/ext-valhalla/0404/testbuild/build/macosx-x86_64-server-release/support/gensrc/java.base/java/lang/invoke/VarHandleValues.java:283: error: class is not allowed to extend sealed class: VarHandle (as it is not listed in its permits clause)
    static sealed class FieldStaticReadOnly extends VarHandle {
                  ^
/Users/ivm/ext-valhalla/0404/testbuild/build/macosx-x86_64-server-release/support/gensrc/java.base/java/lang/invoke/VarHandleValues.java:528: error: class is not allowed to extend sealed class: VarHandle (as it is not listed in its permits clause)
    static final class Array extends VarHandle {
                 ^
Note: Some input files additionally use or override a deprecated API that is marked for removal.
Note: Some input files additionally use unchecked or unsafe operations.
3 errors
```

fyi @tajila @hangshao0 

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/commit/1f85f232df6b823eba3d3dda4c814ca7fe836d5b

**Comment by hangshao0** [comment]
So [this](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/651655b7082f5eec499645ff76d4f145e2b7b021) openjdk next commit has changed `VarHandle` to sealed class. Jdknext does not have `VarHandleValues`, so 
`VarHandleValues.Array,VarHandleValues.FieldInstanceReadOnly,VarHandleValues.FieldStaticReadOnly`
are not added to the permits class list in `VarHandle.java` by this change. 

Currently OpenJDK Valhalla repo has not accept this change yet. I believe when openJDK Valhalla repo accept this change, they will add the above `VarHandleValues` classes into the permits list to make Valhalla build work.

**Comment by hangshao0** [comment]
@JasonFengJ9 Can you try https://github.com/hangshao0/openj9-openjdk-jdk.valuetypes/commit/d3e455f8b26818413d6306b319822394ef16f7db to see if this failure is fixed ?

**Comment by JasonFengJ9** [comment]
Yeah, that works, pls create a PR.

**Comment by hangshao0** [comment]
PR is here: https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/1

**Comment by JasonFengJ9** [comment]
Merged. Closing..
