### ISSUE TITLE
cmdLineTester_pltest_osx failed with JDK11.0.14.1 on Mac12

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#14867]
cmdLineTester_pltest_osx_0 test failed with JDK11.0.14.1 on Mac12 only
- machine: mac12x64rt15.rtp.raleigh.ibm.com
- OPENJ9_BRANCH=v0.30.1-release
- internal/Grinder/22374
```
01:43:27.436  openjdk version "11.0.14.1" 2022-02-08
01:43:27.436  IBM Semeru Runtime Open Edition 11.0.14.1 (build 11.0.14.1+1)
01:43:27.436  Eclipse OpenJ9 VM 11.0.14.1 (build openj9-0.30.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20220209_310 (JIT enabled, AOT enabled)
01:43:27.436  OpenJ9   - 9dccbe076
01:43:27.436  OMR      - 56c3376ba
01:43:27.436  JCL      - 5c423dacd0 based on jdk-11.0.14.1+1)
```

```
 [ERR] 1: j9sysinfo_test_sysinfo_set_limit_ADDRESS_SPACE
 [ERR] 	/Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/openj9/runtime/tests/port/si.c line  598: j9sysinfo_set_limit set ADDRESS_SPACE soft max FAILED
 [ERR] 
 [ERR] 		LastErrorNumber: -113
 [ERR] 		LastErrorMessage: Invalid argument
 [ERR] 
>> Success condition was not found: [Output match: ALL TESTS COMPLETED AND PASSED]
>> Failure condition was not found: [Output match: ASSERTION FAILED]
```

**Comment by llxia** [comment]
Grinder with nightly Grinder/22392/ (waiting for machine)

**Comment by jdekonin** [comment]
```
$ ulimit -v
unlimited
$ ulimit -v 300000
-bash: ulimit: virtual memory: cannot modify limit: Invalid argument
```

But I can do this on a MacOS11 system...

`ulimit: setrlimit failed: invalid argument` is the error as an admin account

**Comment by pshipton** [comment]
I logged in and tried different values, but nothing worked. You can't set the hard limit or soft limit to bigger or smaller values. 

I don't find any code in OpenJ9 that modifies the address space limit. I could just remove the OpenJ9 port library test on mac, unless somebody has other ideas. @keithc-ca ?

**Comment by keithc-ca** [comment]
I don't find any uses of `xxxsysinfo_set_limit(XXXPORT_RESOURCE_ADDRESS_SPACE)` besides in tests; perhaps we should just remove support for modifying the virtual memory limit (and the related tests)?

**Comment by pshipton** [comment]
I'll open a PR to remove the OpenJ9 test, but I won't do anything on the OMR side for now. If it comes up there, perhaps somebody else will figure something out.
