### ISSUE TITLE
A question about the remainder operation

### ISSUE THREAD

**Issue by YuanWangC** [eclipse-openj9/openj9#14874]
##### Description:

When I use the following test case for the remainder operation, the result of the calculation is `0.0`, while the result of HotSpot is `2.53E-321`. I would like to know what is the reason for this situation? Is this a special handling of numerical computation boundaries by OpenJ9?

##### Environment:

```
Ubuntu 18.04 x86_64
```

###### jdk8:

```
openjdk version "1.8.0_332-internal"
OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_02_17_10_23-b00)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 301202f49f based on jdk8u332-b02)
```

###### jdk11:

```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 11 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 24e7209ed4 based on jdk-11.0.15+1)
```

##### Testcase:

```java
public class MyJVMTest{
   static void testWithPrint() {
            double a = Double.longBitsToDouble(0x7FE0000000000000L);
            double b = Double.longBitsToDouble(0x000000000003FFFFL);
            double mod = a % b;
            System.out.println(mod);
    }
    public static void main(String[] args) {
        testWithPrint();
    }
}
```

##### output:

```
0.0
```

##### Expected output:

```
2.53E-321
```

**Comment by pshipton** [comment]
I also tried `System.out.println(Long.toHexString(Double.doubleToLongBits(mod)));` which shows `0` as well, so it's not related to printing the value.
The same results occur with -Xint.
This is not a recent regression, the earliest version of OpenJ9 0.23 has the same behaviour.

@tajila

**Comment by tajila** [comment]
@dnakamura Can you please take a look at this

**Comment by dnakamura** [comment]
It looks like we explicitly return 0 when the divisor is subnormal. https://github.com/eclipse-openj9/openj9/blob/52f4f77546a8ab2b0f8aeac69f08b234e922498f/runtime/util/fltrem.c#L76-L87  I'm not entirely sure why we do. Nothing in the vm spec would indicate this behavior, and we don't do it for single precision floats. In addition it doesn't match the behavior of the jit generated code (ie running with `-Xjit:count=0` yields the expected results. Currently running tests with relevant code removed.

**Comment by pshipton** [comment]
> Currently running tests with relevant code removed.

Those tests should include sanity.openjdk

**Comment by keithc-ca** [comment]
I double-checked the expected remainder using `BigInteger`:
```
	public static void main(String[] args) {
		double a = Double.longBitsToDouble(0x7FE0000000000000L);
		double b = Double.longBitsToDouble(0x000000000003FFFFL);

		showRemainder(a, b);

		// a = 2^1023, b = 0x3FFFF * 2^-(1022+52)
		BigInteger bigA = BigInteger.ONE.shiftLeft(1023).shiftLeft(1022 + 52);
		BigInteger bigB = BigInteger.valueOf(0x3FFFF);

		System.out.format("big: %s%n   %% %s%n   = %s%n", bigA, bigB, bigA.mod(bigB));
	}

	private static void showDouble(String prefix, double x) {
		System.out.format("%s: %a = %g = 0x%016x%n", prefix, x, x, Double.doubleToRawLongBits(x));
	}

	private static void showRemainder(double a, double b) {
		double mod = a % b;

		showDouble("a", a);
		showDouble("b", b);
		showDouble("%", mod);
		System.out.println();
	}
```
