### ISSUE TITLE
The Try-Catch statement seems to affect the IllegalStateException object calling the getCause method

### ISSUE THREAD

**Issue by YuanWangC** [eclipse-openj9/openj9#14873]
##### Description:

I use the try-catch statement to catch an `IllegalStateException`  object named `ise`. Then I call the `getCause` method to perform a Cause check and find that it cannot find the Cause object (Testcase1 below). However, HotSpot returned t2.
And when I define the Cause object of `ise` directly and then use `getCause` to check it, I find that it can find the Cause object (Testcase2 below).

It seems that the try-catch statement has an effect on the `IllegalStateException` object calling the `getCause` method, is this an issue with the implementation of OpenJ9?

By the way, if you need more information about this, please contact me.

##### Environment：

```
Ubuntu 18.04 x86_64
```

###### jdk8:

```
openjdk version "1.8.0_332-internal"
OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_02_17_10_23-b00)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 301202f49f based on jdk8u332-b02)
```

###### jdk11:

```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 11 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 24e7209ed4 based on jdk-11.0.15+1)
```

##### Testcase1:

```java
import java.io.*;
import java.util.*;
public class MyJVMTest{
    static void initCausePlumbing() {
        Throwable t2 = new Throwable("message", new Throwable());
        try {
            t2.initCause(new Throwable());
        } catch (IllegalStateException ise) {
            System.out.println(ise.getCause().equals(t2));
        }
    }
    public static void main(String[] args) {
        initCausePlumbing();
    }
}
```

##### output1:

```
Exception in thread "main" java.lang.NullPointerException at MyJVMTest.initCausePlumbing(MyJVMTest.java:9) at MyJVMTest.main(MyJVMTest.java:13)
```

##### Expected output1:

```
true
```

##### Testcase2:

```java
import java.io.*;
import java.util.*;
public class MyJVMTest{
    static void initCausePlumbing() {
        Throwable t2 = new Throwable("message", new Throwable());
        IllegalStateException ise = new IllegalStateException(t2);
        System.out.println(ise.getCause().equals(t2));
    }
    public static void main(String[] args) {
        initCausePlumbing();
    }
}
```

##### output2:

```
true
```

**Comment by pshipton** [comment]
This is just a misunderstanding of how it works. In the first test case the IllegalStateException is as follows. It doesn't have a cause, nor should it, so the NPE is expected. t2 has a cause when created, but t2 is not the caught exception.
```
java.lang.IllegalStateException: Cause already initialized
	at java.lang.Throwable.initCause(Throwable.java:381)
	at Cause.initCausePlumbing(Cause.java:7)
	at Cause.main(Cause.java:14)
```

**Comment by pshipton** [comment]
Note when I recreated the test case I renamed it from `MyJVMTest` to `Cause`, which is why you see `Cause.main` in the stack trace in the previous comment.

**Comment by pshipton** [comment]
Sorry, right, this is a difference in behavior from Hotspot which can be corrected.

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/pull/14877 to fix it.
