### ISSUE TITLE
The loop in DsaStackFrame.findSfxm() needs to be improved.

### ISSUE THREAD

**Issue by Niwedita-Rani** [eclipse-openj9/openj9#14908]
There is a case in which user is looking for help to understand an OutofMemoryError, followed by a GPF crash. They have collected dumps, but there are some issues with opening the dumps in tools like Memory Analyzer, jdpmview and other tools that use the DTFJ API.

All the dumps requested by IEATDUMP - after the OOM occurs - ended with a return code 2, reason code 4, which means:

```
Return code     Reason code 
00000004	00000002	Meaning: Contention detected when attempting to set tasks in the address space non-dispatchable.
Action: Data in dump may be inconsistent. Reissue IEATDUMP.
```

The sequence of events for this particular issue is like this: 

**At runtime:** 

- IEATDUMP is issued.
- A TQE that is used by the dumping process expires *before* the dump is complete (because we have a lot of private storage to dump in this case, and it simply takes a long wallclock time to complete).
- The TCBs in the dumped address space are forced to be MVS dispatchable again, so they may run before the dump completes.
- The IEATDUMP process finally ends and a complete dump is written. Because we know that we forced the TCBs to be dispatchable, and they could have run, and could have mutated storage we are interested in, the IEATDUMP service ends with the Rc2, Reas4, which tells is that "Data in the dump may be inconsistent'

 
**After runtime, during diagnosis, using the IEATDUMP**

- Any code that uses the DTFJ API (e.g. jdpmview, MAT, service store, polyxena) to open this dump loops in com/ibm/j9ddr/corereaders/tdump/zebedee/le/DsaStackFrame.findSfxm
- This is probably because the TCB/pthread being looked at was inflight after being redispatched by MVS after the TQE expiry, so the expected 'frozen in time' stack frame data is now not walkable without this infinite loop in the diagnostic code. 

We are requesting for a fix to the j9ddr corereader code that will tolerate gracefully the state of the native stack found for that thread in the dump, or provide some kind of adhoc patch to the dump itself that will allow the dump to be initialized by tools that use DTFJ.

**Comment by pshipton** [comment]
@tajila fyi

**Comment by dajc64ibm** [comment]
If we can get a patch for this suitable for deployment with the IBM JDK it would be very useful, so we can continue diagnosis on the customer memory issue. Thanks, Dave Clarke (CICS L3)

**Comment by dajc64ibm** [comment]
Hi - any news about this? Thanks, Dave Clarke (CICS L3)

**Comment by keithc-ca** [comment]
I am testing my solution to this.
