### ISSUE TITLE
JDK8 Windows MauveMultiThrdLoad_special_5m_0_FAILED - **POSSIBLE HANG DETECTED**

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#14907]
Failure link
------------

From an internal build `job/Test_openjdk8_j9_special.system_x86-32_windows_testList_1/182/tapResults/`(`win16x64rt2-10`):
```
openjdk version "1.8.0_332"
IBM Semeru Runtime Open Edition (build 1.8.0_332-b06)
Eclipse OpenJ9 VM (build openj9-0.32.0-m2, JRE 1.8.0 Windows Server 2016 x86-32-Bit 20220408_344 (JIT enabled, AOT enabled)
OpenJ9   - 959fc5030
OMR      - ab24b6666
JCL      - efe20b8440 based on jdk8u332-b06)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_j9_special.system_x86-32_windows&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-32_windows&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F344%2Fibm-semeru-open-debugimage_x86-32_windows_8u332b06_openj9-0.32.0-m2.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F344%2Fibm-semeru-open-jre_x86-32_windows_8u332b06_openj9-0.32.0-m2.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F344%2Fibm-semeru-open-jdk_x86-32_windows_8u332b06_openj9-0.32.0-m2.zip+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-windows-x86-32-openj9%2F344%2Fibm-semeru-open-testimage_x86-32_windows_8u332b06_openj9-0.32.0-m2.zip&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&RELEASE_TAG=v0.32.0-release&OPENJ9_BRANCH=v0.32.0-release&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=v0.32.0-release&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=195&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test MauveMultiThrdLoad_special_5m_0 ...
===============================================
MauveMultiThrdLoad_special_5m_0 Start Time: Fri Apr  8 15:18:10 2022 Epoch Time (ms): 1649445490009
variation: Mode101
JVM_OPTIONS:  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs 

LT  15:37:26.164 - Completed 100.0%. Number of tests started=2110844 (+0)
LT  15:37:27.695 - **POSSIBLE HANG DETECTED**
LT  15:37:32.726 - **POSSIBLE HANG DETECTED**

LT  17:16:04.023 - **POSSIBLE HANG DETECTED**
LT  17:16:06.210 - Completed 100.0%. Number of tests started=2110844 (+0)
LT  17:16:09.053 - **POSSIBLE HANG DETECTED**
LT  17:16:14.083 - **POSSIBLE HANG DETECTED**
LT  17:16:15.036 - Thread completed. Suite=0 thread=1
LT  17:16:15.036 - Thread completed. Suite=0 thread=5
LT  17:16:15.036 - Thread completed. Suite=0 thread=2
LT  17:16:15.036 - Thread completed. Suite=0 thread=3
LT  17:16:15.036 - Thread completed. Suite=0 thread=4
LT  17:16:15.036 - Thread completed. Suite=0 thread=6
LT  17:16:26.110 - Completed 100.0%. Number of tests started=2110844 (+0)
LT  17:16:46.127 - Completed 100.0%. Number of tests started=2110844 (+0)
STF 17:16:53.016 - **FAILED** Process LT  has timed out
STF 17:16:53.016 - **FAILED** Process LT  has hung
STF 17:16:53.016 - Collecting dumps for: LT 

LT  17:21:43.865 - Thread completed. Suite=0 thread=0
LT  17:23:03.765 - Test stopped due to reaching runtime limit
LT  17:23:03.765 - Load test completed
LT  17:23:03.781 -   Ran     : 2110844
LT  17:23:03.781 -   Passed  : 2110844
LT  17:23:03.781 -   Failed  : 0
LT  17:23:03.781 -   Result  : PASSED
STF 19:18:13.078 - Monitoring Report Summary:
STF 19:18:13.078 -   o Process LT  has timed out
STF 19:18:13.079 - Killing processes: LT 
STF 19:18:13.079 -   o Process LT  pid 5896 is not running
**FAILED** at step 1 (Run Mauve load test). Expected return value=0 Actual=1 at C:/Users/jenkins/workspace/Test_openjdk8_j9_special.system_x86-32_windows_testList_1/aqa-tests/\TKG\output_16494372853476\MauveMultiThrdLoad_special_5m_0/20220408-151813-MauveMultiThrdLoadTrc/execute.pl line 96.
STF 19:21:34.292 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 19:21:34.293 - 
STF 19:21:34.293 - ====================   T E A R D O W N   ====================
STF 19:21:34.293 - Running teardown: perl C:/Users/jenkins/workspace/Test_openjdk8_j9_special.system_x86-32_windows_testList_1/aqa-tests/\TKG\output_16494372853476\MauveMultiThrdLoad_special_5m_0/20220408-151813-MauveMultiThrdLoadTrc/tearDown.pl
STF 19:21:34.675 - TEARDOWN stage completed
STF 19:21:34.717 - 
STF 19:21:34.718 - =====================   R E S U L T S   =====================
STF 19:21:34.718 - Stage results:
STF 19:21:34.718 -   setUp:     pass
STF 19:21:34.718 -   execute:  *fail*
STF 19:21:34.718 -   teardown:  pass
STF 19:21:34.718 - 
STF 19:21:34.718 - Overall result: **FAILED**

MauveMultiThrdLoad_special_5m_0_FAILED
```
50x grinder - `job/Grinder/22751/` - passed

**Comment by pshipton** [comment]
Likely this issue and https://github.com/eclipse-openj9/openj9/issues/14887 are a dup of https://github.com/eclipse-openj9/openj9/issues/11868

**Comment by pshipton** [comment]
The grinder passed

**Comment by JasonFengJ9** [comment]
Closing as dup of https://github.com/eclipse-openj9/openj9/issues/11868
