### ISSUE TITLE
Invalid ConstantPool on JDK 17.0.2.8 when instrumenting a class with -Xshare:off JVM option

### ISSUE THREAD

**Issue by erichhochmuth** [eclipse-openj9/openj9#14904]
Java -version output
--------------------
openjdk version "17.0.2" 2022-01-18
IBM Semeru Runtime Open Edition 17.0.2.0 (build 17.0.2+8)
Eclipse OpenJ9 VM 17.0.2.0 (build openj9-0.30.0, JRE 17 Linux amd64-64-Bit Compressed References 20220128_115 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 64cd399ca28 based on jdk-17.0.2+8)

Stack from:
openjdk version "17.0.3-internal" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc..hostdir)
Eclipse OpenJ9 VM (build master-eb8be6913, JRE 17 Linux amd64-64-Bit Compressed References 20220411_000000 (JIT enabled, AOT enabled)
OpenJ9   - eb8be6913
OMR      - 48d41b458
JCL      - aff77b6333b based on jdk-17.0.3+5)

Summary of problem
------------------
When instrumenting a class (in our case javax.management.ObjectName) and add a MethodHandle to the ConstantPool in the ClassFileLoadHook, it appears that the original ConstantPool is used while the Attributes are used from the instrumented class.

This results in a crash and the following assertion:
> 21:00:26.027 0x21f00j9bcu(j9vm).129    *   ** ASSERTION FAILED ** at /root/hostdir/openj9/runtime/bcutil/ClassFileOracle.cpp:2720: ((15 == _classFile->constantPool[cpIndex].tag))

The classfile has the original constantPoolCount:
`(gdb) print *_classFile
$56 = {magic = 3405691582, minorVersion = 0, majorVersion = 61, accessFlags = 33, j9Flags = 0, thisClass = 1, superClass = 381, 
  constantPoolCount = 749, interfacesCount = 2, fieldsCount = 19, methodsCount = 50, attributesCount = 5, firstUTF8CPIndex = 2, 
  lastUTF8CPIndex = 748, firstNATCPIndex = 8, constantPool = 0x7ffff14a81e0, interfaces = 0x7ffff14aff56, fields = 0x7ffff14aff60, 
  methods = 0x7ffff14b02c0, attributes = 0x7ffff14b7328, classFileSize = 24511}
`

While the BoostrapMethods attribute points to the ConstantPool index of the added MethodHandle:
`(gdb) print *_bootstrapMethodsAttribute->bootstrapMethods
$57 = {bootstrapMethodIndex = 773, numberOfBootstrapArguments = 1, bootstrapArguments = 0x7ffff14b74b8}
`

Iff necessary, we can create a reproducer. Same code works when class data sharing is not disabled (and other JVMs).

Diagnostic files
----------------
Stacktrace from gdb
[stacktrace.txt](https://github.com/ibmruntimes/openj9-openjdk-jdk17/files/8468093/stacktrace.txt)

**Comment by pshipton** [comment]
@tajila fyi

**Comment by pshipton** [comment]
I don't understand what "Same code works when class data sharing is not disabled" means.

**Comment by pshipton** [comment]
Hm, I see `-Xshare:off` in the title now.

**Comment by erichhochmuth** [comment]
Was able to reproduce the issue on 17.0.1.0, 11.0.14.1 and 11.0.12.0 on Linux x64.

**Comment by erichhochmuth** [comment]
The problem can not be reproduced on 8u302 / 8u322.

**Comment by tajila** [comment]
@hangshao0 Can you please take a look at this

**Comment by hangshao0** [comment]
Can you provide a reproducer ? @erichhochmuth

**Comment by erichhochmuth** [comment]
Unfortunately it is not as easy as to create a dummy jvmti agent that replaces the class in the ClassFileLoadHook and load the class in the VMInit callback. May take me a day or two to create a reproducer.

**Comment by erichhochmuth** [comment]
I was not able to reproduce the issue with a simple jvmti agent. Even if I initialize the ObjectName class in a static initializer I can't recreate the crash. Since we have a workaround for the issue, feel free to resolve the bug. If we run into it again we'll invest more time into a reproducer.
