### ISSUE TITLE
jstacktrace trace action no longer works

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#14956]
Internal ref 147394

Java -version output
--------------------
```
$ jdk8u322-b06-openj9-0.30.0/bin/java -version
openjdk version "1.8.0_322"
IBM Semeru Runtime Open Edition (build 1.8.0_322-b06)
Eclipse OpenJ9 VM (build openj9-0.30.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220128_306 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - c1d9a7af7c based on jdk8u322-b06)
```

Summary of problem
------------------
Consider this simple class:
```
public class fact {

    public static void main(String[] args) {
        int result = factorial(5);

        System.out.println(result);
    }

    public static int factorial(int k) {
        if (k <= 1) {
            return 1;
        } else {
            return k * factorial(k - 1);
        }
    }

}
```

Running this with version 0.27.0 with `-Xtrace:'print=mt,trigger=method{*.factorial,jstacktrace}' -showversion` yields:
```
openjdk version "1.8.0_302-internal"
OpenJDK Runtime Environment (build 1.8.0_302-internal-_2021_07_24_21_06-b00)
Eclipse OpenJ9 VM (build openj9-0.27.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210724_9 (JIT disabled, AOT disabled)
OpenJ9   - 1851b00
OMR      - 9db1c87
JCL      - de702c3 based on jdk8u302-b08)

14:35:41.425*0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:35:41.425 0x16f00       j9trc_aux.0        - jstacktrace:
14:35:41.425 0x16f00       j9trc_aux.1        - [1] fact.factorial (fact.java:36)
14:35:41.425 0x16f00       j9trc_aux.1        - [2] fact.main (fact.java:30)
14:35:41.425 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00       j9trc_aux.0        - jstacktrace:
14:35:41.426 0x16f00       j9trc_aux.1        - [1] fact.factorial (fact.java:36)
14:35:41.426 0x16f00       j9trc_aux.1        - [2] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [3] fact.main (fact.java:30)
14:35:41.426 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00       j9trc_aux.0        - jstacktrace:
14:35:41.426 0x16f00       j9trc_aux.1        - [1] fact.factorial (fact.java:36)
14:35:41.426 0x16f00       j9trc_aux.1        - [2] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [3] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [4] fact.main (fact.java:30)
14:35:41.426 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00       j9trc_aux.0        - jstacktrace:
14:35:41.426 0x16f00       j9trc_aux.1        - [1] fact.factorial (fact.java:36)
14:35:41.426 0x16f00       j9trc_aux.1        - [2] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [3] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [4] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [5] fact.main (fact.java:30)
14:35:41.426 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00       j9trc_aux.0        - jstacktrace:
14:35:41.426 0x16f00       j9trc_aux.1        - [1] fact.factorial (fact.java:36)
14:35:41.426 0x16f00       j9trc_aux.1        - [2] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [3] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [4] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [5] fact.factorial (fact.java:39)
14:35:41.426 0x16f00       j9trc_aux.1        - [6] fact.main (fact.java:30)
14:35:41.426 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:35:41.426 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
120
```

However, running with 0.30.0 yields empty stack traces:
```
openjdk version "1.8.0_322"
IBM Semeru Runtime Open Edition (build 1.8.0_322-b06)
Eclipse OpenJ9 VM (build openj9-0.30.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220128_306 (JIT disabled, AOT disabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - c1d9a7af7c based on jdk8u322-b06)

14:41:24.868*0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00       j9trc_aux.0        - jstacktrace:
14:41:24.869 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00       j9trc_aux.0        - jstacktrace:
14:41:24.869 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00       j9trc_aux.0        - jstacktrace:
14:41:24.869 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00       j9trc_aux.0        - jstacktrace:
14:41:24.869 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00       j9trc_aux.0        - jstacktrace:
14:41:24.869 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
14:41:24.869 0x16f00              mt.9        < fact.factorial(I)I bytecode static method
120
```

**Comment by pshipton** [comment]
I think @gacholio is already be working on a fix for this.

**Comment by gacholio** [comment]
Not sure what @pshipton is referring to.

**Comment by pshipton** [comment]
@tobi do you know?

**Comment by pshipton** [comment]
@tajila do you know.

**Comment by pshipton** [comment]
Ok, could be I misunderstood, or the wrong name was mentioned. I guess @keithc-ca  is expected to fix it.

**Comment by manqingl** [comment]
@keithc-ca I believe the jstackwalk parser needs to be improved so that it does not get confused by the new trace points from the call to walkstackframes().

The issue can be worked around with the following option:  "-Xtrace:none=j9vm.682-683"

**Comment by pshipton** [comment]
A test would be handy as well, not sure why existing tests didn't catch this.

**Comment by manqingl** [comment]
We have a couple of test cases here :  

https://jazz103.hursley.ibm.com:9443/jazz/web/projects/JTC-JAT#action=com.ibm.team.workitem.viewWorkItem&id=147394

**Comment by llxia** [comment]
@LongyuZhang could you help to add the test to cover this case? Thanks

**Comment by keithc-ca** [comment]
The option (`-Xtrace:none=j9vm.682-683`) doesn't help.

I think the culprit is the check for `J9_PRIVATE_FLAGS2_ASYNC_GET_CALL_TRACE` which bypasses auxiliary trace points. I should have a fix shortly.

**Comment by manqingl** [comment]
Are you sure you used the option correctly?

`
root@mli1:~/t# sdk/bin/java  "-Xtrace:print=mt,trigger=method{*.fun3,jstacktrace}" calls
20:07:38.473*0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.475 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.475 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.475 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.475 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.475 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.475 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.475 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.475 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.475 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.475 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.475 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.475 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.475 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.475 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.475 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.475 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.475 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.476 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.476 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.476 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.476 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.476 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.476 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.476 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.476 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.476 0x19a00              mt.6        < func.fun3()V bytecode method
20:07:38.476 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:07:38.476 0x19a00       j9trc_aux.0        - jstacktrace:
Check
20:07:38.476 0x19a00              mt.6        < func.fun3()V bytecode method
root@mli1:~/t# sdk/bin/java  "-Xtrace:print=mt,trigger=method{*.fun3,jstacktrace}" "-Xtrace:none=j9vm.682-683" calls
20:08:12.386*0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.387 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.387 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.387 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.387 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.387 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.388 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.388 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.388 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.388 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.388 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.388 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.388 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.388 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.388 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.388 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.388 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.388 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.388 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.388 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.388 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.388 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.388 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.388 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.388 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.388 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.388 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.388 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.388 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.388 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.388 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.388 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.388 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.388 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.388 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.388 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.388 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.388 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.388 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.388 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.388 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.388 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.388 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.388 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.388 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.388 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.388 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.388 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.388 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.388 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.388 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.388 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.388 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.388 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.388 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.389 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.389 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.389 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.389 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.389 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.389 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.389 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.389 0x19a00              mt.6        < func.fun3()V bytecode method
20:08:12.389 0x19a00              mt.0        > func.fun3()V bytecode method, this = 0xfff6e800
20:08:12.389 0x19a00       j9trc_aux.0        - jstacktrace:
20:08:12.389 0x19a00       j9trc_aux.1        - [1] func.fun3 (calls.java:18)
20:08:12.389 0x19a00       j9trc_aux.1        - [2] func.fun2 (calls.java:15)
20:08:12.389 0x19a00       j9trc_aux.1        - [3] func.fun1 (calls.java:12)
20:08:12.389 0x19a00       j9trc_aux.1        - [4] calls.main (calls.java:6)
Check
20:08:12.389 0x19a00              mt.6        < func.fun3()V bytecode method
root@mli1:~/t#
`

**Comment by keithc-ca** [comment]
When try with 0.27.0 I get
```
JVMTRCE003E Error processing trace option, detail: Unable to set tracepoint 682 in j9vm - tracepoint id out of range
JVMTRCE011W Module not configured for trace: j9vm
```

**Comment by keithc-ca** [comment]
With 0.30.0 it seems to understand the option and restore `jstacktrace` behavior.
Perhaps the problem I had earlier was becase I was also using `-verbose:stackwalk`.

**Comment by manqingl** [comment]
> When try with 0.27.0 I get
> 
> ```
> JVMTRCE003E Error processing trace option, detail: Unable to set tracepoint 682 in j9vm - tracepoint id out of range
> JVMTRCE011W Module not configured for trace: j9vm
> ```

The error message from 0.27.0 for option  "-Xtrace:none=j9vm.682-683" makes sense because those trace points are new in recent releases, and in those old releases, j9vm.682 and j9vm.683 are indeed out of range.  You would get the similar error message if you use  "-Xtrace:none=j9vm.682-683" with Java 8.0.7.0.

**Comment by keithc-ca** [comment]
Adding `-Xtrace:print=j9vm.682-683` results in sequences like this:
```
12:52:07.423 0x16f00              mt.3        > fact.factorial(I)I bytecode static method
12:52:07.423 0x16f00       j9trc_aux.0        - jstacktrace:
12:52:07.423 0x16f00            j9vm.682      > WalkStackFrames - walkThread=0000000000016F00 flags=00000000002C0001 sp=000000000010D500 a0=000000000010D518 pc=0000000000000001 literals=0000000000000000 els=00007F9A9A8E6AC0 j2i=0000000000000000
12:52:07.423 0x16f00       j9trc_aux.1        - [1] fact.factorial (fact.java:14)
12:52:07.423 0x16f00       j9trc_aux.1        - [2] fact.main (fact.java:8)
12:52:07.423 0x16f00            j9vm.683      < WalkStackFrames - walkThread=0000000000016F00, rc=0
```
The auxiliary tracepoints fire based on the previous regular tracepoint. Because `mt.3` is printed, so is `j9trc_aux.0`, but unless `j9vm.682` is printed (or disabled), we lose the other auxiliary tracepoints. I'm exploring options to reduce such unwanted interactions.
