### ISSUE TITLE
Switch from using <init> to <new> for Value Types

### ISSUE THREAD

**Issue by ehrenjulzert** [eclipse-openj9/openj9#14959]
Currently JavaC compiles value classes with an `<init>` method instead of a `<new>` method. Because of this, class verification also assumes that value types will always use `<init>` and not `<new>`. When JavaC switches to using `<new>` instead of `<init>`, the verification code will have to switch as well.

#14816 has code to verify value types that have both `<init>` and `<new>` methods, but the code to verify the `<new>` methods is currently disabled. To enable it we just need to get rid of the `#if defined(J9VM_OPT_VALHALLA_NEW_FACTORY_METHOD)` checks, and then get rid of the code for verifying `<init>` (since it will no longer be relevant).

**Comment by hzongaro** [comment]
The JIT compiler also has some [special handling](https://github.com/eclipse-openj9/openj9/blob/55c52ff26d9a8755b9de00704dee2b7f6543a041/runtime/compiler/env/j9method.cpp#L4839-L4842) to allow for the possibility that a method named `<init>` might not be a constructor if value types are enabled.  It will no longer be relevant once `<vnew>` is introduced.  I'll start on a pull request for that.

**Comment by hangshao0** [comment]
The VM [PR](https://github.com/eclipse-openj9/openj9/pull/16355) is merged.

**Comment by hangshao0** [comment]
Re-open this issue as the JIT [PR](https://github.com/eclipse-openj9/openj9/pull/16357) is still open.
