### ISSUE TITLE
[JDK8 OJDK-MH] IAE from test_FindSpecial_Default_CrossPackage_Interface

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#14987]
The below failure(s) is(are) only seen when OJDK MHs are enabled in OpenJ9.

### Errors

```
FAILED: test_FindSpecial_Default_CrossPackage_Interface
java.lang.IllegalAccessException: no private access for invokespecial: interface examples.CrossPackageDefaultMethodInterface, from com.ibm.j9.jsr292.LookupAPITests_Find
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
	at java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:1572)
	at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1002)
	at com.ibm.j9.jsr292.LookupAPITests_Find.test_FindSpecial_Default_CrossPackage_Interface(LookupAPITests_Find.java:2109)
```

### Failing Test Targets

- `BUILD_LIST=functional`
    - `jsr292Test_jdk8_0`
    - `jsr292Test_JitCount0_jdk8_0`
    - `jsr292Test_jdk8_special_0`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK8 with OJDK MHs enabled

Refer to https://github.com/eclipse-openj9/openj9/issues/14541.

**Comment by babsingh** [comment]
I believe that the RI also throws `IllegalAccessException` for this test. When OJDK-MHs are enabled in OJ9, we automatically adopt RI's behaviour. These statements should be re-confirmed. Afterwards, it should be verified if the RI behaviour is correct. If RI behaviour is as-per spec or Java doc, then the test should be updated or disabled accordingly. Otherwise, we will have to look into updating the RI's behaviour.

**Comment by ThanHenderson** [comment]
w.r.t. https://github.com/eclipse-openj9/openj9/issues/14987#issuecomment-1115048527

> I believe that the RI also throws `IllegalAccessException` for this test. When OJDK-MHs are enabled in OJ9, we automatically adopted the RI's behaviour. These statements should be re-confirmed.

These statements are true.

> it should be verified if the RI's behaviour is correct.

The RI's behaviour seems correct, the spec says: 
> Before method resolution, if the explicitly specified caller class is not identical with the lookup class, or if this lookup object does not have private access privileges, the access fails.

Which is what this does:
https://github.com/openjdk/jdk8/blob/6a383433a9f4661a96a90b2a4c7b5b9a85720031/jdk/src/share/classes/java/lang/invoke/MethodHandles.java#L1554-L1557

The behaviour of `findSpecial` changed with JEP 274 (https://openjdk.org/jeps/274) stating:

> Lookups
The implementation of the method MethodHandles.Lookup.findSpecial(Class<?> refc, String name, MethodType type, Class<?> specialCaller) will be modified to allow for finding super-callable methods on interfaces. While this is not a change of the API as such, its documented behaviour changes significantly.

Here is the code:
https://github.com/openjdk/jdk11/blob/37115c8ea4aff13a8148ee2b8832b20888a5d880/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L2235-L2238

and JEP 274 shipped with Java 9.

> the test should be updated or disabled accordingly

The test that is failing tests the behaviour of JEP 274 (finding methods on interfaces). Given the statements above, this test should be disabled for Java 8.

**Comment by babsingh** [comment]
> The RI's behaviour seems correct, the spec says: ...

This implies that OpenJ9's current MH impl doesn't satisfy the spec in JDK8. https://github.com/eclipse-openj9/openj9/pull/3978 might have changed the behaviour in JDK 8. Will ifdef'ing https://github.com/eclipse-openj9/openj9/pull/3978 to JDK 9+ fix the OpenJ9 MH behaviour in JDK 8?

**Comment by ThanHenderson** [comment]
I'll look more into that. That would likely be the solution; just ifdef'ing the latter part of the condition here: https://github.com/eclipse-openj9/openj9/pull/3978/files#diff-0a684f4145fdb97062bd8f290586a3a737634cb776bcf1a7adea2a394a9777d8R563 would do the trick. I can open an Issue

**Comment by babsingh** [comment]
Keeping this issue open until the below points are addressed:
- https://github.com/eclipse-openj9/openj9/issues/14987#issuecomment-1795350727
- https://github.com/eclipse-openj9/openj9/pull/18398#discussion_r1385225646
