### ISSUE TITLE
10% increase in CPU IBM J11.0.14 Liberty L22.0.0.3 CICS 6.1 zOS 2.5 vs J1.8.0_321

### ISSUE THREAD

**Issue by SimonMcNab** [eclipse-openj9/openj9#15019]
Java -version output
--------------------

java version "11.0.14.1" 2022-02-08
IBM Semeru Runtime Certified Edition for z/OS 11.0.14.1 (build 11.0.14.1+1)
IBM J9 VM 11.0.14.1 (build z/OS-Release-11.0.14.1-b01, JRE 11 z/OS s390x-64-Bit Compressed References 20220315_174 (JIT enabled, AOT
enabled)
OpenJ9 - 251e7679cf3
OMR - 59845b76b8a
IBM - 3c151c1
JCL - 090eaebc57d based on jdk-11.0.14.1+1)

Summary of problem
------------------

When performance testing a workload with IBM J11.0.14 Liberty L22.0.0.3 CICS 6.1 zOS 2.5, we observe a 10% increase in CPU usage compared to java version "1.8.0_321". 

The increase is demonstrated in SMF data

All other test conditions are identical

Diagnostic files
----------------

<please advise what is required>

**Comment by pshipton** [comment]
Pls report this problem to IBM.
