### ISSUE TITLE
Significant Liberty Startup performance with IBM J9 VM 11.0.14.1 vs IBM J9 VM (build 2.9..)

### ISSUE THREAD

**Issue by SimonMcNab** [eclipse-openj9/openj9#15021]
Java -version output
--------------------

java version "1.8.0_321"                                                                                          
Java(TM) SE Runtime Environment (build 8.0.7.5 - pmz6480sr7fp5-20220208_01(SR7 FP5))                              
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20220104_19630 (JIT enabled, AOT enabled) 
OpenJ9   - 2d4c7d9                                                                                                
OMR      - 59845b7                                                                                                
IBM      - 3c151c1)                                                                                               
JCL - 20220120_01 based on Oracle jdk8u321-b07                                                                    

vs

java version "11.0.14.1" 2022-02-08
IBM Semeru Runtime Certified Edition for z/OS 11.0.14.1 (build 11.0.14.1+1)
IBM J9 VM 11.0.14.1 (build z/OS-Release-11.0.14.1-b01, JRE 11 z/OS s390x-64-Bit Compressed References 20220315_174 (JIT enabled, AOT
enabled)
OpenJ9 - 251e7679cf3
OMR - 59845b76b8a
IBM - 3c151c1
JCL - 090eaebc57d based on jdk-11.0.14.1+1)

Summary of problem
------------------

When running a performance startup test with 20 springboot apps and measuring the time between server startup and the last CWWKZ0001I message, we see approx 40% faster startup with J11 vs J8

Test was repeated 20 times back-to-back at J8 then run 20 times back-to-back at J11,

Results in .csv files attached

Is it possible to port this improvement to J8?

All remaining test conditions are identical:

 IBM J11.0.14 Liberty L22.0.0.3 CICS 6.1 zOS 2.5 on a z15
 

Diagnostic files
----------------
These csv files capture data from the tests

[26APR22_J8.csv](https://github.com/eclipse-openj9/openj9/files/8641890/26APR22_J8.csv)

[26APR22_J11.csv](https://github.com/eclipse-openj9/openj9/files/8641893/26APR22_J11.csv)

**Comment by pshipton** [comment]
Pls raise this with IBM.
