### ISSUE TITLE
50MB increase in 31 bit virtual storage using IBM J11.0.14 CICS 6.1 zOS 2.5 vs J1.8.0_321

### ISSUE THREAD

**Issue by SimonMcNab** [eclipse-openj9/openj9#15020]
Java -version output
--------------------

java version "11.0.14.1" 2022-02-08
IBM Semeru Runtime Certified Edition for z/OS 11.0.14.1 (build 11.0.14.1+1)
IBM J9 VM 11.0.14.1 (build z/OS-Release-11.0.14.1-b01, JRE 11 z/OS s390x-64-Bit Compressed References 20220315_174 (JIT enabled, AOT
enabled)
OpenJ9 - 251e7679cf3
OMR - 59845b76b8a
IBM - 3c151c1
JCL - 090eaebc57d based on jdk-11.0.14.1+1)

Summary of problem
------------------

When performance testing a workload with IBM J11.0.14 CICS 6.1 zOS 2.5, we observe a 50MB increase in 31 bit virtual storage compared to java version "1.8.0_321".

All other test conditions are identical

This is seen with Liberty and OSGI workloads

The increase is demonstrated in the attached CICS statistics reports. 

Diagnostic files
----------------

In the attached files, look for "CICS TCB Private Storage allocated above 16MB"

At J8 we have 684476K

At J11 we have 739460K

Increase is approx 50Mb

[J8_CICS Statistics.txt](https://github.com/eclipse-openj9/openj9/files/8641806/J8_CICS.Statistics.txt)
[J11_CICS Statistics.txt](https://github.com/eclipse-openj9/openj9/files/8641807/J11_CICS.Statistics.txt)

**Comment by pshipton** [comment]
Pls report this problem to IBM.
