### ISSUE TITLE
Add CompilationInfo pointer into the J9JITConfig

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#15036]
The purpose of this work is to improve debug-ability.
`J9JITConfig` is a data structure used by both the VM and the JIT. It is attached to `J9JavaVM` and thus readily available from many custom OpenJ9 debugging tools.
`TR::CompilationInfo` is a data structure that holds a lot of information about other data structures in the JIT. The JIT creates a single such object and stores its address into the static field:  `static TR::CompilationInfo * _compilationRuntime`.
In order to easily find the address of this singleton this issue proposes to add a new field to `J9JITConfig` called `compilationRuntime` and initialize it appropriately in `TR::CompilationInfo::createCompilationInfo(J9JITConfig * jitConfig)`

**Comment by mpirvu** [comment]
Attn: @Manasha-Vetrivelu

**Comment by piyush280599** [comment]
@mpirvu can you please assign me this issue if it is still open?
