### ISSUE TITLE
"\\?\D:\very long path". syntax on windows is not accepted as valid path in File.exists()

### ISSUE THREAD

**Issue by robert-bray** [eclipse-openj9/openj9#15049]
I sometimes get paths on windows that include the "very long path" syntax from windows (\\?\)

This link has some references to that syntax.
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

in this test case:
import java.io.File;
public class TestReplace
{

	public static void main(String[] args)
	{
		File f = new File("\\\\?\\C:\\Users\\rob\\AppData\\Local");
		if(f.exists())
		{
			System.out.println("T");
		}
		else
			System.out.println("F");
		
	}

}

In jre version:
```
openjdk 11.0.15 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220422_352 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)
```
this testcase prints F (fail)

in jre version:
```
openjdk version "11.0.14" 2022-01-18
IBM Semeru Runtime Open Edition 11.0.14.0 (build 11.0.14+9)
Eclipse OpenJ9 VM 11.0.14.0 (build openj9-0.30.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220128_296 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 01f86654ee based on jdk-11.0.14+9)
```
the testcase print T (pass)

I think this syntax should be supported

**Comment by pshipton** [comment]
If I understand correctly, it works in 11.0.14 but doesn't work in 11.0.15.

Do the builds from [Adoptium ](https://adoptium.net/temurin/releases) have the same behavior? I'm not sure this has anything to do with OpenJ9.

**Comment by robert-bray** [comment]
yes,  it also fails in that build.

**Comment by pshipton** [comment]
This problem needs to be reported to the [OpenJDK ](http://openjdk.java.net/) project. Although you could try a preliminary 11.0.16 build to see if it has been resolved. 

The latest OpenJ9 build:
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_windows_Nightly/283/OpenJ9-JDK11-x86-64_windows-20220510-204335.tar.gz

Adoptium: https://adoptium.net/temurin/nightly

**Comment by robert-bray** [comment]
It does appear to be fixed in 11.0.16

**Comment by pshipton** [comment]
I did see https://mail.openjdk.java.net/pipermail/jdk8u-dev/2022-April/014889.html not sure if it's related.

**Comment by pshipton** [comment]
Although that post was about jdk8, I don't think the regression was specific to jdk8.

**Comment by robert-bray** [comment]
I'm not so accustomed to reading these threads, did anyone decide that it was important enough to make a patch?

**Comment by robert-bray** [comment]
it also seems that adding this flag -Djdk.io.File.enableADS=true  fixes it,  but is there a downside to that?

**Comment by pshipton** [comment]
I didn't see any reply to the post. 
See 
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2022-April/thread.html
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2022-May/thread.html
https://mail.openjdk.java.net/pipermail/jdk8u-dev/

> it also seems that adding this flag -Djdk.io.File.enableADS=true fixes it, but is there a downside to that?

I don't know anything about this as it's in OpenJDK code. We build OpenJDK and put in OpenJ9, but don't have a full understanding of everything in OpenJDK. 

The only version that got a respin is 18. There is an 18.0.1.1 update that should fix this. 
https://github.com/ibmruntimes/openj9-openjdk-jdk18/compare/jdk-18.0.1+10...jdk-18.0.1.1+2

I did an OpenJ9 project build of 18.0.1.1
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK18_x86-64_windows_Personal/25/OpenJ9-JDK18-x86-64_windows-20220506-192228.tar.gz
and Semeru should be releasing a build in the near future.
