### ISSUE TITLE
Loom: Impact of Loom on root scanning

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15058]
Loom proposes to introduce virtual threads (AKA green threading) to the JDK. Our current implementation is going to implement Virtual threads with a J9VMthread (except this J9VMthread will not be backed by a J9Thread/native thread).

The impact of this design is that there will be many more J9VMthreads with Loom enabled in comparison to before. We can expect to have >10000s of J9VMthreads. This means that there will be a lot more threads to walk during root scanning. 

What will the performance impact of this be?

**Comment by tajila** [comment]
@gacholio @amicic

**Comment by tajila** [comment]
FYI @fengxue-IS

**Comment by tajila** [comment]
@dmitripivkine

**Comment by dmitripivkine** [comment]
I am not sure we have something special flor this item, I believe general discussion is going to be in https://github.com/eclipse-openj9/openj9/issues/15057
