### ISSUE TITLE
Inconsistency with HotSpot when performing ensureCapacity

### ISSUE THREAD

**Issue by YuanWangC** [eclipse-openj9/openj9#15050]
##### Description:

When I use the method `ensureCapacity` and pass it `Integer.MAX_VALUE/ 2 + 1`, OpenJ9 for JDK11 catches the OOM Exception, and at the same time HotSpot for JDK11 and  OpenJ9 for JDK8 do nothing. 

And I looked up the description of this method in the JDK Specification: `Ensures that the capacity is at least equal to the specified minimum. If the current capacity is less than the argument, then a new internal array is allocated with greater capacity. The new capacity is the larger of: The minimumCapacity argument. Twice the old capacity, plus 2.`It seems that the capacity is going to change into `Integer.MAX_VALUE/ 2 + 1` according to the Specification, and the OOM exception is not specified.

 I couldn't figure out why this happened. Is this an implementation issue of the OpenJ9 when migrating OpenJDK?

##### Environment：

```
Ubuntu 18.04 x86_64
```

###### jdk8:

```
openjdk version "1.8.0_332-internal"
OpenJDK Runtime Environment (build 1.8.0_332-internal-_2022_02_17_10_23-b00)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 301202f49f based on jdk8u332-b02)
```

###### jdk11:

```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-39c490eaf, JRE 11 Linux amd64-64-Bit Compressed References 20220217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 39c490eaf
OMR      - b63287860
JCL      - 24e7209ed4 based on jdk-11.0.15+1)
```

##### Testcase:

```
public class MyJVMTest {
    boolean testLatin1() {
        try {
            StringBuilder sb = new StringBuilder();
            System.out.println(sb.capacity());
            sb.ensureCapacity(Integer.MAX_VALUE/ 2 + 1);
        } catch (OutOfMemoryError oom) {
            oom.printStackTrace();
        }
        return true;
    }
    public static void main(String[] args) throws Exception {
        new MyJVMTest().testLatin1();
    }
}

```

##### Output of JDK11:

```
16
java.lang.OutOfMemoryError
	at java.base/java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:214)
	at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:206)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:173)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacity(AbstractStringBuilder.java:157)
	at java.base/java.lang.StringBuilder.ensureCapacity(StringBuilder.java:89)
	at MyJVMTest.testLatin1(MyJVMTest.java:6)
	at MyJVMTest.main(MyJVMTest.java:13)
```

##### Output of JDK8 and HotSpot:

```
16
```

**Comment by YuanWangC** [comment]
Thanks a lot for your reply, I will go and try to add this VM parameter and see the effect again. By the way, since I am not familiar with OpenJ9, is there any other default VM parameter that is different between OpenJ9 and HotSpot? Or is there any documentation I can refer to?

**Comment by YuanWangC** [comment]
Thanks a lot for your reply, I will go and try to add this VM parameter and see the effect again. By the way, since I am not familiar with OpenJ9, is there any other default VM parameter that is different between OpenJ9 and HotSpot? Or is there any documentation I can refer to? @pshipton

**Comment by pshipton** [comment]
There is a "Creating compatible behavior" section near the bottom of https://www.eclipse.org/openj9/docs/cmdline_migration/, but I see it's missing the `-XX:+CompactStrings` option. I've created an issue to update the table.

**Comment by YuanWangC** [comment]
Thank you for your reply, I will read this document carefully.
