### ISSUE TITLE
jdk_vector_1_FAILED Error evaluating expression: invalid boolean value: null for expression vm.gc.Z

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15064]
Failure link
------------

From an internal build `job/Test_openjdk17_j9_extended.openjdk_ppc64_aix/61/`(`paix824`):
```
java version "17.0.4" 2022-07-19
IBM Semeru Runtime Certified Edition 17.0.4+2 (build 17.0.4+2)
Eclipse OpenJ9 VM 17.0.4+2 (build master-19c3dc498, JRE 17 AIX ppc64-64-Bit Compressed References 20220514_146 (JIT enabled, AOT enabled)
OpenJ9   - 19c3dc498
OMR      - c945d253d
JCL      - 32611aab1 based on jdk-17.0.4+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_vector_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F146%2Fibm-semeru-certified-jdk_ppc64_aix_JDK17U_2022-05-14-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F146%2Fibm-semeru-certified-debugimage_ppc64_aix_JDK17U_2022-05-14-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F146%2Fibm-semeru-certified-jre_ppc64_aix_JDK17U_2022-05-14-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F146%2Fibm-semeru-certified-testimage_ppc64_aix_JDK17U_2022-05-14-14-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-05-14T21:01:25.898Z] variation: Mode650
[2022-05-14T21:01:25.898Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-05-14T22:08:46.938Z] --------------------------------------------------
[2022-05-14T22:08:46.938Z] TEST: jdk/incubator/vector/VectorMaxConversionTests.java#id1
[2022-05-14T22:08:46.938Z] 
[2022-05-14T22:08:46.938Z] TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.Z'
[2022-05-14T22:08:46.938Z] --------------------------------------------------
[2022-05-14T22:12:41.659Z] Test results: passed: 73; error: 1
[2022-05-14T22:12:44.017Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/report/html/report.html
[2022-05-14T22:12:44.017Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_ppc64_aix/aqa-tests/TKG/output_16525481683687/jdk_vector_1/work
[2022-05-14T22:12:44.017Z] Error: Some tests failed or other problems occurred.
[2022-05-14T22:12:44.017Z] 
[2022-05-14T22:12:44.017Z] jdk_vector_1_FAILED
```

This is across platform, last successful run was April 23rd, might be a test change.

**Comment by pshipton** [comment]
@llxia can somebody add the test variable for OpenJ9 pls.

**Comment by pshipton** [comment]
Should be fixed now, closing.
