### ISSUE TITLE
Can you publish to SDKMan?

### ISSUE THREAD

**Issue by tonycody** [eclipse-openj9/openj9#15060]
Can you publish to SDKMan?
Open J9 is not included in the Sdkman Java list.

Installation is not user-friendly.

https://sdkman.io/vendors

**Comment by pshipton** [comment]
@AdamBrousseau fyi

**Comment by tonycody** [comment]
> @AdamBrousseau fyi

The official Docker image doesn't seem to be available either

**Comment by AdamBrousseau** [comment]
OpenJ9 is built by IBM and released under IBM Semeru Runtimes.
https://ibm.com/semeru-runtimes/
https://hub.docker.com/_/ibm-semeru-runtimes
https://sdkman.io/jdks

**Comment by tonycody** [comment]
> 

https://sdkman.io/jdks#sem
nice.

**Comment by tonycody** [comment]
> IBM builds OpenJ9 binaires and releases under IBM Semeru Runtimes. https://ibm.com/semeru-runtimes/ https://hub.docker.com/_/ibm-semeru-runtimes https://sdkman.io/jdks

https://sdkman.io/jdks#sem
nice.

**Comment by tonycody** [comment]
> IBM builds OpenJ9 binaires and releases under IBM Semeru Runtimes. https://ibm.com/semeru-runtimes/ https://hub.docker.com/_/ibm-semeru-runtimes https://sdkman.io/jdks

@AdamBrousseau 
https://sdkman.io/jdks#sem
nice.
