### ISSUE TITLE
RuntimePermission getClassLoader issue when creating the cleaner thread in SunPKCS11 if security manager is enabled

### ISSUE THREAD

**Issue by taoliult** [eclipse-openj9/openj9#15078]
When running the cleaner thread creation in the security provider "SunPKCS11" of module "jdk.crypto.cryptoki", and meanwhile the security manager is enabled. The access denied error "Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "getClassLoader")" happens.

**Comment by keithc-ca** [comment]
@taoliult This should be resolved by #15090: could you please confirm by closing this.

**Comment by taoliult** [comment]
@keithc-ca Let me run the FIPS tests to see if it fix the issue, will update once the tests done.

**Comment by taoliult** [comment]
Run the FIPS tests with both personal build and nightly build, reports links as follow. Both works. No such access denied "getClassLoader" error. So, close this.

Tests reports:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24066/testReport/
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/24052/testReport/
