### ISSUE TITLE
core_pattern problem

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15088]
on ub18-390-2
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_0/230/tapResults/
```
 [ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.15904.
```

**Comment by pshipton** [comment]
Fixed it, I hope. At least for the moment.
https://askubuntu.com/questions/420410/how-to-permanently-edit-the-core-pattern-file
https://github.com/eclipse-openj9/openj9/issues/14940#issuecomment-1106669956

**Comment by pshipton** [comment]
```
jenkins@ubuntu22x86-beta1:~$ cat  /proc/sys/kernel/core_pattern
|/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E
```
```
jenkins@ubuntu22x86-beta2:~$ cat  /proc/sys/kernel/core_pattern
|/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E
```

**Comment by AdamBrousseau** [comment]
Apport service was enabled (but inactive/stopped). Package was marked for hold. So a restart would have reactivated it. Should be good now :crossed_fingers:

**Comment by pshipton** [comment]
@AdamBrousseau What did you do that I didn't do?
I did set `enabled=0` in `/etc/default/apport`.

**Comment by AdamBrousseau** [comment]
as root
`systemctl disable apport`
See infra 6186 for more info.

**Comment by pshipton** [comment]
core_pattern issue on [ub16-ppcle-1](https://openj9-jenkins.osuosl.org/computer/ub16-ppcle-1)
I don't think I have root access to fix it. @AdamBrousseau can you please update it.

**Comment by AdamBrousseau** [comment]
All the core settings were gone.
```
echo "core%p" > /proc/sys/kernel/core_pattern
echo "kernel.core_pattern=core.%p" >> /etc/sysctl.conf
systemctl stop apport
systemctl disable apport
apt-mark hold apport
```

**Comment by pshipton** [comment]
Do you do what is described in https://askubuntu.com/questions/420410/how-to-permanently-edit-the-core-pattern-file and set `enabled=0` in `/etc/default/apport`?

**Comment by AdamBrousseau** [comment]
afaik that is the old way, replaced by `systemctl disable apport`.

**Comment by pshipton** [comment]
core_pattern issue on https://openj9-jenkins.osuosl.org/computer/ub16x64j98
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_linux_aot_Personal_testList_1/76/
```
     [test]     [junit] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.31227.
     [test]     [junit] 
     [test]     [junit] JVMDUMP012E Error in System dump: The core file created by child process with pid = 31227 was not found. Expected to find core file with name "/tmp/core"
     [test]     [junit] Unable to find file The core file created by child process with pid = 31227 was not found. Expected to find core file with name "/tmp/core" to delete for test case testSystemDumpWithSameFile
```

**Comment by AdamBrousseau** [comment]
All settings are reset. Last apt packages installed in April. No idea.
Reapplied all settings.
