### ISSUE TITLE
Version Number?

### ISSUE THREAD

**Issue by PowerUser1234** [eclipse-openj9/openj9#15101]
What version of the Java OpenJDK is eclipse-openj9 up to, and compatible with?  OpenJDK is on version 18, preparing for version 19 at the time of this message.  By reckoning of OpenJDK version numbers, and in order for us to know for sure, which such version number does the latest stable version of eclipse-openj9 possess?

[https://openjdk.java.net/](https://openjdk.java.net/)

**Comment by DanHeidinga** [comment]
Does that address your question?  If there's something that needs more explanation, please let us know

**Comment by PowerUser1234** [comment]
Dear eclipse-openj9,

Yes, that's brilliant.  I didn't know that you were paralleling the OpenJDK
for version numbers.

This answers my question here, yes.  However I have posted another, more
serious one for you guys at:

https://github.com/eclipse-openj9/openj9/issues/15102

Could someone pass this to the pertinent people, and
could they please look on this matter favourably,
and seriously consider taking this matter on board,
for Java implementation?


Yours Sincerely,

Sergio Minervini.

S.M.

________________________________
