### ISSUE TITLE
JDK11 jdk_lang_1_FAILED NPE at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:277) & Unexpected provider count. Expected: 12. Actual: 4

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15107]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips_testList_0/1/`(`rhel8x64-fips4-1`):
```
java version "11.0.16" 2022-07-19
IBM Semeru Runtime Certified Edition 11.0.16+3 (build 11.0.16+3)
Eclipse OpenJ9 VM 11.0.16+3 (build master-00bc246e2, JRE 11 Linux amd64-64-Bit Compressed References 20220521_349 (JIT enabled, AOT enabled)
OpenJ9   - 00bc246e2
OMR      - 42677ec34
JCL      - dbbf417306 based on jdk-11.0.16+3)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_lang_1&amp;TEST_FLAG=FIPS&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.openjdk_x86-64_linux_fips&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=-Dsemeru.fips%3Dtrue&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-jdk_x64_linux_JDK11U_2022-05-21-01-02.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-jre_x64_linux_JDK11U_2022-05-21-01-02.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-testimage_x64_linux_JDK11U_2022-05-21-01-02.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-x64-openj9-IBM%2F349%2Fibm-semeru-certified-debugimage_x64_linux_JDK11U_2022-05-21-01-02.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=3&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-05-21T02:19:59.270Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode650
[2022-05-21T02:19:59.270Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:-UseCompressedOops -Dsemeru.fips=true

[2022-05-21T02:21:06.530Z] TEST: java/lang/Class/GetPackageBootLoaderChildLayer.java

[2022-05-21T02:21:06.539Z] STDERR:
[2022-05-21T02:21:06.539Z] com.sun.tools.attach.AttachNotSupportedException: Virtual machine ID or display name is null
[2022-05-21T02:21:06.539Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:70)
[2022-05-21T02:21:06.539Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:47)
[2022-05-21T02:21:06.539Z] 	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
[2022-05-21T02:21:06.539Z] 	at GetPackageBootLoaderChildLayer.main(GetPackageBootLoaderChildLayer.java:45)
[2022-05-21T02:21:06.539Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T02:21:06.539Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T02:21:06.541Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T02:21:06.541Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T02:21:06.541Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-05-21T02:21:06.541Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T02:21:06.541Z] Caused by: java.lang.NullPointerException
[2022-05-21T02:21:06.541Z] 	at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:277)
[2022-05-21T02:21:06.541Z] 	at java.base/java.security.SecureRandom.<init>(SecureRandom.java:227)
[2022-05-21T02:21:06.541Z] 	at java.base/openj9.internal.tools.attach.target.IPC.getRandomString(IPC.java:358)
[2022-05-21T02:21:06.541Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.tryAttachTarget(OpenJ9VirtualMachine.java:452)
[2022-05-21T02:21:06.541Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTargetImpl(OpenJ9VirtualMachine.java:157)
[2022-05-21T02:21:06.541Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.lambda$attachTarget$1(OpenJ9VirtualMachine.java:128)
[2022-05-21T02:21:06.541Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:747)
[2022-05-21T02:21:06.542Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTarget(OpenJ9VirtualMachine.java:130)
[2022-05-21T02:21:06.542Z] 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:64)
[2022-05-21T02:21:06.542Z] 	... 9 more
[2022-05-21T02:21:06.543Z] 
[2022-05-21T02:21:06.543Z] JavaTest Message: Test threw exception: com.sun.tools.attach.AttachNotSupportedException: Virtual machine ID or display name is null

[2022-05-21T02:27:41.857Z] TEST: java/lang/SecurityManager/CheckSecurityProvider.java

[2022-05-21T02:27:41.859Z] STDERR:
[2022-05-21T02:27:41.859Z] java.lang.Exception: Unexpected provider count. Expected: 12. Actual: 4
[2022-05-21T02:27:41.859Z] 	at CheckSecurityProvider.main(CheckSecurityProvider.java:108)
[2022-05-21T02:27:41.859Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-21T02:27:41.859Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-21T02:27:41.859Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-21T02:27:41.859Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-21T02:27:41.859Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-05-21T02:27:41.859Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-05-21T02:27:41.859Z] 
[2022-05-21T02:27:41.859Z] JavaTest Message: Test threw exception: java.lang.Exception: Unexpected provider count. Expected: 12. Actual: 4
```

**Comment by pshipton** [comment]
@alon-sh @taoliult

**Comment by vij-singh** [comment]
@alon-sh @taoliult - Any update on this one as well?

**Comment by taoliult** [comment]
@vij-singh @pshipton @alon-sh 

The first failure "java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:277)", is due to ONLY in the FIPS mode, when creating the VM using attach mechanism, the providers creation seem have issues. I am still checking this issue. 

This second failure "java.lang.Exception: Unexpected provider count. Expected: 12. Actual: 4", is due to in FIPS mode, there are only 4 providers enabled. So, when the test counting the provider number, it is 4 not the 12. So this failure I will add to the FIPS exclude list, once the FIPS exclude list PR commit, this counting provider number test will not be run.

**Comment by vij-singh** [comment]
@taoliult  Could you update this with current status?

**Comment by taoliult** [comment]
@vij-singh @alon-sh 

The test "java/lang/SecurityManager/CheckSecurityProvider" is already added into the FIPS mode testing exclude list by the PR https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/537, so this test will not be run in the FIPS mode testing.

The test "java/lang/Class/GetPackageBootLoaderChildLayer", I am using my forked repo issue https://github.ibm.com/Tao-Liu/openj9-openjdk-jdk11/issues/3 to track this issue. From the current investigation, it looks like a limitation when using VM attach mechanism to initial the non java.base provider in the FIPS mode. But still need time to investigate, will update shortly.

**Comment by taoliult** [comment]
@vij-singh The current investigation status about this issue, as below. Next, I will check, in the non-fips mode, if the non java.base providers can be loaded by using the VM attach mechanism. Will update shortly.

From the ProviderConfig code, when it will try to getProviders, in the ProviderConfig.getProvider, if the providers are in java.base directly, they will be initialized directly. As the below codes:

        // Create providers which are in java.base directly
        if (provName.equals("SUN") || provName.equals("sun.security.provider.Sun")) {
            p = new sun.security.provider.Sun();
        } else if (provName.equals("SunRsaSign") || provName.equals("sun.security.rsa.SunRsaSign")) {
            p = new sun.security.rsa.SunRsaSign();
        } else if (provName.equals("SunJCE") || provName.equals("com.sun.crypto.provider.SunJCE")) {
            p = new com.sun.crypto.provider.SunJCE();
        } else if (provName.equals("SunJSSE") || provName.equals("com.sun.net.ssl.internal.ssl.Provider")) {
            if (hasArgument()) {
                p = new com.sun.net.ssl.internal.ssl.Provider(argument);
            } else {
                p = new com.sun.net.ssl.internal.ssl.Provider();
            }

For those providers are not in the java.base, like SunEC, SunPKCS11. It will first try to load them from the ServiceLoader, which initialed by “services = ServiceLoader.load(java.security.Provider.class, ClassLoader.getSystemClassLoader());”, debug output as follow:

ProviderConfig: Loading provider SunPKCS11('/root/tao/JDKs/OpenJ9-JDK11-x86-64_linux/conf/security/nss.fips.cfg')
ProviderConfig: Attempt to load SunPKCS11 using SL
ProviderConfig: Found SL Provider named SunPKCS11
ProviderConfig: Loaded provider SunPKCS11-NSS-FIPS

In the above normal provider initialize case, the provider SunPKCS11-NSS-FIPS will be found from the ServiceLoader and load success.

But in the VM attach test cases, debug output as below. When attach VM try to getRandomString, it will also call the same getProviders as normal provider initialize did. And same, if the providers are in java.base directly, they will be initialized directly. If the providers are not in the java.base, it will first try to load them from the ServiceLoader. But in this VM attach case, the provider can not be found from the ServiceLoader, actually, there is no any provider return from the ServiceLoader. And then, it will try the Loading legacy provider, and also, failed.

ProviderConfig: Loading provider SunPKCS11('/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/conf/security/nss.fips.cfg') ProviderConfig: Attempt to load SunPKCS11 using SL ProviderConfig: Loading legacy provider: SunPKCS11 ProviderConfig: Error loading legacy provider SunPKCS11 java.lang.ClassNotFoundException: SunPKCS11 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1074) at java.base/sun.security.jca.ProviderConfig$ProviderLoader.legacyLoad(ProviderConfig.java:385) at java.base/sun.security.jca.ProviderConfig$ProviderLoader.load(ProviderConfig.java:362) at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:248) at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:242) at java.base/java.security.AccessController.doPrivileged(AccessController.java:691) at java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:242) at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:222) at java.base/sun.security.jca.ProviderList.loadAll(ProviderList.java:315) at java.base/sun.security.jca.ProviderList.removeInvalid(ProviderList.java:332) at java.base/sun.security.jca.Providers.getFullProviderList(Providers.java:174) at java.base/java.security.Security.getProviders(Security.java:476) at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:275) at java.base/java.security.SecureRandom.(SecureRandom.java:227) at java.base/openj9.internal.tools.attach.target.IPC.getRandomString(IPC.java:358) at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.tryAttachTarget(OpenJ9VirtualMachine.java:452)

That is why we see this issue when using the VM attach mechanism, looks like, in the VM attach mechanism, the non java.base providers can not be initialized.

And in non-fips, in VM attach, the SecureRandom will be get from provider SUN, and SUN is a java.base provider. So, SUN can be loaded.

Next, I will check, in the non-fips mode, if the non java.base providers can be loaded by using the VM attach mechanism. Will update shortly.

**Comment by taoliult** [comment]
@alon-sh fyi

**Comment by taoliult** [comment]
@vij-singh @alon-sh 

After adding some debug output and reproduce on my local, I think, it should be a limitation for using the VM attach in FIPS mode. Here is what I found.

In a normal case, without using the VM attach mechanism, the provider SunPKCS11 initialized as follow. “Found SL Provider named SunPKCS11” mean the provider SunPKCS11 can be found and loaded from SL, the ServiceLoader.

```
ProviderList: provider configuration: [SunPKCS11('/root/tao/JDKs/OpenJ9-JDK11-x86-64_linux/conf/security/nss.fips.cfg'), SUN, SunEC, SunJSSE] 
ProviderList: config configuration: null
ProviderList: Loading all providers 
ProviderConfig: Loading provider SunPKCS11('/root/tao/JDKs/OpenJ9-JDK11-x86-64_linux/conf/security/nss.fips.cfg') 
ProviderConfig: Attempt to load SunPKCS11 using SL 
ProviderConfig: Found SL Provider named SunPKCS11 
ProviderConfig: Loaded provider SunPKCS11-NSS-FIPS
```

In the FIPS case, using the VM attach mechanism in FIPS mode, the SunPKCS11 initialization failed. 

Because the VM attach will call the "java.security.SecureRandom.getDefaultPRNG()" to get the Secure Random. And in the FIPS mode, the Secure Random come from the provider SunPKCS11, not provider SUN. So then, the code will try to load the provider SunPKCS11. But in the ServiceLoader, provider SunPKCS11 can NOT be found. So, report the SunPKCS11 initialization failed error. Output as follow:

```
----------System.err:(107/8926)----------
ProviderList: provider configuration: [SunPKCS11('/root/tao/JDKs/OpenJ9-JDK11-x86-64_linux/conf/security/nss.fips.cfg'), SUN, SunEC, SunJSSE]
ProviderList: config configuration: null
ProviderConfig: Loading provider SunPKCS11('/root/tao/JDKs/OpenJ9-JDK11-x86-64_linux/conf/security/nss.fips.cfg')
ProviderConfig: Attempt to load SunPKCS11 using SL
ProviderConfig: Loading legacy provider: SunPKCS11
ProviderConfig: Error loading legacy provider SunPKCS11
java.lang.ClassNotFoundException: SunPKCS11
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
……
	at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:286)
	at java.base/java.security.Security.getProvider(Security.java:492)
	at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:275)
	at java.base/java.security.SecureRandom.<init>(SecureRandom.java:227)
	at java.base/openj9.internal.tools.attach.target.IPC.getRandomString(IPC.java:358)
	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.tryAttachTarget(OpenJ9VirtualMachine.java:452)
……
	at java.base/java.lang.Thread.run(Thread.java:838)
ProviderConfig: Error loading provider SunPKCS11('/root/tao/JDKs/OpenJ9-JDK11-x86-64_linux/conf/security/nss.fips.cfg')
```

Why the SunPKCS11 can NOT be found in the ServiceLoader? That is because, by using the VM attach mechanism, there is no any provider returned from the ServiceLoader. I verify this assumption, by running the same tests in non-fips mode and adding some debug output. The output as below.

```
----------System.err:(36/2971)----------
ProviderList: provider configuration: [SUN, SunRsaSign, SunEC, SunJSSE, SunJCE, SunJGSS, SunSASL, XMLDSig, SunPCSC, JdkLDAP, JdkSASL, SunPKCS11]
ProviderList: config configuration: null
ProviderConfig: TAO: Initial SUN. 
ProviderConfig: Attempt to load TAO: TESTING_PROVIDER using SL
ProviderConfig: Loading legacy provider: TAO: TESTING_PROVIDER
ProviderConfig: Error loading legacy provider TAO: TESTING_PROVIDER
java.lang.ClassNotFoundException: TAO: TESTING_PROVIDER
```

From the above, we can see the provider SUN is initialized in the non-fips mode. Because in non-FIPS mode, the SecureRandom come from the provider SUN. That also explained why in the non-FIPS mode, this test passed. That because, in non-FIPS mode, the SecureRandom come from the provider SUN, and SUN is a java.base provider. So SUN will be initialized directly by calling the “new sun.security.provider.Sun();”, not by the ServiceLoader. 

And also from the above, we can see “ProviderConfig: Attempt to load TAO: TESTING_PROVIDER using SL”, this is a test provider never exist, I am using it just want to trigger, to see if there is any provider return from the ServiceLoader. And from this output, we did not see any output like "Found SL Provider named XXXXX”, this is a debug output to list all the found providers in ServiceLoader. If no this output, that mean, the provider list returned from the ServiceLoader is empty. So, that mean, even in the non-fips mode, there is no any provider returned from the ServiceLoader.

So, according to the above, I think it should be a limitation for using the VM attach in FIPS mode. Because in the FIPS, the SecureRandom must come from the provider SunPKCS11. But when using the VM attach, there is no any non-java.base provider can be initialized.

@vij-singh @alon-sh any advice?

**Comment by taoliult** [comment]
@vij-singh @alon-sh 

After I did some debug and tests, it is not an issue.

In the test case, it has the following when running the tests:

`* @run main/othervm --limit-modules jdk.attach -Djdk.attach.allowAttachSelf`

It limited the modules only to "jdk.attach". But in the FIPS mode, the SecureRandom must come from the provider SunPKCS11, which is in the module "jdk.crypto.cryptoki". So, that is why in this test, no matter in FIPS mode or not, the provider SunPKCS11 can not be initialized.

When we change this command to the following, by adding the  module "jdk.crypto.cryptoki" in the limit modules list.

`* @run main/othervm **--limit-modules jdk.attach,jdk.crypto.cryptoki -Djdk.attach.allowAttachSelf`

The test passed in the FIPS mode.

**Comment by taoliult** [comment]
@JasonFengJ9

The root cause about this failure is updated in the last comment. Do you think, if the test case need to be updated with "--limit-modules jdk.attach,jdk.crypto.cryptoki"? Please advice. Thanks.

**Comment by pshipton** [comment]
@taoliult Why do you say "no matter in FIPS mode or not".
> So, that is why in this test, no matter in FIPS mode or not, the provider SunPKCS11 can not be initialized.

**Comment by JasonFengJ9** [comment]
> So, that is why in this test, no matter in FIPS mode or not, the provider SunPKCS11 can not be initialized.

Assuming this refers `java/lang/Class/GetPackageBootLoaderChildLayer.java` which is excluded for JDK20/19/18/19 for all platforms, `windows-x64` for JDK11. Do you have a grinder showing JDK11 non-FIPS mode failure? 

It appears this test was excluded for RI (hotspot) on `macosx-all` only, can you confirm its behaviour at `x86-64_linux`?

**Comment by taoliult** [comment]
@JasonFengJ9  In the JDK11 non-FIPS mode, this test passed.

**Comment by pshipton** [comment]
Does adding `jdk.crypto.cryptoki` break the test in non-FIPS mode?

**Comment by taoliult** [comment]
@pshipton In non-FIPS mode, for this test "java/lang/Class/GetPackageBootLoaderChildLayer.java", adding `jdk.crypto.cryptoki` into the `--limit-modules` or not, the result all passed. Because in non-FIPS mode, SecureRandom will be initialized from provider SUN.

**Comment by pshipton** [comment]
Sounds good to update the test case with `jdk.crypto.cryptoki` then, so it can pass in FIPs mode.

**Comment by pshipton** [comment]
When you make the update, pls add a comment to explain the change.

**Comment by taoliult** [comment]
@vij-singh @pshipton @alon-sh 
Made the test code changes and rerun the Grinder tests to double confirm the changes work. Once the Grinder tests done, I will then create the PR for this test code changes.

**Comment by taoliult** [comment]
@vij-singh @pshipton @alon-sh
PR https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/557 created, please help to review.

Grinder test result before update the test case:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/26008/

Grinder test result after update the test case:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/26013/

**Comment by pshipton** [comment]
Moving this forward while we update test cases for the various versions.

**Comment by vij-singh** [comment]
@taoliult  Have all the various versions been updated? Of not, which versions are left?

**Comment by taoliult** [comment]
@vij-singh

JDK11, 17, 19 and Next are updated with this test code changes. PR as follow, they are all merged.

JDK11 PR https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/557
JDK17 PR https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/136
JDK19 PR https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/21
JDK Next PR https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/480

**Comment by pshipton** [comment]
18 is out of service. Assuming 8 doesn't need to be updated. This is complete.
