### ISSUE TITLE
JDK11 jdk_nio_0_FAILED Compilation failed cannot find symbol: class ExType

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15105]
Failure link
------------

From an internal build `job/Test_openjdk11_j9_extended.openjdk_s390x_linux/71/`:
```
java version "11.0.16" 2022-07-19
IBM Semeru Runtime Certified Edition 11.0.16+3 (build 11.0.16+3)
Eclipse OpenJ9 VM 11.0.16+3 (build master-00bc246e2, JRE 11 Linux s390x-64-Bit Compressed References 20220520_299 (JIT enabled, AOT enabled)
OpenJ9   - 00bc246e2
OMR      - 42677ec34
JCL      - dbbf417306 based on jdk-11.0.16+3)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_nio_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F299%2Fibm-semeru-certified-testimage_s390x_linux_JDK11U_2022-05-21-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F299%2Fibm-semeru-certified-jdk_s390x_linux_JDK11U_2022-05-21-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F299%2Fibm-semeru-certified-jre_s390x_linux_JDK11U_2022-05-21-01-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-s390x-openj9-IBM%2F299%2Fibm-semeru-certified-debugimage_s390x_linux_JDK11U_2022-05-21-01-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-05-21T02:30:44.518Z] variation: Mode150
[2022-05-21T02:30:44.518Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-05-21T02:34:50.762Z] TEST: java/nio/file/Files/probeContentType/Basic.java

[2022-05-21T02:34:50.763Z] /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/nio/file/Files/probeContentType/Basic.java:99: error: cannot find symbol
[2022-05-21T02:34:50.763Z]     static int checkContentTypes(ExType[] exTypes)
[2022-05-21T02:34:50.763Z]                                  ^
[2022-05-21T02:34:50.763Z]   symbol:   class ExType
[2022-05-21T02:34:50.763Z]   location: class Basic
```
This is a recent regression cross platforms (last weekly run passed on April 27th), appears test related.

**Comment by pshipton** [comment]
ExType is defined later in the same file.
`    record ExType(String extension, List<String> expectedTypes) { }`

**Comment by pshipton** [comment]
`record` is only applicable to jdk17+, not sure why this test exists in this form in jdk11. It must not have been there last week.

**Comment by pshipton** [comment]
There was a change in the test https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/33f59394fd7 that added this, but it's been there since 11.0.16+1

**Comment by pshipton** [comment]
Oh I see, "last weekly run" from April 27 was quite some time ago, 11.0.16+1 was promoted after May 4. https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/516

**Comment by pshipton** [comment]
Seems we should patch the test until OpenJDK decides to fix it. Created https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/530
