### ISSUE TITLE
Floating Point Correction Clarification.

### ISSUE THREAD

**Issue by PowerUser1234** [eclipse-openj9/openj9#15110]
This is a reply to the last statement at the end of
[https://github.com/eclipse-openj9/openj9/issues/15102](https://github.com/eclipse-openj9/openj9/issues/15102)
from **pshipton**

Yes, but the problem is that the OpenJDK and JCP have abjectly turned down fixing these errors.  Therfore, if the nominated matter is an important change, even a bug to be fixed, despite what Oracle has ruled, the only choice this necessary matter has is with another vendor.

And it is a bug fix, because in the practical world, without initial philosophies about accuracy tradeoff, there is a need 
for context accuracy which can be found in [Rational Numbers](https://en.wikipedia.org/wiki/Rational_number), because results need to be entirely true or otherwise, in order to be relied on.  Since in context, you can't always partially rely on something, you need to be able to entirely rely upon it. This logic in mathematics and computer science spills over to absolutely anything in the real world.  The present workarounds are a waste of memory and slow things down.  What really should happen is that the root of the floating point problem should be dealt with itself.

I have suggested that floating point bug repairs can be done in an entirely dual mode, compatible way.  That includes the content and behaviour of all classes and interfaces.  With their content rendered compatible, there would be no deletion involved.  Just additional logic put in of the form

```
if(switch_on)
{//correct floating point behaviour}
else
{//original, denormal or pronormal vulnerable floating point behaviour}

```

The other thing, is that the example C++ compute and display results, certainly in double, which is entirely accurate with the Java double range, and therefore the Java float range.

```
******************************************
C++ Ranges  
double:    64 bits, 2.3E-308 to 1.7E+308

Java Ranges
float:     32 bits, 3.4e-038 to 3.4e+038 
double:    64 bits, 1.7e-308 to 1.7e+308 
******************************************
```

**The C++ floating point double, SSE enabled rangle totally encapsulates the Java floating point, non-SSE double and float ranges. The intial view for the C++ outputs of its float and double can be seen as a range right there, and could be made into fixed ranges with no problems, shaving off further values and value degredations as it first seems to do, which can also be implemented concretely.  C++ uses SSE and offsets its double range degrading entirely further out of Java ranges than Java(!).  
GNU C++ has all of its code right there to find.  For my example I used TDM C++, which is effectively a GNU effort.**

**This C++ behaviour can be made has a hard and fast Java-equal range for Java double, and float too.  This is what my example attempts to show, but that these statements here qualify more clearly and completely.**

Is the eclipse-openj Java team able to update its JDK and JRE offerings for all platforms, to either repair at default or at capability, these floating point logic errors and computer bugs, from within the roots of the OpenJDK Java language, itself?

**Comment by pshipton** [comment]
> the OpenJDK and JCP have abjectly turned down fixing these errors

Then you can expect the same answer here. Like I said, OpenJ9 depends on OpenJDK.
