### ISSUE TITLE
extensions PR build with depends not working

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15125]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/533#issuecomment-1138734273
Is there something wrong with
`jenkins compile amac jdk11 depends eclipse-openj9/openj9#v0.33.0-release eclipse-openj9/openj9-omr#v0.33.0-release`?

https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_mac_Personal/96/console
```
ERROR: Cannot parse dependent change: 'eclipse-openj9/openj9#v0.33.0-release'
```

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
I think I broke this in #14995. It only allows numbers now and not branch names. It should be a simple fix.
