### ISSUE TITLE
OpenJDK java/lang/System/PropertyTest stdout.encoding expected to not be null

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15129]
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_x86-64_windows_Personal/1/
java/lang/System/PropertyTest.java
```
13:19:24  test PropertyTest.checkRequiredProperties("stdout.encoding"): failure
13:19:24  java.lang.AssertionError: stdout.encoding expected object to not be null
13:19:24  	at org.testng.Assert.fail(Assert.java:99)
13:19:24  	at org.testng.Assert.assertNotNull(Assert.java:942)
13:19:24  	at PropertyTest.checkRequiredProperties(PropertyTest.java:231)

13:19:24  test PropertyTest.checkRequiredProperties("stderr.encoding"): failure
13:19:24  java.lang.AssertionError: stderr.encoding expected object to not be null
13:19:24  	at org.testng.Assert.fail(Assert.java:99)
13:19:24  	at org.testng.Assert.assertNotNull(Assert.java:942)
13:19:24  	at PropertyTest.checkRequiredProperties(PropertyTest.java:231)

```

**Comment by pshipton** [comment]
From build +20:
"New system properties for System.out and System.err ([JDK-8283620](https://bugs.openjdk.java.net/browse/JDK-8283620))
core-libs/java.lang

Two new system properties, stdout.encoding and stderr.encoding, have been added. The value of these system properties is the encoding used by the standard output and standard error streams (System.out and System.err).

The default values of these system properties depend on the platform. The values take on the value of the native.encoding property when the platform does not provide streams for the console. The properties can be overridden on the launcher's command line option (with -D) to set them to UTF-8 where required."

**Comment by babsingh** [comment]
The test needs to be re-enabled:
- JDK19: https://github.com/adoptium/aqa-tests/blob/a74405ca1262c4e50ea0a88e9cb27ade2dd60179/openjdk/excludes/ProblemList_openjdk19-openj9.txt#L126
- JDK20: https://github.com/adoptium/aqa-tests/blob/a74405ca1262c4e50ea0a88e9cb27ade2dd60179/openjdk/excludes/ProblemList_openjdk20-openj9.txt#L131

**Comment by pshipton** [comment]
Re-including via https://github.com/adoptium/aqa-tests/pull/4191

**Comment by pshipton** [comment]
Tests are unexcluded.
