### ISSUE TITLE
Clarification/Inquiry about Floating Point Behaviour Correction?

### ISSUE THREAD

**Issue by PowerUser1234** [eclipse-openj9/openj9#15123]
This message is a reply to the statement towards the bottom of 
[https://github.com/eclipse-openj9/openj9/issues/15110](https://github.com/eclipse-openj9/openj9/issues/15110)
from **pshipton**.

What I have said is that the corrections that I have tried to propose can be implemented with full, previous compatability.
Either from a patch program installer, or from within the JRE or JDK themselves.

[https://github.com/eclipse-openj9/openj9/issues/15102](https://github.com/eclipse-openj9/openj9/issues/15102)
**Floating Point correction doesn't mean that only the default behaviour be changed. It can be done compatibility.**

and again, at:

[https://github.com/eclipse-openj9/openj9/issues/15110](https://github.com/eclipse-openj9/openj9/issues/15110)
**I have suggested that floating point bug repairs can be done in an entirely dual mode, compatible way.**

It is possible for you to maintain a reliance on the OpenJDK entirely, through a dual mode compatability approach to floating point arithmetic and StrictMath elementary function methods repair.  You need not have do delete or object edit anything that comes from the OpenJDK, because you will always have the option to use code blocks like this:

**if(switch_on)
{//correct floating point behaviour}
else
{//original, denormal or pronormal vulnerable floating point behaviour}**

to include the original and the updated content.

In light of all this, is it possible to reconsider my proposition, since a flexability posture is possible, both in reliance to the OpenJDK, and IEEE 754 as well, using these sorts of means?

**Comment by DanHeidinga** [comment]
@PowerUser1234 One way to gain traction for a change like this is to implement it as a library with a liberal license and share it on github / maven / etc so that it's easy to get access to.

Adoption by a broad section of the Java community will first fix the behaviour for users of the library and second show that there is a strong desire for your correct floating point behaviour.

Once there's broad demand for such a change, it will provide motivation for the JVM runtimes to change.

I'd also suggest taking a long hard look at why the OpenJDK community rejected the proposal as that will help guide how you develop your library and your next steps in this process.

At this time, OpenJ9 won't be pursuing this change.

**Comment by PowerUser1234** [comment]
I have already considered this, however we involved are not C, C++ or Assembly language programmers.  We do not know about the bindings involved, we do not know enough about CPU or RAM hardware either.  We aren't software engineers of systems engineers. **As will follow here, these things should really have to be a problem, either.**

```
Once there's broad demand for such a change, it will provide motivation for the JVM runtimes to change.

I'd also suggest taking a long hard look at why the OpenJDK community rejected the proposal as that will help guide how you develop your library and your next steps in this process.
```
BigInteger and BigDecimal work arounds are slower, and are a waste of memory. Where range accuracy is needed, the reasonable approach is a repaired float and double, and a repaired StrictMath.

This kind of consideration, we have in fact over-done.  Floating Point is originally defined by the fact that the position of the decimal point, the dot separator, is worried about in a number value after the resolution of arithmetic. The idea of value approximation is perhaps only one way of looking at values, if with enough speed and storage space in a computer, that idea is as valid, which it isn't, because of the secondary possibility, being range accuracy.  The more objective, more reasonable approach is to consider values as Rational Numbers as possessing a limited precision, which is a range limit, with every digit remaining accurate. 

Value range accuracy should be considered directly in terms of application to the real world phenomenon, the software is involved with.  IEEE 754, and the Java Community Process, simply don't have anything to do with these deeper truths, which should be considered earlier than floating point 'accuracy tradeoffs'.  In a real way, the demand for such a change isn't strictly really relevant either.  Such demand has existed for a long time, however people haven't come forward about it.  What is more important is the deeper reasoning involved.  To say nothing of a dual, compatibility mode of operation, allowing programmers to work with either mode.

**OpenJDK Floating Point Errors are precisely that, errors.  They are a computer bug, a logic error.  Given the Free Open Source Software nature of the OpenJDK, along with the fact that the real source of these errors is the vendor, it is natural that the vendor aught repair these errors in a concomitant manner.  Floating Point denormal and pronormal values in the digit in the last place just aren't as rational as total range accuracy, which other FOSS languages have implemented in improved hardware and just as rapidly. 
Even GNU C++ has done differently, and has released the code involved.  It simply makes improved sense on its own that such an improved should be, wrought, on its own, anyway, despite the present broader circumstances around this matter.**

Are eclipse-openj9 able to reconsider this things in another light?

**Comment by DanHeidinga** [comment]
The Java ecosystem benefits from standardization.  Changes to how floating point works would violate the standard and make OpenJ9 incompatible.  This isn't something we're willing to do.  

The path forward is as I explained above - to produce a library that offers the semantics you want and drive community adoption of it.  That will help convince the broader java community of the necessity of your approach.

**Comment by PowerUser1234** [comment]
The IEEE 754 standard doesn't say anything about floating point denormal and pronormal values, or how to deal with them or not.  This is why C++ has allowed for SSE and SSE2 use.   Therefore removing floating point errors from representation, arithmetic, and StrictMath methods to another result and its representation, doesn't violate any particular standard.

The change involved needn't be an incompatability. It could have some manner of mode switch, so that developers can implement one mode or the other.  To Java programs operating in seperate moves could still communiate with one another, 
just as can happen now between two classes, because the storage of the internal binary for float and double would be the same.
Presuming that any manner of syntax options, like the annotation, doesn't allow for things like floating point behaviour to be specified per method or per field.

What do people over there think about this, or how do they respond to me, here?

**Comment by DanHeidinga** [comment]
@PowerUser1234 You're asking a lot of people to do a tremendous amount of work to maintain compatibility while providing an additional mode for floating point that you prefer. 

If you want this to move forward, you need to build the consensus around it.  I've already explained a path to do that.

We're not going to implement this proposal without seeing that broad demand.
