### ISSUE TITLE
Incorrect native method return type causes a segfault that doesn't occur with HotSpot

### ISSUE THREAD

**Issue by itsTyrion** [eclipse-openj9/openj9#15142]
I noticed that, if the return type of a native (JNI) method is specified incorrectly, e.g. `byte[]` for a `void` method, a HotSpot VM throws a NPE with stacktrace, while an OpenJ9 VM segfaults.
![image](https://user-images.githubusercontent.com/17730120/171032081-35c71baf-34c5-445b-8e33-6f02cda232d0.png)
![image](https://user-images.githubusercontent.com/17730120/171032114-6ee4fe3a-becb-4204-9983-2af719a72088.png)

`-Xcheck:jni` doesn't seem to fix the issue

**OS**: Windows 10 LTSC 21H2
**Java HotSpot**: Eclipse Temurin; build 11.0.15+10
**Java OpenJ9** : IBM Semeru; build 11.0.15+10 (OpenJ9 - 9a84ec34e)
Dump: https://v.itstyrion.de/random/dump.7z (and .zip if you cannot open 7z for some reason)

Example code:
```rust
use jni::JNIEnv;
use jni::objects::JClass;

#[no_mangle] // function without return, basically void
pub extern "C" fn Java_Main_wrongNativeType(_: JNIEnv, _: JClass) {
    println!("kaboom");
}
```
```java
final class Main {
    static native byte[] wrongNativeType();

    public static void main(String... args) {
        load();
        System.out.println("hello");
        wrongNativeType();
    }

    static void load() {
        var os = System.getProperty("os.name").toLowerCase(Locale.ROOT);
        var ext = os.contains("win") ? ".dll" : os.contains("mac") ? ".dylib" : ".so";
        try {
            try (InputStream is = Main.class.getResourceAsStream("/mylib" + ext)) {
                File file = File.createTempFile("lib", ext);
                Files.write(file.toPath(), Objects.requireNonNull(is, "Native lib not found in jar!").readAllBytes());
                System.load(file.getAbsolutePath());
                new Thread(() -> {
                    try { Thread.sleep(100); }
                    catch (InterruptedException ignored) {}
                    file.delete();
                });
            }
        } catch (IOException ex) {
            System.out.println("Error during initialization: " + ex.getMessage());
            System.exit(1);
        }
    }
}
```
[Precompiled jar with .so/.dll/.dylib(x64) (zipped bc GH wants .zip)](https://github.com/eclipse-openj9/openj9/files/8799786/untitled-1.0.jar.zip)
[IntelliJ Project if you don't trust the jar](https://github.com/eclipse-openj9/openj9/files/8799718/untitled.zip)

**Comment by gacholio** [comment]
This is not a VM error. If Hotspot survives this, it's purely by chance.
