### ISSUE TITLE
DDR not working on alinux64 cent8 -Xnocompressedrefs

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15140]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/834
Tested on the latest nightly build.
Re-run link:
https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?TARGET=testList+TESTLIST=cmdLineTester_GCCheck_0,testDDRExtJunit_MonitorsAndDeadlock3_0,testDDRExtJunit_MonitorsAndDeadlock4_0&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK8_aarch64_linux_Nightly%2F174%2FOpenJ9-JDK8-aarch64_linux-20220527-232722.tar.gz&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&JDK_VERSION=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=&OPENJ9_BRANCH=rmdeprecated&OPENJ9_SHA=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Fpshipton%2Fopenj9.git&UPSTREAM_JOB_NAME=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=sw.os.cent.8&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=&JDK_IMPL=&AUTO_DETECT=true&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=AdoptOpenJDK%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&BUILD_LIST=functional&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=AdoptOpenJDK%3Amaster&JDK_VENDOR=&JVM_OPTIONS=&PARALLEL=None

The following DDR tests are failing on alinux64 cent8 machines with -Xnocompressedrefs.
cmdLineTester_GCCheck_0
testDDRExtJunit_MonitorsAndDeadlock3_0
testDDRExtJunit_MonitorsAndDeadlock4_0

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Grinder/834/functional_test_output.tar.gz

The cmdLineTester_GCCheck_0 test shows the problem.
```
Running command: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core.dmp
Time spent starting: 3 milliseconds
Time spent executing: 16596 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Warning: dump file was produced by a different, possibly incompatible, VM.
 [OUT]   core file: (unknown)
 [OUT]   this VM:   Eclipse OpenJ9 VM
 [OUT] 
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] Available contexts (* = currently selected context) : 
 [OUT] 
 [OUT] Source : file:///home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16539197867328/cmdLineTester_GCCheck_0/j9core.dmp
 [OUT] 	*0 : PID: 2373518 : No JRE
```

**Comment by pshipton** [comment]
The problem doesn't show up in the nightly builds, although they also run on cent8 machines.
I didn't duplicate the problem with jdk11 either, https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/835/

**Comment by keithc-ca** [comment]
The problem is that when the executable is available, its sections are included as part of the virtual address space of the process image and may conflict with virtual addresses defined by the core file.
