### ISSUE TITLE
Loom: JIT Pinning support

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15175]
See https://github.com/eclipse-openj9/openj9/issues/15174

Depends on https://github.com/eclipse-openj9/openj9/issues/15172

Part 1: Basic Pinning support
- JNI callout increment counter, decrement when callout frame is popped
    - Only need to worry about direct JNI transitions from JIT, if it goes through interpreter VM will handle it
- monenter increment counter, vice versa on monexit (same for sync methods)
- Object.wait inc counter on entry, vice versa on exit
    - VM will handle fastJNI case. If the JIT doesnt treat this as an instrinsic there may be nothing to do here

Part 2: Exception throws
- There is a JIT optimization that converts exception throws to gotos, if this doesnt cross synchronization blocks there may be nothing to do here since real exception throws call a VM runtime helper

**Comment by tajila** [comment]
FYI @0xdaryl

**Comment by 0xdaryl** [comment]
A couple of initial questions:

1) Just to confirm, is `pinnedStateCounter` in the `J9VMThread` the counter that needs to be incremented/decremented?
```
typedef struct J9VMThread {
    ...
    J9VMContinuation *currentContinuation
    UDATA pinnedStateCounter
    j9object_t carrierThreadObject;
...
}
```

2) Is a check required at runtime that the thread is a virtual thread, or is this counter bumped for both virtual and platform threads?  If yes, then how do we distinguish these kinds of threads at runtime?

**Comment by tajila** [comment]
> Just to confirm, is pinnedStateCounter in the J9VMThread the counter that needs to be incremented/decremented?

Yes, that is correct

> Is a check required at runtime that the thread is a virtual thread, or is this counter bumped for both virtual and platform threads? If yes, then how do we distinguish these kinds of threads at runtime?

The counter is only bumbed if a VirtualThread is mounted. We can supply a jit runtimehelper to query if there is a mounted virtualThread, would that be sufficient?

**Comment by 0xdaryl** [comment]
> The counter is only inc/dec if a VirtualThread is mounted. We can supply a jit runtimehelper to query if there is a mounted virtualThread, would that be sufficient?

Ideally this would be a cheap test we could do inline at runtime, like checking a bit on the VMThread.  Calling out to a helper at every monent/exit may become prohibitively expensive.  Is this kind of check straightforward to expose to JITed code?

**Comment by tajila** [comment]
> Ideally this would be a cheap test we could do inline at runtime, like checking a bit on the VMThread. Calling out to a helper at every monent/exit may become prohibitively expensive. Is this kind of check straightforward to expose to JITed code?

We can add a bit to the privateFlags to indicate when a VirtualThread is mounted

**Comment by tajila** [comment]
> Is there a runtime command-line option to check as well to enable this logic?

Yes, youll also need to check `--enable-preview` with something like:

```
J9_ARE_ANY_BITS_SET(currentThread->javaVM->extendedRuntimeFlags2, J9_EXTENDED_RUNTIME2_ENABLE_PREVIEW)
```

**Comment by tajila** [comment]
@zl-wang @0xdaryl We recently decided that we will need different counters for native, monitor and object.wait() pinning as we need to be able to determine the reason for pinning

**Comment by tajila** [comment]
```
public enum Pinned {
     NATIVE,
    MONITOR,
   CRITICAL_SECTION 
}
```

**Comment by 0xdaryl** [comment]
Have the counter fields been created yet (if so, what are they named) and is the VMThread private flag available yet?  Thanks.

**Comment by babsingh** [comment]
> Have the counter fields been created yet (if so, what are they named) and is the VMThread private flag available yet?

No for both.
- I will soon have details for the counter fields documented in https://github.com/eclipse-openj9/openj9/issues/15174.
- A private flag to track if a VirtualThread is running (mounted) will be added as part of https://github.com/eclipse-openj9/openj9/issues/15177.

**Comment by babsingh** [comment]
Adding counters and virtual thread mounted flag via https://github.com/eclipse-openj9/openj9/pull/15383.

**Comment by 0xdaryl** [comment]
There are also circumstances where we don't create a JNI callout frame, namely when `J9_FAST_NO_NATIVE_METHOD_FRAME` is set.  Does `callOutCount` need to be incremented even when we don't create a callout frame?

**Comment by babsingh** [comment]
> When incrementing callOutCount for JNI dispatch, does it make any difference if the count is updated before or after VM access is released?

We only want to cover the area where the call-out happens. [Assumption] VM access is not part of the call-out; it refers to being in the VM. So, it won't make any difference if the count is updated before or after VM access is released. 

>  Does callOutCount need to be incremented even when we don't create a callout frame?

The frames are only used to easily identify the call-out locations. If a call-out happens without a frame, we will still need to cover it.

@gacholio Can you please confirm the above answers?

**Comment by gacholio** [comment]
> Does `callOutCount` need to be incremented even when we don't create a callout frame?

Hadn't considered fast JNI, but I think the answer is no. With no frame, we will presumably not do a blocking operation in the native.

The scheduler must already be resilient to the inherent inaccuracy of asking if a continuation is pinned (i.e. the answer to the question may well change immediately after the call returns).

I believe the counter only needs to be accurate if we are going to block. @babsingh Does this make sense?

**Comment by gacholio** [comment]
> The frames are only used to easily identify the call-out locations. If a call-out happens without a frame, we will still need to cover it.

I don't really understand what you're saying here, but I think my response above covers it. We do not need to be able to identify callout/in locations for purposes of pinning, that's what the counters are for.

**Comment by 0xdaryl** [comment]
Thanks for the clarification @gacholio and @babsingh.

In the case of monent/monexit, the JIT runtime may delegate to a helper to perform the acquire/release (`jitMonitorEntry` and `jitMonitorExit`).  Can you confirm that those helpers will guarantee to either ALWAYS inc/dec the counters or NEVER inc/dec the counters (leaving it to the JITed code)?  I'd check myself but the code hasn't been implemented yet.

**Comment by gacholio** [comment]
The helpers will always manage the counters. Only if you are modifying the lockword field in compiled code do you need to do it.

**Comment by babsingh** [comment]
> Does this make sense?

Yes, that the frames will be reason for the blocking operation. Initially, I had assumed that the frames just pin-pointed the locations where we are going to block.
