### ISSUE TITLE
Loom: j.l.Thread native support

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15176]
Add implementations and tests for:

Java_java_lang_Thread_currentCarrierThread
- this will need a new field on j9vmthread which will have to be added to the GC list of objects to track

Java_java_lang_Thread_setCurrentThread
- this sets vmthread->threadObject
- this may need a cINL and fastJNI since its called frequently

Java_java_lang_Thread_extentLocalCache
- this will need a new field on j9vmthread, will need to be tracked by GC

Java_java_lang_Thread_setExtentLocalCache
- set vmthread->extentLocalCache

Java_java_lang_Thread_dumpThreads
- dumps StackTraceElemets[] for the given threads

Java_java_lang_Thread_getThreads
- returns all threads
- will need to determine if this includes virtual threads as well

Java_java_lang_Thread_getNextThreadIdOffset
- we will need to verify the behaviour of this

**Comment by JasonFengJ9** [comment]
> we need the first 4 as soon as https://github.com/eclipse-openj9/openj9/pull/15073 is merged

I already have following:
```
Implemented JVM_IsPreviewEnabled(),
Java_java_lang_Thread_setCurrentThread(),
Java_java_lang_Thread_extentLocalCache(),
Java_java_lang_Thread_setExtentLocalCache().
```
will add `Java_java_lang_Thread_currentCarrierThread`.

**Comment by JasonFengJ9** [comment]
Created a draft https://github.com/eclipse-openj9/openj9/pull/15219

>Java_java_lang_Thread_currentCarrierThread
this will need a new field on j9vmthread which will have to be added to the GC list of objects to track

Existing `Java_java_lang_Thread_currentCarrierThread` uses `J9VMThread->threadObject`, how about something like `carrierThreadObject`?

> Java_java_lang_Thread_setCurrentThread
this may need a cINL and fastJNI since its called frequently

Will add cINL & fastJNI.

**Comment by tajila** [comment]
>  how about something like carrierThreadObject?

yes we will need to add that

**Comment by fengxue-IS** [comment]
closing as all mentioned native methods have been implemented
