### ISSUE TITLE
Loom: GC Thread scanning

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15179]
Depends on https://github.com/eclipse-openj9/openj9/issues/15178

Threads should be scanned as they normally would. If a thread is mounted with a VirtualThread, then the virtual thread stack will be scanned, the carrier thread stack will be stored in a continuation instance.

All continuation objects will have a stack that can be found with the vmref field. These stacks should be scanned just as a regular platform thread would be.

We also need to consider concurrent aspects in regards to scanning. What happens if the GC is doing a concurrent scan and the VirtualThread attempts to mount/unmount? Perhaps we need a mechanism to block a mount/unmount operation while a thread stack is being scanned.

**Comment by tajila** [comment]
FYI @dmitripivkine @gacholio @amicic

**Comment by LinHu2016** [comment]
Currently GC use javaVM->walkStackFrames(vmThread, &stackWalkState) to scan StackObject in J9VMThread (set J9_STACKWALK_ITERATE_O_SLOTS flag and oSlotIterator callback in stackWalkState), now GC also need to scan stackOject in J9VMContinuation, but looks walkStackFrames() only check "walkthread", could VM side please update walkStackFrames() also handle J9VMContinuation case? Thanks

**Comment by tajila** [comment]
The plan is that when the GC needs to do a stackwalk it will stack allocate a J9VMThread then copy all the fields from the continuation into it.
