### ISSUE TITLE
Loom: JNI support

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15182]
Depends on https://github.com/eclipse-openj9/openj9/issues/15172

Implement `IsVirtualThread` 

See https://download.java.net/java/early_access/jdk19/docs/specs/jni/index.html

**Comment by babsingh** [comment]
I had confused the `JVM_*` methods with `JNI` methods. We have only added stubs for the below methods:
```
JVM_RegisterContinuationMethods
JVM_IsContinuationsSupported
JVM_IsPreviewEnabled
JVM_VirtualThreadMountBegin
JVM_VirtualThreadMountEnd
JVM_VirtualThreadUnmountBegin
JVM_VirtualThreadUnmountEnd
```
Which issue tracks the implementation of the above methods?

Will OpenJ9 also require the below methods?
```
JVM_CurrentCarrierThread
JVM_SetCurrentThread
JVM_GetNextThreadIdOffset
JVM_GetStackTrace
JVM_ExtentLocalCache
JVM_SetExtentLocalCache
JVM_SetStackWalkContinuation
```

**Comment by tajila** [comment]
The virtualThread ones are not needed right now, we will need those later for tooling and event handling support. The most of the rest are already implemented.

**Comment by fengxue-IS** [comment]
closing this issue as `IsVirtualThread` change has been merged, rest of the `JVM_*` methods are not required by OpenJ9's implementation. If Loom requires new JNI functions in the future, those will be tracked in a new issue.
