### ISSUE TITLE
JDK19 jdk_util_0_FAILED java/util/Locale/LanguageSubtagRegistryTest.java & LSRDataTest.java 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15188]
Failure link
------------

From an internal build `view/Test_grinder/job/Grinder/24367/`(`ub18-aarch64-9`):
```
09:25:08  openjdk version "19-internal" 2022-09-20
09:25:08  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
09:25:08  Eclipse OpenJ9 VM (build loom_patch-5264b46c002, JRE 19 Linux aarch64-64-Bit Compressed References 20220531_29 (JIT enabled, AOT enabled)
09:25:08  OpenJ9   - 5264b46c002
09:25:08  OMR      - e8fbaa89d50
09:25:08  JCL      - a66f9edf71a based on jdk-19+24)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=sanity&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F29%2FOpenJ9-JDKnext-aarch64_linux-20220531-212225.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F29%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=loomexcludes&ARTIFACTORY_NUM_ARTIFACTS=60&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=next&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
10:08:40  ===============================================
10:08:40  Running test jdk_util_0 ...
10:08:40  ===============================================
10:08:40  jdk_util_0 Start Time: Wed Jun  1 10:08:40 2022 Epoch Time (ms): 1654092520366

10:08:40  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
10:08:40  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

10:13:05  TEST: java/util/Locale/LanguageSubtagRegistryTest.java

10:13:05      language parse() test failed.
10:13:05  java.lang.RuntimeException: Failed.
10:13:05  	at LanguageSubtagRegistryTest.main(LanguageSubtagRegistryTest.java:166)
10:13:05  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:13:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
10:13:05  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:13:05  	at java.base/java.lang.Thread.run(Thread.java:1555)
10:13:05  
10:13:05  JavaTest Message: Test threw exception: java.lang.RuntimeException
10:13:05  JavaTest Message: shutting down test
10:13:05  
10:13:05  STDOUT:
10:13:05  Test LanguageRange class parse method...
10:13:05    test_parse() failed.
10:13:05  Test Locale class methods...
10:13:05    test_filter() passed.
10:13:05    test_filterTags() passed.
10:13:05    test_lookup() passed.
10:13:05    test_lookupTag() passed.
10:13:05  
10:13:05  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed.

10:13:05  TEST: java/util/Locale/LSRDataTest.java

10:13:05  STDERR:
10:13:05  java.lang.RuntimeException: [FAILED: Size of the priority list does not match, Expected size=725]
10:13:05  	at LSRDataTest.checkEquality(LSRDataTest.java:361)
10:13:05  	at LSRDataTest.main(LSRDataTest.java:77)
10:13:05  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:13:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
10:13:05  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:13:05  	at java.base/java.lang.Thread.run(Thread.java:1555)
10:13:05  
10:13:05  JavaTest Message: Test threw exception: java.lang.RuntimeException
10:13:05  JavaTest Message: shutting down test
10:13:05  
10:13:05  
10:13:05  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: [FAILED: Size of the priority list does not match, Expected size=725]
10:13:05  --------------------------------------------------
10:20:04  Test results: passed: 853; failed: 2
10:20:07  Report written to /home/jenkins/workspace/Grinder/jvmtest/openjdk/report/html/report.html
10:20:07  Results written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16540900451365/jdk_util_0/work
10:20:07  Error: Some tests failed or other problems occurred.
10:20:08  
10:20:08  jdk_util_0_FAILED
```
This doesn't appear project loom related.

**Comment by pshipton** [comment]
Passing on a later build. I will un-exclude.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/999 - java/util/Locale/LanguageSubtagRegistryTest.java
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1000 - java/util/Locale/LSRDataTest.java

**Comment by pshipton** [comment]
Created https://github.com/adoptium/aqa-tests/pull/3782
