### ISSUE TITLE
JDK19 jdk_security3_1_FAILED sun/security/util/Resources/Usages.java RuntimeException: Unused keys: [enter.dname.components, no.field.in.dname]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15209]
Failure link
------------

From an internal build `job/Grinder_testList_0/931/consoleFull`(`ub20x64rt1-5`):
```
11:17:02  openjdk version "19-internal" 2022-09-20
11:17:02  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextx86-64linuxPersonal)
11:17:02  Eclipse OpenJ9 VM (build loom_patch-5264b46c002, JRE 19 Linux amd64-64-Bit Compressed References 20220531_1000 (JIT enabled, AOT enabled)
11:17:02  OpenJ9   - 5264b46c002
11:17:02  OMR      - e8fbaa89d50
11:17:02  JCL      - a66f9edf71a based on jdk-19+24)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=-f+parallelList.mk+testList_0&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Grinder&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F1000%2FOpenJ9-JDKnext-x86-64_linux-20220531-190019.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_NUM_ARTIFACTS=60&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&USE_JRE=false&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=next&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=customized&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=24450&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&OPENJDK_SHA=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
11:21:37  ===============================================
11:21:37  Running test jdk_security3_1 ...
11:21:37  ===============================================
11:21:37  jdk_security3_1 Start Time: Thu Jun  2 08:21:35 2022 Epoch Time (ms): 1654183295496
11:21:37  "/home/jenkins/workspace/Grinder_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Grinder_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
11:21:37  JVMSHRC005I No shared class caches available
11:21:37  JVMSHRC005I No shared class caches available
11:21:37  cache cleanup done
11:21:37  variation: Mode650
11:21:37  JVM_OPTIONS:  -XX:-UseCompressedOops 

12:49:19  TEST: sun/security/util/Resources/Usages.java

12:49:19  STDERR:
12:49:19  java.lang.RuntimeException: java.lang.RuntimeException: Unused keys: [enter.dname.components, no.field.in.dname]
12:49:19  	at Usages.check(Usages.java:194)
12:49:19  	at java.base/java.util.Map.forEach(Map.java:716)
12:49:19  	at Usages.main(Usages.java:141)
12:49:19  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
12:49:19  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
12:49:19  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
12:49:19  	at java.base/java.lang.Thread.run(Thread.java:1555)
12:49:19  Caused by: java.lang.RuntimeException: Unused keys: [enter.dname.components, no.field.in.dname]
12:49:19  	at Usages.check(Usages.java:191)
12:49:19  	... 6 more
12:49:19  
12:49:19  JavaTest Message: Test threw exception: java.lang.RuntimeException
12:49:19  JavaTest Message: shutting down test
12:49:19  
12:49:19  
12:49:19  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: java.lang.RuntimeException: Unused keys: [enter.dname.components, no.field.in.dname]
12:49:19  --------------------------------------------------
12:50:44  Test results: passed: 864; failed: 2
12:50:58  Report written to /home/jenkins/workspace/Grinder_testList_1/jvmtest/openjdk/report/html/report.html
12:50:58  Results written to /home/jenkins/workspace/Grinder_testList_1/aqa-tests/TKG/output_16541831511047/jdk_security3_1/work
12:50:58  Error: Some tests failed or other problems occurred.
12:50:58  
12:50:58  jdk_security3_1_FAILED
```

**Comment by pshipton** [comment]
Ignore the bad machines, passing in https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1010
More runs in https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1015

**Comment by pshipton** [comment]
Un-exclude via https://github.com/adoptium/aqa-tests/pull/3791
