### ISSUE TITLE
Panama MemoryAccessAPI: Add jit intrinsic support for vectorizedMismatch

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15204]
The following is used for mismatch operations in MemoryAccessAPIs. The JDK supplies a java implementation which is very slow. We are seeing test failures due to timeouts as a result of this, https://github.com/eclipse-openj9/openj9/issues/13211.

This API takes two arrays (of the same type) and compares each elements until there is a mismatch. This operation is can be applied to all primitive array types, the `log2ArrayIndexScale` denotes which type it is.

```
class jdk.internal.util.ArraySupport {
     @IntrinsicCandidate
     public static int vectorizedMismatch(Object a, long aOffset, Object b, long bOffset, int length, int log2ArrayIndexScale) 
}
```

**Comment by zl-wang** [comment]
hmm ... there is even existing arrayCmp implementations already.  This API has almost identical semantic as arrayCmp, from looking at the source code @r30shah posted in the slack channel.  This can be mapped to arrayCmp somehow before coming to codegen. Pretty good performance.

**Comment by tajila** [comment]
@gita-omr any update on this?

**Comment by gita-omr** [comment]
> @gita-omr any update on this?

Sorry, was busy with another project. I think this is multi-platform issue. 

@r30shah @0xdaryl @knn-k @zl-wang , do you think you can help with z, intel, arm, and p respectively?

**Comment by zl-wang** [comment]
for p, i assigned the implementation to @bhavanisn 

technically, if your platform supports vector byte comparison and counting equal-byte in the right endian (p10 does and pre-p10 need a longer instr sequence), you will have fairly efficient implementations.  the complicated return value for no-mismatching case in implementation can be simplified as follows:
```
        ~((lengthInByte & ((log2ArrayIndexScale<2)?3:7)) >> log2ArrayIndexScale);

               seems correct for all cases as below:
                       log2ArrayIndexScale is 3:  lengthInByte must be divisible by 8, the no-mismatch result destines to be -1;
                       log2ArrayIndexScale is 2:  lengthInByte must be divisible by 4, the only results are possibly -1 or -2;
                       log2ArrayIndexScale is 1:  lengthInByte must be multiple of 2, the only results are also possibly -1 or -2;
                       log2ArrayIndexScale is 0: possible results are -1, -2, -3, and -4.
```

**Comment by r30shah** [comment]
For Z implementation, generated code for  `arrayCmp` [1] and code needed to accelerate `arrayMismatch` would be fairly same except the output value that `arrayMismatch` API returns , which I think can be handled easily. @zl-wang / @bhavanisn  Are you planning to something that that Julian mentioned in https://github.com/eclipse-openj9/openj9/issues/15204#issuecomment-1150239143 ? 

@tajila This one is tagged 0.34/Java19 which might not be the correct target, are we expecting this to be resolved in 0.36? 

[1]. https://github.com/eclipse/omr/blob/cf8ddbd1adcd87e388cad6be1fd0e0c085285a29/compiler/z/codegen/OMRTreeEvaluator.cpp#L11567-L11609

**Comment by zl-wang** [comment]
@r30shah  it is tantalizing to take advantages of the existing arrayCmp implementation for mis-match cases and adding new instructions to calculate the no-mismatch cases.  there are two issues to be followed up though:
1. transforming this call into arrayCmp node in IL (and tagging it as the 3rd scenario of arrayCmp);
2. not sure how arrayCmp for compressed strings complicates the situation. maybe reduce the code readability to such an extent that it is not worth of it.

**Comment by knn-k** [comment]
Is it about generating inlined code for `vectorizedMismatch()`, or calling a JIT helper function for the method?
AArch64 does not have the support for arrayCmp now.

**Comment by zl-wang** [comment]
@knn-k  it is about better implementation/code for vectorizedMismatch() than JIT-compiled code.  there is no dependency on existence of arrayCmp inlined ... that is just a coincidental finding of possible reuse/hint for this implementation.

**Comment by tajila** [comment]
> @tajila This one is tagged 0.34/Java19 which might not be the correct target, are we expecting this to be resolved in 0.36?

Memeroy Access APIs is a preview for JDK19 so we need to be functionally complete. That being said this is technically a perf issue not a functional problem, but we had to disable tests to not hit the timeouts due to poor performance.

We can move it out, if its unfeasible to deliver this in the next month.

**Comment by Spencer-Comin** [comment]
I've done some testing and determined that the following pseudocode is equivalent to `vectorizedMismatch`:
```c
int vectorizedMismatch(byte *a, long aOffset, byte *b, long bOffset, int length, int log2ArrayIndexScale) {
    int lengthInBytes = length << log2ArrayIndexScale;
    int mask = (log2ArrayIndexScale<<1) | 3;
    int n = lengthInBytes & ~(mask);
    int res = arrayCmpLen(a+aOffset, b+bOffset, n);
    if (res == n) // no mismatch found
        return ~((lengthInBytes & mask) >> log2ArrayIndexScale);
    else          // mismatch found
        return res >> log2ArrayIndexScale;
}
```

Swapping out the body of `vectorizedMismatch` with the following IL (derived from the pseudocode) is giving me correct results:
```
n1n       BBStart <block_2>
n12n      istore  <temp slot 20>[#400  Auto] [flags 0x3 0x0 ]
n11n        ishl
n9n           iload  length<parm 6 I>[#398  Parm] [flags 0x40000103 0x0 ]
n10n          iload  log2ArrayIndexScale<parm 7 I>[#399  Parm] [flags 0x40000103 0x0 ]
n18n      istore  <temp slot 21>[#401  Auto] [flags 0x3 0x0 ]
n17n        ior
n15n          ishl
n13n            iload  log2ArrayIndexScale<parm 7 I>[#399  Parm] [flags 0x40000103 0x0 ]
n14n            iconst 1
n16n          iconst 3
n24n      istore  <temp slot 22>[#402  Auto] [flags 0x3 0x0 ]
n23n        iand
n19n          iload  <temp slot 20>[#400  Auto] [flags 0x3 0x0 ]
n22n          ixor
n20n            iload  <temp slot 21>[#401  Auto] [flags 0x3 0x0 ]
n21n            iconst -1
n34n      istore  <temp slot 23>[#403  Auto] [flags 0x3 0x0 ]
n33n        arraycmp  <arraycmp>[#246  helper Method] [flags 0x400 0x0 ] (arrayCmpLen )
n27n          aladd
n25n            aload  a<parm 0 Ljava/lang/Object;>[#394  Parm] [flags 0x40000107 0x0 ]
n26n            lload  aOffset<parm 1 J>[#395  Parm] [flags 0x40000104 0x0 ]
n30n          aladd
n28n            aload  b<parm 3 Ljava/lang/Object;>[#396  Parm] [flags 0x40000107 0x0 ]
n29n            lload  bOffset<parm 4 J>[#397  Parm] [flags 0x40000104 0x0 ]
n32n          i2l
n31n            iload  <temp slot 22>[#402  Auto] [flags 0x3 0x0 ]
n37n      ificmpne --> block_4 BBStart at n5n ()
n35n        iload  <temp slot 22>[#402  Auto] [flags 0x3 0x0 ]
n36n        iload  <temp slot 23>[#403  Auto] [flags 0x3 0x0 ]
n2n       BBEnd </block_2> =====

n3n       BBStart <block_3>
n45n      istore  <temp slot 24>[#404  Auto] [flags 0x3 0x0 ]
n44n        ixor
n42n          ishr
n40n            iand
n38n              iload  <temp slot 20>[#400  Auto] [flags 0x3 0x0 ]
n39n              iload  <temp slot 21>[#401  Auto] [flags 0x3 0x0 ]
n41n            iload  log2ArrayIndexScale<parm 7 I>[#399  Parm] [flags 0x40000103 0x0 ]
n43n          iconst -1
n46n      goto --> block_5 BBStart at n7n
n4n       BBEnd </block_3> =====

n5n       BBStart <block_4>
n50n      istore  <temp slot 24>[#404  Auto] [flags 0x3 0x0 ]
n49n        ishr
n47n          iload  <temp slot 23>[#403  Auto] [flags 0x3 0x0 ]
n48n          iload  log2ArrayIndexScale<parm 7 I>[#399  Parm] [flags 0x40000103 0x0 ]
n6n       BBEnd </block_4> =====

n7n       BBStart <block_5>
n52n      ireturn
n51n        iload  <temp slot 24>[#404  Auto] [flags 0x3 0x0 ]
n8n       BBEnd </block_5> =====
```

Caveat: I've only done functionality testing locally on Z with `byte`, `char`, `short`, `int`, `long`, `float`, and `double` arrays. I have not yet tested the `null` case (see [1] for explanation, [2] for example).

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/332135c6a1fedc19e2e607b273125eb242b5d213/src/java.base/share/classes/jdk/internal/util/ArraysSupport.java#L92-L102
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/332135c6a1fedc19e2e607b273125eb242b5d213/src/java.base/share/classes/sun/nio/ch/NativeSocketAddress.java#L153-L158

**Comment by zl-wang** [comment]
@r30shah  A good try indeed. It is also understood that the existing IL is not in complete form yet. Exactly you need to take care of the different situations.  the IL transformation needs to test if a/b is null and take the object header size (or off-heap addressing) into account.  I saw the calling offsets are compensating for this purpose in the tests.

compressed strings have two further implications:  1) need to take care of the difference between intended element-size and representational in-memory element-size;  2) little-endian and big-endian difference in result calculation (might not applicable to z/x supporting single mode only).

@bhavanisn FYI ...

**Comment by zl-wang** [comment]
it is also nice that, if a/b is not null, it can be assumed to be an array object. otherwise, it is much more complicated.

**Comment by dchopra001** [comment]
Summarizing a couple of offline discussions regarding the following
> compressed strings have two further implications: 1) need to take care of the difference between intended element-size and representational in-memory element-size;

We may have a scenario where two arrays are passed in that represent strings. One array is representing a compressed string and the other is not. In addition, the `log2ArrayIndexScale` argument may indicate we are comparing `char` characters. This could theoretically be a problem. The implementation in jit code to handle this could be tricky.

However the internals of how a string is represented is private to the `String` class. In addition it doesn't look like the java implementation of `VectorizedMismatch` handles this scenario either. I believe @Spencer-Comin is performing some experiments to better understand how the Java implementation handles these scenarios. If it's not able to handle these correctly then we should be okay with not worrying about it as well.

**Comment by Spencer-Comin** [comment]
A rather convoluted test case to see what happens when I pass the internal `String` representation to `vectorizedMismatch`:
```java
import java.lang.reflect.Field;
import jdk.internal.misc.Unsafe;
import jdk.internal.util.ArraysSupport;

public class TestCompressedString {
    public static void main(String[] args) throws IllegalAccessException, NoSuchFieldException {
        String a = "This is a string that I am using for testing that should be long enough to give a good answer";
        String b = "This is a string that I am using for test\u0101ng that should be long enough to give a good answer";
        // The char at index 41 is different
        // \u0101 should force b to not use a compressed representation
        Field value = String.class.getDeclaredField("value");
        value.setAccessible(true);
        int vv = ArraysSupport.vectorizedMismatch(
            ((byte[])value.get(a)), Unsafe.ARRAY_BYTE_BASE_OFFSET,
            ((byte[])value.get(b)), Unsafe.ARRAY_BYTE_BASE_OFFSET,
            ((byte[])value.get(a)).length,
            ArraysSupport.LOG2_ARRAY_BYTE_INDEX_SCALE
        );
        System.out.println(vv);
    }
}
```

Running it on Z/Linux with OpenJ9:
```bash
$ java -version
openjdk version "19.0.1-internal" 2022-10-18
OpenJDK Runtime Environment (build 19.0.1-internal-adhoc.spencer.test)
Eclipse OpenJ9 VM (build master-892071c6a, JRE 19 Linux s390x-64-Bit Compressed References 20230109_000000 (JIT enabled, AOT enabled)
OpenJ9   - 277af292f
OMR      - 9c865e119
JCL      - d78ba9640fe based on jdk-19.0.1+10)
$ # without compressed strings
$ java  -XX:-CompactStrings --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED TestCompressedString
82
$ # with compressed strings
$ java  -XX:+CompactStrings --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED TestCompressedString
0
```

On Z/Linux with OpenJDK:
```bash
$ java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Temurin-19.0.1+10 (build 19.0.1+10)
OpenJDK 64-Bit Server VM Temurin-19.0.1+10 (build 19.0.1+10, mixed mode, sharing)
$ # without compressed strings
$ java  -XX:-CompactStrings --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED TestCompressedString
82
$ # with compressed strings
$ java  -XX:+CompactStrings --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED TestCompressedString
0
```

On Intel MacOS with OpenJDK:
```bash
$ java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Homebrew (build 19.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.1, mixed mode, sharing)
$ # without compressed strings
$ java  -XX:-CompactStrings --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED TestCompressedString
82
$ # with compressed strings
$ java  -XX:+CompactStrings --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED TestCompressedString
1
```

**Comment by Spencer-Comin** [comment]
Additionally, a quick test to see what happens when I pass in a `String` and treat it as a `char[]`
```java
import java.lang.reflect.Field;
import jdk.internal.misc.Unsafe;
import jdk.internal.util.ArraysSupport;

public class TestCompressedString {
    public static void main(String[] args) throws IllegalAccessException, NoSuchFieldException {
        String a = "This is a string that I am using for testing that should be long enough to give a good answer";
        String b = "This is a string that I am using for test\u0101ng that should be long enough to give a good answer";
        Field value = String.class.getDeclaredField("value");
        value.setAccessible(true);
        int vv = ArraysSupport.vectorizedMismatch(
            a, Unsafe.ARRAY_CHAR_BASE_OFFSET,
            b, Unsafe.ARRAY_CHAR_BASE_OFFSET,
            a.length(),
            ArraysSupport.LOG2_ARRAY_CHAR_INDEX_SCALE
        );
        System.out.println(vv);
    }
}
```
| JVM                 | With compressed strings | Without compressed strings |
| ------------------- | ----------------------- | -------------------------- |
| Z/Linux OpenJ9      |                       7 |                         11 |
| Z/Linux OpenJDK     |                       0 |                          3 |
| Intel macOS OpenJDK |                       0 |                          2 |

**Comment by r30shah** [comment]
Thanks a lot @Spencer-Comin  for the experiments, https://github.com/eclipse-openj9/openj9/issues/15204#issuecomment-1387340649

Looking at the results in the comment, it seems like VectorizedMismatch simply compares the array with passed object and does not work with combination of compact strings, and it is caller's responsibility to pass in parameters which are compatible (Hotspot and OpenJ9 results are same in this experiments). Can you make sure that you disable the JIT in your run to get the results purely through interpreter (Just for sanity, I do not think your current setup runs with JIT compiled code). 

I am bit confused about experiment in https://github.com/eclipse-openj9/openj9/issues/15204#issuecomment-1387364627 though, can you elaborate what does it mean?

**Comment by zl-wang** [comment]
@r30shah  @Spencer-Comin  please use iselect or lselect or similar ILOpcode to allow codegen making use of branchless sequence to generate the input addresses to arrayCmp.  for example, ultimate b address can be expressed as:   `b + bOffset + (b?ARRAY_BASE_OFFSET:0)`

**Comment by Spencer-Comin** [comment]
@r30shah 

> Can you make sure that you disable the JIT in your run to get the results purely through interpreter (Just for sanity, I do not think your current setup runs with JIT compiled code).

Same results with JIT disabled

> I am bit confused about experiment in [#15204 (comment)](https://github.com/eclipse-openj9/openj9/issues/15204#issuecomment-1387364627) though, can you elaborate what does it mean?

This experiment was just to confirm that passing in `String`s expecting to get the index of mismatching `char` will give an incorrect result

**Comment by Spencer-Comin** [comment]
> the IL transformation needs to test if a/b is null and take the object header size (or off-heap addressing) into account. I saw the calling offsets are compensating for this purpose in the tests.

@zl-wang I think there may be some misunderstanding here on accounting for object header. The `aOffset` and `bOffset` parameters are byte offsets from the base address of the array, not from the address of the first index of the array. This means it is the responsibility of the caller to take the object header size into account when passing in the offset. For examples, see the various `mismatch` functions in [1] which call `vectorizedMismatch`.

For off-heap addressing the calculation will indeed have to be more involved than simply adding.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/master/src/java.base/share/classes/jdk/internal/util/ArraysSupport.java

**Comment by zl-wang** [comment]
> This means it is the responsibility of the caller to take the object header size into account when passing in the offset.

@Spencer-Comin  sounds good.  that simplified things quite a bit.

**Comment by Spencer-Comin** [comment]
With the `iselect` opcode I was able to simplify the IL I have and easily replace the call to `vectorizedMismatch`, transforming
```
n9n         icall  jdk/internal/util/ArraysSupport.vectorizedMismatch(Ljava/lang/Object;JLjava/lang/Object;JII)I[#406  static Method] [flags 0x500 0x0 ] ()
n3n           aload  <parm 0 Ljava/lang/Object;>[#394  Parm] [flags 0x40000107 0x0 ]
n4n           lload  <parm 1 J>[#395  Parm] [flags 0x40000104 0x0 ]
n5n           aload  <parm 3 Ljava/lang/Object;>[#396  Parm] [flags 0x40000107 0x0 ]
n6n           lload  <parm 4 J>[#397  Parm] [flags 0x40000104 0x0 ]
n7n           iload  <parm 6 I>[#398  Parm] [flags 0x40000103 0x0 ]
n8n           iload  <parm 7 I>[#399  Parm] [flags 0x40000103 0x0 ]
```
to
```
n26n        iselect ()
n25n          icmpeq
n20n            arraycmp  <arraycmp>[#246  helper Method] [flags 0x400 0x0 ] (arrayCmpLen )
n17n              aladd
n3n                 aload  <parm 0 Ljava/lang/Object;>[#394  Parm] [flags 0x40000107 0x0 ]
n4n                 lload  <parm 1 J>[#395  Parm] [flags 0x40000104 0x0 ]
n18n              aladd
n5n                 aload  <parm 3 Ljava/lang/Object;>[#396  Parm] [flags 0x40000107 0x0 ]
n6n                 lload  <parm 4 J>[#397  Parm] [flags 0x40000104 0x0 ]
n19n              i2l
n16n                iand
n9n                   ishl
n7n                     iload  <parm 6 I>[#398  Parm] [flags 0x40000103 0x0 ]
n8n                     iload  <parm 7 I>[#399  Parm] [flags 0x40000103 0x0 ]
n15n                  ixor
n13n                    ior
n11n                      ishl
n8n                         ==>iload
n10n                        iconst 1
n12n                      iconst 3
n14n                    iconst -1
n16n            ==>iand
n23n          ixor
n22n            ishr
n21n              iand
n9n                 ==>ishl
n13n                ==>ior
n8n               ==>iload
n14n            ==>iconst -1
n24n          ishr
n20n            ==>arraycmp
n8n             ==>iload
```
This is giving me the right numbers in my ad hoc unit tests on Z, Power, and x86.

Also testing with an unit test (below) using JNI to test the `null` case gives me the correct value.
```java
import jdk.internal.util.ArraysSupport;

public class TestNull {
    private static int unitTest(Object a, long aOffset, Object b, long bOffset, int length, int log2ArrayIndexScale) {
        return ArraysSupport.vectorizedMismatch(a, aOffset, b, bOffset, length, log2ArrayIndexScale);
    }

    static {
        System.loadLibrary("TestNull");
    }
    private native long addressOfA();
    private native long addressOfB();
    private native int bytesToCheck();

    public static void main(String[] args) {
        TestNull uut = new TestNull();
        int dummy = 0;
        for (int j = 0; j < 100000; j++)
            dummy += unitTest(
                null, uut.addressOfA(),
                null, uut.addressOfB(),
                uut.bytesToCheck(),
                ArraysSupport.LOG2_ARRAY_BYTE_INDEX_SCALE
            );
        System.out.println(dummy);  // Should print 29 * 100000
    }
}
```
```c
// TestNull.c
#include <jni.h>
#include <stdint.h>

// mismatch at index 29
static uint8_t a[] = {
        0xca, 0xfe, 0xba, 0xbe, 0xde, 0xad, 0xbe, 0xef, 0x01, 0x02, 0x03, 0x04, 0x20, 0xc0, 0x40, 0x80,
        0xa0, 0xb0, 0xc0, 0xd0, 0x0b, 0x03, 0x0d, 0x05, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef
};
static uint8_t b[] = {
        0xca, 0xfe, 0xba, 0xbe, 0xde, 0xad, 0xbe, 0xef, 0x01, 0x02, 0x03, 0x04, 0x20, 0xc0, 0x40, 0x80,
        0xa0, 0xb0, 0xc0, 0xd0, 0x0b, 0x03, 0x0d, 0x05, 0x01, 0x23, 0x45, 0x67, 0x89, 0xFF, 0xcd, 0xef
};

JNIEXPORT jlong JNICALL Java_TestNull_addressOfA(JNIEnv *env, jobject thisObj)
{
        return (jlong) &a;
}

JNIEXPORT jlong JNICALL Java_TestNull_addressOfB(JNIEnv *env, jobject thisObj)
{
        return (jlong) &b;
}

JNIEXPORT jint JNICALL Java_TestNull_bytesToCheck (JNIEnv *env, jobject thisObj)
{
        return (jint) sizeof(a);
}
```

More rigorous testing is needed, but this is looking promising.

**Comment by knn-k** [comment]
I guess we will need to support `arraycmp` on AArch64.

**Comment by knn-k** [comment]
https://github.com/eclipse/omr/pull/6904 implemented `arraycmp` on AArch64.

**Comment by r30shah** [comment]
Most of the development work for this is done and there are two PRs [1][2] which should go in couple of weeks. Given the code-split for 0.40 is already happened, I do not think we would be get the PRs in. @tajila  should we move this to next milestone? 


[1]. https://github.com/eclipse/omr/pull/6983
[2]. https://github.com/eclipse-openj9/openj9/pull/16662
