### ISSUE TITLE
Build issue:  cannot get close to 63GB compressed heap anymore

### ISSUE THREAD

**Issue by zl-wang** [eclipse-openj9/openj9#15214]
I ran into this during a performance evaluation:
Silently turned to uncompressed ...
```
root@javaever3lp4 zlwang]# openj9_8_0.32/bin/java -Xcompressedrefs -Xmx58g -Xms58g -version
openjdk version "1.8.0_332"
IBM Semeru Runtime Open Edition (build 1.8.0_332-b09)
Eclipse OpenJ9 VM (build openj9-0.32.0, JRE 1.8.0 Linux ppc64le-64-Bit 20220422_347 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0b8b8af39a based on jdk8u332-b09)
```

we can get to 57GB compressed heap:
```
[root@javaever3lp4 zlwang]# openj9_8_0.32/bin/java -Xcompressedrefs -Xmx57g -Xms57g -version
openjdk version "1.8.0_332"
IBM Semeru Runtime Open Edition (build 1.8.0_332-b09)
Eclipse OpenJ9 VM (build openj9-0.32.0, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20220422_347 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0b8b8af39a based on jdk8u332-b09)
```

the build might not specify ld option to relocate .text/.data/.bss out of below-64G region anymore. So, the C-heap allocation obviously interferes with the java-heap allocation (although from the map alone below, i figured we should be able to get 60GB compressed heap. Not sure why we cannot in reality.)
```
[root@javaever3lp4 zlwang]# cat /proc/9861/maps
00060000-00070000 r-xp 00000000 fd:02 872440018                          /home/zlwang/openj9_8_0.32/bin/java
00070000-00080000 r--p 00000000 fd:02 872440018                          /home/zlwang/openj9_8_0.32/bin/java
00080000-00090000 rw-p 00010000 fd:02 872440018                          /home/zlwang/openj9_8_0.32/bin/java
00090000-03290000 rw-p 00000000 00:00 0
03290000-0c890000 ---p 00000000 00:00 0
3bdc0000-3bdf0000 rw-p 00000000 00:00 0                                  [heap]
1c0000000-1000000000 rw-p 00000000 00:00 0
```

**Comment by pshipton** [comment]
I think it's a side affect of using mixed refs, but agree it does seem correct. By specifying -Xcompressedrefs it should force that mode even if the requested size isn't appropriate.
@dmitripivkine any comments?

I'll look for the code and see about updating it.

**Comment by dmitripivkine** [comment]
If I understand correctly there are might be two problems:
- Redirector should check `-Xcompressedrefs` is requested explicitly and never try to switch to Full-64 version (IBM J9 seems work correct). I agree the problem should be in Redirector for OpenJ9
- Virtual memory below 64G has allocations can be moved out from this range using compiler options (C-heap)

**Comment by pshipton** [comment]
With https://github.com/eclipse-openj9/openj9/pull/15218, -Xmx63g works, at least on some plinux machines. I think this is resolved, but pls give the following JVM a try. 
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK8_ppc64le_linux_Personal/233/OpenJ9-JDK8-ppc64le_linux-20220603-171530.tar.gz
```
bin/java -Xcompressedrefs -Xmx63g -version
openjdk version "1.8.0_342-internal"
OpenJDK Runtime Environment (build 1.8.0_342-internal-jenkins_2022_06_03_17_15-b00)
Eclipse OpenJ9 VM (build HEAD-eb9eaf9033b, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20220603_233 (JIT enabled, AOT enabled)
OpenJ9   - eb9eaf9033b
OMR      - 453e06ac2f7
JCL      - bd90446dfce based on jdk8u342-b04)
```

**Comment by pshipton** [comment]
I'm going to close this assuming it's fixed.
