### ISSUE TITLE
JDK19 jdk_nio_0_FAILED java/nio/channels/etc/AdaptorCloseAndInterrupt.java ClosedByInterruptException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15210]
Failure link
------------

From an internal build `job/Grinder_testList_2/242/consoleFull`(`ub20x64rt3-1`):
```
11:17:02  openjdk version "19-internal" 2022-09-20
11:17:02  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextx86-64linuxPersonal)
11:17:02  Eclipse OpenJ9 VM (build loom_patch-5264b46c002, JRE 19 Linux amd64-64-Bit Compressed References 20220531_1000 (JIT enabled, AOT enabled)
11:17:02  OpenJ9   - 5264b46c002
11:17:02  OMR      - e8fbaa89d50
11:17:02  JCL      - a66f9edf71a based on jdk-19+24)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=-f+parallelList.mk+testList_2&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Grinder&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_Personal%2F1000%2FOpenJ9-JDKnext-x86-64_linux-20220531-190019.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_NUM_ARTIFACTS=60&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&USE_JRE=false&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=next&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=customized&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=24450&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&OPENJDK_SHA=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
11:27:37  ===============================================
11:27:37  Running test jdk_nio_0 ...
11:27:37  ===============================================
11:27:37  jdk_nio_0 Start Time: Thu Jun  2 08:27:37 2022 Epoch Time (ms): 1654183657166
11:27:37  "/home/jenkins/workspace/Grinder_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Grinder_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
11:27:37  JVMSHRC005I No shared class caches available
11:27:37  JVMSHRC005I No shared class caches available
11:27:37  cache cleanup done
11:27:37  variation: Mode150
11:27:37  JVM_OPTIONS:  -XX:+UseCompressedOops 

11:33:47  TEST: java/nio/channels/etc/AdaptorCloseAndInterrupt.java

11:33:47  STDERR:
11:33:47  java.nio.channels.ClosedByInterruptException
11:33:47  	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
11:33:47  	at java.base/sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:550)
11:33:47  	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:706)
11:33:47  	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:663)
11:33:47  	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:241)
11:33:47  	at AdaptorCloseAndInterrupt.dcReceiveAsyncInterrupt(AdaptorCloseAndInterrupt.java:168)
11:33:47  	at AdaptorCloseAndInterrupt.main(AdaptorCloseAndInterrupt.java:83)
11:33:47  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
11:33:47  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
11:33:47  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
11:33:47  	at java.base/java.lang.Thread.run(Thread.java:1555)
11:33:47  
11:33:47  JavaTest Message: Test threw exception: java.nio.channels.ClosedByInterruptException
11:33:47  JavaTest Message: shutting down test
11:33:47  
11:33:47  STDOUT:
11:33:47  interrupt() was invoked: true
11:33:47  scReadAsyncInterrupt was interrupted: true
11:33:47  
11:33:47  TEST RESULT: Failed. Execution failed: `main' threw exception: java.nio.channels.ClosedByInterruptException
11:33:47  --------------------------------------------------
11:46:36  Test results: passed: 390; failed: 1
11:47:05  Report written to /home/jenkins/workspace/Grinder_testList_2/jvmtest/openjdk/report/html/report.html
11:47:05  Results written to /home/jenkins/workspace/Grinder_testList_2/aqa-tests/TKG/output_16541831437185/jdk_nio_0/work
11:47:05  Error: Some tests failed or other problems occurred.
11:47:05  
11:47:05  jdk_nio_0_FAILED
```
50x grinder - `job/Grinder/24491/` - all failed.

**Comment by pshipton** [comment]
Ignoring the bad machines, passing in https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1011
More runs in:
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1013/
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1014/
