### ISSUE TITLE
JDK19 MBCS_Tests_i18n_zh_CN_linux_0_FAILED: not ok 3 - DateFormatTest

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15249]
Failure link
------------

From an internal build `job/Test_openjdknext_j9_special.functional_aarch64_linux_Personal/1/tapResults/`(`ub18-aarch64-8`):
```
11:32:28  openjdk version "19-internal" 2022-09-20
11:32:28  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
11:32:28  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 Linux aarch64-64-Bit Compressed References 20220607_35 (JIT enabled, AOT enabled)
11:32:28  OpenJ9   - 52f04efbff5
11:32:28  OMR      - c60867497c6
11:32:28  JCL      - 5ccf02de16a based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=special.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F35%2FOpenJ9-JDKnext-aarch64_linux-20220607-105822.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F35%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=exclude19&OPENJ9_SHA=52f04efbff5d2f4613971cdd550c6802117f0fd7&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test MBCS_Tests_i18n_zh_CN_linux_0 ...
===============================================
MBCS_Tests_i18n_zh_CN_linux_0 Start Time: Tue Jun  7 12:02:20 2022 Epoch Time (ms): 1654617740571
variation: NoOptions
JVM_OPTIONS:  
1..3
# linux_zh_CN.UTF-8
base /home/jenkins/workspace/Test_openjdknext_j9_special.functional_aarch64_linux_Personal_testList_0/jvmtest/functional/MBCS_Tests/i18n/
ok 1 - showlocale test
ok 2 - BreakIteratorTest test
not ok 3 - DateFormatTest
#   Failed test 'DateFormatTest'
#   at /home/jenkins/workspace/Test_openjdknext_j9_special.functional_aarch64_linux_Personal_testList_0/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/i18n/test.pl line 113.
# Looks like you failed 1 test of 3.

MBCS_Tests_i18n_zh_CN_linux_0_FAILED
```
This appears like https://github.com/eclipse-openj9/openj9/issues/12884, a test issue.

**Comment by pshipton** [comment]
@JasonFengJ9 pls unexclude the test if it's working now.

**Comment by JasonFengJ9** [comment]
Created https://github.com/adoptium/aqa-tests/pull/4118.

**Comment by babsingh** [comment]
The test has been re-enabled in https://github.com/adoptium/aqa-tests/pull/4118. Thus, removing the `test excluded` label.
