### ISSUE TITLE
JDK19 testDDRExt_Class_0_FAILED [ERROR] testJ9ClassShapeExt(j9vm.test.ddrext.junit.TestClassExt) - output does not contain success key : threadRef

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15252]
Failure link
------------

From an internal build `job/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal/10/tapResults/`(`paix825`):
```
11:58:45  openjdk version "19-internal" 2022-09-20
11:58:45  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextppc64aixPersonal)
11:58:45  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 AIX ppc64-64-Bit Compressed References 20220607_85 (JIT enabled, AOT enabled)
11:58:45  OpenJ9   - 52f04efbff5
11:58:45  OMR      - c60867497c6
11:58:45  JCL      - 5ccf02de16a based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_ppc64_aix_Personal%2F85%2FOpenJ9-JDKnext-ppc64_aix-20220607-105735.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_ppc64_aix_Personal%2F85%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=exclude19&OPENJ9_SHA=52f04efbff5d2f4613971cdd550c6802117f0fd7&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test testDDRExt_Class_0 ...
===============================================
testDDRExt_Class_0 Start Time: Tue Jun  7 12:35:16 2022 Epoch Time (ms): 1654623316841
variation: NoOptions
JVM_OPTIONS:  

 [java] [AutoRun] [INFO] Starting testJ9ClassShapeExt(j9vm.test.ddrext.junit.TestClassExt)
     [java] [DDRExtTesterBase] [ERROR] '!j9classshape  0x0000000030210600' output does not contain success key : threadRef
     [java] [DDRExtTesterBase] [ERROR] '!j9classshape  0x0000000030210600' output :Instance fields in j9vm/test/corehelper/SimpleThread$DumperThread:

[java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestClassExt.testJ9ClassShapeExt(TestClassExt.java:52)
     [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!j9classshape  0x0000000030210600'
     [java] [AutoRun] [INFO] Finished testJ9ClassShapeExt(j9vm.test.ddrext.junit.TestClassExt)
     [java] 
     [java] [AutoRun] [INFO] Starting testJ9VTablesExt(j9vm.test.ddrext.junit.TestClassExt)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)

    [java] [AutoRun] [INFO] ================Test Result for /home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/aqa-tests/TKG/../TKG/output_16546232901864/testDDRExt_Class_0/DDREXT.J9CORE.DMP==================
     [java] [AutoRun] [INFO] Errors:   0 out of 20 test cases.
     [java] [AutoRun] [INFO] Failures: 1 out of 20 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 1
     [java] [AutoRun] [ERROR] testJ9ClassShapeExt(j9vm.test.ddrext.junit.TestClassExt)

BUILD FAILED
/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/aqa-tests/TKG/output_16546232901864/testDDRExt_Class_0/tck_ddrext.xml:152: The following error occurred while executing this line:
/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64_aix_Personal_testList_1/aqa-tests/TKG/output_16546232901864/testDDRExt_Class_0/tck_ddrext.xml:140: Java returned: 254

Total time: 37 seconds

testDDRExt_Class_0_FAILED
```
This appears be a test issue, JDK19 adopts OpenJDK `j.l.Thread` which doesn't have `threadRef`.

**Comment by pshipton** [comment]
jdk8 failed to compile.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1267/console
```
14:34:18      [javac] /home/jenkins/workspace/Grinder/aqa-tests/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java:24: error: cannot find symbol
14:34:18      [javac] import org.openj9.test.util.VersionCheck;
14:34:18      [javac]                            ^
14:34:18      [javac]   symbol:   class VersionCheck
14:34:18      [javac]   location: package org.openj9.test.util
14:34:19      [javac] /home/jenkins/workspace/Grinder/aqa-tests/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java:297: error: cannot find symbol
14:34:19      [javac] 	public static final String J9CLASSSHAPE_SUCCESS_KEY = (VersionCheck.major() >= 19 ? "eetop," : "threadRef,") + J9CLASS_TEST_SUCCESS_KEY;
14:34:19      [javac] 	                                                       ^
14:34:19      [javac]   symbol:   variable VersionCheck
14:34:19      [javac]   location: class Constants
14:34:19      [javac] 2 errors
```
