### ISSUE TITLE
How to set the classpath in the file specified with -Xoptionsfile?

### ISSUE THREAD

**Issue by rrozenshteyn-jha** [eclipse-openj9/openj9#15259]
Java -version output
--------------------

openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Windows Server 2019 amd64-64-Bit Compressed References 20220422_352 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)

Summary of problem
------------------

I have a file where I want to specify JVM command-line options, specifically classpath.  I tried several ways of specifying the classpath in that file:

- -classpath <classpath elements on the same line, the whole line either with or without double quotes>
- -classpath
<classpath elements on the next line, the whole line either with or without double quotes>

- -classpath:<classpath elements on the same line, the whole line either with or without double quotes>

I also tried the above combinations with -cp instead of -classpath.  I tried all these combinations with OpenJ9 JVM either on Windows or on AIX.

No matter what combination I tried, I got back the error:
**JVMJ9VM007E** Command-line option unrecognised: -classpath
The "unrecognized" option varied depending on the combination I was trying.

Is there an example of a file that I can provide to the -Xoptionsfile arg which has a valid/working specification for the JVM classpath?

Thanks,
Roman.

Diagnostic files
----------------

N/A

OutOfMemoryError: Java Heap Space
---------------------------------

N/A

**Comment by pshipton** [comment]
`-classpath` and `-cp` are recognized by the java launcher and converted to `-Djava.class.path=` which is passed to the VM. You can put that option into the -Xoptionsfile, or use the Java 11 `@<file>` feature instead. 

```
java -help
...
    @argument files
                  one or more argument files containing options
```
You can find more info about `@` files in https://docs.oracle.com/en/java/javase/11/tools/java.html
