### ISSUE TITLE
JDK19 MauveMultiThrdLoad_5m_0_FAILED **FAILED** Process LT  has timed out

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15253]
Failure link
------------

From an internal build `job/Test_openjdkNext_j9_sanity.system_ppc64_aix_Personal/6/tapResults/`(`paix908`):
```
11:59:14  openjdk version "19-internal" 2022-09-20
11:59:14  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextppc64aixPersonal)
11:59:14  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 AIX ppc64-64-Bit Compressed References 20220607_85 (JIT enabled, AOT enabled)
11:59:14  OpenJ9   - 52f04efbff5
11:59:14  OMR      - c60867497c6
11:59:14  JCL      - 5ccf02de16a based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=sanity.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_ppc64_aix_Personal%2F85%2FOpenJ9-JDKnext-ppc64_aix-20220607-105735.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_ppc64_aix_Personal%2F85%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=exclude19&OPENJ9_SHA=52f04efbff5d2f4613971cdd550c6802117f0fd7&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=3&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test MauveMultiThrdLoad_5m_0 ...
===============================================
MauveMultiThrdLoad_5m_0 Start Time: Tue Jun  7 12:49:30 2022 Epoch Time (ms): 1654624170600
variation: Mode150
JVM_OPTIONS:  -XX:+UseCompressedOops 

STF 13:54:34.215 - Heartbeat: Process LT  is still running
STF 13:54:36.222 - **FAILED** Process LT  has timed out
STF 13:54:36.222 - Collecting dumps for: LT 
STF 13:54:36.222 - Sending SIG 3 to the java process to generate a javacore

STF 13:56:36.277 - Monitoring Report Summary:
STF 13:56:36.277 -   o Process LT  has timed out
STF 13:56:36.278 - Killing processes: LT 
STF 13:56:36.278 -   o Process clean up attempt 1 for LT  pid 10682842
STF 13:56:36.278 -   o Process LT  pid 10682842 stop()
STF 13:56:37.279 -   o Process LT  pid 10682842 killed
**FAILED** at step 1 (Run Mauve load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdkNext_j9_sanity.system_ppc64_aix_Personal_testList_0/aqa-tests/TKG/../TKG/output_16546186426493/MauveMultiThrdLoad_5m_0/20220607-124930-MauveMultiThrdLoad/execute.pl line 95.
STF 13:56:37.768 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 13:56:37.768 - 
STF 13:56:37.768 - ====================   T E A R D O W N   ====================
STF 13:56:37.768 - Running teardown: perl /home/jenkins/workspace/Test_openjdkNext_j9_sanity.system_ppc64_aix_Personal_testList_0/aqa-tests/TKG/../TKG/output_16546186426493/MauveMultiThrdLoad_5m_0/20220607-124930-MauveMultiThrdLoad/tearDown.pl
STF 13:56:37.871 - TEARDOWN stage completed
STF 13:56:37.878 - 
STF 13:56:37.878 - =====================   R E S U L T S   =====================
STF 13:56:37.878 - Stage results:
STF 13:56:37.878 -   setUp:     pass
STF 13:56:37.878 -   execute:  *fail*
STF 13:56:37.878 -   teardown:  pass
STF 13:56:37.878 - 
STF 13:56:37.878 - Overall result: **FAILED**

MauveMultiThrdLoad_5m_0_FAILED
```

**Comment by pshipton** [comment]
@Mesbah-Alam can you pls modify these tests to send the abort signal rather than the quit signal on a hang.

**Comment by pshipton** [comment]
There are 13 `1.LT.executionlog.<n>.ltd` files (`<n>` = 1 - 13). Each file is 8MB except for the last one. The files are binary. @Mesbah-Alam do you know how to read these files?

**Comment by Mesbah-Alam** [comment]
> do you know how to read these files?

There is a pl script in STF that should be helpful here: 

```
'$HOME/git/stf/scripts/formatExecutionLog.pl --detail /stf/MathLoadTest/results/1.LT.executionlog'
```

Details are here: https://github.com/adoptium/STF/blob/master/stf.load/docs/README.md.

**Comment by pshipton** [comment]
There doesn't seem to be anything interesting in the execution log files. There aren't any failures found, it's just a large list of the tests being run.
```
~/jdk-11.0.15+10/bin/java -cp /home/peter/git/STF/bin net.adoptopenjdk.loadTestAnalysis.FormatExecutionLog -f 1.LT.executionlog.ltd
Truncating log name to: 1.LT.executionlog
Formatting execution log for: 1.LT.executionlog

No failures found.
```

**Comment by pshipton** [comment]
The end of the log shows
```
19:52:36.505 +251146ms  6 Passed     2853 ..a.lang.UnsupportedClassVersionError.classInfo.getDeclaringClass -  |  |  |  |  |  |  V  |  |  |  |  |  |  |  | 
19:52:36.505 +251146ms  6 Started    1435 ..et.java.lang.IllegalThreadStateException.classInfo.getModifiers -  |  |  |  |  |  |  o  |  |  |  |  |  |  |  | 
19:52:36.505 +251146ms  7 Passed     2879 gnu.testlet.java.lang.UnsupportedClassVersionError.constructor    -  |  |  |  |  |  |  |  V  |  |  |  |  |  |  | 
19:52:36.505 +251146ms  7 Started    2753 gnu.testlet.java.lang.UnknownError.classInfo.getAnnotation        -  |  |  |  |  |  |  |  o  |  |  |  |  |  |  | 
19:52:36.505 +251146ms  0 Passed     3158 gnu.testlet.java.text.StringCharacterIterator.iter                -  V  |  |  |  |  |  |  |  |  |  |  |  |  |  | 
19:52:36.505 +251146ms  9 Passed      132 gnu.testlet.java.io.InvalidObjectException.classInfo.isInterface  -     |  |  |  |  |  |  |  |  V  |  |  |  |  | 
19:52:36.505 +251146ms  0 Started     579 gnu.testlet.java.lang.Byte.classInfo.getInterfaces                -  o  |  |  |  |  |  |  |  |     |  |  |  |  | 
19:52:36.505 +251146ms  9 Started    3514 gnu.testlet.java.util.StringTokenizer.hasMoreTokens               -  |  |  |  |  |  |  |  |  |  o  |  |  |  |  | 
19:52:36.505 +251146ms  5 Passed      332 gnu.testlet.java.lang.AbstractMethodError.classInfo.isPrimitive   -  |  |  |  |  |  V  |  |  |  |  |  |  |  |  | 
19:52:36.505 +251146ms  5 Started    2406 gnu.testlet.java.lang.RuntimeException.classInfo.InstanceOf       -  |  |  |  |  |  o  |  |  |  |  |  |  |  |  | 
```

**Comment by pshipton** [comment]
The log stopping at 19:52:36.505 does seem consistent with a hang after `19:52:25.405 - Completed 80.4%`

**Comment by pshipton** [comment]
https://github.com/adoptium/aqa-tests/pull/3804 is merged.
Trying another grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1079/

**Comment by pshipton** [comment]
The grinder didn't pick up the 3804 changes, trying again https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1080/

**Comment by pshipton** [comment]
We got a single core file, and no javacore files, but the tests appear to be doing the right things.
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Grinder/1080/system_test_output.tar.gz
```
LT  15:38:41.348 - Completed 26.8%. Number of tests started=1437611 (+518977)
...
STF 16:42:18.496 - Heartbeat: Process LT  is still running
STF 16:42:20.003 - **FAILED** Process LT  has timed out
STF 16:42:20.003 - Collecting dumps for: LT 
STF 16:42:20.003 - Sending SIG 3 to the java process to generate a javacore
```
```
JVMDUMP039I Processing dump event "user", detail "" at 2022/06/29 16:42:20 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16565170334009/MauveMultiThrdLoad_5m_0/20220629-153714-MauveMultiThrdLoad/results/core.20220629.164220.12779640.0001.dmp' in response to an event
```

**Comment by tajila** [comment]
@JasonFengJ9 does this still fail?

**Comment by JasonFengJ9** [comment]
The test has been excluded and launched [10x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/28670/).

**Comment by JasonFengJ9** [comment]
> does this still fail?

@tajila yes, the test still failed due to `Process LT  has timed out` in the grinder https://github.com/eclipse-openj9/openj9/issues/15253#issuecomment-1282436315.

**Comment by tajila** [comment]
@dnakamura Please take a look at this

**Comment by JasonFengJ9** [comment]
Launched a verification [50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30133/)
will close if the timed out failure is not reproduced.

**Comment by pshipton** [comment]
@dnakamura @JasonFengJ9 before this is closed the excluded test(s) need to be re-enabled. And then we'll see if it still fails in the builds.

**Comment by JasonFengJ9** [comment]
The grinder https://github.com/eclipse-openj9/openj9/issues/15253#issuecomment-1343111431 passed, enabling the test
* https://github.com/adoptium/aqa-tests/pull/4194
