### ISSUE TITLE
JDK19 ERROR: JDWP unable to get necessary JVMTI capabilities

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15272]
Failure link
------------

From an internal build `job/Test_openjdkNext_j9_extended.functional_x86-64_mac_Personal/17/tapResults/`(`mac12x64rt16`):
```
12:09:39  openjdk version "19-internal" 2022-09-20
12:09:39  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextx86-64macPersonal)
12:09:39  Eclipse OpenJ9 VM (build exclude19-622b1ac1f26, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220608_72 (JIT enabled, AOT enabled)
12:09:39  OpenJ9   - 622b1ac1f26
12:09:39  OMR      - c859f0d17d0
12:09:39  JCL      - 4cb748300c8 based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_mac_Personal%2F72%2FOpenJ9-JDKnext-x86-64_mac-20220608-113832.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_mac_Personal%2F72%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&OPENJ9_BRANCH=exclude19&OPENJ9_SHA=622b1ac1f266b556d0405c96083ad9265ea3c1ee&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3AJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.is.osx.10_11%26%26%21sw.os.mac.10_11&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test TestRefreshGCSpecialClassesCache_NOBCI_JIT_ON_0 ...
===============================================
TestRefreshGCSpecialClassesCache_NOBCI_JIT_ON_0 Start Time: Wed Jun  8 13:05:13 2022 Epoch Time (ms): 1654707913174
variation: Mode107
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0 -Xnocompressedrefs 
ERROR: JDWP unable to get necessary JVMTI capabilities.

TestRefreshGCSpecialClassesCache_NOBCI_JIT_ON_0_FAILED

===============================================
Running test TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_2 ...
===============================================
TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_2 Start Time: Wed Jun  8 13:05:13 2022 Epoch Time (ms): 1654707913599
variation: Mode107
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0 -Xnocompressedrefs 
ERROR: JDWP unable to get necessary JVMTI capabilities.

TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_2_FAILED

===============================================
Running test TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR_1 ...
===============================================
TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR_1 Start Time: Wed Jun  8 12:39:55 2022 Epoch Time (ms): 1654706395239
variation: Mode107
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0 -Xnocompressedrefs 
ERROR: JDWP unable to get necessary JVMTI capabilities.

TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR_1_FAILED
```

`job/Test_openjdkNext_j9_extended.functional_s390x_linux_Personal/32/tapResults/`
```
===============================================
Running test cmdLineTester_jvmtitests_extended_nongold_2 ...
===============================================
cmdLineTester_jvmtitests_extended_nongold_2 Start Time: Wed Jun  8 22:21:41 2022 Epoch Time (ms): 1654752101618
variation: Mode108
JVM_OPTIONS:  -Xgcpolicy:gencon -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xint -Xnocompressedrefs 
ERROR: JDWP unable to get necessary JVMTI capabilities.

cmdLineTester_jvmtitests_extended_nongold_2_FAILED
```

**Comment by fengxue-IS** [comment]
https://github.com/eclipse-openj9/openj9/pull/15254 should fix this

**Comment by tajila** [comment]
@JasonFengJ9 is this fixed?

**Comment by JasonFengJ9** [comment]
Yeah, passed in [latest run](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.functional_x86-64_mac/40/tapResults/).
