### ISSUE TITLE
JDK19 jdk_other_0_FAILED error: cannot find symbol HotSpotDiagnosticMXBean.ThreadDumpFormat

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15278]
Failure link
------------

From an internal build `view/Test_grinder/job/Grinder/24751/consoleFull`(`mac10x64rt02`):
```
23:46:16  openjdk version "19-internal" 2022-09-20
23:46:16  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextx86-64macPersonal)
23:46:16  Eclipse OpenJ9 VM (build jdk19excludes-5cba1cdc4d8, JRE 19 Mac OS X amd64-64-Bit Compressed References 20220608_74 (JIT enabled, AOT enabled)
23:46:16  OpenJ9   - 5cba1cdc4d8
23:46:16  OMR      - cf8ddbd1adc
23:46:16  JCL      - 4cb748300c8 based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=extended.openjdk&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_mac_Personal%2F74%2FOpenJ9-JDKnext-x86-64_mac-20220608-180603.tar.gz&ADOPTOPENJDK_BRANCH=jdk19for&ARTIFACTORY_NUM_ARTIFACTS=200&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=next&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=jdk19excludes&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:56:47  ===============================================
23:56:47  Running test jdk_other_0 ...
23:56:47  ===============================================
23:56:47  jdk_other_0 Start Time: Wed Jun  8 23:56:47 2022 Epoch Time (ms): 1654747007710
23:56:47  "/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
23:56:47  JVMSHRC005I No shared class caches available
23:56:47  JVMSHRC005I No shared class caches available
23:56:47  cache cleanup done
23:56:47  variation: Mode150
23:56:47  JVM_OPTIONS:  -XX:+UseCompressedOops 

00:00:08  TEST: jdk/incubator/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java

00:00:08  /Users/jenkins/workspace/Grinder/aqa-tests/openjdk/openjdk-jdk/test/jdk/jdk/incubator/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java:44: error: cannot find symbol
00:00:08  import com.sun.management.HotSpotDiagnosticMXBean.ThreadDumpFormat;
00:00:08                                                   ^
00:00:08    symbol:   class ThreadDumpFormat
00:00:08    location: interface HotSpotDiagnosticMXBean
00:00:08  /Users/jenkins/workspace/Grinder/aqa-tests/openjdk/openjdk-jdk/test/jdk/jdk/incubator/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java:150: error: cannot find symbol
00:00:08                  .dumpThreads(file.toString(), ThreadDumpFormat.JSON);
00:00:08                                                ^
00:00:08    symbol:   variable ThreadDumpFormat
00:00:08    location: class StructuredThreadDumpTest
00:00:08  Note: /Users/jenkins/workspace/Grinder/aqa-tests/openjdk/openjdk-jdk/test/jdk/jdk/incubator/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java uses preview features of Java SE 19.
00:00:08  Note: Recompile with -Xlint:preview for details.
00:00:08  2 errors
00:00:08  1 warning
00:00:08  
00:00:08  TEST RESULT: Failed. Compilation failed: Compilation failed
00:00:08  --------------------------------------------------
00:00:57  Test results: passed: 264; failed: 1
00:01:09  Report written to /Users/jenkins/workspace/Grinder/jvmtest/openjdk/report/html/report.html
00:01:09  Results written to /Users/jenkins/workspace/Grinder/aqa-tests/TKG/output_16547464946514/jdk_other_0/work
00:01:09  Error: Some tests failed or other problems occurred.
00:01:09  
00:01:09  jdk_other_0_FAILED
```
It appears hotspot specific test.

**Comment by babsingh** [comment]
JDK19 is no longer supported, but a fix for this issue has been pushed for JDK21:
- https://github.com/eclipse-openj9/openj9/pull/17709
- https://github.com/adoptium/aqa-tests/pull/4659
