### ISSUE TITLE
JDK19 jdk_util_0_FAILED IllegalArgumentException: bound must be greater than origin

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15287]
Failure link
------------

From an internal build `view/Test_grinder/job/Grinder/24782/consoleFull`(`rhel7s390x-4-5`):
```
09:44:45  openjdk version "19-internal" 2022-09-20
09:44:45  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnexts390xlinuxPersonal)
09:44:45  Eclipse OpenJ9 VM (build jdk19excludes-5cba1cdc4d8, JRE 19 Linux s390x-64-Bit Compressed References 20220608_96 (JIT enabled, AOT enabled)
09:44:45  OpenJ9   - 5cba1cdc4d8
09:44:45  OMR      - cf8ddbd1adc
09:44:45  JCL      - 4cb748300c8 based on jdk-19+25)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=sanity.openjdk&SDK_RESOURCE=customized&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_s390x_linux_Personal%2F96%2FOpenJ9-JDKnext-s390x_linux-20220608-150638.tar.gz&ADOPTOPENJDK_BRANCH=jdk19for&ARTIFACTORY_NUM_ARTIFACTS=200&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=next&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=jdk19excludes&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2FJasonFengJ9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
10:21:25  ===============================================
10:21:25  Running test jdk_util_0 ...
10:21:25  ===============================================
10:21:25  jdk_util_0 Start Time: Thu Jun  9 07:21:21 2022 Epoch Time (ms): 1654784481763
10:21:25  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
10:21:25  JVMSHRC005I No shared class caches available
10:21:25  JVMSHRC005I No shared class caches available
10:21:25  cache cleanup done
10:21:25  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
10:21:25  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

10:28:45  TEST: java/util/Random/RandomNextDoubleBoundary.java

10:28:45  STDERR:
10:28:45  java.lang.IllegalArgumentException: bound must be greater than origin
10:28:45  	at java.base/jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:218)
10:28:45  	at java.base/jdk.internal.util.random.RandomSupport$AbstractSpliteratorGenerator.doubles(RandomSupport.java:1499)
10:28:45  	at java.base/java.util.Random.doubles(Random.java:1097)
10:28:45  	at RandomNextDoubleBoundary.nextDoubleHugeRange(RandomNextDoubleBoundary.java:106)
10:28:45  	at RandomNextDoubleBoundary.main(RandomNextDoubleBoundary.java:44)
10:28:45  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
10:28:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
10:28:45  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:28:45  	at java.base/java.lang.Thread.run(Thread.java:1566)
10:28:45  
10:28:45  JavaTest Message: Test threw exception: java.lang.IllegalArgumentException
10:28:45  JavaTest Message: shutting down test
10:28:45  
10:28:45  
10:28:45  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.IllegalArgumentException: bound must be greater than origin
10:28:45  --------------------------------------------------
10:35:56  Test results: passed: 903; failed: 1
10:36:03  Report written to /home/jenkins/workspace/Grinder/jvmtest/openjdk/report/html/report.html
10:36:03  Results written to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16547824125653/jdk_util_0/work
10:36:03  Error: Some tests failed or other problems occurred.
10:36:03  
10:36:03  jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
Un-excluding via https://github.com/adoptium/aqa-tests/pull/3785
