### ISSUE TITLE
Builds timeout after 20 hours even when TIMEOUT_TIME is set higher

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15302]
https://openj9-jenkins.osuosl.org/job/Pipeline-Special-System-JDK8/55/
https://openj9-jenkins.osuosl.org/job/Pipeline-Release-0.33.0-Build8/2/
https://openj9-jenkins.osuosl.org/job/Pipeline-Release-0.33.0-Build11/2/

@AdamBrousseau any ideas?

**Comment by AdamBrousseau** [comment]
https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDK8_x86-64_windows/1045
timeout after 20 hours
The second layer `Pipeline-Build-Test-<VERSION>-<SPEC> has a hardcoded 20 hours for some reason
https://github.com/eclipse-openj9/openj9/blob/7c5c4148460dff53af663a679ecbce0ce8cdbd65/buildenv/jenkins/jobs/pipelines/Pipeline-Initialize.groovy#L31
