### ISSUE TITLE
CRIU: Better deadlock handling in core JDK code

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15367]
There are cases where the thread running a checkpoint requires access to a resource that is held by a halted thread. This will result in a deadlock. In some cases the relevant code is in the JDK so a user will not having any control of the issue. An example is the MethodType table lock which is essential when resolving a MethodHandle.

To solve this problem a new annotation will be introduced `@NotCheckpointSafe`

This annotation will be added to any internal API where a thread may be holding on to an essential resource. During checkpoint any thread with that annotation will not be halted immediately. Instead it will poll the thread and wait for that frame to be popped.

When no threads have the `@NotCheckpointSafe` annotation in any of their frames then the checkpoint will proceed.

**Comment by tajila** [comment]
FYI @gacholio

**Comment by gacholio** [comment]
This is not going to work as stated, and would require modifying the base JCL which is an awful idea for maintainability - every JCL refresh will introduce new deadlocks. I also don't believe there's any chance you could find all of the necessary locations to modify.

This is essentially safe point exclusive with a different definition of the safe point. It would mean maintaining a count of the marked frames and managing it on method enter/exit (and all the other ways of removing frames from the stack). This would certainly introduce a performance penalty on method exit.

**Comment by tajila** [comment]
> I also don't believe there's any chance you could find all of the necessary locations to modify.

Likely, that we wont catch every case, but we can catch common cases. I don't propose to annotate the entire JCL, but common paths in core openj9 JCL are doable.

> This is essentially safe point exclusive with a different definition of the safe point. It would mean maintaining a count of the marked frames and managing it on method enter/exit (and all the other ways of removing frames from the stack). This would certainly introduce a performance penalty on method exit.

Thats not quite what I was proposing. I was thinking something more like `Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0` 

```
/**
 * For each thread, walk Java stack and look for the scope instance. Methods that can take and access a scope
 * instance are marked with the "@Scoped" extended modifier. If the scope instance is found in a method, that
 * method is accessing the memory segment associated with the scope and thus closing the scope will fail.
 */
jboolean JNICALL
Java_jdk_internal_misc_ScopedMemoryAccess_closeScope0(JNIEnv *env, jobject instance, jobject scope)
```

The only performance penalty is when we initiate taking a checkpoint.

**Comment by gacholio** [comment]
This is also going to deadlock if anyone holds a lock when they are suspended and it's needed in the single thread, not to mention wait/notify deadlocks.

Polling makes it easier to implement (though it may never actually complete). I assume you would just periodically walk the thread list looking for threads which are eligible for suspension but haven't been yet. You would need to halt the thread, see if it's out of the critical regions, then mark it for checkpoint before resuming it.

**Comment by gacholio** [comment]
The whack-a-mole thread suspension is never going to be reiable. It might be better to do the whole process repeatedly, i.e. get exclusive, see if all threads can be suspended now and if not, release exclusive and poll again later. Only mark the threads for checkpoint when they are all safe.

This still doesn't fix the issue of a suspended thread holding a lock required by the single thread.

**Comment by tajila** [comment]
> This is also going to deadlock if anyone holds a lock when they are suspended and it's needed in the single thread, not to mention wait/notify deadlocks.

Yes, this is a an inherent problem with single thread mode. 

There are cases where we can live with this, in fact we will be introducing new behaviour to throw any time the checkpoint thread (exclusive thread) attempts acquire a lock that is held by another thread (blocked thread). So instead of deadlock we throw an exception. 

For wait/notify, we throw if the checkpoint thread (exclusive thread) attempts to wait indefinitely, we also capture and save all notify request and re-send them after we exit single thread mode.

The cases we can't live with are places where it would be too difficult or impossible for a user to mitigate the problem by changing their code. So the main examples right now are methodHandle resolution and charset initialization.

**Comment by tajila** [comment]
> The whack-a-mole thread suspension is never going to be reliable. It might be better to do the whole process repeatedly, i.e. get exclusive, see if all threads can be suspended now and if not, release exclusive and poll again later. Only mark the threads for checkpoint when they are all safe.

Interesting. I would have thought the opposite would be true. The oppositie being:
1) For each java thread
a) inspect thread
b) if annotation is not present on the stack, halt thread
c) move to next thread
2) if a thread in list wasn't halted in 1b) go back to 1) 

If we backout as soon as we detect a thread cannot be checkpointed doesn't that give other threads the opportunity enter "non-checkpoint-safe" code?

**Comment by gacholio** [comment]
As I said, there's a potential to never complete (I suppose you'd need a global timeout).

I see this is far less likely than some inter-thread dependencies being broken by halting piecemeal.

T1 owns lock, not in critical region
T1 gets halted for checkpoint
T2 is in critical region
T2 attempts to get the lock <- never going to happen
Checkpoint waits forever for T2

**Comment by tajila** [comment]
Okay, I see what you mean.

**Comment by keithc-ca** [comment]
I have to agree with the concerns raised by @gacholio. We aren't likely to get all the places that might need the `NotCheckpointSafe` annotation (particularly in code or libraries outside the JDK and OpenJ9).

Although, closing this via #15568 puzzles me.

**Comment by tajila** [comment]
The intention wasn't to get all the places that might be affected, especially in places outside the JDK. Throwing an exception is perfectly fine if user code is causing the deadlock because a user can simply address this themselves. However, there are cases where the user has no way of addressing the deadlock, ie. methodHandle code acquiring a global lock because the user decided to do string concat. In these cases the JDK should provide some support.

**Comment by tajila** [comment]
> Although, closing this via https://github.com/eclipse-openj9/openj9/issues/15568 puzzles me.

The VM support is complete, all thats left is to add the annotation to places that need it. The criteria right now is to add it to places where basic VM functionalities are being affected (MH support, charset init) and places where the Liberty team can't address the deadlocks on their own.

As a result, finding all the places that need the annotation is not something that will be done in the short term, but rather something that we will address as development continues.
