### ISSUE TITLE
JITServer compilation failures due to interrupted network I/O system calls

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [eclipse-openj9/openj9#15394]
Network I/O system calls in JITServer communication layer can sometimes fail with the `EINTR` error (interrupted system call). Such failures at the JIT client can lead to failed remote compilations and are handled as a "lost connection", leading to subsequent compilations being performed locally for a short time period, which can result in memory usage spikes. JITServer networking code (including encrypted communication with SSL) needs to handle the `EINTR` errors that are possible during normal operation.

**Comment by cjjdespres** [comment]
I tried testing this using the same setup I was using for #15396, but I didn't get any `EINTR` errors at the client. Did you also observe `EINTR` errors in the same circumstances as in that other issue?

I did get errors like:

```
#FAILURE:  JITServer::StreamFailure: JITServer I/O error: read error: Resource temporarily unavailable for org/apache/cxf/transport/http/AbstractHTTPDestination.flushHeaders(Lorg/apache/cxf/message/Message;Z)Ljava/io/OutputStream; @ hot
```

which correspond to `EAGAIN` errors, I believe. These errors cause the same spike in peak RSS as the errors in that other issue. The documentation for `read` seems to suggest that these will not happen when reading from a blocking socket, but from looking online it appears that `read` will also fail with `EAGAIN` when a timeout is set on the socket and the read takes too long. That might be why the SSL reads are failing in #15396 too; they could be catching an underlying `EAGAIN` from a timeout and propagating it upward through `BIO_should_retry`.

If these are timeout-related issues, I'm not sure we should fix them by retrying the `BIO_read` or `read`, because all that does is thwart the timeout mechanism. We could probably eliminate them by removing the timeout entirely, but I'm not sure if that's a good idea either.

**Comment by mpirvu** [comment]
Do the EAGAIN errors happen sooner than the timeout we set? If they do, then having a retrying mechanism makes sense. If they happen exactly when the timeout expires, then it may be better to increase the timeout.

I am somewhat reluctant to increase the timeout to large values though. If the network connection is so bad that most messages take a very long time, we may be better off to compile locally, accepting the increase in memory spikes (if the client has enough memory to afford it)

**Comment by mpirvu** [comment]
I wonder if we should have some code to collect stats about network latency. I am concerned about additional overhead though, since we have so many messages.

**Comment by mpirvu** [comment]
I am ok with increasing the timeouts slightly (maybe double) provided that:
- If the server dies, the client does not wait for the entire duration of the timeout
- The client never executes synchronous compilation requests remotely: -XX:+JITServerLocalSyncCompiles needs to become the default

**Comment by mpirvu** [comment]
Where is the 2000 ms timeout declared? The documentation says 10 sec at the client and 30 sec at the server.

**Comment by cjjdespres** [comment]
Oh, I see, the timeout is increased later in the options parsing. The initializer for `PersistentInfo` has it set to 2 seconds by default, but the `DEFAULT_JITCLIENT_TIMEOUT` that it gets set to is in fact 10. Increasing the default timeout to 35-40 seconds would still be a fairly large increase, then, but not as much as from 2 seconds.

**Comment by mpirvu** [comment]
I have the following proposal, but I am open to other suggestions.
- Increase the timeout at the client to 30 sec to match the one at the server. Q1: do we have to adjust the timeout at the server as well? Q2: with this new change, do we capture most of cases when the client experiences a timeout?
- Make -XX:+JITServerLocalSyncCompiles the default
- When the client experiences a timeout, try to reconnect immediately for the next request and only then implement a back-off mechanism (I remember we start with a 1ms wait time before a reconnect is attempted (see -Xjit:reconnectWaitTimeMs=)

**Comment by cjjdespres** [comment]
I'm only seeing timeouts on the client side, so I don't think the server timeout needs adjustment. I've run some tests with `JITServerTimeout=30000` and the number of timeouts is 2-5 total across the 16 clients per run, down from 15-30 with the default. That's with or without SSL, though there were generally more timeouts with SSL disabled than enabled for both `JITServerTimeout` values.

I think those changes are reasonable.

**Comment by AlexeyKhrabrov** [comment]
> I tried testing this using the same setup I was using for #15396, but I didn't get any `EINTR` errors at the client. Did you also observe `EINTR` errors in the same circumstances as in that other issue?

The `EINTR` errors are rare, I've only seen it once in the vlog. This error code is returned in the `read` or `write` system call is interrupted by a signal (see the man pages), which can rarely happen during normal operation. The operation should be simply retried in such case. This is a separate issue from `EAGAIN`/timeouts.

**Comment by AlexeyKhrabrov** [comment]
Just a clarification about the timeout issue. I'm pretty sure it's not the network connection that's getting too much load, but rather the compilation requests taking too long at the server. What I think is happening is that the largest interval between messages during a compilation exceeds the client-side timeout.
