### ISSUE TITLE
CRIU: Address System.nanoTime deficiencies when machine reboots

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15417]
The existing solution to fixup System.nanoTime involves getting the nanotime pre and post checkpoint to compute the "JVMdowntime" delta. This approach assumes that the nanoTime clock has the same time base pre and post checkpoint. We have noticed that rebooting the machine resets the timebase.

We will fix this issue by using nano wall clock time to determine  the "JVMdowntime" (`InternalCRIUSupport.getCheckpointRestoreNanoTimeDelta`). 

For System.nanoTime, instead of returning `nanoTime - JVMdowntime` it will instead return `nanoTime - PrePostCheckpointNanottimeClockDelta`.

The `PrePostCheckpointNanottimeClockDelta` is essentially the difference between the nanotime clock in checkpoint and restore.

**Comment by tjwatson** [comment]
For clock delta, is that just using UTC.  I assume there are not concerns with cases where you checkpoint in one timezone and restore in another.  Or checkpoint during daylight savings but restore in "normal" time?

**Comment by tajila** [comment]
Testing the reboot behaviour will be difficult, but I believe that the same scenario can occur when you restore on a different machine so the container tests should come in handy here.

FYI @LongyuZhang

**Comment by JasonFengJ9** [comment]
> Yes, its UTC. I believe Jason did some experiments that showed it will account for timezone changes. I dont think we tried DST differences yet though, but I expect that should work as well.

The experiment verified that `System.currentTimeMillis()` returns correct values when the timezone changes, the underneath API for Linux platforms for CRIU is [gettimeofday](https://man7.org/linux/man-pages/man2/gettimeofday.2.html).
 DST technically is a timezone change as well, and same behaviour is expected.
Just note if the machine time is configured wrongly, the API in question won't get correct results.

To measure the JVM downtime between checkpoint and restore, `j9time_current_time_nanos` will be used instead of existing `j9time_nano_time`, the API proposed eventually invokes [clock_gettime(CLOCK_REALTIME)](https://linux.die.net/man/3/clock_settime) which returns time since the Epoch, and is expected to be same as `gettimeofday` above. I will verify w/ another testcase.

**Comment by JasonFengJ9** [comment]
Follow up the measurement of JVM downtime between checkpoint and restore w/ `j9time_current_time_nanos`, there is no Java API for this native direct usage. Just hacked a VM, replaced `j9time_current_time_millis()` w/ `j9time_current_time_nanos()/100000` for `System.currentTimeMillis()`, and the result is same as the initial experiment which showed it adopts timezone changes.

The test code snippet in question is:
```
	private void showThreadCurrentTime(String logStr) {
		System.out.println(logStr + ": System.currentTimeMillis: " + System.currentTimeMillis() + ", " + new Date()
				+ ", Thread's name: " + Thread.currentThread().getName());
	}

	void testAll() {
		showThreadCurrentTime("start");
		TimeZone.setDefault(TimeZone.getTimeZone("GMT+1"));
		showThreadCurrentTime("timezone change to GMT+1");
		final long startTime = System.currentTimeMillis();
		try {
			Thread.sleep(1234); // sleep 1234ms
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		TimeZone.setDefault(TimeZone.getTimeZone("GMT-9"));
		showThreadCurrentTime("timezone change to GMT-9");
		final long endTime = System.currentTimeMillis();
		showThreadCurrentTime("end");
		final long elapsedTime = endTime - startTime;
		System.out.println("elapsedTime = " + elapsedTime);
	}
```

The result for this hacked JVM is:
```
start: System.currentTimeMillis: 1656024677709, Thu Jun 23 15:51:17 PDT 2022, Thread's name: main
timezone change to GMT+1: System.currentTimeMillis: 1656024677785, Thu Jun 23 23:51:17 GMT+01:00 2022, Thread's name: main
timezone change to GMT-9: System.currentTimeMillis: 1656024679048, Thu Jun 23 13:51:19 GMT-09:00 2022, Thread's name: main
end: System.currentTimeMillis: 1656024679062, Thu Jun 23 13:51:19 GMT-09:00 2022, Thread's name: main
elapsedTime = 1248
```
