### ISSUE TITLE
ValueTypeTests_1_FAILED NPE at java.base/java.lang.Class.forNameImpl(Native Method)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15429]
Failure link
------------

From an internal build `job/Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly/648/tapResults/`(`ub18x64rt1-7`):
```
21:44:53  openjdk version "20-internal" 2023-03-21
21:44:53  OpenJDK Runtime Environment (build 20-internal-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
21:44:53  Eclipse OpenJ9 VM (build master-9581a020aee, JRE 20 Linux amd64-64-Bit Compressed References 20220626_772 (JIT enabled, AOT enabled)
21:44:53  OpenJ9   - 9581a020aee
21:44:53  OMR      - a57ad601d66
21:44:53  JCL      - 4c2f2523361 based on jdk-20+3)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=sanity.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Nightly&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_valhalla_Nightly%2F772%2FOpenJ9-JDKnext-x86-64_linux_valhalla-20220626-181419.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_x86-64_linux_valhalla_Nightly%2F772%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=Valhalla&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.valuetypes.git&OPENJ9_BRANCH=master&OPENJ9_SHA=9581a020aeefe5228672fbffb6f12cd1e58b40fa&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=8351d880d75daf01e631d8fc6abff75a40a68158&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9%26%26%21sw.os.cent.6%26%26%21sw.os.rhel.6&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=false&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional%2FValhalla%2Cfunctional%2Fcmdline_options_tester%2Cfunctional%2FcmdLineTests%2Fvaluetypeddrtests&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test ValueTypeTests_1 ...
===============================================
ValueTypeTests_1 Start Time: Sun Jun 26 18:49:18 2022 Epoch Time (ms): 1656294558011
variation: -XX:ValueTypeFlatteningThreshold=99999 -Xgcpolicy:optthruput -XX:-EnableArrayFlattening
JVM_OPTIONS:  -XX:ValueTypeFlatteningThreshold=99999 -Xgcpolicy:optthruput -XX:-EnableArrayFlattening 
JVMJ9VM193W Since Java 13 -Xverify:none and -noverify were deprecated for removal and may not be accepted options in the future.
Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:171)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1525)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:201)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:548)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:498)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1053)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1039)
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:301)
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
	at java.base/sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:299)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:288)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSelectAnnotations(AnnotationParser.java:102)
	at java.base/sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:146)
	at java.base/sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:262)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.reflect.Field.declaredAnnotations(Field.java:1290)
	at java.base/java.lang.reflect.Field.declaredAnnotations(Field.java:1288)
	at java.base/java.lang.reflect.Field.getAnnotation(Field.java:1255)
	at com.beust.jcommander.Parameterized.parseArg(Parameterized.java:44)
	at com.beust.jcommander.JCommander.addDescription(JCommander.java:529)
	at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:522)
	at com.beust.jcommander.JCommander.parse(JCommander.java:280)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.testng.TestNG.privateMain(TestNG.java:1342)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:372)
	at java.base/java.lang.Class.forName(Class.java:350)
	at jdk.proxy1/jdk.proxy1.$Proxy0.<clinit>(Unknown Source)
	... 33 more

ValueTypeTests_1_FAILED
```

Similarly NPE caused other `ValueTypeTests` variants, `ValueTypeTestsJIT`, and `ValueTypeUnsafeTests`.

fyi @hangshao0

**Comment by hangshao0** [comment]
Does it fail 100% of the time ? I am not aware of any Valhalla change merged recently.

**Comment by hangshao0** [comment]
Last passing build:

```
21:56:19  openjdk version "19-internal" 2022-09-20
21:56:19  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
21:56:19  Eclipse OpenJ9 VM (build master-6335127afcf, JRE 19 Linux amd64-64-Bit Compressed References 20220602_749 (JIT enabled, AOT enabled)
21:56:19  OpenJ9   - 6335127afcf
21:56:19  OMR      - ca03f92a867
21:56:19  JCL      - bee4e4a03f4 based on jdk-19+21)
```

First failing build:
```
21:43:33  openjdk version "19-internal" 2022-09-20
21:43:33  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
21:43:33  Eclipse OpenJ9 VM (build master-cddb8bf6b53, JRE 19 Linux amd64-64-Bit Compressed References 20220616_762 (JIT enabled, AOT enabled)
21:43:33  OpenJ9   - cddb8bf6b53
21:43:33  OMR      - 81e9c1cf425
21:43:33  JCL      - b41d25e57d8 based on jdk-19+25)
```
@ehrenjulzert Since you are working on these tests, can you look at this ? Need to find out which class can not be found here.

**Comment by ehrenjulzert** [comment]
Sure, I can take a look at it

**Comment by hangshao0** [comment]
The OpenJ9 diff: https://github.com/eclipse-openj9/openj9/compare/cddb8bf6b53..6335127afcf. 
There is an change in `Class.forName()` there.

**Comment by ehrenjulzert** [comment]
It looks like the `className` being passed in to `forName` is null, and so reverting the changes from #15343 doesn't fix the error. The problem is in whatever is calling `forName`

**Comment by hangshao0** [comment]
We may hit the following code from one of the `goto initFailed;` in this function.

https://github.com/eclipse-openj9/openj9/blob/483e879d91bef6225f89c870089be438e9938146/runtime/vm/ClassInitialization.cpp#L764-L771

You can look at what is the class (variable `clazz`) being initialized here. The trace point `Trc_VM_classInitStateMachine_Entry` has the class name. You can find the trace number of this trace point in `ut_j9vm.h`. Then run with -Xtrace:print={j9vm.XXX} to see the class name, where XXX is the trace number.

If we know the class, you can further look at why one of the `goto initFailed;` is triggered.

**Comment by ehrenjulzert** [comment]
Reverting https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/commit/31418dcc2d9d040bc13cb63f9b05e513165074b6 does indeed fix the issue, so the cause of the problem definitely lies in there, but I'm not exactly sure where it is.

I was able to get the code for the `<clinit>` method using `-Djdk.proxy.ProxyGenerator.saveGeneratedFiles=true`, however I don't see any references to `null` in the method. I'm not exactly an expert on java byte code though, so here is the code if anyone else would like to take a look:

```
static {};
    descriptor: ()V
    flags: (0x0008) ACC_STATIC
    Code:
      stack=15, locals=2, args_size=0
         0: ldc           #2                  // class jdk/proxy1/$Proxy0
         2: invokevirtual #86                 // Method java/lang/Class.getClassLoader:()Ljava/lang/ClassLoader;
         5: astore_0
         6: ldc           #88                 // String java.lang.Object
         8: iconst_0
         9: aload_0
        10: invokestatic  #92                 // Method java/lang/Class.forName:(Ljava/lang/String;)Ljava/lang/Class;
        13: ldc           #93                 // String hashCode
        15: iconst_0
        16: anewarray     #69                 // class java/lang/Class
        19: invokevirtual #97                 // Method java/lang/Class.getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
        22: putstatic     #26                 // Field m0:Ljava/lang/reflect/Method;
        25: ldc           #88                 // String java.lang.Object
        27: iconst_0
        28: aload_0
        29: invokestatic  #92                 // Method java/lang/Class.forName:(Ljava/lang/String;)Ljava/lang/Class;
        32: ldc           #98                 // String equals
        34: iconst_1
        35: anewarray     #69                 // class java/lang/Class
        38: dup
        39: iconst_0
        40: ldc           #88                 // String java.lang.Object
        42: iconst_0
        43: aload_0
        44: invokestatic  #92                 // Method java/lang/Class.forName:(Ljava/lang/String;)Ljava/lang/Class;
        47: aastore
        48: invokevirtual #97                 // Method java/lang/Class.getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
        51: putstatic     #47                 // Field m1:Ljava/lang/reflect/Method;
        54: ldc           #88                 // String java.lang.Object
        56: iconst_0
        57: aload_0
        58: invokestatic  #92                 // Method java/lang/Class.forName:(Ljava/lang/String;)Ljava/lang/Class;
        61: ldc           #99                 // String toString
        63: iconst_0
        64: anewarray     #69                 // class java/lang/Class
        67: invokevirtual #97                 // Method java/lang/Class.getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
        70: putstatic     #60                 // Field m2:Ljava/lang/reflect/Method;
        73: ldc           #101                // String java.lang.annotation.Retention
        75: iconst_0
        76: aload_0
        77: invokestatic  #92                 // Method java/lang/Class.forName:(Ljava/lang/String;)Ljava/lang/Class;
        80: ldc           #102                // String annotationType
        82: iconst_0
        83: anewarray     #69                 // class java/lang/Class
        86: invokevirtual #97                 // Method java/lang/Class.getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
        89: putstatic     #67                 // Field m3:Ljava/lang/reflect/Method;
        92: ldc           #101                // String java.lang.annotation.Retention
        94: iconst_0
        95: aload_0
        96: invokestatic  #92                 // Method java/lang/Class.forName:(Ljava/lang/String;)Ljava/lang/Class;
        99: ldc           #103                // String value
       101: iconst_0
       102: anewarray     #69                 // class java/lang/Class
       105: invokevirtual #97                 // Method java/lang/Class.getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
       108: putstatic     #74                 // Field m4:Ljava/lang/reflect/Method;
       111: return
       112: astore_1
       113: new           #105                // class java/lang/NoSuchMethodError
       116: dup
       117: aload_1
       118: invokevirtual #108                // Method java/lang/Throwable.getMessage:()Ljava/lang/String;
       121: invokespecial #111                // Method java/lang/NoSuchMethodError."<init>":(Ljava/lang/String;)V
       124: athrow
       125: astore_1
       126: new           #113                // class java/lang/NoClassDefFoundError
       129: dup
       130: aload_1
       131: invokevirtual #108                // Method java/lang/Throwable.getMessage:()Ljava/lang/String;
       134: invokespecial #114                // Method java/lang/NoClassDefFoundError."<init>":(Ljava/lang/String;)V
       137: athrow
      Exception table:
         from    to  target type
             6   112   112   Class java/lang/NoSuchMethodException
             6   112   125   Class java/lang/ClassNotFoundException
      StackMapTable: number_of_entries = 2
        frame_type = 255 /* full_frame */
          offset_delta = 112
          locals = [ class java/lang/ClassLoader ]
          stack = [ class java/lang/NoSuchMethodException ]
        frame_type = 76 /* same_locals_1_stack_item */
          stack = [ class java/lang/ClassNotFoundException ]
```

**Comment by hangshao0** [comment]
So the code to generate the Class.forName() call is:
https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/blob/9fe0064438340d8a526de97fc2c9d70835746178/src/java.base/share/classes/java/lang/reflect/ProxyGenerator.java#L959-L965

But from the bytecode, the ldc before the `forName()` call is always referencing a valid string. Is it `className` null or some other parameter null inside `Class.forName()` that triggers the NPE ?

**Comment by ehrenjulzert** [comment]
I tested again and got the same result (`className` was null)

To be clear, to print the result I'm changing line 406 of Class.java here to catch the NPE: https://github.com/eclipse-openj9/openj9/blob/f9c5836bd7879978ec50fd037675cd5a1dcad0d3/jcl/src/java.base/share/classes/java/lang/Class.java#L406
This is what my edit of the code looks like:
```
public static Class<?> forName(String className) throws ClassNotFoundException
{
/*[IF JAVA_SPEC_VERSION >= 18]*/
	try {
		return forName(className, getStackClass(1));
	} catch (NullPointerException e) {
		System.out.println("NPE IN forName while looking for class: " + className);
		System.out.println(className == null);
		throw e;
	}
/*[ELSE] JAVA_SPEC_VERSION >= 18
```

**Comment by hangshao0** [comment]
I seem to know what is going on here. Looking at the generated bytecode:

`  29: invokestatic  #92                 // Method java/lang/Class.forName:(Ljava/lang/String;)Ljava/lang/Class;`

From the method descriptor, the method being called is 
`public static Class<?> forName(String className) `

However, the code prepares `className`, `false` and `classloader` as parameters, so the intention of that commit is to call: 
`public static Class<?> forName(String className, boolean initializeBoolean, ClassLoader classLoader)`

I believe the descriptor of `forName()` used in this line is incorrect:
https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/blob/9fe0064438340d8a526de97fc2c9d70835746178/src/java.base/share/classes/java/lang/reflect/ProxyGenerator.java#L965

It should be changed to the descriptor of 
`public static Class<?> forName(String className, boolean initializeBoolean, ClassLoader classLoader)`

Can you make the change to see if that fixes the problem ? @ehrenjulzert

**Comment by ehrenjulzert** [comment]
I changed the descriptor to `"(Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljava/lang/Class;"` and it looks like the issue is now fixed. Should I make a PR on [openj9-openjdk-jdk.valuetypes](https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes)?

**Comment by hangshao0** [comment]
> Should I make a PR on [openj9-openjdk-jdk.valuetypes](https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes)?

Yes, please. Also I assume the same issue exists in the Jdknext repo. If so, please make the same change in https://github.com/ibmruntimes/openj9-openjdk-jdk.

**Comment by JasonFengJ9** [comment]
> Yes, please. Also I assume the same issue exists in the Jdknext repo. If so, please make the same change in https://github.com/ibmruntimes/openj9-openjdk-jdk.

Please make the change in [openj9-openjdk-jdk](https://github.com/ibmruntimes/openj9-openjdk-jdk) which will be merged into [openj9-openjdk-jdk.valuetypes](https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes).

**Comment by ehrenjulzert** [comment]
I believe the bug was introduced during a merge on our side

The code on line 912 of https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/commit/31418dcc2d9d040bc13cb63f9b05e513165074b6 looks correct, but during this merge: https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/commit/dc9687492aa493e72d5a97a171c587bb4e627af5#diff-108e405c90b5012e3a36d52e0423e8387aa8c38636f316fe80fc41f6814ec261R965 
I only see the `mv.visitInsn(ICONST_0); // false` and `mv.visitVarInsn(ALOAD, 0); // classLoader` lines being added, without the new descriptor.

**Comment by ehrenjulzert** [comment]
Also, it looks like https://github.com/ibmruntimes/openj9-openjdk-jdk doesn't have this problem, the corrected line is right here: https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/fbe5e8830b48613222c9c971161d273a8b113430/src/java.base/share/classes/java/lang/reflect/ProxyGenerator.java#L912

**Comment by JasonFengJ9** [comment]
[valhalla](https://github.com/openjdk/valhalla/blob/lworld/src/java.base/share/classes/java/lang/reflect/ProxyGenerator.java) has a slightly different version:
```
            mv.visitLdcInsn(cl.getName());
            mv.visitMethodInsn(INVOKESTATIC,
                    JL_CLASS,
                    "forName", "(Ljava/lang/String;)Ljava/lang/Class;", false);
            if (cl.isPrimitiveValueType()) {
              mv.visitMethodInsn(INVOKEVIRTUAL,
                                 JL_CLASS,
                                 "asValueType", "()Ljava/lang/Class;", false);
            }
```
We need a patch to mix this with [openj9-openjdk-jdk](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/fbe5e8830b48613222c9c971161d273a8b113430/src/java.base/share/classes/java/lang/reflect/ProxyGenerator.java#L905-L914)

**Comment by ehrenjulzert** [comment]
I see, so I should make a separate PR for both Valhalla and for openj9-openjdk-jdk.valuetypes? Or is there somewhere that I can put in a single PR that will be merged by both repos?

**Comment by ehrenjulzert** [comment]
Ah, so I just need to make the one PR on [openj9-openjdk-jdk.valuetypes](https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes) then?

**Comment by JasonFengJ9** [comment]
> so I just need to make the one PR on [openj9-openjdk-jdk.valuetypes](https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes) then?

Correct

**Comment by hangshao0** [comment]
Can this be closed as the PR is merged ? @JasonFengJ9

**Comment by JasonFengJ9** [comment]
Latest nightly build is green - `view/Valhalla%20Tests/job/Pipeline_Build_Test_JDKnext_x86-64_linux_valhalla/1033/`

Closing.

**Comment by hangshao0** [comment]
This is resolved. FYI @a7ehuo
