### ISSUE TITLE
Assertion failed: _methodInfo->getMethodInfo() == reinterpret_cast<TR_OpaqueMethodBlock *>(_j9method)

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9#15426]
From a few different internal builds:

- `/job/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal/386/`
- `/job/Test_openjdk17_j9_extended.system_x86-64_linux_jit_Personal/307/`
- `/job/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Personal/384/`
- `/job/Test_openjdk8_j9_extended.system_ppc64le_linux_jit_Personal/379/`
- `/job/Test_openjdk8_j9_sanity.system_ppc64le_linux_jit_Personal/380/`
- `/job/Test_openjdk17_j9_extended.system_ppc64le_linux_jit_Personal/293/`
- `/job/Test_openjdk17_j9_sanity.system_ppc64le_linux_jit_Personal/293/`

in the following tests:

- `ClassLoadingTest_CS_5m_0`
- `DaaLoadTest_all_CS_5m_0`
- `DaaLoadTest_daa1_CS_5m_0`
- `DaaLoadTest_daa2_CS_5m_0`
- `DaaLoadTest_daa3_CS_5m_0`
- `HCRLateAttachWorkload_0`
- `HCRLateAttachWorkload_1`
- `HCRLateAttachWorkload_previewEnabled_0`
- `HCRLateAttachWorkload_previewEnabled_1`
- `LambdaLoadTest_CS_5m_0`
- `MathLoadTest_all_CS_5m_0`
- `MathLoadTest_autosimd_CS_5m_0`
- `MathLoadTest_bigdecimal_CS_5m_0`
- `ParallelStreamsLoadTest_CS_0`

Console log for, e.g., one of the `HCRLateAttachWorkload_previewEnabled_0` failures:

```
LT  stderr Assertion failed at /home/jenkins/workspace/Build_JDK11_x86-64_linux_jit_Personal/openj9/runtime/compiler/control/CompilationController.cpp:703: _methodInfo->getMethodInfo() == reinterpret_cast<TR_OpaqueMethodBlock *>(_j9method)
LT  stderr 	_methodInfo->getMethodInfo()=0x613a38 != _j9method=0x608458
LT  stderr #0: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x8ab955) [0x7f15bf78d955]
LT  stderr #1: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x8b6d00) [0x7f15bf798d00]
LT  stderr #2: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x580451) [0x7f15bf462451]
LT  stderr #3: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x581b3d) [0x7f15bf463b3d]
LT  stderr #4: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x12fc56) [0x7f15bf011c56]
LT  stderr #5: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x12fccb) [0x7f15bf011ccb]
LT  stderr #6: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x12fe99) [0x7f15bf011e99]
LT  stderr #7: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x132c3f) [0x7f15bf014c3f]
LT  stderr #8: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x45af8f) [0x7f15bf33cf8f]
LT  stderr #9: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x15d19b) [0x7f15bf03f19b]
LT  stderr #10: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so(+0x41127) [0x7f15c720e127]
LT  stderr #11: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so(+0x17a48) [0x7f15c71e4a48]
LT  stderr #12: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x95ab18) [0x7f15bf83cb18]
LT  stderr #13: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x96dd46) [0x7f15bf84fd46]
LT  stderr 
LT  stderr Unhandled exception
LT  stderr Type=Unhandled trap vmState=0x00000000
LT  stderr J9Generic_Signal_Number=00000108 Signal_Number=00000005 Error_Value=00000000 Signal_Code=fffffffa
LT  stderr Handler1=00007F15C720CB30 Handler2=00007F15C6F67690
LT  stderr RDI=0000000000007B8A RSI=0000000000007BC7 RAX=0000000000000000 RBX=00007F1568AE2990
LT  stderr RCX=FFFFFFFFFFFFFFFF RDX=0000000000000005 R8=00007F1568AE6700 R9=00007F1568AE6700
LT  stderr R10=78305B2029363464 R11=0000000000000202 R12=0000000000608458 R13=00007F15C80BA3F0
LT  stderr R14=0000000000608458 R15=00007F15B2AB3610
LT  stderr RIP=00007F15CD0264FB GS=0000 FS=0000 RSP=00007F1568AE2828
LT  stderr EFlags=0000000000000202 CS=0033 RBP=00007F15C80C1120 ERR=0000000000000000
LT  stderr TRAPNO=0000000000000000 OLDMASK=0000000000000000 CR2=0000000000000000
LT  stderr xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm1 00000000000000ff (f: 255.000000, d: 1.259867e-321)
LT  stderr xmm2 67756265446f4e5f (f: 1148145280.000000, d: 2.381955e+190)
LT  stderr xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm5 00007f153950f4bf (f: 961606848.000000, d: 6.903536e-310)
LT  stderr xmm6 00000000be350646 (f: 3191145984.000000, d: 1.576636e-314)
LT  stderr xmm7 0000000085d01af0 (f: 2245008128.000000, d: 1.109181e-314)
LT  stderr xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm9 000000003e17cee7 (f: 1041747712.000000, d: 5.146917e-315)
LT  stderr xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm11 0000ff0000000000 (f: 0.000000, d: 1.385239e-309)
LT  stderr xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr Module=/lib64/libpthread.so.0
LT  stderr Module_base_address=00007F15CD017000 Symbol=raise
LT  stderr Symbol_address=00007F15CD0264D0
LT  stderr Target=2_90_20220624_1151 (Linux 3.10.0-1160.66.1.el7.x86_64)
LT  stderr CPU=amd64 (4 logical CPUs) (0x1e8d07000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr raise+0x2b (0x00007F15CD0264FB [libpthread.so.0+0xf4fb])
LT  stderr _ZN2TR4trapEv+0x47 (0x00007F15BF463AB7 [libj9jit29.so+0x581ab7])
LT  stderr  (0x00007F15BF463B42 [libj9jit29.so+0x581b42])
LT  stderr _ZN2TR26DefaultCompilationStrategy19ProcessJittedSample19shouldProcessSampleEv+0x3b6 (0x00007F15BF011C56 [libj9jit29.so+0x12fc56])
LT  stderr _ZN2TR26DefaultCompilationStrategy19ProcessJittedSample7processEv+0x4b (0x00007F15BF011CCB [libj9jit29.so+0x12fccb])
LT  stderr _ZN2TR26DefaultCompilationStrategy19processJittedSampleEP14TR_MethodEvent+0x89 (0x00007F15BF011E99 [libj9jit29.so+0x12fe99])
LT  stderr _ZN2TR26DefaultCompilationStrategy12processEventEP14TR_MethodEventPb+0x15f (0x00007F15BF014C3F [libj9jit29.so+0x132c3f])
LT  stderr _ZN2J913Recompilation12sampleMethodEPvP11TR_FrontEndS1_iS1_S1_i+0x8f (0x00007F15BF33CF8F [libj9jit29.so+0x45af8f])
LT  stderr jitMethodSampleInterrupt+0x3eb (0x00007F15BF03F19B [libj9jit29.so+0x15d19b])
LT  stderr dispatchAsyncEvents+0xc7 (0x00007F15C720E127 [libj9vm29.so+0x41127])
LT  stderr javaCheckAsyncMessages+0xa8 (0x00007F15C71E4A48 [libj9vm29.so+0x17a48])
LT  stderr old_slow_jitStackOverflow+0xc8 (0x00007F15BF83CB18 [libj9jit29.so+0x95ab18])
LT  stderr  (0x00007F15BF84FD46 [libj9jit29.so+0x96dd46])
```

I think that particular assertion was introduced in 227adc67ad31d2ffff424a678889e1124b4dead8 (from the merge of #15137 yesterday). These initially came up in internal JITAAS tests (reported [here](https://github.com/eclipse-openj9/openj9/issues/14538#issuecomment-1165584446)), but the 100x grinder `/job/Grinder/25284/` of `HCRLateAttachWorkload_previewEnabled_0` without JITAAS fails consistently.

**Comment by pshipton** [comment]
There are more test failures as well in the builds Thursday night. I suspect all the failures caused so many test artifacts that we ran out of disk space, we didn't get any builds on Friday night. I'll be listing the test failures in this issue, but I'm going to start by reverting https://github.com/eclipse-openj9/openj9/pull/15137

**Comment by dsouzai** [comment]
I thought I understood the code such that that assert was valid. I'll have to take a closer look; maybe it is completely possible for the two j9methods to not match. I'll take a look and reopen that PR either with the right assert condition or just not have the assert at all and account for the fact that the two j9methods are different (the previously refactored code used two different variables, so that very likely may be the right thing to do).

**Comment by pshipton** [comment]
jdk11 failures:
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_aarch64_linux_Nightly/199
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_linux_Nightly/197
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_aarch64_mac_Nightly/85
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly/303
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly/303
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly/311
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_linux_Nightly/309
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_mac_Nightly/306
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/309

**Comment by pshipton** [comment]
Take a look at some of other failures, it's more than just that assert.

**Comment by pshipton** [comment]
jdk17 failures:
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_aarch64_linux_Nightly/223
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_aarch64_linux_Nightly/225
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_aarch64_mac_Nightly/86
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_ppc64_aix_Nightly/249
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_ppc64_aix_Nightly/248
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_s390x_linux_Nightly/254
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_linux_Nightly/253
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_mac_Nightly/254
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly/255

**Comment by pshipton** [comment]
jdk18 failures:
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_aarch64_linux_Nightly/90
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_aarch64_linux_Nightly/89
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_aarch64_mac_Nightly/85
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.system_ppc64_aix_Nightly/91
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_ppc64_aix_Nightly/90
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_s390x_linux_Nightly/89
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_x86-64_linux_Nightly/90
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_x86-64_mac_Nightly/90
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_extended.system_x86-64_windows_Nightly/90

**Comment by pshipton** [comment]
Note SharedClassesAPI failures on Windows is a known issue, unrelated to this.

**Comment by pshipton** [comment]
Moving this separate problem to a new issue https://github.com/eclipse-openj9/openj9/issues/15443

**Comment by pshipton** [comment]
The problematic change was reverted (https://github.com/eclipse-openj9/openj9/issues/15426#issuecomment-1167384633) so this can be closed.
