### ISSUE TITLE
Windows 32-bit and amac testing using -XX:+UseCompressedOops fails

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15432]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Release_testList_1/25

regressionFastresolve_mode150_0
```
regressionFastresolve_mode150_0 Start Time: Sun Jun 26 01:43:23 2022 Epoch Time (ms): 1656225803416
variation: Mode150 -Xfastresolve0
JVM_OPTIONS:  -XX:+UseCompressedOops -Xfastresolve0 
Selected VM [compressedrefs] by option -XX:+UseCompressedOops does not exist.
This JVM package only includes the '-Xnocompressedrefs' configuration. Please run the VM without specifying the '-Xcompressedrefs' option or by specifying the '-Xnocompressedrefs' option.
To compile the other configuration, please run configure without '--with-noncompressedrefs'.

regressionFastresolve_mode150_0_FAILED
```

floatSanityTests_2
```
floatSanityTests_2 Start Time: Sun Jun 26 01:51:07 2022 Epoch Time (ms): 1656226267135
variation: Mode150
JVM_OPTIONS:  -XX:+UseCompressedOops 
Selected VM [compressedrefs] by option -XX:+UseCompressedOops does not exist.
This JVM package only includes the '-Xnocompressedrefs' configuration. Please run the VM without specifying the '-Xcompressedrefs' option or by specifying the '-Xnocompressedrefs' option.
To compile the other configuration, please run configure without '--with-noncompressedrefs'.

floatSanityTests_2_FAILED
```

**Comment by pshipton** [comment]
@llxia did something change on the Adoptium side of things? In previous testing these tests were skipped on Windows 32-bit.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Release_testList_1/25
regressionBucketDefault_1

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Release_testList_2/25
TestJlmRemoteThreadNoAuth_0

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Release_testList_1/25
TestJlmRemoteClassNoAuth_0
MathLoadTest_bigdecimal_5m_0
NioLoadTest_5m_0

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Release_testList_0/25/
TestJlmLocal_0
TestJlmRemoteMemoryNoAuth_0
MathLoadTest_autosimd_5m_0
MauveMultiThrdLoad_5m_0
ClassLoadingTest_5m_0

**Comment by pshipton** [comment]
The same problem on amac. I won't list all the resulting failures.

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_mac_Release_testList_1/6/
regressionBucketDefault_1
```
regressionBucketDefault_1 Start Time: Sun Jun 26 16:06:58 2022 Epoch Time (ms): 1656223618007
variation: Mode150
JVM_OPTIONS:  -XX:+UseCompressedOops 
Selected VM [compressedrefs] by option -XX:+UseCompressedOops does not exist.
This JVM package only includes the '-Xnocompressedrefs' configuration. Please run the VM without specifying the '-Xcompressedrefs' option or by specifying the '-Xnocompressedrefs' option.
To compile the other configuration, please run configure without '--with-noncompressedrefs'.

regressionBucketDefault_1_FAILED
```

**Comment by llxia** [comment]
I think this is due to recent PR in TKG. https://github.com/adoptium/TKG/blob/master/resources/ottawa.csv#L57 Mode150 is set to the wrong value. @renfeiw could you fix it? Thanks

**Comment by llxia** [comment]
The above PR is delivered. Close this issue. Please reopen if the issue still occurs.
