### ISSUE TITLE
jdk19 openjdk java/lang/Thread/jni/AttachCurrentThread/AttachTest.java#id1 UnsatisfiedLinkError: jdk/internal/foreign/abi/UpcallLinker.registerNatives()V

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15466]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_OpenJDK19/4
jdk_lang_0 & jdk_lang_1
java/lang/Thread/jni/AttachCurrentThread/AttachTest.java#id1
```
15:16:23  Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: jdk/internal/foreign/abi/UpcallLinker.registerNatives()V
15:16:23  	at java.base/jdk.internal.foreign.abi.UpcallLinker.<clinit>(UpcallLinker.java:206)
15:16:23  	at java.base/jdk.internal.foreign.abi.aarch64.CallArranger.arrangeUpcall(CallArranger.java:171)
15:16:23  	at java.base/jdk.internal.foreign.abi.aarch64.linux.LinuxAArch64Linker.arrangeUpcall(LinuxAArch64Linker.java:61)
15:16:23  	at java.base/jdk.internal.foreign.abi.AbstractLinker.upcallStub(AbstractLinker.java:70)
15:16:23  	at ImplicitAttach.main(ImplicitAttach.java:53)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_OpenJDK19/3
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_linux_OpenJDK19/4/
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_OpenJDK19/4

https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64le_linux_OpenJDK19/4
```
15:53:52  Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
15:53:52  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:171)
15:53:52  	at java.base/jdk.internal.foreign.abi.SharedUtils$1.<clinit>(SharedUtils.java:236)
15:53:52  	at java.base/jdk.internal.foreign.abi.SharedUtils.getSystemLinker(SharedUtils.java:236)
15:53:52  	at java.base/java.lang.foreign.Linker.nativeLinker(Linker.java:198)
15:53:52  	at ImplicitAttach.main(ImplicitAttach.java:48)
15:53:52  Caused by: java.lang.UnsupportedOperationException: Unsupported os, arch, or address size: Linux, ppc64le, 64
15:53:52  	at java.base/jdk.internal.foreign.CABI.<clinit>(CABI.java:59)
15:53:52  	... 4 more
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_s390x_linux_OpenJDK19/4
```
15:31:55  Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
15:31:55  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:171)
15:31:55  	at java.base/jdk.internal.foreign.abi.SharedUtils$1.<clinit>(SharedUtils.java:236)
15:31:55  	at java.base/jdk.internal.foreign.abi.SharedUtils.getSystemLinker(SharedUtils.java:236)
15:31:55  	at java.base/java.lang.foreign.Linker.nativeLinker(Linker.java:198)
15:31:55  	at ImplicitAttach.main(ImplicitAttach.java:48)
15:31:55  Caused by: java.lang.UnsupportedOperationException: Unsupported os, arch, or address size: Linux, s390x, 64
15:31:55  	at java.base/jdk.internal.foreign.CABI.<clinit>(CABI.java:59)
15:31:55  	... 4 more
```

**Comment by pshipton** [comment]
@ChengJin01 fyi

**Comment by pshipton** [comment]
These failures are in the jdk-19+28 acceptance build.
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK19-Acceptance/6/

**Comment by ChengJin01** [comment]
The failing tests above attempted to invoke `upcallStub()` which are not yet merged to JDK19 (still in the progress of code review via https://github.com/eclipse-openj9/openj9/issues/15068)
```
15:16:23  	at java.base/jdk.internal.foreign.abi.AbstractLinker.upcallStub(AbstractLinker.java:70) <------
15:16:23  	at ImplicitAttach.main(ImplicitAttach.java:53)
```
Meanwhile, all previous downcall specific implementation at the java level were entirely removed due to the new API changes in JEP424 and will be replaced with the new code at https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/5 (not yet merged).  So the test need to be excluded till all related code in https://github.com/eclipse-openj9/openj9/issues/15068 are merged to repo.

**Comment by ChengJin01** [comment]
It seems the actual test cases are placed at `/test/jdk/java/lang/Thread/jni/AttachCurrentThread/ImplicitAttach.java` rather than `AttachTest` which is simpler a helper class in `/test/jdk/java/lang/Thread/jni/AttachCurrentThread`. I will create another PR to exclude `ImplicitAttach` to see whether it works as expected.

**Comment by tajila** [comment]
@ChengJin01 has this been addressed?

**Comment by ChengJin01** [comment]
I just verified locally on zLinux which works good as expected:
```
===============================================
Running test jdk_custom_0 ...
===============================================
jdk_custom_0 Start Time: Thu Oct 20 09:03:25 2022 Epoch Time (ms): 1666281805672
"../jdk19_openj9_ffi_cmk_s390x_v09/bin/java" -Xshareclasses:destroyAll; "../jdk19_openj9_ffi_cmk_s390x_v09/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
...
-jdk:"../jdk19_openj9_ffi_cmk_s390x_v09" \
"../aqa-tests/TKG/../openjdk/openjdk-jdk/test/jdk/test/jdk/java/lang/Thread/jni/AttachCurrentThread/AttachTest.java"; \
if [ $? -eq 0 ] ; then echo ""; echo "jdk_custom_0""_PASSED"; echo ""; cd ../aqa-tests/TKG/..;  else echo ""; echo "jdk_custom_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "../aqa-tests/TKG/../TKG/output_16662818048524/TestTargetResult";
Directory "../aqa-tests/TKG/../TKG/output_16662818048524/jdk_custom_0/work" not found: creating
Directory "../aqa-tests/TKG/../TKG/output_16662818048524/jdk_custom_0/report" not found: creating
XML output with verification to ../aqa-tests/TKG/output_16662818048524/jdk_custom_0/work
Test results: passed: 2
```
So it should work fine given the upcall thunk was implemented on all supported platforms. I will need to create a PR at https://github.com/adoptium/aqa-tests to enable this test.

**Comment by ChengJin01** [comment]
https://github.com/adoptium/aqa-tests/pull/4068 has been created to enable the test.

**Comment by ChengJin01** [comment]
Close this issue as https://github.com/adoptium/aqa-tests/pull/4068 has been merged.
