### ISSUE TITLE
ValueTypes: Unsafe.monitorEnter doesnt detect valuebased/value classes

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#15463]
The `Java_sun_misc_Unsafe_monitorEnter` needs to detect a value based class or identity-less and throw an exception (only if certain options are passed for value base classes JEP 390) as we do for the regular monitorEnter. 

We also need to check what the JIT does in this case, whether it is an intrinsic or if it calls the VM.

**Comment by hangshao0** [comment]
Yes, needs a check for `J9_OBJECT_MONITOR_VALUE_TYPE_IMSE` on the return value of `objectMonitorEnter()` in `Java_sun_misc_Unsafe_monitorEnter` to throw an exception. 

For the warning case in value based class, we should be fine as the message is printed out inside `objectMonitorEnter()`

**Comment by hangshao0** [comment]
According to https://bugs.openjdk.org/browse/JDK-8155887, `Unsafe.monitorEnter()` and `Unsafe.tryMonitorEnter()` are already removed. There is nothing left that needs to be done for this issue.

**Comment by hangshao0** [comment]
Closing this based on the comment above.
