### ISSUE TITLE
How to control jit data cache size by command line option?

### ISSUE THREAD

**Issue by Frank-liuyang** [eclipse-openj9/openj9#15478]
Java -version output
--------------------
openjdk version "11.0.14.1" 2022-02-08
IBM Semeru Runtime Open Edition 11.0.14.1 (build 11.0.14.1+1)
Eclipse OpenJ9 VM 11.0.14.1 (build openj9-0.30.1, JRE 11 Linux amd64-64-Bit Compressed References 20220210_379 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - 56c3376ba
JCL      - 5c423dacd0 based on jdk-11.0.14.1+1)

Summary of problem
------------------
It is going to generate some javaCore.* files.
Here is the screenshot:
![02a5fe841548fcb8396ad46693f0601](https://user-images.githubusercontent.com/88373305/177063865-5a70e54a-5a0b-4808-acc4-fab964b030d1.png)

How could I expand the data cache use command line option?

Appreciate.

**Comment by zcz3313** [comment]
We try to use ```-Xcodecachetotal64m``` option to control jit total cache size, but it seems like jit data cache is also affected.
@pshipton Is there an independent option to control just jit data cache?

**Comment by Frank-liuyang** [comment]
Thanks for your reply. I will try this command line option later.

**Comment by pshipton** [comment]
The question has been answered so I'll close this. I can be re-opened if necessary if there is more activity.
