### ISSUE TITLE
Loom: Investigate alternate JIT register spilling

### ISSUE THREAD

**Issue by gacholio** [eclipse-openj9/openj9#15506]
See https://github.com/eclipse-openj9/openj9/issues/15464#issuecomment-1178018557

The issue here is that the a continuation can be run in two ways - the initial mount onto a carrier thread and a remount at some point after the continuation yields (possibly on a different carrier thread).

When run for the first time, a call-in results in a new ELS being created on the C stack of the carrier thread. When a continuation is remounted, the goal is not to call-in.

The JIT spilled registers are currently stored in the C interpreter native stack frame (ELS points to these locations on the C stack). For the initial run, the registers are stored in the call-in stack frame like any other thread. When the continuation is remounted, that ELS will not exist.

**Comment by gacholio** [comment]
An incomplete implementation for xa64 can be seen here: https://github.com/gacholio/openj9/tree/indirect

@tajila @EricYangIBM

**Comment by gacholio** [comment]
@fengxue-IS

**Comment by fengxue-IS** [comment]
Closing this issue as we will be using new design in https://github.com/eclipse-openj9/openj9/issues/15464#issuecomment-1192824120
