### ISSUE TITLE
freetype missing from mac10-x86-4

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15533]
[mac10-x86-4](https://openj9-jenkins.osuosl.org/computer/mac10%2Dx86%2D4/) is missing freetype and fails to build jdk8.
https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_mac_Nightly/332/console
```
19:28:36  + bash configure --with-freemarker-jar=/Users/jenkins/freemarker.jar --with-boot-jdk=/Users/jenkins/bootjdks/jdk8 --disable-zip-debug-info --with-openssl=fetched --enable-openssl-bundling --with-toolchain-type=clang --with-freetype=/usr/local/freetype-2.9.1
...
19:28:44  configure: error: Can not find or use freetype at location given by --with-freetype
```

@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
Removed the build label from the machine.

**Comment by jdekonin** [comment]
Should be good now, looks like I missed 1 "minor" step.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/205/

**Comment by AdamBrousseau** [comment]
Thanks, Joe.
