### ISSUE TITLE
LUDCL refresh points

### ISSUE THREAD

**Issue by rmnattas** [eclipse-openj9/openj9#15570]
In `ObjectInputStream`, the latest user defined class loader (LUDCL) is cached. The cache is refreshed at different points in the code by walking the stack, some of the points are called more ofter than where the LUDCL is actually needed (in `resolveClass()`). This causes the cache to be refreshed and perform a stackWalk more times than LUDCL is used.

This fix removes the points of refresh outside `resolveClass()` so a stackWalk is performed at most as many times the LUDCL is needed, or less if already cached.

- JDK8: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/591
- JDK11: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/552
- JDK17: https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/126
- JDK19: https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/16
- JDKNext: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/475

**Comment by pshipton** [comment]
We don't need jdk18 updated, by the time this change goes it there won't be any more jdk18 releases.

**Comment by rmnattas** [comment]
Tests passed and performance numbers are good. PRs should be good to continue on.

**Comment by rmnattas** [comment]
This should be good to be merged now.

**Comment by pshipton** [comment]
Merged them all but 17, which I plan to do later today after 17.0.5+2 is promoted.

**Comment by keithc-ca** [comment]
Shouldn't there be a similar change for jdk18?

**Comment by pshipton** [comment]
We've already done the last build for jdk18, there is no point in updating it further.
