### ISSUE TITLE
jdmpview "data unavailable" error walking a stack in a Linux core dump

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#15580]
Java -version output
--------------------

Java version from the core dump is IBM Java 8.0.7.5:

```
> !coreinfo
[...]
JAVA VM NAME	- IBM J9 VM
JAVA VM VERSION	- 2.9
JAVA SERVICE LEVEL INFO
JRE 1.8.0 Linux amd64-64 (build 8.0.7.5 - pxa6480sr7fp5-20220208_01(SR7 FP5))
JAVA VERSION INFO
JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220104_19630 (JIT enabled, AOT enabled)
OpenJ9   - 2d4c7d9
OMR      - 59845b7
IBM      - 3c151c1
```

Java version of `jdmpview` is IBM Java 8.0.7.11.

Summary of problem
------------------

`jdmpview` shows the error "data unavailable" when walking the stack of thread 23712 (at the far end of the line for the first stack frame). The top stack frame is `java/util/regex/Pattern$Branch.match`. It also shows the error "corrupt data encountered" trying to inspect the stack frame locals.

```
> info thread 23712
[...]
   associated Java thread: 
    name:          Windows Event Log RPC Protocol Provider Thread: Windows Event Log RPC Provider 336
    Thread object: com/q1labs/semsources/sources/windowseventrpc/WindowsEventRPCProvider @ 0x454e8eb0
    Native info:   !j9vmthread 0x1d92c00  !stack 0x1d92c00
    Daemon:        false
    ID:            920 (0x398)
    Priority:      5
    Thread.State:  RUNNABLE 
    JVMTI state:   ALIVE RUNNABLE 
    Java stack frames: 
     bp: 0x0000000001ed7700  method: boolean java/util/regex/Pattern$Branch.match(java.util.regex.Matcher, int, CharSequence)  source: Pattern.java:<data unavailable>
      objects:<corrupt data encountered>

     <corrupt data encountered>
```

I think the thread state shows it's just in the interpreter:

```
> !j9vmthread 0x1d92c00 | grep omr_vmthread
	0x918: struct OMR_VMThread * omrVMThread = !omr_vmthread 0x0000000001D93580
> !omr_vmthread 0x0000000001D93580 | grep vmState
	0x40: uintptr_t vmState = 0x0000000000000000 (0)
```

The dump was taken without `request=exclusive+prepwalk` (presumably with something like `gcore`). Could that cause this sort of issue?

```
> !context
*0 : PID: 29346;  !j9javavm 0x7f083c022000
> !j9javavm 0x7f083c022000 | grep exclusiveAccessState
                0x1b60: UDATA exclusiveAccessState = 0x0000000000000000 (0)
```

Diagnostic files
----------------

`/ecurep/sf/TS009/860/TS009860298/2022-07-18/ecs-ec-ingress.ecs-ec-ingress.sysdump-18-07-2022.tar.gz_unpack/store/jheap/ecs-ec-ingress.ecs-ec-ingress.system.dmp`

@keithc-ca FYI

**Comment by gacholio** [comment]
A core dump from a crash or any other non-exclusive request (such as gcore) will regularly contains threads that are not in a walkable state.

**Comment by kgibm** [comment]
Ok, that's probably it then. I'll continue to try to get customers to use JVM mechanisms that request the core dump instead, along with the request options `exclusive+prepwalk`. Thanks.
