### ISSUE TITLE
Wrong values in decompressedAsciiTable in the String class

### ISSUE THREAD

**Issue by horn** [eclipse-openj9/openj9#15594]
Java -version output
--------------------

java 11.0.11 2021-04-20
Java(TM) SE Runtime Environment 11.0.11.0-IBM (build 11.0.11+9)
Eclipse OpenJ9 VM 11.0.11.0-IBM (build openj9-0.26.0, JRE 11 Linux amd64-64-Bit Compressed References 20210421_60 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 9110d0b174 based on jdk-11.0.11+9)

Summary of problem
------------------

For some reason decompressedAsciiTable in String class contains wrong values for characters '1' (49) and 'C' (67).

![obrazek](https://user-images.githubusercontent.com/794073/180213699-4b3b1525-5773-4c50-8ccb-011e8412632f.png)

This results in some chinese character being returned instead of the real value for 1-char long Strings.

I have absolutely no idea where those wrong values come from.

**Comment by pshipton** [comment]
Do you have a test case show the problem? The decompressedAsciiTable is created programmatically with the correct values so I assume it's been corrupted somehow. With the information provided so far I don't expect there is anything we can do.

**Comment by horn** [comment]
The problem is that we are not able to isolate the issue and create a test case for that.
It only happens on one of our test servers, we are not able to reproduce the issue elsewhere.
On that specific server, the issue happens consistently always at the same moment.
When client connects to our server, the server performs the same operations multiple times:
It reads the String from DB and parses it using the StringTokenizer.
Few times it works just fine, but after few calls it suddenly stops working as the decompressedAsciiTable changes the values.

Any ideas what could possibly cause the table to become corrupt, please?
Is there anything we can do what would help us with further investigation?

**Comment by pshipton** [comment]
@0xdaryl are there any JIT options you'd recommend trying?
