### ISSUE TITLE
JDK19 j9vm.226    *   ** ASSERTION FAILED ** at openj9/runtime/vm/ContinuationHelpers.cpp:155: ((currentThread->currentContinuation) != NULL)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15624]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_s390x_linux/5/)(`ub18s390xrt-1-1`):
```
openjdk version "19" 2022-09-20
IBM Semeru Runtime Open Edition 19+31 (build 19+31)
Eclipse OpenJ9 VM 19+31 (build master-e70b78378, JRE 19 Linux s390x-64-Bit Compressed References 20220919_19 (JIT enabled, AOT enabled)
OpenJ9   - e70b78378
OMR      - 6061e7ce4
JCL      - 5da3ac5d21 based on jdk-19+31)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F19%2Fibm-semeru-open-jre_s390x_linux_JDK19U_2022-07-23-16-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F19%2Fibm-semeru-open-testimage_s390x_linux_JDK19U_2022-07-23-16-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F19%2Fibm-semeru-open-jdk_s390x_linux_JDK19U_2022-07-23-16-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F19%2Fibm-semeru-open-debugimage_s390x_linux_JDK19U_2022-07-23-16-00.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-07-23T18:15:18.144Z] variation: Mode150
[2022-07-23T18:15:18.144Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-07-23T18:22:24.877Z] TEST: jdk/incubator/concurrent/StructuredTaskScope/StructuredTaskScopeTest.java

[2022-07-23T18:22:24.878Z] STDERR:
[2022-07-23T18:22:24.878Z] WARNING: Using incubator modules: jdk.incubator.concurrent
[2022-07-23T18:22:24.879Z] 18:22:20.728 0x18bc900    j9vm.226    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/build-scripts/jobs/jdk19/jdk19-linux-s390x-openj9/workspace/build/src/openj9/runtime/vm/ContinuationHelpers.cpp:155: ((currentThread->currentContinuation) != NULL)
[2022-07-23T18:22:24.879Z] JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/07/23 11:22:20 - please wait.

[2022-07-23T18:22:24.879Z] TEST RESULT: Failed. Unexpected exit from test [exit code: 255]
[2022-07-23T18:22:24.879Z] --------------------------------------------------
[2022-07-23T18:22:24.879Z] Test results: passed: 264; failed: 1
[2022-07-23T18:22:31.375Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_s390x_linux/jvmtest/openjdk/report/html/report.html
[2022-07-23T18:22:31.375Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16585995717451/jdk_other_0/work
[2022-07-23T18:22:31.376Z] Error: Some tests failed or other problems occurred.
[2022-07-23T18:22:31.376Z] 
[2022-07-23T18:22:31.376Z] jdk_other_0_FAILED
```

fyi @tajila @fengxue-IS

**Comment by tajila** [comment]
@JasonFengJ9 Is that a new test?

**Comment by JasonFengJ9** [comment]
It was added on June 4th - https://github.com/ibmruntimes/openj9-openjdk-jdk19/commit/2929abf7287053519d37c7b5a6ccebd1f1eb8ffa, so it probably missed first round of excludes.

**Comment by tajila** [comment]
> Edit: it was green at [previous weekly run July 16th](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_s390x_linux/4/tapResults/)

Was that before we merged the continuation changes? If so it was use the os thread fallback solution and we should add it to the excludes

**Comment by JasonFengJ9** [comment]
> Was that before we merged the continuation changes? If so it was use the os thread fallback solution and we should add it to the excludes

The code in question is part of https://github.com/eclipse-openj9/openj9/pull/15434 merged on July 18th, so green run was before the continuation changes.
Will create an exclude PR.

**Comment by tajila** [comment]
@fengxue-IS can you take a look at this?

**Comment by fengxue-IS** [comment]
Moving this out of Java 19 milestone as test is targeting structured concurrency which is still in incubator. Not required for Java 19
