### ISSUE TITLE
Assertion failure at ClassLoaderRememberedSet.cpp:248 

### ISSUE THREAD

**Issue by jenifer-alt** [eclipse-openj9/openj9#15633]
Java -version output
--------------------
```
JRE 1.8.0 Linux amd64-64 (build 8.0.7.5 - pxa6480sr7fp5ifix-20220310_01(SR7 FP5+IJ37785))
IBM J9 VM(JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220104_19630 (JIT enabled, AOT enabled)
OpenJ9   - 2d4c7d9
OMR      - 59845b7
IBM      - 3c151c1)
```
Summary of problem
------------------
Client had an assert failure due to accessing a Class before it was fully initialized. 
j9mm.107             Assert     * ** ASSERTION FAILED ** at ClassLoaderRememberedSet.cpp:248: ((false && ((0 != (((((clazz)->classFlags))) & ((0x40)))))))

Diagnostic files
----------------

**Comment by manqingl** [comment]
The problem was caused because a class was exposed to GC before it was fully initialized.

**Comment by manqingl** [comment]
@tajila @dmitripivkine : FYI

**Comment by dmitripivkine** [comment]
An assertion occur while GC was scanning Anonymous classloader RAM segments and discovered j9class without Anonymous flag set. There is a problem - all RAM classes in this classloader must be Anonymous. 
Looks like the reason for this is partially initialized class was exposed to GC.

Current VM/GC contract is: VM should not expose partially initialized classes to GC.
I don't like idea to change this contract - it might cause unpredictable behaviour, unwanted object collections etc

**Comment by tajila** [comment]
FYI @gacholio

**Comment by gacholio** [comment]
I agree that the class must be complete before being presented to the user (in this case, via the JVMTI ClassLoad event).

**Comment by gacholio** [comment]
This code needs to move into `internalCreateRAMClassFromROMClassImpl`

https://github.com/eclipse-openj9/openj9/blob/d47d53ff76701448eeab55f52cae28e0b757802e/runtime/vm/createramclass.cpp#L3536-L3625

**Comment by gacholio** [comment]
The code needs to occur before the new class is put in the hash table or the class load event is sent.

**Comment by manqingl** [comment]
@gacholio @tajila Thanks.
