### ISSUE TITLE
JDK19+ Where should the new TLS be used?

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#15662]
The old TLS is stored in `J9Thread`. There is a 1-to-1 relationship between `J9VMThread` and `J9Thread`. Virtual threads are introduced in JDK19. Many virtual threads can be related to a single `J9VMThread`, which prevents virtual threads to have their own unique TLS in the old implementation. So, the old TLS can't be used at places where the virtual threads are expected to have their own unique TLS.

The new TLS is introduced in https://github.com/eclipse-openj9/openj9/pull/15541. The new TLS is added in the `java.lang.Thread` objects as a hidden field. This allows virtual threads and platform threads to have their own unique TLS.

https://github.com/eclipse-openj9/openj9/pull/15541 will replace the old TLS with the new TLS for the below case:
```
runtime/jvmti/jvmtiHelpers.c:			if (omrthread_tls_alloc(&j9env->tlsKey)) {
```

There are still 6 cases where the old TLS is used.
```
runtime/rastrace/trcmain.c:   if (omrthread_tls_alloc(&j9rasTLSKey)) {

runtime/rastrace/trcmain.c:   if (omrthread_tls_alloc(&j9uteTLSKey)) {

runtime/shared_common/CompositeCache.cpp:   IDATA rc = omrthread_tls_alloc(&(_commonCCInfo->writeMutexEntryCount));

runtime/jnichk/jnicheck.c:   if (omrthread_tls_alloc(&jniEntryCountKey)) {

runtime/jnichk/jnicheck.c:   if (omrthread_tls_alloc(&potentialPendingExceptionKey)) {

runtime/port/common/j9sockptb.c:   if (omrthread_tls_alloc_with_finalizer(&portLibrary->portGlobals->socketTlsKey, j9sock_ptb_free)) {
```

### TASK

To determine if the 6 cases (shown above) need to use the new TLS in JDK19+.

**Comment by babsingh** [comment]
> runtime/shared_common/CompositeCache.cpp:   IDATA rc = omrthread_tls_alloc(&(_commonCCInfo->writeMutexEntryCount));

@hangshao0 I believe that the above SCC case should work fine with the old TLS. Can you confirm if the new TLS is not required for this case?

**Comment by hangshao0** [comment]
> Virtual threads are introduced in JDK19. Many virtual threads can be related to a single J9VMThread, which prevents virtual threads to have their own unique TLS in the old implementation. 

Can such virtual threads be used for classes loading or AOT compilation ?

**Comment by babsingh** [comment]
> Can such virtual threads be used for classes loading or AOT compilation ?

`Class.forName` can be invoked from a virtual thread. So, it should be possible to load classes from a virtual thread.

Not sure about AOT compilation. ++ @dsouzai 

++ @tajila @gacholio

**Comment by tajila** [comment]
I think the important question is, does the scc need to distinguish between a carrierthread and a virtualthread? I think the answer is no. I dont think the Java thread that triggers classloading is particularly relevant from an SCC standpoint, but I could be mistaken.

For aot compilation, I believe the JIT uses JIT threads for that?

**Comment by dsouzai** [comment]
For AOT compilation / AOT load, the JIT uses Compilation Threads; we no longer have code that can do compilation on application threads.

**Comment by gacholio** [comment]
Note that multiple vthreads can never be running on a J9VMThread at the same time - the mapping is 1:1. Any use of the mutex will presumably be in a section of code that cannot swap vthreads (i.e. you never run java code while holding the mutex).

**Comment by hangshao0** [comment]
> Can you confirm if the new TLS is not required for this case?

So the answer is not required.

**Comment by gacholio** [comment]
I'm fairly certain that new TLS is only needed for JVMTI which associates java.lang.Thread instances with the data. OMR TLS associates native threads (i.e. J9VMThread) with the data.

**Comment by babsingh** [comment]
Closing. The new TLS is only needed for JVMTI, which will be handled in https://github.com/eclipse-openj9/openj9/pull/15541.
