### ISSUE TITLE
I can't to deploy an openj9 application on Openshift

### ISSUE THREAD

**Issue by felipejareta** [eclipse-openj9/openj9#15661]
Hi guys.

I've been a problem to deploy an openj9 on openshift platform.
This issue is occuring.

_JVMSHRC559E Failed to create a directory "//javasharedresources" for the shared class cache
JVMSHRC840E Failed to start up the shared cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit._

I've tried to set an environment to this javasharedresources directory but isn't work.

My dockerfile is this:

_FROM adoptopenjdk/openjdk8-openj9:alpine-slim as build
WORKDIR /workspace/app

RUN mkdir -p target

COPY target/*.jar target

RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM adoptopenjdk/openjdk8-openj9:alpine-slim
VOLUME /tmp

ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

RUN apk add --no-cache curl

RUN addgroup bootapp && \
    adduser -D -S -h /var/cache/bootapp -s /sbin/nologin -G bootapp bootapp && \
    chmod -R 777 /app && \
    mkdir /app/config
     

WORKDIR /app

ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms16m -Xmx48m -XX:MaxMetaspaceSize=64m -XX:CompressedClassSpaceSize=8m -Xss256k -Xmn8m -XX:InitialCodeCacheSize=4m -XX:ReservedCodeCacheSize=8m -XX:MaxDirectMemorySize=16m"

USER bootapp

ENTRYPOINT java $JAVA_OPTS -Dlog4j.formatMsgNoLookups=true -Xshareclasses -Xquickstart -cp .:lib/* (my.site.domain).Application_

Does anyone have an idea?

**Comment by pshipton** [comment]
It's looking for the current user's HOME directory, i.e. `//javasharedresources` should be `/<home>/javasharedresources` but the detected HOME directory seems to be empty. 

One way to fix it is to explicitly set the cacheDir for -Xshareclasses, i.e. `-Xshareclasses:cacheDir=<preferred dir>`

**Comment by pshipton** [comment]
https://www.eclipse.org/openj9/docs/xshareclasses/#cachedir

**Comment by felipejareta** [comment]
I've tried this as well in JAVA_OPTS variable:

-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+ExitOnOutOfMemoryError -Xmx100m  -Xshareclasses:cacheDir=/tmp/javasharedresources

But don't worked...
Am i doing it wrong?

**Comment by pshipton** [comment]
Did the error message change? There is nothing wrong with `-Xshareclasses:cacheDir=/tmp/javasharedresources`, it works in a simple test outside of docker.

**Comment by pshipton** [comment]
I see, you've got this `java $JAVA_OPTS -Dlog4j.formatMsgNoLookups=true -Xshareclasses`.
The second `-Xshareclasses` overrides the one in JAVA_OPTS.

**Comment by hangshao0** [comment]
Another solution is to set environment variable "HOME" to the /tmp directory if you want the cache directory to be under it.

**Comment by felipejareta** [comment]
> I see, you've got this `java $JAVA_OPTS -Dlog4j.formatMsgNoLookups=true -Xshareclasses`. The second `-Xshareclasses` overrides the one in JAVA_OPTS.

Great! It works!

Gratitude!
