### ISSUE TITLE
Docker registry access for both openj9-jenkins and hyc-jenkins

### ISSUE THREAD

**Issue by LongyuZhang** [eclipse-openj9/openj9#15676]
Docker Registry is required by Criu Portable Docker Test. Currently we have a docker registry available for hyc-jenkins, but not openj9-jenkins.osuosl. To enable portable test on openj9-jenkins, we can either 
- Add a docker registry for openj9-jenkins
- or Add the credentials of hyc-jenkins docker registry into openj9-jenkins so they can use the same docker registry.

Related Issue: https://github.com/eclipse-openj9/openj9/issues/14486

**Comment by LongyuZhang** [comment]
FYI @AdamBrousseau @tajila @llxia

**Comment by AdamBrousseau** [comment]
Few options I can think of.
1. Add docker images to DockerHub under the [eclipseopenj9 namespace](https://hub.docker.com/u/eclipseopenj9)
2. Add a Docker repo to [OpenJ9 Artifactory](https://openj9-artifactory.osuosl.org/artifactory/webapp/)

We cannot give OpenJ9 Jenkins access to the internal IBM docker registry.

**Comment by LongyuZhang** [comment]
For option 2, Would it be faster in pushing and pulling images than option 1 DockerHub?

Each docker image with criu checkpoint can be around `2GB`, so the space needed will be
- `per_image_size` * `os (ubi & ubuntu)` * `jdk_version` * `jdk_impl` *`platform (x86)` * `micro-architecture ( skylake & broadwell)`
- so far it is `2GB * 2 * 2 * 1 * 1 * 2 = 16G`, but will increase when more options are supported.

**Comment by AdamBrousseau** [comment]
I would guess DockerHub would be faster transfer speeds. We could leave the images on the nodes and do pull/update which will save time. We'd still need to have a periodic cleanup of all nodes so images don't build up over time. I have a job that runs internally that does a prune on all the nodes labeled `sw.tool.docker` (Docker-Prune). We can add it outside too. If we're going to use the same set of images internally, I think my preference would be to **not** use OpenJ9 Artifacotry.

**Comment by AdamBrousseau** [comment]
I don't know about any space limitations, there may be. But if I recall correctly, with the recent DockerHub changes, we now need to ask Eclipse anytime we want to make a new image. This is a 1 time cost per image, then once it is created we can update as often as we need. It's been a while now so I should verify my understanding is correct.

@fredg02 can you comment on any space limitations of Dockerhub [eclipseopenj9](https://hub.docker.com/u/eclipseopenj9) namespace and if we need you (Eclipse) in order to add new images?

**Comment by fredg02** [comment]
AFAIK there are no space limitations (so far). See also https://www.docker.com/pricing/.

>  we now need to ask Eclipse anytime we want to make a new image

I assume you mean "creating a new docker hub repository". In that case, yes.

**Comment by llxia** [comment]
As discussed with @tajila and @AdamBrousseau , we will run Docker-based (external) CRIU testing in hyc Jenkins. I think this issue can be closed.
