### ISSUE TITLE
jit_vich: Invalid JIT return address

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#15673]
> https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal/75/

All tests in this suite pass but there is an error at the end (`Invalid JIT return address`).

```
===============================================
JIT_Test suite
Total tests run: 18, Failures: 0, Skips: 0
===============================================

*** Invalid JIT return address 000000037A4175E0 in 000000016FBDFD98

jit_vich_0_FAILED
```

**Comment by pshipton** [comment]
Closing as dup of https://github.com/eclipse-openj9/openj9/issues/14717
