### ISSUE TITLE
Assertion failure at exceptionsupport.c:648 in internal acceptance build on z/OS

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#15693]
Failure link
------------
Failed in jvm.29.openj9.acceptance build:
`/job_output.php?id=40255768`
 
```
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 8.0.8.0 - pmz6480sr8-20220725_01(SR8))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit 20220810_33974 (JIT enabled, AOT enabled)
OpenJ9   - efaae29
OMR      - a1eb699
IBM      - bf759bf)
JCL - 20220722_01 based on Oracle jdk8u341-b10
```

Optional info
-------------

- intermittent failure: yes
10x grinder all passed: `build_info.php?build_id=33989`
40x grinder all passed: `build_info.php?build_id=33990`

Assertion code is here:
https://github.com/eclipse-openj9/openj9/blob/fc5ae4e6892b7ad809270ecb981606f4095f62da/runtime/vm/exceptionsupport.c#L645-L648

Failure output (captured from console output)
---------------------------------------------
```
10:27:08.138 0x5039e03000    j9vm.547    *   ** ASSERTION FAILED ** at ./exceptionsupport.c:648: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/08/10 10:27:08 - please wait.
JVMDUMP032I JVM requested System dump using 'J9BUILD.JVM.J9BUILD2.D220810.T102708.X&DS' in response to an event
IEATDUMP in progress with options SDATA=(LPA,GRSQ,LSQA,NUC,PSA,RGN,SQA,SUM,SWA,TRT)
IEATDUMP success for DSN='J9BUILD.JVM.J9BUILD2.D220810.T102708.X&DS'
```

**Comment by gacholio** [comment]
This is usually caused by an early inability to allocate native memory. Seems to only ever happen on ZOS.

There's nothing we can do to fix this.
