### ISSUE TITLE
Serviceability tests failing across platforms, DTFJ Core Analyser failed ExceptionInInitializerError

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15731]
[Internal failures](http://vmfarm.rtp.raleigh.ibm.com/jobs_by_status.php?build_id=34371&status=FAILED) in Serviceability tests on all platforms. Seems to be caused by an ExceptionInInitializerError, but details in the output are lacking.

Set a high priority since all these tests are failing regularly now.

```
>> 2022 Mon Aug 15 22:44:29 DTFJ processing failed
>> 2022 Mon Aug 15 22:44:29 Analysis of core file information using DTFJ Core Analyser Complete
>> 2022 Mon Aug 15 22:44:29 Fromatting trace with command: java -Xmx256m com.ibm.jvm.TraceFormat /tmp/bld_34371/diagnostics.xdump_gpf/40685197/cent7x64rtp2-3-diagnostics_xdump-m103-20220815-224332/gpf/expected_dumps/Snap.20220815.224352.13211.0004.trc
>> 2022 Mon Aug 15 22:44:29 Warning: JAVA_DUMP_OPTS already set to ONERROR(ALL) ONEXCEPTION(ALL) ONDUMP(JAVADUMP), leaving as is.
>> 2022 Mon Aug 15 22:44:29 Starting process (java -Xmx256m com.ibm.jvm.TraceFormat /tmp/bld_34371/diagnostics.xdump_gpf/40685197/cent7x64rtp2-3-diagnostics_xdump-m103-20220815-224332/gpf/expected_dumps/Snap.20220815.224352.13211.0004.trc)

>> 2022 Mon Aug 15 22:44:29 Started process
>> 2022 Mon Aug 15 22:44:29 Waiting for process start confirmation: Looking for keyword string "Completed processing"....
>> 2022 Mon Aug 15 22:44:36 Keyword string found, process start confirmed.
>> 2022 Mon Aug 15 22:44:36 gpf test failed...
>> 2022 Mon Aug 15 22:44:36 ERROR: DTFJ Core Analyser failed
>> 2022 Mon Aug 15 22:44:36 ERROR: Found Exception in thread "main" java.lang.ExceptionInInitializerError
 in std error
>> 2022 Mon Aug 15 22:44:36 ERROR: Unable to find pass string Found thread
>> 2022 Mon Aug 15 22:44:36 ERROR: Unable to find pass string Found Runtime
```

Changes from last working build:
https://github.com/eclipse-openj9/openj9/compare/92da2c631ff02...5a9f1569a85778d
https://github.com/eclipse-openj9/openj9-omr/compare/33b7bc883319...909848f974efc

**Comment by pshipton** [comment]
@keithc-ca can you pls take a look.
@tajila fyi

**Comment by keithc-ca** [comment]
This suggests a problem with the test environment:
> Caused by: java.lang.IllegalArgumentException: This stub class should not be on your classpath

**Comment by pshipton** [comment]
I tried a build (of the latest) with https://github.com/eclipse-openj9/openj9/pull/15637 (and https://github.com/eclipse-openj9/openj9/pull/15719) reverted, which seems to fix the test failures.

**Comment by keithc-ca** [comment]
Yes, #15637 introduced uses of `com.ibm.j9ddr.vm29.structure.J9PortLibrary` (which should be entirely reasonable). The test should not be using the stub classes (as the exception says). I'll have a look at the test setup.

**Comment by keithc-ca** [comment]
For the record, I don't think reverting #15719 is relevant.

**Comment by pshipton** [comment]
> For the record, I don't think reverting https://github.com/eclipse-openj9/openj9/pull/15719 is relevant.

Agreed, this change wasn't in the original failing build. It was just easier to revert that so I could revert https://github.com/eclipse-openj9/openj9/pull/15637

**Comment by keithc-ca** [comment]
I am able to reproduce the problem locally with the core file from a failing test.
Classes in the `com.ibm.j9ddr.vm29.structure` package should be derived from the core file rather than read from `j9ddr.jar` (those classes are only in the jar in IBM builds, but perhaps should not be).

**Comment by keithc-ca** [comment]
I expect the solution will be to correct the implementation of methods `getSignalNumber()` and `getSignalName()` in `J9DDRImageProcess`; they don't follow the documented expectations in the [`ImageProcess` interface](https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/ImageProcess.java#L128-L150). The signal and name should be OS-specific so the problematic translation in `J9DDRImageProcess` can be removed.
