### ISSUE TITLE
Loom: Enable JVMTI serviceability tests from the extensions repo

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#15748]
JVMTI serviceability tests: https://github.com/ibmruntimes/openj9-openjdk-jdk19/tree/openj9/test/hotspot/jtreg/serviceability/jvmti 

Currently, OpenJ9 builds neither create the binaries nor run these tests. 

Currently, I run these tests with OpenJ9 by using the test binaries from the Adoptium OpenJDK builds.

For Project Loom, we want to reuse these tests for verifying the OpenJ9 JVMTI functions. Some tests may require minor tweaks. But, it will be less work to enable these tests in our builds than writing the tests from scratch.

@llxia How much time and work will be needed to enable them in OpenJ9 builds?

- Related: https://github.com/eclipse-openj9/openj9/issues/15183

**Comment by babsingh** [comment]
@llxia Example of how we currently run these tests locally: https://github.com/eclipse-openj9/openj9/pull/15753#issuecomment-1221184203.

**Comment by llxia** [comment]
We need serviceability jvmti tests required test libs to run the tests.

Grinder/26903/testReport/

For example:
```
JVMJ9TI001E Agent library FieldAccessWatch could not be opened (libFieldAccessWatch.so: cannot open shared object file: No such file or directory)
JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed
```

afaik, there are two ways for getting OpenJDK native test images:
- option 1: build serviceability jvmti test required test libs in Openj9 build
- option 2: copy serviceability jvmti test required test libs from Temurin build 

Option 2 creates a dependency on the Temurin build, which is not ideal. IMO, option 1 is a better choice. 
For option 1, I am not sure how much work will be needed for building serviceability jvmti test required test libs. 
@AdamBrousseau @pshipton do you have any idea?

**Comment by AdamBrousseau** [comment]
Would this be a similar story to how we currently build/store/share the native test libs in the builds?

**Comment by llxia** [comment]
Yes, it should be very similar. Currently, we only build a limited set of native OpenJDK test libs.

**Comment by AdamBrousseau** [comment]
> For option 1, I am not sure how much work will be needed for building serviceability jvmti test required test libs.

Can we simply start building them and add them to the native test lib tar.gz or do we need another artifact?

**Comment by llxia** [comment]
@keithc-ca, did you update openj9 build to build the existing OpenJDK native test libs? Could you help us to add the native test libs for serviceability tests? Or pointing out what needs to be done?

**Comment by keithc-ca** [comment]
It doesn't look promising: attempting `make test-image-libtest-jtreg-native` tries to build `hotspot-server-gensrc` which fails because we don't have `src/hotspot/share/prims` in our repositories.

This shouldn't be a big surprise given the presence of the `hotspot` folder in `test/hotspot/jtreg/serviceability/jvmti/thread/GetStackTrace`.

**Comment by pshipton** [comment]
@keithc-ca what happens if we remove the hotspot-server-gensrc dependency? We should figure out what is needed so we can evaluate either implementing it / providing it from OpenJ9, or perhaps cut out the hotspot specific part of the testing.

**Comment by keithc-ca** [comment]
I adjusted the change to `make/Main.gmk` so the `test-image-libtest-jtreg-native` target succeeds, but it doesn't create `libFieldAccessWatch.so`, for example. I'll keep digging.

**Comment by keithc-ca** [comment]
With some additional adjustments, and https://github.com/eclipse-openj9/openj9/pull/15896, I was able to build the libraries.

**Comment by keithc-ca** [comment]
See https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/30 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/491.

**Comment by pshipton** [comment]
Everything was merged, so the native library should be in the next build. Tonight for OpenJ9, and late Sat night internally. Or any personal build.

**Comment by llxia** [comment]
@keithc-ca and @pshipton , thanks a lot!
I will enable the test (serviceability_jvmti_j9) once the native library is ready in the build. PR https://github.com/adoptium/aqa-tests/pull/3970

**Comment by llxia** [comment]
serviceability_jvmti_j9 is enabled. It will show up in extended.openjdk JDK19 weekly runs. Or it can be run in Grinder. Please note that this test is not green (94/214 tests failed). Once we have issues created for the failed subtests, we will exclude the failed subtests.

**Comment by babsingh** [comment]
@llxia Can you provide me a link to your grinder/build with the failed tests? Presuming, many of the failed tests use custom JVMTI extension API, which has not been implemented in OpenJ9.

**Comment by llxia** [comment]
It is the same as running any other tests. Set `TARGET=serviceability_jvmti_j9` and `JDK_VERSION=19`. For details, please see the [internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/27829).
