### ISSUE TITLE
build failed due to *** Could not determine OPENJDK_SHA for /root/hostdir/openj9-openjdk-jdk17.  Stop.

### ISSUE THREAD

**Issue by trulliandloeb** [eclipse-openj9/openj9#15757]
Hello dear,

I'm following the guide for compile openj9: 
https://github.com/eclipse-openj9/openj9/blob/master/doc/build-instructions/Build_Instructions_V17.md

But when I run 'make all', I got below error:
root@d8162dbf8ba6:~/hostdir/openj9-openjdk-jdk17# make all
Building OpenJ9 Java Preprocessor
Building /root/hostdir/openj9-openjdk-jdk17/build/linux-x86_64-server-release/support/j9tools/jpp.jar
Generating J9JCL sources
Reading preprocess instructions from xml...
[builder]
Preprocessing /root/hostdir/openj9-openjdk-jdk17/build/linux-x86_64-server-release/support/overlay/src
[builder] 7 of 7 file(s) included in preprocess
[builder] PREPROCESS WAS SUCCESSFUL
Reading preprocess instructions from xml...
[builder]
Preprocessing /root/hostdir/openj9-openjdk-jdk17/closed/src
[builder] 51 of 56 file(s) included in preprocess
[builder] PREPROCESS WAS SUCCESSFUL
Reading preprocess instructions from xml...
[builder]
Preprocessing /root/hostdir/openj9-openjdk-jdk17/openj9/jcl/src
[preprocessor] No INCLUDE-IF directives found.  File will be EXCLUDED
    file: /root/hostdir/openj9-openjdk-jdk17/openj9/jcl/src/java.base/share/classes/java/lang/about.html
    line: 1 (char 0 to 109)
[builder] 1005 of 1124 file(s) included in preprocess
[msg] Messages written to "/root/hostdir/openj9-openjdk-jdk17/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/com/ibm/oti/util/ExternalMessages.properties
[builder] PREPROCESS WAS SUCCESSFUL
Generating DDR_VM sources
Reading preprocess instructions from xml...
[builder]
Preprocessing /root/hostdir/openj9-openjdk-jdk17/openj9/debugtools/DDR_VM/src/.
[builder] 824 of 825 file(s) included in preprocess
[builder] PREPROCESS WAS SUCCESSFUL
Building target 'all' in configuration 'linux-x86_64-server-release'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17/omr'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17/omr
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17/openj9'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17/openj9
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17/omr'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17/omr
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17/openj9'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17/openj9
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17/openj9'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17/openj9
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17/omr'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17/omr
fatal: detected dubious ownership in repository at '/root/hostdir/openj9-openjdk-jdk17'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/hostdir/openj9-openjdk-jdk17
/root/hostdir/openj9-openjdk-jdk17/closed/OpenJ9.gmk:63: *** Could not determine OPENJDK_SHA for /root/hostdir/openj9-openjdk-jdk17.  Stop.
make[2]: *** [/root/hostdir/openj9-openjdk-jdk17/closed/custom/Main.gmk:51: j9vm-build] Error 2
make[2]: *** Waiting for unfinished jobs....
Parsing 2 properties into enum-like class for jdk.compiler
Compiling 7 properties into resource bundles for jdk.jshell
Compiling 16 properties into resource bundles for jdk.compiler
Compiling 13 properties into resource bundles for jdk.javadoc
Compiling 12 properties into resource bundles for jdk.jdeps

ERROR: Build failed for target 'all' in configuration 'linux-x86_64-server-release' (exit code 2)

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

make[1]: *** [/root/hostdir/openj9-openjdk-jdk17/make/Init.gmk:315: main] Error 2
make: *** [/root/hostdir/openj9-openjdk-jdk17/make/Init.gmk:186: all] Error 2

Could you help to check?

**Comment by pshipton** [comment]
It seems like something you should google for help on. I found https://ittutoria.net/fatal-detected-dubious-ownership-in-repository-what-do-we-need-to-do-to-fix-it/ , not sure if it's helpful.

**Comment by keithc-ca** [comment]
The error is because git is trying to keep you safe; see https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9.

**Comment by keithc-ca** [comment]
I don't think there's anything the openj9 project can do to help with this; closing.
