### ISSUE TITLE
Loom: VirtualThread support for JVMTI  GetThreadState

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9#15762]
Part of #15183 
https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html#GetThreadState

Need to check if thread object is VirtualThread, return the correct state based on VirtualThread.state

See: https://github.com/eclipse-openj9/openj9/issues/15183#issuecomment-1167767823

**Comment by hangshao0** [comment]
I can look at this one.
