### ISSUE TITLE
Loom: VirtualThread support for JVMTI GetOSThreadID & InterruptThread

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9#15763]
Part of #15183 
https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html#InterruptThread
https://www.ibm.com/docs/en/sdk-java-technology/8?topic=interfaces-jvmti#getosthreadid

Needs to check for the case of (NULL == targetThread) [i.e. a yielded virtual thread]. 
With the updated sync design of getVMThread, we should always try to pin during the mount/unmount process to ensure accurate result. 
Potential optimization is to add an extra boolean parameter to jvmtiHelpers.c::getVMThread to indicated if caller requires access to volatile data (which must have the vthread pinned) to avoid unneeded pinning a virtual thread to evade the omthread_monitor_* costs.

**Comment by babsingh** [comment]
@hangshao0 I had already worked on this issue earlier this week. See https://github.com/eclipse-openj9/openj9/pull/15843 for my current work. `jvmtiGetOSThreadID` requires similar changes.

Testing is pending: https://github.com/ibmruntimes/openj9-openjdk-jdk19/tree/332135c6a1fedc19e2e607b273125eb242b5d213/test/hotspot/jtreg/serviceability/jvmti/vthread/InterruptThreadTest.
