### ISSUE TITLE
Test Smell: it is not a good practice to write a return statement in test case

### ISSUE THREAD

**Issue by TestSmell** [eclipse-openj9/openj9#15786]
Hi!

I notice that you write a test case with a return statement.
<img width="997" alt="image" src="https://user-images.githubusercontent.com/110402847/187116626-c4c91ec4-d6b0-404c-8842-2690fb67d26d.png">

It is not a good idea to write the return statement in your test case.
So I would like to know if is it really a useful test case? And no assertion is in this test case.
Maybe I think you should remove the @test annotation from this method ?

**Comment by smlambert** [comment]
Dup of https://github.com/eclipse-openj9/openj9/issues/15746
