### ISSUE TITLE
 TestHashTableCorrectness_0 NoSuchElementException in OMR acceptance build

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15791]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal_testList_1/491) openjdk8_j9_sanity.functional_x86-64_linux - ub20x64rt3-4
- OMR acceptance build with changes https://github.com/eclipse-openj9/openj9-omr/compare/openj9...master

TestHashTableCorrectness_0
```
FAILED: testHashTableCorrectness
java.util.NoSuchElementException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1209)
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1265)
	at j9vm.test.hashTable.HashTableCorrectnessTest.calculateTotalLength(HashTableCorrectnessTest.java:146)
	at j9vm.test.hashTable.HashTableCorrectnessTest.testHashTableCorrectness(HashTableCorrectnessTest.java:89)
```

**Comment by pshipton** [comment]
[50x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26971/)

**Comment by pshipton** [comment]
The grinder passed, but the same problem also occurred in the [jdk11 testing](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal_testList_0/1006) in the same OMR acceptance build.

**Comment by pshipton** [comment]
Trying [the jdk8 tests](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/26974/) and [the jdk11 tests](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26973/) on the latest nightly build without the un-promoted OMR changes.

**Comment by pshipton** [comment]
Try another [200x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26975/)

**Comment by pshipton** [comment]
Try a [200x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26976/) on a recent nightly build.

**Comment by pshipton** [comment]
@hzongaro at first glance it appears there is a bad change in OMR which is causing this failure. Until we figure it out, OMR promotion is blocked. Does anything stand out to you?

So far I've narrowed it down to one of the following.
https://github.com/eclipse-openj9/openj9/compare/861ea616f...c14fe74
https://github.com/eclipse-openj9/openj9-omr/compare/938f0686f...87a7601

**Comment by pshipton** [comment]
Dmitri mentioned https://github.com/eclipse/omr/pull/6575 may be a concern so I'll try a build without that change.

**Comment by pshipton** [comment]
[200x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/26978/) without https://github.com/eclipse/omr/pull/6575

**Comment by pshipton** [comment]
@dmitripivkine - it appears that https://github.com/eclipse/omr/pull/6575 is causing the failure.

**Comment by dmitripivkine** [comment]
@LinHu2016 Would you please investigate?

**Comment by pshipton** [comment]
This isn't actually impacting the 0.35 release, which has branched. It only impacts promotion of OMR changes. Removing from the milestone.

**Comment by dmitripivkine** [comment]
> I expect we should revert the change in OMR to unblock the other changes, unless we can have a quick fix.

Let's make this decision today EOD. Currently we have no details about failure

**Comment by pshipton** [comment]
I suspect these failures that occurred in a different OMR accetance build are related as well.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_1/288/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_OMR_testList_0/284/console

**Comment by amicic** [comment]
So far, we don't see how this change could have caused the failure (it's not intended to change behavior, but just expand existing and add new APIs), but we'll keep the change in for another night and continue looking.

BTW, beside reverted GC commit, there is also a small difference in OpenJ9 commits between two builds used in https://github.com/eclipse-openj9/openj9/issues/15791#issuecomment-1230714712 that's failing vs https://github.com/eclipse-openj9/openj9/issues/15791#issuecomment-1230949730 that's passing

Nothing obvious that would affect a HashTable test in a direct way, but perhaps somehow indirectly!?

**Comment by pshipton** [comment]
While there is a difference in OpenJ9 in the two builds, the passing grinder contains more OpenJ9 changes. Unless we think an OpenJ9 change fixed the problem, the GC commit still seems more likely. The other possibility is that we got lucky in the passing grinder, but I can try more grinders runs to try and rule that out.

**Comment by pshipton** [comment]
The new grinder (735 tests) passed. I'm creating a build where the only change is adding back the GC change, and will run another grinder on this JVM when it's ready.

**Comment by pshipton** [comment]
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27000/) where the only difference is the GC change.

**Comment by llxia** [comment]
copyArtifacts works in Openj9 Jenkins, but fails in internal Jenkins. I suspect it is related to Jenkins.
PR is delivered to ensure TestHashTableCorrectness required 3rd party libs get downloaded during the test compilation step if they do not exist (i.e., copyArtifacts fails).

**Comment by pshipton** [comment]
Trying another [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27020/console) to see if it works, but there is no machine to run on atm.

**Comment by pshipton** [comment]
The grinder where the only difference is the GC change isn't finished, but there are [failures](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/1388/) already.

**Comment by pshipton** [comment]
We should really revert the GC change to unblock promotion of the latest OMR changes. There are 3 changes blocked at present.

**Comment by pshipton** [comment]
Hmm, there may be a problem with the conclusions considering the [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/27024/) passed, but child jobs ([2](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/1388/), [6](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_6/453/), [7](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_7/452/), [9](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_9/426/)) failed.
@llxia

**Comment by pshipton** [comment]
I double checked the child jobs all passed in the grinders from https://github.com/eclipse-openj9/openj9/issues/15791#issuecomment-1232241708 and https://github.com/eclipse-openj9/openj9/issues/15791#issuecomment-1230949730, so the GC change being the cause of the problem still stands.

**Comment by amicic** [comment]
@pshipton Thanks a lot for doing the extra testing. Yes, it's reasonable to revert it, while we are trying to fix it
https://github.com/eclipse/omr/pull/6682

**Comment by amicic** [comment]
The problem is understood (the order of some operations have been changed with new wrapper APIs) causing an unintended change of behavior. We have a prototype proven to fix the reported problem, although still testing  for wider conditions (Concurrent Scavenger enabled). Should be ready by EOD.
