### ISSUE TITLE
Loom: Potential issues moving continuations between threads

### ISSUE THREAD

**Issue by gacholio** [eclipse-openj9/openj9#15796]
Certain persistent data is allocated out of thread-local pools in the J9VMThread, so moving continuations between platform threads could lead to the elements being returned to the wrong pool. The reason for thread-local pools is to avoid the need for locking when allocating and freeing.

I can think of two instances immediately:

1) JNI local refs

This should not be an issue due to continuation pinning when calling out to JNI.

2) Monitor enter records

Two obvious solutions are to allocate instead of using a pool (may increase memory fragmentation), or use a locked global pool (which would likely severely degrade interpreter performance).

We could use the global pool only on carrier threads and the thread local pool for standard threads. This will slow down monitor operations in continuations.

**Comment by gacholio** [comment]
@tajila @fengxue-IS

**Comment by fengxue-IS** [comment]
Wouldn't monitor enter also pin the continuation?

**Comment by gacholio** [comment]
Yes, I suppose so. We should take a pass over the thread to see if there are any other instances.

Decompilation records are individually allocated, so they aren't an issue.

**Comment by gacholio** [comment]
At a glance, those are the only two thread local pools, so perhaps this is a complete non-issue.
