### ISSUE TITLE
aarch64_linux aot_test_0_FAILED : AOT header validation failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15801]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.external_aarch64_linux/25/)(`ub18-aarch64-3`):
```
java version "11.0.17" 2022-10-18
IBM Semeru Runtime Certified Edition 11.0.17+2 (build 11.0.17+2)
Eclipse OpenJ9 VM 11.0.17+2 (build master-1719d2e01, JRE 11 Linux aarch64-64-Bit Compressed References 20220827_120 (JIT enabled, AOT enabled)
OpenJ9   - 1719d2e01
OMR      - 938f0686f
JCL      - 3dc2dd0048 based on jdk-11.0.17+2)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.external&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=true&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F120%2Fibm-semeru-certified-jre_aarch64_linux_JDK11U_2022-08-27-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F120%2Fibm-semeru-certified-testimage_aarch64_linux_JDK11U_2022-08-27-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F120%2Fibm-semeru-certified-debugimage_aarch64_linux_JDK11U_2022-08-27-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F120%2Fibm-semeru-certified-jdk_aarch64_linux_JDK11U_2022-08-27-01-00.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=external&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-08-27T01:37:06.441Z] variation: NoOptions
[2022-08-27T01:37:06.441Z] JVM_OPTIONS:  

[2022-08-27T01:37:21.103Z] #INFO:  AOT header validation failed: incompatible compressed pointer shift

[2022-08-27T01:37:21.111Z] Error: AOT header validation failed
[2022-08-27T01:37:21.558Z] 
[2022-08-27T01:37:21.558Z] aot_test_0_FAILED
```

**Comment by pshipton** [comment]
@dsouzai fyi

**Comment by pshipton** [comment]
Pls run a grinder.

**Comment by knn-k** [comment]
This is reproducible in Grinder: job/Grinder/26995/

**Comment by knn-k** [comment]
The test runs in docker.  Perhaps the SCC in the docker image was created in an environment with a different compressed pointer shift amount.

From JIT verbose output:
```
[2022-08-27T01:37:21.103Z] #INFO:  options in effect:
[2022-08-27T01:37:21.103Z] #INFO:       samplingFrequency=2
[2022-08-27T01:37:21.103Z] #INFO:       verbose=1
[2022-08-27T01:37:21.103Z] 
[2022-08-27T01:37:21.103Z] #INFO:       compressedRefs shiftAmount=0
[2022-08-27T01:37:21.103Z] #INFO:  aggressivenessLevel=5
[2022-08-27T01:37:21.103Z] #INFO:  AOT header validation failed: incompatible compressed pointer shift
```

**Comment by dsouzai** [comment]
I think this is because this code in the VM isn't active on aarch64:
https://github.com/eclipse-openj9/openj9/blob/ba83feeac9fdf489d95792ae8db8e2e3bd99a947/runtime/vm/jvminit.c#L1983-L1995

When running in a container, we're supposed to automatically run in Portable SCC mode which limits the CPU features used as well as sets the compressedrefs shift to 3 I believe, at least as per:
https://github.com/eclipse-openj9/openj9/blob/ba83feeac9fdf489d95792ae8db8e2e3bd99a947/runtime/gc_modron_startup/mminit.cpp#L313-L314
https://github.com/eclipse/omr/blob/0db5d7c559b8b47754f1264f73f54c7ca8c7b374/gc/base/Configuration.cpp#L308-L312
```
		if (extensions->shouldForceLowMemoryHeapCeilingShiftIfPossible) {
			if (canChangeShift && (shift < DEFAULT_LOW_MEMORY_HEAP_CEILING_SHIFT)) {
				shift = DEFAULT_LOW_MEMORY_HEAP_CEILING_SHIFT;
			}
		}
```

**Comment by pshipton** [comment]
FYI https://github.com/eclipse-openj9/openj9/pull/15812#issuecomment-1233537528
