### ISSUE TITLE
OpenJ9 crashed with OutOfMemoryError when using SoftReference.

### ISSUE THREAD

**Issue by BurryPotter** [eclipse-openj9/openj9#15818]
### Java -version output
```
openjdk version "11.0.12" 2021-07-20
IBM Semeru Runtime Open Edition 11.0.12.0 (build 11.0.12+7)
Eclipse OpenJ9 VM 11.0.12.0 (build openj9-0.27.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20210730_175 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - 21849e2ca0 based on jdk-11.0.12+7)
```
```
openjdk version "11.0.16.1" 2022-08-12
IBM Semeru Runtime Open Edition 11.0.16.1 (build 11.0.16.1+1)
Eclipse OpenJ9 VM 11.0.16.1 (build openj9-0.33.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220818_429 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - 84b84a0409 based on jdk-11.0.16.1+1)
```
```
openjdk version "1.8.0_332"
IBM Semeru Runtime Open Edition (build 1.8.0_332-b09)
Eclipse OpenJ9 VM (build openj9-0.32.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220422_375 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0b8b8af39a based on jdk8u332-b09)
```
### Summary of problem
The program should be executed with the `-Xmx128m` option.  We want to check if the SoftReference object is recycled. The program will create a lot of SoftReference objects and then call OOME by allocating huge memory. When we use the hotspot virtual machine, there is no output (this is the normal result). But when using OpenJ9 VM 8 and 11, we found they crashed. 

### Reproduce command
```
> java -Xmx128m case1.Case 512 2k

JVMDUMP039I 正在处理转储事件“systhrow”，详细信息“java/lang/OutOfMemoryError”，位于 2022/09/02 15:16:56 - 请稍候。
JVMDUMP032I JVM 使用“D:\projects\Cases\src\core.20220902.151656.21612.0001.dmp”来请求 System 转储以响应事件
JVMDUMP010I System 转储已写入 D:\projects\Cases\src\core.20220902.151656.21612.0001.dmp
JVMDUMP032I JVM 使用“D:\projects\Cases\src\heapdump.20220902.151656.21612.0002.phd”来请求 Heap 转储以响应事件
JVMDUMP010I Heap 转储已写入 D:\projects\Cases\src\heapdump.20220902.151656.21612.0002.phd
JVMDUMP032I JVM 使用“D:\projects\Cases\src\javacore.20220902.151656.21612.0003.txt”来请求 Java 转储以响应事件
JVMDUMP010I Java 转储已写入 D:\projects\Cases\src\javacore.20220902.151656.21612.0003.txt
JVMDUMP032I JVM 使用“D:\projects\Cases\src\Snap.20220902.151656.21612.0004.trc”来请求 Snap 转储以响应事件
JVMDUMP010I Snap 转储已写入 D:\projects\Cases\src\Snap.20220902.151656.21612.0004.trc
JVMDUMP013I 已处理转储事件“systhrow”，详细信息：“java/lang/OutOfMemoryError”。
```

### Diagnostic files

[case1.zip](https://github.com/eclipse-openj9/openj9/files/9475842/case1.zip)

**Comment by pshipton** [comment]
There is no crash. The difference between Hotspot and OpenJ9 is that OpenJ9 has a default dump agent to create diagnostic files when an OOM exception occurs, but OpenJ9 keeps running after producing the diagnostic files.

Usually when an OOM occurs it is unexpected and the diagnostic files are useful to determine what went wrong. The easy way to turn off the diagnostics (all diagnostics) is via `-Xdump:none`, so with OpenJ9 running `java -Xmx128m -Xdump:none case1.Case 512 2k` produces the same result as Hotspot.

For more information about `-Xdump` see https://www.eclipse.org/openj9/docs/xdump/
To see the default OpenJ9 dump agents run `-java -Xdump:what`

**Comment by pshipton** [comment]
Instead of `-Xdump:none` which disables all diagnostics, you can use `-XX:[+|-]HeapDumpOnOutOfMemory`.
https://www.eclipse.org/openj9/docs/xxheapdumponoutofmemory/
