### ISSUE TITLE
There's no way to install openj9 without openjdk for use with Kotlin exclusively with the Apache terms.

### ISSUE THREAD

**Issue by kevincrans** [eclipse-openj9/openj9#15825]
This is a big let down and I don't know if it's legal to remove the openjdk binary/build environment to treat it as apache only, I also see no reason to agree with the gnu gpl terms.

**Comment by DanHeidinga** [comment]
I'm sorry you're disappointed by the licensing of the binaries but we need to comply with the license terms of the code we combine into the final binary.

**Comment by kevincrans** [comment]
Thank you for your response. Too bad, I really like if the user has control over what they use, but it is what it is.
