### ISSUE TITLE
Will it ever be able to be bundled with an iOS app?

### ISSUE THREAD

**Issue by kevincrans** [eclipse-openj9/openj9#15826]
I don't know if Apple m1 is supported yet, but It really frustrates me that there's no way to run Kotlin or Java apps on iOS as an android/java developer

**Comment by pshipton** [comment]
OpenJDK needs to support it before OpenJ9 can support it. 

There are M1 (aarch64) builds of Java available for macOS.
https://adoptium.net/temurin/releases
The OpenJ9 build is Early Access. https://developer.ibm.com/semeru-runtime-downloads/?version=17
