### ISSUE TITLE
win2019-x64-1 not responding

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#15838]
https://openj9-jenkins.osuosl.org/computer/win2019%2Dx64%2D1/log
```
SSH Connection failed with IOException: "connect timed out"
```

@AdamBrousseau @vsebe

**Comment by pshipton** [comment]
Same problem with https://openj9-jenkins.osuosl.org/computer/win2012-x86-1/

I tried renaming these nodes, but it didn't help.

**Comment by vsebe** [comment]
[win2019-x64-1](https://openj9-jenkins.osuosl.org/computer/win2019-x64-1/) is back online.

**Comment by vsebe** [comment]
[win2012-x86-1](https://openj9-jenkins.osuosl.org/computer/win2012-x86-1/) is back online.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/computer/win2012-x86-2 has the same issue.

**Comment by vsebe** [comment]
Rebooted [win2012-x86-2](https://openj9-jenkins.osuosl.org/computer/win2012-x86-2), back online.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/computer/win2012-x86-5a has the same issue

**Comment by vsebe** [comment]
[win2012-x86-5a](https://openj9-jenkins.osuosl.org/computer/win2012-x86-5a) unresponsive, rebooted, is back online.
