### ISSUE TITLE
Missing Q type check in value type

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#15861]
OpenJ9 had added minimal change to recognize and support the 'Q' type introduced in project Valhalla. 
There are other places that Q type check is missing at the moment. Here are a few examples:

https://github.com/eclipse-openj9/openj9/blob/b8752ec8b129f49573912cc1d32a31419ed029a5/runtime/bcutil/ClassFileWriter.cpp#L1232

https://github.com/eclipse-openj9/openj9/blob/b8752ec8b129f49573912cc1d32a31419ed029a5/runtime/cfdumper/main.c#L1055

https://github.com/eclipse-openj9/openj9/blob/b8752ec8b129f49573912cc1d32a31419ed029a5/runtime/rastrace/method_trace.c#L480

We need to do a global search and fix all the missing 'Q' type checks.

**Comment by hangshao0** [comment]
Can you look at this ? @ehrenjulzert

**Comment by ehrenjulzert** [comment]
sure, as we discussed I'll fix decomp.cpp and jswalk.c first and then look at files that affect just the VM

**Comment by hangshao0** [comment]
Can this be closed ? I see https://github.com/eclipse-openj9/openj9/pull/16411 is merged.

**Comment by hangshao0** [comment]
@ehrenjulzert ^^

**Comment by ehrenjulzert** [comment]
Yup, this can be closed now.
