### ISSUE TITLE
AIX Semeru 11.0.16.1 - OpenJ9 0.33.0 JNI call failure

### ISSUE THREAD

**Issue by silviu-nanau** [eclipse-openj9/openj9#15901]
We are using JNI from a graphical application on AIX 7.2.

Semeru 11.0.16.1
OpenJDK 11.0.16.1+1
OpenJ9 0.33.1

We replicated the problem using a sample application.
The JNI calls a simple C++ function - std::getline which fails.
Interesting is that from a command line application (no swing) the same call works.

This worked in:
Semeru 11.0.14.1
OpenJDK 11.0.14.1+1
OpenJ9 0.30.1

**Comment by pshipton** [comment]
The compiler changed for AIX from xlc 13 to xlc 16.1. Did you recompile your JNI with xlc 16.1?

**Comment by silviu-nanau** [comment]
Hello,

We are compiling the JNI library with gcc:

#gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix7.1.0.0/9.3.1/lto-wrapper
Target: powerpc-ibm-aix7.1.0.0
Configured with: ../gcc-9.3.1-20200408/configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++ --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --enable-bootstrap --build=powerpc-ibm-aix7.1.0.0
Thread model: aix
gcc version 9.3.1 20200408 (GCC)

With any older version of Semeru the JNI calls work.

**Comment by pshipton** [comment]
Maybe gcc isn't compatible with xlc 16.1. Does it work if you compile with xlc 16.1?

**Comment by pshipton** [comment]
Java 17 is also compiled with xlC 16.1
gcc is not supported.
I expect it's an incompatibility between gcc and xlC, nothing to do with JNI itself. Using C instead of C++ should work fine.
