### ISSUE TITLE
Valhalla : Access is not abstract and does not override abstract method isPrimitiveClass(Class<?>) in JavaLangAccess

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#15929]
Latest valhalla local build failure after resolving merging conflicts:
```
build/macosx-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:67: error: Access is not abstract and does not override abstract method isPrimitiveClass(Class<?>) in JavaLangAccess
final class Access implements JavaLangAccess {
```

In addition, there is another error - reference not found `Class#accessFlags()`.
```
src/java.base/share/classes/java/lang/reflect/Modifier.java:40: error: reference not found
 * @see Class#accessFlags()
 ```

FYI @hangshao0

**Comment by hangshao0** [comment]
For the error regarding `Class#accessFlags()`, a new public API `public Set<AccessFlag> accessFlags()` is introduced in jdknext (Java 20), and OpenJ9 is missing the implementation. This is more like a jdknext issue rather than a Valhalla issue. I will create a separate issue to track that.

**Comment by hangshao0** [comment]
> I will create a separate issue to track that.

https://github.com/eclipse-openj9/openj9/issues/15933

**Comment by hangshao0** [comment]
Seems that there is a merge issue that result in redefinition of `unexpectedClasses` here: https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/blob/openj9/test/hotspot/jtreg/vmTestbase/nsk/jvmti/ClassPrepare/classprep001/classprep001.cpp#L67-L73

**Comment by JasonFengJ9** [comment]
> redefinition of unexpectedClasses

Note: this is fixed via https://github.com/ibmruntimes/openj9-openjdk-jdk.valuetypes/pull/5
