### ISSUE TITLE
JVM from jdk-11.0.16.1+1 fails to start on AIX

### ISSUE THREAD

**Issue by rrozenshteyn-jha** [eclipse-openj9/openj9#16039]
Hi,

I've downloaded **[ibm-semeru-certified-jdk_ppc64_aix_11.0.16.1.tar.gz](https://github.com/ibmruntimes/semeru11-certified-binaries/releases/download/jdk-11.0.16.1%2B1_openj9-0.33.1/ibm-semeru-certified-jdk_ppc64_aix_11.0.16.1.tar.gz)** to test if our application can run on the latest available Java 11 version.  After extracting the contents to a local directory on our AIX development partition, I attempted to execute the _java -version_ command and got the following error:

```
$jdk-11.0.16.1+1/bin/java -version
failed to open </SYM/TEST/rrozenshteyn/work/java_11_0_16_1_install_test/jdk-11.0.16.1+1/lib/default/libjvm.so> - reason: <Could not load module /SYM/TEST/rrozenshteyn/work/java_11_0_16_1_install_test/jdk-11.0.16.1+1/lib/default/libjvm.so.
        Dependent module libc++.a(shr_64.o) could not be loaded.
Could not load module libc++.a(shr_64.o).
System error: No such file or directory
Could not load module /SYM/TEST/rrozenshteyn/work/java_11_0_16_1_install_test/jdk-11.0.16.1+1/lib/default/libjvm.so.
```
We have an existing older version of Java 11 installed on the same partition and the works just fine:

```
$/usr/java11_64/bin/java -version
java version "11.0.13" 2021-10-19
IBM Semeru Runtime Certified Edition 11.0.13.0 (build 11.0.13+8)
Eclipse OpenJ9 VM 11.0.13.0 (build openj9-0.29.0, JRE 11 AIX ppc64-64-Bit Compressed References 20211022_168 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 43ed76284c based on jdk-11.0.13+8)
```

Here's the partition info:

```
$oslevel -s
7100-04-01-1543
$prtconf
System Model: IBM,9040-MR9
Machine Serial Number: 78EB77X
Processor Type: PowerPC_POWER9
Processor Implementation Mode: POWER 8
Processor Version: PV_8_Compat
Number Of Processors: 20
Processor Clock Speed: 3000 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
...
```

**Comment by pshipton** [comment]
What changes is the new version is compiled with xlC 16.1 so you need the C++ Runtime installed now.
https://www.eclipse.org/openj9/docs/version0.33/#xl-c-runtime-required-on-aix

**Comment by rrozenshteyn-jha** [comment]
Ok.  Thank you @pshipton .  I will bring this up with our AIX support team.
