### ISSUE TITLE
Consider updating references to openjdk.java.net

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#16057]
OpenJDK has started updating URLs so they refer instead to openjdk.org (see https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0fe8bef36f6034d33d362e2d09b52f19cd66f352). The old URLs currently redirect to the new domain, but it's unclear how long that will be the case. If there were only a few references in this repository, I would have just opened a pull request, but the copyright notice of most files includes a reference to http://openjdk.java.net/legal/assembly-exception.html, so it seems prudent to discuss what action, if any, we should take.

See also https://github.com/eclipse/omr/issues/6755.

**Comment by DanHeidinga** [comment]
I agree with Peter.  Updating to point to the new URL seems like the right path.  Timeline sounds fine as well
