### ISSUE TITLE
JDK11 throws the RuntimeException, but JDK8 executes normally

### ISSUE THREAD

**Issue by JavaTailor** [eclipse-openj9/openj9#16078]
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at [[attachment](https://github.com/eclipse-openj9/openj9/issues/new?assignees=&labels=userRaised&template=user-problem.md##Attachment)](##Attachment).

Windows 10:

```
Microsoft Windows 10 Professional
10.0.19044 Build 19044
AMD Ryzen 5 5600G with Radeon Graphics 3.90 GHz
Memory 32 GB
```

Java -version output under Windows 10

```
openjdk version "1.8.0_332"
IBM Semeru Runtime Open Edition (build 1.8.0_332-b09)
Eclipse OpenJ9 VM (build openj9-0.32.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220422_375 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - 0b8b8af39a based on jdk8u332-b09)
```

```
openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20220422_352 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)
```

## Problem summary
When the test case TestCase22 is executed using JDK11, a RuntimeException is thrown, and JDK8 executes normally.

## Attachment
[TestCase22.zip](https://github.com/eclipse-openj9/openj9/files/9752079/TestCase22.zip)

**Comment by pshipton** [comment]
Hospot has the same behavior so I expect this is normal.

```
TestCase22 {
  Test4486735 {
    Uncaught exception thrown in test method Test4486735
Exception in thread "main" java.lang.RuntimeException: Uncaught exception thrown in test method Test4486735
	at TestCase22_interface.errImpl(IntlTest.jasm)
	at TestCase22_interface.errln(IntlTest.jasm)
	at TestCase22_interface.run(IntlTest.jasm)
	at TestCase22.main(DateFormatTest.jasm)
```

**Comment by pshipton** [comment]
Whatever is causing it, I notice jdk18, jdk19 have the same (passing) behavior as jdk8.

**Comment by JavaTailor** [comment]
> Whatever is causing it, I notice jdk18, jdk19 have the same (passing) behavior as jdk8.

We also submit relevant issue reports to the hotspot developers. They believe that the reported issue was confirmed to exist before JDK 17.0.4.1 but not observed in later versions (18,19,20). Since this problem has not been observed in later releases, the initial fix will be ported back to JDK 17 and 11.
