### ISSUE TITLE
Wrong -Dfile.encoding option picked up after #14285

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#16080]
This issue was found with IBM Java, in a scenario where a customer sets a system wide default `-Dfile.encoding` option in the IBM_JAVA_OPTIONS environment variable, and applications can override the default by specifying their own `-Dfile.encoding` option on their command line. This works because the second `-Dfile.encoding` option on the command line supercedes the first.

Simple testcase:

```
public class SysPropTest {
	public static void main (String[] args) {
		if (args.length != 1) {
			System.err.println("Usage:  java SysPropTest <system property name>");
			System.exit(1);
		}
		System.out.println(args[0] + " = " + System.getProperty(args[0]));
	}
}
```

This works as expected up until 8.0.7.5:

```
> java -Dfile.encoding="UTF-8" -Dfile.encoding="CP1141" SysPropTest file.encoding
file.encoding = CP1141
```

But with 8.0.7.6 and later, the _first_ `-Dfile.encoding` property is picked up instead, and the second one is ignored.

```
> java -Dfile.encoding="UTF-8" -Dfile.encoding="CP1141" SysPropTest file.encoding
file.encoding = UTF-8
```

I believe the patch for #14285 is responsible: https://github.com/eclipse-openj9/openj9/commit/06c46171dceb65fd17eca78a7ce2ebe7338032ac

The system properties are held in a Properties instance in the java.lang.System class, and prior to the patch above, the `-Dfile.encoding` options (along with any other `-D` options on the command line) were added to the Properties instance in order, from left to right, so that if two options specifying the same property key were on the command line, the second one would replace the first.

However, for reasons that aren't completely clear to me, the patch changes the code so that it gets the value of the `-Dfile.encoding` option before the System class's Properties instance is populated, and then adds that cached value to the Properties instance after it has been populated, thus replacing the value for the `file.encoding` property.

This is a problem because the cached value is obtained using this function:

https://github.com/eclipse-openj9/openj9/blob/8cf30924a98eced7b8685948e5e8e271e0399506/runtime/jcl/common/system.c#L308-L311

Which goes through the system property options on the command line from left to right and returns the **first** one it finds, not the last one. As a result, after the patch for #14285 is applied, the first `-Dfile.encoding` option is picked up instead of the second one.

**Comment by pshipton** [comment]
@tajila @JasonFengJ9 fyi
