### ISSUE TITLE
JITServer AOT caching failing

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9#16099]
Attn @mpirvu, @AlexeyKhrabrov. While testing #15949 with acmeair, I noticed a lot of messages in the log like:

```
#JITServer: clientUID 293357720754206506 failed to get defining class chain record for 0000000000050300 due to the AOT cache size limit; method 000000000004F7E0 won't be loaded from or stored in AOT cache
```

without any "AOT cache allocations exceeded maximum..." message earlier in the log. That means that at some point loading the class chain record fails for some reason unrelated to the cache limit, but the `missingLoaderInfo` flag is not updated properly.

**Comment by cjjdespres** [comment]
I think this issue might be interfering with AOT caching in my testing of #15949; after applying an acmeair load I get these statistics for the cache:

```
JITServer AOT cache  statistics:
        stored methods: 0
        class loader records: 52
        class records: 1725
        method records: 0
        class chain records: 0
        well-known classes records: 0
        AOT header records: 1
        cache bypasses: 807
        cache hits: 0
        cache misses: 7111
        deserialized methods: 0
        deserialization failures: 0
```

and that seems implausible to me.

**Comment by AlexeyKhrabrov** [comment]
Yeah this looks pretty bad, class chain record creation is broken. What exact version of the code are there results for?

**Comment by cjjdespres** [comment]
I tested it with the version of master that the persistence PR is based on, which is commit 628e9db3d74554ebd3757e82b4feb3da78d7529d.
