### ISSUE TITLE
zlinux jdk8 builds take 3+ hours or timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16136]
Related to https://github.com/eclipse-openj9/openj9/issues/16037

The last "fast" nightly build was https://openj9-jenkins.osuosl.org/job/Build_JDK8_s390x_linux_Nightly/408/ - 1:25 on Oct 11.

Subsequent builds take 3+ hours or timeout.
https://openj9-jenkins.osuosl.org/job/Build_JDK8_s390x_linux_Nightly/
https://openj9-jenkins.osuosl.org/job/Build_JDK8_s390x_linux_OMR/

@jdekonin

**Comment by pshipton** [comment]
Creating jsse.jar is very slow, not sure what's special about creating that jar file. The build could be generating something.
```
19:57:17  Creating images/lib/jsse.jar
21:00:55  Creating images/lib/jconsole.jar
```

**Comment by pshipton** [comment]
Looking at the machine while running `16:11:06  Creating images/lib/jsse.jar`, it seems to be gmake which is taking all the time. The only java running atm is for jenkins
```
52067 jenkins   20   0  455660 341996    940 R  99.0  4.2  14:55.48 gmake                                                                                    
```

`GNU Make 3.82`

**Comment by pshipton** [comment]
Can we update gmake to a newer version, 4.1 or later?

**Comment by pshipton** [comment]
The old build showed
`configure: Using GNU make 3.81 (or later) at /usr/local/bin/gmake (version: GNU Make 4.1)`
the new
`configure: Using GNU make 3.81 (or later) at /usr/bin/gmake (version: GNU Make 3.82)`

**Comment by jdekonin** [comment]
Somehow this was missed for the Redhat 7 systems.  I've v4.1 on them now.

**Comment by pshipton** [comment]
No, that fixed it.
