### ISSUE TITLE
cent7-ppcle-1 - /home/jenkins/set_gcc_10.3.0_env: No such file or directory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16151]
https://openj9-jenkins.osuosl.org/job/Build_JDK19_ppc64le_linux_OMR/22/console - [cent7-ppcle-1](https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-1)
```
13:07:42  /home/jenkins/workspace/Build_JDK19_ppc64le_linux_OMR@tmp/durable-5b3dee1b/script.sh: line 1: /home/jenkins/set_gcc_10.3.0_env: No such file or directory
```

@AdamBrousseau @vsebe

**Comment by AdamBrousseau** [comment]
Maybe why it was missing labels. I only tested jdk11.

**Comment by vsebe** [comment]
```
15:31:42  configure: Using default toolchain gcc (GNU Compiler Collection)
15:31:42  checking for gcc... /usr/local/gcc10/bin/gcc
15:31:42  checking resolved symbolic links for CC... /usr/local/gcc10/bin/gcc-10.3
15:31:42  configure: Using gcc C compiler version 10.3.0 [gcc (GCC) 10.3.0]
```
https://openj9-jenkins.osuosl.org/job/Build_JDK19_ppc64le_linux_Personal/45/ running on [cent7-ppcle-1](https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-1)
