### ISSUE TITLE
[JDK19] JVMTI GetCarrierThread

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#16168]
JVMTI **GetCarrierThread** is part of the JVMTI Extension API, which is not covered by the [JVMTI documentation](https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html). So, it doesn't need to be supported for the current [Java 19 milestone](https://github.com/eclipse-openj9/openj9/milestone/35).

GetCarrierThread just returns the carrier thread object for a virtual thread via one of the input parameters.

The following **JVMTI serviceability tests will need to be disabled** until support for GetCarrierThread is introduced:
```
stress/StackTrace/Suspended/libGetStackTraceSuspendedStress.cpp
vthread/GetSetLocalTest/libGetSetLocalTest.cpp
vthread/MethodExitTest/libMethodExitTest.cpp
vthread/RawMonitorTest/libRawMonitorTest.cpp
vthread/VThreadMonitorTest/libVThreadMonitorTest.cpp
vthread/VThreadTest/libVThreadTest.cpp
vthread/WaitNotifySuspendedVThreadTest/libWaitNotifySuspendedVThread.cpp
```

**Comment by babsingh** [comment]
fyi @fengxue-IS @tajila @pshipton @JasonFengJ9

**Comment by pshipton** [comment]
Is somebody taking care of excluding those tests?

**Comment by babsingh** [comment]
@fengxue-IS Can you confirm if you plan to exclude the above tests while enabling the fixed tests?

**Comment by fengxue-IS** [comment]
> @fengxue-IS Can you confirm if you plan to exclude the above tests while enabling the fixed tests?

yes, I've created https://github.com/fengxue-IS/aqa-tests/tree/loom3 to address this, still testing to make sure it covers all cases

**Comment by babsingh** [comment]
The JVMTI GetCarrierThread extension function is implemented in https://github.com/eclipse-openj9/openj9/pull/16518.

For JDK20, no test is disabled due to this issue in https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk20-openj9.txt.

Thus, closing this issue.
