### ISSUE TITLE
[JDK19] JVMTI VirtualThread[Mount|UnMount] Events

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#16167]
**JVMTI VirtualThreadMount and VirtualThreadUnMount events** are part of the **JVMTI Extension API**, which is not covered by the [JVMTI documentation](https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html). So, they don't need to be supported for the current [Java 19 milestone](https://github.com/eclipse-openj9/openj9/milestone/35).

Their implementation will be similar to the VirtualThreadStart and VirtualThreadEnd events. VirtualThreadStart and VirtualThreadEnd events are only triggered during the first mount and last unmount respectively. But, VirtualThreadMount and VirtualThreadUnMount events will be triggered on each mount and unmount respectively.

The following **JVMTI serviceability tests will need to be disabled** until support for the VirtualThreadMount and VirtualThreadUnMount events is introduced:
```
vthread/BreakpointInYieldTest/libBreakpointInYieldTest.cpp
vthread/MethodExitTest/libMethodExitTest.cpp
vthread/NullAsCurrentThreadTest/libNullAsCurrentThreadTest.cpp
vthread/VThreadTest/libVThreadTest.cpp
vthread/VThreadUnsupportedTest/libVThreadUnsupportedTest.cpp
```

**Comment by babsingh** [comment]
fyi @fengxue-IS @tajila @pshipton @JasonFengJ9

**Comment by pshipton** [comment]
Is somebody taking care of excluding those tests?

**Comment by babsingh** [comment]
@fengxue-IS Can you confirm if you plan to exclude the above tests while enabling the fixed tests?

**Comment by fengxue-IS** [comment]
> @fengxue-IS Can you confirm if you plan to exclude the above tests while enabling the fixed tests?

yes, I've created https://github.com/fengxue-IS/aqa-tests/tree/loom3 to address this, still testing to make sure it covers all cases

**Comment by babsingh** [comment]
@dipak-bagadiya Can you look at this issue?

The solution will be similar to the `VirtualThreadStart` and `VirtualThreadEnd` events, which were implemented in https://github.com/eclipse-openj9/openj9/pull/15254.

The only difference is that the `VirtualThreadMount` and `VirtualThreadUnMount` events are part of the JVMTI Extension API. Existing JVMTI extension events are implemented in `jvmtiExtensionMechanism.c`. Samples:

https://github.com/eclipse-openj9/openj9/blob/3f2decad888ba945e3b1604c7b70215a8755227c/runtime/jvmti/jvmtiExtensionMechanism.c#L737-L743

fyi @fengxue-IS @tajila

**Comment by babsingh** [comment]
Reopening since the disabled tests still need to be re-enabled.

**Comment by babsingh** [comment]
The events were implemented in https://github.com/eclipse-openj9/openj9/pull/16501.

For JDK20, no test is disabled due to this issue in https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk20-openj9.txt.

Thus, closing this issue.
