### ISSUE TITLE
zlinux build killed

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16173]
https://openj9-jenkins.osuosl.org/job/Build_JDK17_s390x_linux_Personal/369/console - [rh7-390-4](https://openj9-jenkins.osuosl.org/computer/rh7-390-4)
```
13:22:41  /usr/bin/bash: line 1:  9730 Killed                  /home/jenkins/bootjdks/jdk17/bin/java -Xms64M -Xmx1600M -Duser.language=en -Duser.country=US -Xshare:auto ...
```

@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
No cleanup zlinux job running at the time.
All node config appear to be using unique IPs.
I see Joe is running a compile now.

**Comment by jdekonin** [comment]
The compile passed without issue, the PR that triggered doesn't appear to have anything to do with javadoc (where the failures above is), so not sure what to say.  Short of reviewing to make sure the OpenJ9/OpenJDK javadoc dependencies are accurate, I don't see a problem atm.

https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/281/

**Comment by pshipton** [comment]
The failing build isn't a PR build, it's a weekly build for special.system testing, so it's building the head stream. The other java versions (8, 11) worked. The OMR acceptance this morning worked. I suspect sometimes our zlinux machines don't have enough resources and the build gets killed by the OS.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK17_s390x_linux_Nightly/345 - [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3)
```
19:26:55  /usr/bin/bash: line 1: 37637 Killed                  /home/jenkins/bootjdks/jdk17/bin/java -Xms64M -Xmx1600M -Duser.language=en -Duser.country=US ...
```

**Comment by pshipton** [comment]
Even the restart didn't work, on [rh7-390-2](https://openj9-jenkins.osuosl.org/computer/rh7-390-2).
https://openj9-jenkins.osuosl.org/job/Build_JDK17_s390x_linux_Nightly/346/consoleFull

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Build_JDK17_s390x_linux_OpenJDK17/43/console - [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3)

**Comment by pshipton** [comment]
Both 11 & 17 show the following.
```
09:28:58  Build performance summary:
09:28:58  * Cores to use:   5
09:28:58  * Memory limit:   7873 MB
```

The javadoc tool may be different on 17 vs 11. I don't see anything explicit, but the implementation on 17 may be using jdk17 features.

Is there anything in the /var/log about the process being killed? Afaik it's the OS killing the process, nothing with the JDK itself.

The machines have 8GB, and 4 cores (at least rh7-390-3, assuming they are all the same). The process that was killed in the last failure shows ` /home/jenkins/bootjdks/jdk17/bin/java -Xms64M -Xmx1600M`, so it's not trying to use too much memory for the JDK.

bootjdk is openj9-0.33.1

The jenkins agent may be using the default heap size, which is 25% of 8MB, i.e. 2MB. This is the max heap size, which isn't necessarily all used. On rh7-390-3 there is an agent for both openj9 and omr but memory usage doesn't seem too excessive.

```
                           RES
omr       20   0 4935400 738332  12780 S   0.7  9.2  55:10.76 java                               
jenkins   20   0 5195820 290628  34040 S   0.3  3.6   1:23.37 java                               
```

**Comment by pshipton** [comment]
Can we run the omr/jenkins agents with -Xmx1G to reduce the max heap and virtual memory usage?

The machines seems to have zero swap space, so if the physical memory is ever exceeded, that could explain why processes are being killed.

**Comment by AdamBrousseau** [comment]
We can. It's a bit of a pain because it requires a code change. Can we do it in an environment variable? That would be faster to test.
We should probably assign some swap too.

**Comment by pshipton** [comment]
The environment variable will affect all JVMs that see it, which may have side affects. We should try some swap and see how that goes.

**Comment by pshipton** [comment]
Removed the ci.role.build label from rh7-390-3

**Comment by jdekonin** [comment]
> Can we run the omr/jenkins agents with -Xmx1G to reduce the max heap

rh7-s390x-03 & rh7-s390x-04 have both been modified on jenkins only.  A jenkins restart will reset this as its not done in config-as-code.

Swap configured on 01->04 for 8G.  ci.role.build label added back to rh7-390-3

**Comment by AdamBrousseau** [comment]
Seems this is more stable now. Can we update ALL shared nodes on both farms to be Xmx 1G and then close this?
aarch-mac-8, rh7-390-3, rh7-390-4.

**Comment by jdekonin** [comment]
Should we disable core generation for the node connections as well??  `-Xdump:none`

**Comment by pshipton** [comment]
> Should we disable core generation for the node connections as well?? -Xdump:none

As mentioned in https://github.com/eclipse-cbi/jiro/pull/235#issuecomment-1317743870 we can do the following to disabled dumps for OOM but keep other dumps, such as for crashes, enabled.
`-Xdump:system:none -Xdump:heap:none -Xdump:java:none -Xdump:snap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -Xdump:java:events=gpf+user+abort+traceassert+corruptcache -Xdump:snap:events=gpf+abort+traceassert+corruptcache`

**Comment by jdekonin** [comment]
I poked the PR and asked it to be merged and deployed.  I had updated the PR with the suggested Xdump settings above.  The OpenJ9 node configurations for these same machines have been updated as well.

**Comment by jdekonin** [comment]
PRs merged, I suggest closing this down if problems are no longer seen.
