### ISSUE TITLE
[JDK19] JVMTI GetVirtualThread

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#16203]
JVMTI **GetVirtualThread** is part of the JVMTI Extension API, which is not covered by the [JVMTI documentation](https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html). So, it doesn't need to be supported for the current [Java 19 milestone](https://github.com/eclipse-openj9/openj9/milestone/35).

GetVirtualThread just returns the virtual thread object corresponding to a carrier thread via one of the input parameters. It's the inverse of GetCarrierThread (see https://github.com/eclipse-openj9/openj9/issues/16168).

The following **JVMTI serviceability tests will need to be disabled** until support for GetVirtualThread is introduced:
```
serviceability/jvmti/vthread/SuspendResume1/SuspendResume1.java
serviceability/jvmti/vthread/VThreadTest/VThreadTest.java
serviceability/jvmti/vthread/MethodExitTest/MethodExitTest.java

serviceability/jvmti/stress/ThreadLocalStorage/SetGetThreadLocalStorageStressTest/SetGetThreadLocalStorageStressTest.java
serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java
serviceability/jvmti/stress/StackTrace/NotSuspended/GetStackTraceNotSuspendedStressTest.java
```

Related: #16187

Excluded via https://github.com/adoptium/aqa-tests/pull/4087.

**Comment by babsingh** [comment]
@JasonFengJ9 @fengxue-IS I have updated the list of tests impacted by JVMTI GetVirtualThread. They will need to be excluded.

**Comment by JasonFengJ9** [comment]
Created https://github.com/adoptium/aqa-tests/pull/4122 to exclude following tests:
```
serviceability/jvmti/RedefineClasses/RedefineRunningMethodsWithBacktrace.java
serviceability/jvmti/stress/StackTrace/NotSuspended/GetStackTraceNotSuspendedStressTest.java
serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java
```
