### ISSUE TITLE
[JDK19] JVMTI ContYieldBreakPointTest Fails

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#16215]
This test is related to Project Loom and passes with the RI.

Related: #16187.

### Issue
- `Java_ContYieldBreakPointTest_enableEvents` invokes `jvmtiGetClassMethods` and tries to find the `yield0` method in the `jdk.internal.vm.Continuation` class.
- But, `yield0` does not exist in OpenJ9's implementation of the `jdk.internal.vm.Continuation` class.
- We can either update the test or match our implementation of the `jdk.internal.vm.Continuation` class with the RI to resolve this failure.
- Until then, this test cannot be supported with OpenJ9.
- Related test code:
```
  err = jvmti->GetClassMethods(contKlass, &method_count, &methods);
  check_jvmti_status(jni, err, "enableEvents: error in JVMTI GetClassMethods");

  // Find jmethodID of Continuation.yield0()
  while (--method_count >= 0) {
    jmethodID meth = methods[method_count];
    char* mname = get_method_name(jvmti, jni, meth);

    if (strcmp(mname, "yield0") == 0) {
      LOG("enableEvents: found method %s() to set a breakpoint\n", mname);

      method = meth;
    }
    deallocate(jvmti, jni, (void*)mname);
  }
  if (method == NULL) {
    jni->FatalError("Error in enableEvents: not found method fibTest()");
  }
```

### Test CMD
```
make test TEST="jtreg:test/hotspot/jtreg/serviceability/jvmti/vthread/ContYieldBreakPointTest/ContYieldBreakPointTest.java" JTREG="JAVA_OPTIONS=--enable-preview -Dvm.continuations=true;VERBOSE=all"
```

### Test Output
```
STDOUT:
Agent_OnLoad started
Agent_OnLoad finished

######   main: started   #####


####  runTest: started  ####


####  yieldTest: started  ####


####  yieldTest: done warming up ####

enableEvents: started
STDERR:

Fatal error: Error in enableEvents: not found method fibTest()
```

**Comment by babsingh** [comment]
> `yield0` does not exist in OpenJ9's implementation of the `jdk.internal.vm.Continuation` class. We can either update the test or match our implementation of the `jdk.internal.vm.Continuation` class with the RI to resolve this failure.

RI's signature for `yield0`
```
    private boolean yield0(ContinuationScope scope, Continuation child) {
```

@fengxue-IS Let us know how shall we proceed. Tagged this failure under the current Java 19 milestone. If this test does not need to be supported, please change the milestone.

**Comment by fengxue-IS** [comment]
OpenJ9 have a separate impl on how continuation is yielded due to the difference in native representation of a continuation. This test should be excluded for now and we can re-visit this when working on structured concurrency.

**Comment by babsingh** [comment]
As per https://github.com/eclipse-openj9/openj9/issues/16437#issuecomment-1397695263, structured concurrency won't need more changes. @fengxue-IS Will it be easy and straightforward to match the RI: https://github.com/eclipse-openj9/openj9/issues/16215#issuecomment-1293536241? The goal is to enable the test for JDK20 if feasible.

**Comment by babsingh** [comment]
@fengxue-IS any updates on https://github.com/eclipse-openj9/openj9/issues/16215#issuecomment-1402119622?

**Comment by fengxue-IS** [comment]
I've tried a prototype https://github.com/eclipse-openj9/openj9/pull/16693.
Test passed with this change in JDK19
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/serviceability/jvmti/vthread/ContYieldBreakPointTest/ContYieldBreakPointTest.java
                                                         1     1     0     0   
==============================
TEST SUCCESS
```
Given that this change doesn't offer any benefit other than passing this test, we should have a discussion on if this should be merged.

**Comment by babsingh** [comment]
Closing, `ContYieldBreakPointTest` enabled in https://github.com/adoptium/aqa-tests/pull/4550.
