### ISSUE TITLE
Most macOS aarch64 machines have a version mismatch

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16216]
See also [internal issue](https://github.ibm.com/runtimes/infrastructure/issues/7412).

https://openj9-jenkins.osuosl.org/label/sw.os.mac.11_5/
mac11-aarch64-1 through mac11-aarch64-8 have a sw.os.mac.11_5 label, but according to `sw_vers` only mac11-aarch64-1 is 11.5.2 and the rest are all 11.4 machines.

However if you run `defaults read loginwindow SystemVersionStampAsString` on the machines 2-8, you get `11.5.2`.
This is currently stopping us from running jdk20 sanity.openjdk testing on these machines, as per https://github.com/adoptium/aqa-tests/issues/4090
See also https://bugs.openjdk.java.net/browse/JDK-8253702

**Comment by jdekonin** [comment]
- [x] mac11-aarch64-01
- [x] mac11-aarch64-02
- [x] mac11-aarch64-03
- [x] mac11-aarch64-04
- [x] mac11-aarch64-05
- [x] mac11-aarch64-06
- [x] mac11-aarch64-07
- [x] mac11-aarch64-08 - upgraded via https://github.com/eclipse-openj9/openj9/issues/16210

All systems updated to 11.7.1.
