### ISSUE TITLE
"source /home/jenkins/set_gcc_11.2.0_env" not working on rh7-390-1

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16221]
The gcc11 builds use `source /home/jenkins/set_gcc_11.2.0_env` to setup the gcc 11 compile environment. On [rh7-390-1](https://openj9-jenkins.osuosl.org/computer/rh7-390-1) this does nothing since configure detects gcc 4.8.5

https://openj9-jenkins.osuosl.org/job/Build_JDK19_s390x_linux_gcc11_Personal/96/

@vsebe @AdamBrousseau

**Comment by pshipton** [comment]
These are new machines, so maybe I need to ping @jdekonin

**Comment by jdekonin** [comment]
A couple links didn't get created.  I've corrected and should work as expected now.  I've verified the other 3 work as expected.

```
gcc (Adoptium/sxa) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ (Adoptium/sxa) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
