### ISSUE TITLE
Loom - JVMTI - Bad VM access

### ISSUE THREAD

**Issue by gacholio** [eclipse-openj9/openj9#16250]
By inspection:

https://github.com/gacholio/openj9/blob/9997d015a7e591cd675c42c01008fc5813ad7682/runtime/jvmti/jvmtiThread.c#L537

https://github.com/gacholio/openj9/blob/9997d015a7e591cd675c42c01008fc5813ad7682/runtime/jvmti/jvmtiThread.c#L544

`releaseVMThread` must be called with VM access.

I suggest you look for other such cases.

**Comment by babsingh** [comment]
Most times, `releaseVMThread` is immediately followed by `internalExitVMToJNI`, which suggests that VM access has been acquired. For the below functions, this pattern was not followed. But I have verified that their callers acquire VM access before invoking them. So, the only location to be fixed is `jvmtiGetThreadInfo` (https://github.com/eclipse-openj9/openj9/pull/15765) as mentioned in the issue's description.

```
getVirtualThreadState
setEventNotificationMode
resumeThread
getThreadGroupChildrenImpl
suspendThread
```
