### ISSUE TITLE
jdk19 OpenJDK VectorTests assertArraysEquals failures

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16255]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_Nightly/44
    jdk/incubator/vector/Byte128VectorTests.java.Byte128VectorTests
    jdk/incubator/vector/Double128VectorTests.java.Double128VectorTests
    jdk/incubator/vector/Float128VectorTests.java.Float128VectorTests
    jdk/incubator/vector/Int128VectorTests.java.Int128VectorTests
    jdk/incubator/vector/Long128VectorTests.java.Long128VectorTests
    jdk/incubator/vector/Short128VectorTests.java.Short128VectorTests

Example
```
21:44:31  test Byte128VectorTests.ABSMaskedByte128VectorTests(byte[i * 5], mask[i % 2]): failure
21:44:31  java.lang.AssertionError: at index #33, input = -91, mask = false expected [-91] but found [91]
21:44:31  	at org.testng.Assert.fail(Assert.java:99)
21:44:31  	at org.testng.Assert.failNotEquals(Assert.java:1037)
21:44:31  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
21:44:31  	at org.testng.Assert.assertEquals(Assert.java:122)
21:44:31  	at org.testng.Assert.assertEquals(Assert.java:841)
21:44:31  	at Byte128VectorTests.assertArraysEquals(Byte128VectorTests.java:109)
21:44:31  	at Byte128VectorTests.ABSMaskedByte128VectorTests(Byte128VectorTests.java:5265)
```

Changes from previous build
https://github.com/eclipse-openj9/openj9/compare/fd7e4b9412...a31c79403ab
https://github.com/eclipse-openj9/openj9-omr/compare/29a6de35...fc60df565a2

@knn-k @gita-omr pls take a look. Not sure if this is intermittent or not. If it's caused by a recent change, ideally we'll quickly fix or revert so we don't have a regular failure in the builds.

**Comment by pshipton** [comment]
Running jdk_vector_byte128_j9_0 to check if easily repeatable https://openj9-jenkins.osuosl.org/job/Grinder/1491/

**Comment by pshipton** [comment]
Trying a full sanity run https://openj9-jenkins.osuosl.org/job/Grinder/1493/

**Comment by pshipton** [comment]
I take it back, the grinder on jdk_vector_byte128_j9_0 is failing tests, although the jenkins result is passing. Similarly for the full sanity run, tests are failing, but jenkins is showing passed. I've got https://github.com/adoptium/aqa-tests/issues/4115 open for the test harness problems. Ignore the harness problem, in the results from [two nights ago](https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_Nightly/43/consoleFull) I don't see these failures, so it does seem like a regression from the changes made yesterday.

```
11:08:17  test Byte128VectorTests.ABSMaskedByte128VectorTests(byte[i * 5], mask[i % 2]): failure
11:08:17  java.lang.AssertionError: at index #33, input = -91, mask = false expected [-91] but found [91]
11:08:17  	at org.testng.Assert.fail(Assert.java:99)
11:08:17  	at org.testng.Assert.failNotEquals(Assert.java:1037)
11:08:17  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
11:08:17  	at org.testng.Assert.assertEquals(Assert.java:122)
11:08:17  	at org.testng.Assert.assertEquals(Assert.java:841)
11:08:17  	at Byte128VectorTests.assertArraysEquals(Byte128VectorTests.java:109)
11:08:17  	at Byte128VectorTests.ABSMaskedByte128VectorTests(Byte128VectorTests.java:5265)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_Nightly/45/

**Comment by knn-k** [comment]
FYI @Akira1Saitoh

**Comment by Akira1Saitoh** [comment]
On compressed reference builds, the offset to the first element of the contiguous array is 24.
https://github.com/eclipse-openj9/openj9/blob/f6c7bee4bf4b5c00be9f0e20bd6b3efaf95004bf/runtime/oti/j9nonbuilder.h#L3061-L3068

However, the immediate offset for 128-bit load/store must be multiples of 16, and it seems aarch64 codegen does not handle the offset restriction and generates incorrect binary encoding for the tree below. 
```
 192881  n5347n   (  0)  mstore  <auto slot -1>[#1170  Auto] [flags 0x17 0x0 ] (X!=0 )                        [       0x11282f710] bci=[0,47,208] rc=0 vc=6213 vn=- li=381│
 192881  udi=- nc=1 flg=0x4                                                                                                                                               │
 192882  n735n    (  0)    v2mVector128Int8_Vector128Int8 (in VRF_0032) ()                                    [       0x112225570] bci=[0,47,208] rc=0 vc=6213 vn=- li=381│
 192882  udi=11056 nc=1 flg=0x20                                                                                                                                          │
 192883  n6805n   (  0)      vloadi  <generic int shadow>[#1169  Shadow] [flags 0x603 0x0 ] (in VRF_0032)     [       0x11302bed0] bci=[0,47,208] rc=0 vc=6213 vn=- li=381│
 192883  udi=11056 nc=1                                                                                                                                                   │
 192884  n6794n   (  0)        aladd (X>=0 sharedMemory )                                                     [       0x11302bb60] bci=[-1,0,50] rc=0 vc=6213 vn=- li=381 │
 192884 udi=- nc=2 flg=0x100                                                                                                                                              │
 192885  n681n    (  0)          ==>aRegLoad (in &GPR_0018) (X!=0 sharedMemory )                                                                                          │
 192886  n6792n   (  0)          lconst 24 (highWordZero X!=0 X>=0 )                                          [       0x11302bac0] bci=[-1,0,50] rc=0 vc=6213 vn=- li=381 │
 192886 udi=- nc=0 flg=0x4104     
```

**Comment by Akira1Saitoh** [comment]
https://github.com/eclipse/omr/pull/6802 and https://github.com/eclipse/omr/pull/6803 will fix this problem.

**Comment by knn-k** [comment]
I reviewed and merged the two OMR changes above.
