### ISSUE TITLE
JDK19 serviceability_jvmti_j9_1_FAILED serviceability/jvmti/vthread/SelfSuspendDisablerTest/SelfSuspendDisablerTest.java  Test FAILED: Unexpected thread state

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16276]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk19_j9_extended.openjdk_s390x_linux/23/)(`rhel7s390x-4-6`):
```
openjdk version "19.0.1" 2022-10-18
IBM Semeru Runtime Open Edition 19.0.1+10 (build 19.0.1+10)
Eclipse OpenJ9 VM 19.0.1+10 (build master-f6c7bee4b, JRE 19 Linux s390x-64-Bit Compressed References 20221018_71 (JIT enabled, AOT enabled)
OpenJ9   - f6c7bee4b
OMR      - 357df2f80
JCL      - 110e1e7808 based on jdk-19.0.1+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=serviceability_jvmti_j9_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F71%2Fibm-semeru-open-jdk_s390x_linux_JDK19U_2022-11-05-16-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F71%2Fibm-semeru-open-jre_s390x_linux_JDK19U_2022-11-05-16-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F71%2Fibm-semeru-open-debugimage_s390x_linux_JDK19U_2022-11-05-16-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk19%2Fjdk19-linux-s390x-openj9%2F71%2Fibm-semeru-open-testimage_s390x_linux_JDK19U_2022-11-05-16-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=19&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk19&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2022-11-05T17:27:26.328Z] variation: Mode650
[2022-11-05T17:27:26.328Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-11-05T17:46:43.917Z] TEST: serviceability/jvmti/vthread/SelfSuspendDisablerTest/SelfSuspendDisablerTest.java

[2022-11-05T17:46:43.918Z] STDOUT:
[2022-11-05T17:46:43.918Z] Agent init started
[2022-11-05T17:46:43.918Z] Agent init finished
[2022-11-05T17:46:43.918Z] Expected platform thread state: 000000 got: 000000
[2022-11-05T17:46:43.918Z] Expected virtual  thread state: 000000 got: 000000
[2022-11-05T17:46:43.918Z] Expected platform thread state: 000005 got: 000005
[2022-11-05T17:46:43.918Z] Expected virtual  thread state: 000005 got: 000005
[2022-11-05T17:46:43.918Z] Expected platform thread state: 100005 got: 500005
[2022-11-05T17:46:43.918Z] Timeout refired 960 times
[2022-11-05T17:46:43.918Z] STDERR:
[2022-11-05T17:46:43.918Z] Exception in thread "" java.lang.RuntimeException: Test FAILED: Unexpected thread state
[2022-11-05T17:46:43.918Z] 	at SelfSuspendDisablerTest.testJvmtiThreadState(SelfSuspendDisablerTest.java:67)
[2022-11-05T17:46:43.918Z] 	at SelfSuspendDisablerTest.lambda$main$1(SelfSuspendDisablerTest.java:83)
[2022-11-05T17:46:43.918Z] 	at java.base/java.lang.VirtualThread.run(VirtualThread.java:292)
[2022-11-05T17:46:43.918Z] 	at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:179)
[2022-11-05T17:46:43.918Z] 	at java.base/jdk.internal.vm.Continuation.execute(Continuation.java:171)

[2022-11-05T17:46:43.918Z] Test results: passed: 112; error: 1
[2022-11-05T17:46:43.918Z] Report written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_s390x_linux/jvmtest/openjdk/report/html/report.html
[2022-11-05T17:46:43.918Z] Results written to /home/jenkins/workspace/Test_openjdk19_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16676679384301/serviceability_jvmti_j9_1/work
[2022-11-05T17:46:43.918Z] Error: Some tests failed or other problems occurred.
[2022-11-05T17:46:43.918Z] 
[2022-11-05T17:46:43.918Z] serviceability_jvmti_j9_1_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/29372/) - all failed

**Comment by babsingh** [comment]
The test fails for a platform thread. This is not related to Project Loom, and does not need to be addressed for the Java 19 release.

The thread is correctly suspended. But, the `JVMTI_THREAD_STATE_IN_NATIVE` flag is set in the thread-state, which causes the test to fail. The failure only occurs on Linux s390. As per the rules in [JVMTI GetThreadState's spec](https://download.java.net/java/early_access/jdk19/docs/specs/jvmti.html#GetThreadState), `JVMTI_THREAD_STATE_IN_NATIVE` is allowed to be set along with `JVMTI_THREAD_STATE_SUSPENDED`.

So, the test needs to perform a check similar to `OMR_ARE_ALL_BITS_SET` instead of an equality check [(state != expectedState)](https://github.com/ibmruntimes/openj9-openjdk-jdk19/blob/110e1e7808efdb0cdd180dfb12a22843777f3d3c/test/hotspot/jtreg/serviceability/jvmti/vthread/SelfSuspendDisablerTest/SelfSuspendDisablerTest.java#L66) to resolve this failure.

```
[2022-11-05T17:46:43.918Z] Expected platform thread state: 100005 got: 500005

Expected:
- 0x000001: JVMTI_THREAD_STATE_ALIVE
- 0x000004: JVMTI_THREAD_STATE_RUNNABLE
- 0x100000: JVMTI_THREAD_STATE_SUSPENDED

Got:
- 0x000001: JVMTI_THREAD_STATE_ALIVE
- 0x000004: JVMTI_THREAD_STATE_RUNNABLE
- 0x100000: JVMTI_THREAD_STATE_SUSPENDED
- 0x400000: JVMTI_THREAD_STATE_IN_NATIVE
```

Ref:
https://github.com/eclipse-openj9/openj9/blob/f21e2960c6b6880df3eebbe631a4da20dc68cd7d/runtime/include/jvmti.h.m4#L72-L87

**Comment by babsingh** [comment]
Created a fix: https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/50.

Running a personal build: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/14771/

**Comment by keithc-ca** [comment]
I don't agree with the solution to this. The quoted document says:

> More than one of
> JVMTI_THREAD_STATE_SUSPENDED
> JVMTI_THREAD_STATE_INTERRUPTED
> JVMTI_THREAD_STATE_IN_NATIVE
> can be set, but if any is set, JVMTI_THREAD_STATE_ALIVE is set.

This says to me that `JVMTI_THREAD_STATE_IN_NATIVE` is not permitted in combination with `JVMTI_THREAD_STATE_SUSPENDED`.

**Comment by tajila** [comment]
> This says to me that JVMTI_THREAD_STATE_IN_NATIVE is not permitted in combination with JVMTI_THREAD_STATE_SUSPENDED.

Can you please elaborate? "More than one of..." implies that both `JVMTI_THREAD_STATE_IN_NATIVE` and `JVMTI_THREAD_STATE_SUSPENDED` can be set simultaneously.

**Comment by keithc-ca** [comment]
Perhaps I read too quickly (or misread that document). Either I assumed that `ALIVE` was incompatible with `SUSPENDED` or I misread 'more than one of' as 'not more than one of' (like earlier sections). I no longer see a problem with the combination of `NATIVE` and `SUSPENDED`.

On the other hand, the test was excessively relaxed, by ignoring all bits other than the expected ones: now situations where more bits are set than legally should be will not (but should) fail.

**Comment by tajila** [comment]
@babsingh can you address Keiths comment

**Comment by babsingh** [comment]
Yes, planning to create a fix by EOD.

**Comment by babsingh** [comment]
**FIX** for the issue described in https://github.com/eclipse-openj9/openj9/issues/16276#issuecomment-1325608709:
- https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/52; and
- https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/529.

fyi @tajila @keithc-ca
