### ISSUE TITLE
OpenJ9 fails to create core file on MacOS 13

### ISSUE THREAD

**Issue by mikezhang1234567890** [eclipse-openj9/openj9#16328]
Java -version output
--------------------

All OpenJ9 versions.

Summary of problem
------------------

On MacOS 13, OpenJ9 fails to generate system cores. This issue occurs on M1 and x86-64 based Macs.

Example output below:
```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400

$ ./semeru-jdk-17.0.5+8/Contents/Home/bin/java -Xdump:system:events=vmstart -version
JVMDUMP039I Processing dump event "vmstart", detail "" at 2022/11/15 12:16:35 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/mike-z/jdks/core.20221115.121635.6720.0001.dmp' in response to an event
task_thread failed with:  (ipc/send) invalid destination port
error getting thread command data:
 (ipc/send) invalid destination port
JVMDUMP012E Error in System dump: /Users/mike-z/jdks/core.20221115.121635.6720.0001.dmp
JVMDUMP013I Processed dump event "vmstart", detail "".
openjdk version "17.0.5" 2022-10-18
IBM Semeru Runtime Open Edition 17.0.5.0 (build 17.0.5+8)
Eclipse OpenJ9 VM 17.0.5.0 (build openj9-0.35.0, JRE 17 Mac OS X amd64-64-Bit Compressed References 20221018_304 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
```

Failure looks to be caused by the system function `task_thread` failing, so we likely need to work around some change in MacOS 13 to get system cores working again.

**Comment by pshipton** [comment]
Actually I'll tag this for 0.36 in case we're able to fix in in time, otherwise we'll move it out.

**Comment by pshipton** [comment]
This also happens intermittently on older versions, https://github.com/eclipse-openj9/openj9/issues/13811

**Comment by pshipton** [comment]
@mikezhang1234567890 what is the latest status on this one?

**Comment by mikezhang1234567890** [comment]
It looks like MacOS 13 disables the ability to pass the parent's task port to the child process we use to create the core dump via assigning it to the bootstrap port. However, we can pass normal mach ports and use those to send the task port to the child process so it can control the parent in order to create the core dump.

Will have a PR created later today.
