### ISSUE TITLE
JVMTI framepop02.java#id1 checks outside a virtual thread's scope

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#16346]
### Issue

In `framepop02/framepop02.java#id1`, the JVMTI frame pop event expects the thread to be a virtual thread after the invocation of `VirtualThread.unmount`.

This is not true since `J9VMThread->threadObject` is changed to the carrier thread in `VirtualThread.unmount`.

Virtual thread's scope is between the `mount` and `unmount` phases. The test should enforce its checks within a virtual thread's scope.

Currently, this test is incompatible with OpenJ9 since it enforces its checks outside a virtual thread's scope.

### Test CMD

```
# FramePop/framepop02
make test TEST="jtreg:test/hotspot/jtreg/serviceability/jvmti/events/FramePop/framepop02" JTREG="JAVA_OPTIONS=--enable-preview -Dvm.continuations=true;VERBOSE=all"
```

### Test Output

```
>>>  Test Thread #5: Ljava/lang/VirtualThread;.setState(I)V, depth = 17
[2022-11-20.21:38:09] >>> Frame Pop
>>>  Test Thread #4: Ljava/lang/VirtualThread;.setState(I)V, depth = 17
[2022-11-20.21:38:09]>>> Method entry
>>>  Test Thread #5: Ljava/lang/VirtualThread;.yieldContinuation()Z, depth = 17
[2022-11-20.21:38:09]>>> Method entry
>>>  Test Thread #4: Ljava/lang/VirtualThread;.yieldContinuation()Z, depth = 17
[2022-11-20.21:38:09]>>> Native Method entry
>>>  Test Thread #5: Ljava/lang/VirtualThread;.notifyJvmtiUnmountBegin(Z)V, depth = 18
[2022-11-20.21:38:09]>>> Method entry
>>>  Test Thread #5: Ljava/lang/VirtualThread;.unmount()V, depth = 18
[2022-11-20.21:38:09]>>> Method entry
>>>  Test Thread #3: Ljava/lang/Thread;.isVirtual()Z, depth = 14
[2022-11-20.21:38:09] >>> Frame Pop
>>>  ForkJoinPool-1-worker-6: Ljava/lang/VirtualThread;.unmount()V, depth = 10
  ForkJoinPool-1-worker-6: Ljava/lang/VirtualThread;.unmount()V, depth = 10
STDERR:

Fatal error: Unknown thread:
```

**Comment by babsingh** [comment]
@dipak-bagadiya Can you investigate this issue? The first step will be to verify if https://github.com/eclipse-openj9/openj9/pull/16654 fixes this issue.

fyi @thallium @fengxue-IS

**Comment by babsingh** [comment]
@dipak-bagadiya https://github.com/eclipse-openj9/openj9/issues/16689 has higher priority. So, this task should be pursued after https://github.com/eclipse-openj9/openj9/issues/16689.

**Comment by dipak-bagadiya** [comment]
This issue is not resolved by #16654; the test case framepop02 failed with the same error.
@babsingh

**Comment by dipak-bagadiya** [comment]
The framepop02 failure will fix by #17125.

**Comment by babsingh** [comment]
https://github.com/eclipse-openj9/openj9/issues/17490 has been opened for the `MethodExitTest` failure in https://github.com/eclipse-openj9/openj9/issues/16346#issuecomment-1420787157 since it happens due to different reasons. This issue will only focus on the `framepop02` failure which should be fixed by https://github.com/eclipse-openj9/openj9/pull/17125.

**Comment by babsingh** [comment]
https://github.com/eclipse-openj9/openj9/pull/17125 fixes this test failure. It was embedded in https://github.com/eclipse-openj9/openj9/pull/17514 and merged. https://github.com/adoptium/aqa-tests/pull/4687 has been opened to re-enable `framepop02.java#id1`.
