### ISSUE TITLE
Support and enable arraycmp IL opcode for AArch64

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#16363]

**Comment by 0xdaryl** [comment]
@knn-k @Akira1Saitoh

**Comment by knn-k** [comment]
Related issues: https://github.com/eclipse/omr/issues/6092 and #13103

**Comment by knn-k** [comment]
arraycmp for AArch64 was implemented in https://github.com/eclipse/omr/pull/6904.  Closing.
