### ISSUE TITLE
Clarify JVMPORT030W and JVMDUMP012E

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#16367]
Many modern Linux distributions have moved to setting `kernel.core_pattern=|$PROGRAM` by default to pipe core dumps to a core dump processing program (e.g. `systemd-coredump`, etc.). This is a welcome change that allows for the constraint of per-core dump or all-core dump disk usage, allowing for avoidance of core dump disk exhaustion that may lead to catastrophic application outages (e.g. application transaction logs can't be written to).

A poor practice has developed of support engineers recommending customers override such a core dump processing program by reverting to the Linux default of `kernel.core_pattern=core` which produces core dumps in the current working directory of the process. This is understandable for two reasons:

1. If J9 can find the core dump, as it normally can with a non-piped `core_pattern`, then it will [post-process the core dump](https://github.com/eclipse-openj9/openj9-omr/blob/openj9-0.35.0/port/linux/omrosdump_helpers.c#L265-L270) by renaming it with a richer file name and add potentially missing virtual memory areas to the dump.
2. This avoids having to deal with any configuration issues with the core dump processing program such as core dump truncation. This is a legitimate concern because, for example, `systemd-coredump` -- which has quickly become the most common core dump processing program -- [truncates 64-bit core dumps at 2GB](https://github.com/systemd/systemd/issues/22076) before v251.

However, these concerns have responses:

1. Renaming the core dump is cosmetic and unnecessary.
2. It seems to me that in the vast, vast majority of cases, the VMAs that the Linux kernel dumps are sufficient. The JVM [dynamically updates `coredump_filter`](https://github.com/eclipse-openj9/openj9/blob/openj9-0.35.0/runtime/vm/jvminit.c#L6834) to `0x7F`.
3. Properly configuring core dump processing programs is not so hard. Some of the most common:
    1. For `systemd-coredump` (e.g. `core_pattern=|/usr/lib/systemd/systemd-coredump`) before v251, update `/etc/systemd/coredump.conf` to increase `ProcessSizeMax` and `ExternalSizeMax` to avoid truncation and reload configuration with `systemctl daemon-reload`.
    2. For `apport` (e.g. `core_pattern=|/usr/share/apport/apport`), default settings should not truncate.
    3. For `abrt-hook-ccpp` (e.g. `core_pattern=|/usr/libexec/abrt-hook-ccpp`), update `/etc/abrt/abrt.conf` to set `MaxCrashReportsSize=0` and restart `abrtd`.
    4. For Dynatrace rdp (e.g. `core_pattern=|/opt/dynatrace/oneagent/agent/rdp`), it should pass along the core dump to the underlying core dump processing program as seen in `/opt/dynatrace/oneagent/agent/conf/original_core_pattern`.
4. Finding core dumps processed by core dump processing programs is not so hard:
    1. `systemd-coredump`: `/var/lib/systemd/coredump/`
    2. `apport`: `/var/crash/`
    3. `abrt-hook-ccpp`: `/var/spool/abrt`

In addition, it's very difficult for customers to justify changing `kernel.core_pattern` in cloud environments like OpenShift as the change [cannot be done at a container-level](https://github.com/containers/podman/issues/6528).

That is all a long-winded background to issues with the following JVM messages which I believe exacerbate the malpractice of disabling core dump processing programs since they are reported as warnings/errors:

> JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.10301.
> JVMDUMP012E Error in System dump: The core file created by child process with pid = 10301 was not found. Expected to find core file with name "/tmp/core.10301"

Staring with JVMDUMP012E first: in my opinion, I think additional logic should be added that if `core_pattern` starts with `|`, then, instead of reporting JVMDUMP012E, the JVM should report a new, informational message rather than an error message; for example (**emphasis added** on the text change):

> JVMDUMP___I The core file created by child process with pid = {0} was not found. **Review the manual for the core_pattern program {1} to find where the core dump is written and ensure the program does not truncate it.**

Regarding JVMPORT030W, in my opinion, it should be an informational message rather than a warning. However, I'm guessing that can't be changed in service. If so, could text be appended? For example (**emphasis added** on the text change):

> JVMPORT030W /proc/sys/kernel/core_pattern setting "{0}" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or {1}. **Review the manual for the core_pattern program to find where the core dump is written and ensure the program does not truncate it.**

If those changes sound reasonable, let me know and I can create a PR.

**Comment by shellberg** [comment]
Reasonable.  I think there is definitely scope to improve the informational content for those messages (and acknowledge the widespread use of post-processing services).

My first and immediate thought, however, is that the core dump file becomes written instead by whichever post-processing tool is configured (running as root?  They are not usually setuid processes, right?), and is not necessarily written to a directory/file that has the PID ownership/access of our original Java job.... That in turn could defeat any further post-processing activity attempted by our own Java job to complete the dump, _e.g._ shared data segments, _etc._
Still, the increasing use of such systems writing and managing core files for the system (rather than the owner of the task) potentially already means that our fix-up for the dump content is emasculated anyway...?

**Comment by kgibm** [comment]
> That in turn could defeat any further post-processing activity attempted by our own Java job to complete the dump, e.g. shared data segments, etc.

Right, but how often do we need shared data segments? Is it worth going against industry best practices and risking disk space exhaustion? If they're more commonly needed than I suspected (e.g. shared class cache investigations?), then maybe modifying `coredump_filter` is a better solution? Perhaps the extra VMAs that Java service needs are related to `file-backed private mappings` and/or `file-backed shared mappings` which are not dumped by default (see below)? If so, maybe a solution would be for the JVM to try to update `coredump_filter` before taking the dump? Here is the relevant section of the [manual on `coredump_filter`](https://www.kernel.org/doc/man-pages/online/pages/man5/core.5.html):

```
Controlling which mappings are written to the core dump
       Since kernel 2.6.23, the Linux-specific
       /proc/[pid]/coredump_filter file can be used to control which
       memory segments are written to the core dump file in the event
       that a core dump is performed for the process with the
       corresponding process ID.

       The value in the file is a bit mask of memory mapping types (see
       [mmap(2)](https://man7.org/linux/man-pages/man2/mmap.2.html)). 
       If a bit is set in the mask, then memory mappings of
       the corresponding type are dumped; otherwise they are not dumped.
       The bits in this file have the following meanings:

           bit 0  Dump anonymous private mappings.
           bit 1  Dump anonymous shared mappings.
           bit 2  Dump file-backed private mappings.
           bit 3  Dump file-backed shared mappings.
           bit 4 (since Linux 2.6.24)
                  Dump ELF headers.
           bit 5 (since Linux 2.6.28)
                  Dump private huge pages.
           bit 6 (since Linux 2.6.28)
                  Dump shared huge pages.
           bit 7 (since Linux 4.4)
                  Dump private DAX pages.
           bit 8 (since Linux 4.4)
                  Dump shared DAX pages.

       By default, the following bits are set: 0, 1, 4 (if the
       CONFIG_CORE_DUMP_DEFAULT_ELF_HEADERS kernel configuration option
       is enabled), and 5.  This default can be modified at boot time
       using the coredump_filter boot option.

       The value of this file is displayed in hexadecimal.  (The default
       value is thus displayed as 33.)
```

**Comment by pshipton** [comment]
@keithc-ca fyi

The shared memory segments are needed since ROM classes, AOT code, and other JIT optimization data is in the shared cache. Setting the coredump_filter to include private and shared mapping sounds reasonable.

**Comment by kgibm** [comment]
> The shared memory segments are needed since ROM classes, AOT code, and other JIT optimization data is in the shared cache.

What are ways to test the availability of this data in `jdmpview`? And what JVM features would I need to enable and/or exercise to populate such data? Are these all related to the shared class and AOT caches? When I have some time to create a patch for this issue, I'd like to compare core dumps produced through `systemd-coredump` before and after the patch.

**Comment by pshipton** [comment]
For Semeru, the shared cache is enabled by default, or you can enable it via -Xshareclasses.
Open the core file in jdmpview and run `!shrc` to see the list of commands. Running `!shrc stats` should be sufficient to indicate if the shared memory is present or not, but you could also run `!shrc allstats`.

Besides the `info` commands documented by `dmpview` (i.e. `info thread *`), some other things to try unrelated to the shared cache are commands shown by `!j9help`. Picking some that don't require parameters:
`!classloaderssummary`
`!dumpallregions`
`!dumpallsegments`
`!findallmodules`
`!gccheck`
`!nativememinfo`
`!ramclasssummary`
`!romclasssummary`
`!vmcheck`

**Comment by pshipton** [comment]
BTW, to create a core for experimentation to answer the previous question, I'm on rhel 8 using the default systemd-coredump, and the core captured into `/var/lib/systemd/coredump/` seems to contain all the needed segments to run all the queries I mentioned.

**Comment by pshipton** [comment]
FYI the JVM does the following to set the coredump_filter.
https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/jvminit.c#L6875-L6888

**Comment by kgibm** [comment]
> FYI the JVM does the following to set the coredump_filter. https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/jvminit.c#L6875-L6888

Ah nice! I didn't even think of checking if the JVM already does this since it has become such a widespread assumption that J9 core post-processing is needed. This suggests to me that all of the claims of lack of information in cores produced by a core-piping program are due to configuration issues with that program (e.g. the 2GB truncation of `systemd-coredump` < v251), rather than lack of J9 core post-processing.

So then back to the original question: would the following changes be reasonable?

1. Add a new `JVMDUMP___I` informational message to replace JVMDUMP012E if `core_pattern` starts with `|`
2. Append "Review the manual for the core_pattern program to find where the core dump is written and ensure the program does not truncate it." to `JVMPORT030W`

**Comment by keithc-ca** [comment]
FYI, on RHEL 8+, you can you `coredumpctl` to work with system dumps in the default configuration.

**Comment by pshipton** [comment]
The proposed changes are reasonable, pls create the PR for review.

**Comment by pshipton** [comment]
I've added the doc label to this, I'm assuming we also want to update the User Guide with the new recommendations. Please open an issue at https://github.com/eclipse-openj9/openj9-docs/issues/

**Comment by kgibm** [comment]
Opened doc issue https://github.com/eclipse-openj9/openj9-docs/issues/1033

**Comment by keithc-ca** [comment]
Is there anything left to be done for this, or should it be closed as completed?

**Comment by kgibm** [comment]
Doc is published: https://www.eclipse.org/openj9/docs/xdump/#piped-system-dumps

So it's done, thanks!
