### ISSUE TITLE
Path to openjdk reference repo doesn't work on Windows

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16433]
**Describe the bug**
I noticed the following when running a grinder on Windows (because Windows was quite a bit slower than other platforms).
```
15:32:44       [exec] git clone --depth 1 -q --reference-if-able C:\cygwin64\home\jenkins/openjdk_cache  https://github.com/ibmruntimes/openj9-openjdk-jdk19.git openjdk-jdk
15:32:44       [exec] info: Could not add alternate for 'C:cygwin64homejenkins/openjdk_cache': path 'C:cygwin64homejenkins/openjdk_cache' does not exist
```

**To Reproduce**
Run a grinder on the OpenJ9 jenkins on an openjdk test.

**Expected behavior**
The path should be specified such that the reference repo is resolved.

@AdamBrousseau

**Comment by pshipton** [comment]
Lan said: In test pipeline, we basically call ${HOME} : https://github.com/adoptium/aqa-tests/blob/master/get.sh#L506

**Comment by llxia** [comment]
[hyc Jenkins windows build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.jck_x86-64_windows/295/console) does not have this problem

```
00:57:44.115  git clone --depth 1 --reference-if-able /home/jenkins/openjdk_cache -b master https://github.com/eclipse-openj9/openj9.git
00:57:44.115  Cloning into 'openj9'...
```

**Comment by AdamBrousseau** [comment]
I think this is one of those weird env things.
Pipeline is shelling out to Ant which is exec-ing git?
The grinder link from Lan is not hitting the code path that Pete's description is talking about.
Pete's grinder is Ant exec git clone. Not shell out to git clone straight from pipeline.
Could be back to the JAVA_HOME problem again?

**Comment by llxia** [comment]
ic, the problem in the description happens in ant (build.xml), not in shell. I do see a similar problem in [hyc Jenkins](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_testList_1/231/consoleFull). 

The problem may be resolved by converting windows style path separators to unix style. I will run some tests.
