### ISSUE TITLE
JEP 437: Structured Concurrency (Second Incubator)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16437]
See https://openjdk.org/jeps/437

@tajila @fengxue-IS

**Comment by babsingh** [comment]
### Tests for structured concurrency

https://github.com/ibmruntimes/openj9-openjdk-jdk20/tree/openj9/test/jdk/jdk/incubator/concurrent/StructuredTaskScope

### Test Results

**Summary:**
```
jdk/incubator/concurrent/StructuredTaskScope/PreviewFeaturesNotEnabled.java         Passed. Execution successful
jdk/incubator/concurrent/StructuredTaskScope/StructuredTaskScopeTest.java#platform  Passed. Execution successful
jdk/incubator/concurrent/StructuredTaskScope/StructuredTaskScopeTest.java#virtual   Passed. Execution successful
jdk/incubator/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java          Failed. Compilation failed: Compilation failed
```

**`StructuredThreadDumpTest.java` fails** compilation because OpenJ9 does not support `HotSpotDiagnosticMXBean`:
```
/root/openj9-openjdk-jdk20/test/jdk/jdk/incubator/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java:44: error: cannot find symbol
import com.sun.management.HotSpotDiagnosticMXBean.ThreadDumpFormat;
                                                 ^
  symbol:   class ThreadDumpFormat
  location: interface HotSpotDiagnosticMXBean
/root/openj9-openjdk-jdk20/test/jdk/jdk/incubator/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java:150: error: cannot find symbol
                .dumpThreads(file.toString(), ThreadDumpFormat.JSON);
                                              ^
  symbol:   variable ThreadDumpFormat
  location: class StructuredThreadDumpTest
```

**Complete test output log:** [StructuredTaskScope.log](https://github.com/eclipse-openj9/openj9/files/10461557/StructuredTaskScope.log)

**Comment by babsingh** [comment]
Tests for Structured Concurrency (JEP437) pass with our existing virtual thread support. The one failing test cannot be supported since it is Hotspot specific. Based upon the test results, it looks like support for nested continuations is not required to support JEP437. fyi @fengxue-IS @tajila

**Comment by babsingh** [comment]
Moving to 20.02 since JEP 437 is an incubator.

**Comment by pshipton** [comment]
Work is completed for Java 20.
