### ISSUE TITLE
Show Semeru Open/Certified Edition in javacore & coredump

### ISSUE THREAD

**Issue by yathamravali** [eclipse-openj9/openj9#16449]
java -version output clearly shows the difference between open & certified as shown below, but Javacore just shows it as `IBM Semeru Runtime` for both open & certified editions.

Open edition:
```
./jdk-11.0.17+8/bin/java -version
openjdk version "11.0.17" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Linux amd64-64-Bit Compressed References 20221031_559 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8)
```
Certified edition:
```
./jdk-11.0.17+8/bin/java -version
java version "11.0.17" 2022-10-18
IBM Semeru Runtime Certified Edition 11.0.17.0 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Linux amd64-64-Bit Compressed References 20221031_559 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8)
```

Request: It would be helpful to provide a way to tell whether it is certified/ openJava from system core file and Javacore file.

**Comment by pshipton** [comment]
The java.runtime.name system property contains the name, i.e. "IBM Semeru Runtime Open Edition".

**Comment by pshipton** [comment]
The javacore includes
```
#if defined(J9PRODUCT_NAME)
	_OutputStream.writeCharacters("1CIPRODUCT     " J9PRODUCT_NAME "\n");
#endif /* defined(J9PRODUCT_NAME) */
```

The extensions (at least jdk11) set `#define J9PRODUCT_NAME            "@PRODUCT_NAME@"`

The edition is specified in the PRODUCT_SUFFIX. It should be simple to update the definition of J9PRODUCT_NAME to include it.

**Comment by pshipton** [comment]
The changes are merged.
