### ISSUE TITLE
Document updated CUDA requirements

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#16463]
See https://github.com/adoptium/infrastructure/issues/2818. If we can't get NVidia to restore access to the 9.0 toolkit, then we should document (e.g. in release notes) the requirement for a newer CUDA runtime version (e.g. 9.1 instead of 9.0).

**Comment by keithc-ca** [comment]
We may not need to do anything: the Windows playbook may be able to stay at version 9.0.

**Comment by pshipton** [comment]
If this is specific to Windows Server 2012, it's time to think about moving off this version considering it's out of support October 9, 2023.

**Comment by keithc-ca** [comment]
Now that https://github.com/eclipse/omr/pull/7088 is merged, the version of CUDA at build time no longer constrains the minimum version required at runtime: Closing this.
