### ISSUE TITLE
Windows builds failing - mkdir: cannot create directory '/cygdrive/f': No such file or directory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16489]
These are builds for 0.36 that should have occurred Sunday.,

https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_windows_Release/64 - [win2019x64-openj9-1](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-1)
https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_windows_Release/48/ - [win2019x64-openj9-3](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-3)

```
19:11:50  + mkdir -p /cygdrive/f/Users/jenkins/bootjdks/jdk17
19:11:50  mkdir: cannot create directory '/cygdrive/f': No such file or directory
```

@AdamBrousseau

**Comment by pshipton** [comment]
Tried another build, still failed, on [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_windows_Release/65/console

I'll remove the build label from all the win2019x64-openj9 machines and try again. The jdk8 builds work on the other win2019-x64 machines.

**Comment by pshipton** [comment]
Actually I don't trust them for running tests, I'll disable them.

**Comment by AdamBrousseau** [comment]
Does that stream have Violeta's windows change for defaults.yml?

**Comment by pshipton** [comment]
Good point, I've created https://github.com/eclipse-openj9/openj9/pull/16492 for you to review and merge.

**Comment by pshipton** [comment]
Machines back online.
