### ISSUE TITLE
J2IThunk serialization for JITServer AOT cache

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#16482]
The following summarizes my understanding of J2I thunks:

J2I thunks are created by the JIT to make the transition to interpreted code. They are snippets of code specialized for each method signature. Because there could be many signatures, the J2I thunks are created on demand when we know the signature of the callee.

Code for J2I thunks is allocated in the code cache, but the VM registers them (in a hashtable) to avoid duplicates. Thunks can be reused for any method that has a particular signature.

`TR_J9VMBase::getJ2IThunk(char *signatureChars, uint32_t signatureLength, TR::Compilation *comp)` is used to retrieve the code for an existing thunk. It calls a VM helper to do a hashtable lookup.
`TR_J9VMBase::setJ2IThunk()` is used to register a thunk with the VM.It calls a VM helper.

The codegen calls `setJ2IThunk()` in `buildIndirectDispatch()` but only if `getProperties().getNeedsThunksForIndirectCalls()` responds true.
The codegen first checks to see whether an appropriate thunk already exists and if not, creates one.
	`virtualThunk = fej9->setJ2IThunk(methodSymbol->getMethod(), generateVirtualIndirectThunk(callNode), comp());`

`generateVirtualIndirectThunk()` allocates code memory for the thunk and returns the thunk address, but before that we have two int32_t offsets. Actually, if `fej9->storeOffsetToArgumentsInVirtualIndirectThunks()` is true then we use heap memory and not code memory. This is done for JITServer and AOT because for JITServer we need to allocate the thunk at the client and for AOT we need to allocate the thunk in the SCC.

**How does JITServer handle thunks?**
Codegen allocates a temporary thunk using heap memory. `setJ2IThunk()` serializes the temporary thunk code and sends a message to the client. The client allocates the thunk using code memory and registers the thunk with the VM. The address of the thunk is returned to the server which memorizes it in `_registeredJ2IThunksMap` in the client session. `getJ2IThunk()` at the server always searches this map first.

**How does AOT handles thunks?**
AOT compilation allocates a temporary thunk using heap memory. See `generateVirtualIndirectThunk(callNode), comp());`
`setJ2IThunk()` calls  `persistThunk(signatureChars, signatureLength, (U_8*)thunkptr - 8 /* start of thunk */, *((U_32 *)((U_8*)thunkptr -8)) + 8 /* size of thunk */);`
which writes the thunk into SCC. During AOT load, the thunk is loaded from SCC, copied into code cache, the address of the VM helper is fixed-up,  the thunk is registerd with the VM and then we relocate the code that points to the newly allocated thunk. See `TR_RelocationRecordThunks::applyRelocation()`

**How does JITServer handles AOT code requiring thunks?**
AOT compilation allocates a temporary thunk using heap memory. See `generateVirtualIndirectThunk(callNode), comp());`
`TR_J9ServerVM::setJ2IThunk()` serializes the temporary thunk code and sends a message to the client.
The client calls the AOT version of `setJ2IThunk()` which persists the thunk into SCC through `persistThunk()`
The address of the thunk (which address? possible bug) is pased back to the server to be memorized in its map `registeredJ2IThunksMap`. Note that mappings for AOT are kept separate from mappings of non AOT.
During AOT load we copy the thunk's body and relocate like in the non-jitserver case.
	

For JITServer AOT cache we also have to keep the body of the J2I thunk that was generated during codegen.
During serialization, we also have to send the code of the thunk to the client.
The client, during deserialization, must persist the thunk's code into the SCC, must like a local AOT compilation would do.

**Comment by mpirvu** [comment]
Some ideas on how we can implement this:

The compilation object (at the server) needs to keep a list of allocated thunks. These thunks can be allocated with heap memory as we do today, but we just have to keep track of them (sizes as well).
When we create the CachedAOTMethod (in outOfProcessCompilationEnd() which calls cache->storeMethod()) we need to add all those snippets to the AOTSerializedMethod.
Currently, an AOTSerializedMethod has the following fields:
```
   const size_t _size;
   const uintptr_t _definingClassChainId;
   // Index in the array of methods of the defining class
   const uint32_t _index;
   const TR_Hotness _optLevel;
   // Represents the TR_AOTHeader of the client JVM that this method was originally compiled for
   const uintptr_t _aotHeaderId;
   // Number of serialization records and corresponding SCC offsets
   const size_t _numRecords;
   const size_t _codeSize;
   const size_t _dataSize;
   // Layout: SerializedSCCOffset offsets[_numRecords], uint8_t code[_codeSize], uint8_t data[_dataSize]
   uint8_t _varSizedData[];
```
We may need to add extra fields: `size_t _numThunks` `size_t _totalThunksSize` `uint8_t thunkCode[_totalThunksSize]`
I think that each thunk includes its size in the header, but if that is not the case, we need to add an array of offsets to the beginning of each thunk.
This implementation has the disadvantage of duplicating code for thunks. Two methods may require a thunk with the same signature and the code would be duplicated.

**Comment by AlexeyKhrabrov** [comment]
If duplication is a concern, the solution would be to introduce thunk IDs that serialized methods can refer to. Each unique thunk can be identified by its signature string. I suspect that local SCC does something similar. Do we have an idea of how large the thunks are (and how many per method) compared to AOT method bodies?

**Comment by mpirvu** [comment]
I ran AcmeAir with -Xaot:forceaot and looked at thunk allocations for AOT compilations (JITServer was not used).
There were 1667 different thunks that were allocated and the average size was 31 bytes.
If we didn't eliminate duplicates there would be 27167 thunks. This means an increase of about 790 KB

**Comment by mpirvu** [comment]
**Proposal of implementation:**
General idea: for each different thunk that may be created during an AOT compilation at the server we need to store the generated thunk code and send it back to the client to add it to its SCC. Leverage as much as possible the current AOT serialization/deserialization infrastructure.

Details:

Extend the `AOTSerializationRecord` to create a `ThunkSerializationRecord` which adds the signature of the thunk and the generated code
```
class ThunkSerializationRecord : public AOTSerializationRecord
{
   // _size and _idAndType are inherited
   const size_t _thunkSize;
   const size_t _signatureSize;
   //uint8_t _signatureData[]; // variable sized
   //uint8_t _thunkCode[];  // variable sized
};
```
Extend the `AOTCacheRecord` to create an `AOTCacheThunkRecord`
```
class AOTCacheThunkRecord : public AOTCacheRecord
{
   // _nextRecord inherited from AOTCacheRecord
   const ThunkSerializationRecord _data;
};
```
Create a map to hold all the different thunks and put the map into the `JITServerAOTCache`. The key for this map is the signature of the thunk
```
class JITServerAOTCache
{
   struct ThunkKey
      {
      bool operator==(const ThunkKey &k) const;
      struct Hash { size_t operator()(const ThunkKey &k) const noexcept; };

      const uint8_t *const _signature;
      const size_t _signatureLength;
      };
   static ThunkKey getRecordKey(const AOTCacheThunkRecord *record)
      { return { record->data().signature(), record->data().signatureLength() }; }
   ...
   PersistentUnorderedMap<ThunkKey, AOTCacheThunkRecord *, ThunkKey::Hash> _thunkMap;
   uintptr_t _nextThunkId;
   AOTCacheThunkRecord *_thunkHead;
   AOTCacheThunkRecord *_thunkTail;
   TR::Monitor *const _thunkMonitor;
   ...
};
```
During codegen, in `buildIndirectDispatch()`, the JIT checks to see if a thunk for the given signature already exists with fe()->getJ2IThunk(), and if not, it creates one:
```
         virtualThunk = fej9->getJ2IThunk(methodSymbol->getMethod(), comp());
         if (!virtualThunk)
            virtualThunk = fej9->setJ2IThunk(methodSymbol->getMethod(), generateVirtualIndirectThunk(callNode), comp());
```
We need to modify `getJ2IThunk()` to search our `_thunkMap` based on thunk signature. 
If not found, we need to change  `generateVirtualIndirectThunk()` to allocate an `AOTCacheThunkRecord` which will contain the code for the thunk. This newly allocated `AOTCacheThunkRecord` will be added to the `_thunkMap`.
A pointer to the `AOTCacheThunkRecord`, either existing or newly created, will be added to a set maintained by the compilation object.

At the end of the AOT compilation the code calls `cache->storeMethod()` to store the method into the AOT cache. 
The set of thunks that was added to the comp object needs to be added to the `_serializationRecords` list (maintained also by the comp object) with `comp->addSerializationRecord(const AOTCacheRecord *record, uintptr_t reloDataOffset)` with a reloDataOffset of 0. This way we treat thunk records like any serialization records. 
`storeMethod()` calls `CachedAOTMethod::create()` which computes the space needed, allocates persistent memory and then calls the constructor of `CachedAOTMethod`.
The `CachedAOTMethod` constructor goes through the list of records given as a parameter (`_serializationRecords` from compilation object) and constructs a `SerializedSCCOffset` in each of the array entries for serialization records (this is really not needed for thunks). It also adds an array of pointers to records that are needed by this AOT body, so now this array will include thunks as well.

When the server needs to send an AOT body from the AOT cache, it will call `serveCachedAOTMethod()`. This one
sends the `SerializedAOTMethod` part of the `CachedAOTMethod`, but also a vector of serialization records.
This vector is built by going through the array of records pointers at the end of `CachedAOTMethod`. We filter out
the records that have a corresponding match in knownIds and also we filter out the duplicate records based on pointer comparison. So, the result will include some `ThunkSerializationRecords`.

Deserialization needs to store the thunks into the SCC.
In `remoteCompile()` the client receives the result of the compilation result: `MessageType::AOTCache_serializedAOTMethod` and then calls `deserializer->deserialize(method, records, compiler, usesSVM)`. In here we go over the vector of records and call `cacheRecord()` on them.
`JITServerAOTDeserializer::cacheRecord(const AOTSerializationRecord *record, TR::Compilation *comp, bool &isNew, bool &wasReset)` has a switch inside for each type of serialization record so we need to add another case statement for `ThunkSerializationRecord` and we need to write a specialized `cacheRecord()` method that works on `ThunkSerializationRecords` 
`bool JITServerAOTDeserializer::cacheRecord(const ThunkSerializationRecord *record, TR::Compilation *comp, bool &isNew, bool &wasReset)`
This new routine needs to call `TR_J9SharedCacheVM::setJ2IThunk(char *signatureChars, uint32_t signatureLength, void *thunkptr, TR::Compilation *comp)` with an AOT frontend, to store the thunk into SCC. I am not sure whether we need to keep additional information around.

**Comment by mpirvu** [comment]
@cjjdespres maybe you can implement a solution for the J2I thunk support in JITServer. Thanks

**Comment by cjjdespres** [comment]
Just so I'm sure I understand the problem correctly - the JITServer creates thunks during code generation. These thunks are properly registered on a per-client basis and sent to the clients that requested the compilation. Those clients deserialize the thunks and store them in their SCC. However, the JITServer AOT cache does not store the thunks that are generated for particular cached methods, so AOT code relying on these thunks that is sent to the client may (will?) experience a thunk relocation error. The above design corrects this deficiency.

One small question - when you said

> If not found, we need to change generateVirtualIndirectThunk() to allocate an AOTCacheThunkRecord which will contain the code for the thunk.

does that mean that we only care about the thunks generated by that particular method, and not thunks generated by any of the other methods that are called inside `fej9->setJ2IThunk` invocations? (Also, that `generateVirtualIndirectThunk` method lives in `AMD64PrivateLinkage.cpp`, right?) Otherwise I would have assumed that `TR_J9ServerVM::setJ2IThunk` itself would take care of caching the thunk.

**Comment by mpirvu** [comment]
I don't understand this "thunks generated by any of the other methods that are called inside fej9->setJ2IThunk invocations"

J2I thunks are pieces of generated code and therefore they are created during JIT compilation, but they are separate entities from the method bodies (because multiple method bodies can share the same thunk).
The codegen must make sure that an appropriate J2I thunk exist when a virtual call is present. First it checks whether an appropriate J2I already exists (created by a previous compilation), This is done with `fej9->getJ2IThunk()`. For an AOT compilation at JITServer, this frontend query first checks the thunkmap stored in the client session. If the thunk map has an entry, it means this client already has an appropriate thunk already registered with the VM or in it's SCC (however, if we want to store this AOT method into the AOT cache we still have to make sure that an appropriate serialized thunk already exists in the JITServer AOT cache where this method will be stored). If the thunkmap from the client session returns NULL, we don't know if the client has a corresponding thunk so getJ2IThunk() sends a message to the client and retrieves the possible thunk. If there is a thunk at the client, this is cached into the thunkmap for the client session (again, I think that we must ensure that such a thunk exists also in the JITServer AOT cache). If the client says it does not have an appropriate J2I thunk, the server must generate one with `generateVirtualIndirectThunk()` . Every time such a thunk is generated we must also add it to the JITServer AOT cache.  Maybe we can transfer that responsibility to `fej9->setJ2IThunk()` which seems to always be called immediately after the thunk is generated. In `setJ2IThunk()` we need to be able to test whether we are in an AOT compilation that will be stored in JITServer AOT cache. This information may be available in the comp object.

**Comment by cjjdespres** [comment]
There are other methods like `TR::PPCCallSnippet::generateVIThunk` or `TR::S390J9CallSnippet::generateVIThunk` that seemed to generate these thunks as well, based on their name and the fact that their output is also passed to `fej9->setJ2IThunk()`. I wanted to make sure that we only cared about the `generateVirtualIndirectThunk()` ones.

**Comment by mpirvu** [comment]
We care about all 3 platforms where we support JITServer, so P and Z must be taken into consideration as well.
