### ISSUE TITLE
Build errors with Xcode 14.x

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#16517]
Building OpenJ9 for macOS with the latest Xcode (14.x) fails with the following errors for `sprintf()`:

```
[  0%] Building CXX object runtime/omr/tools/tracegen/CMakeFiles/trace.dir/CFileWriter.cpp.o
/Users/openj9/openj9-openjdk-jdk17/omr/third_party/pugixml-1.5/pugixml.cpp:3989:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
                sprintf(buf, "%d", value);

...

[  1%] Building CXX object runtime/omr/ddr/lib/ddr-ir/CMakeFiles/omr_ddr_ir.dir/Members.cpp.o
/Users/openj9/openj9-openjdk-jdk17/omr/tools/tracegen/TraceHeaderWriter.cpp:238:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
                sprintf(testMacro, testMacroTemplate, name, module, id);
```

The options `--disable-warnings-as-errors` and `--disable-warnings-as-errors-openj9` do not work for these errors.

Xcode 13.4.1 (MacOSX12.3.sdk) can build OpenJ9.
It seems `sprintf()` was deprecated by MacOSX13.x.sdk in Xcode 14.x.

From stdio.h of MacOSX13.1.sdk:
```
#if !defined(_POSIX_C_SOURCE)
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
#endif
```

I tried it on M1 Mac with macOS Monterey 12.6.2.
I guess Intel Mac should have the same problem.

**Comment by knn-k** [comment]
Compiling a simple program like this does not show the error:

```
#include <stdio.h>

int main(int argc, char **argv)
{
	char buf[16];
	sprintf(buf, "%d", argc);
	return 0;
}

% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
% clang -c -Werror test.c
(no errors)
```

Running the C preprocessor shows the symbol `_POSIX_C_SOURCE` is not defined, however.  I need to find out how the `__deprecated__` attribute generates the error during OpenJ9 build.

```
% clang -E test.c
...
__attribute__((__deprecated__("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")))

int sprintf(char * restrict, const char * restrict, ...) __attribute__((__format__ (__printf__, 2, 3)));
...
```

**Comment by pshipton** [comment]
Why not just change the code to use snprintf()?

**Comment by knn-k** [comment]
Because there are too many of them.

**Comment by knn-k** [comment]
I can see the warning for `sprintf()` by changing the file name from `.c` to `.cpp` as shown below.  The option `-Wno-deprecated-declarations` suppresses it.

```
% clang -c test.cpp
test.cpp:5:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        return sprintf(buf, "%d", n);

% clang -Wno-deprecated-declarations -c test.cpp
(no warnings)
```

**Comment by knn-k** [comment]
Adding the following line to omr/cmake/modules/platform/os/osx.cmake is a workaround for the time being.

```
list(APPEND OMR_PLATFORM_CXX_COMPILE_OPTIONS -Wno-deprecated-declarations)
```

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/6862 as a partial fix.

**Comment by knn-k** [comment]
I also opened PR #16550 for a file for a native test.

For omr/third_party/pugixml-1.5/pugixml.cpp, I think we need to consider updating the third party code to the latest version, pugixml-1.13, which mentions Xcode 14.
See https://github.com/zeux/pugixml/blob/95683943bba726729079886d0967112a60fa71aa/src/pugixml.cpp#L146-L147

**Comment by knn-k** [comment]
pugixml 1.5 in OMR contains a change for EBCDIC.  You cannot just upgrade pugixml to the latest version.
https://github.com/eclipse/omr/blob/master/third_party/pugixml-1.5/pugixml.cpp

**Comment by knn-k** [comment]
I opened PR https://github.com/eclipse/omr/pull/6881 for fixing pugixml.

**Comment by knn-k** [comment]
My PRs in OMR have been merged, and I can build OpenJ9 with Xcode 14.2 now.

**Comment by knn-k** [comment]
Use of `snprintf()` broke the build for z/OS on a V2R1 machine.
Reopening this issue.

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/6907.  It should work with the compiler for z/OS.

**Comment by knn-k** [comment]
Closing this issue now.
See https://github.com/eclipse/omr/issues/6863 for non-OpenJ9 failures with `sprintf()` in OMR.
