### ISSUE TITLE
OpenJDK java/foreign/TestResourceScope.java AssertionError: expected [4950] but found [4894]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16551]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_linux_Nightly/391
jdk_foreign_1
java/foreign/TestResourceScope.java

Related to https://github.com/eclipse-openj9/openj9/issues/13234
```
23:09:57  test TestResourceScope.testSharedMultiThread(TestResourceScope$$Lambda$85/0x000000003c235a60@4bdb6924): failure
23:09:57  java.lang.AssertionError: expected [4950] but found [4894]
23:09:57  	at org.testng.Assert.fail(Assert.java:99)
23:09:57  	at org.testng.Assert.failNotEquals(Assert.java:1037)
23:09:57  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
23:09:57  	at org.testng.Assert.assertEquals(Assert.java:122)
23:09:57  	at org.testng.Assert.assertEquals(Assert.java:907)
23:09:57  	at org.testng.Assert.assertEquals(Assert.java:917)
23:09:57  	at TestResourceScope.testSharedMultiThread(TestResourceScope.java:149)
```

@ChengJin01 @tajila @babsingh fyi

**Comment by ChengJin01** [comment]
@babsingh, should the test suite be excluded for now given the issue with https://github.com/eclipse-openj9/openj9/issues/13234 still exists in JDK17 (Probably it still exists `TestMemorySession.java` in JDK19) ?

**Comment by babsingh** [comment]
- The test was enabled recently via https://github.com/adoptium/aqa-tests/pull/4226.
- In JDK17, `TestResourceScope` should stay disabled since the issue was in the Java/test code which is common between OpenJ9 and the RI.
- In JDK19, the common implementation changed and the failure is no longer seen. So, `TestMemorySession` does need to be excluded.

**Comment by babsingh** [comment]
@ChengJin01 Correction to above comment; there was a typo: `TestMemorySession does NOT need to be excluded.` It should stay enabled.

**Comment by ChengJin01** [comment]
The PR is created at https://github.com/adoptium/aqa-tests/pull/4241 to exclude the test suite.
