### ISSUE TITLE
[Jtreg/FFI] Disable FFI test suites in Jtreg test for JDK20

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#16565]
Given the changes at https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/531 with updated APIs for JEP434 (https://github.com/eclipse-openj9/openj9/issues/16329) will be merged to JDK20 only for compilation, in which case all FFI specific test suites in JDK20 at https://github.com/ibmruntimes/openj9-openjdk-jdk20/tree/openj9/test/jdk/java/foreign must be disabled via https://github.com/adoptium/aqa-tests for the moment till we update everything related to JEP434 in OpenJDK & OpenJ9.

**Comment by ChengJin01** [comment]
FYI: @tajila, @pshipton, @llxia

**Comment by ChengJin01** [comment]
PR has been created at https://github.com/adoptium/aqa-tests/pull/4251 to exclude all FFI specific test suites.

**Comment by ChengJin01** [comment]
Close this issue as https://github.com/adoptium/aqa-tests/pull/4251 was merged.

**Comment by pshipton** [comment]
Unless I misunderstand, this should stay open in the jdk20 milestone plan as a reminder to un-exclude the tests later.

**Comment by ChengJin01** [comment]
The failing FFI related test case (in `java/lang/Thread/jni/AttachCurrentThread/AttachTest.java`) captured at https://github.com/eclipse-openj9/openj9/issues/16656 was excluded via https://github.com/adoptium/aqa-tests/pull/4318. So we will enable them all after we finished updated the code in OpenJDK & OpenJ9 against the latest APIs in JDK20.

**Comment by ChengJin01** [comment]
> @ChengJin01 were these tests re-enabled?

Not yet due to the issue with the heap segment in upcall at https://github.com/eclipse-openj9/openj9/issues/16761. Will double-check everything in FFI Jtreg test suite to see what else is left assuming this is no platform dependent issue.

**Comment by ChengJin01** [comment]
There was a Jtreg test failure detected in JDK17/20 on some of platforms by https://github.com/eclipse-openj9/openj9/issues/16761 which was caused by the null check on the pointer segment (which needs to be removed). Currently I am verifying my fix at https://github.com/ChengJin01/openj9/commit/84e15f2068116afb1218d8fba5a13ccce221a104 to ensure it works good on the failing platforms.

**Comment by tajila** [comment]
@ChengJin01 Any update on this?

**Comment by ChengJin01** [comment]
Close this issue as the FFI test suites in JDK20 has been enabled via https://github.com/adoptium/aqa-tests/pull/4591.
