### ISSUE TITLE
cmdLineTester_hangTest_0_FAILED Testing: hang FAILED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16629]
Failure link
------------

From [an 0.36.1 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_aarch64_linux_testList_1/224/)(`cent7-aarch64-4`):
```
java version "11.0.18" 2023-01-17
IBM Semeru Runtime Certified Edition 11.0.18.1-rc1 (build 11.0.18+10)
Eclipse OpenJ9 VM 11.0.18.1-rc1 (build v0.36.1-release-0592661e4, JRE 11 Linux aarch64-64-Bit Compressed References 20230127_231 (JIT enabled, AOT enabled)
OpenJ9   - 0592661e4
OMR      - f491bbf6f
JCL      - 90e1a4e204 based on jdk-11.0.18+10)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=cmdLineTester_hangTest_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F231%2Fibm-semeru-certified-debugimage_aarch64_linux_11.0.18.1-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F231%2Fibm-semeru-certified-jre_aarch64_linux_11.0.18.1-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F231%2Fibm-semeru-certified-testimage_aarch64_linux_11.0.18.1-rc1.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9-IBM%2F231%2Fibm-semeru-certified-jdk_aarch64_linux_11.0.18.1-rc1.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.6-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.36.0-release&amp;OPENJ9_BRANCH=v0.36.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=v0.9.6-release&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.36.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=287&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-01-27T22:57:07.966Z] variation: NoOptions
[2023-01-27T22:57:07.966Z] JVM_OPTIONS:  

[2023-01-27T22:57:29.015Z] Testing: hang
[2023-01-27T22:57:29.015Z] Test start time: 2023/01/27 17:57:28 Eastern Standard Time
[2023-01-27T22:57:29.015Z] Running command: cat output.txt
[2023-01-27T22:57:29.015Z] Time spent starting: 16 milliseconds
[2023-01-27T22:57:29.015Z] Time spent executing: 29 milliseconds
[2023-01-27T22:57:29.015Z] Test result: FAILED
[2023-01-27T22:57:29.015Z] Output from test:
[2023-01-27T22:57:29.015Z] >> Success condition was not found: [Output match: Exiting ...]
[2023-01-27T22:57:29.015Z] >> Failure condition was not found: [Output match: Segmentation fault]
[2023-01-27T22:57:29.015Z] 
[2023-01-27T22:57:29.015Z] 
[2023-01-27T22:57:29.015Z] ---TEST RESULTS---
[2023-01-27T22:57:29.015Z] Number of PASSED tests: 0 out of 1
[2023-01-27T22:57:29.015Z] Number of FAILED tests: 1 out of 1
[2023-01-27T22:57:29.015Z] 
[2023-01-27T22:57:29.015Z] ---SUMMARY OF FAILED TESTS---
[2023-01-27T22:57:29.015Z] hang
[2023-01-27T22:57:29.015Z] -----------------------------
[2023-01-27T22:57:29.015Z] 
[2023-01-27T22:57:29.015Z] -----------------------------------
[2023-01-27T22:57:29.015Z] cmdLineTester_hangTest_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/30769/)

**Comment by pshipton** [comment]
Grinder passed

**Comment by JasonFengJ9** [comment]
Dup of https://github.com/eclipse-openj9/openj9/issues/16899
