### ISSUE TITLE
Stop maintaining a last-modified year in copyright notices

### ISSUE THREAD

**Issue by jdmpapin** [eclipse-openj9/openj9#16669]
(This issue is the same as eclipse/omr#6879 but as it applies to OpenJ9.)

All of our source files start with a copyright notice containing two years, like the following:

```Copyright (c) 2000, 2019 IBM Corp. and others```

The first year tells us when the file contents were first written, and the second tells us when they were last modified.

Because the copyright notices are in this form, the second year needs to be updated the first time each file is modified in a given year. These updates are a widespread paper cut that affect many contributions, as contributors generally need to manually carry them out. Furthermore, committers need to ensure that the year is updated appropriately, and remembering to do so is so error prone that we have had to develop an automated check that runs in each PR. When the check fails, before merging we have to wait for (roughly speaking) a round trip through two humans. Sometimes it can be combined with another round trip that was necessary anyway, i.e. when review has found problems that need to be addressed, but sometimes it can't be. Finally, setting aside raw efficiency, some (many?) of us find dealing with these updates to be a hassle. It's annoying to have to appease a failing copyright check.

Recently there have been [rumblings](https://hynek.me/til/copyright-years/) online about the (lack of) necessity of updating copyright years in this way for open source projects, which prompted me to look into why we do this. It turns out that maintaining the last-modified year was a requirement from IBM (my current employer) at the time of open-sourcing. However, IBM has since dropped that requirement, so it's simply no longer necessary.

As such, I propose changing our copyright notices to the following format (which is acceptable to IBM):

```Copyright IBM Corp. and others <initial-year>```

For instance, the example copyright notice from above would become:

```Copyright IBM Corp. and others 2000```

By removing the last-modified year, it no longer needs to be maintained, and we can all save a little bit of time and be a little bit less annoyed.

I would be happy to personally carry out this change. I'd like to update all of the files at once so that we aren't still left with the problem of making sure that they are updated piecemeal as other changes flow into them. The only disruption would be some (extremely easy to resolve) merge conflicts in in-flight changes that already include updates to the year in the copyright notice.

Any objections?

**Comment by DanHeidinga** [comment]
@jdmpapin While it's great that IBM has dropped the requirement, the more relevant entity is the Eclipse Foundation.  Do you know what their current requirements are around copyright years?

**Comment by jdmpapin** [comment]
I'm not sure that I agree that the Eclipse Foundation is more relevant. It doesn't own the copyright of which these notices are notifying the reader. Regardless, it [mainly suggests copyright notices with only a creation year](https://www.eclipse.org/projects/handbook/#ip-copyright-headers), with an additional last-modified year mentioned as an option.

**Comment by keithc-ca** [comment]
> IBM has since dropped that requirement

Please share a link that supports this claim.

**Comment by mstoodle** [comment]
Note that EF does not own the copyright: https://www.eclipse.org/legal/legalfaq.php#h.skv48lga3op6 . My understanding is that it is up to the respective copyright holders (in other words, our contributors). I've included below the same text I posted to the Eclipse OMR issue on the same topic. We don't have to use the same date I mentioned below if others prefer a different date.

I confess that this feels like a code hygiene issue to me (and we have so many of those), but if 1) it's something that doesn't need to be done and 2) the second date provides no inherent value above capturing the original copyright, then I would support removing the second copyright date from the message. But that second one is sort of up to all the contributors to assess even though IBM has provided the bulk of contributions.

This also feels like a question we could get mired in, though, so I hope it's fairly clear cut across our community, or else I will quickly switch my position to "leave it the way it is and move on".

Since the urgency is (relatively) low and I want to give as many contributors as possible a chance to see this issue and comment, I suggest we set a deadline of March 1, 2023 to make a decision on this proposal.

**Comment by jdmpapin** [comment]
> > IBM has since dropped that requirement
> 
> Please share a link that supports this claim.

Please see [my response to this](https://github.com/eclipse/omr/issues/6879#issuecomment-1424959513) in eclipse/omr#6879.

By the way, I don't think that in general we need to duplicate the entire discussion. To future commenters, if your comment applies equally to both OMR and OpenJ9, I'd ask you to please leave it in the OMR issue only. We can use *this* (OpenJ9) issue to point out important differences that are specific to OpenJ9 (if there are any), and we can follow the conclusion of the OMR discussion unless there is some OpenJ9-specific reason not to do so.

**Comment by DanHeidinga** [comment]
I'm fine with the March 1, 2023 deadline and have no objection to the proposal based on reading the EF policy in @jdmpapin's post which states that only an initial year is required.

Will this be changed in a single commit across the code base?  If it's done in a single commit, we should use Github's "ignore commit in the blame view" feature [0] to avoid having it pollute the git blame.

[0] https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by jdmpapin** [comment]
Yes, I intend to update all files in one commit. In most files only one line should be modified though, so I'm not sure there's much benefit to ignoring it in blame

**Comment by jdmpapin** [comment]
This change has now been done in OMR, and we're well past March 1 with no objections. Unless there is further input here very soon, I'll carry out the same thing in OpenJ9.

**Comment by DanHeidinga** [comment]
@jdmpapin can you coordinate this with @AdamBrousseau ?  OpenJ9 has the copyright PR check that I assume will start failing once this is done

**Comment by jdmpapin** [comment]
Yes, that's what I did in OMR. The copyright check was turned off before I opened my PR.
