### ISSUE TITLE
Xcheck:jni does not validate NULL value of JNIEnv

### ISSUE THREAD

**Issue by sjmini** [eclipse-openj9/openj9#16665]
Java -version output
------------------
openjdk version "11.0.16.1" 2022-08-12
IBM Semeru Runtime Open Edition 11.0.16.1 (build 11.0.16.1+1)
Eclipse OpenJ9 VM 11.0.16.1 (build openj9-0.33.1, JRE 11 Linux amd64-64-Bit Compressed References 20220818_500 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - 84b84a0409 based on jdk-11.0.16.1+1)

Summary of problem
------------------
OpenJ9 cannot validate the use of NULL for JNIEnv even Xcheck:jni is enabled.
e.g., GetBooleanField(**NULL**, jobject, jfieldID)

According to the JNI specification, the first argument of GetBooleanField  must not be NULL.
Passing a NULL as a first argument of GetBooleanField lead to a segmentation fault on OpenJ9.
However, Hotspot handles this situation correctly and returns an error message.

```
Testing_EAN_JNI: FATAL ERROR in native method: Using JNIEnv in the wrong thread
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@ehrenjulzert please take a look at this.

The JNI check wrappers are in `openj9/runtime/jnichk/jnicwrappers.c`. I suspect this is a general problem and not just with `GetBooleanField`

**Comment by gacholio** [comment]
The actual check should be that the JNIEnv is the current thread (which will cover the NULL case implicitly).

**Comment by ehrenjulzert** [comment]
Yup this looks like it's a general problem. There is already a `jniCheckArgs` function so can put the check in there. What I'm unsure of is how to check if the JNIEnv is the current thread? I can't find any function/field to check that anywhere.

**Comment by tajila** [comment]
you can use `currentVMThread(J9JavaVM *vm)` to find the current thread

**Comment by gacholio** [comment]
I suggest that after fetching the current thread from the function call, check it for NULL (which means the thread is not attached to the VM) and issue a different error.

**Comment by ehrenjulzert** [comment]
I've run into a bit of an issue: I would like to throw an error by calling `jniCheckFatalErrorNLS` but unfortunately `jniCheckFatalErrorNLS` also takes a `JNIEnv*` argument and will crash if it is null. I would just create a new `JNIEnv*` out of the current thread but I see no way of doing that since the only object passed into the check wrappers that has a reference to the VM is `env` (which we already know is null). Is there a different function I can use to throw the error that doesn't require the VM or current thread?

**Comment by gacholio** [comment]
I hadn't thought of that - the easiest thing to do is probably to cache a copy of the J9JavaVM in a global variable when JNI check starts. Use of globals is frowned upon in our codebase,  but I think we can justify it in this case.

The various error functions can use the cached VM to get to the port library. Any other uses of the `env` parameter other than for printing purposes would need to be NULL-checked.

**Comment by ehrenjulzert** [comment]
Okay, I'll try putting a global in `jnicmem.c` and initialize it in the `jniCheckMemoryInit` function (assuming that is the correct place to initialize it).

**Comment by gacholio** [comment]
Sounds right. You will need to replace all VM fetches from the env with the global (unless the user is provably from a non-NULL env).
