### ISSUE TITLE
[JDK20] Thread.findScopedValueBindings to support JEP 429?

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#16677]
For `Thread.findScopedValueBindings`, 
- [step 1] evaluate if an implementation is required to support https://github.com/eclipse-openj9/openj9/issues/16439;
- [step 2] if true, derive its implementation from the RI and implement it for OpenJ9.

**Comment by babsingh** [comment]
Pseudo code implementation:
```
walkStackFrames:
   for each frame:
      if ((methodName is "runWith")
      and (methodClass is either a
              jdk.incubator.concurrent.ScopedValue$Carrier OR
              java.lang.VirtualThread OR
              java.lang.Thread)
      ) {
         Check if the first parameter is an jdk.incubator.concurrent.ScopedValue$Snapshot
         Then, return the first parameter as a local ref;
      )
```

**Comment by thallium** [comment]
@gacholio FYI

**Comment by babsingh** [comment]
fyi @gacholio

**Comment by thallium** [comment]
Currently we don't have a test to validate the implementation. Maybe we should put an assertion in the implementation so we will know when this is actually called.

**Comment by babsingh** [comment]
Closing. An assertion has been added in https://github.com/eclipse-openj9/openj9/pull/17451. `Thread.findScopedValueBindings` is  is unused since there is no API or test that invokes this method in OpenJ9. If the assertion ever triggers, this issue should be re-opened and the draft implementation in https://github.com/eclipse-openj9/openj9/pull/17402 should be completed and merged.

**Comment by babsingh** [comment]
@0xdaryl The three `runWith` methods, where we want to retrieve the first argument while stack walking, are:
- [jdk.incubator.concurrent.ScopedValue$Carrier.runWith](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/78015256cbd4993cd51f522a6b4b5786a75dc00e/src/java.base/share/classes/java/lang/ScopedValue.java#L472)
- [java.lang.VirtualThread.runWith](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/78015256cbd4993cd51f522a6b4b5786a75dc00e/src/java.base/share/classes/java/lang/VirtualThread.java#L345)
- [java.lang.Thread.runWith](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/78015256cbd4993cd51f522a6b4b5786a75dc00e/src/java.base/share/classes/java/lang/Thread.java#L1606C16-L1606C16)

**Issue:** JIT inlining will prevent us to find the first argument during the stack walk since the O-slots don't retain their order when the methods are inlined.

https://github.com/eclipse-openj9/openj9/pull/17402 contains the implementation of the behaviour described in https://github.com/eclipse-openj9/openj9/issues/16677#issuecomment-1520187982.

**Comment by gacholio** [comment]
For the record, you can't reliably retrieve the first argument for any compiled method, inlined or not.
