### ISSUE TITLE
JVMTI SetGetThreadLocalStorageStressTest failed with unexpected value in storage.

### ISSUE THREAD

**Issue by dipak-bagadiya** [eclipse-openj9/openj9#16687]
### Issue
The JVMTI `SetGetThreadLocalStorageStressTest` test fails with an incorrect value in storage.

### Test CMD
```
make test TEST="jtreg:test/hotspot/jtreg/serviceability/jvmti/stress/ThreadLocalStorage/SetGetThreadLocalStorageStressTest" JTREG="JAVA_OPTIONS=--enable-preview -Dvm.continuations=true;VERBOSE=all"
```

### Test Output
```
Unexpected value in storage storage=0x7f338c01ebb0, the self_pointer=0x7f338c01ebb0, data (owner thread name): JIT Compilation Thread-002 Suspended
Thread: 0x7f338c01e930, name: JIT Compilation Thread-002, state(5):  ALIVE RUNNABLE, attrs: kernel daemon
Exiting ...
STDERR:

Fatal error: Incorrect value in storage.
```

**Comment by thallium** [comment]
Currently the test will cause deadlock on liveVirtualThreadMutex, and will likely to be fixed by #16855.

**Comment by babsingh** [comment]
@fengxue-IS @thallium https://github.com/eclipse-openj9/openj9/pull/16855 was merged. Can you confirm if this test is fixed?

**Comment by thallium** [comment]
@babsingh Yes it passes now.

**Comment by babsingh** [comment]
Closing as per https://github.com/eclipse-openj9/openj9/issues/16687#issuecomment-1505652334.
