### ISSUE TITLE
ThreadMxBean:getThreadAllocatedBytes(long) not available with ppc64le IBM Semeru v11

### ISSUE THREAD

**Issue by sahityajain123** [eclipse-openj9/openj9#16694]
Java -version output
--------------------

Output from `java -version`.
```
[root@tz-205401-bastion ~]# java -version
java version "11.0.17" 2022-10-18
IBM Semeru Runtime Certified Edition 11.0.17.0 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Linux ppc64le-64-Bit Compressed References 20221031_427 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - 2767d3a0b2 based on jdk-11.0.17+8)
[root@tz-205401-bastion ~]#
```

JAVA rpm can be downloaded from here: https://github.com/ibmruntimes/semeru11-certified-binaries/releases/download/jdk-11.0.17%2B8_openj9-0.35.0/ibm-semeru-certified-11-jdk-11.0.17.0-1.ppc64le.rpm

Summary of problem
------------------
I have been working on getting an ISV application (Open-source version) running on ppc64le. The source links are located here: https://hub.alfresco.com/t5/alfresco-content-services-blog/building-alfresco-docker-images-from-source-code/ba-p/311375
When trying to build the component called "base-repo" with mvn install,  gives an error with the IBM Semeru v11.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project alfresco-repository: Compilation failure
[ERROR] /root/alfresco-community-repo/repository/src/main/java/org/alfresco/repo/jscript/AlfrescoScriptThreadMxBeanWrapper.java:[51,73] cannot find symbol
[ERROR]   symbol:   method getThreadAllocatedBytes(long)
```
It looks like Semeru/OpenJ9 didn’t implement this symbol currently. I did find the same reference in one of the issues, still open,
https://github.com/eclipse-openj9/openj9/issues/14054#issuecomment-988290220

Would like to know, if this symbol can be included as part of Semeru/OpenJ9. Also, if it can be implemented, when can we expect a new build or a supported maintenance release, so that I can continue with my test.

Do let me know if you need more details, I will be able to provide the same.

**Comment by pshipton** [comment]
You can try the following test build https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_ppc64le_linux_Personal/444/OpenJ9-JDK11-ppc64le_linux-20230209-102156.tar.gz
