### ISSUE TITLE
jdk19 OpenJDK java/util/concurrent/ExecutorService/CloseTest.java

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16762]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_ppc64_aix_Nightly/115
jdk_util_0
java/util/concurrent/ExecutorService/CloseTest.java
```
06:03:36  test CloseTest.testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@8ce56193): failure
06:03:36  java.lang.AssertionError: expected [true] but found [false]
06:03:36  	at org.testng.Assert.fail(Assert.java:99)
06:03:36  	at org.testng.Assert.failNotEquals(Assert.java:1037)
06:03:36  	at org.testng.Assert.assertTrue(Assert.java:45)
06:03:36  	at org.testng.Assert.assertTrue(Assert.java:55)
06:03:36  	at CloseTest.testShutdownBeforeClose(CloseTest.java:111)
```

**Comment by tajila** [comment]
@fengxue-IS Please take a look. Failure like related to Vthreads

**Comment by fengxue-IS** [comment]
[50x Grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/31241/), didn't reproduce the failure. 
looking at the stacktrace of the failure `testShutdownBeforeClose(java.util.concurrent.ForkJoinPool@8ce56193)`
```java
    @DataProvider(name = "executors")
    public Object[][] executors() {
        var defaultThreadFactory = Executors.defaultThreadFactory();
        var virtualThreadFactory = Thread.ofVirtual().factory();
        return new Object[][] {
            // ensures that default close method is tested
            { new DelegatingExecutorService(Executors.newCachedThreadPool()), },

            // implementations that may override close
            { new ForkJoinPool(), },
            { Executors.newFixedThreadPool(1), },
            { Executors.newCachedThreadPool(), },
            { Executors.newThreadPerTaskExecutor(defaultThreadFactory), },
            { Executors.newThreadPerTaskExecutor(virtualThreadFactory), },
```
This failure is with use of ForkJoinPool and isn't related to VThreads.
After examining the code call path, all of the methods called is park of OpenJDK JCL, I have not seen any OpenJ9 specific code within ForkJoinPool operation.
Will launch a larger grinder to reproduce failure.

**Comment by DanHeidinga** [comment]
Moving to JDK20 due to not being reproducible

**Comment by fengxue-IS** [comment]
Another [200x grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/31244/) still didn't reproduce the failure.

**Comment by fengxue-IS** [comment]
[30X jdk_util_0 Grinder(https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/31518/) still unable to reproduce.

**Comment by pshipton** [comment]
Closing since it's not seen again.
