### ISSUE TITLE
JDK21 JCL_Test_0_FAILED Cancelling nested steps due to timeout

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16779]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK_testList_1/124/consoleFull
```
15:52:00  openjdk version "21-internal" 2023-09-19
15:52:00  OpenJDK Runtime Environment (build 21-internal-adhoc.****.BuildJDKnextx86-64linuxOpenJDK)
15:52:00  Eclipse OpenJ9 VM (build master-f44193e2549, JRE 21 Linux amd64-64-Bit Compressed References 20230224_399 (JIT enabled, AOT enabled)
15:52:00  OpenJ9   - f44193e2549
15:52:00  OMR      - 8d5adac3991
15:52:00  JCL      - 8237a5ec2c1 based on jdk-21+10)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=OpenJDK-Acceptance&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_x86-64_linux_OpenJDK%2F399%2FOpenJ9-JDKnext-x86-64_linux-20230224-143209.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_x86-64_linux_OpenJDK%2F399%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=f44193e2549cfd79771a3873fda2a4b755a22fbd&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9-staging&LABEL_ADDITION=%21sw.os.cent.6&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=128&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
17:04:46  ===============================================
17:04:46  Running test JCL_Test_0 ...
17:04:46  ===============================================
17:04:46  JCL_Test_0 Start Time: Fri Feb 24 17:04:45 2023 Epoch Time (ms): 1677276285790
17:04:46  variation: NoOptions
17:04:46  JVM_OPTIONS:  

17:04:53  ===============================================
17:04:53      JCL_TEST_Test-Annotation-Package
17:04:53      Tests run: 2, Failures: 0, Skips: 0
17:04:53  ===============================================
17:04:53  
17:04:54  org.openj9.test.java.lang.
01:51:32  Cancelling nested steps due to timeout
01:51:32  Sending interrupt signal to process
01:51:39  -----------------------------------
01:51:39  JCL_Test_0_FAILED
```

Occurred across platforms
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_linux_OpenJDK_testList_0/125/consoleFull
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_ppc64le_linux_OpenJDK_testList_1/124/consoleFull

**Comment by pshipton** [comment]
I ended up creating https://github.com/eclipse-openj9/openj9/issues/16920 which is a dup of this, plus more.
