### ISSUE TITLE
JDK21 java.management/java.lang.managementThreadInfo missing the filed - boolean virtual

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16780]
Failure link
------------

[From [an internal build]()(``):](https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK_testList_0/138/consoleFull)
```
15:09:23  openjdk version "21-internal" 2023-09-19
15:09:23  OpenJDK Runtime Environment (build 21-internal-adhoc.****.BuildJDKnexts390xlinuxOpenJDK)
15:09:23  Eclipse OpenJ9 VM (build master-f44193e2549, JRE 21 Linux s390x-64-Bit Compressed References 20230224_403 (JIT enabled, AOT enabled)
15:09:23  OpenJ9   - f44193e2549
15:09:23  OMR      - 8d5adac3991
15:09:23  JCL      - 8237a5ec2c1 based on jdk-21+10)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=OpenJDK-Acceptance&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_s390x_linux_OpenJDK%2F403%2FOpenJ9-JDKnext-s390x_linux-20230224-143057.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDKnext_s390x_linux_OpenJDK%2F403%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=f44193e2549cfd79771a3873fda2a4b755a22fbd&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9-staging&LABEL_ADDITION=%21sw.os.rhel.8&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=138&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
15:33:01  variation: NoOptions
15:33:01  JVM_OPTIONS:  

15:33:02  FAILED: testGetPlatformMXBeans
15:33:02  java.lang.InternalError: java.security.PrivilegedActionException: java.lang.NoSuchFieldException: virtual
15:33:02  	at java.management/sun.management.Util.threadInfoVirtual(Util.java:111)
15:33:02  	at java.management/sun.management.Util.<clinit>(Util.java:115)
15:33:02  	at java.management/java.lang.management.ManagementFactory.getProxyNames(ManagementFactory.java:857)
15:33:02  	at java.management/java.lang.management.ManagementFactory.getPlatformMXBeans(ManagementFactory.java:825)
15:33:02  	at org.openj9.test.java.lang.management.TestManagementFactory.testGetPlatformMXBeans(TestManagementFactory.java:1390)
15:33:02  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:33:02  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
15:33:02  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
15:33:02  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
15:33:02  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
15:33:02  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
15:33:02  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:33:02  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
15:33:02  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
15:33:02  	at org.testng.TestRunner.run(TestRunner.java:505)
15:33:02  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
15:33:02  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
15:33:02  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
15:33:02  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
15:33:02  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:33:02  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
15:33:02  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
15:33:02  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
15:33:02  	at org.testng.TestNG.runSuites(TestNG.java:1049)
15:33:02  	at org.testng.TestNG.run(TestNG.java:1017)
15:33:02  	at org.testng.TestNG.privateMain(TestNG.java:1354)
15:33:02  	at org.testng.TestNG.main(TestNG.java:1323)
15:33:02  Caused by: java.security.PrivilegedActionException: java.lang.NoSuchFieldException: virtual
15:33:02  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:752)
15:33:02  	at java.management/sun.management.Util.threadInfoVirtual(Util.java:109)
15:33:02  	... 26 more
15:33:02  Caused by: java.lang.NoSuchFieldException: virtual
15:33:02  	at java.base/java.lang.Class.getDeclaredFieldInternal(Class.java:982)
15:33:02  	at java.base/java.lang.Class.getDeclaredField(Class.java:957)
15:33:02  	at java.management/sun.management.Util.lambda$threadInfoVirtual$0(Util.java:104)
15:33:02  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
15:33:02  	... 27 more
15:33:02  
15:33:02  
15:33:02  ===============================================
15:33:02      JLM_Tests_class
15:33:02      Tests run: 66, Failures: 1, Skips: 0
15:33:02  ===============================================
15:33:02  
15:33:02  
15:33:02  ===============================================
15:33:02  JLM_Tests_Suite
15:33:02  Total tests run: 66, Failures: 1, Skips: 0
15:33:02  ===============================================
15:33:02  
15:33:02  -----------------------------------
15:33:02  JLM_Tests_class_0_FAILED
```

**Comment by pshipton** [comment]
This must have been resolved since the failure is no longer seen in jdk21.
