### ISSUE TITLE
Release note 0.38.0 - Support for running OpenJDK 8 and OpenJDK 11 on CentOS 6.10 is deprecated 

### ISSUE THREAD

**Issue by Sreekala-Gopakumar** [eclipse-openj9/openj9#16788]
https://github.com/eclipse-openj9/openj9/pull/16784#discussion_r1118927432

Update the Notable changes in this release table with "Support for running OpenJDK 8 and OpenJDK 11 on CentOS 6.10 is deprecated and might be removed in a future release." Refer to Release note 0.36.0 for more details.

**Comment by pshipton** [comment]
@Sreekala-Gopakumar you are an official OpenJ9 contributor. In the future when you create a doc issue pls add the `comp:doc` label and put it into the appropriate milestone.
