### ISSUE TITLE
Upgrade to harfbuzz 7.0.1 breaks AIX build

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#16936]
See https://openj9-jenkins.osuosl.org/job/Build_JDKnext_ppc64_aix_OpenJDK/428 for many instances of this error:
```
07:24:14  src/java.desktop/share/native/libharfbuzz/hb-algs.hh:882:10: error: 1540-2993 The builtin "__builtin_mul_overflow" is not supported.
07:24:14    return __builtin_mul_overflow (count, size, result);
07:24:14           ^
```

**Comment by pshipton** [comment]
There are more problem than just the builtin, see https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/567#issuecomment-1470954378

**Comment by pshipton** [comment]
Set as jdk21 for now, but once we have a working harfbuzz it needs to be backported...
