### ISSUE TITLE
JDK20 jdk_security3_0_FAILED RuntimeException: Signature verification failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16969]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_s390x_linux_Personal/1/consoleFull)(`rhel7s390x-4-1`):
```
09:00:53  openjdk version "20-internal" 2023-03-21
09:00:53  OpenJDK Runtime Environment (build 20-internal-adhoc.jenkins.BuildJDK20s390xlinuxPersonal)
09:00:53  Eclipse OpenJ9 VM (build master-8cc902bc75f, JRE 20 Linux s390x-64-Bit Compressed References 20230316_13 (JIT enabled, AOT enabled)
09:00:53  OpenJ9   - 8cc902bc75f
09:00:53  OMR      - 035ec68ec0c
09:00:53  JCL      - 10a35739269 based on jdk-20+36)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_io_0,jdk_io_1,jdk_other_0,jdk_other_1,jdk_security1_0,jdk_security1_1,jdk_security2_0,jdk_security2_1,jdk_security3_0,jdk_security3_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=3&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK20_s390x_linux_Personal%2F13%2FOpenJ9-JDK20-s390x_linux-20230316-051333.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK20_s390x_linux_Personal%2F13%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=20&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk20.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=8cc902bc75ffa8e24f4beef2a1f8726a383771eb&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=034d4edd4350276a2d01aade526b242fb70f4eee&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
10:44:37  variation: Mode150
10:44:37  JVM_OPTIONS:  -XX:+UseCompressedOops 

11:02:40  TEST: sun/security/rsa/pss/SerializedPSSKey.java

11:02:40  STDERR:
11:02:40  java.lang.RuntimeException: Signature verification failed
11:02:40  	at SerializedPSSKey.testSignature(SerializedPSSKey.java:132)
11:02:40  	at SerializedPSSKey.test(SerializedPSSKey.java:105)
11:02:40  	at SerializedPSSKey.main(SerializedPSSKey.java:89)
11:02:40  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
11:02:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
11:02:40  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
11:02:40  	at java.base/java.lang.Thread.run(Thread.java:1639)
11:02:40  
11:02:40  JavaTest Message: Test threw exception: java.lang.RuntimeException
11:02:40  JavaTest Message: shutting down test
11:02:40  
11:02:40  
11:02:40  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Signature verification failed

11:24:08  Test results: passed: 874; failed: 5
11:24:08  Report written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_s390x_linux_Personal/aqa-tests/TKG/output_16789717578283/jdk_security3_0/report/html/report.html
11:24:08  Results written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_s390x_linux_Personal/aqa-tests/TKG/output_16789717578283/jdk_security3_0/work
11:24:08  Error: Some tests failed or other problems occurred.
11:24:08  -----------------------------------
11:24:08  jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31767/)

**Comment by tajila** [comment]
@JasonFengJ9 Was a reproduction of this issue seen?

**Comment by pshipton** [comment]
The test fails when run standalone
Failed OpenJ9 jdk20 zLinux https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2249/
Passed with -Xint https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2250/
Passed on amac https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/2252/

@r30shah another, perhaps a dup of https://github.com/eclipse-openj9/openj9/issues/16967

**Comment by r30shah** [comment]
I will check this one out. I have launched a grinder on internal jenkins (/job/Grinder/32364) As Peter mentioned, FYI : @Spencer-Comin , it might be dup of 16967.

**Comment by JasonFengJ9** [comment]
A few more signature-related test failures from [JDK20 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_extended.openjdk_s390x_linux/4/)
```
openjdk version "20" 2023-03-21
IBM Semeru Runtime Open Edition 20+36 (build 20+36)
Eclipse OpenJ9 VM 20+36 (build master-78a79a0ec, JRE 20 Linux s390x-64-Bit Compressed References 20230321_9 (JIT enabled, AOT enabled)
OpenJ9   - 78a79a0ec
OMR      - 97cf2a6e8
JCL      - 38d10ea9b based on jdk-20+36)

[2023-04-24T15:50:44.416Z] variation: Mode150
[2023-04-24T15:50:44.416Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-04-24T17:18:10.805Z] TEST: sun/security/rsa/pss/SerializedPSSKey.java

[2023-04-24T17:18:10.805Z] STDERR:
[2023-04-24T17:18:10.805Z] java.lang.RuntimeException: Signature verification failed
[2023-04-24T17:18:10.805Z] 	at SerializedPSSKey.testSignature(SerializedPSSKey.java:132)
[2023-04-24T17:18:10.805Z] 	at SerializedPSSKey.test(SerializedPSSKey.java:105)
[2023-04-24T17:18:10.805Z] 	at SerializedPSSKey.main(SerializedPSSKey.java:89)

[2023-04-24T17:22:40.114Z] TEST: sun/security/rsa/pss/TestSigGenPSS.java

[2023-04-24T17:22:40.120Z] STDERR:
[2023-04-24T17:22:40.120Z] java.lang.RuntimeException: One or more test failed
[2023-04-24T17:22:40.120Z] 	at TestSigGenPSS.main(TestSigGenPSS.java:88)

[2023-04-24T17:23:40.362Z] TEST: sun/security/rsa/SignatureTest.java

[2023-04-24T17:23:40.364Z] STDERR:
[2023-04-24T17:23:40.364Z] java.lang.RuntimeException: Failed to verify SHA512/256withRSA signature
[2023-04-24T17:23:40.364Z] 	at SignatureTest.checkSignature(SignatureTest.java:211)
[2023-04-24T17:23:40.364Z] 	at SignatureTest.lambda$test$1(SignatureTest.java:109)
[2023-04-24T17:23:40.364Z] 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[2023-04-24T17:23:40.364Z] 	at SignatureTest.lambda$test$2(SignatureTest.java:104)

[2023-04-24T17:28:54.626Z] TEST: sun/security/rsa/TestSigGen15.java

[2023-04-24T17:28:54.631Z] STDERR:
[2023-04-24T17:28:54.631Z] java.lang.RuntimeException: One or more test failed
[2023-04-24T17:28:54.631Z] 	at TestSigGen15.main(TestSigGen15.java:63)

[2023-04-24T19:20:02.252Z] Test results: passed: 875; failed: 4
[2023-04-24T19:20:08.358Z] Report written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16823366852040/jdk_security3_0/report/html/report.html
[2023-04-24T19:20:08.359Z] Results written to /home/jenkins/workspace/Test_openjdk20_j9_extended.openjdk_s390x_linux/aqa-tests/TKG/output_16823366852040/jdk_security3_0/work
[2023-04-24T19:20:08.359Z] Error: Some tests failed or other problems occurred.
[2023-04-24T19:20:08.359Z] -----------------------------------
[2023-04-24T19:20:08.359Z] jdk_security3_0_FAILED
```

**Comment by r30shah** [comment]
I am checking out the failures posted in previous comment, when I relaunched the grinder, I do see test failing with various signature related failures. I also tried out disabling JIT in  `job/Grinder/32500`, I do see bunch of similar errors. Looking if there are some crypto related issues.

**Comment by r30shah** [comment]
The main failure in the description was a Z codegen bug, it is same bug as found in https://github.com/eclipse-openj9/openj9/issues/16479 which was fixed in https://github.com/eclipse/omr/pull/6893 which I was able to verify at that time (Though I clearly see the issue now in my calculation of updating the field in the instruction). Commit in https://github.com/r30shah/omr/commit/f7aeaa83a87d0de91fb8db3973fced693ced1d64 should fix the failure, doing some sanity testing now on JDK20 before opening up PR.
