### ISSUE TITLE
zlinux CS testing crash vmState=0xffffffff

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16976]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_0/494/
- no diagnostics

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_1/495/
- https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_1/495/system_test_output.tar.gz

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_2/494/
- https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_2/494/system_test_output.tar.gz

LambdaLoadTest_CS_5m_0
MathLoadTest_autosimd_CS_5m_0
ParallelStreamsLoadTest_CS_0
DaaLoadTest_daa2_CS_5m_0
DaaLoadTest_daa3_CS_5m_0
DaaLoadTest_daa1_CS_5m_0
MathLoadTest_bigdecimal_CS_5m_0
ClassLoadingTest_CS_5m_0

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly_testList_0/497
- https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk11_j9_extended.system_s390x_linux_Nightly_testList_0/497/system_test_output.tar.gz

DaaLoadTest_all_CS_5m_0
MathLoadTest_all_CS_5m_0

```
DLT stderr Type=Segmentation error vmState=0xffffffff
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
DLT stderr Handler1=000003FF7F2C8458 Handler2=000003FF7F1B33D0 InaccessibleAddress=0000000000000000
DLT stderr gpr0=0000000000000002 gpr1=000003FF7F112CA0 gpr2=0000000000000000 gpr3=0000000000000058
DLT stderr gpr4=000003FF7D15BE90 gpr5=0000000000000000 gpr6=000003FF78055D50 gpr7=000003FF78039578
DLT stderr gpr8=000003FF78055C70 gpr9=000003FF7F326F00 gpr10=000003FF7FA49FB8 gpr11=000003FF78028A90
DLT stderr gpr12=000003FF7FF26F88 gpr13=000003FF7D347588 gpr14=000003FF7D15BE92 gpr15=000003FF7FF6D1A8
DLT stderr psw=000003FF7F326F00 mask=0705000180000000 fpc=00000000 bea=000003FF7D15BE90
DLT stderr fpr0 ffffffffffffffff (f: 4294967296.000000, d: -nan)
DLT stderr fpr1 0000000000000400 (f: 1024.000000, d: 5.059232e-321)
DLT stderr fpr2 000003ff7f1ec1ff (f: 2132722176.000000, d: 2.171855e-311)
DLT stderr fpr3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr fpr4 0000000000000007 (f: 7.000000, d: 3.458460e-323)
DLT stderr fpr5 000000641cec42a0 (f: 485245600.000000, d: 2.124393e-312)
DLT stderr fpr6 000003ff78000938 (f: 2013268224.000000, d: 2.171796e-311)
DLT stderr fpr7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
DLT stderr fpr9 000002aa3159a880 (f: 827959424.000000, d: 1.447610e-311)
DLT stderr fpr10 0000000001d0a8e0 (f: 30451936.000000, d: 1.504526e-316)
DLT stderr fpr11 000003ffd0ffb0a0 (f: 3506417920.000000, d: 2.172534e-311)
DLT stderr fpr12 0000000001d0b128 (f: 30454056.000000, d: 1.504630e-316)
DLT stderr fpr13 000002aa313a2938 (f: 825895232.000000, d: 1.447609e-311)
DLT stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so
DLT stderr Module_base_address=000003FF7F280000
DLT stderr Target=2_90_20230320_503 (Linux 5.4.0-137-generic)
DLT stderr CPU=s390x (4 logical CPUs) (0x1f58f7000 RAM)
```

Changes between last working and first failing build.

OpenJ9: 9e9fe327f9d
OMR: e07b5edc181
OpenJDK11: a6a55907b48 - openj9-openjdk-jdk11

OpenJ9: c03c76e5071
OMR: 1a20c5d2b24
OpenJDK11: bd949902500 - openj9-openjdk-jdk11

https://github.com/eclipse-openj9/openj9/compare/9e9fe327f9d...c03c76e5071
https://github.com/eclipse-openj9/openj9-omr/compare/e07b5edc181...1a20c5d2b24
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/a6a55907b48...bd949902500

@tajila @dmitripivkine

**Comment by pshipton** [comment]
Initially targeting 0.38 until we determine the cause.

**Comment by dmitripivkine** [comment]
Sorry if I am talking too soon. Unfortunately I can not find core file I can open with DDR.
However my theory is:
- from `gcInitializeDefaults()` for machines Guarded Storage support available only we do call 'vm->internalVMFunctions->isCRIUSupportEnabled()'
-  the `isCRIUSupportEnabled()` trying to read `javaVM->checkpointState.isCheckPointEnabled;`
- I am expecting to see `javaVM->checkpointState` set to `NULL`
I will try to download more results files in hope some of cores can be opened by DDR.
Meanwhile I hope this guess might be useful.
@tajila

**Comment by dmitripivkine** [comment]
Looking to the code - seems `javaVM->checkpointState` can not be `NULL`, it is inlined to `J9JavaVM` structure. So we need to check `vm->internalVMFunctions->currentVMThread(vm)`

**Comment by dmitripivkine** [comment]
```
J9VMThread *
currentVMThread(J9JavaVM *vm)
{
	return getVMThreadFromOMRThread(vm, omrthread_self());
}

J9VMThread *
getVMThreadFromOMRThread(J9JavaVM *vm, omrthread_t omrthread)
{
	J9VMThread *vmThread = NULL;

	if ((NULL != omrthread) && (NULL != vm->omrVM) && (vm->omrVM->_vmThreadKey > 0)) {
		OMR_VMThread *omrVMThread = ((OMR_VMThread *)omrthread_tls_get(omrthread, vm->omrVM->_vmThreadKey));
		if (NULL != omrVMThread) {
			vmThread = (J9VMThread *)omrVMThread->_language_vmthread;
		}
	}
	return vmThread;
}
```

**Comment by tajila** [comment]
@r30shah @VermaSh FYI

**Comment by r30shah** [comment]
@dmitripivkine  I can reproduce the failure as you suggested in https://github.com/eclipse-openj9/openj9/issues/16976#issuecomment-1478375363, Do you want me to send the stderr and corresponding diagnostic files?

**Comment by dmitripivkine** [comment]
> @dmitripivkine I can reproduce the failure as you suggested in [#16976 (comment)](https://github.com/eclipse-openj9/openj9/issues/16976#issuecomment-1478375363), Do you want me to send the stderr and corresponding diagnostic files?

Thank you! Unfortunately this core can not be opened by DDR as well.
