### ISSUE TITLE
JDK21 requires JVM_VirtualThreadMount/JVM_VirtualThreadUnmount implementations

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#16984]
[8304303: implement VirtualThread class notifyJvmti methods as C2 intrinsics](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/b0fd76144219fd4f27ea0ae03df04ca2f1051dab) added two new JVM methods. [1]

```
/*
 * Virtual thread support.
 */
JNIEXPORT void JNICALL
JVM_VirtualThreadMount(JNIEnv* env, jobject vthread, jboolean hide, jboolean first_mount);

JNIEXPORT void JNICALL
JVM_VirtualThreadUnmount(JNIEnv* env, jobject vthread, jboolean hide, jboolean last_unmount);
```

In addition, it removed `notifyJvmtiEvents` which made the JCL patch [Enable VirtualThread JVMTI natives by default](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/f7125485b0aa15c530863d151f67ad3ae44078a1) redundant.

FYI @fengxue-IS @babsingh @tajila 

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/1e70d47e951486673ca369046dadc498ccba4a43/src/hotspot/share/include/jvm.h#L1143-L1150

**Comment by babsingh** [comment]
From a functional perspective, the new functions are amalgamated forms of the old functions:
```
JVM_VirtualThreadMount:
   if (hide): JVM_VirtualThreadMountBegin
   else: JVM_VirtualThreadMountEnd

JVM_VirtualThreadUnmount:
   if (hide): JVM_VirtualThreadUnmountBegin
   else: JVM_VirtualThreadUnmountEnd
```

To avoid hindering the JDK19 release, this change should be applied on top of https://github.com/eclipse-openj9/openj9/pull/16855. 

> removed notifyJvmtiEvents which made the JCL patch [Enable VirtualThread JVMTI natives by default](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/f7125485b0aa15c530863d151f67ad3ae44078a1) redundant.

This field has been moved to native. It is enabled from JNI GetEnv if Continuations are enabled.

**Comment by fengxue-IS** [comment]
@thallium can you take a look at this

**Comment by JasonFengJ9** [comment]
https://github.com/eclipse-openj9/openj9/pull/16985#discussion_r1146431459
```
		JVM_VirtualThreadMountBegin
		JVM_VirtualThreadMountEnd
		JVM_VirtualThreadUnmountBegin
		JVM_VirtualThreadUnmountEnd
```
These exports are not needed by JDK21+.

**Comment by keithc-ca** [comment]
More changes coming from upstream, see
* [8306028: separate ThreadStart/ThreadEnd events posting code in JVMTI VTMS transitions](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0bd6a005a3abb24db730e126804ab0b7894ef695)

meaning the signature of two existing functions change and two new ones are introduced.

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/16984#issuecomment-1542647302: @keithc-ca Looking for a timeline to support the new changes. Are the new changes JDK21 specific or will they flow down to JDK20?

**Comment by keithc-ca** [comment]
I've only seen those changes in JDK21; I don't know whether those changes will get back-ported to JDK20.

**Comment by pshipton** [comment]
There are some changes in the jdk20u master branch. We won't integrate anything until there is a 20.0.2 build tag. No guarantee these changes will go in to 20.0.2 or that we'll integrate anything until July 18.

https://github.com/openjdk/jdk20u/compare/jdk-20.0.1+9...master

**Comment by babsingh** [comment]
I don't see [8306028: separate ThreadStart/ThreadEnd events posting code in JVMTI VTMS transitions](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0bd6a005a3abb24db730e126804ab0b7894ef695) in https://github.com/openjdk/jdk20u/compare/jdk-20.0.1+9...master. For the time being, I will assume that the new changes are JDK21-specific.

**Comment by babsingh** [comment]
[8306028: separate ThreadStart/ThreadEnd events posting code in JVMTI VTMS transitions](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0bd6a005a3abb24db730e126804ab0b7894ef695)

Rough draft of the OpenJ9 changes to support the above upstream changes:
```
JNIEXPORT void JNICALL
JVM_VirtualThreadMount(JNIEnv* env, jobject vthread, jboolean hide)
{
	if (hide) {
		JVM_VirtualThreadMountBegin(env, vthread, false);
	} else {
		JVM_VirtualThreadMountEnd(env, vthread, false);
	}
}

JNIEXPORT void JNICALL
JVM_VirtualThreadUnmount(JNIEnv* env, jobject vthread, jboolean hide)
{
	if (hide) {
		JVM_VirtualThreadUnmountBegin(env, vthread, false);
	} else {
		JVM_VirtualThreadUnmountEnd(env, vthread, false);
	}
}

JNIEXPORT void JNICALL
JVM_VirtualThreadStart(JNIEnv* env, jobject vthread)
{
	JVM_VirtualThreadMountEnd(env, vthread, false);
	// All firstMount specific tasks should be extracted from JVM_VirtualThreadMount[Begin|End] and consolidated here
}

JNIEXPORT void JNICALL
JVM_VirtualThreadEnd(JNIEnv* env, jobject vthread)
{
	// All lastUnmount specific tasks should be extracted from JVM_VirtualThreadUnmount[Begin|End] and consolidated here
	JVM_VirtualThreadUnmountBegin
}
```

**Comment by fengxue-IS** [comment]
> More changes coming from upstream, see
> 
> * [8306028: separate ThreadStart/ThreadEnd events posting code in JVMTI VTMS transitions](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0bd6a005a3abb24db730e126804ab0b7894ef695)
> 
> meaning the signature of two existing functions change and two new ones are introduced.

Is there any ETA on when this will be integrated into the extension-repo build branch? if we are expecting this to be done within this week, we should include the changes in #17125 rather than refactoring it shortly after merging.

**Comment by JasonFengJ9** [comment]
> Is there any ETA on when this will be integrated into the extension-repo build branch?

The branch `master`/`openj9-staging` containing the changes in question will be promoted into `openj9` branch after merging [Update FFI specific code for compilation in JDK21]( https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/598), afterwards, the change is visible for usual JDK21 builds.

**Comment by keithc-ca** [comment]
In
* [8306028: separate ThreadStart/ThreadEnd events posting code in JVMTI VTMS transitions](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0bd6a005a3abb24db730e126804ab0b7894ef695)

the signature of these functions changed
* `JVM_VirtualThreadMount`
* `JVM_VirtualThreadUnmount`

and these functions are added
* `JVM_VirtualThreadStart`
* `JVM_VirtualThreadEnd`

**Comment by JasonFengJ9** [comment]
> JVM_VirtualThreadStart
JVM_VirtualThreadEnd

A change to bring up latest Java 21 level including these two APIs is in progress.

**Comment by babsingh** [comment]
https://github.com/eclipse-openj9/openj9/pull/17125 will support the new changes mentioned in https://github.com/eclipse-openj9/openj9/issues/16984#issuecomment-1572348995. The PR title and description needs to be updated but it includes all the four functions: JVM_VirtualThread Mount, Unmount, Start and End
