### ISSUE TITLE
Backport GB18030-2022

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#16987]
We may want some of this for 0.38. See 

https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/7cd4838

https://bugs.openjdk.org/browse/JDK-8301558
https://bugs.openjdk.org/browse/JDK-8301401
https://git.openjdk.org/jdk11u-ri/commit/0a700c6c3d150ed375c113b31b8e6185cbe57ae6

**Comment by knn-k** [comment]
See also https://github.com/openjdk/jdk/pull/12518 for the mapping changes in GB18030-2022.

**Comment by pshipton** [comment]
I think https://github.com/openjdk/jdk/pull/12518 is the same as https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/7cd4838. They are different repos, the one in ibmruntimes is our imported copy.

**Comment by knn-k** [comment]
Yes, I mentioned https://github.com/openjdk/jdk/pull/12518 as I thought it had more information than only the code diffs.

**Comment by pshipton** [comment]
We're not holding M2 for this so I'll move it forward. If we get something merged in head at some point before 0.38 GA we can have a discussion about feasibility of putting it into 0.38.

**Comment by knn-k** [comment]
Update for supporting Level 2 in Java 11 (Change in javadoc only)
https://bugs.openjdk.org/browse/JDK-8305682

**Comment by knn-k** [comment]
I prepared commits for GB18030-2022 support on Java 11.  They are just PoCs.  I am not intending to open PRs soon.

- https://github.com/knn-k/openj9-openjdk-jdk11/tree/gb18030_a (https://bugs.openjdk.org/browse/JDK-8301401 and https://bugs.openjdk.org/browse/JDK-8305682)
- https://github.com/knn-k/openj9-openjdk-jdk11/tree/gb18030_b (https://bugs.openjdk.org/browse/JDK-8301559)

**Comment by knn-k** [comment]
The backported changes for GB18030-2022 came to https://github.com/ibmruntimes/openj9-openjdk-jdk11/, while the changes are not in Java 8/17 repositories yet.

**Comment by knn-k** [comment]
The backport is available in Java 17, too.
https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/2655094afd9702671442b2f338549b45e9ec2c62
