### ISSUE TITLE
-Xlp4k option results in "System configuration does not support option '-Xlp'" error

### ISSUE THREAD

**Issue by joransiu** [eclipse-openj9/openj9#16999]
Java -version output
--------------------
java version "11.0.15" 2022-04-19
IBM Semeru Runtime Certified Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Linux s390x-64-Bit Compressed References 20220427_289 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - da9a227f69 based on jdk-11.0.15+10)

Summary of problem
------------------

Initially reported by an ISV, and I can reproduce on my local Linux on Z.   If huge pages is not configured on the host, the use of `-Xlp4k` JVM option results in the following error:

```sh
$ java -Xlp4k -version
JVMJ9GC032E System configuration does not support option '-Xlp'
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to initialize; unable to parse command line
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

From `/proc/meminfo`, no huge pages is configured:

```
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
```

Configuring huge pages on the system does allow `-Xlp4k` to execute successfully.

The issue is that a user may have reason to force the use of 4K pages, but the JVM option is not portable across different environments.  The ideal behaviour is that the option should be absorb without error if no huge pages is configured on the system.

I believe it's related to this code here: https://github.com/eclipse-openj9/openj9/blob/91bdf39fb6afc0bd8d1f01868c43b8f4c1dd8580/runtime/gc_modron_startup/mmparse.cpp#L620-L648

**Comment by joransiu** [comment]
Thanks @dmitripivkine.  Yes, the customer is using `-Xlp:objectheap:pagesize=4K` and `-Xlp:codecache:pagesize=4K`, which works.  It just was not obvious from the documentation that -Xlp4k would throw an error.  They did note the deprecation of -Xlp option, but not necessarily -Xlp<size>. https://www.eclipse.org/openj9/docs/xlp/#linux

**Comment by dmitripivkine** [comment]
@pshipton My vote is do nothing for old `-Xlp` parser and close this issue. It has not been intended to be used for small pages setup. New commands work properly.
