### ISSUE TITLE
mkdocker.sh only installs gcc 7.5

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17039]
The docker script mkdocker.sh installs gcc 7.5 but jdk17 uses gcc 10.3 and jdk19 uses 11.2 (except on alinux).

**Comment by keithc-ca** [comment]
Some of those goals may be harder to achieve for out-of-support Ubuntu versions (e.g. 16.04).
We're probably also overdue for adding support for Ubuntu 22.04.

**Comment by pshipton** [comment]
I don't see why we can't drop Ubuntu 16.

**Comment by pshipton** [comment]
I think we agreed "at the first sign of trouble" it could be removed, so I'll leave it up to you. I won't object again if it's removed.
