### ISSUE TITLE
A number of Windows machines are offline

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17055]
Causing a noticeable slowdown in the nightly builds.

https://openj9-jenkins.osuosl.org/computer/win2012%2Dx86%2D1/
https://openj9-jenkins.osuosl.org/computer/win2012%2Dx86%2D2/
https://openj9-jenkins.osuosl.org/computer/win2012%2Dx86%2D7/
https://openj9-jenkins.osuosl.org/computer/win2019%2Dx64%2D3/
https://openj9-jenkins.osuosl.org/computer/win2019x64%2Dopenj9%2D2/

@AdamBrousseau @vsebe

**Comment by AdamBrousseau** [comment]
Tried to reboot win2012-1 but it is giving network error trying to send the request. Need to dig a bit more.

**Comment by vsebe** [comment]
Rebooted [win2019x64-openj9-3](https://openj9-jenkins.osuosl.org/computer/win2019x64%2Dopenj9%2D2/) and recreated the node.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/computer/win2019%2Dx64%2D2/ is offline again.

**Comment by AdamBrousseau** [comment]
Back to the problem where renaming the node forces the reconnect.
Renamed to -2a
