### ISSUE TITLE
Timing hole between concurrent scanning and freeContinuation

### ISSUE THREAD

**Issue by LinHu2016** [eclipse-openj9/openj9#17058]
For last unmounting continuation, the related J9VMContinuation structure need to be freed/recycled and reset vmref (point to the J9VMContinuation) in the contunuation Object, the related native memory might be reallocated for new continuation, currently we use  the filed state of J9VMContinuation to avoid concurrent scan the finished continuation(after last unmounting), before  checking J9VMContinuation->state, we need to verify the vmref is not NULL, but freeContinuation could happen in between, it would cause we retrieve incorrect J9VMContinuation->state and potentially cause JVM crash.

**Comment by gacholio** [comment]
The initial suggestion is to move the state variable into the object instead of the native structure. The state will be updated atomically, and will control the validity of the native structure pointer.

**Comment by gacholio** [comment]
@amicic @dmitripivkine

**Comment by amicic** [comment]
To avoid potentially inconsistency of 'finished' info between the bool and a bit in the state, it's probably wise to remove the bool.
On the other side, I'd consider this PR for propagating to 0.37 - while we can't reproduce the problem, it could be just that our workloads are not complex enough.

**Comment by pshipton** [comment]
Move this back to 0.37 for now.

**Comment by amicic** [comment]
https://github.com/eclipse-openj9/openj9/pull/17111 have been soaked for 2 nights and I recommend propagating to 0.37. Any objections (@tajila, @gacholio, @babsingh)?

**Comment by pshipton** [comment]
I assume this can be closed.
