### ISSUE TITLE
apport is enabled on ub16p8j93

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17088]
All the core file related testing failed on [ub16p8j93](https://openj9-jenkins.osuosl.org/computer/ub16p8j93) because apport became enabled.

 https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_extended.functional_ppc64le_linux_Nightly_testList_1/136

See https://github.com/eclipse-openj9/openj9/issues/15088 for history.

@vsebe

04:49:10  FAILED test targets:
04:49:10  	testOpenJ9DiagnosticsMXBean_0 
04:49:10  	testDDRExt_Class_0 
04:49:10  	testDDRExt_Callsites_0 
04:49:10  	testDDRExtJunit_CollisionResilientHashtable_0 
04:49:10  	testDDRExtJunit_MonitorsAndDeadlock1_0 
04:49:10  	testDDRExtJunit_MonitorsAndDeadlock1_1 
04:49:10  	testDDRExtJunit_MonitorsAndDeadlock3_0 
04:49:10  	testDDRExtJunit_MonitorsAndDeadlock3_1 
04:49:10  	testDDRExtJunit_MonitorsAndDeadlock4_1 
04:49:10  	testDDRExtJunit_MonitorsAndDeadlock6_0 
04:49:10  	testDDRExtJunit_MonitorsAndDeadlock6_1 
04:49:10  	testSCCMLTests2_0 
04:49:10  	testSCCMLTests4_1 
04:49:10  	cmdLineTester_shrcdbgddrext_1 
04:49:10  	cmdLineTester_classesdbgddrext_0 
04:49:10  	cmdLineTester_pltest_j9sig_ext_0 
04:49:10  	cmdLineTester_modularityddrtests17_0 
04:49:10  	cmdLineTester_modularityddrtests17_1 
04:49:10  	cmdLineTester_dumpromclasstests_0

**Comment by pshipton** [comment]
More failures on this machine.
https://openj9-jenkins.osuosl.org/job/Test_openjdk20_j9_sanity.functional_ppc64le_linux_Nightly_testList_1/26/
01:50:48  FAILED test targets:
01:50:48  	cmdLineTester_callsitedbgddrext_openj9_0 
01:50:48  	cmdLineTester_pltest_0 
01:50:48  	cmdLineTester_GCCheck_1 
01:50:48  	cmdLineTester_GCCheck_3

**Comment by vsebe** [comment]
fixed

**Comment by vsebe** [comment]
cmdLineTester_callsitedbgddrext_openj9_0
cmdLineTester_pltest_0
cmdLineTester_GCCheck_1
cmdLineTester_GCCheck_3 
grinder: [![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Grinder&build=2168)](https://openj9-jenkins.osuosl.org/job/Grinder/2168/)
