### ISSUE TITLE
Add support for -XX:+EnableDynamicAgentLoading

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#17085]
Currently, j9 supports dynamic loading agents by default. 

The capabilities required for agents are: 
```
J9_EXTENDED_RUNTIME_OSR_SAFE_POINT
J9_EXTENDED_RUNTIME_ENABLE_HCR
```

These are currently enabled all the time. 

We need to put default enablement of these capabilities under the `EnableDynamicAgentLoading` flag. This will make it possible to turn off `EnableDynamicAgentLoading` in a future release if it is required in a future release. For now `EnableDynamicAgentLoading` can remain enabled by default. This will change likely in JDK21.

Additionally, we need to detect jvm agents attached are startup. We can look at `createAgentLibrary(` and lazily add the OSR/HCR flags when this occurs. 

We should add a runtime flag, for dynamic agent loading, this can be used to check if an agent is allowed to be loading at runtime.

The end result is:
1) When `EnableDynamicAgentLoading` is enabled, OSR/HCR flags are enable and dynamic agent loading is also enabled.
2) When `EnableDynamicAgentLoading` is disabled, OSR/HCR is only enabled when agents are attached at startup. Dynamic loading of agents is disabled.

**Comment by JasonFengJ9** [comment]
[JEP 261: Module System](https://openjdk.org/jeps/261) proposed `-XX:[+|-]EnableDynamicAgentLoading` 
_The dynamic loading of JVM TI agents will be disabled by default in a future release. To prepare for that change we recommend that applications that allow dynamic agents start using the option -XX:+EnableDynamicAgentLoading to enable that loading explicitly. The option -XX:-EnableDynamicAgentLoading disables dynamic agent loading._

This change prevents the AttachAPI from loading an agent into a JVM after startup
https://github.com/eclipse-openj9/openj9/blob/11eb3b77f2ee0cd626f75bb2fb36bd65e4b0baa3/runtime/vm/BytecodeInterpreter.hpp#L4773-L4775
which invokes https://github.com/eclipse-openj9/openj9/blob/11eb3b77f2ee0cd626f75bb2fb36bd65e4b0baa3/runtime/jvmti/jvmtiStartup.c#L556-L563

**Comment by dnakamura** [comment]
Prototype for command line option is at #17215. @JasonFengJ9 are you saying we should also error out when attempting to load an agent? If so is it sufficient to check the `J9_EXTENDED_RUNTIME_OSR_SAFE_POINT` and `J9_EXTENDED_RUNTIME_ENABLE_HCR`? Or should we be adding a new runtime flag? (since its possible to disable either of those flags individually without `-XX:-EnableDynamicAgentLoading`)

**Comment by JasonFengJ9** [comment]
> Or should we be adding a new runtime flag? (since its possible to disable either of those flags individually without -XX:-EnableDynamicAgentLoading)

I think a new runtime flag is required.

**Comment by fengxue-IS** [comment]
`-XX:[+/-]EnableDynamicAgentLoading` should not affect how HCR and OSR work and will need a new runtime flag or internal java property. Looking at the purposed [JEP draft: Prepare to Restrict The Dynamic Loading of Agents](https://openjdk.org/jeps/8306275) this option is simply a way of disabling the Attach API.

As OpenJ9's agentload code only have a single entry point in JCL, could just add new check for the flag/property at 
https://github.com/eclipse-openj9/openj9/blob/84d391418c38c0f5118dd2b3e883e174e2a2f800/jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/Attachment.java#L369-L383

This would be a requirement if we want enable optimization to allow VirtualThread to skip `notifyJvmti*` calls when no JVMTI agent requires such capabilities.

**Comment by tajila** [comment]
From a functional perspective, all we need to do is disable dynamic loading of agents. However, given that in J9 an agent can always be dynamically loaded we need to support OSR/HCR  all the time. The removal of this capability lets us disable HCR/OSR as default JVM capabilities and only apply them when they are needed which is important from a performance perspective.

**Comment by keithc-ca** [comment]
> given that in J9 an agent can always be dynamically loaded

Please explain how this is not in fundamental conflict with the intent of `-XX:-EnableDynamicAgentLoading`?

**Comment by tajila** [comment]
> Please explain how this is not in fundamental conflict with the intent of -XX:-EnableDynamicAgentLoading?

The fact that J9 always allows dynamic agent loading is not spec behaviour. In fact, it hasn't always been J9 behaviour. In the early releases of JDK8 this was not the case. 

The new proposed options standardizes this behaviour.

**Comment by keithc-ca** [comment]
Just to be crystal clear, so using `-XX:-EnableDynamicAgentLoading` would disallow dynamic agent loading (period)?

**Comment by tajila** [comment]
> Just to be crystal clear, so using -XX:-EnableDynamicAgentLoading would disallow dynamic agent loading (period)?

yes, thats correct

**Comment by tajila** [comment]
Closing as initial PR is merged
