### ISSUE TITLE
Variations under test are also used as JVM args in cmdLineTester

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#17095]
I noticed that in the various `playlist.xml` definitions for tests in `cmdLineTests`, the variations that are supposed to be passed in as arguments to `cmdlinetester.jar` (which launches new JVMs with these options) are also for some reason used by the JVM that's running `cmdlinetester.jar`.

This means that, for example, if one of the variations is `-Xjit:count=0`, we actually run something like:
```
java -Xjit:count=0 -jar cmdlinetester.jar -DJVM_OPTIONS="-Xjit:count=0"
```
because of
```
$(JAVA_COMMAND) $(JVM_OPTIONS) -jar $(CMDLINETESTER_JAR) -DJVM_OPTIONS=$(Q)$(JVM_OPTIONS)$(Q)
```
which would just slow down the test overall.

I could be wrong but it doesn't look like this is or should be the intended behaviour; it seems to me that other tests outside `cmdLineTests` do need to do 
```
$(JAVA_COMMAND) $(JVM_OPTIONS) ...
```
and so that template may have been copied over for `cmdLineTests`.

Personally I think that the `cmdLineTests` tests should do the following:
```
$(JAVA_COMMAND) -Xshareclasses:none -jar $(CMDLINETESTER_JAR) -DJVM_OPTIONS=$(Q)$(JVM_OPTIONS)$(Q)
```
This decouples the options under test from the harness, and also prevents situations where the JVM that's under test ends up generating a bad AOT method that the `cmdlinetester.jar` JVM will load and crash. Or if there _really_ is a desire to have the `cmdlinetester.jar` JVM to use a SCC, then it should explicitly name one so that it doesn't use the default SCC generated by JVMs under test.

Ideally the JVM running `cmdlinetester.jar` should also not be the JVM we're testing but some other JVM build, but I'm not sure how feasible that is.

**Comment by dsouzai** [comment]
FYI @llxia @renfeiw 

FWIW, I don't mind volunteering to clean this up if you agree with my suggestion.

**Comment by dsouzai** [comment]
> Hopefully we've removed all the places where we set `-Xint` to run the cmdlinetester, which is from many many year ago when the JIT was often unreliable to run the cmdlinetester.

If we still have any then I'll remove it in a different commit (assuming three's no problems when doing so).

**Comment by llxia** [comment]
Thanks @dsouzai . Please feel free to clean this up.
