### ISSUE TITLE
jdk21 is failing to compile on all platforms

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17115]
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/455/
Example https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/302
```
00:02:23  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/src/java.base/share/classes/jdk/internal/foreign/CABI.java:83: error: cannot find symbol
00:02:23              if (OS.startsWith("Linux")) {
00:02:23                  ^
00:02:23    symbol:   variable OS
00:02:23    location: class CABI
00:02:23  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/src/java.base/share/classes/jdk/internal/foreign/CABI.java:88: error: cannot find symbol
00:02:23          } else if (ARCH.equals("s390x") && OS.startsWith("Linux")) {
00:02:23                                             ^
00:02:23    symbol:   variable OS
00:02:23    location: class CABI
```

Changes from the last working build https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/57c5b689e006...158cbe49440
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/85f1d7cc32abdf was the change.

**Comment by ChengJin01** [comment]
As talked to @JasonFengJ9 offline, the change should be in the `openj9-stagging` branch coming with the latest FFI related changes after https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/572 (still not yet merged to the `openj9` branch due to the blocker issue on AIX at https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/572#issuecomment-1489555805.

In such case, I will need to compile with the changes from the `openj9-stagging` branch to see what needs to be fixed there.

**Comment by pshipton** [comment]
Right, open the PR to fix it against the openj9-staging branch.

**Comment by pshipton** [comment]
@ChengJin01 you can still open a PR with your fix and I would merge it.

**Comment by ChengJin01** [comment]
> @ChengJin01 you can still open a PR with your fix and I would merge it.

PR is created at https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/580.

**Comment by pshipton** [comment]
ATM we don't know if the InternalError is related to the first set of changes, there are additional changes as well which may, or may not, be a factor.

https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/158cbe49440...a762b43b8b1

**Comment by pshipton** [comment]
There is a new build running with Cheng's update.
https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/457/

**Comment by pshipton** [comment]
Jason opened https://github.com/eclipse-openj9/openj9/issues/17121 so I will close this one.
