### ISSUE TITLE
win2012-x86-2 not enough space on the disk

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17114]
A test failed on [win2012-x86-2](https://openj9-jenkins.osuosl.org/computer/win2012-x86-2) due to not enough space.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_0/491/

@vsebe can you pls take a look when you have a chance.

**Comment by vsebe** [comment]
Cleaned C: removed cores, bootjdks and openjdk_cache duplicates, c/cygwin.
D (pagefiles only) used to be 8GB (2 disks: 2GB + 6GB - disk is missing and cannot be brought back online).
![image](https://user-images.githubusercontent.com/28537856/230222290-c9fa2500-5517-4f5f-a305-9884adb452c0.png)

**Comment by vsebe** [comment]
Moved ant to F:/apache-ant.
[testRASAPI_0 grinder](https://openj9-jenkins.osuosl.org/job/Grinder/2207/ ) on [win2012-x86-2](https://openj9-jenkins.osuosl.org/computer/win2012-x86-2) passed  - [![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Grinder&build=2207)](https://openj9-jenkins.osuosl.org/job/Grinder/2207/)
