### ISSUE TITLE
cmdLineTester_getPid fails for JDK_IMPL=hotspot

### ISSUE THREAD

**Issue by smlambert** [eclipse-openj9/openj9#17173]
This fails across all hotspot builds on all platforms and likely was introduced via https://github.com/eclipse-openj9/openj9/pull/17109

Failure link
------------

Public link to the failing test: https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.functional_x86-64_mac/357/
and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/adoptium/aqa-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include:
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): functional
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): cmdLineTester_getPid
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): all platforms
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: regression that appears to have been introduced via https://github.com/eclipse-openj9/openj9/pull/17109

Optional info
-------------

- intermittent failure (yes|no): no
- regression or new test:  regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :  

Failure output (captured from console output)
---------------------------------------------
Include test case name, stack trace output.  If test fails with a crash, please include a link to the artifacts (xxxx_test_output.tar.gz) as they include the core/dmp files.  Artifacts are either stored as an attachment to the CI server job itself or as a link from the job to an Artifactory location.

**Comment by pshipton** [comment]
```
TESTING:
Unrecognized option: -Xshareclasses:none
```

**Comment by llxia** [comment]
We should make sure CMDLINETESTER_JVM_OPTIONS is only set for impl=openj9 and ibm. https://github.com/eclipse-openj9/openj9/blob/8ee78234960b589474e57dd224b3e3b430732994/test/functional/cmdLineTests/variables.mk#L23

@LongyuZhang could you help with this? Thanks
