### ISSUE TITLE
jdk19 assert ContinuationHelpers.cpp:276 running TimedGet or Skynet

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17181]
These failures are seen in grinders, which are short lived. The grinders are running jdk_lang_1 on AIX, from the 0.37 release branch.
https://github.com/eclipse-openj9/openj9/issues/17163#issuecomment-1506275869

https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_3/1831
java/lang/Thread/virtual/stress/TimedGet.java
`18:54:01  22:52:19.743 0x100238df600    j9vm.224    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/build-scripts/jobs/jdk19u/jdk19u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/vm/ContinuationHelpers.cpp:276: ((!VM_VMHelpers::isConcurrentlyScanned(continuationState) && ((0) == VM_VMHelpers::getCarrierThread(continuationState))))`

https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_4/1732/
java/lang/Thread/virtual/stress/Skynet.java
`18:30:36  22:30:08.815 0x10023d6fb00    j9vm.224    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/build-scripts/jobs/jdk19u/jdk19u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/vm/ContinuationHelpers.cpp:276: ((!VM_VMHelpers::isConcurrentlyScanned(continuationState) && ((0) == VM_VMHelpers::getCarrierThread(continuationState))))`

**Comment by LinHu2016** [comment]
the Assertion had recently updated to catch two exceptional cases during freeContinuation, the continuation, which is needed to be freed, 1, it is still currently in scanning, 2, it is still mounted.
since the Assertion happens on AIX(PowerPC has weak memory model), so setContinuationFinished and resetContinuationCarrierID in yieldContinuation could be reordered, then create a timing hole for concurrent scanning, we might need barrier between them.

**Comment by amicic** [comment]
Probably the simplest is to just set finished flag and reset carrier ID in one step. The existing write barrier should be sufficient.

swap
write barrier
if last unmount 
    set finished flag and reset carrier ID (in one store operation)
else
    reset carrier ID

**Comment by LinHu2016** [comment]
Or move
```
	if (finished) {
		VM_VMHelpers::setContinuationFinished(continuationStatePtr);
	}

```
before
	`VM_AtomicSupport::readWriteBarrier();
`
?
