### ISSUE TITLE
The return value of the System Property is incorrect in OpenJ9-17

### ISSUE THREAD

**Issue by TemporaryRepos** [eclipse-openj9/openj9#17248]
Java -version output
--------------------
```
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Linux amd64-64-Bit Compressed References 20230117_397 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)

openjdk version "11.0.18" 2023-01-17
IBM Semeru Runtime Open Edition 11.0.18.0 (build 11.0.18+10)
Eclipse OpenJ9 VM 11.0.18.0 (build openj9-0.36.1, JRE 11 Linux amd64-64-Bit Compressed References 20230214_644 (JIT enabled, AOT enabled)
OpenJ9   - 0592661e4
OMR      - f491bbf6f
JCL      - 4e060ceb0b based on jdk-11.0.18+10)

openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b09)
Eclipse OpenJ9 VM (build openj9-0.36.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20230206_588 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - eebde685ec based on jdk8u362-b09)
```
Summary of problem
------------------

When OpenJ9-8 and OpenJ9-11 call `System.getProperty("jdk.boot.class.path.append")` , it returns null if the Property does not exist. But when the function is called with OpenJ9-17, the string "" is returned. We also executed the test cases using Hotspot and they returned null. Should this be fixed and output uniformly?

Source code
----------------
public class testcase5 {
public static void main(String[] var0) throws Exception {
    	System.out.println(System.getProperty("jdk.boot.class.path.append"));
    }
}

**Comment by pshipton** [comment]
It's null in jdk11 due to https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/jdk/internal/misc/VM.java#L228

jdk17+ handles it differently, never adding it as system property after it's saved in jdk.internal.misc.VM.
