### ISSUE TITLE
jdknext zlinux build Hash of java.rmi differs to expected hash

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17242]
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_s390x_linux_OpenJDK/433
```
14:00:25  Creating java.base.jmod
14:00:33  openjdk version "21-internal" 2023-09-19
14:00:33  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDKnexts390xlinuxOpenJDK)
14:00:33  Eclipse OpenJ9 VM (build master-fdbd7422186, JRE 21 Linux s390x-64-Bit Compressed References 20230420_433 (JIT enabled, AOT enabled)
14:00:33  OpenJ9   - fdbd7422186
14:00:33  OMR      - 97cf2a6e860
14:00:33  JCL      - 4e21bd55041 based on jdk-21+19)
14:01:20  Creating jdk image
14:01:20  Error: Hash of java.rmi (f21d370ed4b0d2b138d1e1ae74c308247a9cd8cc3b9f37be8c03fc68983ef647) differs to expected hash (0c4c5ff69107d4be730d1e36432b97a84e0fe684a8c0290258de434cb1a45e08) recorded in java.base
14:01:20  java.lang.module.FindException: Hash of java.rmi (f21d370ed4b0d2b138d1e1ae74c308247a9cd8cc3b9f37be8c03fc68983ef647) differs to expected hash (0c4c5ff69107d4be730d1e36432b97a84e0fe684a8c0290258de434cb1a45e08) recorded in java.base
14:01:20  	at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
14:01:20  	at java.base/java.lang.module.Resolver.checkHashes(Resolver.java:480)
14:01:20  	at java.base/java.lang.module.Resolver.finish(Resolver.java:378)
14:01:20  	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
14:01:20  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
14:01:20  	at java.base/java.lang.module.Configuration.resolve(Configuration.java:254)
14:01:20  	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:217)
14:01:20  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:523)
14:01:20  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:411)
14:01:20  	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:286)
14:01:20  	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:56)
14:01:20  	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:34)
```

Working 
OpenJ9: 7f68fd61352
OMR: 97cf2a6e860
OpenJDKnext: 26fec234ee4 - openj9-openjdk-jdk

Not working
OpenJ9: fdbd7422186
OMR: 97cf2a6e860
OpenJDKnext: 4e21bd55041 - openj9-openjdk-jdk

https://github.com/eclipse-openj9/openj9/compare/7f68fd61352...fdbd7422186
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/26fec234ee4...4e21bd55041 

Seems that https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/564 caused this.
@keithc-ca @KostasTsiounis @jasonkatonica

**Comment by keithc-ca** [comment]
I noticed a similar failure in an earlier acceptance build. When I tried a local build then it passed so I attributed the problem to infrastructure. A build passed again this morning:
```
$ images/jdk/bin/java -version
openjdk version "21-internal" 2023-09-19
OpenJDK Runtime Environment (build 21-internal-adhoc.keithc.jdknext)
Eclipse OpenJ9 VM (build main-36c047f9db3, JRE 21 Linux s390x-64-Bit Compressed References 20221209_000000 (JIT enabled, AOT enabled)
OpenJ9   - 36c047f9db3
OMR      - 97cf2a6e860
JCL      - 0f7b79d6972 based on jdk-21+19)
```
That build was configured
```
--with-boot-jdk=/home/keithc/space/bootjdk20 --disable-warnings-as-errors --with-native-debug-symbols=external --enable-jitserver --with-openssl=fetched --enable-openssl-bundling --with-conf-name=normal
```
The hashes use "SHA-256" which should not be affected by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/564
```
$ images/jdk/bin/jmod describe images/jmods/java.base.jmod | grep hashes | grep java.rmi
hashes java.rmi SHA-256 7c19bfc70bb2d7ce3ae4ade1ba505aac0a0a41f4453cd5af3bfbe34008b82a29
```

**Comment by keithc-ca** [comment]
The date "20221209_000000" in that `-version` output surprised me, but I'm not sure how it happened as I said `make reconfigure clean` before `make images` (which should have recreated `vm/runtime/j9version.h` with today's date).

I also realized that the first build was based on `OpenSSL_1_1_1t` while the acceptance build used `OpenSSL_1_1_1t+CVEs1`, so I updated openssl and did another build. Same result: no hash error.
```$ images/jdk/bin/java -version
openjdk version "21-internal" 2023-09-19
OpenJDK Runtime Environment (build 21-internal-adhoc.keithc.jdknext)
Eclipse OpenJ9 VM (build main-36c047f9db3, JRE 21 Linux s390x-64-Bit Compressed References 20230421_000000 (JIT enabled, AOT enabled)
OpenJ9   - 36c047f9db3
OMR      - 97cf2a6e860
JCL      - 0f7b79d6972 based on jdk-21+19)
```

**Comment by pshipton** [comment]
The OpenSSL version we build against doesn't matter much since it's not bundled. We'll use the OpenSSL installed on the machine at runtime.

The last working build https://openj9-jenkins.osuosl.org/job/Build_JDKnext_s390x_linux_OpenJDK/432/ was on [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3).
The next 3 builds (using consecutive numbers) were on [rh7-390-1](https://openj9-jenkins.osuosl.org/computer/rh7-390-1), [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3), [rh7-390-4](https://openj9-jenkins.osuosl.org/computer/rh7-390-4)

**Comment by keithc-ca** [comment]
When I forced the build to use the version of openssl installed on my system (OpenSSL 1.1.1f  31 Mar 2020) it still succeeded.

**Comment by keithc-ca** [comment]
Ok, I reproduced the problem by _disabling_ use of openssl via `jlink -J-Djdk.nativeCrypto=false ...`.

**Comment by keithc-ca** [comment]
It still fails with https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/564 reverted (i.e. https://github.com/keithc-ca/openj9-openjdk/tree/hashes).

**Comment by keithc-ca** [comment]
Even 26fec234ee4 fails if told not to use openssl:
```
Creating jdk image
MessageDigest native crypto implementation disabled. Using Java crypto implementation.
Error: Hash of java.rmi (7d1bc12a5c18bf71fc4159bbf9605d3ddbe3bddbab3d776483adf7dd2af1977f) differs to expected hash (7c19bfc70bb2d7ce3ae4ade1ba505aac0a0a41f4453cd5af3bfbe34008b82a29) recorded in java.base
java.lang.module.FindException: Hash of java.rmi (7d1bc12a5c18bf71fc4159bbf9605d3ddbe3bddbab3d776483adf7dd2af1977f) differs to expected hash (7c19bfc70bb2d7ce3ae4ade1ba505aac0a0a41f4453cd5af3bfbe34008b82a29) recorded in java.base
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
	at java.base/java.lang.module.Resolver.checkHashes(Resolver.java:480)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:378)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:254)
	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:217)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:523)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:411)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:286)
	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:56)
	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:34)
```
```
$ ./jdk/bin/java -version
openjdk version "21-internal" 2023-09-19
OpenJDK Runtime Environment (build 21-internal-adhoc.keithc.jdknext)
Eclipse OpenJ9 VM (build main-36c047f9db3, JRE 21 Linux s390x-64-Bit Compressed References 20230421_000000 (JIT enabled, AOT enabled)
OpenJ9   - 36c047f9db3
OMR      - 97cf2a6e860
JCL      - 26fec234ee4 based on jdk-21+19)
```

**Comment by keithc-ca** [comment]
The best explanation I can offer is that with https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/564 openssl is disabled (when we don't expect it to be).

**Comment by keithc-ca** [comment]
I suggest the path forward is to revert https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/564 until a modified change is offered that doesn't disable use of openssl (presumably because the system only has the older 1.0.2k version installed).

**Comment by keithc-ca** [comment]
See https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/589.

**Comment by keithc-ca** [comment]
I suggest we leave this open until we understand (and fix) the failure on zLinux that occurs when openssl is not available (or is disabled).

**Comment by keithc-ca** [comment]
I'm beginning to suspect this is a JIT issue.

If `-Xint` is used to create `java.base.jmod` (when hashes are computed) and used when running `jlink` this problem goes away whether openssl is used or not (for either step).

**Comment by pshipton** [comment]
Could be a dup of https://github.com/eclipse-openj9/openj9/issues/16969

**Comment by pshipton** [comment]
or https://github.com/eclipse-openj9/openj9/issues/16968 or https://github.com/eclipse-openj9/openj9/issues/16967

**Comment by r30shah** [comment]
I am trying to check if this is dup of https://github.com/eclipse-openj9/openj9/issues/16967 or not. On my Z dev machine as well as on one of the internal jenkins machine I can not reproduce this. Will checkout if I can get it failed again on the same machine where it was originally reported.

**Comment by pshipton** [comment]
@r30shah how are you trying to reproduce it? You can re-apply https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/564, which was reverted, or build without OpenSSL support by not using the `--with-openssl=fetched` option.

**Comment by r30shah** [comment]
> @r30shah how are you trying to reproduce it? You can re-apply https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/564, which was reverted, or build without OpenSSL support by not using the --with-openssl=fetched option.

I have certainly not re-applied the patch, let me try with that.

**Comment by r30shah** [comment]
I was able to reproduce this failure on my dev machine, and with the fix mentioned in https://github.com/eclipse-openj9/openj9/issues/16967 I can get the JDK next build finish success fully (I built without OpenSSL support by not using the --with-openssl=fetched option.) So this one is dup of https://github.com/eclipse-openj9/openj9/issues/16967
