### ISSUE TITLE
`DestroyJavaVM()` fails on OpenJ9

### ISSUE THREAD

**Issue by g-pechorin** [eclipse-openj9/openj9#17267]
I'm trying to embed the OpenJ9 JVM in a C++ program, and, I can't close and recreate the JVM. 
Startup and everything else seems to be fine, but, when I close a JVM with DestroyJavaVM() I get an error.
This error means that successive openings don't operate correctly - which makes other things hard.

I asked on Slack (et al) and ... I guess this is a `generic issue?`

I've attached a standalone example of this happening on Windows.
One of the last lines `jvm->DestroyJavaVM();` returns `JVM_ERR (-1)` after which point the `JNI_CreateJavaVM` calls stop working.

```
/*
Simple test demonstrating that the OpenJ9 JVM doesn't close/re-open on Windows

Output;

	> starting loop 0 ...
	> EXPECTED ? JNI_OK == destroy_ret
	> starting loop 1 ...
	> REQUIRED ! JNI_OK == create_ret

Tested with
	- JDK 11
		11.0.18.0
		OpenJDK 11.0.18+10
		OpenJ9 0.36.1
	- JDK 19
		18.0.2.1
		OpenJDK 18.0.2+9
		OpenJ9 0.33.1

Builds with a CMake file

	cmake_minimum_required (VERSION 3.26.3)
	project (embed)
	find_package(JNI)
	include_directories(${JNI_INCLUDE_DIRS})
	add_executable(embed embed.cpp)

*/

#include <stdio.h>
#include <stdlib.h>

///
// include JNI and suppress all the warnings it emits
#pragma once
#pragma warning( push )
#pragma warning( suppress : 26451 )
#pragma warning( suppress : 26495 )
#pragma warning( suppress : 26812 )
#include <jni.h>
#pragma warning( pop )

/// 
// using a function pointer is easier (on Windows)
using create_java_vm_t = jint(JNICALL*)(JavaVM**, void**, void*);
#ifdef _WIN32
#   include <string> // to concatenate path strings
#   include <Windows.h> // to load functions from a .dll
#endif

///
// assertion macros

// for things that must always be true or we crash
#define REQUIRED(CON) do { if (CON) break; fprintf(stderr, ("REQUIRED ! " #CON "\n")); exit(EXIT_FAILURE); } while(false)

// for things that should be true but we can probably continue without
#define EXPECTED(CON) do { if (CON) break; fprintf(stderr, ("EXPECTED ? " #CON "\n")); } while(false)


int main(int argc, char* argv[])
{
	// find the function pointer
	create_java_vm_t create_java_vm;	
#ifdef _WIN32
	{
		auto path = std::string(getenv("JAVA_HOME")) + "bin/server/jvm.dll";
		create_java_vm = (create_java_vm_t)GetProcAddress(LoadLibrary(path.c_str()), "JNI_CreateJavaVM");
	}
#else
	{
		// i haven't tested this on not-windows
		create_java_vm = JNI_CreateJavaVM;
	}
#endif
	REQUIRED(nullptr != create_java_vm);
	
	// create and release the JVM 10 times
	for (int i = 0; i < 10; ++i)
	{
		printf("starting loop %d ...\n", i);

		JavaVMInitArgs args = {};
		args.version = JNI_VERSION_1_2;

		JavaVM* jvm;
		JNIEnv* env;

		// create the jvm
		auto create_ret = create_java_vm(&jvm, (void**)&env, &args);
		REQUIRED(JNI_OK == create_ret);

		// every other time ... run the GC method so we know we're doing something
		if (i % 2)
    	{
			auto sys = env->FindClass("java/lang/System");
			REQUIRED(sys);
			auto gc = env->GetStaticMethodID(sys, "gc", "()V");
			REQUIRED(gc);
			env->CallStaticVoidMethod(sys, gc);
		}

		// destroy the jvm
		const auto destroy_ret = jvm->DestroyJavaVM();
		EXPECTED(JNI_OK == destroy_ret);
	}

	printf("... test complete!\n");
	return EXIT_SUCCESS;
}

```

**Comment by pshipton** [comment]
@tajila @gacholio fyi

**Comment by tajila** [comment]
@gacholio can you please take a look at this

**Comment by gacholio** [comment]
The only reason for the destroy to fail is that there are still threads running. @g-pechorin Can you please run your example with `-verbose:shutdown` - this will tell us what the problematic threads are.

**Comment by gacholio** [comment]
Tried a random JDK19 build, which results in:
```
JVMJ9VM094I Thread "Common-Cleaner" is still alive after running the shutdown hooks.
```

**Comment by gacholio** [comment]
This is a problem in the JCL, not the VM itself.

**Comment by gacholio** [comment]
This looks a lot like https://github.com/eclipse-openj9/openj9/issues/15453 which proports to be fixed. @tajila

**Comment by pshipton** [comment]
OpenJ9 added a system property to work around this that is used in testing `-Dibm.java9.forceCommonCleanerShutdown=true`. It was added before OpenJ9 was opened sourced so there is no issue or PR here for it, but Tobi made the change: "This patch manually empties the cleaner's queues and interrupts it so it can unblock and exit its run loop.".

**Comment by pshipton** [comment]
@g-pechorin have you tried your test with Hotspot / OpenJDK ?

**Comment by g-pechorin** [comment]
I tried (the above approach) with OpenJDK (and Oracle's JDK about two weeks ago) but, the first `JNI_CreateJavaVM` call caused a segfault.

**Comment by g-pechorin** [comment]
@gacholio 



I've rewritten the test so that it works with a `.cpp` and a `.bat` file.

> https://gist.github.com/g-pechorin/2d5a332b142d87c6e199fd4ca6af59e3

I changed the tests to treat the assertions as warnings and continue if they failed ... and it seems to "run" fine, but, still returns those error messages.

> ```
> starting loop 0 ...
> Thread "Common-Cleaner" is still alive after running the shutdown hooks.
> EXPECTED ?FAILED? JNI_OK == destroy_ret
>
>         loop 0 FINISHED
>
>
>
> starting loop 1 ...
> EXPECTED ?FAILED? JNI_OK == create_ret
> EXPECTED ?FAILED? JNI_OK == destroy_ret
>
>         loop 1 FINISHED
>
>
>
> starting loop 2 ...
> EXPECTED ?FAILED? JNI_OK == create_ret
> EXPECTED ?FAILED? JNI_OK == destroy_ret
>
>         loop 2 FINISHED
>
>
>
> starting loop 3 ...
> EXPECTED ?FAILED? JNI_OK == create_ret
> EXPECTED ?FAILED? JNI_OK == destroy_ret
>
>         loop 3 FINISHED
>
>
>
> starting loop 4 ...
> EXPECTED ?FAILED? JNI_OK == create_ret
> EXPECTED ?FAILED? JNI_OK == destroy_ret
>
>         loop 4 FINISHED
```

@pshipton 

When I added in the `"-Dibm.java9.forceCommonCleanerShutdown=true"` option it worked WITH NO errors for the first loop, but, exited during the second one.

```
> starting loop 0 ...
> 
>         loop 0 FINISHED
> 
> 
> 
> starting loop 1 ...
> Error: Couldn't get memory categories from thread library.
> EXPECTED ?FAILED? JNI_OK == create_ret
```

**Comment by gacholio** [comment]
It looks like we don't close some libraries on destroy, which means some globals are not destroyed and recreated in subsequent VM invocations. I think the thread library may be running out of space when creating the memory categories repeatedly.

**Comment by gacholio** [comment]
@g-pechorin Please try a current build to see if this resolves your issue. If not, the follow-on issue (#17364) may also need to be resolved.

**Comment by pshipton** [comment]
I assume Windows, not sure what version. Latest nightly builds for 11, 17:

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_windows_Nightly/563/OpenJ9-JDK11-x86-64_windows-20230511-203043.tar.gz
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_x86-64_windows_Nightly/504/OpenJ9-JDK17-x86-64_windows-20230511-191036.tar.gz

**Comment by g-pechorin** [comment]
Same results.
```
openjdk 17.0.8-internal 2023-07-18
OpenJDK Runtime Environment (build 17.0.8-internal+0-adhoc.jenkins.buildjdk17x86-64windowsnightly)
Eclipse OpenJ9 VM (build master-8aa867692af, JRE 17 Windows 10 amd64-64-Bit Compressed References 20230511_504 (JIT enabled, AOT enabled)
OpenJ9   - 8aa867692af
OMR      - 779c51b9568
JCL      - fb7ca049391 based on jdk-17.0.8+2)
Hello World!


starting loop 0 ...
Thread "Common-Cleaner" is still alive after running the shutdown hooks.
EXPECTED ?FAILED? JNI_OK == destroy_ret

        loop 0 FINISHED



starting loop 1 ...
EXPECTED ?FAILED? JNI_OK == create_ret
EXPECTED ?FAILED? JNI_OK == destroy_ret

        loop 1 FINISHED



starting loop 2 ...
EXPECTED ?FAILED? JNI_OK == create_ret
EXPECTED ?FAILED? JNI_OK == destroy_ret

        loop 2 FINISHED



starting loop 3 ...
EXPECTED ?FAILED? JNI_OK == create_ret
EXPECTED ?FAILED? JNI_OK == destroy_ret

        loop 3 FINISHED



starting loop 4 ...
EXPECTED ?FAILED? JNI_OK == create_ret
EXPECTED ?FAILED? JNI_OK == destroy_ret

        loop 4 FINISHED
```

**Comment by gacholio** [comment]
That looks like a run without the `-Dibm.java9.forceCommonCleanerShutdown=true` option. This case will always result in failure since the initial destroy fails, making all subsequent create attempts fail.

The case I'm hoping to have fixed is:
```
Error: Couldn't get memory categories from thread library.
EXPECTED ?FAILED? JNI_OK == create_ret
```

**Comment by g-pechorin** [comment]
I re-ran it with the JavaVMOption `-Dibm.java9.forceCommonCleanerShutdown=true` set and `18.0.2.1` couldn't create the JVM a second time.

The `jvm` and `env` pointers from `JNI_CreateJavaVM()` are both null.

So `-Dibm.java9.forceCommonCleanerShutdown=true` fixes the first shutdown BUT after that a second instance cannot be created; the situation is "worse"

**Comment by g-pechorin** [comment]
```

starting loop 0 ...
creation call 0 made
        jvm=2318886113056
        env=109056

        loop 0 FINISHED



starting loop 1 ...
Error: Couldn't get memory categories from thread library.
EXPECTED !FAILED! JNI_OK == create_ret
creation call 1 made
        jvm=0
        env=0
REQUIRED !FAILED! jvm && env

C:\Users\peter\Desktop\2d5a332b142d87c6e199fd4ca6af59e3-d7bbf1e7cc3eecd5c3571e9f9fdd00c3f1e9de61>java --version
openjdk 18.0.2 2022-07-19
IBM Semeru Runtime Open Edition 18.0.2.1 (build 18.0.2+9)
Eclipse OpenJ9 VM 18.0.2.1 (build openj9-0.33.1, JRE 18 Windows 10 amd64-64-Bit Compressed References 20220817_36 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - 8406c39ea29 based on jdk-18.0.2+9)
```

**Comment by gacholio** [comment]
That VM appears to be from 2022, so it certainly does not contain the fix.

**Comment by g-pechorin** [comment]
"derp" sorry - I'll check it against ... whatever is "latest" later

**Comment by g-pechorin** [comment]
@gacholio 

i tried it again ... same thing ...


|build	|forceCommonCleanerShutdown	|loop			|result
|---	|----------					|---------		|----------
|jdk19	|true						| on second loop|`Error: Couldn't get memory categories from thread library.`
|		|							| 				|`JNI_CreateJavaVM()` does not return `JNI_OK`
|		|							| 				|`jni` and `env` pointers are `null`
|		|							| 				|
|jdk19	|false						| on first loop	|`Thread "Common-Cleaner" is still alive after running the shutdown hooks.`
|		|							| on second loop|`DestroyJavaVM()` does not return `JNI_OK`
|		|							| 				|`JNI_CreateJavaVM()` does not return `JNI_OK`
|		|							| 				|`jni` and `env` pointers are `null`
|		|							| 				|
|jdk11	|true						| on second loop|`Error: Couldn't get memory categories from thread library.`
|		|							| 				|`JNI_CreateJavaVM()` does not return `JNI_OK`
|		|							| 				|`jni` and `env` pointers are `null`
|		|							| 				|
|jdk11	|false						| on first loop	|`Thread "Common-Cleaner" is still alive after running the shutdown hooks.`
|		|							| on second loop|`DestroyJavaVM()` does not return `JNI_OK`
|		|							| 				|`JNI_CreateJavaVM()` does not return `JNI_OK`
|		|							| 				|`jni` and `env` pointers are `null`

**Comment by g-pechorin** [comment]
same with the JDK11 build from this morning. if the "force shutdown" is true then it can't create a second instance of the VM

```

starting loop 0 ...
creation call 0 made
        jvm=2538152435584
        env=109056

        loop 0 FINISHED



starting loop 1 ...
Error: Couldn't get memory categories from thread library.
EXPECTED !FAILED! JNI_OK == create_ret
creation call 1 made
        jvm=0
        env=0
REQUIRED !FAILED! jvm && env

C:\Users\peter\Desktop\j9\test
λ java --version
openjdk 11.0.20-internal 2023-07-18
OpenJDK Runtime Environment (build 11.0.20-internal+0-adhoc.jenkins.buildjdk11x86-64windowsnightly)
Eclipse OpenJ9 VM (build master-1b94cba4cc3, JRE 11 Windows 10 amd64-64-Bit Compressed References 20230526_574 (JIT enabled, AOT enabled)
OpenJ9   - 1b94cba4cc3
OMR      - 779c51b9568
JCL      - 99f12e84e9e based on jdk-11.0.20+2)
```



starting loop 0 ...
creation call 0 made
        jvm=2431735865248
        env=109056
Thread "Common-Cleaner" is still alive after running the shutdown hooks.
EXPECTED !FAILED! JNI_OK == destroy_ret

        loop 0 FINISHED



starting loop 1 ...
EXPECTED !FAILED! JNI_OK == create_ret
creation call 1 made
        jvm=0
        env=0
REQUIRED !FAILED! jvm && env

C:\Users\peter\Desktop\j9\test
λ java --version
openjdk 11.0.20-internal 2023-07-18
OpenJDK Runtime Environment (build 11.0.20-internal+0-adhoc.jenkins.buildjdk11x86-64windowsnightly)
Eclipse OpenJ9 VM (build master-1b94cba4cc3, JRE 11 Windows 10 amd64-64-Bit Compressed References 20230526_574 (JIT enabled, AOT enabled)
OpenJ9   - 1b94cba4cc3
OMR      - 779c51b9568
JCL      - 99f12e84e9e based on jdk-11.0.20+2)
```

**Comment by gacholio** [comment]
I've reproduced this in a debug VM and it actually has nothing to do with libaries - I initially thought the memory category storage was managed in the thread library, but it's actually in the JVM library itself.

I'm looking into resetting the categories on destroy.

A probable workaround until I can get a proper fix in would be to open and close the JVM library inside the loop.

**Comment by g-pechorin** [comment]
Ooh! That workaround works for my use case. That might work with other JVMs as well.

Thank you

I am excited about that being an option - thank you (... and sorry that I've let work/life prevent me from pursuing this)
