### ISSUE TITLE
Minecraft server crashes with latest version of OpenJ9

### ISSUE THREAD

**Issue by Zilacon** [eclipse-openj9/openj9#17294]
I havent updated in a while, so figured id do an update. However upon starting my servers with the new build multiple servers started crashing from many errors. Going back to the previous build booted without issues.

Crash reports:
[crash-2023-04-26_12.31.46-server.txt](https://github.com/eclipse-openj9/openj9/files/11336815/crash-2023-04-26_12.31.46-server.txt)
[crash-2023-04-26_12.54.28-server.txt](https://github.com/eclipse-openj9/openj9/files/11336816/crash-2023-04-26_12.54.28-server.txt)

Console logs:
[message.txt](https://github.com/eclipse-openj9/openj9/files/11336818/message.txt)

Old OJ9: 1.8.0_302-internal-202105071818-b01
New OJ9:  1.8.0_362-b09

Running Linux x64 Lubuntu, and using Catserver for the server software on version 1.12.2 of minecraft.

**Comment by pshipton** [comment]
This isn't easily diagnosed. Without somebody who understands the Minecraft server debugging the problem, I think we'd need to try and isolate what changed to cause it.

1) Does it work with Hotspot (Adoptium) of the same version 1.8.0_362-b09, if not then it's not a OpenJ9 problem.
2) If it's caused by OpenJ9, can you first narrow it down to which build between 302 and 362 the problem first appears.

**Comment by Zilacon** [comment]
The only versions we have to test are whats available on IBM's site.
302 works, but 312 does not. So this seems to be an old issue.

**Comment by pshipton** [comment]
What about Adoptium / Temurin builds? 
https://adoptium.net/temurin/archive/?version=8

**Comment by Zilacon** [comment]
> 

Just tested adoptium build 312 and the server still crashed, adoptium 302 didnt crash.

**Comment by pshipton** [comment]
That implies the change causing the problem is with OpenJDK and not something from OpenJ9.

**Comment by Zilacon** [comment]
So should i make a issue over there then?

**Comment by pshipton** [comment]
Yes, if the problem is caused by OpenJDK changes then the fix needs to come from there as well.

**Comment by Zilacon** [comment]
Ah i cant, theres no issues tab over there...

**Comment by pshipton** [comment]
I found https://dev.karakun.com/rico/2021/02/22/openjdk-bug-tracker.html perhaps this helps.

**Comment by Zilacon** [comment]
This looks out of my knowledge capabilities...
I guess im stuck on 302 forever then...
Was really hoping you guys could fix it since people like me can actually report and communicate with your team.
