### ISSUE TITLE
1TIDMPDURATION always returns 64d on Windows

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9#17319]
Java -version output
--------------------

```
java -version
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Windows 11 amd64-64-Bit Compressed References 20230117_367 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```

Summary of problem
------------------

On Windows, the new java dump line `1TIDMPDURATION` added by PR #15964 incorrectly returns a constant `64d`:

```
1TIDMPDURATION Approximate time to produce this dump: 64d ms
```

[javacore.20230502.061258.26772.0001.txt](https://github.com/eclipse-openj9/openj9/files/11372537/javacore.20230502.061258.26772.0001.txt)

**Comment by kgibm** [comment]
@keithc-ca I can take a look at this but before I do, have you seen issues with printf and `OMR_PRId64` on Windows before?

**Comment by kgibm** [comment]
Maybe it should have been `PRIu64`?

**Comment by keithc-ca** [comment]
Yes, if we were talking to `sprintf()` it should have used `OMR_PRIu64` instead of `OMR_PRId64`. Here it is ultimately using `omrstr_vprintf()` so the format we want is `"%llu"`.

**Comment by kgibm** [comment]
Okay, thanks. I'll test this out and open a PR.

**Comment by keithc-ca** [comment]
`omrstr_vprintf()` doesn't handle `%I` so that part just disappears.

**Comment by kgibm** [comment]
Given the block on building on Windows 11, could I just submit a PR and one of you could spark a Jenkins build and then I could test that?

**Comment by pshipton** [comment]
You don't need a PR, if you have a branch on your fork let me know what it is and I will kick a build with it. You might want to rebase it on the latest.

**Comment by pshipton** [comment]
Do you need to build on Windows? It's easier to build on Linux if you want to set that up.

**Comment by kgibm** [comment]
> You don't need a PR, if you have a branch on your fork let me know what it is and I will kick a build with it. You might want to rebase it on the latest.

Thanks, please build this branch (rebased on latest): https://github.com/kgibm/openj9/tree/issue17319

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/396/

**Comment by kgibm** [comment]
Thanks Peter.

Tested the build ([with `OMR_PRIu64`](https://github.com/eclipse-openj9/openj9/commit/394052dbefb61f6dd7783c8a5dcfe4a9e5ec5ffa)) but now it just shows:

```
Approximate time to produce this dump: 64u ms
```

@keithc-ca Thoughts?

**Comment by keithc-ca** [comment]
That code should not use any of the `OMR_PRIxxx` macros; the format string is interpreted by OMR, not `printf` and friends. It should use `"%llu"` like line 681.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/397/

**Comment by keithc-ca** [comment]
> I notice another part of the code has the same issue; I presume I should update that as well:

Yes, please and thanks.
