### ISSUE TITLE
cent7-x64-2 missing /home/jenkins/set_gcc_10.3.0_env

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17325]
https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_linux_OMR/345
[cent7-x64-2](https://openj9-jenkins.osuosl.org/computer/cent7-x64-2)
`/home/jenkins/workspace/Build_JDK17_x86-64_linux_OMR@tmp/durable-ea9a34c2/script.sh: line 1: /home/jenkins/set_gcc_10.3.0_env: No such file or directory`

Disabled the machine.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
CRIU not there either.

**Comment by AdamBrousseau** [comment]
I think the path forward here is to scp the known missing components from a working machine and then start launching builds until it seems ok.
@mardekanian

**Comment by pshipton** [comment]
There are jobs still running and failing on this machine. I may disable it again.
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.system_x86-64_linux_Nightly/1/console

**Comment by pshipton** [comment]
Disabled it.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_s390x_linux_Nightly/574/console

**Comment by AdamBrousseau** [comment]
Think this is obsolete now that all compiles are in docker. Machine is enabled.
