### ISSUE TITLE
TestJps_0_FAILED testJvmArguments AssertionError: Missing argument: -Dfoo=bar

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17332]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.functional_x86-64_windows_testList_1/328/)(`win19x64-fips2-1`):
```
java version "17.0.7" 2023-04-18
IBM Semeru Runtime Certified Edition 17.0.7.0-rc1 (build 17.0.7+7)
Eclipse OpenJ9 VM 17.0.7.0-rc1 (build v0.38.0-release-d57d05932, JRE 17 Windows Server 2019 amd64-64-Bit Compressed References 20230418_385 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 47464180951 based on jdk-17.0.7+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=TestJps_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_extended.functional_x86-64_windows&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F385%2Fibm-semeru-certified-jdk_x64_windows_17.0.7.0-rc1.zip+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-openj9-IBM%2F385%2Fibm-semeru-certified-testimage_x64_windows_17.0.7.0-rc1.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v0.9.7-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.38.0-release&amp;OPENJ9_BRANCH=v0.38.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=v0.9.7-release&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.38.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=347&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-03T05:44:21.000Z] variation: NoOptions
[2023-05-03T05:44:21.393Z] JVM_OPTIONS:  

[2023-05-03T05:46:34.335Z] FAILED: testJvmArguments
[2023-05-03T05:46:34.335Z] java.lang.AssertionError: Missing argument: -Dfoo=bar
[2023-05-03T05:46:34.335Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2023-05-03T05:46:34.335Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2023-05-03T05:46:34.335Z] 	at org.openj9.test.attachAPI.TestJps.testJvmArguments(TestJps.java:120)
[2023-05-03T05:46:34.335Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2023-05-03T05:46:34.336Z]     TestJps
[2023-05-03T05:46:34.336Z]     Tests run: 6, Failures: 1, Skips: 0
[2023-05-03T05:46:34.336Z] ===============================================
[2023-05-03T05:46:34.336Z] 
[2023-05-03T05:46:34.336Z] 
[2023-05-03T05:46:34.336Z] ===============================================
[2023-05-03T05:46:34.336Z] GeneralTest suite
[2023-05-03T05:46:34.336Z] Total tests run: 6, Failures: 1, Skips: 0
[2023-05-03T05:46:34.336Z] ===============================================
[2023-05-03T05:46:34.336Z] 
[2023-05-03T05:46:34.336Z] -----------------------------------
[2023-05-03T05:46:34.336Z] TestJps_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/32655/)

**Comment by pshipton** [comment]
The test fix https://github.com/eclipse-openj9/openj9/pull/16817 is not included in 0.38
