### ISSUE TITLE
zLinux ASSERTION FAILED VMAccess.cpp:355: (0 == ((vmThread)->publicFlags & J9_PUBLIC_FLAGS_VM_ACCESS))

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17334]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/535/
java/lang/ThreadGroup/Suspend.java
```
20:02:29  00:01:29.274 0x17d7400    j9vm.228    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK8_s390x_linux_Nightly/openj9/runtime/vm/VMAccess.cpp:355: (0 == ((vmThread)->publicFlags & J9_PUBLIC_FLAGS_VM_ACCESS))
```

This was also seen in the last OMR acceptance build, see https://openj9.slack.com/archives/CDS7QE9HB/p1683147702449159

Changes from last nightly build:
https://github.com/eclipse-openj9/openj9/compare/275bb5a28...0fe9c4b0381
https://github.com/eclipse-openj9/openj9-omr/compare/7ddb743eace...5dcc2f28955

Since it was seen in OMR acceptance we can rule out some OpenJ9 changes. Also the OMR changes were already tested in the previous OMR acceptance without any failures.
https://github.com/eclipse-openj9/openj9/compare/275bb5a28...aa5727ef44b

I think https://github.com/eclipse-openj9/openj9/pull/16943 must be the cause. It changes some non Java 19 specific code in Java_java_lang_Thread_resumeImpl

@dipak-bagadiya @babsingh Unless there is a quick fix we should revert this.

**Comment by babsingh** [comment]
I am in favour of reverting it. We did see a similar error in JDK19 but not in JDK20: https://github.com/eclipse-openj9/openj9/pull/16943#issuecomment-1525989564. @dipak-bagadiya was unable to reproduce the error with JDK20 locally. We will push the change once this failure is resolved.

**Comment by pshipton** [comment]
The failures are all in jdk8, 11, 17. For the record we saw the following failures. There will be more in the nightly build but it's probably not worth listed them since the following is a good representation.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_OMR/436/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR/435/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_OMR/320/

Failures in PR builds:
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Personal/285/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Personal/35/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Personal/276/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/19/

**Comment by pshipton** [comment]
Since the change is reverted, this can be closed.
