### ISSUE TITLE
OpenJDK jdk8 java/util/stream failures

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17337]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly/414/
java/util/stream/test/org/openjdk/tests/java/util/stream/TabulatorsTest.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_Nightly/534/
java/util/stream/test/org/openjdk/tests/java/util/stream/SliceOpTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/518/
    java/util/stream/test/org/openjdk/tests/java/util/stream/SliceOpTest.java
    java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java
    java/util/stream/test/org/openjdk/tests/java/util/stream/TabulatorsTest.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/522/
java/util/stream/test/org/openjdk/tests/java/util/stream/SliceOpTest.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly/514/
java/util/stream/test/org/openjdk/tests/java/util/stream/MapOpTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/SliceOpTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/TabulatorsTest.java

Changes from previous nightly build:
https://github.com/eclipse-openj9/openj9/compare/275bb5a28...0fe9c4b0381
https://github.com/eclipse-openj9/openj9-omr/compare/7ddb743eace...5dcc2f28955

Maybe related to https://github.com/eclipse-openj9/openj9/issues/17334 for which the change was already backed out.

**Comment by pshipton** [comment]
In a build https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/390/ without https://github.com/eclipse-openj9/openj9/pull/16943, the failures in jdk_util seem to be gone, although the build is still running.
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/390/

**Comment by jdmpapin** [comment]
I suppose you mean in a build without eclipse/omr#6959 (or perhaps with neither it nor #16943). I see the commit for the build is https://github.com/pshipton/openj9-omr/commit/ea3c8f02b617a195bee103e42f658fd8ad975c6f, which reverts eclipse/omr#6959. I'll open a revert PR in OMR.

**Comment by jdmpapin** [comment]
Opened eclipse/omr#6977 to revert eclipse/omr#6959

**Comment by pshipton** [comment]
https://github.com/eclipse/omr/pull/6977 is merged so I'll close this, although it still needs to go through acceptance.
