### ISSUE TITLE
New NullRestricted Attribute in Project Valhalla

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#17340]
In the last spec: https://cr.openjdk.org/~dlsmith/jep401/jep401-20230428/specs/flattened-heap-jvms.html, a NullRestricted attribute is introduced. 

It indicates that the field cannot be null. `putfield` and `putstatic` will throw NPE if there is an attempt to assigned null to such fields. The null restricted field needs to be initialized to the default instance.

**Comment by hangshao0** [comment]
FYI @theresa-m

**Comment by hangshao0** [comment]
> can you point me to where this is happening in the code?

The question is regarding https://github.com/eclipse-openj9/openj9/issues/17340#issuecomment-1534954375, i.e. where Q type is initialized to the default instance ?

**Comment by theresa-m** [comment]
> > can you point me to where this is happening in the code?
> 
> The question is regarding [#17340 (comment)](https://github.com/eclipse-openj9/openj9/issues/17340#issuecomment-1534954375), i.e. where Q type is initialized to the default instance ?

yes.

**Comment by hangshao0** [comment]
The default instance of a value type is allocated here:

https://github.com/eclipse-openj9/openj9/blob/5567b8c768d6212fdf0113ed85a6c7b82be5eb0f/runtime/vm/ClassInitialization.cpp#L521-L535

The Q type instance fields are set here:
https://github.com/eclipse-openj9/openj9/blob/5567b8c768d6212fdf0113ed85a6c7b82be5eb0f/runtime/gc_modron_startup/mgcalloc.cpp#L518
https://github.com/eclipse-openj9/openj9/blob/5567b8c768d6212fdf0113ed85a6c7b82be5eb0f/runtime/vm/ValueTypeHelpers.cpp#L78-L96

`defaultValueWithUnflattenedFlattenables()` uses the default instance to set the fields if they are not flattened (inlined). Note the `flattenedClassCache` struct has all the J9Class of the Q type fields.

**Comment by theresa-m** [comment]
The remaining tasks for this issue are:
Class verification + write to ROM class https://github.com/eclipse-openj9/openj9/pull/17781
bytecode checks (putfield and putstatic) TODO
cfdump support TODO
ddr support TODO
functional tests TODO

**Comment by theresa-m** [comment]
@hangshao0 when you have some time, are there any other class verification checks you think should be added for NullRestricted? See the previous comment for all prs that are open against this issue.

**Comment by hangshao0** [comment]
I haven't reviewed https://github.com/eclipse-openj9/openj9/pull/18030 yet. But notice the following in the spec:


Section 5.3.5.
`5. For each non-static field of C declared with a NullRestricted attribute......the class or interface named by the field's type must be a value class with an ImplicitCreation attribute whose ACC_DEFAULT flag is set. If not, loading throws an IncompatibleClassChangeError` 

Section 5.4.2
`1. For each static field of C declared with a NullRestricted attribute......The resolved type must be of a value class with an ImplicitCreation attribute whose ACC_DEFAULT flag set. If not, preparation fails with an IncompatibleClassChangeError.`

Section 6.5
`if the value to store is null and the resolved field is declared with a NullRestricted attribute, the withfield instruction throws a NullPointerException.`

**Comment by theresa-m** [comment]
Thanks, https://github.com/eclipse-openj9/openj9/pull/18030 should cover the first two but I didn't notice there was a specific error to be thrown. I'll update that.

**Comment by theresa-m** [comment]
What about this one? Section 6.5.

```
The initial value of any instance field declared with a NullRestricted attribute is the initial instance of the field's class. The initial value of any instance field of a primitive type is the default value of the type ([2.3](https://docs.oracle.com/javase/specs/jvms/se16/html/jvms-2.html#jvms-2.3)). The initial value of any other instance field is null.
```

**Comment by theresa-m** [comment]
This issue will be closed by https://github.com/eclipse-openj9/openj9/pull/19995. Further null restricted error handling will be related to CheckedType support https://github.com/eclipse-openj9/openj9/issues/19764
