### ISSUE TITLE
cmdLineTester_criu_jitPostRestore Check Verbose Log - vlog: No such file or directory

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17367]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/454
cmdLineTester_criu_jitPostRestore_1
```
*** Starting test suite: J9 Criu Command-Line Post Restore JIT Option Tests ***
Testing: Generate Verbose Log
Test start time: 2023/05/08 22:22:08 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java " -Xjit:count=0 " org.openj9.criu.OptionsFileTest "JitOptionsTest -Xjit:verbose={CheckpointRestore},vlog=vlog" 1 false
Time spent starting: 93 milliseconds
Time spent executing: 39018 milliseconds
Test result: PASSED

Testing: Check Verbose Log
Test start time: 2023/05/08 22:22:47 Eastern Standard Time
Running command: cat vlog
Time spent starting: 7 milliseconds
Time spent executing: 11 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: vlog: No such file or directory
>> Success condition was not found: [Output match: CHECKPOINT RESTORE: Ready for restore]
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@dsouzai Please take a look

**Comment by pshipton** [comment]
Seems related so I'll add it here.

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/475
cmdLineTester_criu_jitserverPostRestore_0
```
Testing: Check Verbose Log
Test start time: 2023/05/10 01:01:51 Coordinated Universal Time
Running command: cat vlog
Time spent starting: 7 milliseconds
Time spent executing: 18 milliseconds
Test result: FAILED
Output from test:
 [OUT] #CHECKPOINT RESTORE: Ready for restore
>> Required condition was found: [Output match: CHECKPOINT RESTORE: Ready for restore]
>> Success condition was not found: [Output match: Connected to a server]
```

**Comment by dsouzai** [comment]
I believe this

> https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/475 cmdLineTester_criu_jitserverPostRestore_0
> 
> ```
> Testing: Check Verbose Log
> Test start time: 2023/05/10 01:01:51 Coordinated Universal Time
> Running command: cat vlog
> Time spent starting: 7 milliseconds
> Time spent executing: 18 milliseconds
> Test result: FAILED
> Output from test:
>  [OUT] #CHECKPOINT RESTORE: Ready for restore
> >> Required condition was found: [Output match: CHECKPOINT RESTORE: Ready for restore]
> >> Success condition was not found: [Output match: Connected to a server]
> ```

is an instance of https://github.com/eclipse-openj9/openj9/issues/17324. The other one looks to be the same as this issue; hopefully we figure out a way forward in https://github.com/eclipse-openj9/openj9/issues/17368.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly_testList_0/527/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_0/478 - [cent7-x64-5](https://openj9-jenkins.osuosl.org/computer/cent7-x64-5)
cmdLineTester_criu_jitserverPostRestore_1
```
Testing: Check Verbose Log
Test start time: 2023/06/12 22:14:41 Atlantic Standard Time
Running command: cat vlog
Time spent starting: 4 milliseconds
Time spent executing: 7 milliseconds
Test result: FAILED
Output from test:
 [ERR] cat: vlog: No such file or directory
>> Required condition was not found: [Output match: CHECKPOINT RESTORE: Ready for restore]
>> Success condition was not found: [Output match: Connected to a server]
```
