### ISSUE TITLE
Can CRIU interop with CRAC

### ISSUE THREAD

**Issue by AngeloRubens** [eclipse-openj9/openj9#17420]
hi all,

can openj9 support jdk Crac project by Criu Feature?

**Comment by AngeloRubens** [comment]
for compatibility feature, like -XX:[+|-]IgnoreUnrecognizedVMOptions compatibility from openjdk and openj9...

**Comment by DanHeidinga** [comment]
There are a lot of similarities between OpenJ9's CRIU support and OpenJDK's Project CRaC but they aren't in the realm of mapping from one command line option to the other.

Both use CRIU to take a checkpoint of the running JVM and then to restore it later.  Both have a "lifecycle api" that allows hooks to run before the checkpoint and after the restore to fix up the state.

But the model for executing those hooks is different:
* CRaC allows all threads to continue to execute while lifecycle api hooks are running which exposes a lot of concurrency issues between "normal operation" and the "fixup code".  
* OpenJ9 instead enters into "single threaded mode" and only allows a single thread to execute the lifecycle api hooks.  All other threads are paused.  This makes the concurrency model simpler and ensures a more consistent environment after the hooks are complete but comes at the cost of potential deadlocks.

Both use their lifecycle apis to fix up the OpenJDK classlibrary so mapping there is covered.  But user code that wants to operate with either OpenJ9 CRIU or OpenJDK CRaC needs to interoperate with one or the others lifecycle apis.  The way those apis are exposed and used - and thought about ie: concurrency - are different and require different approaches by users.

I'm sure there's other differences but this should be sufficient to show that mapping one to the other isn't a simple operation unfortunately.  

If you're interested in OpenJ9 CRIU - or have been playing with CRaC - we'd love to hear the use case and hear about how the checkpoint/restore is helping.  And what improvements / enhancements / pain points you might have.

**Comment by AngeloRubens** [comment]
my contribution just wanted to have a standard api to allow apps running on the jvm to interact with CRIU in the same way for both openj9 and open-jdk.

**Comment by tajila** [comment]
@AngeloRubens you may be interested in https://github.com/OpenLiberty/open-liberty/issues/25594

**Comment by tajila** [comment]
@AngeloRubens OpenJ9 now has support for `-XX:CRaCCheckpointTo=` and `-XX:CRaCRestoreFrom=` as well as CRAC org.crac APIs.
