### ISSUE TITLE
SPDX License Identifier in file headers is invalid

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-openj9/openj9#17429]
I found the following `SPDX-License-Identifier` in your [template](https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md#copyright-notice-and-licensing-requirements) and at least some of the source files in this repository.

`EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception`

The expression is not correct SPDX and so can't be processed correctly by an SPDX parser. The only serious problem is that `Assembly-exception` is not the correct identifier for the Assembly Exception. It should be `OpenJDK-assembly-exception-1.0`. Less serious, `GPL-2.0` is deprecated and `LicenseRef-GPL-2.0` is a form that you use when the license doesn't have an SPDX identifier; both of these should be `GPL-2.0-only`.

The actual expression should be something like this:

`EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0`

**Comment by DanHeidinga** [comment]
Thanks @waynebeaton for catching that and proposing the fixed form.  Are we on the clock to fix this (ie:must fix by ____) or can it be addressed as we run across it?

@mstoodle can you get someone in your org to look at this?

**Comment by DanHeidinga** [comment]
Temporarily assigning this to the 0.40 release while we figure out the timeline for addressing it

**Comment by mstoodle** [comment]
> @mstoodle can you get someone in your org to look at this?

Yup.

**Comment by waynebeaton** [comment]
>  Are we on the clock to fix this

No urgency.
