### ISSUE TITLE
UpgModPath_FAILED java.lang.module.FindException: Hash of java.logging differs to expected hash recorded in java.base

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17427]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.system_aarch64_linux_testList_0/22/)(`cent7-aarch64-6`):
```
openjdk version "20.0.1-beta" 2023-04-18
IBM Semeru Runtime Open Edition 20.0.1+9-202305170026 (build 20.0.1-beta+9-202305170026)
Eclipse OpenJ9 VM 20.0.1+9-202305170026 (build master-22b17b83e, JRE 20 Linux aarch64-64-Bit Compressed References 20230517_27 (JIT enabled, AOT enabled)
OpenJ9   - 22b17b83e
OMR      - 779c51b95
JCL      - ced3ff7a3 based on jdk-20.0.1+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=UpgModPath_ExpImg_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk20_j9_sanity.system_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk20u%2Fjdk20u-linux-aarch64-openj9%2F27%2Fibm-semeru-open-jdk_aarch64_linux_JDK20U_2023-05-16-23-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=20&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk20&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=22&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-05-17T05:33:07.141Z] variation: Mode150
[2023-05-17T05:33:07.141Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-05-17T05:33:17.726Z] OT27 java.lang.module.FindException: Hash of java.logging (fca4227963e46539ebdb3d734a39a90266030841bdd7ac871a1ab560113652d9) differs to expected hash (2c43f38f707393703f00b1c2db5ad6db78f16e7e73398a27f9061da3d8d51b6d) recorded in java.base

[2023-05-17T05:36:17.689Z] UpgModPath_JarImg_0_FAILED
```

[JDK20 aarch64_linux UpgModPath_ExpImg_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.system_aarch64_linux_testList_0/22/)
[JDK20 aarch64_linux UpgModPath_Jar_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.system_aarch64_linux_testList_1/22/)
[JDK20 aarch64_linux UpgModPath_Exp_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk20_j9_sanity.system_aarch64_linux_testList_2/22/)

Also seen on [JDK11 aarch64_linux UpgModPath_Jar_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.system_aarch64_linux_testList_2/305/) [JDK17 s390x_linux UpgModPath_JarImg_0_FAILED](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.system_s390x_linux_testList_2/397/)

**Comment by pshipton** [comment]
@JasonFengJ9 the tests seem to be passing now, can this be closed?

**Comment by JasonFengJ9** [comment]
Sure, closing..
