### ISSUE TITLE
Inconsistent description of a JIT option: compilationDelayTime

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#17431]
Specifying the time in `-Xjit:compilationDelayTime=n` is in seconds according to the description of the option.  But the value is handled as milliseconds.
Which is correct, seconds or milliseconds?

The variable declaration and the option description:
https://github.com/eclipse-openj9/openj9/blob/7d5d62a90089c3a46d20382174bc5d83bfe37e33/runtime/compiler/control/J9Options.cpp#L213
https://github.com/eclipse-openj9/openj9/blob/7d5d62a90089c3a46d20382174bc5d83bfe37e33/runtime/compiler/control/J9Options.cpp#L875-L876

Actual usage:
https://github.com/eclipse-openj9/openj9/blob/7d5d62a90089c3a46d20382174bc5d83bfe37e33/runtime/compiler/control/HookedByTheJit.cpp#L834-L835
(`_compilationDelayTime` is compared against `compInfo->getPersistentInfo()->getElapsedTime()`, which returns a millisecond value)

**Comment by knn-k** [comment]
In addition, there is a similar JIT option in OMR: `-Xjit:delayCompile=n`.
https://github.com/eclipse/omr/blame/bbe1ebce0ecbe0115517261c92d159c3ef14dc2e/compiler/control/OMROptions.cpp#L230-L231

Is there any background of having redundant options?  Both of them are in the initial contributions to the projects.

**Comment by 0xdaryl** [comment]
@mpirvu

**Comment by mpirvu** [comment]
`_compilationDelayTime` is expressed in seconds, like the comment suggests. This is correctly used in rossa.cpp, but incorrectly used in HookedByTheJit.cpp. I'll open a PR to fix it.

`-Xjit:delayCompile=n` in OMR is different than `compilationDelayTime=` in OpenJ9. The former simulates the effect of expensive compilations by burning CPU for the indicated amount of ms. The latter prevents compilations from happening for the specified duration of time (in seconds) since the beginning of the JVM.

**Comment by 0xdaryl** [comment]
Do you think `delayCompile=` should be renamed?  The option name and the description (`Amount of time in ms before compile is started`) don't really match what you described above.  Maybe `delayCompilesWithCPUBurn` ?

**Comment by mpirvu** [comment]
Yes, I agree with the new name, but maybe use the singular `delayCompileWithCPUBurn` because it can be applied in a subset to a single method, e.g. `-Xjit:{method}(delayCompileWithCPUBurn=10)`

**Comment by knn-k** [comment]
I reviewed and merged #17436.
I reopen this issue for further discussion on renaming `delayCompile=`.

**Comment by knn-k** [comment]
JIT compiles many Java methods even with `compilationDelayTime=` after #17436 was merged.
They all seem to be JNI methods.

```
$ ./jdk/bin/java -Xnoaot -Xjit:compilationDelayTime=10,verbose -version
... lines omitted ...
+ (cold) java/lang/Double.longBitsToDouble(J)D @ 0000FFFF7CA0002C-0000FFFF7CA00070 OrdinaryMethod - Q_SZ=3 Q_SZI=3 QW=4 j9m=0000000000057918 bcsz=3 JNI compThreadID=0 CpuLoad=2%(0%avg) JvmCpu=0%
+ (cold) jdk/internal/reflect/Reflection.getCallerClass()Ljava/lang/Class; @ 0000FFFF7CA0008C-0000FFFF7CA001B8 OrdinaryMethod - Q_SZ=2 Q_SZI=2 QW=3 j9m=000000000003DFF8 bcsz=2 JNI compThreadID=0 CpuLoad=2%(0%avg) JvmCpu=0%
+ (cold) java/lang/System.getSysPropBeforePropertiesInitialized(I)Ljava/lang/String; @ 0000FFFF7CA001D4-0000FFFF7CA0030C OrdinaryMethod - Q_SZ=1 Q_SZI=1 QW=2 j9m=0000000000042F68 bcsz=3 JNI compThreadID=0 CpuLoad=2%(0%avg) JvmCpu=0%
+ (cold) jdk/internal/misc/Unsafe.objectFieldOffset1(Ljava/lang/Class;Ljava/lang/String;)J @ 0000FFFF7CA0032C-0000FFFF7CA00480 OrdinaryMethod - Q_SZ=0 Q_SZI=0 QW=1 j9m=0000000000036770 bcsz=4 JNI compThreadID=0 CpuLoad=2%(0%avg) JvmCpu=0%
```

**Comment by mpirvu** [comment]
Compiling JNI is normal, as there was no attempt to block them. The main purpose of `-Xjit:compilationDelayTime=10` was to allow the JVM to collect more interpreter profiling samples. Many applications enjoy a throughput boost when delaying compilations; however, we have not yet found a way to extract that throughput boost without affecting start-up and ramp-up time.

**Comment by mpirvu** [comment]
@0xdaryl  I created an OMR PR to change the name of the delayCompile option here: https://github.com/mpirvu/omr/pull/new/delayCompileWithCPUBurn

**Comment by knn-k** [comment]
Thank you for the comment.  I will look into rossa.cpp.
My purpose is to see how the startup time changes in my workload when I disable JIT compilation during startup while AOT methods are available.  Profiling shows the JIT compiler thread consumes CPU time during startup for MethodHandle-related methods (and JNI methods) even when the SCC is populated with AOT methods.

I am closing this issue as #17436 and https://github.com/eclipse/omr/pull/6997 were merged.

**Comment by mpirvu** [comment]
JNI thunks are not stored into SCC. The compiler also fails some method-handle AOT compilations, so again, we cannot take advantage of AOT.
However, in general I have seen that not allowing JIT compilation has a detrimental effect on start-up time.

**Comment by knn-k** [comment]
My target device has limited CPU resource -- Only 2 cores are available to my workload, due to the CPU affinity setting.
I didn't want the JIT compiler to occupy one of the CPU cores during startup, and wondered what would happen if I disable JIT compilation with SCC being populated.

**Comment by mpirvu** [comment]
You could definitely experiment, but in my experience, for any workload that needs a few seconds to start-up, preventing cheap compilations has an adverse effect on start-up.
