### ISSUE TITLE
Rename TR_InlinedSiteHastTableEntry to TR_InlinedSiteHashTableEntry

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#17450]
Seems like a spelling mistake that has persisted for many years.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by SurajKarmakar1** [comment]
Hey this will be my first open source contribution, i would like to work on this to start my contribution journey.

**Comment by SurajKarmakar1** [comment]
> Seems like a spelling mistake that has persisted for many years.

@0xdaryl  It will be my first contribution, would you like to direct me which folder/file/line of code ?

**Comment by SurajKarmakar1** [comment]
@0xdaryl Hey please can you look after the pull request?

**Comment by hzongaro** [comment]
Daryl 0xdaryl, I will review it

**Comment by 0xdaryl** [comment]
Thanks for contribution.  There should not be multiple PRs or commits to fix this.  A single PR/commit is all that is required.

**Comment by prajwalbandak** [comment]
Hi, if this issue is still open, Can you please assign it to me, I would like to work on it.

**Comment by prajwalbandak** [comment]
Hey @hzongaro, Can you please look after the pull request?
Link for PR : https://github.com/eclipse-openj9/openj9/pull/17846
