### ISSUE TITLE
 jvm29 abuild zOS Assertion failed at bld_zos_390/compiler/../omr/compiler/codegen/CodeGenRA.cpp:439: !containsCollectedReference || (dataSize == TR::Compiler->om.sizeofReferenceAddress())

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17465]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=60987731)(`fyrec50v`):
```
JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pmz3180sr9-20230502_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390-31-Bit 20230529_52015 (JIT enabled, AOT enabled)
OpenJ9   - ea3e958
OMR      - c04a633
IBM      - 696e9df)
JCL - 20230423_01 based on Oracle jdk8u381-b02
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
p> 20230529-16:20:56 Logging java -Xmx512M -Xms4M -Xdump:system+java:events=user -Xnocompressedrefs -Dduration=300 -cp /j9vm/ebcdic/javatest/HEAD_382595/test/SVT/stress/jltf/engine/jltf.core/lib/*:/j9vm/ebcdic/javatest/HEAD_382595/test/SVT/daa/junitsvt/classes/junitsvt.jar:/j9vm/ebcdic/javatest/HEAD_382595/test/SVT/daa/junitdev/classes/junitdev.jar -version output to java_version.txt
p> 20230529-16:20:57 JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
p> 20230529-16:20:59 Assertion failed at /j9tmp/bld_52015/bld_zos_390/compiler/../omr/compiler/codegen/CodeGenRA.cpp:439: !containsCollectedReference || (dataSize == TR::Compiler->om.sizeofReferenceAddress())
p> 20230529-16:20:59 
p> 20230529-16:20:59 	assertion failure
p> 20230529-16:20:59 compiling java/lang/ClassLoader.getSystemClassLoader()Ljava/lang/ClassLoader; at level: warm
p> 20230529-16:20:59 
p> 20230529-16:20:59 ERROR: Return code of java -version process was 14592
p> 20230529-16:20:59 Test FAILED because:
p> 20230529-16:20:59 * Return code of java -version process was 14592
```

[[zOS S390] 80 JIT_Sanity.abbs.5mins.Mode140.3](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=60987741)
[[zOS S390] 80 Load_Level_2.abbs.5mins.Mode101.5](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=60987761)
and more at [jvm.29.openj9.acceptance failures](http://vmfarm.rtp.raleigh.ibm.com/jobs_by_status.php?build_id=52015&status=FAILED&categories=17)

Tentatively set it to `blocker` since this prevents jvm29 abuild promotion.

**Comment by JasonFengJ9** [comment]
FYI @0xdaryl

**Comment by r30shah** [comment]
@Spencer-Comin Can you take a look and see if it is related to your changes to use load immediate instructions for Class and methods addresses or not?

**Comment by 0xdaryl** [comment]
Looking at all the recent OMR changes, the only consequential ones are Z specific.   @spencer-comin, could you investigate whether your changes are responsible for this issue please?

https://github.com/eclipse/omr/pull/6596/commits

@r30shah FYI

**Comment by Spencer-Comin** [comment]
Looking into it now
