### ISSUE TITLE
JEP 453: Structured Concurrency (Preview)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17487]
See [Structured Concurrency (Preview)](https://openjdk.org/jeps/453)

**Comment by pshipton** [comment]
@tajila @babsingh @fengxue-IS

**Comment by babsingh** [comment]
All current testing for structured concurrency passes in JDK20. Will keep monitoring the JEP's state periodically.

**Comment by tajila** [comment]
> All current testing for structured concurrency passes in JDK20. Will keep monitoring the JEP's state periodically.

Are all tests re-enabled?

**Comment by babsingh** [comment]
> Are all tests re-enabled?

Yes. References:
- JDK20: https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk20-openj9.txt
- JDK21: https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk21-openj9.txt

Only one RI specific test is disabled: `StructuredThreadDumpTest` (https://github.com/eclipse-openj9/openj9/issues/15278).

Current tests in JDK20: https://github.com/ibmruntimes/openj9-openjdk-jdk20/tree/openj9/test/jdk/jdk/incubator/concurrent/StructuredTaskScope

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/17487#issuecomment-1570727586: The last disabled structured concurrency OpenJDK/jtreg test was enabled through https://github.com/eclipse-openj9/openj9/pull/17709.

Closing, all OpenJDK/jtreg tests for structured concurrency pass and have been enabled.
