### ISSUE TITLE
Incorrect evaluation of x>=0

### ISSUE THREAD

**Issue by Meldexun** [eclipse-openj9/openj9#17496]
Java -version output
--------------------

```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b09)
Eclipse OpenJ9 VM (build openj9-0.36.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20230207_599 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - eebde685ec based on jdk8u362-b09)
```

Summary of problem
------------------

I got an issue report for one of my programs which was unexplainable to me. But after a lot of testing I found out that the issue only happens when an IBM Semeru OpenJ9 Java 8 JVM is used.
I was then able to write a small program which reproduces the issue consistently for me:

```Java
public static void main(String[] args) {
	while (true) {
		for (int r = 2; r < 16; r++) {
			int y = r * 2 + 1;
			int x = 1 - y / 2;
			int t = x / y;
			if (x >= 0) throw new RuntimeException();
		}
	}
}
```

The above code should never throw a RuntimeException because x is always negative. But for some reason after a few thousand iterations of the while loop `x >= 0` is `true` and a RuntimeException is thrown.

The issue only happens when `x / y` is computed right before the `x >= 0` check.

The issue does **not** happen when `-Xint` is passed as a jvm arg.

Diagnostic files
----------------

*No crash or OutOfMemory condition happening*

OutOfMemoryError: Java Heap Space
---------------------------------

*No OutOfMemory condition happening*

**Comment by pshipton** [comment]
@0xdaryl @hzongaro fyi

**Comment by BradleyWood** [comment]
Temporary workaround

```
export TR_disableNoTestEFlags=1
```

**Comment by BradleyWood** [comment]
This bug looks like a product of redundant comparison elimination optimisation. The code generator looks for opportunities to eliminate compare instructions when the result of an operation (which sets ZF and SF flags) is compared with 0. However in this particular case shown below, other operations, in this case a DIV managed to get between the SUB and the compare. I think there are two problems here:

1. The code generator does not know that the result of these flags from IDIV instruction is undefined
2. The code generator does not check if instructions modifying these flags belong to the expected IL node

```
2b c2                              sub	eax, edx		   # SUB4RegReg
89 44 24 1c                        mov	dword ptr [rsp+0x1c], eax  # S4MemReg,
                                   assocreg                        # assocreg
99                                 cdq                             # CDQAcc
                                   assocreg                        # assocreg
f7 f9                              idiv	ecx	                   # IDIV4AccReg
7d 33                              jge	Label L0019	           # JGE1
```

**Comment by 0xdaryl** [comment]
@BradleyWood : Please create an openj9-omr PR against 0.40 for this.
