### ISSUE TITLE
JEP 451: Prepare to Disallow the Dynamic Loading of Agents

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17500]
See [Prepare to Disallow the Dynamic Loading of Agents](https://openjdk.org/jeps/451)

**Comment by pshipton** [comment]
@JasonFengJ9 @tajila

**Comment by JasonFengJ9** [comment]
I can look into it to prevent the AttachAPI from loading an agent into a JVM after startup, also disable HCR/OSR as default JVM capabilities as per a related issue
* https://github.com/eclipse-openj9/openj9/issues/17085

**Comment by tajila** [comment]
@JasonFengJ9 Now that Devins PR is in, we will need to add the warning message to JDK21+ for dynamic loading of agents. Also, trace usage with `-Djdk.instrument.traceUsage`

**Comment by JasonFengJ9** [comment]
Will look into it.

**Comment by JasonFengJ9** [comment]
The changes required have been implemented, the doc issue has been created, and an automated OpenJDK test has been added & passed.

Closing as completed.
