### ISSUE TITLE
Core dump at mgcalloc.cpp:358

### ISSUE THREAD

**Issue by bachlipp** [eclipse-openj9/openj9#17501]
We are running JBoss EAP on IBM J9 / OpenJ9 JVM on IBM AIX and experience a core dump that displays the following failure in the trace file:
3XEHSTTYPE     16:45:50:684553094 GMT j9mm.107 - * ** ASSERTION FAILED ** at mgcalloc.cpp:358: ((false && (allocatedBytes == indexableOAM.getAllocateDescription()->getContiguousBytes())))

There does not seem to be a close correlation of this failure to a certain activity within the application server: The JBoss EAP logfiles show nothing special, in particular there does not seem to be any entries correlated to the crash.

Is this an issue in the JVM, caused by resource constraints or caused by an alleged issue in one of our applications deployed on the application server? Any hints and help will be greatly appreciated!

Details of our environment:
IBM AIX:
/home/oracle $ oslevel
7.2.0.0

Application Server:
JBoss EAP 7.4.3

IBM Java:
/home/oracle $ java -version
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 8.0.7.11 - pap6480sr7fp11-20220601_01(SR7 FP11))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20220511_28614 (JIT enabled, AOT enabled)
OpenJ9   - 844d750
OMR      - d297a72
IBM      - 7175f82)
JCL - 20220531_01 based on Oracle jdk8u331-b09

**Comment by dmitripivkine** [comment]
This is known (but not fixed) problem. This assertion means newly allocated object was discovered corrupted in the sanity check right after allocation.
I believe this is not OpenJ9 (or Semeru) but specific IBM Java problem. I have added `comp:gc` label to simplify tracking, despite assertion is in GC code I believe the source of object heap corruption is not.
@manqingl Would you recommend to open IBM internal ticket instead?

**Comment by dmitripivkine** [comment]
Just to keep things together I believe there is another manifestation of the same problem https://github.com/eclipse-openj9/openj9/issues/17180

**Comment by pshipton** [comment]
Closing since this will be reported elsewhere.

**Comment by bachlipp** [comment]
Thank you for you prompt replies!

One last issue, however: My machine cannot resolve the link to the IBM ticket system https://w3.ibm.com/w3publisher/ibm_runtime_technologies/support/reporting-java-issues, therefore I cannot create a ticket there. Is there another way to approach IBM?

**Comment by manqingl** [comment]
@bachlipp That link is only for IBM internals.  Please use the following link to report issue to us:

https://www.ibm.com/mysupport/
