### ISSUE TITLE
 [JDK21] Support JvmtiMountTransition Annotation

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#17520]
[JvmtiMountTransition](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/jdk/internal/vm/annotation/JvmtiMountTransition.java) annotation's description:

- A method is annotated as "jvmti mount transition" if it starts or ends virtual thread mount state transition (VTMS transition).
- This annotation is only used for [VirtualThread](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/java/lang/VirtualThread.java) methods, which are skipped during JVMTI inspection.

**Comment by thallium** [comment]
#16654 implements check for method entry and method exit events. Not sure if that suffices.

**Comment by babsingh** [comment]
> https://github.com/eclipse-openj9/openj9/pull/16654 implements check for method entry and method exit events. Not sure if that suffices.

No. At some places, the RI skips the method frames with the JvmtiMountTransition annotation while stackwalking in the JVMTI.

[MethodExitTest](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/test/hotspot/jtreg/serviceability/jvmti/vthread/MethodExitTest/MethodExitTest.java) which utilizes the hide frame feature.

**Comment by babsingh** [comment]
Work done to support the JvmtiMountTransition annotation:
- https://github.com/eclipse-openj9/openj9/pull/16654
- https://github.com/eclipse-openj9/openj9/pull/17855

Pending task from https://github.com/eclipse-openj9/openj9/pull/17855#issuecomment-1652307131:

>> There are stack trace APIs in JVMTI - the depth of frames will now not match (i.e. get a stack trace, find a method at depth 3, then try to use one of the APIs modified here, and fail because the deoth is off due to an annotated method).

> Yes. We will need to apply this change to all places where walkStackFrames is used in JVMTI functions. Will address this in a follow up PR.
