### ISSUE TITLE
Param -Xlog unsupport gc log rolling 

### ISSUE THREAD

**Issue by Albedooooooo** [eclipse-openj9/openj9#17532]
Param -Xlog:gc:<filename>   verbose gc log, however no option controller retention  log

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by dmitripivkine** [comment]
@Albedooooooo Would you please elaborate what the problem is? Which version of JVM you are using?
This option is documented in https://www.eclipse.org/openj9/docs/xlog/

**Comment by Albedooooooo** [comment]
> @Albedooooooo Would you please elaborate what the problem is? Which version of JVM you are using? This option is documented in https://www.eclipse.org/openj9/docs/xlog/

Thanks for the reply@dmitripivkine, the elaborate information as follows:
kafka server run on linux and jdk version: 1.8.0_322,openj9: 0.30.0

The gc file I configured : -Xlog:gc:file=/home/kafka/kafka/log/kafka-gc.log

The problem is file will be large after a long time

I try to find  some options, such as max_file_size, max_backup_index, but not find in documented 

so If I do this wrong please be aware.

Thanks！

**Comment by dmitripivkine** [comment]
@Albedooooooo -Xlog:gc` is mapped to `-Xverbosegclog`, so you can get more details here https://www.eclipse.org/openj9/docs/xverbosegclog/

The option format is:
```
-Xlog:gc[:<filename>[,<x>,<y>]]
```
If you specify `<x>` and `<y>`, the output is redirected to `x` files, each containing `y` GC cycles. Once reached the end the earliest file is going to be overwritten.

For example you can try something like:
```
-Xlog:gc:/home/kafka/kafka/log/kafka-gc.%Y%m%d.%H%M%S.%pid.log,2,1000
```
This option requests generation two log files with names like:
```
kafka-gc.20230607.095353.17499.log.001
kafka-gc.20230607.095353.17499.log.002
```
containing 1000 gc cycles each. When full, the older file should be overwritten and prevent logs set growing. In theory you can use `...,1,1000` to have single log file but rolling overs occur on file level, so I expect once full log is going to be overwritten (and previous info is lost).

I hope it can help. Please let me know if you need more details.
Thank you for using OpenJ9!

**Comment by Albedooooooo** [comment]
> @Albedooooooo -Xlog:gc`is mapped to`-Xverbosegclog`, so you can get more details here https://www.eclipse.org/openj9/docs/xverbosegclog/
> 
> The option format is:
> 
> ```
> -Xlog:gc[:<filename>[,<x>,<y>]]
> ```
> 
> If you specify `<x>` and `<y>`, the output is redirected to `x` files, each containing `y` GC cycles. Once reached the end the earliest file is going to be overwritten.
> 
> For example you can try something like:
> 
> ```
> -Xlog:gc:/home/kafka/kafka/log/kafka-gc.%Y%m%d.%H%M%S.%pid.log,2,1000
> ```
> 
> This option requests generation of two log files with names like:
> 
> ```
> kafka-gc.20230607.095353.17499.log.001
> kafka-gc.20230607.095353.17499.log.002
> ```
> 
> containing 1000 gc cycles each. When full, the older file should be overwritten and prevent logs set growing. In theory you can use `...,1,1000` to have single log file but rolling over occurs on file level, so I expect once full log is going to be overwritten (and previous info is lost).
> 
> I hope it can help. Please let me know if you need more details. Thank you for using OpenJ9!

@dmitripivkine That's great, this is very helpful! 
Thank you very much!
