### ISSUE TITLE
jdk_security2_0_FAILED javax/crypto/SecretKeyFactory/SecKeyFacSunJCEPrf.java IllegalArgumentException: Key must be at least 160 bits

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17551]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_aarch64_linux/113/)(`ubu20-aarch64-1`):
```
openjdk version "17.0.8" 2023-07-18
IBM Semeru Runtime Open Edition 17.0.8.0-m1 (build 17.0.8+5)
Eclipse OpenJ9 VM 17.0.8.0-m1 (build v0.40.0-release-b9cd65edd, JRE 17 Linux aarch64-64-Bit Compressed References 20230718_458 (JIT enabled, AOT enabled)
OpenJ9   - b9cd65edd
OMR      - 0e572348b
JCL      - 037408d4b91 based on jdk-17.0.8+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security2_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F458%2Fibm-semeru-open-jdk_aarch64_linux_17.0.8_5_openj9-0.40.0-m1.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-linux-aarch64-openj9%2F458%2Fibm-semeru-open-testimage_aarch64_linux_17.0.8_5_openj9-0.40.0-m1.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.40.0-release&amp;OPENJ9_BRANCH=v0.40.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.40.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-06-06T17:16:21.902Z] variation: Mode150
[2023-06-06T17:16:21.902Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-06-06T17:18:25.153Z] TEST: javax/crypto/SecretKeyFactory/SecKeyFacSunJCEPrf.java

[2023-06-06T17:18:25.153Z] STDOUT:
[2023-06-06T17:18:25.153Z] 3rd Party Provider: EvilProvider version 1.0
[2023-06-06T17:18:25.153Z] STDERR:
[2023-06-06T17:18:25.153Z] java.lang.IllegalArgumentException: Key must be at least 160 bits
[2023-06-06T17:18:25.153Z] 	at com.evilprovider.EvilHmacSHA1.engineInit(EvilHmacSHA1.java:44)
[2023-06-06T17:18:25.153Z] 	at java.base/javax.crypto.Mac.init(Mac.java:432)
[2023-06-06T17:18:25.153Z] 	at java.base/com.sun.crypto.provider.PBKDF2KeyImpl.deriveKey(PBKDF2KeyImpl.java:185)
[2023-06-06T17:18:25.153Z] 	at java.base/com.sun.crypto.provider.PBKDF2KeyImpl.<init>(PBKDF2KeyImpl.java:124)
[2023-06-06T17:18:25.153Z] 	at java.base/com.sun.crypto.provider.PBKDF2Core.engineGenerateSecret(PBKDF2Core.java:70)
[2023-06-06T17:18:25.153Z] 	at java.base/javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:334)
[2023-06-06T17:18:25.153Z] 	at SecKeyFacSunJCEPrf.main(SecKeyFacSunJCEPrf.java:62)
[2023-06-06T17:18:25.153Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-06-06T17:18:25.153Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-06-06T17:18:25.153Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-06-06T17:18:25.153Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2023-06-06T17:18:25.153Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-06-06T17:18:25.153Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2023-06-06T17:18:25.153Z] 
[2023-06-06T17:18:25.153Z] JavaTest Message: Test threw exception: java.lang.IllegalArgumentException: Key must be at least 160 bits

[2023-06-06T17:18:25.154Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.IllegalArgumentException: Key must be at least 160 bits
[2023-06-06T17:18:25.154Z] --------------------------------------------------
[2023-06-06T17:20:13.733Z] Test results: passed: 211; failed: 1
[2023-06-06T17:20:27.756Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16860687733463/jdk_security2_0/report/html/report.html
[2023-06-06T17:20:27.756Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_aarch64_linux/aqa-tests/TKG/output_16860687733463/jdk_security2_0/work
[2023-06-06T17:20:27.756Z] Error: Some tests failed or other problems occurred.
[2023-06-06T17:20:27.756Z] -----------------------------------
[2023-06-06T17:20:27.756Z] jdk_security2_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33227/)

**Comment by pshipton** [comment]
100% failure rate. 
cent7-aarch64-1, ub18-aarch64-3, ub18-aarch64-4, ub18-aarch64-8, ub22-aarch64-5

@JasonFengJ9 does it also fail on Hotspot?

**Comment by JasonFengJ9** [comment]
[JDK17 hotspot](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33251/)

**Comment by JasonFengJ9** [comment]
JDK17 hotpot `jdk_security2_0` passed in a grinder above.

**Comment by pshipton** [comment]
@jasonkatonica any idea why this would be failing on OpenJ9?

@JasonFengJ9 does it only fail on alinux?

**Comment by JasonFengJ9** [comment]
> does it only fail on alinux?

Across platforms
[JDK17 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_x86-64_linux/131/)
[JDK17 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_s390x_linux/128/)
[JDK17 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.openjdk_ppc64_aix/117/)

**Comment by pshipton** [comment]
Try on xlinux
[Internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/33256) - failed

Testing with -Djdk.nativeCrypto=false
[Internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/33257/) - failed
tracing:
```
15:39:59  MessageDigest native crypto implementation disabled. Using Java crypto implementation.
15:39:59  RSACore native crypto implementation disabled. Using Java crypto implementation.
15:39:59  SunEC native crypto implementation disabled. Using Java crypto implementation.
15:39:59  SunEC native crypto implementation disabled. Using Java crypto implementation.
15:39:59  SunEC native crypto implementation disabled. Using Java crypto implementation.
15:39:59  SunEC native crypto implementation disabled. Using Java crypto implementation.
15:39:59  NativeChaCha20Cipher native crypto implementation disabled. Using Java crypto implementation.
15:39:59  NativeGaloisCounterMode native crypto implementation disabled. Using Java crypto implementation.
```

The test was seen last passing with
10:37:45      openjdk - 8bef05cbd2 same as 5f8b804d09
10:37:45      openj9  - b9cd65edd
10:37:45      omr     - 0e572348b
10:37:45      openssl - 70c2912f

https://github.com/ibmruntimes/openj9-openjdk-jdk17/compare/5f8b804d09...037408d4b91
Two recent changes:
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/212 "PKCS#12 file-based Keystore support in FIPS mode"
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/219 "Use native OpenSSL library for XDH key generation and agreement"

Tested head stream build 463 - passed
OpenJ9   - 7cabea3aa
OMR      - 283d187d3
JCL      - 8bef05cbd2 same as 5f8b804d09

Tested head stream build 464 - failed
OpenJ9   - c969c5c98
OMR      - 283d187d3
JCL      - 1c66af2e7c same as 5c90aea743

Same two OpenJDK changes:
https://github.com/ibmruntimes/openj9-openjdk-jdk17/compare/5f8b804d09...5c90aea743

Seems unlikely to be caused by OpenJ9 changes, but here they are:
https://github.com/eclipse-openj9/openj9/compare/7cabea3aa...c969c5c98

Will create some build for triage.

**Comment by jasonkatonica** [comment]
I did try to isolate the test and run it against yesterdays x86-64 build downloaded from https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_x86-64_linux_Nightly/506/OpenJ9-JDK17-x86-64_linux-20230607-200936.tar.gz

I did not however encounter the same exception for some reason. I do find it strange this fails on openj9 but not hotspot for one reason or another.

The test files:

[issue17551.tar.gz](https://github.com/eclipse-openj9/openj9/files/11692764/issue17551.tar.gz)

```
# ls
EvilHmacSHA1.class  EvilHmacSHA1.java  EvilProvider.class  EvilProvider.java  SecKeyFacSunJCEPrf.class  SecKeyFacSunJCEPrf.java
```

```
# java -version
openjdk version "17.0.8-internal" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8-internal+0-adhoc.jenkins.BuildJDK17x86-64linuxNightly)
Eclipse OpenJ9 VM (build master-50019a8a232, JRE 17 Linux amd64-64-Bit Compressed References 20230607_506 (JIT enabled, AOT enabled)
OpenJ9   - 50019a8a232
OMR      - 3f989f0fde7
JCL      - 5c90aea743b based on jdk-17.0.8+5)
```

```
# java SecKeyFacSunJCEPrf
3rd Party Provider: EvilProvider version 1.0
PBKDF2WithHmacSHA1:
4B007901B765489ABEAD49D926F721D065A429C1
Test Vector Passed
```

@WilburZjh
@KostasTsiounis
Any thoughts here as to how PKCS12 or XDH code updates mentioned as deltas here could be involved in this scenario?

**Comment by KostasTsiounis** [comment]
Issue seems to be coming from https://github.com/KostasTsiounis/openj9-openjdk-jdk17/blob/22e949c62b9fced31e171016dbe0df9fbf50cdb1/src/java.base/share/classes/com/sun/crypto/provider/PBKDF2KeyImpl.java#L123, which was changed as part of https://github.com/KostasTsiounis/openj9-openjdk-jdk17/commit/22e949c62b9fced31e171016dbe0df9fbf50cdb1#diff-69c5b9e4c3707d5bd7bf4546a407f040745ffaa3d804456473b93a843f528748.

**Comment by KostasTsiounis** [comment]
Not sure why the problem appears only in `OpenJDK17`. Maybe `RestrictedSecurity`, which would not allow the addition of `EvilProvider`, is not enabled at some of those tests.

**Comment by pshipton** [comment]
> Not sure why the problem appears only in OpenJDK17

It may occur in other versions, and we just haven't got to them yet. The changes went in this week, the test only runs on the weekend for the head stream. We are working on the triage of the 0.40 M1 builds, starting with jdk17.

**Comment by pshipton** [comment]
Testing on the following passed, which rules out OpenJ9 changes.
10:14:12  OpenJ9   - c969c5c9826
10:14:12  OMR      - 283d187d38a
10:14:12  JCL      - 5f8b804d091 based on jdk-17.0.8+5)

Testing on the following also passed, which rules out [Use native OpenSSL library for XDH key generation and agreement](https://github.com/ibmruntimes/openj9-openjdk-jdk17/commit/7a823b99251cb684f0822434d54123775032127b)
10:23:10  OpenJ9   - c969c5c9826
10:23:10  OMR      - 283d187d38a
10:23:10  JCL      - a34ff642e88 based on jdk-17.0.8+5)

From https://github.com/eclipse-openj9/openj9/issues/17551#issuecomment-1583266224
Tested head stream build 464 - failed
OpenJ9 - c969c5c9826
OMR - 283d187d3
JCL - 1c66af2e7c same as 5c90aea743

https://github.com/ibmruntimes/openj9-openjdk-jdk17/compare/a34ff642e88...5c90aea743
Which supports https://github.com/eclipse-openj9/openj9/issues/17551#issuecomment-1583346161

**Comment by WilburZjh** [comment]
I tried to reproduce the failure, and I can get the same failure as @JasonFengJ9 posted by using the Nightly x86_64 build posted by @jasonkatonica . I thought this is caused by the most recent changes on https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/212 "PKCS#12 file-based Keystore support in FIPS mode". 

To verify the reason for this failure, I add the following code in `PBKDF2KeyImpl.java` file and made another build in jenkins.
```
            if (RestrictedSecurity.isFIPSEnabled()) {
                this.prf = Mac.getInstance(prfAlgo); 
            } else {
                this.prf = Mac.getInstance(prfAlgo, SunJCE.getInstance()); 
            }
```
After testing again, the failure is gone, so this seems to be the "remove the provider argument" in Mac.getInstance() method. 

@keithc-ca , I think this is one of the case that we need to keep the provider argument to keep the consistency in non-FIPS mode and add an additional check for FIPS mode as we discussed in [JDKnext](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/573#discussion_r1196774921). So I suggest that we use the above code in `PBKDF2KeyImpl.java` file in various jdk versions.

**Comment by WilburZjh** [comment]
I can not reproduce this failure directly compiled from java, but I can reproduce the failure by the mentioned precompiled jar -> jar file: openj9-openjdk-jdk17/test/jdk/javax/crypto/SecretKeyFactory/evilprov.jar files in this case.

**Comment by WilburZjh** [comment]
A fix is opened and merged for jdk17 -> https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/221. After testing in jenkins -> https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/33406/, the test is passed.

**Comment by pshipton** [comment]
Should be fixed for all versions. All the PRs are linked fromhttps://github.com/ibmruntimes/openj9-openjdk-jdk/pull/612
