### ISSUE TITLE
Footprint (Heap Sizing) Issue with InstantOn

### ISSUE THREAD

**Issue by RSalman** [eclipse-openj9/openj9#17596]
A performance issue has been identified when running InstantOn in environments that have different memory limits during the checkpoint and restore runs. The problem occurs when the checkpoint run takes place in an environment where the memory limit is greater than that of the restore environment. In such cases, the InstantOn (restore) JVM heap size is larger than what would have been set for a non-InstantOn JVM running in the same environment where the restore was performed. As a result, memory usage (footprint) appears to be higher when using InstantOn compared to a regular run. Overall, this problem arises because the heap configuration is based on the checkpoint environment and does not consider restore environment memory limits.

This behaviour has been documented to inform users of this issue. However, we need to provide proper support for these scenarios. This issue will be used to explore potential solutions and track the work required to address this.

**Comment by RSalman** [comment]
A potential solution that's currently being explored involves utilizing existing GC [softmx logic](https://www.ibm.com/docs/en/sdk-java-technology/8?topic=options-xsoftmx). In this approach, softmx can be repurposed and invoked as part of restore GC reinit routine to dynamically adjust the heap size based on the restore env memory limit. Unused memory would be disclaimed in this process.

**Comment by RSalman** [comment]
Currently, softmx simply enforces an extra criteria during heap contraction/expansion to ensure the heap size doesn't exceed specified limit. The current implementation provides a good starting point, however it needs to be extended to be used as a solution to this issue. All the components consuming the heap size (e.g., memory pool, verbose gc, etc) need to be correctly updated with the new heap size.

**Comment by dmitripivkine** [comment]
Please note this issue is applicable for cases when `-Xmx` has not been specified and JVM selects default (25% of machine RAM for Java 11 and up, Java 8 has hardcoded 512m)

**Comment by RSalman** [comment]
I was optimist before that I could have some sort of partial solution for the 0.40 release. However, I do not anticipate that this will be addressed before the release.
