### ISSUE TITLE
jdk21 java/util/concurrent/StructuredTaskScope/StructuredThreadDumpTest cannot find symbol HotSpotDiagnosticMXBean

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17634]
https://openj9-jenkins.osuosl.org/job/Grinder_testList_2/46/ - amac jdk21
java/util/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java
```
15:11:14  /Users/jenkins/workspace/Grinder_testList_2/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java:43: error: cannot find symbol
15:11:14  import com.sun.management.HotSpotDiagnosticMXBean.ThreadDumpFormat;
15:11:14                                                   ^
15:11:14    symbol:   class ThreadDumpFormat
15:11:14    location: interface HotSpotDiagnosticMXBean
15:11:14  /Users/jenkins/workspace/Grinder_testList_2/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/concurrent/StructuredTaskScope/StructuredThreadDumpTest.java:149: error: cannot find symbol
15:11:14                  .dumpThreads(file.toString(), ThreadDumpFormat.JSON);
15:11:14                                                ^
15:11:14    symbol:   variable ThreadDumpFormat
15:11:14    location: class StructuredThreadDumpTest
```

**Comment by pshipton** [comment]
@babsingh pls take a look. Should OpenJ9 provide an equivalent JSON formatted Thread dump implementation, or start including a subset of HotSpotDiagnosticMXBean?

I didn't see it at first, but this is a dup of https://github.com/eclipse-openj9/openj9/issues/15278 which excluded the test. The test was renamed since it's no longer an incubator.

@tajila fyi

**Comment by babsingh** [comment]
Fix:
- https://github.com/eclipse-openj9/openj9/pull/17709
- https://github.com/adoptium/aqa-tests/pull/4659

**Comment by pshipton** [comment]
@babsingh a reminder to remove the `test excluded` label when a test is re-enabled.
