### ISSUE TITLE
jdk21 ZGenerational, cds.write.archived.java.heap test parameters missing

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17631]
https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/231/ - amac jdk21

java/lang/ProcessBuilder/CloseRace.java#id0
```
TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.opt.final.ZGenerational'\
```

jdk/internal/misc/CDS/ArchivedEnumTest.java
```
TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.cds.write.archived.java.heap'
```

**Comment by keithc-ca** [comment]
I note that `ArchivedEnumTest` requires `vm.cds.write.archived.java.heap` in jdk20 as well; we'll need a pull request for there as well.

**Comment by pshipton** [comment]
For some reason we haven't spotted any test problem in jdk20 M1 testing, perhaps the test isn't running there.

**Comment by keithc-ca** [comment]
That test is in a different package in jdk20 vs. newer versions, perhaps that's why it isn't being executed. On the other hand, I see no danger in adding the property in `OpenJ9PropsExt` in jdk20.

**Comment by pshipton** [comment]
Created https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/65

**Comment by keithc-ca** [comment]
Closing: this has been addressed in all relevant repositories.
