### ISSUE TITLE
jdk21 com/sun/crypto/provider/DHKEM/Compliance Undetermined for -6756058909602679649

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17633]
https://openj9-jenkins.osuosl.org/job/Grinder_testList_2/46/ - amac jdk21
com/sun/crypto/provider/DHKEM/Compliance.java

```
15:09:01  java.lang.RuntimeException: Undetermined for -6756058909602679649: expected true, was false
15:09:01  	at jdk.test.lib.Asserts.fail(Asserts.java:594)
15:09:01  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
15:09:01  	at Compliance.determined(Compliance.java:205)
15:09:01  	at Compliance.main(Compliance.java:53)
15:09:01  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
15:09:01  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
15:09:01  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
15:09:01  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment]
Still fails on the latest jdk21 OpenJ9.
Passes on the latest Temurin nightly build.

Passes on OpenJ9 with -Djdk.nativeXDHKeyGen=false

Tentatively setting as a blocker, unless we can explain why this failure doesn't matter.

**Comment by KostasTsiounis** [comment]
The test creates two `Random` instances with a specific seed. It then uses them to create two sets of XDH keys and encapsulate them. The expectation is that the result will be the same, since the source of randomness is the same.

However, the `Random` instance is never used when using OpenSSL to perform operations (uses its own source of randomness), which leads to two consecutive calls providing two different results.

**Comment by 0xdaryl** [comment]
Kostas (@KostasTsiounis ), could you post a current status update on this blocking JDK 21 issue please?  Thanks.

**Comment by KostasTsiounis** [comment]
We are currently working on a fix for this issue.

**Comment by vij-singh** [comment]
@KostasTsiounis  Any new news on this one?

**Comment by tajila** [comment]
@KostasTsiounis Any update?

**Comment by pshipton** [comment]
Keep it open until the test is unexcluded.

**Comment by pshipton** [comment]
Unexcluding via 
https://github.com/adoptium/aqa-tests/pull/4920
https://github.com/adoptium/aqa-tests/pull/4921
