### ISSUE TITLE
jdk21 Class.isUnnamedClass() missing

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17630]
https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/231/ - amac jdk21
java/lang/Class/UnnamedClass/TestUnnamedClass.java

```
15:05:34  /Users/jenkins/workspace/Grinder_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/Class/UnnamedClass/TestUnnamedClass.java:53: error: cannot find symbol
15:05:34          check(unnamedClass.isUnnamedClass(), "Unnamed class was isUnnamedClass() false");
```

**Comment by pshipton** [comment]
@tajila

**Comment by tajila** [comment]
This is a new API added for JDK21 https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/Class.html#isUnnamedClass()

**Comment by hangshao0** [comment]
From https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/Class.html#unnamedClasses:
`
The Class object representing an unnamed class is top-level, synthetic, and final.`
