### ISSUE TITLE
gcc 10 (perhaps others) missing from cent7-x64-2, other setup issues

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17678]
gcc 4.8.5 is being used to compile.
https://openj9-jenkins.osuosl.org/job/Build_JDK17_x86-64_linux_Nightly/519/consoleFull

I've removed the `ci.role.build ci.role.build.criu` labels from this machine.

@AdamBrousseau @jdekonin fyi

**Comment by pshipton** [comment]
Seems that criu isn't setup properly on this machine either. I've disabled it.
https://github.com/eclipse-openj9/openj9/issues/17681

**Comment by AdamBrousseau** [comment]
Dup #17325 
Mahdi was working on it yesterday so that is why it was re-enabled. Should have removed the labels first. Apologies for the inconvenience.
