### ISSUE TITLE
JDK21 jdk_security3_0_FAILED sun/security/pkcs11/KeyStore/CertChainRemoval.java PKCS11Exception: CKR_GENERAL_ERROR

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17672]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/1/consoleFull)(`rhel8x86-rtp-rt2-1`):
```
08:24:53  openjdk version "21-internal" 2023-09-19
08:24:53  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21x86-64linuxPersonal)
08:24:53  Eclipse OpenJ9 VM (build master-163a51495d5, JRE 21 Linux amd64-64-Bit Compressed References 20230624_7 (JIT enabled, AOT enabled)
08:24:53  OpenJ9   - 163a51495d5
08:24:53  OMR      - 59b55e30960
08:24:53  JCL      - e76b3946ed5 based on jdk-21+27)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_other_0,jdk_other_1,jdk_security3_0,jdk_security3_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_x86-64_linux_Personal%2F7%2FOpenJ9-JDK21-x86-64_linux-20230624-043005.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_x86-64_linux_Personal%2F7%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=163a51495d5fb2b004ba596846de1738b454bcc2&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
09:12:57  variation: Mode150
09:12:57  JVM_OPTIONS:  -XX:+UseCompressedOops 

09:25:23  TEST: sun/security/pkcs11/KeyStore/CertChainRemoval.java

09:25:23  STDOUT:
09:25:23  config CertChainRemoval.setUp(): success
09:25:23  Beginning test run CertChainRemoval...
09:25:23  Cannot resolve artifact, please check if JIB jar is present in classpath.
09:25:23  nssLibDir: /usr/lib64/
09:25:23  Running test with provider SunPKCS11-nss (security manager disabled) ...
09:25:23  Starting with: 
09:25:23  Entry# 1 = ca1
09:25:23  Entry# 2 = root
09:25:23  Entry# 3 = pk1
09:25:23  ========
09:25:23  Initial PKCS11 KeyStore: 
09:25:23  ========
09:25:23  Add pk1, ca1 and root, then delete pk1
09:25:23  test CertChainRemoval.test(): failure
09:25:23  java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
09:25:23  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1121)
09:25:23  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetKeyEntry(P11KeyStore.java:462)
09:25:23  	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1192)
09:25:23  	at CertChainRemoval.main(CertChainRemoval.java:141)
09:25:23  	at PKCS11Test.premain(PKCS11Test.java:178)
09:25:23  	at PKCS11Test.testNSS(PKCS11Test.java:554)
09:25:23  	at PKCS11Test.main(PKCS11Test.java:214)
09:25:23  	at PKCS11Test.main(PKCS11Test.java:190)
09:25:23  	at CertChainRemoval.test(CertChainRemoval.java:77)
09:25:23  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
09:25:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
09:25:23  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
09:25:23  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
09:25:23  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
09:25:23  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
09:25:23  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
09:25:23  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
09:25:23  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
09:25:23  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
09:25:23  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1593)
09:25:23  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
09:25:23  	at org.testng.TestRunner.run(TestRunner.java:585)
09:25:23  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
09:25:23  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
09:25:23  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
09:25:23  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
09:25:23  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
09:25:23  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
09:25:23  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
09:25:23  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
09:25:23  	at org.testng.TestNG.runSuites(TestNG.java:1069)
09:25:23  	at org.testng.TestNG.run(TestNG.java:1037)
09:25:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
09:25:23  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
09:25:23  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
09:25:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
09:25:23  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
09:25:23  	at java.base/java.lang.Thread.run(Thread.java:1595)
09:25:23  Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
09:25:23  	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11$InnerPKCS11.C_CreateObject(PKCS11.java:197)
09:25:23  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.storeCert(P11KeyStore.java:1576)
09:25:23  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.storeChain(P11KeyStore.java:1591)
09:25:23  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.storePkey(P11KeyStore.java:1814)
09:25:23  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1117)
09:25:23  	... 37 more
09:25:23  
09:25:23  ===============================================
09:25:23  sun/security/pkcs11/KeyStore/CertChainRemoval.java
09:25:23  Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
09:25:23  ===============================================

09:25:23  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
09:25:23  --------------------------------------------------
09:53:23  Test results: passed: 901; failed: 1
09:53:37  Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/aqa-tests/TKG/output_16876095876025/jdk_security3_0/report/html/report.html
09:53:37  Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/aqa-tests/TKG/output_16876095876025/jdk_security3_0/work
09:53:37  Error: Some tests failed or other problems occurred.
09:53:37  -----------------------------------
09:53:37  jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33618/)

**Comment by pshipton** [comment]
All the grinder appear to be failing the same way. Does it also fail on Adoptium?

**Comment by JasonFengJ9** [comment]
[15x grinder w/ hotspot](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33628/)

**Comment by pshipton** [comment]
@jasonkatonica fyi

**Comment by JasonFengJ9** [comment]
Still seen in a latest run - [JDK21 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/20/consoleFull)
```
12:29:47  openjdk version "21-internal" 2023-09-19
12:29:47  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21x86-64linuxPersonal)
12:29:47  Eclipse OpenJ9 VM (build master-ea0d545d82a, JRE 21 Linux amd64-64-Bit Compressed References 20230814_56 (JIT enabled, AOT enabled)
12:29:47  OpenJ9   - ea0d545d82a
12:29:47  OMR      - 43a2b1d3416
12:29:47  JCL      - 87ec21cbc99 based on jdk-21+33)

13:53:56  variation: Mode150
13:53:56  JVM_OPTIONS:  -XX:+UseCompressedOops 

14:18:21  TEST: sun/security/pkcs11/KeyStore/CertChainRemoval.java

14:18:21  test CertChainRemoval.test(): failure
14:18:21  java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
14:18:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1121)
14:18:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetKeyEntry(P11KeyStore.java:462)
14:18:21  	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1192)
14:18:21  	at CertChainRemoval.main(CertChainRemoval.java:141)
14:18:21  	at PKCS11Test.premain(PKCS11Test.java:178)
14:18:21  	at PKCS11Test.testNSS(PKCS11Test.java:554)
14:18:21  	at PKCS11Test.main(PKCS11Test.java:214)
14:18:21  	at PKCS11Test.main(PKCS11Test.java:190)
14:18:21  	at CertChainRemoval.test(CertChainRemoval.java:77)
14:18:21  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
14:18:21  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
14:18:21  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
14:18:21  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
14:18:21  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
14:18:21  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
14:18:21  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
14:18:21  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
14:18:21  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
14:18:21  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
14:18:21  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
14:18:21  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
14:18:21  	at org.testng.TestRunner.run(TestRunner.java:585)
14:18:21  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
14:18:21  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
14:18:21  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
14:18:21  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
14:18:21  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
14:18:21  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
14:18:21  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
14:18:21  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
14:18:21  	at org.testng.TestNG.runSuites(TestNG.java:1069)
14:18:21  	at org.testng.TestNG.run(TestNG.java:1037)
14:18:21  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
14:18:21  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
14:18:21  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
14:18:21  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
14:18:21  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
14:18:21  	at java.base/java.lang.Thread.run(Thread.java:1595)
14:18:21  Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
14:18:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11$InnerPKCS11.C_CreateObject(PKCS11.java:197)
14:18:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.storeCert(P11KeyStore.java:1576)
14:18:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.storeChain(P11KeyStore.java:1591)
14:18:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.storePkey(P11KeyStore.java:1814)
14:18:21  	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1117)
14:18:21  	... 37 more
14:18:21  
14:18:21  ===============================================
14:18:21  sun/security/pkcs11/KeyStore/CertChainRemoval.java
14:18:21  Total tests run: 1, Passes: 0, Failures: 1, Skips: 0

14:18:21  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
14:18:21  --------------------------------------------------
15:14:42  Test results: passed: 902; failed: 1
15:14:54  Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/aqa-tests/TKG/output_16920306894918/jdk_security3_0/report/html/report.html
15:14:54  Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/aqa-tests/TKG/output_16920306894918/jdk_security3_0/work
15:14:54  Error: Some tests failed or other problems occurred.
15:14:54  -----------------------------------
15:14:54  jdk_security3_0_FAILED
```

hotspot failed as well [3x grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34335/console)
```
10:35:57  openjdk version "21-beta" 2023-09-19
10:35:57  OpenJDK Runtime Environment Temurin-21+34-202308082331 (build 21-beta+34-202308082331)
10:35:57  OpenJDK 64-Bit Server VM Temurin-21+34-202308082331 (build 21-beta+34-202308082331, mixed mode, sharing)
```

**Comment by pshipton** [comment]
@jasonkatonica any ideas about this one, do you think we have a machine setup issue?

**Comment by jasonkatonica** [comment]
The error CKR_ATTRIBUTE_READ_ONLY can be expected if running on a FIPS machine since the NSS database is read only. Perhaps the CKR_GENERAL_ERROR could indicate this too since in the stack it is attempting to insert a certificate into the PKCS11 database ( NSS ). Could it be that NSS, or another PKCS11 setup, is not on this machine? Non fips tests I would expect to work with a read / write database when not in fips mode.

**Comment by pshipton** [comment]
I added the internal machine names, which are also available in the grinders (while they remain). There were a number of machines used and they all failed. Can you pls look at one of these to see if NSS or another PKCS11 is installed? Or let me know how to check (it doesn't seem obvious). I also wonder if the account we are using to run testing needs special privilege to write? 
ubu22x86-svl-rt11-1, rhel8x86-rt1-1, cent8x86-rtp-rt7-1, cent9x86-svl-rt4-1

**Comment by jasonkatonica** [comment]
On rhel the NSS database is typically installed at `/etc/pki/nssdb` and the nss libraries are installed with `dnf install nss`. 

The test itself can be coded to use any library and or nss database location. The test [CertChainRemoval.java on line 72](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/440eb6c28cb2c718debf3cfc21c13a09584540c0/test/jdk/sun/security/pkcs11/KeyStore/CertChainRemoval.java#L72) is using a custom configuration file which points to the file [p11-nss.txt](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/sun/security/pkcs11/KeyStore/CertChainRemoval/p11-nss.txt) , from there i am unsure what values it actually specifies for the location of the nssdb and library for `configdir=` and `library =` since it is doing substitution.

I did check out the machine `ubu22x86-svl-rt11-1` and it does have nss installed as seen here:
```
jenkins@ubu22x86-svl-rt11-1:~$ apt list --installed | grep libnss3

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnss3/jammy-updates,jammy-security,now 2:3.68.2-0ubuntu1.2 amd64 [installed,automatic]
```
I could not however find any nssdb file on this system, I would assume we need this for this test to pass. The [doc here ](https://discourse.ubuntu.com/t/network-security-services-nss/35168) seems to indicate on Ubuntu that we should expect the nssdb to be located in `~/.pki/nssdb` but this directory did not exist. It might be possible to try to create the nssdb using the instructions `Bootstrapping the NSS database` in the NSS doc to see if the test ends up picking up the nss database that was created. I didnt have the permission to try to run these commands to see what happens:
```
sudo apt install libnss3-tools
mkdir -p ~/.pki/nssdb
certutil -d ~/.pki/nssdb -N
```
I also agree that the permissions to the nssdb file would need to allow for the jenkins user to read and write the file for this to work.

**Comment by taoliult** [comment]
Checking on this issue, will update shortly.

**Comment by taoliult** [comment]
This issue is due to a NSS behavior change in newer NSS releases. And there is a defect, link below, opened in OpenJDK to updates the PKCS11 KeyStore impl to work with the NSS behavior change.

https://bugs.openjdk.org/browse/JDK-8309214
[openjdk/jdk21u@c849fa5](https://github.com/openjdk/jdk21u/commit/c849fa5b1fe52ff92588762fb739253d6f2044b6)

So, a question, do we will pick up the codes fix from OpenJDK repo, or we have to manually apply this code change?

And, since it is not an issue introduced by us, so I don't think it is a blocker issue.

**Comment by pshipton** [comment]
It appears the fix is part of 20.0.1 which OpenJ9 will pick up in Oct before any OpenJ9 jdk21 release.

**Comment by pshipton** [comment]
@JasonFengJ9 once we have builds testing 20.0.1 (i.e. tonight) pls confirm if this is resolved.

**Comment by JasonFengJ9** [comment]
Passed in [latest run](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux/12/)
```
05:57:41  java version "21.0.1-beta" 2023-10-17
05:57:41  IBM Semeru Runtime Certified Edition 21.0.1+12-202310260910 (build 21.0.1-beta+12-202310260910)
05:57:41  Eclipse OpenJ9 VM 21.0.1+12-202310260910 (build master-66e3fd1da, JRE 21 Linux amd64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
05:57:41  OpenJ9   - 66e3fd1da
05:57:41  OMR      - 071c0c25b
05:57:41  JCL      - c06eaf638 based on jdk-21.0.1+12)
```
