### ISSUE TITLE
[FFI/Jtreg_JDK21] AssertionError detected in TestLayouts.java on AIX

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17683]
The test suite ended up with the following error:
```
test TestLayouts.testStructToString(): failure
java.lang.AssertionError: expected [[i4](struct)] but found [[I4](struct)] <----------
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertEqualsImpl(Assert.java:140)
        at org.testng.Assert.assertEquals(Assert.java:122)
        at org.testng.Assert.assertEquals(Assert.java:629)
        at org.testng.Assert.assertEquals(Assert.java:639)
        at TestLayouts.testStructToString(TestLayouts.java:264)
```
FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
Looking at the failing test case at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/8fdc0f13b1557ace8be6a63c1f1c429e3b5bac54/test/jdk/java/foreign/TestLayouts.java#L264
```
    @Test
    public void testStructToString() {
        StructLayout padding = MemoryLayout.structLayout(JAVA_INT).withName("struct");
        assertEquals(padding.toString(), "[i4](struct)"); <--------
        var toStringUnaligned = padding.withByteAlignment(8).toString();
        assertEquals(toStringUnaligned, "8%[i4](struct)");
    }
```
against the related code in OpenJDK at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/8fdc0f13b1557ace8be6a63c1f1c429e3b5bac54/src/java.base/share/classes/jdk/internal/foreign/layout/ValueLayouts.java#L111
```
        @Override
        public String toString() {
            char descriptor = carrier.descriptorString().charAt(0);
            if (order == ByteOrder.LITTLE_ENDIAN) {  <-----------------
                descriptor = Character.toLowerCase(descriptor);
            }
            return decorateLayoutString(String.format("%s%d", descriptor, byteSize()));
        }
```
which only convert the descriptor of type to the lower case for the `LITTLE_ENDIAN` platforms.

Given the test case is never verified on the `BIG_ENDIAN` platforms like AIX, there is no wonder the failure occurs on AIX.

**Comment by ChengJin01** [comment]
Assuming the intention of the code at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/8fdc0f13b1557ace8be6a63c1f1c429e3b5bac54/src/java.base/share/classes/jdk/internal/foreign/layout/ValueLayouts.java#L111 is to differentiate the LE/BE platforms, there is no need to change the code to convert the descriptor to the lower case regardless of the platforms in OpenJDK.  I will simply update the test case to accommodate the situation on AIX.

**Comment by keithc-ca** [comment]
I expect this applies not just to AIX, but to s390x Linux as well (another big-endian platform).

**Comment by ChengJin01** [comment]
> I expect this applies not just to AIX, but to s390x Linux as well (another big-endian platform).

Yes, it applies to all LE/BE platforms.

**Comment by ChengJin01** [comment]
Close the issue as resolved at https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/13.
