### ISSUE TITLE
Potential issues with j9time_current_time_millis() in GC

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#17706]
`j9time_current_time_millis()` is implemented by `gettimeofday()` on UNIX, and the API is not guaranteed to be monotonic.  The time returned by the API could jump forward or backward.

I found some uses of `j9time_current_time_millis()` in the GC code that seem to be expecting monotonic time as shown below.

The following functions will hit the time limit earlier or later than expected when `gettimeofday()` value is adjusted:

MM_ParallelScrubCardTableTask::shouldYieldFromTask()
https://github.com/eclipse-openj9/openj9/blob/f715f7fbc27e7c9be8495463206904c919b0f3f7/runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp#L398-L402

MM_ParallelGlobalMarkTask::shouldYieldFromTask()
https://github.com/eclipse-openj9/openj9/blob/f715f7fbc27e7c9be8495463206904c919b0f3f7/runtime/gc_vlhgc/GlobalMarkingScheme.cpp#L223-L227

MM_GlobalMarkDelegate::performMarkIncremental()
https://github.com/eclipse-openj9/openj9/blob/f715f7fbc27e7c9be8495463206904c919b0f3f7/runtime/gc_vlhgc/GlobalMarkDelegate.cpp#L256

The following function can print a huge number when `end` is smaller than `start`:

RunAllTests()
https://github.com/eclipse-openj9/openj9/blob/f715f7fbc27e7c9be8495463206904c919b0f3f7/runtime/gc_tests/rwlocktests/main.cpp#L48

**Comment by knn-k** [comment]
See also https://github.com/eclipse/omr/issues/7051

**Comment by pshipton** [comment]
@dmitripivkine @amicic

**Comment by amicic** [comment]
@knn-k thanks for reporting this. OK, we will use hires API then, which is believed to be monotonic.

**Comment by JasonFengJ9** [comment]
* https://github.com/eclipse-openj9/openj9/pull/17730#issuecomment-1625266281
I suggest j9time_nano_time() which returns monotonic time and is also CRIU compatible, i.e., if there is a checkpoint between taking startTime and endTime using j9time_nano_time(), the timeDiff calculated is adjusted according to the JVM downtime between the checkpoint and restore.
