### ISSUE TITLE
Potential issue with j9time_current_time_millis() in VM

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#17719]
`j9time_current_time_millis()` is implemented by `gettimeofday()` on UNIX, and the API is not guaranteed to be monotonic. The time returned by the API could jump forward or backward.

I found some uses of `j9time_current_time_millis()` in the VM code that seem to be expecting monotonic time as shown below.

https://github.com/eclipse-openj9/openj9/blob/a52a0b853a70eb6cf168d710b63d4178cf23124c/runtime/vm/rasdump.c#L631-L634

`endTime - start` can be a huge number when the `gettimeofday()` value jumps backward because the variables are declared as `U_64` while the type of `j9time_current_time_millis()` is `int64_t`;

See also #17706

**Comment by knn-k** [comment]
Quick fix for this would be to change the type of the variables from `U_64` to `I_64`.
If the code expects the time to be monotonic, it will need to use another j9time API like `omrtime_hires_clock()`;  It requires to call `omrtime_hires_delta()` for calculating the time difference.

**Comment by pshipton** [comment]
@keithc-ca @tajila fyi

**Comment by keithc-ca** [comment]
> If the code expects the time to be monotonic

In the case you quote, I think it does.

**Comment by knn-k** [comment]
I opened #17730 as the fix.
