### ISSUE TITLE
cmdLineTester_criu_jitPostRestore_2_FAILED Check Verbose Log Success condition was not found: [Output match: CHECKPOINT RESTORE: Ready for restore]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17729]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_testList_0/336/)(`cent7-aarch64-5`):
```
openjdk version "11.0.20" 2023-07-18
IBM Semeru Runtime Open Edition 11.0.20.0-m2 (build 11.0.20+7)
Eclipse OpenJ9 VM 11.0.20.0-m2 (build v0.40.0-release-6eed0535c, JRE 11 Linux aarch64-64-Bit Compressed References 20230628_721 (JIT enabled, AOT enabled)
OpenJ9   - 6eed0535c
OMR      - e80bff83b
JCL      - 20e0e53157 based on jdk-11.0.20+7)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=cmdLineTester_criu_jitPostRestore_2&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.functional_aarch64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F721%2Fibm-semeru-open-jdk_aarch64_linux_11.0.20_7_openj9-0.40.0-m2.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-aarch64-openj9%2F721%2Fibm-semeru-open-testimage_aarch64_linux_11.0.20_7_openj9-0.40.0-m2.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=v0.40.0-release&amp;OPENJ9_BRANCH=v0.40.0-release&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=v0.40.0-release&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=437&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=20&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2023-06-29T04:12:46.584Z] variation: -Xjit:vlog=vlog
[2023-06-29T04:12:46.584Z] JVM_OPTIONS:  -Xjit:vlog=vlog 

[2023-06-29T04:12:51.281Z] Testing: Check Verbose Log
[2023-06-29T04:12:51.281Z] Test start time: 2023/06/29 00:12:50 Eastern Standard Time
[2023-06-29T04:12:51.281Z] Running command: cat vlog
[2023-06-29T04:12:51.281Z] Time spent starting: 3 milliseconds
[2023-06-29T04:12:51.281Z] Time spent executing: 4 milliseconds
[2023-06-29T04:12:51.281Z] Test result: FAILED
[2023-06-29T04:12:51.281Z] Output from test:
[2023-06-29T04:12:51.281Z] >> Success condition was not found: [Output match: CHECKPOINT RESTORE: Ready for restore]

[2023-06-29T04:13:06.506Z] ---TEST RESULTS---
[2023-06-29T04:13:06.506Z] Number of PASSED tests: 4 out of 5
[2023-06-29T04:13:06.506Z] Number of FAILED tests: 1 out of 5
[2023-06-29T04:13:06.506Z] 
[2023-06-29T04:13:06.506Z] ---SUMMARY OF FAILED TESTS---
[2023-06-29T04:13:06.506Z] Check Verbose Log
[2023-06-29T04:13:06.506Z] -----------------------------
[2023-06-29T04:13:06.506Z] 
[2023-06-29T04:13:06.506Z] -----------------------------------
[2023-06-29T04:13:06.506Z] cmdLineTester_criu_jitPostRestore_2_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33760/) - all passed

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/518
cmdLineTester_criu_jitPostRestore_2
```
Testing: Check Verbose Log
Test start time: 2023/07/11 00:31:37 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuCatVlog.sh vlog true true
Time spent starting: 3 milliseconds
Time spent executing: 83 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] Outputting vlog vlog
 [OUT] 
 [OUT] Outputting previous test output
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Tue Jul 11 00:31:32 EDT 2023, System.currentTimeMillis(): 1689049892963, System.nanoTime(): 1689049892961075172
 [OUT] pie: 53518: Error (criu/pie/restorer.c:1651): Unable to create a thread: 53520
 [OUT] pie: 53518: Error (criu/pie/restorer.c:1787): Restorer fail 53518
 [OUT] Error (criu/cr-restore.c:1414): 53518 exited, status=1
 [OUT] Error (criu/cr-restore.c:2293): Restoring FAILED.
 [OUT] 
 [OUT] Removed test output files
 [OUT] finished script
>> Success condition was not found: [Output match: CHECKPOINT RESTORE: Ready for restore]
>> Success condition was not found: [Output match: CAT VLOG FORCE PASS]
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/520
cmdLineTester_criu_jitPostRestore_2
```
Testing: Check Verbose Log
Test start time: 2023/07/12 22:47:00 Eastern Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuCatVlog.sh vlog true true
Time spent starting: 6 milliseconds
Time spent executing: 25 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] Outputting vlog vlog
 [OUT] 
 [OUT] Outputting previous test output
 [OUT] Pre-checkpoint
 [OUT] Performing CRIUSupport.checkpointJVM(), current thread name: main, Wed Jul 12 22:46:57 EDT 2023, System.currentTimeMillis(): 1689216417461, System.nanoTime(): 1689216417457143365
 [OUT] pie: 35407: Error (criu/pie/restorer.c:1651): Unable to create a thread: 35411
 [OUT] pie: 35407: Error (criu/pie/restorer.c:1787): Restorer fail 35407
 [OUT] Error (criu/cr-restore.c:2293): Restoring FAILED.
 [OUT] 
 [OUT] Removed test output files
 [OUT] finished script
>> Success condition was not found: [Output match: CHECKPOINT RESTORE: Ready for restore]
>> Success condition was not found: [Output match: CAT VLOG FORCE PASS]
```

**Comment by pshipton** [comment]
@tajila fyi

**Comment by dsouzai** [comment]
I think at least part of this is because I missed the situation where a vlog can exist AND the restore can fail:
https://github.com/eclipse-openj9/openj9/blob/e8bc291edfd92b7dca94d046674a1f4e3b536544/test/functional/cmdLineTests/criu/criuCatVlog.sh#L37-L45

Not really sure why the vlog is empty though considering that that a verbose option was set in the previous test:
https://github.com/eclipse-openj9/openj9/blob/e8bc291edfd92b7dca94d046674a1f4e3b536544/test/functional/cmdLineTests/criu/criu_jitPostRestore.xml#L31
