### ISSUE TITLE
Investigate why right shift 0 IL trees are not removed

### ISSUE THREAD

**Issue by a7ehuo** [eclipse-openj9/openj9#17740]
Issue #17708 reports an assert on Power CG due to right shift by `0`.  This issue is opened to investigate why the right shift by `0` IL trees are not removed in the Optimizer [1]. As mentioned in https://github.com/eclipse-openj9/openj9/issues/17708#issuecomment-1615322345, right shift by `0` tree is inserted in GRA 

```
n11195n   iRegStore gr22                                                                      [    0x74ba62449b00] bci=[32,44,1766] rc=0 vc=12381 vn=- li=-4 udi=121 nc=1
n11196n     iushr (normalizedShift )                                                          [    0x74ba62449b50] bci=[36,15,2120] rc=4 vc=12381 vn=- li=- udi=- nc=2 flg=0x8000
n4017n        ==>iload
n11216n       ==>iconst 0
```

[1] https://github.com/eclipse-openj9/openj9/issues/17708#issuecomment-1623663043

**Comment by a7ehuo** [comment]
As mentioned in https://github.com/eclipse-openj9/openj9/issues/17708#issuecomment-1615322345, after `tacticalGlobalRegisterAllocator`, the shift value `n11197n` (`iload #1194`) for `n11196n iushr` is replaced as `n11216n` (`iconst 0`) because `0` is stored to temp `#1194` by `n11219n` in `block_745`. `block_742` that has `n11196n` (`iushr`) is an extension of `block_745` [1].

`block_742` becomes an extension of `block_745` after `id=84 name=trivialBlockExtension` [2]. Afterwards, two things have to happen in order for `n11196n` (`iushr`) to be folded away 
1. The second child of `n11196n` (`iushr`), the shift value, has to be a const load, which didn't happen until `id=95 name=tacticalGlobalRegisterAllocator` [1]
2. `OMR::treeSimplification` has to run after `tacticalGlobalRegisterAllocator` so that shifting by `0` can be folded away by `BINARY_IDENTITY_OP(Int, 0)` in [iushrSimplifier](https://github.com/eclipse/omr/blob/bcc94e429522b4a221412df052705a732c0ac689/compiler/optimizer/OMRSimplifierHandlers.cpp#L10181) [3] 

The method `openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>` is compiled at **warm**.  [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707) is used. [There is no `OMR::treeSimplification` after `OMR::cheapTacticalGlobalRegisterAllocatorGroup`](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L784C2-L784-L798) [4]. In fact, `OMR::treeSimplification` doesn't run after GRA in any of the optimization strategy, warm, hot, etc. 

Another way `n11196n` (`iushr`) might be folded away is
1. After  `id=84 name=trivialBlockExtension`, value `0` from `n11219n istore #1194` is populated to `n11197n iload #1194` before GRA
2. Run `OMR::treeSimplification` after 1 to fold away `n11196n` (`iushr`) [3]

@hzongaro To populate `0` from `n11219n istore #1194` to `n11197n iload #1194`, could this be done by `OMR::localCSE` or `OMR::localValuePropagationGroup`? The reason I'm asking is that [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707) already has [`OMR::localCSE` after `OMR::trivialBlockExtension` if it is enabled](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L774-L777) [5]. It's just that `TR_TrivialBlockExtension` doesn't request other optimizations to run. If `OMR::localCSE` can help populate  `0` from `n11219n istore #1194` to `n11197n iload #1194`, I wonder if we could just request `OMR::localCSE` from `TR_TrivialBlockExtension`. 

If populating `0` from `n11219n istore #1194` to `n11197n iload #1194` has to be done by VP, it would be more complicated because currently VP doesn't run after `trivialBlockExtension` [5]. I'm not sure if we'd like to change what's done in [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707) because of this one issue.





[1]
Before GRA
```
...
n11218n   BBStart <block_745> (freq 2137) (extension of previous block)                       [    0x74ba6244a230] bci=[31,3,3850] rc=0 vc=4626 vn=- li=- udi=- nc=0
n11219n   istore  <temp slot 33>[#1194  Auto] [flags 0x20000003 0x0 ]                         [    0x74ba6244a280] bci=[25,24,5299] rc=0 vc=4626 vn=- li=- udi=89 nc=1
n11216n     ==>iconst 0
...
n11166n   BBStart <block_742> (freq 2665) (extension of previous block)                       [    0x74ba624491f0] bci=[32,28,1764] rc=0 vc=4904 vn=- li=- udi=- nc=0
...
n11195n   istore  s3len<auto slot 6>[#916  Auto] [flags 0x3 0x0 ]                             [    0x74ba62449b00] bci=[32,44,1766] rc=0 vc=4904 vn=- li=- udi=121 nc=1
n11196n     iushr (normalizedShift )                                                          [    0x74ba62449b50] bci=[36,15,2120] rc=2 vc=4904 vn=- li=- udi=- nc=2 flg=0x8000
n4017n        ==>iload
n11197n       iload  <temp slot 33>[#1194  Auto] [flags 0x20000003 0x0 ] (X>=0 cannotOverflow )  [    0x74ba62449ba0] bci=[36,12,2120] rc=1 vc=4904 vn=- li=- udi=532 nc=0 flg=0x1100
```

After GRA
```
<optimization id=95 name=tacticalGlobalRegisterAllocator method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
...
         O^O GLOBAL REGISTER ASSIGNER:  change load var [000074BA62449BA0] of  symRef#1194 to load reg
         O^O GLOBAL REGISTER ASSIGNER:  change load var [000074BA62449BA0] of  symRef#1194 to load reg
...
n11218n   BBStart <block_745> (freq 2137) (extension of previous block)                       [    0x74ba6244a230] bci=[31,3,3850] rc=0 vc=12381 vn=- li=-4 udi=- nc=0
n12461n   astore  <temp slot 3>[#906  Auto] [flags 0x20000007 0x0 ]                           [    0x74ba62f126c0] bci=[25,16,5298] rc=0 vc=12381 vn=- li=- udi=- nc=1
n12453n     ==>aRegLoad
n11219n   iRegStore gr23                                                                      [    0x74ba6244a280] bci=[25,24,5299] rc=0 vc=12381 vn=- li=-4 udi=89 nc=1
n11216n     ==>iconst 0
...
n11166n   BBStart <block_742> (freq 2665) (extension of previous block)                       [    0x74ba624491f0] bci=[32,28,1764] rc=0 vc=12381 vn=- li=-4 udi=- nc=0
...
n11195n   iRegStore gr22                                                                      [    0x74ba62449b00] bci=[32,44,1766] rc=0 vc=12381 vn=- li=-4 udi=121 nc=1
n11196n     iushr (normalizedShift )                                                          [    0x74ba62449b50] bci=[36,15,2120] rc=4 vc=12381 vn=- li=- udi=- nc=2 flg=0x8000
n4017n        ==>iload
n11216n       ==>iconst 0
```

[2]
```
<optimization id=84 name=trivialBlockExtension method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
Performing 84: trivialBlockExtension
[  4828] O^O BLOCK EXTENSION: Mark block_219 as an extension of block_745
```

[3]
```c++
//**************************************
// Binary identity operation
//
// If the second child is a constant that represents an identity operation,
// replace this node with the first child.
//
#define BINARY_IDENTITY_OP(Type,NullValue)               \
   if (secondChild->getOpCode().isLoadConst() && secondChild->get##Type() == NullValue) \
      return s->replaceNode(node, firstChild, s->_curTree);
```

[4]
```
<optimization id=84 name=trivialBlockExtension method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=88 name=trivialDeadTreeRemoval method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=89 name=jProfilingRecompLoopTest method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
   <optgroup name=cheapTacticalGlobalRegisterAllocatorGroup>
<optimization id=94 name=redundantGotoElimination method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=95 name=tacticalGlobalRegisterAllocator method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=96 name=jProfilingValue method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=97 name=treeLowering method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
   <optgroup name=globalDeadStoreGroup>
<optimization id=98 name=globalDeadStoreElimination method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=100 name=deadTreesElimination method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=102 name=deadTreesElimination method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=104 name=redundantGotoElimination method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=105 name=compactLocals method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=106 name=globalLiveVariablesForGC method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=108 name=catchBlockProfiler method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=109 name=regDepCopyRemoval method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
<optimization id=110 name=hotFieldMarking method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
```

[5]

```
   { OMR::trivialBlockExtension                                                      },
   { OMR::localCSE,                                  OMR::IfEnabled                  },  //common up lit pool refs in the same block
   { OMR::deadTreesElimination,                      OMR::IfEnabled                  }, // cleanup at the end
   { OMR::treeSimplification,                        OMR::IfEnabledMarkLastRun       }, // Simplify non-normalized address computations introduced by prefetch insertion
   { OMR::trivialDeadTreeRemoval,                    OMR::IfEnabled                  }, // final cleanup before opcode expansion
   { OMR::jProfilingRecompLoopTest,                  OMR::IfLoops                    },
   { OMR::globalDeadStoreElimination,                OMR::IfVectorAPI                }, // global dead store removal
   { OMR::deadTreesElimination,                      OMR::IfVectorAPI                }, // cleanup after dead store removal
   { OMR::vectorAPIExpansion,                        OMR::IfVectorAPI                },
   { OMR::osrGuardRemoval,                           OMR::IfVectorAPI                },
   { OMR::cheapTacticalGlobalRegisterAllocatorGroup, OMR::IfEnabled                  },
```

**Comment by a7ehuo** [comment]
A summary of the issue below. For detailed description, please refer to [previous comment](https://github.com/eclipse-openj9/openj9/issues/17740#issuecomment-1624322286). 

There was one case on Power where right shift by `0` IL trees are not folded away [1]. Right shift by `0` IL trees appear after GRA[2].  The IL trees are not folded away because `treeSimplification` does not run after GRA in any of the optimization strategies. 

From what I can see, if we would like to catch this missed opportunity to fold away the right shift by `0` IL trees, two possible solutions:

1. Add `treeSimplification` after GRA in [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707)
2. Add/enable other optimization (localCSE? Or VP? Or other?) after `trivialBlockExtension` in [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707), which can populate store `0` to the temp used by shift `iushr` as shift amount, and then run `treeSimplification` afterwards
   - After `trivialBlockExtension`, the block that contains the shift `iushr` using the temp as the shift amount becomes an extension of the block that stores `0` to the temp. An optimization after `trivialBlockExtension` has to run to populate the `0` to the load in the later block. In solution 1, it's done by GRA[2]. GRA runs at a later stage in [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707). If it should be done before GRA, [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707) needs to be updated to first include an optimization after `trivialBlockExtension` to populate store `0` to the temp to the later load. Then afterwards, `treeSimplification` needs to run to fold away the shift by `0` IL trees

Both solutions add compilation time. Updating [cheapWarmStrategyOpts](https://github.com/eclipse-openj9/openj9/blob/548af364c146415e65306e530a27f2e3d52e1976/runtime/compiler/optimizer/J9Optimizer.cpp#L707) would impact all platforms and things. Meanwhile this issue is only observed on Power so far. I run the OpenJDK test that reported this issue in [Grinder over 100x](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/33801/). Not reproducible so far. As far as I know, there is no performance issue reported that's linked to the missed opportunity to fold away shift by 0 IL trees.

At this point, I'm too convinced if it's worth of pursuing either of the solutions. @vijaysun-omr @0xdaryl I'm wondering if you might be able to help shed some light. Should we leave this issue as it is for now and investigate further if more similar occasions are observed in the future? 

[1] https://github.com/eclipse-openj9/openj9/issues/17708#issuecomment-1614668232
[2]
Before GRA
```
...
n11218n   BBStart <block_745> (freq 2137) (extension of previous block)                       [    0x74ba6244a230] bci=[31,3,3850] rc=0 vc=4626 vn=- li=- udi=- nc=0
n11219n   istore  <temp slot 33>[#1194  Auto] [flags 0x20000003 0x0 ]                         [    0x74ba6244a280] bci=[25,24,5299] rc=0 vc=4626 vn=- li=- udi=89 nc=1
n11216n     ==>iconst 0
...
n11166n   BBStart <block_742> (freq 2665) (extension of previous block)                       [    0x74ba624491f0] bci=[32,28,1764] rc=0 vc=4904 vn=- li=- udi=- nc=0
...
n11195n   istore  s3len<auto slot 6>[#916  Auto] [flags 0x3 0x0 ]                             [    0x74ba62449b00] bci=[32,44,1766] rc=0 vc=4904 vn=- li=- udi=121 nc=1
n11196n     iushr (normalizedShift )                                                          [    0x74ba62449b50] bci=[36,15,2120] rc=2 vc=4904 vn=- li=- udi=- nc=2 flg=0x8000
n4017n        ==>iload
n11197n       iload  <temp slot 33>[#1194  Auto] [flags 0x20000003 0x0 ] (X>=0 cannotOverflow )  [    0x74ba62449ba0] bci=[36,12,2120] rc=1 vc=4904 vn=- li=- udi=532 nc=0 flg=0x1100
```
After GRA
```
<optimization id=95 name=tacticalGlobalRegisterAllocator method=openj9/internal/tools/attach/target/FileLock.lockFile(ZLjava/lang/String;Z)Z>
...
         O^O GLOBAL REGISTER ASSIGNER:  change load var [000074BA62449BA0] of  symRef#1194 to load reg
         O^O GLOBAL REGISTER ASSIGNER:  change load var [000074BA62449BA0] of  symRef#1194 to load reg
...
n11218n   BBStart <block_745> (freq 2137) (extension of previous block)                       [    0x74ba6244a230] bci=[31,3,3850] rc=0 vc=12381 vn=- li=-4 udi=- nc=0
n12461n   astore  <temp slot 3>[#906  Auto] [flags 0x20000007 0x0 ]                           [    0x74ba62f126c0] bci=[25,16,5298] rc=0 vc=12381 vn=- li=- udi=- nc=1
n12453n     ==>aRegLoad
n11219n   iRegStore gr23                                                                      [    0x74ba6244a280] bci=[25,24,5299] rc=0 vc=12381 vn=- li=-4 udi=89 nc=1
n11216n     ==>iconst 0
...
n11166n   BBStart <block_742> (freq 2665) (extension of previous block)                       [    0x74ba624491f0] bci=[32,28,1764] rc=0 vc=12381 vn=- li=-4 udi=- nc=0
...
n11195n   iRegStore gr22                                                                      [    0x74ba62449b00] bci=[32,44,1766] rc=0 vc=12381 vn=- li=-4 udi=121 nc=1
n11196n     iushr (normalizedShift )                                                          [    0x74ba62449b50] bci=[36,15,2120] rc=4 vc=12381 vn=- li=- udi=- nc=2 flg=0x8000
n4017n        ==>iload
n11216n       ==>iconst 0
```

**Comment by vijaysun-omr** [comment]
Thanks Annabelle. Two initial thoughts 

1. We should probably have a consistent story across different code generators for what is expected from the optimizer and what the code generators are themselves capable of handling. Do other code generators handle this case ?
 
2. I think it may be harder than first appears to guarantee that such unoptimized IL trees won't get into the code generator (as you sketched in your summary). In my opinion, depending on the optimizer for functional correctness feels like a bridge too far (even if we believed that that was the right expectation years ago). Something like a "cheap warm strategy" is specifically used to avoid taking up too much compile time and so adding passes there feels like a slippery slope (maybe what we do in this specific case does not add too much overhead but is it the last such case ?). Then there is the question of whether we are even able to run all the optimizations that may be needed at the right time for functional reasons. At least at one point I believe `endBlockSimplifier` (a routine in the simplifier) could not be run after GRA because it did not know about `GlRegDeps`. I don't know if that specific issue is fixed nowadays, but equally I don't know if other such issues might exist.

**Comment by a7ehuo** [comment]
>We should probably have a consistent story across different code generators for what is expected from the optimizer and what the code generators are themselves capable of handling. Do other code generators handle this case ?

Good point! I have a simple test (unsigned right shift by `0`) that reproduces [the assert on Power](https://github.com/eclipse-openj9/openj9/issues/17708) [1], and the same test passes in x86 [2] and Z [3]. 

Both x86 and Z code generators are able to handle unsigned right shift by `0`:

- x86 CG explicitly [processes shift amount as 0](https://github.com/eclipse/omr/blob/e10a1e55e1cbb4c4dbda9ec5d649373824d8d647/compiler/x/codegen/BinaryEvaluator.cpp#L2484-L2487) in `generateRegisterShift`
- Z CG explicitly [process shift amount as 0](https://github.com/eclipse/omr/blob/e10a1e55e1cbb4c4dbda9ec5d649373824d8d647/compiler/z/codegen/BinaryEvaluator.cpp#L1371-L1375)  in `genericIntShift`

With all the discussions and discovery, I'm more convinced now that no change needs to be done at this time in the Optimizer. 

[1]
**=== P ===** (hit the assert: rotate left and mask by 32)
```
------------------------------
 n19n     (  0)  iRegStore gr31                                                                       [    0x7cd1b2894cb0] bci=[-1,12,7] rc=0 vc=436 vn=- li=4 udi=- nc=1
 n18n     (  2)    iadd (in GPR_0087)                                                                 [    0x7cd1b2894c60] bci=[-1,11,7] rc=2 vc=436 vn=- li=4 udi=45136 nc=2
 n92n     (  0)      ==>iRegLoad (in GPR_0081) (cannotOverflow SeenRealReference )
 n17n     (  0)      iushr (in GPR_0086)                                                              [    0x7cd1b2894c10] bci=[-1,10,7] rc=0 vc=436 vn=- li=4 udi=44848 nc=2
 n92n     (  0)        ==>iRegLoad (in GPR_0081) (cannotOverflow SeenRealReference )
 n16n     (  0)        iconst 0 (X==0 X>=0 X<=0 )                                                     [    0x7cd1b2894bc0] bci=[-1,9,7] rc=0 vc=436 vn=- li=4 udi=- nc=0 flg=0x302
------------------------------

 [    0x7cd1b29eafa0]	10 	rlwinm 	GPR_0086, GPR_0081, 0000000000000020, 00000000FFFFFFFF 
 [    0x7cd1b29eb0c0]	11 	add 	GPR_0087, GPR_0081, GPR_0086
```

[2]
**=== x86 ===**  (pass)
```
------------------------------
 n19n     (  0)  iRegStore esi                                                                        [0x7f4b4f004c10] bci=[-1,12,5] rc=0 vc=320 vn=- li=4 udi=- nc=1
 n18n     (  2)    iadd (in GPR_0192)                                                                 [0x7f4b4f004bc0] bci=[-1,11,5] rc=2 vc=320 vn=- li=4 udi=47760 nc=2
 n94n     (  0)      ==>iRegLoad (in GPR_0192) (cannotOverflow SeenRealReference )
 n17n     (  0)      iushr (in GPR_0192)                                                              [0x7f4b4f004b70] bci=[-1,10,5] rc=0 vc=320 vn=- li=4 udi=47760 nc=2
 n94n     (  0)        ==>iRegLoad (in GPR_0192) (cannotOverflow SeenRealReference )
 n16n     (  0)        iconst 0 (X==0 X>=0 X<=0 )                                                     [0x7f4b4f004b20] bci=[-1,9,5] rc=0 vc=320 vn=- li=4 udi=1 nc=0 flg=0x302
------------------------------

 [0x7f4b4f15d010]	add	GPR_0192, GPR_0192		# ADD4RegReg
```

[3]
**=== Z ===** (pass)
```
------------------------------
 n19n     (  0)  istore  <parm 1 I>[#397  Parm] [flags 0xc0000103 0x0 ]                               [     0x3ff6f004ce0] bci=[-1,12,5] rc=0 vc=83 vn=- li=4 udi=- nc=1
 n18n     (  0)    iadd (in GPR_0070)                                                                 [     0x3ff6f004c90] bci=[-1,11,5] rc=0 vc=83 vn=- li=4 udi=- nc=2
 n14n     (  0)      iload  <parm 1 I>[#397  Parm] [flags 0xc0000103 0x0 ] (in GPR_0069) (cannotOverflow )  [     0x3ff6f004b50] bci=[-1,7,5] rc=0 vc=83 vn=- li=4 udi=- nc=0 flg=0x1000
 n17n     (  0)      iushr (in GPR_0070)                                                              [     0x3ff6f004c40] bci=[-1,10,5] rc=0 vc=83 vn=- li=4 udi=- nc=2
 n14n     (  0)        ==>iload (in GPR_0069) (cannotOverflow )
 n16n     (  0)        iconst 0 (X==0 X>=0 X<=0 )                                                     [     0x3ff6f004bf0] bci=[-1,9,5] rc=0 vc=83 vn=- li=4 udi=- nc=0 flg=0x302
------------------------------

 [     0x3ff6f130070]	                       L       GPR_0069, Parm[<parm 1 I>] ?+8(GPR5)
 [     0x3ff6f1301b0]	                       LR      GPR_0070,GPR_0069	
 [     0x3ff6f130290]	                       AR      GPR_0070,GPR_0069	
 [     0x3ff6f130460]	                       ST      GPR_0070, Parm[<parm 1 I>] ?+8(GPR5)
```

**Comment by hzongaro** [comment]
Thanks for the all the investigation, @a7ehuo.

> Both x86 and Z code generators are able to handle unsigned right shift by 0:

May I ask you to check into aarch64 as well?

**Comment by a7ehuo** [comment]
>May I ask you to check into aarch64 as well?

The IL tree with unsigned right shift by `0` is also processed successfully by aarch64 code generator [1]. The shift amount is checked/used in [generateLogicalShiftRightImmInstruction](https://github.com/eclipse/omr/blob/b1af0b4c8fbbfaa033846148eba1e7ac129b026e/compiler/aarch64/codegen/GenerateInstructions.cpp#L416). It allows `0`, however it doesn't explicitly do anything about it.  

```c++
   TR_ASSERT_FATAL(shiftAmount < (is64bit ? 64 : 32), "Shift amount out of range.");

   TR::InstOpCode::Mnemonic op = is64bit ? TR::InstOpCode::ubfmx : TR::InstOpCode::ubfmw;
   uint32_t imms = is64bit ? 0x3f : 0x1f;
   uint32_t immr = shiftAmount;
   uint32_t imm = (immr << 6) | imms;
```


[1]
**=== aarch64 === (pass)**
```
------------------------------
 n17n     (  0)  iRegStore x1                                                                         [    0xfffff43686d0] bci=[-1,10,4] rc=0 vc=418 vn=- li=4 udi=- nc=1
 n16n     (  2)    iushr (in GPR_0100)                                                                [    0xfffff4368680] bci=[-1,9,4] rc=2 vc=418 vn=- li=4 udi=63360 nc=2
 n86n     (  0)      ==>iRegLoad (in GPR_0097) (cannotOverflow SeenRealReference )
 n15n     (  0)      iconst 0 (X==0 X>=0 X<=0 )                                                       [    0xfffff4368630] bci=[-1,8,4] rc=0 vc=418 vn=- li=4 udi=- nc=0 flg=0x302
------------------------------

 [    0xfffff44cf810]   9       lsrw    GPR_0100, GPR_0097, 0
```

**Comment by hzongaro** [comment]
@knn-k, this is for your consideration.  From the investigation that @a7ehuo did, it looks like code generation on x86 and z will avoid generating a shift instruction if there is a constant shift amount of zero, but not on aarch64.  There are changes underway for code generation on Power in eclipse/omr#7057 to handle this case as well.

**Comment by a7ehuo** [comment]
Btw, it looks to me `arm` code checks if shift amount is `0` to avoid generating shift instruction in [ishiftEvaluator](https://github.com/eclipse/omr/blob/b1af0b4c8fbbfaa033846148eba1e7ac129b026e/compiler/arm/codegen/BinaryEvaluator.cpp#L805), but I haven't found similar code in `aarc64` during my investigation as [mentioned in the above](https://github.com/eclipse-openj9/openj9/issues/17740#issuecomment-1634873566). 

```c++
   if (secondChild->getOpCodeValue() == TR::iconst)
      {
      if ((secondChild->getInt() & 0x1f) == 0)
         {
         if (firstChild->getReferenceCount() == 1)
            {
            trgReg = src1Reg;
            }
```

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/7061 for AArch64.

I tried running `java/lang/ProcessBuilder/Basic.java#id0` with JDK 20, but I don't find the method `FileLock.lockFile()` in the generated JIT trace files.
Is there any simple testcase available for this?  Thanks.

**Comment by a7ehuo** [comment]
>Is there any simple testcase available for this? 

Sorry I should've mentioned it earlier. Below is a simple test I used to test `iushr`. Running with `disableTreeSimplification` makes sure right shift by `0` won't be folded away by the optimizer, which simulates what happened in #17708

```
$JAVA_BIN '-Xjit:count=1,disableAsyncCompilation,{TestShift.test*}(disableTreeSimplification,traceFull,traceILGen,traceCG,log=jitlog)' TestShift
```

```java
public class TestShift {
   public static int test(int loop, int val) {
      for (int i=0; i<loop; ++i) {
         val = val >>> 0;
      }
      return val;
   }
   public static void main(String[] args) {
      int val1 = 0xABCDABCD;
      int val2 = 0xABCDABCD;
      int loop = 4;

      System.out.println(test(loop, val1));
      System.out.println(test(loop, val2));
   }
}
```

**Comment by knn-k** [comment]
I made sure my PR https://github.com/eclipse/omr/pull/7061 for AArch64 works as expected, using `TestShift` above.

**Comment by hzongaro** [comment]
Given the fact that code generators for all supported platforms will now fold a shift by a constant amount of zero, and given [Vijay's comment](#issuecomment-1626248248) pointing out why we might not want to force optimizations that would likely catch such cases, I think we say that the investigation called for by this issue has been completed, so I will close this issue.  If anyone would like to argue for reopening it, please feel free.
