### ISSUE TITLE
Remove test_countStackFrames() on JDKNext

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#17772]
`Thread.countStackFrames()` is removed from Java 22: https://bugs.openjdk.org/browse/JDK-8309196. 

We are seeing the following error in Java 22 builds:

```
10:54:55      [javac] /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal_testList_0/aqa-tests/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Thread.java:246: error: cannot find symbol
10:54:55      [javac] 			AssertJUnit.assertTrue("Test failed.", Thread.currentThread().countStackFrames() == 0);
10:54:55      [javac] 			                                                             ^
10:54:55      [javac]   symbol:   method countStackFrames()
10:54:55      [javac]   location: class Thread
```
The following test should be removed/disabled on JDKNext (JDK 22):
https://github.com/eclipse-openj9/openj9/blob/6426c11175aa2d8f664d61a516ef7633a07d8383/test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Thread.java#L243

**Comment by JasonFengJ9** [comment]
The test in question can only be run within JDK21 and earlier JDK.
