### ISSUE TITLE
Make j9javaaccessflags.h more readable

### ISSUE THREAD

**Issue by theresa-m** [eclipse-openj9/openj9#17785]
The constants in [j9javaaccessflags.h](https://github.com/eclipse-openj9/openj9/blob/master/runtime/oti/j9javaaccessflags.h) are not organized in a way where it is obvious which bits are available for new entries. The suggestion in this issue is to reorganize these in a more manageable way.

**Comment by theresa-m** [comment]
@hangshao0 it looks like J9AccClassHasIdentity added in https://github.com/eclipse-openj9/openj9/pull/16041 has the same flag value as J9AccSuper. Can you confirm if that's correct?

**Comment by theresa-m** [comment]
The other odd one is that J9AccSynthetic appears to have been used in `extraModifiers` in early versions of Java and `modifiers` from Java 1.5
https://github.com/eclipse-openj9/openj9/blob/master/runtime/bcutil/ROMClassBuilder.cpp#L1302-L1306
I think it is safe to remove this from `extraModifiers`

**Comment by hangshao0** [comment]
> @hangshao0 it looks like J9AccClassHasIdentity added in https://github.com/eclipse-openj9/openj9/pull/16041 has the same flag value as J9AccSuper. Can you confirm if that's correct?

Yes, see [here](https://cr.openjdk.org/~dlsmith/jep8277163/jep8277163-20220519/specs/value-objects-jvms.html#jvms-4.1) that `ACC_SUPER` flag is repurposed to indicate identity classes.

**Comment by theresa-m** [comment]
Thanks, I'll add a comment about that in the file.
