### ISSUE TITLE
JDK21 serviceability/jvmti/vthread/SuspendResume1&2 Fatal error: test_vthread_resume[_all]: error in JVMTI ResumeThread

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17791]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/2628/consoleFull)(`cent7-aarch64-1`):
```
10:38:11  openjdk version "21-internal" 2023-09-19
10:38:11  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21aarch64linuxPersonal)
10:38:11  Eclipse OpenJ9 VM (build master-6bae0289b9e, JRE 21 Linux aarch64-64-Bit Compressed References 20230711_10 (JIT enabled, AOT enabled)
10:38:11  OpenJ9   - 6bae0289b9e
10:38:11  OMR      - bcc94e42952
10:38:11  JCL      - 73fae096864 based on jdk-21+30)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&EXTRA_DOCKER_ARGS=&PLATFORM=aarch64_linux&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=&JENKINS_KEY=&LIGHT_WEIGHT_CHECKOUT=true&ARTIFACTORY_SERVER=na.artifactory.swg-devops&USE_JRE=false&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&EXIT_FAILURE=false&EXIT_SUCCESS=false&JCK_GIT_BRANCH=main&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&OPENJ9_BRANCH=master&OPENJ9_SHA=6bae0289b9eb7748b84521bfd18d0cecf5c84785&RELEASE_TAG=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&CODE_COVERAGE=false&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=&OPENLIBERTY_SHA=&UPSTREAM_TEST_JOB_NUMBER=33922&DOCKERIMAGE_TAG=&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&OPENJDK_SHA=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&BUILDS_TO_KEEP=100&TIME_LIMIT=20&PARALLEL=None&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_0,serviceability_jvmti_j9_0,serviceability_jvmti_j9_0,serviceability_jvmti_j9_0,serviceability_jvmti_j9_0,serviceability_jvmti_j9_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Grinder&VENDOR_TEST_DIRS=functional&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&GENERATE_JOBS=true&KEEP_REPORTDIR=true&RERUN_ITERATIONS=0&LABEL=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F10%2FOpenJ9-JDK21-aarch64_linux-20230711-073423.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F10%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&ITERATIONS=10&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JCK_GIT_REPO=&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&TEST_IMAGES_REQUIRED=true&ARTIFACTORY_ROOT_DIR=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&TKG_ITERATIONS=1&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&ADDITIONAL_ARTIFACTS_REQUIRED=&JVM_OPTIONS=) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
10:54:09  variation: Mode150
10:54:09  JVM_OPTIONS:  -XX:+UseCompressedOops 

10:56:08  TEST: serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default

10:56:08  STDERR:
10:56:08  
10:56:08  Fatal error: test_vthread_resume_all: error in JVMTI ResumeThread

10:56:08  TEST RESULT: Failed. Unexpected exit from test [exit code: 87]
10:56:08  --------------------------------------------------
10:56:16  TEST: serviceability/jvmti/vthread/SuspendResume1/SuspendResume1.java#default

10:56:16  STDERR:
10:56:16  
10:56:16  Fatal error: test_thread_resume: error in JVMTI ResumeThread

10:56:16  TEST RESULT: Failed. Unexpected exit from test [exit code: 87]
10:56:16  --------------------------------------------------
10:56:26  Test results: passed: 116; failed: 2
10:56:38  Report written to /home/jenkins/workspace/Grinder_iteration_0/jvmtest/openjdk/report/html/report.html
10:56:38  Results written to /home/jenkins/workspace/Grinder_iteration_0/aqa-tests/TKG/output_16892600481225/serviceability_jvmti_j9_0/work
10:56:38  Error: Some tests failed or other problems occurred.
10:56:38  -----------------------------------
10:56:38  serviceability_jvmti_j9_0_FAILED
```

https://github.com/eclipse-openj9/openj9/issues/17784#issuecomment-1634720017
serviceability/jvmti/vthread/SuspendResume1/SuspendResume1.java - 1 failure (in [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/2628/))
serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java - 2 failures (in [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_0/2628/) and [grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_3/1990/))

**Comment by babsingh** [comment]
Fixed by #17802.
