### ISSUE TITLE
Difference in behaviour of -Xdebug -Djava.compiler=NONE between OpenJ9 and HotSpot

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse-openj9/openj9#17808]
I'm opening this issue not in the expectation of any changes, but primarily to document the difference.

This difference relates to the interaction of two extremely old command line options, -Djava.compiler and -Xdebug.

-Djava.compiler=NONE can be used to disable the JIT compiler, and this works on both JVMs

Behaviour with HotSpot JVM, "interpreted mode" indicates no JIT:

```
$ bin/java -Djava.compiler=NONE -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, interpreted mode, sharing) 
```
And with Semeru, "JIT disabled" similarly indicates the JIT has been disabled:

```
$ bin/java -Djava.compiler=NONE -version
openjdk version "17.0.2" 2022-01-18
IBM Semeru Runtime Open Edition 17.0.2.0 (build 17.0.2+8)
Eclipse OpenJ9 VM 17.0.2.0 (build openj9-0.30.0, JRE 17 Linux amd64-64-Bit Compressed References 20220128_115 (JIT disabled, AOT disabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 64cd399ca28 based on jdk-17.0.2+8)
```

`-Xdebug` is an obsolete option documented as "Does nothing" (https://docs.oracle.com/en/java/javase/20/docs/specs/man/java.html#extra-options-for-java), however, with HotSpot, when used in conjunction with -Djava.compiler=NONE it over-rides that option and re-enables the JIT. This interaction does not happen with OpenJ9.

HotSpot, "mixed mode" indicates the JIT is enabled:

```
$ bin/java -Djava.compiler=NONE -Xdebug -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
```

Semeru, JIT still disabled:

```
$ bin/java -Djava.compiler=NONE -Xdebug -version
openjdk version "17.0.2" 2022-01-18
IBM Semeru Runtime Open Edition 17.0.2.0 (build 17.0.2+8)
Eclipse OpenJ9 VM 17.0.2.0 (build openj9-0.30.0, JRE 17 Linux amd64-64-Bit Compressed References 20220128_115 (JIT disabled, AOT disabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 64cd399ca28 based on jdk-17.0.2+8)
```

The upshot of this is that an application run with the same combination of command line options including both -Xdebug and -Djava.compiler=NONE will run with the JIT on HotSpot and with only the interpreter on OpenJ9. The end user is likely to experience a significant performance difference in the two cases.

How did we get to here? In the last years of the previous century debug mode was only supported by the interpreter and so the standard command line for debugging included both -Xdebug and -Djava.compiler=NONE. When the HotSpot compiler was updated to support debug it was a major step forward, except that all the tools and scripts in the world already had the above options in place and so the majority of users wouldn't see the benefit. Instead of facing this head on and requiring all the tooling to be changed to match, the JVM was modified to ignore the java.compiler option if -Xdebug was set, and this behaviour remains to this day. The documentation claiming "Does nothing" for -Xdebug sadly overlooks this detail, adding to the confusion. There is currently an open bug report proposing the removal of -Xdebug that details this history (and from which most of the above was drawn): https://bugs.openjdk.org/browse/JDK-8227229. The original bug report leading to the 'fix' for -Xdebug is https://bugs.java.com/bugdatabase/view_bug?bug_id=4516835

Ok this is fascinating, but surely irrelevant as no-one would be using these options now, right?
Well, not quite. Searching for the above options, often as a triplet including -Xnoagent, will discover *many* hits, including in currently published product documentation and in samples shipped with current JVMs. I became aware of the problem after dealing with a report of poor performance where the options are currently embedded in a debug launch script. Hence this issue, to raise awareness and document the difference.

**Comment by JamesKingdon** [comment]
And a final twist, it looks like support for the java.compiler property has very recently been removed
https://bugs.openjdk.org/browse/JDK-8041676

**Comment by DanHeidinga** [comment]
And I believe -Xdebug support is being removed as well.

This doesn't seem like it's worth changing in OpenJ9 given it appears to be an extreme corner case in functionality that's being removed.
