### ISSUE TITLE
JDK21 serviceability_jvmti_j9_0_FAILED serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default Fatal error: test_vthread_resume_half: error in JVMTI ResumeThread

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17869]
Failure link
------------

From [an internal grinder build](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_2/2293/consoleFull)(`paix906`) - launched at https://github.com/eclipse-openj9/openj9/issues/17865
```
08:08:05  openjdk version "21-internal" 2023-09-19
08:08:05  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21ppc64aixPersonal)
08:08:05  Eclipse OpenJ9 VM (build master-c9a98669642, JRE 21 AIX ppc64-64-Bit Compressed References 20230726_28 (JIT enabled, AOT enabled)
08:08:05  OpenJ9   - c9a98669642
08:08:05  OMR      - 436bad3c438
08:08:05  JCL      - 78015256cbd based on jdk-21+31)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&EXTRA_DOCKER_ARGS=&PLATFORM=ppc64_aix&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=&JENKINS_KEY=&LIGHT_WEIGHT_CHECKOUT=true&ARTIFACTORY_SERVER=na.artifactory.swg-devops&USE_JRE=false&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&EXIT_FAILURE=false&EXIT_SUCCESS=false&JCK_GIT_BRANCH=main&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&OPENJ9_BRANCH=master&OPENJ9_SHA=c9a98669642cf02546c38c3b295417e98340915d&RELEASE_TAG=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&CODE_COVERAGE=false&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=&OPENLIBERTY_SHA=&UPSTREAM_TEST_JOB_NUMBER=34157&DOCKERIMAGE_TAG=&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&OPENJDK_SHA=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&BUILDS_TO_KEEP=100&TIME_LIMIT=20&PARALLEL=None&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_0,serviceability_jvmti_j9_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Grinder&VENDOR_TEST_DIRS=functional&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&GENERATE_JOBS=true&KEEP_REPORTDIR=true&RERUN_ITERATIONS=0&LABEL=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_ppc64_aix_Personal%2F28%2FOpenJ9-JDK21-ppc64_aix-20230726-060412.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_ppc64_aix_Personal%2F28%2Ftest-images.tar.gz&ADOPTOPENJDK_BRANCH=master&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&ITERATIONS=10&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JCK_GIT_REPO=&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&DEBUG_IMAGES_REQUIRED=false&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&TEST_IMAGES_REQUIRED=true&ARTIFACTORY_ROOT_DIR=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&TKG_ITERATIONS=1&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&ADDITIONAL_ARTIFACTS_REQUIRED=&JVM_OPTIONS=) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
11:54:29  variation: Mode150
11:54:29  JVM_OPTIONS:  -XX:+UseCompressedOops 

12:04:30  TEST: serviceability/jvmti/vthread/SuspendResume2/SuspendResume2.java#default

12:04:30  STDERR:
12:04:30  
12:04:30  Fatal error: test_vthread_resume_half: error in JVMTI ResumeThread

12:04:30  --------------------------------------------------
12:04:32  Test results: passed: 121; failed: 2
12:04:56  Report written to /home/jenkins/workspace/Grinder_iteration_2/jvmtest/openjdk/report/html/report.html
12:04:56  Results written to /home/jenkins/workspace/Grinder_iteration_2/aqa-tests/TKG/output_16904731027876/serviceability_jvmti_j9_0/work
12:04:56  Error: Some tests failed or other problems occurred.
12:04:56  -----------------------------------
12:04:56  serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34157/console) - 1/50 failing rate

https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_3/2017/consoleFull
```
11:41:45  TEST: serviceability/jvmti/vthread/SuspendResumeAll/SuspendResumeAll.java#default

11:41:45  ## Java: runIt FAILED: status from native Agent: 2
11:41:45  STDERR:
11:41:45  java.lang.RuntimeException: FAILED: unexpected status: 2
11:41:45  	at SuspendResumeAll.main(SuspendResumeAll.java:78)
11:41:45  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
11:41:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
11:41:45  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
11:41:45  	at java.base/java.lang.Thread.run(Thread.java:1595)
11:41:45  
11:41:45  JavaTest Message: Test threw exception: java.lang.RuntimeException: FAILED: unexpected status: 2

12:03:30  TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

12:03:30  TEST RESULT: Error. Program `/home/jenkins/workspace/Grinder_iteration_3/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 961851ms).
```

FYI @babsingh

**Comment by babsingh** [comment]
Moving to the 0.44 release since the failure is highly intermittent.

**Comment by JasonFengJ9** [comment]
[JDK21 x86-64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_mac/11/)(`mac11x64rt04`)
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202310261403 (build 21.0.1-beta+12-202310261403)
Eclipse OpenJ9 VM 21.0.1+12-202310261403 (build master-66e3fd1da, JRE 21 Mac OS X amd64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
OpenJ9   - 66e3fd1da
OMR      - 071c0c25b
JCL      - c06eaf638 based on jdk-21.0.1+12)

[2023-10-26T15:00:50.188Z] variation: Mode650
[2023-10-26T15:00:50.188Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-10-26T15:03:11.620Z] TEST: serviceability/jvmti/vthread/SuspendResumeAll/SuspendResumeAll.java#no-vmcontinuations

[2023-10-26T15:03:11.621Z] STDERR:
[2023-10-26T15:03:11.621Z] java.lang.RuntimeException: FAILED: unexpected status: 2
[2023-10-26T15:03:11.621Z] 	at SuspendResumeAll.main(SuspendResumeAll.java:78)
[2023-10-26T15:03:11.621Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2023-10-26T15:03:11.621Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2023-10-26T15:03:11.621Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
[2023-10-26T15:03:11.621Z] 	at java.base/java.lang.Thread.run(Thread.java:1595)

[2023-10-26T15:03:30.804Z] serviceability_jvmti_j9_1_FAILED
```

**Comment by babsingh** [comment]
Moving it back to the 0.42 release due to the new failure.

**Comment by babsingh** [comment]
re https://github.com/eclipse-openj9/openj9/issues/17869#issuecomment-1783515379: This is a new failure, which is seen for the first time. Opened https://github.com/eclipse-openj9/openj9/issues/18370 for it.

**Comment by babsingh** [comment]
Fixed via
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/59
- https://github.com/eclipse-openj9/openj9/pull/18420
- https://github.com/eclipse-openj9/openj9/pull/18439
- https://github.com/eclipse-openj9/openj9/pull/18421
- https://github.com/eclipse-openj9/openj9/pull/18432
- https://github.com/eclipse-openj9/openj9/pull/18453
