### ISSUE TITLE
cmdLineTester_criu_jitserverPostRestore_2_FAILED [ERR] can't bind server address: Address already in use

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17863]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly/522/tapResults/ `ub16x64j98`:
```
22:26:52  openjdk version "17.0.8-internal" 2023-07-18
22:26:52  OpenJDK Runtime Environment (build 17.0.8-internal+0-adhoc.****.BuildJDK17x86-64linuxNightly)
22:26:52  Eclipse OpenJ9 VM (build master-63a90ea2642, JRE 17 Linux amd64-64-Bit Compressed References 20230724_539 (JIT enabled, AOT enabled)
22:26:52  OpenJ9   - 63a90ea2642
22:26:52  OMR      - 605ec7ca239
22:26:52  JCL      - bf3d2d75916 based on jdk-17.0.8+7)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=cmdLineTester_criu_jitserverPostRestore_2&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Nightly&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_x86-64_linux_Nightly%2F539%2FOpenJ9-JDK17-x86-64_linux-20230724-220725.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_x86-64_linux_Nightly%2F539%2Ftest-images.tar.gz&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=ci-eclipse-openj9&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17.git&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=63a90ea264222f664cc8880116af8e20e03ac0fb&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=%21sw.os.cent.6&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=2&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=functional&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=Dynamic) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
variation: -Xjit:vlog=vlog
JVM_OPTIONS:  -Xjit:vlog=vlog 

Testing: Test -Xnojit -Xnoaot
Test start time: 2023/07/25 01:27:12 Atlantic Standard Time
Running command: bash /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu/criuJitServerScript.sh /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/criu /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin " -Xjit:vlog=vlog " org.openj9.criu.OptionsFileTest "JitOptionsTest -XX:+UseJITServer -Xnojit -Xnoaot" 1 false false
Time spent starting: 4 milliseconds
Time spent executing: 2745 milliseconds
Test result: FAILED
Output from test:
 [OUT] start running script
 [OUT] export GLIBC_TUNABLES=glibc.cpu.hwcaps=-XSAVEC,-XSAVE,-AVX2,-ERMS,-AVX,-AVX_Fast_Unaligned_Load
 [OUT] export LD_BIND_NOT=on
 [OUT] Starting /home/jenkins/workspace/Test_openjdk17_j9_sanity.functional_x86-64_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/jitserver -XX:JITServerPort=52538
 [OUT] JITSERVER DOES NOT EXIST
 [OUT] finished script
 [ERR] can't bind server address: Address already in use
 [ERR] 
 [ERR] JITServer is ready to accept incoming requests
>> Success condition was not found: [Output match: Killed]
>> Required condition was not found: [Output match: Pre-checkpoint]
>> Success condition was not found: [Output match: Post-checkpoint]
>> Failure condition was not found: [Output match: CRIU is not enabled]
>> Failure condition was not found: [Output match: Operation not permitted]
>> Success condition was not found: [Output match: Some or all compiled code in the code cache invalidated post restore.]
>> Success condition was not found: [Output match: JIT compilation disabled post restore.]
>> Success condition was not found: [Output match: AOT load and compilation disabled post restore.]
>> Success condition was not found: [Output match: Thread pid mismatch]
>> Success condition was not found: [Output match: do not match expected]
>> Success condition was not found: [Output match: Unable to create a thread:]
>> Success condition was not found: [Output match: JITSERVER EXISTS]
>> Success condition was not found: [Output match: JITSERVER STILL EXISTS]
>> Failure condition was found: [Output match: JITSERVER DOES NOT EXIST]
>> Failure condition was not found: [Output match: JITSERVER NO LONGER EXISTS]

---TEST RESULTS---
Number of PASSED tests: 4 out of 5
Number of FAILED tests: 1 out of 5

---SUMMARY OF FAILED TESTS---
Test -Xnojit -Xnoaot
-----------------------------

-----------------------------------
cmdLineTester_criu_jitserverPostRestore_2_FAILED
```

**Comment by dsouzai** [comment]
I think this is the same issue as https://github.com/eclipse-openj9/openj9/issues/17823

**Comment by JasonFengJ9** [comment]
Okay, closing as dup of https://github.com/eclipse-openj9/openj9/issues/17823
