### ISSUE TITLE
JDK21 serviceability_jvmti_j9_0 Fatal error: Error in ResumeThread & get_method_class_name: error in JVMTI GetMethodDeclaringClass

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17865]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix_Personal/6/consoleFull)(`paix911`):
```
08:08:05  openjdk version "21-internal" 2023-09-19
08:08:05  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21ppc64aixPersonal)
08:08:05  Eclipse OpenJ9 VM (build master-c9a98669642, JRE 21 AIX ppc64-64-Bit Compressed References 20230726_28 (JIT enabled, AOT enabled)
08:08:05  OpenJ9   - c9a98669642
08:08:05  OMR      - 436bad3c438
08:08:05  JCL      - 78015256cbd based on jdk-21+31)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,jdk_other_0,jdk_other_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_ppc64_aix_Personal%2F28%2FOpenJ9-JDK21-ppc64_aix-20230726-060412.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_ppc64_aix_Personal%2F28%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=c9a98669642cf02546c38c3b295417e98340915d&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
08:12:32  variation: Mode150
08:12:32  JVM_OPTIONS:  -XX:+UseCompressedOops 

08:17:58  TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

08:17:58  STDERR:
08:17:58  
08:17:58  Fatal error: Error in ResumeThread
08:17:58  
08:17:58  Fatal error: get_method_class_name: error in JVMTI GetMethodDeclaringClass

08:17:58  TEST RESULT: Failed. Unexpected exit from test [exit code: 87]
08:17:58  --------------------------------------------------
08:22:08  Test results: passed: 122; failed: 1
08:22:08  Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64_aix_Personal/jvmtest/openjdk/report/html/report.html
08:22:08  Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64_aix_Personal/aqa-tests/TKG/output_16903735147351/serviceability_jvmti_j9_0/work
08:22:08  Error: Some tests failed or other problems occurred.
08:22:08  -----------------------------------
08:22:08  serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34157/) - 11/50 failing rate

FYI @babsingh

**Comment by JasonFengJ9** [comment]
[JDK21 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix_Personal/14/consoleFull)(`paix824`)
```
15:50:15  variation: Mode150
15:50:15  JVM_OPTIONS:  -XX:+UseCompressedOops 

15:56:07  TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

15:56:07  STDERR:
15:56:07  
15:56:07  Fatal error: Error in ResumeThread
15:56:07  
15:56:07  Fatal error: get_method_class_name: error in JVMTI GetMethodDeclaringClass

16:00:32  serviceability_jvmti_j9_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK21 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix_Personal/21/consoleFull)(`paix826`)
```
21:07:54  TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

21:07:54  STDERR:
21:07:54  
21:07:54  Fatal error: Error in ResumeThread
21:07:54  
21:07:54  Fatal error: get_method_class_name: error in JVMTI GetMethodDeclaringClass

21:13:18  serviceability_jvmti_j9_0_FAILED
```

**Comment by babsingh** [comment]
Moving to the 0.44 release since the failure is highly intermittent.

**Comment by JasonFengJ9** [comment]
[JDK21 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix/10/)(`paix816`)
```
java version "21.0.1-beta" 2023-10-17
IBM Semeru Runtime Certified Edition 21.0.1+12-202310261948 (build 21.0.1-beta+12-202310261948)
Eclipse OpenJ9 VM 21.0.1+12-202310261948 (build master-39fd615b3, JRE 21 AIX ppc64-64-Bit Compressed References 20231026_22 (JIT enabled, AOT enabled)
OpenJ9   - 39fd615b3
OMR      - 071c0c25b
JCL      - c06eaf638 based on jdk-21.0.1+12)

[2023-10-26T21:39:03.456Z] variation: Mode650
[2023-10-26T21:39:03.456Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-10-26T21:45:25.093Z] TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

[2023-10-26T21:45:25.097Z] STDERR:
[2023-10-26T21:45:25.097Z] 
[2023-10-26T21:45:25.097Z] Fatal error: Error in ResumeThread
[2023-10-26T21:45:25.097Z] 
[2023-10-26T21:45:25.097Z] Fatal error: get_method_class_name: error in JVMTI GetMethodDeclaringClass

[2023-10-26T21:50:51.190Z] serviceability_jvmti_j9_1_FAILED
```

**Comment by pshipton** [comment]
Having two failures in a test cycle doesn't seem to meet the definition of highly intermittent. Moving back to the Java 21 milestone while we consider this.

**Comment by JasonFengJ9** [comment]
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_linux/13/)(`ubu20-aarch64-2`)
```
[2023-11-11T17:24:55.887Z] TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

[2023-11-11T17:24:55.889Z] STDERR:
[2023-11-11T17:24:55.889Z] 
[2023-11-11T17:24:55.889Z] Fatal error: Error in ResumeThread
[2023-11-11T17:24:55.889Z] 
[2023-11-11T17:24:55.889Z] Fatal error: jvmti_common get_carrier_thread: Error in JVMTI extension GetCarrierThread
```

**Comment by babsingh** [comment]
Fixed via
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/59
- https://github.com/eclipse-openj9/openj9/pull/18420
- https://github.com/eclipse-openj9/openj9/pull/18439
- https://github.com/eclipse-openj9/openj9/pull/18421
- https://github.com/eclipse-openj9/openj9/pull/18432
- https://github.com/eclipse-openj9/openj9/pull/18453
