### ISSUE TITLE
[FFI] Mixed code in the JDK21 extension repo on Power

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#17884]
I notice that https://github.com/ibmruntimes/openj9-openjdk-jdk21/tree/openj9/src/java.base/share/classes/jdk/internal/foreign/abi/ppc64 are currently merged with the Hostpot specific code intended for `pLinux` as follows:
/linux
ABIv2CallArranger.java
CallArranger.java
PPC64Architecture.java
TypeClass.java

which is wrong as these code are specific to the Hotspot implementation which doesn't belong the `openj9` branch.

If we keep them there, it is easy to mess things up in compilation with such confusion.

FYI: @tajila, @pshipton

**Comment by ChengJin01** [comment]
@tajila  & @keithc-ca,

I am considering to remove these files/folders from https://github.com/ibmruntimes/openj9-openjdk-jdk21/tree/openj9/src/java.base/share/classes/jdk/internal/foreign/abi/ppc64 if you have no objection to this.

**Comment by keithc-ca** [comment]
In what way is the code specific to hotspot? I would expect the implementation to respect the ABI of the target platform which should be independent of any JVM implementation.

**Comment by ChengJin01** [comment]
Technically, we don't use any of these code there from OpenJ9 perspective as they are totally different in implementation. Keeping them there is misleading & easy to make mistakes in the future given our own code in the OpenJDK extension is only linked to our own FFI implementation.

**Comment by ChengJin01** [comment]
I also notice that https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/CallArranger.java has been changed to point to the FFI implementation in OpenJ9 when merging the latest `master` branch.

**Comment by ChengJin01** [comment]
As discussed with @keithc-ca offline, it is reasonable to keep these generic code in OpenJDK to avoid any conflicts from upstream, in which case we need to figure out a way to keep both AIX and pLinux (from OpenJ9 perspective) work correctly with all unnecessary code removed.

**Comment by ChengJin01** [comment]
I will get back to work on this issue later after my vacation next week.

**Comment by ChengJin01** [comment]
With my solution at https://github.com/ChengJin01/openj9-openjdk-jdk21/commit/9680612da89bbc0b644d4ff40853bbfadd48c768, it works good as expected on Power (AIX & pLinux) by verifying the FFI specific test suites in OpenJ9/Jtreg.

**Comment by ChengJin01** [comment]
Close this issue as all related PRs are merged to the repo.
