### ISSUE TITLE
Facing issue with AIX Java  semeru version 17.0.5. failed to open </root/jdk-17.0.5+8-jre/lib/default/libjvm.so>

### ISSUE THREAD

**Issue by Viky8526** [eclipse-openj9/openj9#17881]
Hi All

We are facing an issue with AIX Java semeru version 17.0.5 
We are getting below errors while running java -verison

failed to open </root/jdk-17.0.5+8-jre/lib/default/libjvm.so> - reason: < 0509-022 Cannot load module /root/jdk-17.0.5+8-jre/lib/default/libjvm.so

0509-150
0509-022
0509-026

Failed to find Vm -aborting

Could you please let us know for possible reasons and it's rectification ?

**Comment by pshipton** [comment]
I found the following https://www.ibm.com/support/pages/aix-open-source-tip-analyzing-module-loading-errors, it seems some prereq modules are not installed.

You can run `ldd /root/jdk-17.0.5+8-jre/lib/default/libjvm.so` to see what is found and not found.

Did you install the required C++ Runtime? https://eclipse.dev/openj9/docs/version0.35/#xl-c-runtime-16107-or-later-required-on-aix

**Comment by pshipton** [comment]
Assuming it's a C++ Runtime issue, closing.
