### ISSUE TITLE
Jep425Tests_testVirtualThread expected [WAITING] but found [RUNNABLE]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#17924]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_ppc64_aix_Nightly_testList_1/25
Jep425Tests_testVirtualThread_3 `--enable-preview -Xgcpolicy:optavgpause`
```
18:37:28  FAILED: test_jniFromVirtualthread
18:37:28  java.lang.AssertionError: expected [WAITING] but found [RUNNABLE]
18:37:28  	at org.testng.Assert.fail(Assert.java:96)
18:37:28  	at org.testng.Assert.failNotEquals(Assert.java:776)
18:37:28  	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
18:37:28  	at org.testng.Assert.assertEquals(Assert.java:118)
18:37:28  	at org.testng.Assert.assertEquals(Assert.java:442)
18:37:28  	at org.openj9.test.jep425.VirtualThreadTests.test_jniFromVirtualthread(VirtualThreadTests.java:158)
```

**Comment by pshipton** [comment]
5 x 100x exit on failure https://openj9-jenkins.osuosl.org/job/Grinder/2661/

**Comment by pshipton** [comment]
@babsingh @fengxue-IS fyi

**Comment by fengxue-IS** [comment]
I suspect this is an extreme case where the 500ms delay we set in the testcase isn't sufficient.
recall we have done incremental waiting on another test `test_VirtualthreadYieldResume`, maybe we should do something similar for this?
