### ISSUE TITLE
JDK21 serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17933]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_Personal/17/consoleFull)(`sles15le-rt1-7`):
```
19:36:47  openjdk version "21-internal" 2023-09-19
19:36:47  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21ppc64lelinuxPersonal)
19:36:47  Eclipse OpenJ9 VM (build master-07388a27432, JRE 21 Linux ppc64le-64-Bit Compressed References 20230809_23 (JIT enabled, AOT enabled)
19:36:47  OpenJ9   - 07388a27432
19:36:47  OMR      - 43a2b1d3416
19:36:47  JCL      - 1fdb064c8b9 based on jdk-21+33)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_other_0,jdk_other_1,jdk_security3_0,jdk_security3_1,jdk_security_infra_0,jdk_security_infra_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_ppc64le_linux_Personal%2F23%2FOpenJ9-JDK21-ppc64le_linux-20230809-144924.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_ppc64le_linux_Personal%2F23%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=07388a274321421d17b5b4039c1bea42df89a9c0&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
19:42:09  variation: Mode150
19:42:09  JVM_OPTIONS:  -XX:+UseCompressedOops 

19:45:59  TEST: serviceability/jvmti/stress/StackTrace/Suspended/GetStackTraceSuspendedStressTest.java

19:45:59  STDERR:
19:45:59  Unhandled exception
19:45:59  Type=Segmentation error vmState=0x00000000
19:45:59  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
19:45:59  Handler1=00007FFF8FAC0830 Handler2=00007FFF8F9E96C0
19:45:59  R0=00007FFF8DDB2E9C R1=00007FFF7081BE00 R2=00007FFF8DE37B00 R3=0000000000000000
19:45:59  R4=0000000000000000 R5=0000000000000000 R6=0000000000000001 R7=0000000000000000
19:45:59  R8=0000000000000000 R9=0000000000000000 R10=0000000000000001 R11=00007FFF8F3B3550
19:45:59  R12=00007FFF945AF2B0 R13=00007FFF708268F0 R14=00007FFF94710000 R15=0000000000000000
19:45:59  R16=00007FFF945E4110 R17=00007FFF945E4120 R18=00007FFF7081F240 R19=00007FFF04028418
19:45:59  R20=0000000000000000 R21=00007FFF7081BFA0 R22=00007FFF7081BF9C R23=000000000000003E
19:45:59  R24=00007FFF945617C0 R25=00007FFF7081BFA8 R26=00007FFF900316B0 R27=00007FFF04029350
19:45:59  R28=00007FFF8DE31210 R29=00007FFF7081BF08 R30=0000000000000000 R31=0000000000000000
19:45:59  NIP=00007FFF8DDB2EB0 MSR=800000000280D033 ORIG_GPR3=00007FFF8EACE11C CTR=00007FFF945AF2B0
19:45:59  LINK=00007FFF8DDB2E9C XER=0000000020000000 CCR=0000000028444482 SOFTE=0000000000000001
19:45:59  TRAP=0000000000000300 DAR=0000000000000AE8 dsisr=0000000040000000 RESULT=0000000000000000
19:45:59  FPR0 0000000000000007 (f: 7.000000, d: 3.458460e-323)
19:45:59  FPR1 4055564ce0000000 (f: 3758096384.000000, d: 8.534844e+01)
19:45:59  FPR2 3fefe55ddee01cf3 (f: 3739229440.000000, d: 9.967489e-01)
19:45:59  FPR3 3fee666660000000 (f: 1610612736.000000, d: 9.500000e-01)
19:45:59  FPR4 3fce840b4ac4e4d2 (f: 1254417664.000000, d: 2.384047e-01)
19:45:59  FPR5 bfe7154748bef6c8 (f: 1220474624.000000, d: -7.213475e-01)
19:45:59  FPR6 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
19:45:59  FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR8 616d692d74736574 (f: 1953719680.000000, d: 2.067451e+161)
19:45:59  FPR9 7073746f682f6567 (f: 1747936640.000000, d: 4.832635e+233)
19:45:59  FPR10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR11 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
19:45:59  FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR13 0000000000223f00 (f: 2244352.000000, d: 1.108857e-317)
19:45:59  FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:45:59  Module=/home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_Personal/openjdkbinary/j2sdk-image/lib/default/libj9jvmti29.so
19:45:59  Module_base_address=00007FFF8DDA0000
19:45:59  Target=2_90_20230809_23 (Linux 5.14.21-150400.24.69-default)
19:45:59  CPU=ppc64le (4 logical CPUs) (0x1e8390000 RAM)
19:45:59  ----------- Stack Backtrace -----------
19:45:59  jvmtiGetCarrierThread+0x160 (0x00007FFF8DDB2EB0 [libj9jvmti29.so+0x12eb0])
19:45:59  _ZL18get_carrier_threadP9_jvmtiEnvP7JNIEnv_P8_jobject+0x5c (0x00007FFF71562CEC [libGetStackTraceSuspendedStress.so+0x2cec])
19:45:59  _ZL9agentProcP9_jvmtiEnvP7JNIEnv_Pv+0x244 (0x00007FFF71566B44 [libGetStackTraceSuspendedStress.so+0x6b44])
19:45:59  agent_thread_wrapper+0x64 (0x00007FFF715632C4 [libGetStackTraceSuspendedStress.so+0x32c4])
19:45:59  wrappedAgentThreadStart+0x10c (0x00007FFF8DDDC2FC [libj9jvmti29.so+0x3c2fc])
19:45:59  omrsig_protect+0x3e4 (0x00007FFF8F9EAB74 [libj9prt29.so+0x3ab74])
19:45:59  agentThreadStart+0x88 (0x00007FFF8DDDBEA8 [libj9jvmti29.so+0x3bea8])
19:45:59  thread_wrapper+0x190 (0x00007FFF9404D820 [libj9thr29.so+0xd820])
19:45:59  start_thread+0xf8 (0x00007FFF945A9748 [libpthread.so.0+0x9748])
19:45:59  clone+0x74 (0x00007FFF9448A084 [libc.so.6+0x13a084])
19:45:59  ---------------------------------------
19:45:59  JVMDUMP039I Processing dump event "gpf", detail "" at 2023/08/09 16:45:58 - please wait.

19:45:59  TEST RESULT: Failed. Unexpected exit from test [exit code: 255]
19:45:59  --------------------------------------------------
19:48:30  Test results: passed: 124; failed: 1
19:48:45  Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_Personal/jvmtest/openjdk/report/html/report.html
19:48:45  Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux_Personal/aqa-tests/TKG/output_16916244103824/serviceability_jvmti_j9_0/work
19:48:45  Error: Some tests failed or other problems occurred.
19:48:45  -----------------------------------
19:48:45  serviceability_jvmti_j9_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34284/) - 30/50 failed

[JDK21 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/16/consoleFull)
[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34285/) - 14/50 failed

[JDK21 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/18/consoleFull)

FYI @babsingh

**Comment by babsingh** [comment]
This issue should be resolved by https://github.com/eclipse-openj9/openj9/pull/17999.

**Comment by JasonFengJ9** [comment]
Not seen in the latest internal [JDK21 run](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/17870/).
Closing
