### ISSUE TITLE
JDK21 java/lang/template/T8313809.java java.lang.StringIndexOutOfBoundsException: Range [22, 22 + 4) out of bounds for length 12

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#17958]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Personal_testList_0/15/consoleFull)(`sles15-aarch64-3`):
```
12:26:02  openjdk version "21-internal" 2023-09-19
12:26:02  OpenJDK Runtime Environment (build 21-internal-adhoc.jenkins.BuildJDK21aarch64linuxPersonal)
12:26:02  Eclipse OpenJ9 VM (build master-ea0d545d82a, JRE 21 Linux aarch64-64-Bit Compressed References 20230814_27 (JIT enabled, AOT enabled)
12:26:02  OpenJ9   - ea0d545d82a
12:26:02  OMR      - 43a2b1d3416
12:26:02  JCL      - 87ec21cbc99 based on jdk-21+33)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_lang_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Personal&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F27%2FOpenJ9-JDK21-aarch64_linux-20230814-114242.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDK21_aarch64_linux_Personal%2F27%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk21.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=ea0d545d82a8d8acc9501245e0c2984b8fa2f914&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=5ed35e82a0197057f8ce137ae4ab9e16bc9431d3&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=18&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
12:29:10  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode150
12:29:10  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops 

12:41:14  TEST: java/lang/template/T8313809.java

12:41:14  java.lang.StringIndexOutOfBoundsException: Range [22, 22 + 4) out of bounds for length 12
12:41:14  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
12:41:14  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
12:41:14  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
12:41:14  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
12:41:14  	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
12:41:14  	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:118)
12:41:14  	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:397)
12:41:14  	at java.base/java.lang.String.checkBoundsOffCount(String.java:5621)
12:41:14  	at java.base/java.lang.StringUTF16.checkBoundsOffCount(StringUTF16.java:1625)
12:41:14  	at java.base/java.lang.StringUTF16.inflate(StringUTF16.java:1459)
12:41:14  	at java.base/java.lang.StringLatin1.inflate(StringLatin1.java:771)
12:41:14  	at java.base/java.lang.String.getBytes(String.java:5492)
12:41:14  	at java.base/java.lang.StringConcatHelper.newArrayWithSuffix(StringConcatHelper.java:491)
12:41:14  	at T8313809.main(T8313809.java:37)
12:41:14  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
12:41:14  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
12:41:14  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
12:41:14  	at java.base/java.lang.Thread.run(Thread.java:1595)
12:41:14  
12:41:14  JavaTest Message: Test threw exception: java.lang.StringIndexOutOfBoundsException: Range [22, 22 + 4) out of bounds for length 12

12:41:14  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.StringIndexOutOfBoundsException: Range [22, 22 + 4) out of bounds for length 12
12:41:14  --------------------------------------------------
12:43:55  Test results: passed: 913; failed: 1
12:44:01  Report written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Personal_testList_0/aqa-tests/TKG/output_16920305493004/jdk_lang_0/report/html/report.html
12:44:01  Results written to /home/jenkins/workspace/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Personal_testList_0/aqa-tests/TKG/output_16920305493004/jdk_lang_0/work
12:44:01  Error: Some tests failed or other problems occurred.
12:44:01  -----------------------------------
12:44:01  jdk_lang_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/34339/)

[JDK21 aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_aarch64_mac_Personal_testList_0/14/consoleFull)
[JDK21 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Personal_testList_0/9/consoleFull)

**Comment by pshipton** [comment]
This failure doesn't appear to be intermittent.

**Comment by pshipton** [comment]
Yesterday OpenJDK was updated to jdk-21+35, is there a mismatch between the tests and the JVM which is jdk-21+33 ?

**Comment by JasonFengJ9** [comment]
It seems resolved in the past two builds.
