### ISSUE TITLE
Update needed for jtreg for jdknext

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#17961]
Failure link
------------
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_ppc64le_linux_Personal/3

Failure output (captured from console output)
---------------------------------------------
Several tests failed:
```
Error: The testsuite at /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64le_linux_Personal_testList_2/aqa-tests/openjdk/openjdk-jdk/test/jdk requires jtreg version 7.3+1 or higher and this is jtreg version 7.2-dev+1.
```

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
I do not see jtreg version 7.3+1 or higher built at Adoptium

https://ci.adoptium.net/job/dependency_pipeline/893/artifact/jtreg/

**Comment by keithc-ca** [comment]
Apparently we'll need to build a newer versions from https://github.com/openjdk/jtreg/releases/tag/jtreg-7.3%2B1.

**Comment by keithc-ca** [comment]
I'll update https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/code-tools/jtreg.sh.

**Comment by llxia** [comment]
Thanks @keithc-ca . All PRs are merged.
JDK22 jdk_math: https://openj9-jenkins.osuosl.org/job/Grinder/2756/ passed
