### ISSUE TITLE
OpenJ9's verbosegc output can contain invalid XML escape characters

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#17978]
Summary of problem
------------------
OpenJ9's verbosegc output can contain invalid XML escape characters, for example in the thread name:

```
<largest-consumer threadName="Thread with a control character: &#x1;" threadId="0000000000F7FF00" bytes="21556272" />
```

Note the `&#x1;` escaped character.

I believe this code is responsible:

```
if (((uint8_t)(string[stringPos])) < 0x20) {
    /* use XML escape sequence for characters below 0x20 */
    omrstr_printf(tmpBuf, sizeof(tmpBuf), "&#x%X;", (uint32_t)string[stringPos]);
```

https://github.com/eclipse/omr/blob/ac8ca57b0341457a7a4894d6f8e1f4ed6e08a62e/util/omrutil/xml.c#L63-L65

This block escapes **all** characters under `0x20`, but most characters in this range are invalid in XML 1.0. The valid characters are defined here in the XML specification:

> _Character Range_
> [2]   `Char   ::=   #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */`

https://www.w3.org/TR/xml/#NT-Char

I believe this issue applies to all Java/Semeru versions versions on all platforms

Reproduction Instructions
------------------
Compile and run the testcase below like this:

`> javac VerboseGCTest.java`
`> java -verbosegc VerboseGCTest 2>&1 | grep largest-consumer`

You should see output like this:

```
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="1037936" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="555408" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="856080" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="977184" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="1398960" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="1662048" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="1920960" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="2117232" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="2246688" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="2376144" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="2505600" />
  <largest-consumer threadName="Thread name with a control character: &#x1;" threadId="0000000000F7FF00" bytes="2635056" />
  ...
```

Note the invalid `&#x1;` escaped character.

Testcase
------------------
```
import java.io.*;

public class VerboseGCTest {
	public static void main(String[] args) {
		Thread.currentThread().setName("Thread name with a control character: \u0001");
		
		// Swallow output sent to System.out
		System.setOut(new PrintStream(new OutputStream() {
			public void write(int b) {
				// Do nothing
			}
		}));
		
		String[] array;
		
		while (true) {
			array = new String[1000];
			
			// Keep the JIT happy
			System.out.println(array.length);
		}
	}
}
```

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by keithc-ca** [comment]
It should be as simple as changing `%X` to `%02X`.

**Comment by paulcheeseman** [comment]
Wouldn't that just prepend a `0` - i.e. we'd see `&#x01;` in the verbosegc?

The value would still be invalid though, wouldn't it?

**Comment by keithc-ca** [comment]
No, I think that would be valid. It is my understanding that `CR`, for example, could be expressed as `&#13;` (decimal) or `&#x0D;` (hexadecimal). See section 4.1 of https://www.w3.org/TR/xml/#NT-Char.

**Comment by keithc-ca** [comment]
That makes me think, though, that perhaps we should use decimal so the result is (slightly) shorter (4 or 5 characters instead of always 6). Any preferences?

**Comment by paulcheeseman** [comment]
> No, I think that would be valid. It is my understanding that CR, for example, could be expressed as &#13; (decimal) or &#x0D; (hexadecimal). See section 4.1 of https://www.w3.org/TR/xml/#NT-Char.

But `&#x1;` would just change to `&#x01;` wouldn't it? And the `0x1` (or `0x01`) character is not valid either way.

The text in section 4.1 links to the spec I posted in the original description:

> Characters referred to using character references must match the production for [Char](https://www.w3.org/TR/xml/#NT-Char).

i.e.:

> _Character Range_
> [2]   	`Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */`

So the only valid values below `0x20` are `0x9`, `0xA` and `0xD`. Or am I reading that wrong?

> perhaps we should use decimal so the result is (slightly) shorter (4 or 5 characters instead of always 6).

Sounds sensible to me.

**Comment by keithc-ca** [comment]
As I re-read https://www.w3.org/TR/xml/#NT-Char, I think the use of `&#x1;` *is* legal. The rules described there allow for one or more digits. What tool says otherwise?

**Comment by paulcheeseman** [comment]
> What tool says otherwise?

This validation tool doesn't like it:

https://www.w3schools.com/xml/xml_validator.asp

You can try it out by pasting `&#x1;` into the first text box in the **Syntax-Check Your XML** section, then clicking **Check XML** button. You'll get an error like this:

>error on line 6 at column 41: xmlParseCharRef: invalid xmlChar value 1

These validators don't like it either:

https://www.xmlvalidation.com/
https://jsonformatter.org/xml-validator
https://validator.w3.org/nu/
https://www.truugo.com/xml_validator/
https://www.freeformatter.com/xml-validator-xsd.html
https://onlinexmltools.com/validate-xml
https://www.liquid-technologies.com/online-xml-validator

Interestingly I did manage to find one that accepts it:

https://codebeautify.org/xmlvalidator

**Comment by keithc-ca** [comment]
I think we should ignore https://codebeautify.org/xmlvalidator; it even accepts `&#notgood;`.

**Comment by paulcheeseman** [comment]
It looks like the XML 1.1 spec _does_ allow `0x1`:

> Character Range
> [2]   	`Char	   ::=   	[#x1-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */`

https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-Char

But the verbosegc output declares itself as XML 1.0.

**Comment by keithc-ca** [comment]
> verbosegc output declares itself as XML 1.0

Any objections to changing that so it says `<?xml version="1.1"?>`? Does anyone expect that to break any consumers of verbose GC output?

**Comment by keithc-ca** [comment]
@pshipton Any thoughts on changing to XML version 1.1?

**Comment by pshipton** [comment]
We need input from the GC team, I don't know what side effects the change might have, in particular on existing tools that read the files.

**Comment by keithc-ca** [comment]
Another detail to consider: a NUL character in the name of a thread is serialized as two bytes, 0xc0, 0x80. The expansion of NUL to that two-character sequence occurs before calls to `escapeXMLString()` so they don't get special treatment there.

**Comment by paulcheeseman** [comment]
>Any objections to changing that so it says `<?xml version="1.1"?>`? Does anyone expect that to break any consumers of verbose GC output?

There's a lot of commentary out there which basically says "don't use XML 1.1".

As far as I can tell almost nobody uses XML 1.1, and it's not very widely implemented. In fact, most of the XML validation tools I listed earlier choke if you change the XML version to 1.1. I'd be very surprised if it didn't cause problems for existing tools that parse the verbosegc output.

**Comment by keithc-ca** [comment]
If we stick with xml version 1.0 we'll need to use some other encoding of characters in the range 0x01-0x1F (other than for 0x9, 0xA and 0xD). Just `?`, or something else? Any suggestions?

**Comment by hzongaro** [comment]
> a NUL character in the name of a thread is serialized as two bytes, 0xc0, 0x80

Is that a so-called "overlong" UTF-8 encoding of NUL?  Will it appear in the XML output as the two characters `&#xc0;&#x80;`, and if so, do tools know they should be pasted together again?  And if they are pasted together, how are they distinguished from a thread that actually has the sequence of characters `\00c0\0080` in its name?

**Comment by paulcheeseman** [comment]
>If we stick with xml version 1.0 we'll need to use some other encoding of characters in the range 0x01-0x1F (other than for 0x9, 0xA and 0xD). Just ?, or something else? Any suggestions?

I see three options:

1. Replace invalid characters with the Unicode replacement character � (U+FFFD / `&#xFFFD;`)
2. Replace invalid characters with a normal question mark `?`.
3. Remove/ignore invalid characters completely.

I can see arguments for all three approaches, but I would lean towards option 1 as the most correct thing to do.

**Comment by keithc-ca** [comment]
> > a NUL character in the name of a thread is serialized as two bytes, 0xc0, 0x80
> 
> Is that a so-called "overlong" UTF-8 encoding of NUL? Will it appear in the XML output as the two characters `&#xc0;&#x80;`, and if so, do tools know they should be pasted together again? And if they are pasted together, how are they distinguished from a thread that actually has the sequence of characters `\00c0\0080` in its name?

Yes, the two-byte UTF8 sequence 0xc0, 0x80 is an "overlong" encoding of NUL, which is also illegal in XML version 1.0.

> * Replace invalid characters with the Unicode replacement character � (U+FFFD / `&#xFFFD;`)

This seems the best approach to me as well.
