### ISSUE TITLE
rh7-390-2,rh7-390-3 No route to host

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18008]
rh7-390-2
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_1/604/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_2/604/
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_s390x_linux_Nightly_testList_1/608
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_1/605/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_s390x_linux_Nightly_testList_0/546/

rh7-390-3
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_1/604
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly_testList_2/606/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly_testList_0/604/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly_testList_2/607/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_s390x_linux_Nightly_testList_2/545/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_s390x_linux_Nightly_testList_2/546/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.system_s390x_linux_Nightly_testList_2/41/

A number of test failures on https://openj9-jenkins.osuosl.org/computer/rh8-390-2 and https://openj9-jenkins.osuosl.org/computer/rh7-390-3 with the following or similar
`01:19:25  CL1 stderr 	java.net.NoRouteToHostException: No route to host (Host unreachable)`

Marked these machines offline.

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Rebooted number 2
Grinder running [![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Grinder&build=2828)](https://openj9-jenkins.osuosl.org/job/Grinder/2828/)

**Comment by pshipton** [comment]
Still getting some failures on [rh7-390-2](https://openj9-jenkins.osuosl.org/computer/rh7-390-2)

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.system_s390x_linux_Nightly_testList_0/43/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_s390x_linux_Nightly_testList_1/548/

**Comment by pshipton** [comment]
It's blocking testing from completing. I'll disable [rh7-390-2](https://openj9-jenkins.osuosl.org/computer/rh7-390-2) for now.

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/45/

**Comment by AdamBrousseau** [comment]
Infra issue 3473#issuecomment-53341610 for the documented solution.
Added commands to a script on the machine since this seems to be a reoccurring issue.
Testing on rh7-390-2
[![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Grinder&build=2931)](https://openj9-jenkins.osuosl.org/job/Grinder/2931/)

**Comment by AdamBrousseau** [comment]
rh7-390-3
[![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Grinder&build=2932)](https://openj9-jenkins.osuosl.org/job/Grinder/2932/)


Assuming this will pass. I've re-enable and relabeled both machines.

**Comment by pshipton** [comment]
@AdamBrousseau There are still problems on [rh8-390-2](https://openj9-jenkins.osuosl.org/computer/rh8-390-2), which we have seen originally, but I suspected it was a typo and changed the issues to call out rh7-390-2.

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly_testList_0/628/

**Comment by AdamBrousseau** [comment]
Grinder on rh8-390-2
[![Build Status](https://openj9-jenkins.osuosl.org/buildStatus/icon?job=Grinder&build=2934)](https://openj9-jenkins.osuosl.org/job/Grinder/2934/)

**Comment by AdamBrousseau** [comment]
Also checked the remaining rh on z.
