### ISSUE TITLE
OpenJDK test flag vm.continuations is false but should be true

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18037]
https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/closed/test/jtreg-ext/requires/OpenJ9PropsExt.java#L44

If there are tests that fail when vm.continuations is set to true, we should exclude them and create issues to track.

@babsingh fyi

**Comment by fengxue-IS** [comment]
[Personal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/17930/) in progress to verify the tests that require `vm.continuations` flag

**Comment by fengxue-IS** [comment]
sanity.openjdk failures:
```
java/lang/Thread/virtual/CarrierThreadWaits.java
java/lang/Thread/virtual/GetStackTrace.java
jdk/internal/vm/Continuation/MovingCompWindow.java (OpenJDK specific, doesn't apply to OpenJ9)
```

extended.openjdk failures:
```
serviceability/jvmti/vthread/FollowReferences/VThreadStackRefTest.java
serviceability/jvmti/vthread/ThreadStateTest/ThreadStateTest.java
serviceability/jvmti/vthread/ToggleNotifyJvmtiTest/ToggleNotifyJvmtiTest.java (OpenJDK specific, doesn't apply to OpenJ9)
```

I will open Issue/PR on test failure and exclude this before enabling the `vm.continuations` flag.

**Comment by pshipton** [comment]
Pls exclude the OpenJDK specific tests under a different issue, as we will mark it with the `perm excluded` label and close it.

**Comment by fengxue-IS** [comment]
Created issues to track test failure:
#18051 
#18052 
#18053 
#18054 
Exclude PR https://github.com/adoptium/aqa-tests/pull/4738

Perm exclude for OpenJDK specific testing under #18049 and exclude PR https://github.com/adoptium/aqa-tests/pull/4737

**Comment by babsingh** [comment]
Closing: OpenJDK test flag `vm.continuations` has been enabled; the failing tests have been excluded; and standalone issues have been opened for each failure.
