### ISSUE TITLE
OpenJDK test flag vm.opt.final.ClassUnloading should be true

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18038]
It seems vm.opt.final.ClassUnloading should be true. 

It was set to false by https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/34 due to a particular Hotspot centric test. However the flag should be true and the test should be excluded.

https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/closed/test/jtreg-ext/requires/OpenJ9PropsExt.java#L59

**Comment by babsingh** [comment]
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/34
- Personal build (`sanity.functional`, `sanity.openjdk`, `extended.openjdk`): https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/17933

**Comment by pshipton** [comment]
I don't think there is any reason to run sanity.functional for a change that only affects openjdk testing.

**Comment by babsingh** [comment]
Only `serviceability/jvmti/RedefineClasses/RedefinePreviousVersions.java` failed in the personal builds:
- https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_mac_Personal/29/testReport
- https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_s390x_linux_Personal/27/testReport

`serviceability/jvmti/RedefineClasses/RedefinePreviousVersions.java` is not supported by OpenJ9 and will be permanently disabled. For more details, see
- https://github.com/eclipse-openj9/openj9/issues/18046
- https://github.com/adoptium/aqa-tests/pull/4736
