### ISSUE TITLE
Failure in JLM_Tests_interface_0/1 on z/OS 3.1

### ISSUE THREAD

**Issue by jdekonin** [eclipse-openj9/openj9#18081]
There isn't a public link as there is no z/OS machines available on OpenJ9 jenkins for testing.  Specifically this is the sub-test that fails. This is a brand new system setup undergoing validation, but I think this is a real failure...

BUILDLIST=functional
TARGET=`testList TESTLIST=JLM_Tests_interface_0,JLM_Tests_interface_1`
MACHINE=fyrec21g.vmec.svl.ibm.com (there is currently only 1 operational for testing at 3.1)
SDK under test was the latest 11.0.20 build for z/OS JDK11

Failure output (captured from console output)
---------------------------------------------
```
16:31:50  [TestOperatingSystemMXBean] [INFO] Starting TestOperatingSystemMXBean tests ...
scriptorAPIs
16:31:52  FAILED: testGetAttributes
16:31:52  java.lang.AssertionError: 
16:31:52  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
16:31:52  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
16:31:52  	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
16:31:52  	at org.openj9.test.java.lang.management.TestOperatingSystemMXBean.testGetAttributes(TestOperatingSystemMXBean.java:464)
```

**Comment by pshipton** [comment]
It's the HardwareModel test, it fails sometimes on other OS versions too. I wouldn't let it block anything.

**Comment by pshipton** [comment]
Should be fixed by https://github.com/eclipse-openj9/openj9/pull/18165
