### ISSUE TITLE
xlinux failing to read system test tools.jar

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18090]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly_testList_2/591/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly_testList_1/591/console
```
02:03:39  build-java-8:
02:03:39      [javac] Compiling 16 source files to /home/****/workspace/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly_testList_1/aqa-tests/system/aqa-systemtest/openjdk.test.debugging/bin
02:03:39      [javac] error: error reading /home/****/workspace/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly_testList_1/aqa-tests/systemtest_prereqs/tools/tools.jar; error in opening zip file
02:03:39      [javac] 1 error
```

@llxia @AdamBrousseau

**Comment by pshipton** [comment]
Similar failure in an [internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_special.system_x86-64_windows_testList_3/373/console) on Windows
`19:35:39      [javac] error: error reading C:\Users\jenkins\workspace\Test_openjdk17_j9_special.system_x86-64_windows_testList_3\aqa-tests\systemtest_prereqs\tools\tools.jar; zip END header not found`

**Comment by llxia** [comment]
> Is the build supposed to fallback to getting these dependencies from another place if copyArtifacts fails? Or should we be aborting at that point?

The fallback logic is in TKG, and it is used for non-system tests. The system tests have its own logic in STF. I am not sure if the correct fallback logic is implemented in STF. 

To avoid confusion, maybe we should abort if copyArtifacts from systemtest.getDependency fails.

**Comment by cjjdespres** [comment]
I've been seeing this in the JITServer nightly tests recently with some regularity, e.g. in https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.system_s390x_linux_jit_Personal_testList_1/1103/

```
03:51:28  build-java-11:
03:51:28      [javac] Compiling 16 source files to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_jit_Personal_testList_1/aqa-tests/system/aqa-systemtest/openjdk.test.debugging/bin
03:51:29      [javac] error: error reading /home/jenkins/testDependency/system_lib/tools/tools.jar; zip END header not found
03:51:29  
03:51:29  BUILD FAILED
```

**Comment by llxia** [comment]
The logic has changed since the initial reporting of this issue. We are no longer using Jenkins `copyArtifacts` in the test pipeline. The dependent jars are pre-staged on the machines. And the test pipeline will only download them if they do not exist.

In this case, I suspect a bad tools.jar got pre-staged on the machine.

```
00:02:02.309  /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_jit_Personal_testList_1/../../testDependency/system_lib/tools/tools.jar exists, not downloading. 
```


[ubu22s390x-svl-rt7-1](https://hyc-runtimes-jenkins.swg-devops.com/computer/ubu22s390x%2Dsvl%2Drt7%2D1.fyre.ibm.com/) is offline. I cannot clean up `testDependency` on the machine atm.

**Comment by llxia** [comment]
tools.jar is removed from ubu22s390x-svl-rt7-1.

Close this issue. Please reopen if the issue still occurs.
