### ISSUE TITLE
JDK22 StackWalker.Option requires DROP_METHOD_INFO implementation

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18100]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/378/consoleFull

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:25:58  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/src/java.base/share/classes/javax/crypto/JceSecurityManager.java:75: error: cannot find symbol
23:25:58                  () -> StackWalker.getInstance(Set.of(Option.DROP_METHOD_INFO, Option.RETAIN_CLASS_REFERENCE));
23:25:58                                                             ^
23:25:58    symbol:   variable DROP_METHOD_INFO
23:25:58    location: class Option
```

https://github.com/eclipse-openj9/openj9/blob/b03d898a204183ae8594cc07741cc47e44c4d65c/jcl/src/java.base/share/classes/java/lang/StackWalker.java#L286-L300

**Comment by keithc-ca** [comment]
A new function is declared in `jvm.h`
```c
JNIEXPORT void JNICALL JVM_ExpandStackFrameInfo(JNIEnv *env, jobject obj);
```
and the signatures of `JVM_CallStackWalk()` and `JVM_MoreStackWalk()` have changed: the `mode` parameter will be of type `jint` instead of `jlong`.

See https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/373341ab4c9b14a74a2c0a0937350753baf467fd

**Comment by pshipton** [comment]
I've disabled the jdk acceptance build until the builds are working again.

**Comment by keithc-ca** [comment]
Reopening to address the failure of `StackWalkerTest.testOptions()`.

**Comment by keithc-ca** [comment]
https://github.com/eclipse-openj9/openj9/pull/18366 should fix `StackWalkerTest`.

**Comment by pshipton** [comment]
@keithc-ca I think this should have been closed?

**Comment by keithc-ca** [comment]
Yes.
