### ISSUE TITLE
Add .project to openj9-docs

### ISSUE THREAD

**Issue by gacholio** [eclipse-openj9/openj9#18133]
For the convenience of Eclipse users, please add a .project file to the root of the repository so Eclipse doesn't keep recreating it.

**Comment by pshipton** [comment]
Seems you could open a PR.

**Comment by gacholio** [comment]
If the default created one is good enough, I can commit it. The issue is here in case there needs to be discussion about the contents.

**Comment by pshipton** [comment]
Probably not. Looking that openj9 one, it's simple.
```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>openj9</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
	</buildSpec>
	<natures>
	</natures>
</projectDescription>
```

**Comment by gacholio** [comment]
I suppose the issue should have been in the doc repo as well...
