### ISSUE TITLE
OpenJDK com/sun/crypto/provider/Cipher/AES/TestKATForGCM Error in Native GaloisCounterMode

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18191]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal_testList_0/19) OMR Acceptance - ubu20s390x-svl-rt2-1
com/sun/crypto/provider/Cipher/AES/TestKATForGCM.java
```
11:46:00  Test #23: byte[].
11:46:00  Test #23: ByteBuffer Heap.
11:46:00  Test #23: ByteBuffer Direct.
11:46:00  Test #23: ByteBuffer Heap.  offset = 2
11:46:00  Test #23: ByteBuffer Direct.  offset = 2
11:46:00  Test #24: byte[].
11:46:00  Failed Test Vector: id = 24, key=1672c3537afa82004c6b8a46f6f0d026, iv=05, pt=null,aad=null, ct=null, tag=8e2ad721f9455f74d8b53d3141f27e8e
11:46:00  STDERR:
11:46:00  java.security.ProviderException: Error in Native GaloisCounterMode
11:46:00  	at java.base/com.sun.crypto.provider.NativeGaloisCounterMode$GCMEncrypt.doFinal(NativeGaloisCounterMode.java:841)
11:46:00  	at java.base/com.sun.crypto.provider.NativeGaloisCounterMode.engineDoFinal(NativeGaloisCounterMode.java:476)
11:46:00  	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
11:46:00  	at TestKATForGCM.executeArray(TestKATForGCM.java:287)
11:46:00  	at TestKATForGCM.main(TestKATForGCM.java:405)
```

**Comment by pshipton** [comment]
@jasonkatonica pls take a look.

**Comment by KostasTsiounis** [comment]
Starting in OpenSSL 3.0.0, a check for minimum length of IV was added (https://github.com/openssl/openssl/issues/11843, https://github.com/slontis/openssl/blob/dca81e1c93836c3f936d4209a4f968ede0d917ff/providers/implementations/ciphers/cipher_aes_gcm.c#L23).

However, after complaints about backwards compatibility, the check was removed (https://github.com/slontis/openssl/commit/c55c7d0292947bb906847ff03132c7eeb967936f).

The change, as seen in the mentioned commit was made on July 14, 2021. The machine that run the test uses the following OpenSSL version: `OpenSSL 3.0.0-alpha17 20 May 2021`. At that point the commit that removes the check hasn't been picked up yet.

The test should be fine as soon as the OpenSSL version in the machine is updated.

**Comment by pshipton** [comment]
Opened an [infra issue](https://github.ibm.com/runtimes/infrastructure/issues/8453) to update the machine(s).

**Comment by pshipton** [comment]
The machine has been updated to OpenSSL 3.1.3
