### ISSUE TITLE
JDK Next builds now require Boot JDK version must be one of: 21 22

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18211]
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/388/console
```
23:23:03  configure: (Your Boot JDK version must be one of: 21 22)
23:23:03  configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
```

**Comment by JasonFengJ9** [comment]
FYI @AdamBrousseau @pshipton

**Comment by pshipton** [comment]
Since there are no Temurin or OpenJ9 21 releases yet, I suggest we modify the code to continue to accept jdk20.
@keithc-ca

**Comment by keithc-ca** [comment]
Should we close this? Or keep it as a reminder to revert https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/671 when we can get Java 21 boot jdks?

**Comment by pshipton** [comment]
Sure, I've added it to the Java 22 milestone.

**Comment by keithc-ca** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/696 is another change that should be reverted once a Java 21 boot JDK is available.

**Comment by tajila** [comment]
@keithc-ca can this be closed?
