### ISSUE TITLE
Openj9 compatibility options

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#18265]
`-XX:Compatibility=[compatibilityMode]`

This option allows the JDK to run in compatibility mode to support applications that require specific capabilities.
Some examples are cases where applications rely on vendor-specific command line arguments to be processed, or cases where unspecified APIs are to be made available.

We will determine which applications we will provide compatibility mode for. If an unsupported mode is specified, we will fail to start the JVM.

Initially, we will only support a single usage of this option. That is `-XX:Compatibility=mode1` ` -XX:Compatibility=mode2` will not be supported.

We reserve the right to remove or modify the behaviour of these options at any time.

The first usage of this option will be  `-XX:Compatibility=elasticsearch`. Mode names will not be case-sensitive, so one could equivalently say `-XX:Compatibility=ElasticSearch`. 

With the `elasticsearch` compatibility mode, OpenJ9 may accept or appear to support Hotspot-specific options or APIs in ways that enhance compatibility to run elasticsearch workloads. 

More modes may be added in the future.

**Comment by keithc-ca** [comment]
I propose two minor adjustments:
* use `=` before the mode, for better consistency with other options and to simplify the code slightly
* modes should be case-insensitive so `-XX:Compatibility=Elasticsearch`, `-XX:Compatibility=ElasticSearch` and  `-XX:Compatibility=elasticsearch` are all equivalent

**Comment by keithc-ca** [comment]
The description is updated to reflect those adjustments.

**Comment by keithc-ca** [comment]
I downloaded elasticsearch and kibana (both version 8.10.4). In a shell I said
```
$ export ES_JAVA_HOME=/home/keithc/space/openj9/jdk17/build/normal/images/jdk
$ export OPENJ9_JAVA_OPTIONS=-XX:Compatibility=elasticsearch
```
so `$ES_JAVA_HOME` refers to my local build with (initial) support for `-XX:Compatibility=elasticsearch`. (See https://github.com/keithc-ca/openj9/tree/compatibility.)

Starting `elasticsearch-8.10.4/bin/elasticsearch` appears to work, or at least enough for `kibana-8.10.4/bin/kibana` to interact with the server and for my browser to allow me to install plugins, etc.

I don't know enough about elasticsearch, etc. to know how to tell whether there's more work to be done. @tajila Can you recommend someone to help with that?

**Comment by tajila** [comment]
@bhavanisn Can you verify if Keiths prototype is sufficient

**Comment by bhavanisn** [comment]
@tajila @keithc-ca I tested the changes in https://github.com/keithc-ca/openj9/tree/compatibility and it works. I ran the benchmark I am using to evaluate ES and it completed successfully.

One request, if possible, is to have the option `-XX:Compatibility=elasticsearch` a more simple `-XX:+ESCompatability` or similar option.

**Comment by tajila** [comment]
> One request, if possible, is to have the option -XX:Compatibility=elasticsearch a more simple -XX:+ESCompatability or similar option.

We want the application name to be a parameter in case we have to do something similar for another app in the future.

**Comment by keithc-ca** [comment]
> I ran the benchmark I am using to evaluate ES and it completed successfully.

Good, thanks for checking. I'll review my changes; I think we want things like `G1HeapRegionSize` in the output of `-XX:+PrintFlagsFinal` to be derived from the heap size which might have been specified via `-Xmx`.

**Comment by keithc-ca** [comment]
Closing this as the initial mode (elasticsearch) has been implemented. We can reopen or create a new issue if other modes are required.
