### ISSUE TITLE
[FFI/Jtreg_JDK21] IllegalArgumentException detected in TestNested.java on AIX

### ISSUE THREAD

**Issue by ChengJin01** [eclipse-openj9/openj9#18287]
With my changes (intended for union in downcall & upcall) at https://github.com/ChengJin01/openj9/commit/5c3f1e4e3118ee353b893c37c4ebf8785cd3832e#diff-710539390ec016913e8ff24f64faf40f7e64cc9de4b1f113e9f0c9820b22908e, two of the subtests in `testNested` at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/foreign/nested/TestNested.java failed on AIX with the following exceptions:
```
test TestNested.testNested(jdk.internal.foreign.layout.StructLayoutImpl@8f8a4a78): failure
java.lang.IllegalArgumentException: Member layout '[2:D8](f1)', of 
'[B1(f0)x7
 [2:D8](f1)
 B1(f2)x7
 [[3:D8](f0)[S2(f0)]
 (f1)x6
  A8(f2):[*:B1]
  A8(f3):[*:B1]]
 (f3)] (S9)' found at unexpected offset: 8 != 4
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkMemberOffset(AbstractLinker.java:236)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayoutRecursive(AbstractLinker.java:196)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayout(AbstractLinker.java:182)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayouts(AbstractLinker.java:173)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle0(AbstractLinker.java:101)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle(AbstractLinker.java:88)
	at NativeTestHelper.downcallHandle(NativeTestHelper.java:163)
	at TestNested.testNested(TestNested.java:66)

test TestNested.testNested(jdk.internal.foreign.layout.UnionLayoutImpl@6226c73e): failure
java.lang.IllegalArgumentException: Member layout '[2:D8](f1)', 
of '[B1(f0)x7 [2:D8](f1) 
B1(f2)x7[[3:D8](f0)[S2(f0)](f1)x6A8(f2)
:[*:B1]A8(f3):[*:B1]](f3)](f2)' found at unexpected offset: 8 != 4
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkMemberOffset(AbstractLinker.java:236)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayoutRecursive(AbstractLinker.java:196)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayoutRecursive(AbstractLinker.java:209)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayout(AbstractLinker.java:182)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayouts(AbstractLinker.java:173)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle0(AbstractLinker.java:101)
	at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle(AbstractLinker.java:88)
	at NativeTestHelper.downcallHandle(NativeTestHelper.java:163)
	at TestNested.testNested(TestNested.java:66)
```
FYI:  @tajila, @pshipton

**Comment by ChengJin01** [comment]
Based on failing test cases are as follows:
https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/9e4783d1f1520d34f5261f8e94ec5d22004ade08/test/jdk/java/foreign/nested/libNested.c#L46
```
static final StructLayout S9 = MemoryLayout.structLayout(
            C_CHAR.withName("f0"),
            MemoryLayout.paddingLayout(7), <-----------
            MemoryLayout.sequenceLayout(2, C_DOUBLE).withName("f1"),
            C_CHAR.withName("f2"),
            MemoryLayout.paddingLayout(7), <------------
            S8.withName("f3")
    ).withName("S9");

static final StructLayout S8 = MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(3, C_DOUBLE).withName("f0"),
            U7.withName("f1"),
            MemoryLayout.paddingLayout(6),
            C_POINTER.withName("f2"),
            C_POINTER.withName("f3")
    ).withName("S8");

 static final UnionLayout U7 = MemoryLayout.unionLayout(
            C_SHORT.withName("f0")
    ).withName("U7");
```
plus the corresponding native code at https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/9e4783d1f1520d34f5261f8e94ec5d22004ade08/test/jdk/java/foreign/nested/libNested.c#L44C1-L46C60
```
union U7{ short f0; };
struct S8{ double f0[3]; union U7 f1; void* f2; void* f3; };
struct S9{ char f0; double f1[2]; char f2; struct S8 f3; };

EXPORT struct S8 test_S8(struct S8 arg, struct S8(*cb)(struct S8)) { return cb(arg); }
EXPORT struct S9 test_S9(struct S9 arg, struct S9(*cb)(struct S9)) { return cb(arg); }
```
against the captured exceptions in the description, it indicates that there might be a padding issue with `double` on AIX as we modified the code on AIX in the OpenJDK extension to be 4-byte aligned `double`. So I wrote a simple test to verify how it goes with the following struct:
```
typedef struct stru_char_double_char {  <---------- var1
        char elem1;
        double elem2[2];
        char elem3;
} stru_char_double_char;

int main()
{
     stru_char_double_char  var1 = {0x1, 22.333, 22.333, 0x2};
     printf("size of var1 = %d\n", sizeof(var1));
    return 0;
}
``` 
to debug the test as follows:
```
[1] stopped in main at line 25
   25       printf("size of var1 = %d\n", sizeof(var1));
(dbx) p var1
(elem1 = '^A', elem2 = (22.332999999999998, 22.332999999999998), elem3 = '^B')
(dbx) p &var2
0x2ff22b30
(dbx) p &var2.elem1
0x2ff22b30
(dbx) p &var2.elem2[0]
0x2ff22b34 <-------------------- the padding between `char` and `double` is 3 bytes
(dbx) p &var2.elem2[1]
0x2ff22b3c
(dbx) p &var2.elem3
0x2ff22b44
(dbx) p sizeof(var2)
24    <-------------------- the padding after the 2nd `char` is 3 bytes
```
which means the failing jtreg test struct `S9` should be modified to with the correct padding bytes on AIX.

**Comment by ChengJin01** [comment]
To isolate the test cases, I modified the failing test struct as follows:
```
static final StructLayout S9 = MemoryLayout.structLayout(
            C_CHAR.withName("f0"),
            MemoryLayout.paddingLayout(3), <-----------
            MemoryLayout.sequenceLayout(2, C_DOUBLE).withName("f1"),
            C_CHAR.withName("f2"),
            MemoryLayout.paddingLayout(3), <------------
            S8.withName("f3")
    ).withName("S9");
```
and disabled the check on the returned value at  https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/9e4783d1f1520d34f5261f8e94ec5d22004ade08/test/jdk/java/foreign/nested/TestNested.java#L73
```
    public void testNested(GroupLayout layout) throws Throwable {
        try (Arena arena = Arena.ofConfined()) {
...
            MemorySegment returned = (MemorySegment) downcallHandle.invokeExact(
                    (SegmentAllocator) arena, (MemorySegment) testValue.value(), stub);

            // testValue.check().accept(returnBox.get()[0]); <----- ignore the check on the returned value
            testValue.check().accept(returned);
        }
    }
```
plus the modified native code (to simply return the passed-in struct rather than triggering the upcall thunk) at  https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/9e4783d1f1520d34f5261f8e94ec5d22004ade08/test/jdk/java/foreign/nested/libNested.c#L79  to ensure it only works for downcall.
```
EXPORT struct S9 test_S9(struct S9 arg, struct S9(*cb)(struct S9)) { 
   // return cb(arg);  <------ disable the upcall thunk
   rerurn arg; 
   }
```
which works good and the failing tests passed without any issue. That being said, there is no issue with downcall as long as the padding bytes are correct on AIX.

However, it crashed when invoking the upcall thunk (not yet reaching the upcall dispather) when enabling the upcall in the native code:
```
EXPORT struct S9 test_S9(struct S9 arg, struct S9(*cb)(struct S9)) { 
     return cb(arg);  <------ disable the upcall thunk
   }
```
with the following stacktrace:
```
Signal 0 in genSystemCoreUsingGencore at line 203 in file ".../openj9-openjdk-jdk21/omr/port/aix/omrosdump_helpers.c" ($t27)
  203           rc = gencore(&coreDumpInfo);
where
(dbx) genSystemCoreUsingGencore(??, ??), line 203 in "omrosdump_helpers.c"
omrdump_create(??, ??, ??, ??), line 118 in "omrosdump.c"
doSystemDump(??, ??, ??), line 763 in "dmpagent.c"
protectedDumpFunction(??, ??), line 2897 in "dmpagent.c"
omrsig_protect(??, ??, ??, ??, ??, ??, ??), line 425 in "omrsignal.c"
runDumpAgent(??, ??, ??, ??, ??, ??), line 2875 in "dmpagent.c"
triggerDumpAgents(??, ??, ??, ??), line 1041 in "trigger.c"
generateDiagnosticFiles(??, ??), line 1162 in "gphandle.c"
omrsig_protect(??, ??, ??, ??, ??, ??, ??), line 425 in "omrsignal.c"
structuredSignalHandler(??, ??, ??, ??), line 837 in "gphandle.c"
mainSynchSignalHandler(??, ??, ??), line 1066 in "omrsignal.c"
test_S9(arg = (...), cb = 0xb765432122a8bae0), line 84 in "libNested.c" <----------
ffi_call_AIX(), line 110 in "aix.S"
ffi_call(??, ??, ??, ??), line 945 in "ffi_darwin.c"
ffiCallWithSetJmpForUpcall(??, ??, ??, ??, ??), line 73 in "UpcallExceptionHandler.cpp"
bytecodeLoopCompressed() at 0x90000000c69a238
c_cInterpreter(), line 48 in "pcinterp.s"
runJavaThread(??), line 682 in "callin.cpp"
javaProtectedThreadProc(J9PortLibrary*, void*)(??, ??), line 2104 in "vmthread.cpp"
omrsig_protect(??, ??, ??, ??, ??, ??, ??), line 425 in "omrsignal.c"
javaThreadProc(??), line 383 in "vmthread.cpp"
thread_wrapper(??), line 1733 in "omrthread.c"
```

Considering there is no issue on pLinux and other platforms in these tests, there should be no problem with the encoded native signature as they are shared on all supported platforms, in which case it is mostly likely to be an issue with this type of struct in the upcall thunk on AIX.

**Comment by ChengJin01** [comment]
@zl-wang, could you please help take a look at what really happened to the thunk on AIX?

**Comment by zl-wang** [comment]
all of your modifications still made the struct as if it were packed (i.e. members are not aligned right).  is it intended to be that way?  the correct padding should look like:  char, 7-byte padding, two-double-array, char (with or without padding i think would be fine).

**Comment by zl-wang** [comment]
i guessed the struct C declaration might look like:
```
   struct Foo {
         char  f0;
         double f1[2];
          char f2;
   }
```
Is my guess right?  then, 7-byte padding should be expected (at the first char).

**Comment by ChengJin01** [comment]
> i guessed the struct C declaration might look like:
> 
> ```
>    struct Foo {
>          char  f0;
>          double f1[2];
>           char f2;
>    }
> ```
> 
> Is my guess right? then, 7-byte padding should be expected. the size is 32-byte i think.

Not really. It is 3 bytes detected at https://github.com/eclipse-openj9/openj9/issues/18287#issuecomment-1765048560
```
[1] stopped in main at line 25
   25       printf("size of var1 = %d\n", sizeof(var1));
(dbx) p var1
(elem1 = '^A', elem2 = (22.332999999999998, 22.332999999999998), elem3 = '^B')
(dbx) p &var2
0x2ff22b30
(dbx) p &var2.elem1
0x2ff22b30
(dbx) p &var2.elem2[0]
0x2ff22b34 <-------------------- the padding between `char` and `double` is 3 bytes
(dbx) p &var2.elem2[1]
0x2ff22b3c
(dbx) p &var2.elem3
0x2ff22b44
(dbx) p sizeof(var2)
24    <-------------------- the padding after the 2nd `char` is 3 bytes
```

**Comment by zl-wang** [comment]
3-byte padding is a valid choice, but only for 32-bit mode (i.e. 32-bit executable).  it is not right for 64-bit mode (our JVM mode ... we don't do 32bit build after java8).

**Comment by zl-wang** [comment]
it is an easy test:  xlC -q64 your-C-test.c        to see if 3-byte or 7-byte padding is applied.

**Comment by ChengJin01** [comment]
> it is an easy test: xlC -q64 your-C-test.c to see if 3-byte or 7-byte padding is applied. without -q64, the default is 32-bit mode compilation.

Here's the result of the test as follows:
```
typedef struct stru_char_double_char {
        char elem1;
        double elem2[2];
        char elem3;
} stru_char_double_char;

int main()
{
stru_char_double_char var1;
    var1.elem1 = 0x1;
    var1.elem2[0] = 22.333;
    var1.elem2[1] = 22.333;
    var1.elem3 = 0x2;

    printf("size of var1 = %d\n", sizeof(var1));
   return 0;
}

-bash-5.0$ xlc  -q64 -g struct.c -o struct
-bash-5.0$ dbx struct
Type 'help' for help.
reading symbolic information ...
(dbx) stop at 26
[1] stop at 26
(dbx) run
[1] stopped in main at line 26
   26       printf("size of var1 = %d\n", sizeof(var1));
(dbx) p var1
(elem1 = '^A', elem2 = (22.332999999999998, 22.332999999999998), elem3 = '^B')
(dbx) p sizeof(var1)
24  <---------------------  4 + 8 * 2 + 4 = 24
(dbx) p &var1.elem1
0x0ffffffffffff9e0
(dbx) p &var1.elem2[0]
0x0ffffffffffff9e4    <------------------- 3 bytes
(dbx) p &var1.elem2[1]
0x0ffffffffffff9ec
(dbx) p &var1.elem3
0x0ffffffffffff9f4
```

**Comment by zl-wang** [comment]
that looks like a compiler bug. we can pursue this bug separately.  in any case, what did you present to the thunk generation mechanism? it should be AGGREGATE_OTHER (if I remember correctly) with 24-byte in size, then it should work.
you will have 32-byte in size on other 64bit platforms i think, i.e. your signature encoding code is going to be different between AIX and others.

**Comment by ChengJin01** [comment]
>   it should be AGGREGATE_OTHER (if I remember correctly) with 24-byte in size, then it should work.
you will have 32-byte in size on other 64bit platforms 

That' correct as the struct size for upcall is computed ahead of time in the java code  before passing it to `sigType->sizeInByte` for the native signature in native.

> your signature encoding code is going to be different between AIX and others.

If we change the code in https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/LayoutFFITypeHelpers.hpp for the native signature encoding on AIX, does it mean the upcall thunk should be updated accordingly to differentiate AIX from other platform in such case?

**Comment by zl-wang** [comment]
> If we change the code in https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/LayoutFFITypeHelpers.hpp for the native signature encoding on AIX, does it mean the upcall thunk should be updated accordingly to differentiate AIX from other platform in such case?

yes, different AGGREGATE_OTHER and size combination presented to the thunk gen ... different thunk code(s) will be generated to fit with the upcall.  i hoped the signature coming in on AIX already has the correct padding identified (at least for the time being as it is).

**Comment by ChengJin01** [comment]
> yes, different AGGREGATE_OTHER and size combination presented to the thunk gen ... different thunk code(s) will be generated to fit with the upcall...

If so, this is something we should coordinate to ensure the new type (.e.g. `J9_FFI_UPCALL_SIG_TYPE_STRUCT_AGGREGATE_OTHER_C_D` (char, double) or something else more preferable) is only intended for AIX to minimize the changes on other platforms.

**Comment by zl-wang** [comment]
> If so, this is something we should coordinate to ensure the new type (.e.g. J9_FFI_UPCALL_SIG_TYPE_STRUCT_AGGREGATE_OTHER_C_D (char, double) or something else more preferable) is only intended for AIX to minimize the changes on other platforms.

that sounds unsustainable.  you cannot cover all these unlimited possibilities ...  C_D, C_C_D, etc etc  i remembered you told us there is signature with correct padding available to you.

**Comment by ChengJin01** [comment]
>  i remembered you told us there is signature with correct padding available to you.

You mean the existing definition we already have now in the code? but I can't determine which one in https://github.com/eclipse-openj9/openj9/blob/d5a2e02636e983944e98f52592a222b2c63217cb/runtime/oti/j9nonbuilder.h#L6047 is suitable in this case.

**Comment by zl-wang** [comment]
AGGREGATE_OTHER is the suitable/correct one to encode to ... of course need the right size  (24 on AIX and 32 on others).

**Comment by ChengJin01** [comment]
> AGGREGATE_OTHER is the suitable/correct one to encode to ... of course need the right size (24 on AIX and 32 on others).

Then there is no need to add a new definition given the correct struct size is already set to `sigType->sizeInByte` for the upcall thunk.

**Comment by ChengJin01** [comment]
With the following struct in the test on AIX: 
```
{
         char  f0;
         double f1[2];
          char f2;
}
```
the printing-out message from the code seems correct in terms of sigArray input. Now the question is why it crashed in there.
```
encodeUpcallSignature: sigType->sizeInByte = 24, cSignature = #[C(3)2:DC(3)]
encodeUpcallSignature: sigType->type = 58  <----- J9_FFI_UPCALL_SIG_TYPE_STRUCT_AGGREGATE_OTHER 0x3A
```

**Comment by keithc-ca** [comment]
> that looks like a compiler bug. we can pursue this bug separately

If a bug, it's not clear how it could be fixed without breaking compatibility with existing binaries.

**Comment by keithc-ca** [comment]
If the first failure relates to this:
```java
    static final StructLayout S9 = MemoryLayout.structLayout(
            C_CHAR.withName("f0"),
            MemoryLayout.paddingLayout(7),
            MemoryLayout.sequenceLayout(2, C_DOUBLE).withName("f1"),
            C_CHAR.withName("f2"),
            MemoryLayout.paddingLayout(7),
            S8.withName("f3")
    ).withName("S9");
```
then I believe the test is just broken in that it assumes 7 bytes of padding between `f0` and `f1`.

Alternatively, the checking in `AbstractLinker` should not be ignoring padding members.

**Comment by keithc-ca** [comment]
> it is a bug from expectation perspective

I had the same expectation, but I don't see we have any alternatives to working with what the compiler does (and I expect must continue to do). Calling it a "bug" suggests it might someday be fixed, but, as I said, I don't think this can be "fixed".

**Comment by zl-wang** [comment]
> I had the same expectation, but I don't see we have any alternatives to working with what the compiler does (and I expect must continue to do). Calling it a "bug" suggests it might someday be fixed, but, as I said, I don't think this can be "fixed".

now, that is down to the specific situation whether the compiled application needs to consume existing data in former shape and form. an option can be provided for that case. fixing it is still possible.

**Comment by ChengJin01** [comment]
Based on the printing message from the test & code:
```
allocateUpcallStub: thunkAddr = 0x10022e3a7a8
inlInternalDowncallHandlerInvokeNative: values[i] = 10022aa91b8, values[i] = 10022aa91b8 <----- prior to ffi_call
test_S9: cb = 0x22aa8ae0, cb = 0xb7654321 22aa8ae0 <----- corrupted address
```
plus the information from the core dump:
```
(dbx) 0x10022aa91b8/2X
0x0000010022aa91b8: 00000100 22e3a7a8  <---- the upcall thunk address is set correctly in values before passed over to ffi_call

frame 11
(dbx) test_S9(arg = (...), cb = 0xb765432122aa8ae0), line 89 in "libNested.c"
p arg
(dbx) (f0 = '`', f1 = (0.83144098878706119, 0.60634521599735958), f2 = ':')
p cb
(dbx) 0xb765432122aa8ae0
p sizeof(arg)
(dbx) 24
(dbx) 0x10022aa91b8/2X
0x0000010022aa91b8: 00000100 22e3a7a8  <---- the upcall thunk address is set correctly in values before passed over to ffi_call
p &arg
(dbx) 0x0000010022aa8a58
p &arg.f2
(dbx) 0x0000010022aa8a6c
0x0000010022aa8a6c/6X
(dbx) 0x0000010022aa8a6c:  3a000000 b7654321 22aa8ae0 (garbage value set to cb) 00000100
0x0000010022aa8a7c:            22e3a7a8 (the correct thunk address) 00000100
```
as discussed with @zl-wang, we determined that the crash occurred in `ffi_call` (libffi in downcall) before triggering the upcall thunk given the `cb` value (stored the thunk address) was corrupted due to unexpected size of the `arg` struct (24 bytes) as the correct thunk address is right after 32 bytes of the `arg` struct. So we have to exclude the test suite on AIX for the time being and raise an issue in https://github.com/libffi/libffi/issues to request them to fix it up.

**Comment by zl-wang** [comment]
i talked to xlC team.  xlC option `-qalign=natural` seems the solution.  that option makes the padding scheme identical to default padding scheme as gcc.  @ChengJin01  please hold your idea of excluding or libffi change ... and test this option out first.

**Comment by zl-wang** [comment]
xlC alignment documentation:  https://www.ibm.com/docs/en/xl-c-and-cpp-aix/16.1?topic=modes-alignment-aggregates

**Comment by keithc-ca** [comment]
That documentation says `-qalign=natural` is not the default behavior. Using it has the potential to alter the layout of structures in system header files. It doesn't seem to really be a choice we can make (nor expect users to make).

**Comment by zl-wang** [comment]
> That documentation says -qalign=natural is not the default behavior. Using it has the potential to alter the layout of structures in system header files. It doesn't seem to really be a choice we can make (nor expect users to make).

really it is not that pessimistic.  system headers are explicitly aligned by and large (of course, I cannot provide the guarantee for everything out there). at least, we should give it a try.

**Comment by ChengJin01** [comment]
> -qalign=natural

The test end up with the failure due to the 4byte-aligned double we previously make in the OpenJDK extension
```
java.lang.IllegalArgumentException: Unsupported layout: 8%D8
        at java.base/jdk.internal.foreign.abi.AbstractLinker.checkSupported(AbstractLinker.java:247)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayoutRecursive(AbstractLinker.java:188)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayoutRecursive(AbstractLinker.java:217)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayoutRecursive(AbstractLinker.java:197)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayout(AbstractLinker.java:182)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.checkLayouts(AbstractLinker.java:173)
        at java.base/jdk.internal.foreign.abi.AbstractLinker.downcallHandle0(AbstractLink
```
So I will need to restore the alignment back to 8 bytes by recompiling the build to see how it goes.

**Comment by keithc-ca** [comment]
> by and large

I don't think that is sufficient.

> the question is whether we agree on this solution

We need to tread very carefully here. I think we may have to keep the adjustment for AIX that allows double to be 4-byte aligned, otherwise the JDK on AIX would be incompatible with foreign code that assumes `-qalign=power` (the default) compiler option.

**Comment by zl-wang** [comment]
two possible ways moving forward:
1) building with default -qalign, excluding the failed test for the time being, expect not to work for structs with different layouts between power and natural -qalign options.  long-term solution in the furture: changing libffi to work for default -qalign layout;
2) building with -qalign=natural, document potential incompatibility with default -qalign built libraries.

I am ok with either choice.  OpenXL team is looking into the long-term solution above.

**Comment by zl-wang** [comment]
if we choose to go with default layout, @ChengJin01 please open another PR to keep track of the long-term solution dependency on libffi work.  It will be a good thing to begin with as inputs to OpenXL side.

**Comment by keithc-ca** [comment]
This isn't just about how we build the JDK. Users (e.g. package developers) will be making use of FFM to make use of native code and data structures. We need to be very clear about they need to do their work. On the one hand, it's unfortunate that the default alignment rules on AIX are surprising, on the other hand, we're not making those developers lives any easier if they have to either use a special compile option, or guess how a third party built the library they want to use.

**Comment by zl-wang** [comment]
> This isn't just about how we build the JDK. Users (e.g. package developers) will be making use of FFM to make use of native code and data structures. We need to be very clear about they need to do their work. On the one hand, it's unfortunate that the default alignment rules on AIX are surprising, on the other hand, we're not making those developers lives any easier if they have to either use a special compile option, or guess how a third party built the library they want to use.

nothing different from what i described already ...

actually in this regard, every platform is likely to have the same issue potentially, given all compilers provided -qalign equivalent options one way or another. there is always a possibility somebody chooses to use a non-default layout.

**Comment by ChengJin01** [comment]
> two possible ways moving forward:
> 
>     1. building with default -qalign, excluding the failed test for the time being, expect not to work for structs with different layouts between power and natural -qalign options.  long-term solution in the furture: changing libffi to work for default -qalign layout;
> 
>     2. building with -qalign=natural, document potential incompatibility with default -qalign built libraries.

I will raise an issue for this problem in https://github.com/libffi/libffi/issues to request them to fix it up based on the default layout featured with the 4-byte aligned double if there is no concern/comment on this situation.

**Comment by zl-wang** [comment]
whom do you intend to raise the issue against?  i.e. what do you mean by **"them"**? 
the default layout on AIX could not be described as 4-byte aligned doubles.  it has a whole scheme (set of rules) when the struct declaration is parsed. when you open the issue, do you have the complete info to describe the whole scheme?

**Comment by ChengJin01** [comment]
> whom do you intend to raise the issue against? i.e. what do you mean by "them"?

There is nobody except [Anthony Green](https://github.com/atgreen)  (the libffi maintainer) who is responsible to forward the issue to right guy previously working on the libffi specific code on AIX, which is out of our control.

> the default layout on AIX could not be described as 4-byte aligned doubles. it has a whole scheme (set of rules) when the struct declaration is parsed. when you open the issue, do you have the complete info to describe the whole scheme?

For `struct {char a; double b[2]; char; void *p }`, the compilation with the default option ends up with 32 bytes (in which the double is 4-byte aligned and 3 bytes is padded between `char` and `double`, which messes up the pointer element in the struct while it is supposed to be 40 bytes if compiled with `-qalign=natural` (in which the double is 8-byte aligned as normal) which works good on the existing libffi code on AIX. So, what we'd like them to do is to modify their code to handle the case of 4-byte aligned double by default.

**Comment by edelsohn** [comment]
I probably have touched the libffi AIX code the most.

**Comment by ChengJin01** [comment]
> https://github.com/libffi/libffi/blob/4661ba7928b49588aec9e6976673208c8cbf0295/doc/libffi.texi#L505 (no direct support for arrays or unions. However, they can be emulated using structures.)

That's how we implemented the union in FFI at https://github.com/eclipse-openj9/openj9/pull/18291

> To verify if this PR is the same, you can test out this below struct: 
> struct {char a; double b1, b2; char; void *p;}

This is something I already verified previous by modifying the failing test which crashed in the same way as `struct {char a; double b[2]; char; void *p;}`. But I can double-check again to confirm that.

**Comment by zl-wang** [comment]
i didn't notice the ending *p.  I intended to say testing out this one:
`struct {char a; double b1, b2; char c;}`
this is exactly the same as your original failing case, in terms of size, padding, and layout.  just doesn't have array and nested struct.

**Comment by ChengJin01** [comment]
> i didn't notice the ending *p. I intended to say testing out this one:
> `struct {char a; double b1, b2; char c;}`
> this is exactly the same as your original failing case, in terms of size, padding, and layout. just doesn't have array and nested struct.

After changing the java code of `struct S9` to
```
    static final StructLayout S9 = MemoryLayout.structLayout(
            C_CHAR.withName("f0"),
            MemoryLayout.paddingLayout(3),
            C_DOUBLE.withName("f1"),
            C_DOUBLE.withName("f2"),
            C_CHAR.withName("f3"),
            MemoryLayout.paddingLayout(3)
    ).withName("S9");
```
plus the native code as follows:
```
struct S9{ char f0; double f1, f2;  char f3; };
```
the failing test for S9 passed without any issue. That being said, the crash occurred only when there is a nested double array in the struct.

**Comment by edelsohn** [comment]
As @zl-wang quoted the libffi documentation link that I sent him, arrays are not first-class objects in libffi.  Arrays and nested arrays do not function in libffi reliably.

Can the Java code pretend that the pair of doubles are non-nested members of the struct and claim victory?

**Comment by zl-wang** [comment]
from the testings we have done (which case succeeded and which failed) and what @edelsohn described arrays and nested-arrays as unreliable for libffi, I think we can claim victory from java perspective for the time being. 

@edelsohn is this-unreliability happening on other platforms too? plus, the main change (for specific struct) is in C code when you fill in the ffi_type struct in order to use libffi where you can emulate arrays as sequence of scalar in providing struct definition to libffi.  the java-side changes are only relevant to calculating field-offset within C struct for java code to access them in the corresponding/reflective MemorySegment.

**Comment by edelsohn** [comment]
If one looks at the Python and libffi file history, it has been tweaked for multiple platforms, but fewer and fewer have the type of ABI quirks as AIX.

Because the inlined double members behave as expected and the array doesn't, this probably is related to libffi emulating the array as a nested struct, and a struct with the first member a double has a stricter alignment and padding than an interior double.  The "as if" behavior of libffi is not correct in this case and the member position doesn't agree.

**Comment by daltenty** [comment]
> Because the inlined double members behave as expected and the array doesn't, this probably is related to libffi emulating the array as a nested struct, and a struct with the first member a double has a stricter alignment and padding than an interior double. The "as if" behavior of libffi is not correct in this case and the member position doesn't agree.

It's not clear that case is broken either, I tried this case in an libffi test. We preform a call which takes the struct by value, increments the members and returns the struct and everything comes back fine.      

The struct:
```
typedef struct
{
  unsigned char c1;
  double s[2];
  unsigned char c2;
} test_structure_12;
```
How Clang computes layout on AIX:
```
*** Dumping AST Record Layout
         0 | test_structure_12
         0 |   unsigned char c1
         4 |   double[2] s
        20 |   unsigned char c2
           | [sizeof=24, align=4, preferredalign=4]
```
The libffi type description:
```
  ts12a_type.type = FFI_TYPE_STRUCT;
  ts12a_type.elements = ts12a_type_elements;
  ts12a_type_elements[0] = &ffi_type_double;
  ts12a_type_elements[1] = &ffi_type_double;
  ts12a_type_elements[2] = NULL;

  ts12_type.type = FFI_TYPE_STRUCT;
  ts12_type.elements = ts12_type_elements;
  ts12_type_elements[0] = &ffi_type_uchar;
  ts12_type_elements[1] = &ts12a_type;
  ts12_type_elements[2] = &ffi_type_uchar;
  ts12_type_elements[3] = NULL;      
```
The resulting size and alignment from libffi:
```
size: 28
align: 4
```
so everything seems to agree, at least for this case.

I think to clarify the crashing case, we'd need to be clear on what the ffitype description java passes to fficall looks like. That would help clearly identify if the libffi_call is faulty.

(Another suggestion that came to mind while reading https://github.com/eclipse-openj9/openj9/issues/18287#issuecomment-1765069485 where the upcall was disabled, would be to try just a downcall with a test function on the C side that will modify the struct and then have the java side inspect the return, similar to what we had in the stand alone ffi test. That might also help clarify if the ffi_call is going wrong)

**Comment by ChengJin01** [comment]
> I think to clarify the crashing case, we'd need to be clear on what the ffitype description java passes to fficall looks like. That would help clearly identify if the libffi_call is faulty.

You'd better try with `struct  { char f0; double f1[2],  char f2; void *p; } by adding one more pointer parameter in the end of the struct (which is what happens in the crash due to the messed-up pointer (nothing to do with upcall) to see how it goes.

**Comment by ChengJin01** [comment]
@daltenty,

>  ts12_type_elements[0] = &ffi_type_uchar;

Maybe it doesn't matter but we are using `ffi_type_sint8` for `char` (1 byte) in our code rather than  `ffi_type_uchar` (which is literally `ffi_type_uint8`).

**Comment by zl-wang** [comment]
@daltenty 
```
size: 28    <<< typo? 24 is expected
align: 4
```

**Comment by daltenty** [comment]
> @daltenty
> 
> ```
> size: 28    <<< typo? 24 is expected
> align: 4
> ```

Ah point taken, I've clearly misread that. Yes, while the call works libffi and the compiler do disagree about the size, and when I add the extra parameter I get the crash you are seeing.

**Comment by ChengJin01** [comment]
Hi @daltenty,  is there any update on your side?

**Comment by daltenty** [comment]
> Hi @daltenty, is there any update on your side?

I've posted a PR to libffi to hopefully correct the layout computation: https://github.com/libffi/libffi/pull/805

I think you can try applying that patch to the openj9 local copy of libffi to test and see if it resolves the issue we're seeing here.

**Comment by ChengJin01** [comment]
> > Hi @daltenty, is there any update on your side?
> 
> I've posted a PR to libffi to hopefully correct the layout computation: [libffi/libffi#805](https://github.com/libffi/libffi/pull/805)
> 
> I think you can try applying that patch to the openj9 local copy of libffi to test and see if it resolves the issue we're seeing here.

Many thanks. I will try this patch to in our code to see how it goes.

**Comment by ChengJin01** [comment]
I've verified the path offered by @daltenty at https://github.com/libffi/libffi/pull/805 with a recompiled build which works good as expected and all test cases passed in the test suite:
```
===============================================
test/jdk/java/foreign/nested/TestNested.java
Total tests run: 32, Passes: 32, Failures: 0, Skips: 0
===============================================
```

**Comment by pshipton** [comment]
Now that https://github.com/eclipse-openj9/openj9/pull/18375 has been merged, is there an excluded set of tests that need to be enabled?

**Comment by keithc-ca** [comment]
TestNested seems to be disabled for all platforms for jdk21+:
* https://github.com/adoptium/aqa-tests/pull/4647
* https://github.com/adoptium/aqa-tests/pull/4694

**Comment by ChengJin01** [comment]
> TestNested seems to be disabled for all platforms for jdk21+:
> 
>     * [Exclude the FFI test suites added in JDK21 adoptium/aqa-tests#4647](https://github.com/adoptium/aqa-tests/pull/4647)
> 
>     * [Add openjdk/excludes/ProblemList_openjdk22 files adoptium/aqa-tests#4694](https://github.com/adoptium/aqa-tests/pull/4694)

We will need to double-check the test suite again before enabling it on all supported platforms.

**Comment by pshipton** [comment]
This is waiting for https://github.com/libffi/libffi/pull/805 to merge so we can update to the approved content.

See https://github.com/eclipse-openj9/openj9/pull/18375#issuecomment-1808957660

**Comment by pshipton** [comment]
https://github.com/libffi/libffi/pull/805 has merged without further changes. Closing this.
