### ISSUE TITLE
Remove duplicate System.gc() in test

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#18335]
Some tests call GC twice.

https://github.com/eclipse-openj9/openj9/blob/fadb895178d06504a9e0ff7d6d8963879cb45a28/test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java#L357..%23L358

This is no longer needed in the tests (see https://github.com/eclipse-openj9/openj9/pull/18044). We should clean it up and call System.gc() once.

FYI @dmitripivkine

**Comment by 0scvr** [comment]
Sign me up, please. I would like to try this issue :)

**Comment by flooxo** [comment]
I would also love to work on the issue :)

**Comment by llxia** [comment]
Additional tests that need to be cleaned up:
- https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/test/functional/cmdLineTests/gcRegressionTests/src/com/ibm/tests/garbagecollector/TestContractionMain.java#L69-L71
- https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/test/functional/Java11andUp/src/org/openj9/test/condy/GarbageCollectionCondyTest.java#L67-L68
- https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/test/functional/JIT_Test/src/jit/test/finalizer/TestObject.java#L69-L70
- https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/test/functional/VM_Test/src/j9vm/test/classunloading/ClassUnloadingTestParent.java#L64-L65
- https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/test/functional/JLM_Tests/src/org/openj9/test/java/lang/management/TestGarbageCollectorMXBean.java#L116-L117
- https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/test/functional/Valhalla/src_qtypes/org/openj9/test/lworld/ValueTypeTests.java#L342
- https://github.com/eclipse-openj9/openj9/blob/06c3abcca73751a569836b2df970873366b50312/test/functional/VM_Test/src/j9vm/test/hash/HashCodeTestParent.java#L54-L55

**Comment by flooxo** [comment]
Thanks, I'll fix them as well.
Sometimes there are also duplicate `System.runFinalization();` after `System.gc();`. I'm not sure, can those duplicates be removed as well?

**Comment by llxia** [comment]
re https://github.com/eclipse-openj9/openj9/issues/18335#issuecomment-1777943045, @pshipton @TobiAjila Do you happen to know why we call `System.runFinalization();` twice and can we remove one?

**Comment by tajila** [comment]
We've needed to call gc() twice because J9 doesn't always respect it the first time. Calling it twice guarantees that at least 1 GC occurs. 

> Do you happen to know why we call System.runFinalization(); twice and can we remove one?

Sometimes finalizable objects are created as a result of running finalizers. Calling it twice provides a better guarantee that all finalizable objects are cleared.
