### ISSUE TITLE
Virtual Thread Support for JVMTI Extensions API

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#18386]
We need to mirror changes for virtual thread support to the JVMTI Extensions API.

Currently, the following functions need virtual thread support:
https://github.com/eclipse-openj9/openj9/blob/20cb61e29490ba48096a8be0b79c2e42753d24be/runtime/jvmti/jvmtiExtensionMechanism.c#L74-L78

We should also double check other JVMTI Extensions API for missing virtual thread support.

The JVMTI Extensions API is not regulated by specification. So, it shouldn't block any release. But, it might affect consumers of the JVMTI Extensions API.

**Comment by babsingh** [comment]
fyi @gacholio @tajila 

Targeting this work for the 0.44 Apr 2024 release.

**Comment by babsingh** [comment]
Assigned to @thallium. @thallium, you will need to post in the issue before I can add you to the `Assignees`.

**Comment by babsingh** [comment]
> We should also double check other JVMTI Extensions API for missing virtual thread support.

https://github.com/eclipse-openj9/openj9/pull/18856 has been merged. @thallium Do we need to add any more virtual support to the JVMTI Extensions API, or can we close this issue?

**Comment by thallium** [comment]
@babsingh Yes I think we can close this issue now.

**Comment by babsingh** [comment]
Closing as per https://github.com/eclipse-openj9/openj9/issues/18386#issuecomment-2007689684.
