### ISSUE TITLE
jdk commands slow response

### ISSUE THREAD

**Issue by Albedooooooo** [eclipse-openj9/openj9#18390]
Hi team,
I encountered a confusion, jdk commands(such as jps,version) take a long time when configured an incorrect dns in my environment.
Do these commands depend on getHostname method?

environment info: 
jdk:1.8.0_322
openj9: 0.30.0
centos7.6

Thanks！

**Comment by pshipton** [comment]
@JasonFengJ9 pls take a look.

**Comment by JasonFengJ9** [comment]
```
14:48:49.076 0x12c15f300              mt.0        > java/net/InetSocketAddress.getHostString()Ljava/lang/String; bytecode method, this = 0x47fec7050
14:48:49.076 0x12c15f300              mt.6        < java/net/InetSocketAddress.getHostString()Ljava/lang/String; bytecode method
14:48:49.076 0x12c15f300              mt.0        > java/net/InetSocketAddress.getAddress()Ljava/net/InetAddress; bytecode method, this = 0x47fec7050
14:48:49.076 0x12c15f300              mt.6        < java/net/InetSocketAddress.getAddress()Ljava/net/InetAddress; bytecode method
```

> Do these commands depend on getHostname method?

`jps` does invoke `java/net/InetSocketAddress.getHostString()/getAddress()`.

I don't think this is a `CRIU` issue, removing the tag.

**Comment by Albedooooooo** [comment]
> ```
> 14:48:49.076 0x12c15f300              mt.0        > java/net/InetSocketAddress.getHostString()Ljava/lang/String; bytecode method, this = 0x47fec7050
> 14:48:49.076 0x12c15f300              mt.6        < java/net/InetSocketAddress.getHostString()Ljava/lang/String; bytecode method
> 14:48:49.076 0x12c15f300              mt.0        > java/net/InetSocketAddress.getAddress()Ljava/net/InetAddress; bytecode method, this = 0x47fec7050
> 14:48:49.076 0x12c15f300              mt.6        < java/net/InetSocketAddress.getAddress()Ljava/net/InetAddress; bytecode method
> ```
> 
> > Do these commands depend on getHostname method?
> 
> `jps` does invoke `java/net/InetSocketAddress.getHostString()/getAddress()`.
> 
> I don't think this is a `CRIU` issue, removing the tag.

Thank you very much, I have got it
