### ISSUE TITLE
jdk22 -Xdebug and -debug options deprecated for removal and should print deprecation warning

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18403]
Copied from the jdk22 release notes.

-Xdebug and -debug Options Are Deprecated for Removal ([JDK-8227229](https://bugs.openjdk.org/browse/JDK-8227229))
tools/launcher

The -Xdebug and -debug options of the java command have been deprecated for removal. These options have been ignored for several releases and don't provide any functionality. Using either of these options while launching java will now log a deprecation warning.

Existing applications which use either of these options should be updated to remove references to these options.

-Xnoagent Option Is Deprecated for Removal ([JDK-8312072](https://bugs.openjdk.org/browse/JDK-8312072))
hotspot/runtime

The -Xnoagent option of the java command has been deprecated for removal. This option has been ignored for many releases and doesn't provide any functionality. It will now generate a deprecation warning when used while launching java.

Any existing code which uses this option should be updated to remove reference to this option.

**Comment by gacholio** [comment]
Adding code for deprecated options seems foolish to me.

**Comment by tajila** [comment]
@fengxue-IS Please take a look at this.
