### ISSUE TITLE
Remove java.lang.Compiler from Java 21+

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#18430]
It was removed upstream via https://github.com/openjdk/jdk/commit/a8e3a2dd2f8025986501f59f085afeffa6559e6b.

Also the following

core-libs/java.lang
[➜](https://www.oracle.com/java/technologies/javase/21-relnote-issues.html#JDK-8041676) Removal of the java.compiler System Property ([JDK-8041676](https://bugs.openjdk.org/browse/JDK-8041676))

The system property java.compiler has been removed from the list of standard system properties.

Running with this system property set on the command line will now print a warning to say that the system property is obsolete; it has no other effect. In previous releases, running with -Djava.compiler or -Djava.compiler=NONE on the command line selected interpreter only execution mode. If needed, the -Xint option can be used to run in interpreter only mode.

**Comment by pshipton** [comment]
Did you mean 22+, why do you expect jdk21 to change? Since it's GAed it would be weird to remove something from the spec now.

**Comment by keithc-ca** [comment]
You'll notice the commit I referenced is from April. The change is included in jdk21-ga (you won't see Compiler.java in https://github.com/openjdk/jdk/tree/jdk-21-ga/src/java.base/share/classes/java/lang).

**Comment by keithc-ca** [comment]
We agreed to keep this open; see https://github.com/eclipse-openj9/openj9/pull/18571#issuecomment-1841886066.
