### ISSUE TITLE
CRIU disable tests on ppc64le platform temporarily

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18468]
This is due to the limited number of `ppc64le` machines w/ proper CRIU setup.

**Comment by llxia** [comment]
PR https://github.com/eclipse-openj9/openj9/pull/18469

**Comment by AdamBrousseau** [comment]
We have all new ppc64le machines. I assume with criu setup from the PBs. Let's see if those excluded targets work now.

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3831/

**Comment by llxia** [comment]
From Jason

```
yes, the tests can be re-enabled.
there is another hang at https://openj9-jenkins.osuosl.org/job/Grinder_iteration_4/368/consoleFull, it needs to be investigated
the machines all look fine from C/R perspective
```

We will revert https://github.com/eclipse-openj9/openj9/pull/18469

**Comment by JasonFengJ9** [comment]
> there is another hang at https://openj9-jenkins.osuosl.org/job/Grinder_iteration_4/368/consoleFull

* https://github.com/eclipse-openj9/openj9/issues/18527

**Comment by JasonFengJ9** [comment]
Closing as per https://github.com/eclipse-openj9/openj9/issues/18468#issuecomment-2346305097
