### ISSUE TITLE
Docker image ibm-semeru-runtimes:open-8-jdk ppc64le failed on p8 machine

### ISSUE THREAD

**Issue by LongyuZhang** [eclipse-openj9/openj9#18559]
Failure link
------------

Public link to the failing test: hyc_grinder/job/Test_openjdk8_j9_sanity.external_ppc64le_linux/86
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): external
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): aot_test
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): ppc64le

Optional info
-------------

Quick commands to reproduce this failure:
- `docker run -it --name restore-test --rm --entrypoint '/bin/bash' docker.io/library/ibm-semeru-runtimes:open-8-jdk`
- on P10 machine: will successfully enter the docker container
- on P8 machine: will fail to enter the docker container, checking the container status showing `Exited (132)`, which might mean machine not compatible with this container image. If this is the case, we may need to disable it for P8 machines.

**Comment by pshipton** [comment]
Pls open this issue against Semeru, which creates and maintains the docker containers.
https://github.com/ibmruntimes/Semeru-Runtimes/issues
