### ISSUE TITLE
commandline compilation broken for JDK21 functional tests

### ISSUE THREAD

**Issue by smlambert** [eclipse-openj9/openj9#18620]
Failure link
------------

Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/adoptium/aqa-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include:
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): functional
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): n/a
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): all
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: JDK_IMPL=hotspot, JDK_VERSION=21, OPENJ9_BRANCH=v0.41.0-release

Optional info
-------------

- intermittent failure (yes|no): no
- regression or new test:  Failing in v0.41.0-release, though seems fixed in main
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output (captured from console output)
---------------------------------------------
Include test case name, stack trace output.  If test fails with a crash, please include a link to the artifacts (xxxx_test_output.tar.gz) as they include the core/dmp files.  Artifacts are either stored as an attachment to the CI server job itself or as a link from the job to an Artifactory location.

Run these steps to reproduce:
```
git clone --depth 1 --branch v0.9.6-release https://github.com/adoptium/aqa-tests
export TEST_JDK_HOME=/latestTemurinJDK21/bin
export USE_TESTENV_PROPERTIES=true
export JDK_VERSION=21
export JDK_IMPL=hotspot
export BUILD_LIST=functional

cd aqa-tests
./get.sh
cd TKG
make compile
```

Results in this error:
```
   [javac] /Users/shelley_lambert@ca.ibm.com/work3/aqa-tests/functional/JIT_Test/src/jit/test/jar/JarTestClassLoader.java:35: error: cannot find symbol
    [javac] 			if (Compiler.compileClass(clazz) == false){
    [javac] 			    ^
    [javac]   symbol:   variable Compiler
    [javac]   location: class JarTestClassLoader
    [javac] /Users/shelley_lambert@ca.ibm.com/work3/aqa-tests/functional/JIT_Test/src/jit/test/jar/ZipTestClassLoaderMT.java:322: error: cannot find symbol
    [javac] 			if ( Compiler.compileClass( clazz ) == false ) {
    [javac] 			     ^
    [javac]   symbol:   variable Compiler
    [javac]   location: class ZipTestClassLoaderMT

```

FYI @llxia

**Comment by hangshao0** [comment]
`Java.lang.Compiler` has been removed on Java 21 and up, see https://github.com/eclipse-openj9/openj9/issues/18430. 
The change that updated the test https://github.com/eclipse-openj9/openj9/pull/18571 is merged in master, 0.42.0 and 0.43.0 branches, not 0.41.0.

**Comment by pshipton** [comment]
Right, use the j9.0.42-release branch for OpenJ9 Java 21.

**Comment by pshipton** [comment]
Or use content for the 24_01 release.

**Comment by pshipton** [comment]
@smlambert the tests won't run on Hotspot either. What we did was keep the native implementation for java.lang.Compiler, created a new test library to call them, and modified the tests to use the new helpers. The OpenJ9 helpers won't work on Hotspot, all the tests that use these natives will have to be excluded for Hotspot.

**Comment by pshipton** [comment]
> all the tests that use these natives will have to be excluded for Hotspot

Even on versions prior to jdk21.

**Comment by pshipton** [comment]
Or rewrite the CompilerAccess.java helper to call java.lang.Compiler on versions prior to 21 so the tests can continue to work.
