### ISSUE TITLE
Possible perf regression 0.42 m1 to 0.43 m2

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18676]
From Slack
https://openj9.slack.com/archives/C01C8PL6319/p1703776509945869?thread_ts=1702921645.212339&cid=C01C8PL6319

@avermeer 
after upgrading my pre-production Apache Storm cluster from IBM Semeru 21-0.42.0-m1 to IBM Semeru 21-0.43.0-m2, I observed a small performance degradation on one Kafka "bolt" (=a piece of code in charge of writing data to a Kafka topic, using standard Apache kafka producer): this bolt's average latency increased from 13ms to 19ms.
  However, this piece of code has a modest bandwith (less than 100000 tuples per jour) and given that other Kafka bolts having greater throughput had no noticeable change in their latency, I don't know if it's worth nociting that small difference.
  For the record this Kafka bolt use Snappy compression.

**Comment by pshipton** [comment]
```
IBM Semeru Runtime Open Edition 21.0.1.0-m1 (build 21.0.1+12-LTS)
Eclipse OpenJ9 VM 21.0.1.0-m1 (build v0.42.0-release-df467094a, JRE 21 Linux amd64-64-Bit Compressed References 20231017_35 (JIT enabled, AOT enabled)
OpenJ9   - df467094a
OMR      - d810fcb98
JCL      - f15a87536b1 based on jdk-21.0.1+12)
```

```
IBM Semeru Runtime Open Edition 21.0.2.0-m2 (build 21.0.1+12-LTS)
Eclipse OpenJ9 VM 21.0.2.0-m2 (build v0.43.0-release-54becab46, JRE 21 Linux amd64-64-Bit Compressed References 20231017_57 (JIT enabled, AOT enabled)
OpenJ9   - 54becab46
OMR      - d810fcb98
JCL      - 10a4ed68a77 based on jdk-21.0.1+12)
```

Presumably the regression would also occur with jdk21 0.42 M2, which is easier to compare.

```
IBM Semeru Runtime Open Edition 21.0.1.0-m2 (build 21.0.1+12-LTS)
Eclipse OpenJ9 VM 21.0.1.0-m2 (build v0.42.0-release-69b6ceb69, JRE 21 Linux amd64-64-Bit Compressed References 20231017_66 (JIT enabled, AOT enabled)
OpenJ9   - 69b6ceb69
OMR      - 494d6eb66
JCL      - 3fe982e7d7d based on jdk-21.0.1+12)
```

**Comment by avermeer** [comment]
yes with IBM Semeru 21 milestone 2 on RedHat Linux 8, here's what I have:

 java -version
openjdk version "21.0.1" 2023-10-17 LTS
IBM Semeru Runtime Open Edition 21.0.2.0-m2 (build 21.0.1+12-LTS)
Eclipse OpenJ9 VM 21.0.2.0-m2 (build v0.43.0-release-54becab46, JRE 21 Linux amd64-64-Bit Compressed References 20231017_57 (JIT enabled, AOT enabled)
OpenJ9   - 54becab46
OMR      - d810fcb98
JCL      - 10a4ed68a77 based on jdk-21.0.1+12)

**Comment by pshipton** [comment]
I'm not sure there is anything here to investigate. Given https://github.com/eclipse-openj9/openj9/issues/18748#issuecomment-1892794989 I will go ahead and close this.
