### ISSUE TITLE
[Loom] Implement JVM_VirtualThreadDisableSuspend

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#18671]
A stub was added for `JVM_VirtualThreadDisableSuspend` (JDK23 only) in https://github.com/eclipse-openj9/openj9/pull/18667.

As per https://bugs.openjdk.org/browse/JDK-8311218, `JVM_VirtualThreadDisableSuspend` will eventually be ported to JDK22.

Also, the assertion in the stub will be triggered because `notifyJvmtiDisableSuspend -> JVM_VirtualThreadDisableSuspend` is used in `VirtualThread` methods such as `unpark`, `interrupt`, `getAndClearInterrupt`, `threadState`, and `toString`: https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/java/lang/VirtualThread.java

To avoid triggering the assertion, the stub needs to be empty.

As for the implementation, this method notifies JVMTI to disable `JVMTI suspend` operations for a `VirtualThread` by toggling a field on/off. The intent is to ignore `JVMTI suspend` operations when a `VirtualThread` is performing certain synchronized blocks related to its carrier thread.

### Next steps
- Verify if the bug exists in OpenJ9 using the test case (`Repro8311218.java`) from https://bugs.openjdk.org/browse/JDK-8311218.
- If it doesn't exist, then let `JVM_VirtualThreadDisableSuspend` stay emtpy.
- If the bug exists in OpenJ9, then implement `JVM_VirtualThreadDisableSuspend` using the above description after verifying if the JVMTI operations are `skipped` or `delayed (wait)` until the `VirtualThread` completes the synchronized block.

**Comment by tajila** [comment]
@babsingh what is the status of this?

**Comment by babsingh** [comment]
> Verify if the bug exists in OpenJ9 using the test case (Repro8311218.java) from https://bugs.openjdk.org/browse/JDK-8311218.

`Repro8311218.java` has been added as [SuspendWithInterruptLock.java](https://github.com/ibmruntimes/openj9-openjdk-jdk22/blob/openj9/test/hotspot/jtreg/serviceability/jvmti/vthread/SuspendWithInterruptLock/SuspendWithInterruptLock.java) in the `openj9-openjdk-jdk22` extension repo. I have been unable to reproduce the bug after running the `SuspendWithInterruptLock` test 200 times. I plan to leave `JVM_VirtualThreadDisableSuspend` empty (no implementation needed) since the bug doesn't exist in OpenJ9.

**Comment by babsingh** [comment]
Closed as per https://github.com/eclipse-openj9/openj9/issues/18671#issuecomment-1908312198.
