### ISSUE TITLE
jdk22 OpenJDK StackWalker/CallerSensitiveMethod - Expected class jdk.test.CallerSensitiveTest but got [class java.util.CSM]

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18696]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_aarch64_mac_Personal_testList_0/1/
jdk_lang
java/lang/StackWalker/CallerSensitiveMethod/Main.java
```
16:04:08  ERROR: Expected class jdk.test.CallerSensitiveTest but got [class java.util.CSM]
16:04:08  java.lang.UnsupportedOperationException: Stack walker configured with DROP_METHOD_INFO
16:04:08  	at java.base/java.lang.StackWalker$StackFrameImpl.ensureMethodInfo(StackWalker.java:431)
16:04:08  	at java.base/java.lang.StackWalker$StackFrameImpl.toStackTraceElement(StackWalker.java:482)
16:04:08  	at java.base/java.lang.StackWalker$StackFrameImpl.toString(StackWalker.java:512)
16:04:08  	at java.base/java.lang.String.valueOf(String.java:5285)
16:04:08  	at csm/jdk.test.CallerSensitiveTest.lambda$checkNonCSMCaller$0(CallerSensitiveTest.java:147)
16:04:08  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
16:04:08  	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
16:04:08  	at csm/jdk.test.CallerSensitiveTest.checkNonCSMCaller(CallerSensitiveTest.java:147)
16:04:08  	at csm/jdk.test.CallerSensitiveTest.invokeMethod(CallerSensitiveTest.java:111)
16:04:08  	at csm/jdk.test.CallerSensitiveTest.main(CallerSensitiveTest.java:73)
```

Perhaps related to https://github.com/eclipse-openj9/openj9/issues/18697

**Comment by pshipton** [comment]
@keithc-ca

**Comment by fengxue-IS** [comment]
the cause of this is due to missing update to the walkState pointer allocated `https://github.com/eclipse-openj9/openj9/blob/master/runtime/jcl/common/java_lang_StackWalker.cpp#L106` which allowed flags/data from previous walkState to be used during stack walking. I will open a PR to fix this shortly.

**Comment by keithc-ca** [comment]
Jenkins compile amac jdk22

**Comment by keithc-ca** [comment]
Tests to be unexcluded via https://github.com/adoptium/aqa-tests/pull/5066.

**Comment by pshipton** [comment]
Reopen since https://github.com/eclipse-openj9/openj9/pull/18926 was reverted.

**Comment by keithc-ca** [comment]
@pshipton Do you think we should re-exclude the test, i.e. revert https://github.com/adoptium/aqa-tests/pull/5066?

**Comment by keithc-ca** [comment]
See https://github.com/adoptium/aqa-tests/pull/5072.

**Comment by pshipton** [comment]
In jdk17+, StackWalkerTest hangs. 

Also spotted these related failures on AIX, where the GEN process times out. This could probably affect other system tests.
DaaLoadTest_all_CS_5m_0	
MiniMix_5m_0 
TestIBMJlmLocal_0 
SharedClassesAPI_0
