### ISSUE TITLE
Jep425Tests_testVirtualThread verifyJVMTIMacros - the VirtualThread states in jdk22 are different

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18693]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_aarch64_mac_Personal_testList_0/1
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_aarch64_mac_Personal_testList_1/1
Jep425Tests_testVirtualThread
```
FAILED: test_verifyJVMTIMacros
java.lang.AssertionError: Unexpected exception occured : RUNNABLE
	at org.testng.Assert.fail(Assert.java:85)
	at org.openj9.test.jep425.VirtualThreadTests.test_verifyJVMTIMacros(VirtualThreadTests.java:350)
```

The VirtualThread states in jdk22 are different from jdk21 and the test.
```
    private static final int NEW      = 0;
    private static final int STARTED  = 1;
    private static final int RUNNING  = 2;     // runnable-mounted

    // untimed and timed parking
    private static final int PARKING       = 3;
    private static final int PARKED        = 4;     // unmounted
    private static final int PINNED        = 5;     // mounted
    private static final int TIMED_PARKING = 6;
    private static final int TIMED_PARKED  = 7;     // unmounted
    private static final int TIMED_PINNED  = 8;     // mounted
    private static final int UNPARKED      = 9;     // unmounted but runnable
```

**Comment by pshipton** [comment]
@babsingh

**Comment by babsingh** [comment]
This issue will be resolved by
- https://github.com/eclipse-openj9/openj9/pull/18673
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/103

This is related to https://bugs.openjdk.org/browse/JDK-8321270, and JDK21 is also affected by this issue. So, the new virtual thread states will eventually be ported to JDK21. The above extension repo PR backoprts the fix to JDK21 so that we don't have to add ifdefs in the OpenJ9 PR.

**Comment by keithc-ca** [comment]
The pull requests mentioned in https://github.com/eclipse-openj9/openj9/issues/18693#issuecomment-1879505836 have been merged. Is it time to close this?

**Comment by pshipton** [comment]
Trying the test https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3195/

**Comment by pshipton** [comment]
That's not going to work, there is no jdk22 build created since the fix was merged. I've started a build and will restart the grinder.

**Comment by babsingh** [comment]
Closing the issue. Tested locally with JDK22, and the test passes.

**Comment by pshipton** [comment]
I've also added a nightly build of jdk22 for all platforms.
