### ISSUE TITLE
JDK 23 builds require Boot JDK 21

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18707]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/456/consoleFull

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
23:23:25  * Boot JDK:       openjdk version "20.0.2" 2023-07-18 IBM Semeru Runtime Open Edition 20.0.2.0 (build 20.0.2+9) Eclipse OpenJ9 VM 20.0.2.0 (build openj9-0.40.0, JRE 20 Linux aarch64-64-Bit Compressed References 20230718_68 (JIT enabled, AOT enabled) OpenJ9 - d12d10c9e OMR - e80bff83b JCL - 19eb54abdac based on jdk-20.0.2+9) (at /home/jenkins/bootjdks/jdk20)

23:40:56  === Output from failing command(s) repeated here ===
23:40:56  * For target buildtools_interim_langtools_modules_jdk.javadoc.interim__the.BUILD_jdk.javadoc.interim_batch:
23:40:56  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/src/jdk.javadoc/share/classes/jdk/javadoc/internal/tool/Start.java:684: error: cannot find symbol
23:40:56              case 1 -> showLinesUsingKey("main.did-you-mean", suggestions.getFirst());
23:40:56                                                                          ^
23:40:56    symbol:   method getFirst()
23:40:56    location: variable suggestions of type List<String>
23:40:56  1 error
```

Using JDK 21 as the Boot JDK the JDK23 build succeeds. 

FYI @pshipton @AdamBrousseau

**Comment by pshipton** [comment]
We should have a jdk21 release later this week.

**Comment by keithc-ca** [comment]
JDK21 builds are now available.
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/730 reverts https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/671, https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/696 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/719 - closing this.
