### ISSUE TITLE
Release notes for 0.41 do not mention support for JITServer on Linux on aarch64 

### ISSUE THREAD

**Issue by hzongaro** [eclipse-openj9/openj9#18717]
Support for JITServer was enabled on Linux on aarch64 in release-0.41, but inadvertently that was not mentioned in the [release notes for that release](https://github.com/eclipse-openj9/openj9/blob/0cd684edf7e85cb09417b5005f10a75ba8d7a351/doc/release-notes/0.41/0.41.md).

I don't know whether the 0.41 release notes should be updated at this point or if this should be called out in the 0.42 release notes.  Regardless, the external documentation for JITServer at https://eclipse.dev/openj9/docs/jitserver/ should be updated.

@0xdaryl - FYI

**Comment by pshipton** [comment]
This would be better created at https://github.com/eclipse-openj9/openj9-docs/issues/. The typical order is to add it to the User Guide and then update the release notes .md file from those items.

**Comment by hzongaro** [comment]
Opened eclipse-openj9/openj9-docs#1243
