### ISSUE TITLE
Attach mechanism implementation needs to prevent deletion of notification files by systemd

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#18720]
By default, the JVM's Attach mechanism places its notification files in the system temporary directory, typically in a sub-directory in `/tmp/.com_ibm_tools_attach`. My understanding is that the JVM does not open, modify or read from these files after they have been created.

This causes a problem for long running JVM processes in Linux environments that use `systemd`, because by default `systemd-tmpfiles` will automatically delete files in `/tmp` that haven't been accessed for 10 days. More information can be found here:

https://systemd.io/TEMPORARY_DIRECTORIES/

Obviously the user can specify a different location in which to place the Attach notification files using the `com.ibm.tools.attach.directory` system property, but out of the box the Attach mechanism will fail for JVMs that run for longer than 10 days.

There are various options outlined in the paged linked above for protecting temp files from automatic deletion. I think the JVM should implement one of these options.

**Comment by pshipton** [comment]
@TobiAjila fyi
