### ISSUE TITLE
Java23: Thread.suspend() and Thread.resume(), etc. have been removed

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9#18758]
Failure link
------------

Test code no longer compiles against the head stream:
* https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_aarch64_linux_Personal_testList_0/31.

The upstream change
* [8320532: Remove Thread/ThreadGroup suspend/resume](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/d053eba1965318f8aa41bf45be606b5046a922ce)

Failure output (captured from console output)
---------------------------------------------
```
10:27:04      [javac] /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_aarch64_linux_Personal_testList_0/aqa-tests/functional/Java8andUp/src/org/openj9/test/java/lang/Test_Thread.java:723: error: cannot find symbol
10:27:04      [javac] 				ct.suspend();
10:27:04      [javac] 				  ^
10:27:04      [javac]   symbol:   method suspend()
10:27:04      [javac]   location: variable ct of type Thread
```

**Comment by pshipton** [comment]
@llxia is there somebody who can fix this?

**Comment by llxia** [comment]
@LongyuZhang could you please take a look? Thanks

**Comment by keithc-ca** [comment]
I think we may have arrived at the point where it makes sense to use the Java preprocessor on test code as well so the effects of API differences like this can simply be encapsulated like this:
```java
/*[IF JAVA_SPEC_VERSION < 23]*/
// tests that depend upon API removed in Java 23
/*[ENDIF] JAVA_SPEC_VERSION 23 */
```

**Comment by pshipton** [comment]
Changes are merged.
