### ISSUE TITLE
OpenJDK java/util/concurrent/SynchronousQueue/Fairness - Error: fair=true i=6 j=7

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18771]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_s390x_linux_Release_testList_0/10/
jdk_util_1
java/util/concurrent/SynchronousQueue/Fairness.java
```
19:29:58  java.lang.Error: fair=true i=6 j=7
19:29:58  
19:29:58  	at Fairness.testFairness(Fairness.java:64)
19:29:58  	at Fairness.main(Fairness.java:73)
19:29:58  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
19:29:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
19:29:58  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
19:29:58  	at java.base/java.lang.Thread.run(Thread.java:1595)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/3181/

**Comment by pshipton** [comment]
The grinder isn't finished, but this failure has already been repeated a couple of time.
https://openj9-jenkins.osuosl.org/job/Grinder_iteration_0/413
https://openj9-jenkins.osuosl.org/job/Grinder_iteration_2/371

@tobi someone needs to look at this.

**Comment by keithc-ca** [comment]
I think the test is broken: There's nothing in the code prioritizes threads started earlier over those started later.

It is possible that the test is in a state where all the started threads are immediately after the call to `lock.unlock()` (but before the call to `q.put(I)`) before CPU cores are available to advance any of them. When processors are available, they can be scheduled in any order, providing no guarantee that the values are queued in order of ascending value.

By artificially inserting delays between those two calls (longer for smaller-numbered threads) the test can be made to fail at will.

**Comment by keithc-ca** [comment]
In fact, even if all threads call `Thread.sleep(0)` the test fails regularly.

**Comment by pshipton** [comment]
It's not a new test, and the test hasn't changed in years. It's not failing on other platforms, and we haven't seen it fail previously. I'm wondering what changed, and why it only fails on zlinux now.

**Comment by keithc-ca** [comment]
There are changes to `SynchronousQueue` between the openj9 and openj9-staging branches. In particular, this [commit](https://github.com/ibmruntimes/openj9-openjdk-jdk21/commit/291aa2aa2a215b68b96c2debfc58e081d5f4322b) makes reference to that test failing

> 8300663: java/util/concurrent/SynchronousQueue/Fairness.java failed with "Error: fair=true i=0 j=1"

I'll dig deeper to see if I can find an explanation there.

**Comment by keithc-ca** [comment]
In https://bugs.java.com/bugdatabase/view_bug?bug_id=8300663 they seem to agree that testing fairness is difficult (emphasis mine):

> I strongly suspect that any test trying to assert for fairness in this case will have to establish a total order, and as such total order is **_not likely to exist in any real-world use-case_** my bet is that **_fairness in this case (synchronous queue) is not observable_**.

**Comment by pshipton** [comment]
If we're going to ignore the test failure, the test needs to be excluded. I'd start with just on zlinux unless we start to see it fail elsewhere.

**Comment by keithc-ca** [comment]
The code for `SynchronousQueue` is the same in jdk21, jdk22 and jdknext. I just reproduced the problem with jdknext on xLinux. I suggest it should be excluded on all platforms.

**Comment by pshipton** [comment]
ok

**Comment by pshipton** [comment]
For the record, it's not failing on the zlinux 21.0.2 Temurin build.
https://openj9-jenkins.osuosl.org/job/Grinder/3184/
```
14:47:33  openjdk version "21.0.2-beta" 2024-01-16
14:47:33  OpenJDK Runtime Environment Temurin-21.0.2+13-202401172331 (build 21.0.2-beta+13-ea)
14:47:33  OpenJDK 64-Bit Server VM Temurin-21.0.2+13-202401172331 (build 21.0.2-beta+13-ea, mixed mode, sharing)
```

**Comment by pshipton** [comment]
Pls create a PR for https://github.com/adoptium/aqa-tests/tree/v1.0.0-release as well.

**Comment by keithc-ca** [comment]
> Pls create a PR for https://github.com/adoptium/aqa-tests/tree/v1.0.0-release as well.

Done: https://github.com/adoptium/aqa-tests/pull/4988

**Comment by pshipton** [comment]
Are any changes for this expected in the next couple of weeks, or should it be moved forward to the next release?

**Comment by keithc-ca** [comment]
The changes to `Thread.getAndClearInterrupt()` that were made in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/746 may have resolved this for jdk23+. I think we should back-port that change to jdk22 and jdk21 which should fix this for those versions as well.

**Comment by keithc-ca** [comment]
As we discovered in testing the related pull requests, removing the synchronization that breaks this test reintroduces a more serious, functional problem. I think the synchronization should be restored in the head stream until a solution that doesn't need it is discovered.

**Comment by keithc-ca** [comment]
See https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/748 which restores that synchronization;

I think we should move this forward to the next release. I don't think it could cause any defensible real-world problems.
