### ISSUE TITLE
jdk22 WrapperHiddenClassTest: MHP impl class cannot be cleared by GC

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9#18804]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_aarch64_linux_Personal_testList_0/1
jdk_lang
java/lang/invoke/MethodHandleProxies/WrapperHiddenClassTest.java

```
16:34:54  STARTED    WrapperHiddenClassTest::testWeakImplClass '[2] interface Client'
16:34:54  org.opentest4j.AssertionFailedError: MHP impl class cannot be cleared by GC
16:34:54  	at junit.platform.console.standalone@1.9.2/org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
16:34:54  	at junit.platform.console.standalone@1.9.2/org.junit.jupiter.api.Assertions.fail(Assertions.java:135)
16:34:54  	at WrapperHiddenClassTest.testWeakImplClass(WrapperHiddenClassTest.java:209)
... 
16:34:54  FAILED     WrapperHiddenClassTest::testWeakImplClass '[2] interface Client'
```

**Comment by babsingh** [comment]
There are two `WrapperHiddenClassTest` failures: this issue and https://github.com/eclipse-openj9/openj9/issues/18805. The failures only happen with `gencon` and `optthruput` GC policies. `WrapperHiddenClassTest` consistently passes with `metronome` and `balanced` GC policies.

fyi @dmitripivkine

**Comment by dmitripivkine** [comment]
> There are two `WrapperHiddenClassTest` failures: this issue and #18805. The failures only happen with `gencon` and `optthruput` GC policies. `WrapperHiddenClassTest` consistently passes with `metronome` and `balanced` GC policies.
> 
> fyi @dmitripivkine

Such set of GC policies points to the JIT most likely. There are many JIT optimizations disabled for Metronome and Balanced. Another possibility for such set that Discontiguous array can be involved, code might expect contiguous array mistakenly.

**Comment by dmitripivkine** [comment]
@babsingh Would you please help to triage this?
I need:
- link to the test source
- help to generate system core to look at
- nice to have comments what test trying to achieve and what is failed (ideally with references in the core)

**Comment by babsingh** [comment]
> link to the test source

16:34:54  	at WrapperHiddenClassTest.testWeakImplClass(WrapperHiddenClassTest.java:209)

https://github.com/ibmruntimes/openj9-openjdk-jdk22/blob/1159998e1cb3beb441d35bc1ca6aea768d6c9afb/test/jdk/java/lang/invoke/MethodHandleProxies/WrapperHiddenClassTest.java#L209

> nice to have comments what test trying to achieve and what is failed (ideally with references in the core)

Tests the caching and weak reference of implementation classes for system and user interfaces. Test expects the GC to clear the weak reference after the strong reference has been cleared.

> help to generate system core to look at

This failure is intermittent, and the failure in #18805 is dominating the test runs. I will share a link to the core file once I generate it.

**Comment by pshipton** [comment]
This can be closed now that https://github.com/eclipse-openj9/openj9/pull/19020 is merged?

**Comment by babsingh** [comment]
I had locally verified that https://github.com/eclipse-openj9/openj9/pull/19020 fixes this issue. I have opened https://github.com/adoptium/aqa-tests/pull/5116 to re-enable the test.
