### ISSUE TITLE
NoSuchFieldException for enum with special characters

### ISSUE THREAD

**Issue by ljgp** [eclipse-openj9/openj9#18816]
Java -version output
--------------------
openjdk version "17.0.9" 2023-10-17
IBM Semeru Runtime Open Edition 17.0.9.0 (build 17.0.9+9)
Eclipse OpenJ9 VM 17.0.9.0 (build openj9-0.41.0, JRE 17 Windows 10 amd64-64-Bit Compressed References 20231017_568 (JIT enabled, AOT enabled)
OpenJ9   - 461bf3c70
OMR      - 5eee6ad9d
JCL      - 3699725139c based on jdk-17.0.9+9)

Summary of problem
------------------
For enums with accents, class.getField causes a NoSuchFieldException. I tried other Jvms like Azul where this seems to work fine.

Diagnostic files
----------------
public class NoSuchFieldTest {
    enum Offender {
        INITIËLE_VULLING("initiele vulling");
        private final String value;
        Offender(String v) {
            this.value = v;
        }
    }
    public static void main( String[] args) throws NoSuchFieldException {
        Offender.class.getField( Offender.INITIËLE_VULLING.name());
    }
}

**Comment by pshipton** [comment]
It works when I run it with `-XX:-CompactStrings`. This is a dup of https://github.com/eclipse-openj9/openj9/issues/18791 which was just fixed and will be resolved in the next release (0.43) due out in Feb.

**Comment by pshipton** [comment]
An open source pre-release build for the upcoming release.

https://openj9-jenkins.osuosl.org/job/Pipeline-Release-0.43.0-Build17/16/

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK17_x86-64_windows_Release/102/OpenJ9-JDK17-x86-64_windows-20240124-192341.tar.gz

**Comment by ljgp** [comment]
Hi Peter,

Thanks for the fast reply ! Good news !

Regards, Luc.
