### ISSUE TITLE
New field access flag in Valhalla

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#18828]
In the latest Valhalla draft spec

`ACC_STRICT(0x0800)` is added to the field access flags in value type, indicating

`A strictly-enforced final field; may only be assigned at the start of object construction.`

The following change in [section 4.5](https://cr.openjdk.org/~dlsmith/jep401/jep401-20240116/specs/value-objects-jvms.html#jvms-4.5) requires OpenJ9 to update the class format check: 

```
A field must not have set both ACC_FINAL and ACC_VOLATILE, and must not have set both ACC_STRICT and ACC_STATIC.
A field that has set ACC_STRICT must also have set ACC_FINAL.
Each field of a value class must have exactly one of its ACC_STATIC or ACC_STRICT flags set.
```

The additional check of `ACC_STRICT` in [4.10.1.9](https://cr.openjdk.org/~dlsmith/jep401/jep401-20240116/specs/value-objects-jvms.html#jvms-4.10.1.9) requires OpenJ9 to update the verification code.

**Comment by theresa-m** [comment]
Class verification for this issue has been completed in https://github.com/eclipse-openj9/openj9/pull/19830

This issue is staying open since we are expecting future spec changes regarding `putfield` behavior.

**Comment by hangshao0** [comment]
We can close this. If there are further change to `putfield`, we can open a new issue.
