### ISSUE TITLE
 J9 Java [Linux IA32] 80 Compile intermittent Segmentation fault (core dumped) ./j9ddrgen

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#18838]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=76911696)(`cent8x64vs1`):

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
cd ./ && ./j9ddrgen
Encoding struct data
Creating output file j9ddr.dat of size 677872
Completed with no errors
/bin/sh: line 1:  1702 Segmentation fault      (core dumped) ./j9ddrgen
makefile:832: recipe for target 'run_j9ddrgen' failed
make[1]: *** [run_j9ddrgen] Error 139
make[1]: Leaving directory '/tmp/bld_64905/bld_linux_x86'
/bluebird/builds/bld_64905/build/linux_x86/compile_vm.mk:144: recipe for target 'phase_core' failed
```

From test history this occurred intermittently.

**Comment by pshipton** [comment]
This is an internal problem related to the docker container used to build. @AdamBrousseau has plans to rebuild it which will hopefully resolve this.

**Comment by pshipton** [comment]
Related to runtimes/infrastructure/issues/8864
