### ISSUE TITLE
JDK22: Excluded tests list

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9#18844]
Test list:
java/util/concurrent/locks/Lock/OOMEInAQS

**Comment by tajila** [comment]
@babsingh Can you please add the list of known JDK22 failures here so we can make test excludes for them.

**Comment by babsingh** [comment]
I will open a PR against aqa-test to disable all the JDK22 tests which fail: https://github.com/eclipse-openj9/openj9/milestone/50

**Comment by babsingh** [comment]
Opened https://github.com/adoptium/aqa-tests/pull/5017 to disable JDK21/22 failing tests.

**Comment by babsingh** [comment]
Closing. https://github.com/adoptium/aqa-tests/pull/5017 has been merged, and the tests have been excluded.
