### ISSUE TITLE
Semeru 8 throws an InternalError with option -Djava.security.manager=allow instead of ignoring it

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9#18900]
According to the documentation for OpenJ9 0.41 (used in Semeru 8.0.392.0) the option `-Djava.security.manager=allow` should be ignored from this release onwards:

> From OpenJDK version 18 onwards, if you enable the SecurityManager at runtime by calling the System.setSecurityManager() API, you must set the -Djava.security.manager=allow option. To disable the SecurityManager, you must specify the -Djava.security.manager=disallow option. If an application is designed to run on multiple OpenJDK versions, the same command line might be used across multiple versions. Because of this use of the same command line across multiple versions, in OpenJDK versions before version 18, the runtime attempts to load a SecurityManager with the class name allow or disallow resulted in an error and the application was not starting.
> 
> To resolve this issue, OpenJDK version 17 ignores these options. **With this release, OpenJDK versions 8 and 11 also ignore the allow and disallow keywords, if specified**.

https://eclipse.dev/openj9/docs/version0.41/#change-in-behavior-of-the-djavasecuritymanager-system-property-for-openjdk-version-8-and-11

However, Semeru 8.0.392.0 (which uses OpenJ9 0.41) and later Semeru 8 releases fail to launch with an InternalError when the option `-Djava.security.manager=allow` (or `-Djava.security.manager=disallow`) is specified. For example, with 8.0.402.0:

```
> java -Djava.security.manager=allow -version
Exception in thread "main" java/lang/InternalError: Could not create SecurityManager: allow
        at sun/misc/Launcher.<init> (Launcher.java:106)
        at sun/misc/Launcher.<clinit> (Launcher.java:54)
        at java/lang/ClassLoader.initializeClassLoaders (ClassLoader.java:196)
        at java/lang/Thread.initialize (Thread.java:404)
        at java/lang/Thread.<init> (Thread.java:161)
```

I checked with the latest Semeru 8 nightly and it still has the same issue. The equivalent Semeru 11 release (11.0.21.0) and later Semeru 11 releases ignore the option as expected.

The problem appears to involve [this line of code](https://github.com/eclipse-openj9/openj9/blob/a088421c98d61be19e8d2134fc27f33476bde46a/jcl/src/java.base/share/classes/java/lang/ClassLoader.java#L292). Maybe there should be a call to [System.initSecurityManager()](https://github.com/eclipse-openj9/openj9/blob/a088421c98d61be19e8d2134fc27f33476bde46a/jcl/src/java.base/share/classes/java/lang/System.java#L1187) here instead?

**Comment by pshipton** [comment]
Related change
https://github.com/eclipse-openj9/openj9/pull/18402
