### ISSUE TITLE
jdk22 java/foreign/TestUpcallAsync.java Processing dump event "abort"

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18941]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_ppc64_aix_Nightly_testList_2/4
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/4
jdk_foreign
java/foreign/TestUpcallAsync.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk22_j9_sanity.openjdk_ppc64_aix_Nightly_testList_0/4/openjdk_test_output.tar.gz
```
03:48:31  JVMDUMP039I Processing dump event "abort", detail "" at 2024/02/10 08:35:46 - please wait.
```

@ChengJin01 fyi

**Comment by ChengJin01** [comment]
Close the issue as resolved via https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/32.
