### ISSUE TITLE
StackWalkerTest testGetCallerClass caller class wrong 

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18961]
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/742/ - all tested platforms

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_linux_Nightly_testList_0/604
StackWalkerTest_1 `-Xjit:count=0`
```
23:24:51  FAILED: testGetCallerClass
23:24:51  java.lang.AssertionError: caller class wrong expected [class org.openj9.test.stackWalker.StackWalkerTest] but found [class java.lang.StackWalker]
23:24:51  	at org.testng.Assert.fail(Assert.java:96)
23:24:51  	at org.testng.Assert.failNotEquals(Assert.java:776)
23:24:51  	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
23:24:51  	at org.testng.Assert.assertEquals(Assert.java:118)
23:24:51  	at org.openj9.test.stackWalker.StackWalkerTest.testGetCallerClass(StackWalkerTest.java:92)
```

Changes from previous build
https://github.com/eclipse-openj9/openj9/compare/1690101f1...70b540ef522
https://github.com/eclipse-openj9/openj9-omr/compare/3f8a0e713...0966eb360f6

Tested by reverting https://github.com/eclipse-openj9/openj9/pull/18926 to confirm this is the cause.
Failure on nightly build https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3308/
Passing with 18926 reverted https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3309/

I'm going to revert the change.

@keithc-ca @fengxue-IS

**Comment by pshipton** [comment]
SC_Softmx_JitAot also passed with the change reverted so this extended.system test failure appears to also have the same cause.

**Comment by pshipton** [comment]
In jdk17+, StackWalkerTest hangs. 

Also spotted these related failures, some of there where the GEN process times out. This could affect other system tests.

DaaLoadTest_all_CS_5m_0	
MiniMix_5m_0 
TestIBMJlmLocal_0 
SharedClasses.SCM23.SingleCL_1

MathLoadTest_bigdecimal_CS_5m_0
CpMpModJar_1
CpMpModJar2_1
AutoMod1_1
TestJlmRemoteClassNoAuth_1
DaaLoadTest_daa2_5m_0
MauveMultiThrdLoad_5m_1 

SharedClassesAPI_0
SharedClassesAPI_1

**Comment by pshipton** [comment]
Not sure if this is related, probably.

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.system_ppc64le_linux_Nightly_testList_2/153
PatModImg_Unex_0
```
19:46:07  OT3 1) testOverrideUsingAppModuleAndNewPackage(net.adoptopenjdk.test.modularity.junit.TestOverrideUsingAppModuleAndNewPackage)
19:46:07  OT3 java.lang.IllegalAccessException: class net.adoptopenjdk.test.modularity.junit.TestOverrideUsingAppModuleAndNewPackage (in module com.test) cannot access class adoptopenjdk.test.modularity.hellonew.HelloNew (in module com.hello) because module com.hello does not export adoptopenjdk.test.modularity.hellonew to module com.test
19:46:07  OT3 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
19:46:07  OT3 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
19:46:07  OT3 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:495)
19:46:07  OT3 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
19:46:07  OT3 	at com.test/net.adoptopenjdk.test.modularity.junit.TestOverrideUsingAppModuleAndNewPackage.testOverrideUsingAppModuleAndNewPackage(TestOverrideUsingAppModuleAndNewPackage.java:31
```

**Comment by fengxue-IS** [comment]
Looks like the failure occurred in `StackWalkerTest_1 -Xjit:count=0` is a conflicting use of `vmThread->stackWalkState` updated in #18926, I will rework the solution to avoid this issue.

**Comment by pshipton** [comment]
Since the change was reverted I'll close this.
