### ISSUE TITLE
sun/security/krb5/auto/rcache_usemd5.sh Exception

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#18980]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_OpenJDK8_testList_2/14 - [cent8-aarch64-4](https://openj9-jenkins.osuosl.org/computer/cent8-aarch64-4)
jdk_security4_0, jdk_security4_1
sun/security/krb5/auto/rcache_usemd5.sh
```
00:06:00  java.lang.Exception
00:06:00  	at ReplayCacheTestProc.main0(ReplayCacheTestProc.java:272)
00:06:00  	at ReplayCacheTestProc.main(ReplayCacheTestProc.java:319)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8_testList_2/8/ - [cent8-ppcle-5](https://openj9-jenkins.osuosl.org/computer/cent8-ppcle-5)
jdk_security4_0 
sun/security/krb5/auto/rcache_usemd5.sh
```
00:38:18  java.lang.Exception
00:38:18  	at ReplayCacheTestProc.main0(ReplayCacheTestProc.java:272)
00:38:18  	at ReplayCacheTestProc.main(ReplayCacheTestProc.java:319)
```

Change is [8168518: rcache interop with krb5-1.15](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/7e96e3f2c571b7074433c4e9b85befb72932ff9e)

**Comment by pshipton** [comment]
Blocking acceptance of jdk8u412-b04

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Nightly_testList_2/167/ - [cent8-aarch64-1](https://openj9-jenkins.osuosl.org/computer/cent8-aarch64-1)

This ones that run on Ubuntu or cent7 pass, the failures may only occur on cent8.
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_OpenJDK8_testList_2/15 -  [ub20-aarch64-1](https://openj9-jenkins.osuosl.org/computer/ub20-aarch64-1)

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8_testList_0/9/ - [ub18-ppcle-2](https://openj9-jenkins.osuosl.org/computer/ub18-ppcle-2)
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8_testList_2/9 - [cent7-ppcle-5](https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-5)

**Comment by pshipton** [comment]
Excluding the test https://github.com/adoptium/aqa-tests/pull/5092

**Comment by pshipton** [comment]
Jason looked and it might be something to do with the configuarion files for kerberos.

**Comment by taoliult** [comment]
The test case is under `sun/security/krb5`, it is not FIPS related.

I run the `jdk_security4`, with

> Semeru OpenJDK8 `ppc64le_linux` and `aarch64_linux` builds.

> My own aqa-tests repo ( https://github.com/taoliult/aqa-tests/tree/master ) which removed `sun/security/krb5/auto/rcache_usemd5.sh` from `ProblemList_openjdk8-openj9.txt` list.

> My own JDK8 repo ( https://github.com/taoliult/openj9-openjdk-jdk8/tree/tao ), for the openjdk8 `jdk_security4` test. I need to manually make a test failed so that all the test results can show in the test report.

The test `sun/security/krb5/auto/rcache_usemd5` is passed both using `ppc64le_linux` and `aarch64_linux` builds.

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/42783/
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/42785/

Peter mentioned `These ones that run on Ubuntu or cent7 pass, the failures may only occur on cent8`. I will check if this related to cent8 or not.

**Comment by taoliult** [comment]
@pshipton 

About “These ones that run on Ubuntu or cent7 pass, the failures may only occur on cent8.”

I checked the Jenkins machines list for all the Linux platforms, did not find any cent7 or cent8 machines. For cent9, it only has the x86 platforms, did not find any aarch64 or ppcle cent OS machines.

https://hyc-runtimes-jenkins.swg-devops.com/label/sw.os.linux/

**Comment by pshipton** [comment]
We had to return all the equinix aarch64 machines last month, we only have Ubuntu at OSU remaining.
https://openj9-jenkins.osuosl.org/label/hw.arch.aarch64&&ci.geo.osu/

The machine that powers all plinux has been down for months, not sure when we'll be able to get it up and running again.

You could try some internal machines.

**Comment by taoliult** [comment]
I tried to create the Fyre VM for local test, but there is no cent OS in p/z linux. There is only cent OS 9 for x84 platforms. And I run the test in cent OS 9 x86, it also passed. Link below:

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/42944/

And since we don’t think it is a blocker for the current release and I can’t reproduce it, I would say, we keep monitoring this issue for a while until the issue shows again.

**Comment by jasonkatonica** [comment]
As per @taoliult comments above this is no longer reproducible and not expected to occur in our supported environments this issue can now be closed until seen again.
