### ISSUE TITLE
Hotspot reports IllegalAccessError, while OpenJ9 reports NumberFormatException

### ISSUE THREAD

**Issue by TemporaryRepos** [eclipse-openj9/openj9#19015]
## Affected versions

We found a test case with execution problems. To facilitate analysis, we simplified the test case and the simplified class file can ben found at attachment.

Linux Ubuntu20.04

Java -version output under Linux

```
openjdk version "1.8.0_402"
IBM Semeru Runtime Open Edition (build 1.8.0_402-b06)
Eclipse OpenJ9 VM (build openj9-0.43.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240131_861 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 0fa9d9c532 based on jdk8u402-b06)
```

```
openjdk version "11.0.22" 2024-01-16
IBM Semeru Runtime Open Edition 11.0.22.0 (build 11.0.22+7)
Eclipse OpenJ9 VM 11.0.22.0 (build openj9-0.43.0, JRE 11 Linux amd64-64-Bit Compressed References 20240131_966 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 7876cac747 based on jdk-11.0.22+7)
```

```
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0 (build 17.0.10+7)
Eclipse OpenJ9 VM 17.0.10.0 (build openj9-0.43.0, JRE 17 Linux amd64-64-Bit Compressed References 20240116_670 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 2aad089841f based on jdk-17.0.10+7)
```

## Problem summary

This test case first throws a NumberFormatException and catches it. Run the same test case with Hotspot and OpenJ9, Hotspot reports IllegalAccessError, And OpenJ9 reports NumberFormatException. Is this due to the different order of analysis in the two virtual machines, or is there a bug inside the virtual machines?

```java
public class MarkReset {
    public static void main(String[] var0) throws Exception {
        try {
            new Double("Vt-U");
        } catch (TestReplacedNodesOSR$MyException var1) {
        }
    }
}

```
Steps to Reproduce
```
java-8/bin/java javaT.util.zip.InflaterInputStream.MarkReset
```
Expected Result
```
Exception in thread "main" java.lang.IllegalAccessError
```
Actual Result
```
Exception in thread "main" java.lang.NumberFormatException
```
## Attachment

[202402261523.zip](https://github.com/eclipse-openj9/openj9/files/14401063/202402261523.zip)

**Comment by pshipton** [comment]
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "Vt-U"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at java.lang.Double.<init>(Double.java:608)
        at javaT.util.zip.InflaterInputStream.MarkReset.main(Unknown Source)
```

```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class TestReplacedNodesOSR$MyException from class javaT.util.zip.InflaterInputStream.MarkReset
        at javaT.util.zip.InflaterInputStream.MarkReset.main(Unknown Source)
```

Seems like a difference in how verification works. 
@tajila @ChengJin01 fyi

**Comment by pshipton** [comment]
When running with -verbose you do see IllegalAccessError being loaded.
```
class load: java/lang/IllegalArgumentException from: /home/peter/jdk8u402-b06/jre/lib/rt.jar
class load: java/lang/NumberFormatException from: /home/peter/jdk8u402-b06/jre/lib/rt.jar
class load: java/lang/IncompatibleClassChangeError from: /home/peter/jdk8u402-b06/jre/lib/rt.jar
class load: java/lang/IllegalAccessError from: /home/peter/jdk8u402-b06/jre/lib/rt.jar
```

**Comment by tajila** [comment]
@singh264 Please take a look at this

**Comment by singh264** [comment]
> This [test case](https://github.com/eclipse-openj9/openj9/issues/19015#issue-2153438460) first throws a NumberFormatException and catches it. Run the same test case with Hotspot and OpenJ9, Hotspot reports IllegalAccessError, And OpenJ9 reports NumberFormatException. Is this due to the different order of analysis in the two virtual machines, or is there a bug inside the virtual machines?

The openj9 behaviour seems to be valid based on the following detail in section `5.4 Linking` of the [jvm specification](https://docs.oracle.com/javase/specs/jvms/se21/jvms21.pdf):

```
For example, a Java Virtual Machine implementation may choose a "lazy" linkage
strategy, where each symbolic reference in a class or interface (other than the
symbolic references above) is resolved individually when it is used. Alternatively,
an implementation may choose an "eager" linkage strategy, where all symbolic
references are resolved at once when the class or interface is being verified. This
means that the resolution process may continue, in some implementations, after a
class or interface has been initialized. Whichever strategy is followed, any error
detected during resolution must be thrown at a point in the program that (directly
or indirectly) uses a symbolic reference to the class or interface.
```

The detail indicates that `"any error detected during resolution must be thrown at a point in the program"`, which is reflected in openj9 behaviour as it throws the `NumberFormatException` at `bytecode 5`, and it seems like hotspot throws the `IllegalAccessError` at `bytecode 11`.


```
javap -c javaT/util/zip/InflaterInputStream/MarkReset.class 
public class javaT.util.zip.InflaterInputStream.MarkReset {
  public javaT.util.zip.InflaterInputStream.MarkReset();
    Code:
       0: aload_0
       1: invokespecial #8                  // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]) throws java.lang.Exception;
    Code:
       0: new           #16                 // class java/lang/Double
       3: ldc           #18                 // String Vt-U
       5: invokespecial #21                 // Method java/lang/Double."<init>":(Ljava/lang/String;)V <-----
       8: goto          12
      11: astore_0 <-----
      12: return
    Exception table:
       from    to  target type
           0    11    11   Class TestReplacedNodesOSR$MyException
}
```

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "Vt-U"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at java.lang.Double.<init>(Double.java:608)
        at javaT.util.zip.InflaterInputStream.MarkReset.main(Unknown Source)
```

```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class TestReplacedNodesOSR$MyException from class javaT.util.zip.InflaterInputStream.MarkReset
        at javaT.util.zip.InflaterInputStream.MarkReset.main(Unknown Source)
```

**Comment by singh264** [comment]
@TemporaryRepos I would like access to the source code with compilation instructions to verify if openj9 throws `IllegalAccessError` when `new Double("Vt-U")` is removed from the test.

```
public class MarkReset {
    public static void main(String[] var0) throws Exception {
        try {
            new Double("Vt-U");
        } catch (TestReplacedNodesOSR$MyException var1) {
        }
    }
}
```

**Comment by ChengJin01** [comment]
@singh264,  

The error captured in OpenJ9 has nothing to do with Verifier (as it should end up with `VerifiyError`(runtime) or `ClassFormatError` (static/loading)) as the exception `NumberFormatException` comes from the application level (I don't think the string passed in `Double` will be checked by the Verifier)

You'd better check the related java code in the application to see where/why `IllegalAccessError` was triggered in Hotspot or whether there is any access restrictions set in the application in which case we are unaware of in OpenJ9.

**Comment by singh264** [comment]
> The detail indicates that "any error detected during resolution must be thrown at a point in the program", which is reflected in openj9 behaviour as it throws the NumberFormatException at bytecode 5, ~and it seems like hotspot throws the IllegalAccessError at bytecode 11~.

I made an error in my previous comment. Hotspot (RI) does not throw the `IllegalAccessError` at `bytecode 11`, instead it seems to throw the `IllegalAccessError` while resolving the constant pool (CP) entry for the `TestReplacedNodesOSR$MyException` class. It seems to employ the `eager` linkage strategy detailed in the [jvm specification](https://github.com/eclipse-openj9/openj9/issues/19015#issuecomment-1981892753), and it throws the `IllegalAccessError` while resolving the CP entry for the exception class, instead of throwing it at `bytecode 11`, which is the start of the `catch` clause and where the symbolic reference for the `TestReplacedNodesOSR$MyException` class is encountered for the first time in the program.

Openj9 throws the `NumberFormatException` at `bytecode 5`. It does not throw an `IllegalAccessError` because it should not be thrown until `bytecode 11` is reached. If we remove `new Double("Vt-U")` at `bytecode 5`, then openj9 should also throw the `IllegalAccessError`. This matches the behaviour defined in the jvm specification: "any error detected during resolution must be thrown at a point in the program that (directly or indirectly) uses a symbolic reference to the class or interface"

> You'd better check the related java code in the application to see where/why IllegalAccessError was triggered in Hotspot or whether there is any access restrictions set in the application in which case we are unaware of in OpenJ9.

I believe that the RI throws the error while resolving the constant pool entry for the `TestReplacedNodesOSR$MyException` class. Currently, I see `(Unknown Source)` in the exception. I have requested @TemporaryRepos for access to the test source code and compilation instructions to confirm where in the source code the error is thrown with the RI, and to verify if openj9 throws `IllegalAccessError` when `new Double("Vt-U")` is removed from the test. I am unable to create and compile such a [test](https://github.com/eclipse-openj9/openj9/issues/19015#issue-2153438460) because it seems like the bytecodes in the class files provided were modified after compilation.

**Comment by TemporaryRepos** [comment]
I am sorry that I cannot provide the source code of test case, because this test case is generated by me using the bytecode analysis tool Soot. We are modifying the code of the intermediate language Jimple, if you think it is necessary, we can provide the relevant jimple code. @singh264

**Comment by singh264** [comment]
@TemporaryRepos I would like the adjusted class files without `new Double("Vt-U")` at `bytecode 5`, and the relevant jimple code with instructions.

**Comment by TemporaryRepos** [comment]
If we remove new Double("Vt-U"), nothing will be reported.
[202403122231.zip](https://github.com/eclipse-openj9/openj9/files/14574275/202403122231.zip)

**Comment by singh264** [comment]
This issue can be closed as per https://github.com/eclipse-openj9/openj9/issues/19015#issuecomment-2047927594.
