### ISSUE TITLE
Program Execution on openj9-openjdk-jdk8 Results in Incorrect Output

### ISSUE THREAD

**Issue by Qeryu** [eclipse-openj9/openj9#19026]
Java -version output
--------------------

```bash
openjdk version "1.8.0_402-internal"
OpenJDK Runtime Environment (build 1.8.0_402-internal-user_2024_01_31_16_41-b00)
Eclipse OpenJ9 VM (build master-40a4d38b2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240131_000000 (JIT enabled, AOT enabled)
OpenJ9   - 40a4d38b2
OMR      - a74c0935b
JCL      - 33602fcbe7 based on jdk8u402-b06)

javac 1.8.0_402-internal
```

Summary of problem
------------------

When running the following testcase with openj9-openjdk-jdk8, there is an incorrect output result.

```java
class Test {
  final int a = 400;
  long n;

  void o(int d) {
    byte by = 8;
    long[] e = new long[a];
    for (int f = 0; f < e.length; f++) {
      e[f] = 25319043172877155L;
    }
    e[d >> 1] = d;
    d = by;
    for (int f = 0; f < e.length; f++) {
      n += e[f];
    }
  }

  void mainTest(int iter) {
    for (int h = 5; h < 500; h++) {
      int i = 1;
      while (++i < 100)
        o(i);
    }
    System.out.println(n);
  }

  public static void main(String[] strArr) {
    Test j = new Test();
    for (int g = 0; g < 10; g++)
      j.mainTest(g);
  }
}
```

Other JDKs and openj9-openjdk-jdk8 with `-Xint` enabled can all output normal results.

```bash
$ other-jdk/.../java Test
6283880024099050049
-5878984025511451518
404895998587598531
6688776022686648580
-5474088026923852987
809791997175197062
7093672021274247111
-5069192028336254456
1214687995762795593
7498568019861845642

$ openj9-openjdk-jdk8/.../java -Xint Test
6283880024099050049
-5878984025511451518
404895998587598531
6688776022686648580
-5474088026923852987
809791997175197062
7093672021274247111
-5069192028336254456
1214687995762795593
7498568019861845642
```

I attempted to locate the relevant optimization and observed the following phenomena.

```bash
# wrong answer
$ openj9-openjdk-jdk8/.../java '-Xjit:{Test.o*}(optLevel=noOpt)' Test 
6283880024099050049
-5878984025511451518
404895998586361526
6688776022684174570
-5474088026927564002
809791997170249042
7093672021268062086
-5069192028342439481
1214687995756610568
7498568019855660617

# right answer
$ openj9-openjdk-jdk8/.../java -Xint Test 
$ openj9-openjdk-jdk8/.../java '-Xjit:{Test.b*}(optLevel=veryhot)' Test 
```

**Comment by hzongaro** [comment]
@Qeryu, thank you for reporting this problem.  I have not yet been able to reproduce the incorrect output.

May I ask you to try running with each of the following options, so we can try to narrow things down?  `-Xjit:limit={Test.mainTest*}` and `-Xjit:limit={Test.o*}`

**Comment by Qeryu** [comment]
It seems like this issue no longer occurs on the new version of OpenJ9. I was testing with a JDK compiled based on the commit master-40a4d38b2. I'm very sorry that I didn't test it with the latest OpenJ9 before reporting. Thank you for your reminder; I will re-examine other issues I've reported recently. @hzongaro

**Comment by hzongaro** [comment]
> I'm very sorry that I didn't test it with the latest OpenJ9 before reporting.

No worries. I wasn't able to reproduce it with a 0.41 or 0.42 build either.  Some problems can be highly intermittent, so if you see the failure re-occur, please reopen the issue.

> I will re-examine other issues I've reported recently.

I have been able to reproduce the others.
