### ISSUE TITLE
jdknext fails to compile on Windows

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19049]
Since https://openj9-jenkins.osuosl.org/job/Pipeline-OpenJDK-Acceptance/662/ we've been getting this error. I ran an [internal build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/20946/) and it worked. @keithc-ca Any ideas?

Every build ran on [win2019-x64-2a](https://openj9-jenkins.osuosl.org/computer/win2019-x64-2a) so it could be a issue with this machine, or even all the openj9 machines for compiling jdknext. The jdk22 builds work [on this machine](https://openj9-jenkins.osuosl.org/job/Build_JDK22_x86-64_windows_Nightly/25/).

https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_OpenJDK/624 - [win2019-x64-2a](https://openj9-jenkins.osuosl.org/computer/win2019-x64-2a)
```
11:51:39  /cygdrive/f/users/jenkins/workspace/build_jdknext_x86-64_windows_openjdk/build/windows-x86_64-server-release/tools/lib: line 2: /nologo: No such file or directory
11:51:39  make[6]: *** [runtime/omr/third_party/pugixml-1.5/CMakeFiles/pugixml.dir/build.make:99: runtime/lib/pugixml.lib] Error 127
11:51:39  make[5]: *** [CMakeFiles/Makefile2:4173: runtime/omr/third_party/pugixml-1.5/CMakeFiles/pugixml.dir/all] Error 2
```

**Comment by keithc-ca** [comment]
The way static libraries are created changed in https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/5f42c0783449722cc27e34ba4c131aa18d2775d8: `AR` is now empty so trying to run `$(AR) /nologo ...` looks like we want `/nologo ...` which isn't likely to work.

**Comment by pshipton** [comment]
Now there is another problem.
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_OpenJDK/626
```
14:00:23  	cmd /C ""cl" /Zs /showIncludes  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -I"crypto" -I"include" -I"providers/implementations/include" -I"providers/common/include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"C:/Program Files/Common Files/SSL\"" -D"ENGINESDIR=\"C:/Program Files/OpenSSL/lib/engines-3\"" -D"MODULESDIR=\"C:/Program Files/OpenSSL/lib/ossl-modules\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG"   -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 "ssl/record/tls_pad.c" > ssl/record/libcommon-lib-tls_pad.d 2>&1"
14:00:23  	"lib" /nologo /out:providers/libcommon.lib @F:\temp\nmEDA9.tmp
14:00:23  	IF EXIST .manifest DEL /F /Q .manifest
14:00:23  	IF EXIST libcrypto-3-x64.dll DEL /F /Q libcrypto-3-x64.dll
14:00:23  	cmd /C ""link" /nologo /debug /dll  /nologo /debug @F:\temp\nmEE36.tmp /implib:libcrypto.lib || (DEL /Q libcrypto-3-x64.* libcrypto.lib & EXIT 1)"
14:00:23  LINK : fatal error LNK1104: cannot open file 'ws2_32.lib'
14:00:23  Could Not Find F:\users\jenkins\workspace\build_jdknext_x86-64_windows_openjdk\openssl\libcrypto-3-x64.*
14:00:23  NMAKE : fatal error U1077: 'cmd' : return code '0x1'
```

**Comment by keithc-ca** [comment]
Perhaps I should have built OpenSSL in my earlier testing... :-(

I have a build underway (with OpenSSL this time) based on https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/751 which seems to be working.

**Comment by keithc-ca** [comment]
Closing: all was well in the last acceptance build (https://openj9-jenkins.osuosl.org/job/Build_JDKnext_x86-64_windows_OpenJDK/647).
