### ISSUE TITLE
p/zlinux JVMJ9VM007E Command-line option unrecognised: -Xgcpolicy:metronome

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19115]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_0/747 - [rh7-390-4](https://openj9-jenkins.osuosl.org/computer/rh7-390-4)
04:44:44  	jsr335tests_SE80_6 
04:44:44  	cmdLineTester_GCRegressionTests_Mode301_0 
04:44:44  	cmdLineTester_GCCheckMetronome_0 
04:44:44  	J9vmTest_1 

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_s390x_linux_Nightly_testList_1/747/ - [rh8-390-1](https://openj9-jenkins.osuosl.org/computer/rh8-390-1)
04:52:02  	J9vmTest_2 

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/746
04:05:31  	cmdLineTester_verbosetest_4 
04:05:31  	cmdLineTester_jvmtitests_hcr_nongold_SE80_6 
04:05:31  	cmdLineTester_jvmtitests_extended_nongold_4 
04:05:31  	cmdLineTester_jvmtitests_extended_nongold_5 
04:05:31  	cmdLineTester_decompilationTests_nongold_1 
04:05:31  	ThreadRegressionTests_2 
04:05:31  	j9vmClassUnloading_1 
04:05:31  	gcNotificationTest_Metronome_1 
04:05:31  	threadMXBeanTestSuite1_2 
04:05:31  	threadMXBeanTestSuite1_6 
04:05:31  	threadMXBeanTestSuite2_2 
04:05:31  	threadMXBeanTimedParkTest_2 
04:05:31  	threadMXBeanTimersTest_2 
04:05:31  	jniOnLoadExceptions_3 
04:05:31  	testvmcheck_3 

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/746/
04:56:23  	cmdLineTester_jvmtitests_nongold_4 
04:56:23  	cmdLineTester_jvmtitests_nongold_5 
04:56:23  	cmdLineTester_jvmtitests_hcr_nongold_SE80_7 
04:56:23  	cmdLineTester_decompilationTests_nongold_2 
04:56:23  	cmdLineTester_verbosetest_5 
04:56:23  	gcNotificationTest_Metronome_0 
04:56:23  	threadMXBeanTestSuite1_1 
04:56:23  	threadMXBeanTestSuite1_5 
04:56:23  	threadMXBeanTestSuite2_1 
04:56:23  	threadMXBeanTimedParkTest_1 
04:56:23  	threadMXBeanTimersTest_1 
04:56:23  	jniOnLoadExceptions_2 
04:56:23  	testvmcheck_2 
04:56:23  	ThreadRegressionTests_3 
04:56:23  	j9vmClassUnloading_2 

jdk8 and 11 don't run plinux builds
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly/742/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly/741/

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly/651/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_ppc64le_linux_Nightly/650/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_s390x_linux_Nightly/682/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly/680/

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_ppc64le_linux_Nightly/176/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_ppc64le_linux_Nightly/178/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.functional_s390x_linux_Nightly/179/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly/181/

https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_ppc64le_linux_Nightly/24/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.functional_ppc64le_linux_Nightly/24/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_sanity.functional_s390x_linux_Nightly/24/
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.functional_s390x_linux_Nightly/24/

Changes
https://github.com/eclipse-openj9/openj9/compare/ae0c76e4fd...e77cdfc1aec

**Comment by pshipton** [comment]
@dmitripivkine any ideas what caused this? None of the changes seem related.

**Comment by dmitripivkine** [comment]
We never support Metronome on zLinux (supported on AIX and xLinux only with limitation for CRIU support).
I guess `-Xgcpolicy:metronome` option was applied to wrong platforms somehow.

**Comment by pshipton** [comment]
@llxia pls take a look

**Comment by pshipton** [comment]
https://github.com/adoptium/aqa-tests/compare/2514b433b...356654960a

https://github.com/adoptium/TKG/compare/33887889b5...99b23a1ea35

**Comment by llxia** [comment]
re https://github.com/eclipse-openj9/openj9/issues/19115#issuecomment-1988909240, I agree. The option was skipped before. I will revert the change.

failed: [link](https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/738/consoleFull)
```
02:40:29.022  Testing: Odd memory parameters are accepted
02:40:30.949  Test start time: 2024/03/09 06:15:00 Coordinated Universal Time
02:40:30.949  Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java"  -Xgcpolicy:metronome -Xnocompressedrefs  -Xint -XXgc:allocationContextCount=1 -Xmx4500123 -Xms4500123 NON_EXISTENT_CLASS_TO_TEST_BOOTSTRAP
02:40:30.949  Time spent starting: 252 milliseconds
02:40:30.949  Time spent executing: 299 milliseconds
02:40:30.949  Test result: FAILED
02:40:30.949  Output from test:
02:40:30.949   [ERR] JVMJ9VM007E Command-line option unrecognised: -Xgcpolicy:metronome
02:40:30.949   [ERR] Error: Could not create the Java Virtual Machine.
02:40:30.949   [ERR] Error: A fatal exception has occurred. Program will exit.
02:40:30.949  >> Success condition was not found: [Output match: NON_EXISTENT_CLASS_TO_TEST_BOOTSTRAP]
02:40:30.949  >> Failure condition was not found: [Output match: JVMJ9GC019E]
```

passed: [link](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_s390x_linux/693/artifact/Test_openjdk11_j9_sanity.functional_s390x_linux_testList_1/619/aqa-tests/TKG/output_17095983372969/Test_openjdk11_j9_sanity.functional_s390x_linux_testList_1.tap/*view*/)

```
ok 31 - cmdLineTester_GCRegressionTests_Mode301_0 # skip
  ---
    duration_ms: 10
```
