### ISSUE TITLE
SmokeTests compilation failed and block other tests

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19122]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-openj9_SmokeTests/519/console):
```
19:24:32  openjdk version "1.8.0_412-beta"
19:24:32  IBM Semeru Runtime Open Edition (build 1.8.0_412-beta-202403112237-b05)
19:24:32  Eclipse OpenJ9 VM (build master-45ebb3194, JRE 1.8.0 Linux aarch64-64-Bit Compressed References 20240311_863 (JIT enabled, AOT enabled)
19:24:32  OpenJ9   - 45ebb3194
19:24:32  OMR      - 66252485a
19:24:32  JCL      - 16aa7c249 based on jdk8u412-b05)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=%2Ftest%2Ffunctional&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-openj9%2F863%2Fibm-semeru-open-jdk_aarch64_linux_JDK8U_2024-03-11-22-30.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&JDK_VERSION=8&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Ftemurin-build&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=ibm&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&TRSS_URL=&BUILD_LIST=functional%2FbuildAndPackage&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=1&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
19:25:26      [javac] /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9_SmokeTests/aqa-tests/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java:310: error: cannot find symbol
19:25:26      [javac]             assertNotEquals(value.replaceAll("[^0-9]", "").length(), 0,
19:25:26      [javac]             ^
19:25:26      [javac]   symbol:   method assertNotEquals(int,int,String)
19:25:26      [javac]   location: class CorrettoPropertiesChecks
19:25:26      [javac] /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9_SmokeTests/aqa-tests/functional/buildAndPackage/src/net/adoptium/test/VerifyCACertsTest.java:79: error: cannot find symbol
19:25:26      [javac]             assertEquals(ks.size(), EXPECTED_COUNT, "Failed to match CA certs number.");
19:25:26      [javac]             ^
19:25:26      [javac]   symbol:   method assertEquals(int,int,String)
19:25:26      [javac]   location: class VerifyCACertsTest
19:25:26      [javac] 87 errors
19:25:26  
19:25:26  BUILD FAILED
19:25:26  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9_SmokeTests/aqa-tests/TKG/scripts/build_test.xml:95: The following error occurred while executing this line:
19:25:26  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9_SmokeTests/aqa-tests/functional/buildAndPackage/build.xml:69: The following error occurred while executing this line:
19:25:26  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9_SmokeTests/aqa-tests/functional/buildAndPackage/build.xml:44: Compile failed; see the compiler error output for details.
19:25:26  
19:25:26  Total time: 2 seconds
19:25:26  1
19:25:26  make[1]: *** [compile.mk:45: compile] Error 1
19:25:26  make[1]: Leaving directory '/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9_SmokeTests/aqa-tests/TKG'
19:25:26  make: *** [makefile:78: compile] Error 2
```

Also occurred at [jdk17u-linux-aarch64](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-linux-aarch64-openj9-IBM_SmokeTests/460/console) [jdk21u-linux-aarch64](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-aarch64-openj9-IBM_SmokeTests/100/console)

**Comment by pshipton** [comment]
@llxia

**Comment by JasonFengJ9** [comment]
@LongyuZhang any insights?

**Comment by pshipton** [comment]
I see this
```
19:24:50  ERROR: sha checksum error.
19:24:50  --> file downloaded to /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-openj9_SmokeTests/../../testDependency/lib/maven-jar-plugin.jar
19:24:50  Expected sha is: 21829ae5feec95ae6fec425f2d85bbbfe49880c4,
19:24:50  Actual sha is  : e544ce2ca812fd7e44d39e6522933e0562f66261.
```

**Comment by LongyuZhang** [comment]
The `maven-jar-plugin.jar` dependency has been removed already. 
Since the Mockit test is still WIP, I think we can remove the dependency for `mockito_core` and `byte_buddy` jars temporarily to unblock the build first. FYI @sophiaxu0424

**Comment by JasonFengJ9** [comment]
It happens again though only in [JDK11 linux-aarch64](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/417/console)
```
22:05:07      [javac] /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/aqa-tests/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java:310: error: cannot find symbol
22:05:07      [javac]             assertNotEquals(value.replaceAll("[^0-9]", "").length(), 0,
22:05:07      [javac]             ^
22:05:07      [javac]   symbol:   method assertNotEquals(int,int,String)
22:05:07      [javac]   location: class CorrettoPropertiesChecks
22:05:07      [javac] /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/aqa-tests/functional/buildAndPackage/src/net/adoptium/test/VerifyCACertsTest.java:79: error: cannot find symbol
22:05:07      [javac]             assertEquals(ks.size(), EXPECTED_COUNT, "Failed to match CA certs number.");
22:05:07      [javac]             ^
22:05:07      [javac]   symbol:   method assertEquals(int,int,String)
22:05:07      [javac]   location: class VerifyCACertsTest
22:05:07      [javac] 87 errors
22:05:07  
22:05:07  BUILD FAILED
22:05:07  /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/aqa-tests/TKG/scripts/build_test.xml:95: The following error occurred while executing this line:
22:05:07  /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/aqa-tests/functional/buildAndPackage/build.xml:69: The following error occurred while executing this line:
22:05:07  /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-IBM_SmokeTests/aqa-tests/functional/buildAndPackage/build.xml:44: Compile failed; see the compiler error output for details.
22:05:07  
22:05:07  Total time: 3 seconds
```

**Comment by pshipton** [comment]
@llxia any ideas why it can't find testng?

**Comment by llxia** [comment]
@LongyuZhang could you fix [somke test build.xml](https://github.com/adoptium/temurin-build/blob/master/test/functional/buildAndPackage/build.xml) by adding `getDependentLibs` call. 
See example at 
https://github.com/eclipse-openj9/openj9/blob/417c02fabb04f00d015dfbb1189b9d2ec61c2141/test/functional/SharedCPEntryInvokerTests/build.xml#L36
https://github.com/eclipse-openj9/openj9/blob/417c02fabb04f00d015dfbb1189b9d2ec61c2141/test/functional/SharedCPEntryInvokerTests/build.xml#L44

**Comment by AdamBrousseau** [comment]
>Is [ubu22-aarch64-5.svl.ibm.com](https://hyc-runtimes-jenkins.swg-devops.com/computer/ubu22-aarch64-5.svl.ibm.com) a new machine? Or do we have some cleanup script that removes the pre-staged jar on the machines?

Not a new machine. I don't believe the cleanup job touches that folder.
```
jenkins@ubu22-aarch64-5:~$ ll testDependency/lib/
total 208020
drwxrwxrwx 3 jenkins jenkins     4096 Mar 19 18:58 ./
drwxrwxrwx 3 jenkins jenkins     4096 Dec  7 00:38 ../
-rw-rw-r-- 1 jenkins jenkins   265176 Dec  7 00:38 asm-all.jar
-rw-rw-r-- 1 jenkins jenkins   121792 Dec  7 00:39 asm.jar
-rw-rw-r-- 1 jenkins jenkins   485286 Dec  7 00:38 asmtools.jar
-rw-rw-r-- 1 jenkins jenkins       95 Dec  7 00:38 asmtools.jar.sha256sum.txt
-rw-rw-r-- 1 jenkins jenkins  8372360 Feb  2 02:41 bcprov-jdk18on.jar
-rw-rw-r-- 1 jenkins jenkins  4212649 Mar 13 04:44 byte-buddy.jar
-rw-rw-r-- 1 jenkins jenkins    41123 Dec  7 00:38 commons-cli.jar
-rw-rw-r-- 1 jenkins jenkins    52543 Dec  7 00:38 commons-exec.jar
drwxrwxr-x 3 jenkins jenkins     4096 Mar 14 04:26 configuration/
-rw-rw-r-- 1 jenkins jenkins    45024 Feb  2 02:41 hamcrest-core.jar
-rw-rw-r-- 1 jenkins jenkins   750581 Dec  7 00:39 javassist.jar
-rw-rw-r-- 1 jenkins jenkins   125632 Dec  7 00:38 jaxb-api.jar
-rw-rw-r-- 1 jenkins jenkins    63504 Dec  7 00:38 jcommander.jar
-rw-rw-r-- 1 jenkins jenkins 56791208 Dec  7 00:38 jcstress-tests-all-20220908.jar
-rw-rw-r-- 1 jenkins jenkins 70421379 Mar 13 04:44 jcstress-tests-all-20240222.jar
-rw-rw-r-- 1 jenkins jenkins    23931 Dec  7 00:39 json-simple.jar
-rw-rw-r-- 1 jenkins jenkins  7202109 Dec  7 00:38 jtreg_5_1_b01.tar.gz
-rw-rw-r-- 1 jenkins jenkins      138 Dec  7 00:38 jtreg_5_1_b01.tar.gz.sha256sum.txt
-rw-rw-r-- 1 jenkins jenkins  8313563 Dec  7 00:38 jtreg_6_1.tar.gz
-rw-rw-r-- 1 jenkins jenkins      135 Dec  7 00:38 jtreg_6_1.tar.gz.sha256sum.txt
-rw-rw-r-- 1 jenkins jenkins  9308142 Dec  7 00:38 jtreg_7_3_1_1.tar.gz
-rw-rw-r-- 1 jenkins jenkins      139 Dec  7 00:38 jtreg_7_3_1_1.tar.gz.sha256sum.txt
-rw-rw-r-- 1 jenkins jenkins   253160 Dec  7 00:39 junit4.jar
-rw-rw-r-- 1 jenkins jenkins 43056592 Dec  7 00:38 jython-standalone.jar
-rw-rw-r-- 1 jenkins jenkins   701412 Mar 13 04:44 mockito-core.jar
-rw-rw-r-- 1 jenkins jenkins     2348 Dec  7 00:38 openj9jtregtimeouthandler.jar
-rw-rw-r-- 1 jenkins jenkins       96 Dec  7 00:38 openj9jtregtimeouthandler.jar.sha256sum.txt
-rw-rw-r-- 1 jenkins jenkins  1515862 Dec  7 00:39 org.eclipse.osgi-3.16.100.jar
-rw-rw-r-- 1 jenkins jenkins   809515 Mar 19 18:58 testng.jar
```

**Comment by LongyuZhang** [comment]
Re: https://github.com/eclipse-openj9/openj9/issues/19122#issuecomment-2007360597
PR https://github.com/adoptium/temurin-build/pull/3719 has been created to add `getDependentLibs` for smoke tests.

**Comment by llxia** [comment]
re https://github.com/eclipse-openj9/openj9/issues/19122#issuecomment-2007956657, hmm, [recent run ](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_0/458/console)on the same machine seems fine. Pre-staged jars were checked.
```
19:08:36  dependencyList is set to all
19:08:36  --------------------------------------------
19:08:36  Starting download third party dependent jars
19:08:36  --------------------------------------------
19:08:36  downloading dependent third party jars to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_0/../../testDependency/lib
19:08:36  /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_0/../../testDependency/lib/jcstress-tests-all-20240222.jar exists with correct hash, not downloading
19:08:36  /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_0/../../testDependency/lib/javassist.jar exists with correct hash, not downloading
19:08:36  /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_0/../../testDependency/lib/junit4.jar exists with correct hash, not downloading
...
```

**Comment by llxia** [comment]
PR https://github.com/adoptium/temurin-build/pull/3719 is merged. I will close this issue. Please reopen if the problem occurs again.

**Comment by llxia** [comment]
@LongyuZhang could you also add jcommander? 

[Recent failure](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-linux-s390x-openj9-IBM_SmokeTests/494/consoleFull)

```20:55:00  TESTING:
20:55:01  Error: Unable to initialize main class org.testng.TestNG
20:55:01  Caused by: java.lang.NoClassDefFoundError: com.beust.jcommander.ParameterException
```

**Comment by llxia** [comment]
Also, the smoke test build has a different folder structure than regular test build. See `build-scripts/jobs/jdk17u` below:
```
/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-s390x-openj9-IBM_SmokeTests/../../testDependency/lib/jcommander.jar
```

To leverage pre-stage libs, LIB_DIR cannot be a relative path in the smoke test builds.

**Comment by LongyuZhang** [comment]
PRs for updating SmokeTests LIB_DIR to the same as other tests to utilize pre-staged dependencies ([link](https://github.com/adoptium/aqa-tests/pull/5173)) and adding jcommander into dependencies ([link](https://github.com/adoptium/temurin-build/pull/3723)) have been merged.

**Comment by pshipton** [comment]
Can we put the updates in v1.0.1-release pls.

**Comment by LongyuZhang** [comment]
Cherry pick to v1.0.1-release created (PR https://github.com/adoptium/aqa-tests/pull/5178)

**Comment by llxia** [comment]
All changes are delivered. Close this issue.
