### ISSUE TITLE
Windows system testing, sha mismatch downloading dependent third party jars

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19123]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_x86-64_windows_Nightly_testList_0/678 - [win2019x64-openj9-3a](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-3a)
```
04:01:30  getDependentLibs:
04:01:30       [exec] --------------------------------------------
04:01:30       [exec] path is set to C:/Users/****/testDependency/lib
04:01:30       [exec] task is set to default
04:01:30       [exec] dependencyList is set to jcstress
04:01:30       [exec] --------------------------------------------
04:01:30       [exec] Starting download third party dependent jars
04:01:30       [exec] --------------------------------------------
04:01:30       [exec] downloading dependent third party jars to C:/Users/****/testDependency/lib
04:01:30       [exec] downloading https://builds.shipilev.net/jcstress/jcstress-tests-all-20220908.jar
04:01:31       [exec] --> file downloaded to C:/Users/****/testDependency/lib/jcstress-tests-all-20220908.jar
04:01:31       [exec] Expected sha is: 8cf348be49b8af939a3ce03216e3df53aa0f9ef2,
04:01:31       [exec] Actual sha is  : e461d072a6ba8f0082d6f187eba7f053343529c6.
04:01:31       [exec] ERROR: sha checksum error.
04:01:31       [exec] Please delete C:/Users/****/testDependency/lib/jcstress-tests-all-20220908.jar and rerun the program!
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_x86-64_windows_Nightly_testList_2/677 - [win2019x64-openj9-3a](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-3a)

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly_testList_0/677/ - [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly_testList_1/677/ - [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)

https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.system_x86-64_windows_Nightly_testList_2/676/ - [win2019x64-openj9-5](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-5)

**Comment by pshipton** [comment]
@llxia pls take a look, this somewhat blocks the system tests from running on Windows.

**Comment by pshipton** [comment]
This job passed, but looking at the details it still failed to download but proceeded anyway.
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_x86-64_windows_Nightly_testList_1/678/ - [win2019x64-openj9-2](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-2)

```
03:52:57  Starting download third party dependent jars
03:52:57  --------------------------------------------
03:52:57  downloading dependent third party jars to C:/Users/jenkins/workspace/Test_openjdk17_j9_sanity.system_x86-64_windows_Nightly_testList_1/../../testDependency/lib
03:52:57  downloading https://ci.adoptium.net/job/test.getDependency/lastSuccessfulBuild/artifact//mockito-core.jar
03:52:57  ERROR: sha checksum error.
03:52:57  --> file downloaded to C:/Users/jenkins/workspace/Test_openjdk17_j9_sanity.system_x86-64_windows_Nightly_testList_1/../../testDependency/lib/mockito-core.jar
03:52:57  Expected sha is: faa88b96db3aeb96a93e83dec7491345bfbfc414,
03:52:57  Actual sha is  : b1e8904d974e4365b713bda0a70bb43f990820fd.
03:52:57  Please delete C:/Users/jenkins/workspace/Test_openjdk17_j9_sanity.system_x86-64_windows_Nightly_testList_1/../../testDependency/lib/mockito-core.jar and rerun the program!
```

**Comment by pshipton** [comment]
This may be related.
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/129/
```
19:19:52  build-java:
19:19:52      [javac] Compiling 58 source files to /Users/****/workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/aqa-tests/system/STF/stf.core/bin
19:19:52      [javac] error: error reading /Users/****/workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/aqa-tests/systemtest_prereqs/junit/junit.jar; zip file is empty
19:19:52      [javac] error: error reading /Users/****/workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/aqa-tests/systemtest_prereqs/junit/hamcrest-core.jar; zip file is empty
19:19:52      [javac] error: error reading /Users/****/workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/aqa-tests/systemtest_prereqs/log4j/log4j-api.jar; zip file is empty
19:19:52      [javac] error: error reading /Users/****/workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/aqa-tests/systemtest_prereqs/log4j/log4j-core.jar; zip file is empty
```

**Comment by LongyuZhang** [comment]
With https://github.com/adoptium/TKG/pull/515, the hyc test.getDependency rebuild has passed; Openj9-jenkins [test.getDependency](https://openj9-jenkins.osuosl.org/job/test.getDependency/) can rebuild too, but I don't have permission to run it.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/test.getDependency/1035/

**Comment by pshipton** [comment]
Closing assuming fixed, we'll find out tonight.

**Comment by pshipton** [comment]
@LongyuZhang any idea what would cause https://github.com/eclipse-openj9/openj9/issues/19123#issuecomment-1991782982?

It happened again on the same machine. I looked at the machine and `workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1` doesn't exist so something must be going wrong getting these files. 
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/130/

**Comment by pshipton** [comment]
I found `testDependency/lib` but the only matching file in there is hamcrest-core.jar and it looks fine.
```
-rw-r--r--  1 jenkins  staff     45024 Feb  2 05:37 hamcrest-core.jar
```

**Comment by LongyuZhang** [comment]
Possibly related to Mockit.jar SHA error, need to update the SHA for it.
```18:45:56  /Users/jenkins/workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/../../testDependency/lib/commons-cli.jar exists with correct hash, not downloading
18:45:56  downloading https://ci.adoptium.net/job/test.getDependency/lastSuccessfulBuild/artifact//mockito-core.jar
18:45:56  ERROR: sha checksum error.
18:45:56  --> file downloaded to /Users/jenkins/workspace/Test_openjdk21_j9_extended.system_x86-64_mac_Nightly_testList_1/../../testDependency/lib/mockito-core.jar
18:45:56  Expected sha is: faa88b96db3aeb96a93e83dec7491345bfbfc414,
18:45:56  Actual sha is  : c08244da11f3346dae807da46f37cfcb2514fa05.
```

**Comment by LongyuZhang** [comment]
https://github.com/adoptium/TKG/pull/518 should fix this issue.
