### ISSUE TITLE
How to disable coredumps in Semeru JVM ?

### ISSUE THREAD

**Issue by mkarrahcl** [eclipse-openj9/openj9#19162]
We use Semeru JVM 8 and JVM 17 in our environments.

1 [C:\fixes] \OpenJDK17\bin\java -version
openjdk version "17.0.9" 2023-10-17
IBM Semeru Runtime Open Edition 17.0.9.0 (build 17.0.9+9)
Eclipse OpenJ9 VM 17.0.9.0 (build openj9-0.41.0, JRE 17 Windows 10 amd64-64-Bit Compressed References 20231017_568 (JIT enabled, AOT enabled)
OpenJ9   - 461bf3c70
OMR      - 5eee6ad9d
JCL      - 3699725139c based on jdk-17.0.9+9)

1 [C:\fixes] \OpenJDK17\bin\java -X

    -Xbatch           disable background compilation
    -Xbootclasspath/a:<directories and zip/jar files separated by ;>
                      append to end of bootstrap class path
    -Xcheck:jni       perform additional checks for JNI functions
    -Xcomp            forces compilation of methods on first invocation
    -Xdebug           does nothing. Provided for backward compatibility.
    -Xdiag            show additional diagnostic messages
    -Xfuture          enable strictest checks, anticipating future default.
                      This option is deprecated and may be removed in a
                      future release.
    -Xint             interpreted mode execution only
    -Xinternalversion
                      displays more detailed JVM version information than the
                      -version option
    -Xlog:<opts>      Configure or enable logging with the Java Virtual
                      Machine (JVM) unified logging framework. Use -Xlog:help
                      for details.
    -Xloggc:<file>    log GC status to a file with time stamps.
                      This option is deprecated and may be removed in a
                      future release. It is replaced by -Xlog:gc:<file>.
    -Xmixed           mixed mode execution (default)
    -Xmn<size>        sets the initial and maximum size (in bytes) of the heap
                      for the young generation (nursery)
    -Xms<size>        set initial Java heap size
    -Xmx<size>        set maximum Java heap size
    -Xnoclassgc       disable class garbage collection
    -Xrs              reduce use of OS signals by Java/VM (see documentation)
    -Xshare:auto      use shared class data if possible (default)
    -Xshare:off       do not attempt to use shared class data
    -Xshare:on        require using shared class data, otherwise fail.
                      This is a testing option and may lead to intermittent
                      failures. It should not be used in production environments.
    -XshowSettings    show all settings and continue
    -XshowSettings:all
                      show all settings and continue
    -XshowSettings:locale
                      show all locale related settings and continue
    -XshowSettings:properties
                      show all property settings and continue
    -XshowSettings:vm
                      show all vm related settings and continue
    -XshowSettings:system
                      (Linux Only) show host system or container
                      configuration and continue
    -Xss<size>        set java thread stack size
    -Xverify          sets the mode of the bytecode verifier
                      Note that option -Xverify:none is deprecated and
                      may be removed in a future release.

We thought we can disable all dump with -Xdump:none per Semeru documentation. However, when we looked for -X options as shown above that does not list -Xdump.

While googling we found that hotspot provided -XX:-CreateCoredumpOnCrash. Is there any equivalent option for Semeru JVM?

Any input or pointers on how to disable the Java core dumps will be appreciated.

**Comment by pshipton** [comment]
The -X output is as provided by OpenJDK. The `-Xdump:none` or `-Xdump:system:none` options are supported on Semeru as per https://eclipse.dev/openj9/docs/xdump/#noneoptions. There are some -XX: options supported for compatibility, see https://eclipse.dev/openj9/docs/cmdline_migration/, but not CreateCoredumpOnCrash.

**Comment by pshipton** [comment]
If you specify any `-X` option and the VM starts, the option is supported. If it's unrecognized the VM will fail to start.
For `-XX:` options this isn't true, unrecognized options are ignored by default, but `-XX:-IgnoreUnrecognizedXXColonOptions` changes that behavior.

**Comment by mkarrahcl** [comment]
Thanks Peter.
