### ISSUE TITLE
Build failure with aarch64 mac

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#19221]
Nightly build https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_mac_Nightly/541 failed with the following error:

```
[2024-03-26T00:23:14.403Z] /Users/jenkins/workspace/Build_JDK11_aarch64_mac_Nightly/openj9/runtime/compiler/ilgen/Walker.cpp:4718:15: error: 1118 enumeration values not handled in switch: 'FirstOMRMethod', 'FirstJ9Method', 'org_apache_harmony_luni_platform_OSMemory_putByte_JB_V'... [-Werror,-Wswitch]
[2024-03-26T00:23:14.403Z]       switch (recognizedMethod)
```

I see the same error with my local build.

The previous aarch64 mac build three days ago was successful.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_mac_Nightly/540
```
[2024-03-23T00:30:37.196Z] OpenJ9   - a3f25b1faf5
[2024-03-23T00:30:37.196Z] OMR      - cbfcf7d9444
[2024-03-23T00:30:37.196Z] JCL      - d4a1f436b3e based on jdk-11.0.23+7)
```

The latest aarch64 linux build is successful.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_linux_Nightly/653
```
[2024-03-26T00:42:53.857Z] OpenJ9   - f4a6293f443
[2024-03-26T00:42:53.857Z] OMR      - cbfcf7d9444
[2024-03-26T00:42:53.857Z] JCL      - d4a1f436b3e based on jdk-11.0.23+7)
```

The latest x86-64 mac build was a failure, but it was "Cannot contact mac10-x86-2".
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/781/

**Comment by knn-k** [comment]
Reverting PR #19087 seems to resolve the build failure.
OpenJ9 f4a6293f443 -> 1c38c8af0

**Comment by knn-k** [comment]
@jdmpapin FYI.

**Comment by knn-k** [comment]
https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/README.md says the target "all" contains x86-64_mac and aarch64_mac, but the jobs for mac platforms are not started.

**Comment by pshipton** [comment]
The target should contain those OSes but we've had issues with the available machines being able to run tests reliably due to network bandwidth at UNB and they were removed "temporarily". At it's worst, trying to run too much testing would cause jenkins to restart. An improvement was made for functional testing, but we're still waiting for system testing to be improved. PR builds don't usually run system testing. I think we can add the OSes back to `all` and we'll see how it goes.

**Comment by pshipton** [comment]
Created and merged https://github.com/eclipse-openj9/openj9/pull/19223

**Comment by pshipton** [comment]
xmac also fails to compile
```
05:26:09  /Users/jenkins/workspace/Build_JDK8_x86-64_mac_OMR/openj9/runtime/compiler/ilgen/Walker.cpp:4718:15: error: 1118 enumeration values not handled in switch: 'FirstOMRMethod', 'FirstJ9Method', 'org_apache_harmony_luni_platform_OSMemory_putByte_JB_V'... [-Werror,-Wswitch]
05:26:09        switch (recognizedMethod)
05:26:09                ^
05:26:09  /Users/jenkins/workspace/Build_JDK8_x86-64_mac_OMR/openj9/runtime/compiler/ilgen/Walker.cpp:4718:15: note: add missing switch cases
05:26:09        switch (recognizedMethod)
05:26:09                ^
```

**Comment by knn-k** [comment]
The latest nightly builds are successful.
https://openj9-jenkins.osuosl.org/job/Build_JDK11_aarch64_mac_Nightly/542/
https://openj9-jenkins.osuosl.org/job/Build_JDK11_x86-64_mac_Nightly/782/
