### ISSUE TITLE
ASSERTION FAILED MarkingDelegate.hpp:142 (uintptr_t)0x99669966 == clazz->eyecatcher

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19237]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_OMR_testList_0/48
jdk_lang_0
java/lang/ThreadLocal/MemoryLeak.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_OMR_testList_0/48/openjdk_test_output.tar.gz
```
10:54:16  14:41:53.824 0x268800    j9mm.107    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK21_ppc64le_linux_OMR/openj9/runtime/gc_glue_java/MarkingDelegate.hpp:142: ((false && ((uintptr_t)0x99669966 == clazz->eyecatcher)))
```

**Comment by dmitripivkine** [comment]
I will triage this

**Comment by dmitripivkine** [comment]
Taking this defect to GC queue. There is not clear what is going on.
There is Global GC triggered after Scavenger Blackout. Work packet has a number of links to Reverse Forwarding pointers. So, looks like by some reason Scavenger Blackout missed location to fix up. Searching for such unfixed alive object where Mark discovered pointers to RFPs.

**Comment by dmitripivkine** [comment]
Bad pointers (pointers to Reversed Forwarded Pointers - RFPs) discovered in the Work Packet in Global GC came from Virtual Thread java stack. I don't see handling for VT java stacks in Scavenger Backout, seems this is the missed bit.
If it is correct Scavenger Backout for Java 21+ is broken (however Backout is marginal operation doesn't happen often). 
@LinHu2016 Would you please check? We need to implementation ASAP.
@amicic @TobiAjila @pshipton FYI

**Comment by pshipton** [comment]
Tentatively adding to the jdk22 milestone, although we may decide we can GA jdk22 without it.

**Comment by pshipton** [comment]
Port to 0.45 https://github.com/eclipse-openj9/openj9/pull/19388
