### ISSUE TITLE
Recent JDK11 ojdk292 builds on Jenkins fail with unrecognized configuration option

### ISSUE THREAD

**Issue by ThanHenderson** [eclipse-openj9/openj9#19248]
The `ojdk292` platform suffix in Jenkins is used to enable OpenJDK MethodHandles for Java 8 and Java 11.

Recent JDK11 `ojdk292` builds on Jenkins fail with the following:

```configure: error: unrecognized options: --enable-openjdk-methodhandles```

Everything is fine for JDK8 `ojdk292` builds.

Here is an example: https://hyc-runtimes-jenkins.swg-devops.com/job/OpenJDK%20Method%20Handles/24/

**Comment by pshipton** [comment]
Seems https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/764 accidentally deleted `OPENJ9_CONFIGURE_OPENJDK_METHODHANDLES` from closed/autoconf/custom-hook.m4
@tajila

**Comment by tajila** [comment]
Ill add it back
