### ISSUE TITLE
It seems to be a problem that the while loop has not been optimized.

### ISSUE THREAD

**Issue by ASMFuzz** [eclipse-openj9/openj9#19240]
# Version

```
11.0.16+8   17.0.7
```

```
Openj9-jdk11   Openj9-jdk17
```

# Test case 1

```java
import java.beans.DefaultPersistenceDelegate;
import java.beans.PersistenceDelegate;
import java.beans.XMLEncoder;

public class test {

    static String msg = "(+E.Q~I:yZ";

    static String m_LibQopqrList_ = "J|v~(TcT&P";

    static String m_Separator = "um)n,O}-Vx";

    String getMessage(String msg) throws Exception {
        Object[] obs = { -2147483648, 0, 0 };
        while (obs != null) {
            try {
                obs = new Object[obs.length + obs.length / 3];
            } catch (OutOfMemoryError error) {
                obs = null;
            }
        }
        String ret = null;
        try {
            ret = new String(msg.getBytes());
        } catch (Exception e) {
            ret = null;
        }
        return ret;
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new test().getMessage(msg));
    }
}
```

![image-20240328211410225](https://raw.githubusercontent.com/AidPaike/article-images/main/typora/202403282114371.png)

# Openj9-jdk11 Output

```
Exception in thread "main" java.lang.NegativeArraySizeException: -1554416224
	at test.getMessage(test.java:18)
	at test.main(test.java:33)
```

# Openj9-jdk17 Output

```
Exception in thread "main" java.lang.NegativeArraySizeException: -1554416224
	at test.getMessage(test.java:18)
	at test.main(test.java:33)
```

# Expected Output

```
(+E.Q~I:yZ
```

# shell

openj9-jdk17

```
timeout -s9 60 /root/jvm/openj9-jdk17/openj9-openjdk-jdk17/build/linux-x86_64-server-release/jdk/bin/java -XX:+CompactStrings -Xnuma:none -XX:-HandleSIGABRT -Xjit:count=0 --add-opens=java.base/sun.nio.ch=ALL-UNNAMED test ——illegal-access=permit
```

openj9-jdk11

```
timeout -s9 60 /root/jvm/openj9-jdk11/openj9-jdk11_0723/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/bin/java -XX:+CompactStrings -Xnuma:none -XX:-HandleSIGABRT -Xjit:count=0 --add-opens=java.base/sun.nio.ch=ALL-UNNAMED test ——illegal-access=permit
```

# Description

When executing the test case, it was found that versions 11 and 17 of openj9 would report a `java.lang.NegativeArraySizeException` error. It is expected to directly output `(+E.Q~I:yZ`, mainly due to the calculation error caused by the previous infinite while loop. It seems that openj9 is not optimized.

Best wish:)

**Comment by BradleyWood** [comment]
I see the `NegativeArraySizeException` with ```-Xint``` and also in JIT when `optLevel >= hot`

**Comment by hzongaro** [comment]
It's not clear that there's any bug here.  I haven't examined what actually happens at run time, but I can imagine that if garbage collection manages to collect the array that's assigned to `obs` on every iteration of the loop &mdash; or the JIT compiler's optimizer manages to avoid allocating the unused array &mdash; it might well be able to execute the loop until the requested array size overflows the range for `int` values.  That would result in a `NegativeArraySizeException` without ever triggering the `OutOfMemoryError` that the test seems to expect.

**Comment by pshipton** [comment]
Set an -Xmx such as `-Xmx7g` or lower and the test case prints the expected value. Otherwise it depends on the default. Simply put, the OpenJ9 default for -Xmx is "25% of the available memory with a maximum of 25 GB".

**Comment by pshipton** [comment]
It may be interesting to get the value of MaxHeapSize from Hotspot, and the -verbose:sizes output from OpenJ9 on the machine where there is a difference.

Hotspot:
`java -XX:+PrintFlagsFinal -version | grep MaxHeapSize`

OpenJ9
`java -verbose:sizes -version`

**Comment by BradleyWood** [comment]
@hzongaro I misread the array allocation as `(obs.length + obs.length) / 3` instead of `obs.length + obs.length / 3` which perplexed me, so your comment makes sense to me now.

@pshipton Both OpenJ9 and Hotspot seem to set max heap size around 8 GB on my machine, with hotspot slightly larger.

I was able to reproduce `NegativeArraySizeException` in hotspot if the heap is more than 20gb.

**Comment by pshipton** [comment]
Seems OpenJ9 is better. It can allocate bigger objects when there is a smaller max heap size.
