### ISSUE TITLE
Support restore with -XX:CRaCRestoreFrom=PATH

### ISSUE THREAD

**Issue by singh264** [eclipse-openj9/openj9#19261]
The documentation about restoring a checkpoint image with `-XX:CRaCRestoreFrom=PATH` is at https://github.com/CRaC/docs.

**Comment by singh264** [comment]
@tajila I would like to address this issue.

**Comment by singh264** [comment]
It seems like the next step is to merge the implementation and test PRs, and backport the implementation to the jdks that support crac.

**Comment by pshipton** [comment]
Pls create a doc issue.

**Comment by tajila** [comment]
> @JasonFengJ9 Pls create a doc issue.

We havent publicly documented any of the CRaC commands, we've been approaching it piecemeal adding the necessary support for certain usecases.
