### ISSUE TITLE
IndexOf method of String file fails using Eclipse OpenJ9 VM 11.0.22.0

### ISSUE THREAD

**Issue by gpezzini** [eclipse-openj9/openj9#19334]
Java -version output
--------------------
openjdk version "11.0.22" 2024-01-16
IBM Semeru Runtime Open Edition 11.0.22.0 (build 11.0.22+7)
Eclipse OpenJ9 VM 11.0.22.0 (build openj9-0.43.0, JRE 11 Windows 11 amd64-64-Bit Compressed References 20240131_835 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 7876cac747 based on jdk-11.0.22+7)

Summary of problem
------------------

The attached simple class demonstrates that the 'indexOf' method fails after reading a string stored in an xml property file.

After execution with the above5ra indicated jsk the output is:
The string: Field1ç°^§|Field2  **does NOT** contains ç°^§|

**Attention**:
1) using JDK
openjdk version "11.0.20" 2023-07-18
IBM Semeru Runtime Open Edition 11.0.20.0 (build 11.0.20+8)
Eclipse OpenJ9 VM 11.0.20.0 (build openj9-0.40.0, JRE 11 Windows 11 amd64-64-Bit Compressed References 20230810_700 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - f53b132192 based on jdk-11.0.20+8)

and older jdk version, it works.

The output is:
The string: Field1ç°^§|Field2  **contains** ç°^§|

2) Also using jdk
openjdk version "17.0.10" 2024-01-16
IBM Semeru Runtime Open Edition 17.0.10.0 (build 17.0.10+7)
Eclipse OpenJ9 VM 17.0.10.0 (build openj9-0.43.0, JRE 17 Windows 11 amd64-64-Bit Compressed References 20240116_624 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 2aad089841f based on jdk-17.0.10+7)

The output is:
The string: Field1ç°^§|Field2  **contains** ç°^§|

So it works with 17 too

[TestIndexOf.java.txt](https://github.com/eclipse-openj9/openj9/files/15022265/TestIndexOf.java.txt)

**Comment by gpezzini** [comment]
I further simplified the example class
The same results described above can also be reproduced with the class attached here.
In practice, the problem can be reproduced even without switching between writing and reading an xml property file.
[TestIndexOf2.java.txt](https://github.com/eclipse-openj9/openj9/files/15022555/TestIndexOf2.java.txt)

**Comment by patric42** [comment]
It's even worse: any String longer than 1 character including anything needing UTF-8 multibyte encoding will not be found. So "ä!", "!ä" or "wörd" won't work. Yikes!

**Comment by gpezzini** [comment]
Thanks and pardon me: we are only talking about the .indexOf() method.
I personally haven't tested other methods like .split() or similar that require a scan of the string.
I hope the fix covers all the scenarios involved.

**Comment by pshipton** [comment]
The fix is released into the upcoming 0.44 release, expected by early May.

**Comment by pshipton** [comment]
An open source pre-release 0.44 Windows build with the fix.
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_windows_Release/134/OpenJ9-JDK11-x86-64_windows-20240419-025627.tar.gz

Let me know if you want a direct link to another platform.

The full builds:
https://openj9-jenkins.osuosl.org/job/Pipeline-Release-0.44.0-Build11/12/
https://openj9-jenkins.osuosl.org/job/Pipeline-Release-0.44.0-Build11x/10/

**Comment by patric42** [comment]
Linux amd64 built please?

**Comment by pshipton** [comment]
https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_x86-64_linux_Release/123/OpenJ9-JDK11-x86-64_linux-20240419-015834.tar.gz

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_aarch64_linux_Release/117/OpenJ9-JDK11-aarch64_linux-20240419-014102.tar.gz

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_aarch64_mac_Release/100/OpenJ9-JDK11-aarch64_mac-20240419-111829.tar.gz

**Comment by patric42** [comment]
thank you very much :-)
