### ISSUE TITLE
Tests missing native tag

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#19390]
I noticed that the following tests are missing the native test tag in the playlist.

JCL_Test
JCL_Test_none_SCC
jit_jar
UnsafeTests

For example, in https://github.com/eclipse-openj9/openj9/blob/8cb8cf38e0fdca413d7ae432309bc8d52884e839/test/functional/Java8andUp/playlist.xml#L1031 add the following native test tag
```
		<types>
			<type>native</type>
		</types>
```

[internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40166/consoleFull)

**Comment by rohit-satya** [comment]
@llxia Please assign this issue to me

**Comment by llxia** [comment]
Thanks @rohit-satya

**Comment by rohit-satya** [comment]
@llxia Please review above PR
