### ISSUE TITLE
JDK23 abuild compilation failed due to error: warnings found and -Werror specified in copyright comments

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19404]
Failure link
------------

From https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/535/consoleFull.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:34:20  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/build/linux-aarch64-server-release/support/j9jcl/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9AttachProvider.java:1: warning: [dangling-doc-comments] documentation comment is not attached to any declaration
23:34:20  /*******************************************************************************
23:34:20  ^
23:34:20  error: warnings found and -Werror specified
```

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/47457a1110...a1950364485

[8303689: javac -Xlint could/should report on "dangling" doc comments](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/bde98b68e506f63615171ea84d4eb09f7b876657)

https://bugs.openjdk.org/browse/JDK-8303689
https://bugs.openjdk.org/browse/JDK-8330177

**Comment by pshipton** [comment]
I don't think we need a line of `*`, they could just be removed. I notice the following class doesn't have them.
https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/Access.java

**Comment by keithc-ca** [comment]
I think it's more important to be consistent than the exact format. Is that the format you're proposing?
```
/*
 * Copyright IBM Corp. and others 2007
 *
```

**Comment by pshipton** [comment]
Yes.
