### ISSUE TITLE
CRIU reinitializeForRestore() revisiting

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19421]
https://github.com/eclipse-openj9/openj9/blob/190a224a7d4e4d42e726698739eb6d658f1360b2/runtime/gc_glue_java/ConfigurationDelegate.hpp#L170-L191

This method seems problematic to invoke `setOwnableSynchronizerObjectLists(NULL)` and `_extensions->setContinuationObjectLists(NULL)`, maybe others.

FYI @LinHu2016 @tajila

**Comment by LinHu2016** [comment]
```
_extensions->unfinalizedObjectLists = NULL;
_extensions->setOwnableSynchronizerObjectLists(NULL);
_extensions->setContinuationObjectLists(NULL);
```
in reinitializeForRestore() were designed for resetting the root of global lists in case we need to rebuild the lists(array of sublists, the size of array match to gcThreadCount, rebuild the lists is only needed for the case restore env has more gcThreadCount than original env). if restore env has the same or less gcThreadCount than original env, the resetting the root of global lists would cause potential assertion when vm need to access those lists. I will create a PR to fix the issue.

**Comment by dmitripivkine** [comment]
@JasonFengJ9 The fix has been merged. Can this item be closed?

**Comment by JasonFengJ9** [comment]
Yup, closing.
