### ISSUE TITLE
jdk11.0.24+1 requires jtreg version 7.3.1 b1 or higher

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19435]
`11:31:39  Error: The testsuite at /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OpenJDK11_testList_0/aqa-tests/openjdk/openjdk-jdk/test/jdk requires jtreg version 7.3.1 b1 or higher and this is jtreg version 6-dev+1.`

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OpenJDK11_testList_0/21

@llxia pls take a look

**Comment by llxia** [comment]
It looks like we need to upgrade jtreg version for jdk11. Will create PR shortly.
https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.xml#L36

**Comment by llxia** [comment]
PR is delivered. This issue is resolved.
