### ISSUE TITLE
Valhalla tests failed to compile

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#19459]
```
22:11:18      [javac] Compiling 15 source files to /home/jenkins/workspace/Test_openjdkValhalla_j9_extended.functional_x86-64_linux_valhalla_Nightly_testList_0/aqa-tests/functional/Valhalla/bin
22:11:18      [javac] error: invalid source release 22 with --enable-preview
22:11:18      [javac]   (preview language features are only supported for release 23)
22:11:18  
22:11:18  BUILD FAILED
```
Internal build [link](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdkValhalla_j9_extended.functional_x86-64_linux_valhalla_Nightly_testList_0/1058/console).
With https://github.com/eclipse-openj9/openj9/pull/19446  merged, we bring in the latest Valhalla changes from OpenJDK. The JDK version has been updated to 23. 

Keyword `primitive` is removed and `Q` type is also removed. Any tests depending on those won't compile anymore. 

There are previous work refactoring Valhalla tests https://github.com/eclipse-openj9/openj9/issues/18157 to remove dependency on `primitive` and `Q` type. We can remove these tests and enable the refactored version.

**Comment by hangshao0** [comment]
FYI @theresa-m

**Comment by theresa-m** [comment]
No, I'll try that out. Thanks.
