### ISSUE TITLE
Clean up references to iiload, iistore, et al.

### ISSUE THREAD

**Issue by hzongaro** [eclipse-openj9/openj9#19489]
Once upon a time, the JIT compiler's opcodes had the letter i as a prefix if the operation was indirect &mdash; `iiload`, `ibstore`, and so on.  Those opcodes were renamed to use the letter i as a suffix instead &mdash; `iiload` became `iloadi`, `ilstore` became `istorei`, etc.

Many comments and some trace code in the compiler &mdash; in both OpenJ9 and OMR &mdash; still refer to the old opcode names.  For example, in [Tree Simplifier](https://github.com/eclipse-openj9/openj9/blob/6880b59c0be1c508a66a71f2558efd8084359e25/runtime/compiler/optimizer/J9Simplifier.cpp#L795) and [Inliner](https://github.com/eclipse-openj9/openj9/blob/6880b59c0be1c508a66a71f2558efd8084359e25/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L1096-L1108).  It would be good to correct those lingering references to the old opcode names.

**Comment by a7ehuo** [comment]
I will start cleaning up the comments in OMR first

**Comment by a7ehuo** [comment]
My plan is

- [ ] Step 1. Clean up iiload/iistore ilload/ilstore iaload/iastore ibload/ibstore in the code comments and trace messages in OMR
   - https://github.com/eclipse-omr/omr/pull/7519
- [ ] Step 2. Clean up iiload/iistore ilload/ilstore iaload/iastore ibload/ibstore in the code comments and trace messages in OpenJ9
- [ ] Step 3. Clean up iiload/iistore ilload/ilstore iaload/iastore ibload/ibstore in the code itself in OMR and OpenJ9
- [ ] Step 4. Clean up isload/isstore, ifload/ifstore, idload/idstore in the code comments and trace messages in OMR
- [ ] Step 5. Clean up isload/isstore, ifload/ifstore, idload/idstore in the code comments and trace messages in OpenJ9
- [ ] Step 6. Clean up isload/isstore, ifload/ifstore, idload/idstore in the code itself in OMR and OpenJ9

**Comment by a7ehuo** [comment]
[All five steps of cleaning up the old opcodes](https://github.com/eclipse-openj9/openj9/issues/19489#issuecomment-2455214764) have been completed. Hence close
