### ISSUE TITLE
jdk23 alinux build failed configure: error: Option --enable-compatible-cds-alignment is not available

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19488]
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/544
```
01:06:30  checking if CDS archive is available... no (CDS is disabled)
01:06:30  checking if compatible cds region alignment enabled... enabled, default
01:06:30  configure: error: Option --enable-compatible-cds-alignment is not available
01:06:30  configure exiting with result code 1
```

https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/e0dc5ddff8e...f1297bdaaab

https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/c4084e2e3c1a602c5456d120cd60efe35fb3c0ce

**Comment by JasonFengJ9** [comment]
Occurred at JDK21 abuild as well - https://openj9-jenkins.osuosl.org/job/Build_JDK21_aarch64_linux_OpenJDK21/25/console
```
00:43:27  checking if compatible cds region alignment enabled... enabled, default
00:43:27  configure: error: Option --enable-compatible-cds-alignment is not available
00:43:28  configure exiting with result code 1
```

**Comment by JasonFengJ9** [comment]
JDK17 abuild failed - https://openj9-jenkins.osuosl.org/job/Build_JDK17_aarch64_linux_OpenJDK17/81/console
```
01:31:32  checking if compatible cds region alignment enabled... enabled, default
01:31:32  configure: error: Option --enable-compatible-cds-alignment is not available
01:31:32  configure exiting with result code 1
```

**Comment by pshipton** [comment]
I expect we'll need to fix this for jdk22 when we get the latest changes.
