### ISSUE TITLE
JDK23 aarch64_linux configure: error: Option --enable-compatible-cds-alignment is not available

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19492]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/545/console

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
23:40:25  checking if compatible cds region alignment enabled... enabled, default
23:40:25  configure: error: Option --enable-compatible-cds-alignment is not available
23:40:25  configure exiting with result code 1
```

**Comment by pshipton** [comment]
Dup of https://github.com/eclipse-openj9/openj9/issues/19488
