### ISSUE TITLE
JDK23 jdk_security3_0_FAILED sun/security/ec/ECDHKeyAgreementParamValidation.java No exception was thrown. Expected: java.security.InvalidKeyException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19500]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/17/consoleFull)(`rhel9-aarch64-8`):
```
16:14:15  openjdk version "23-internal" 2024-09-17
16:14:15  OpenJDK Runtime Environment (build 23-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
16:14:15  Eclipse OpenJ9 VM (build master-0e3af5dfb24, JRE 23 Linux aarch64-64-Bit Compressed References 20240509_110 (JIT enabled, AOT enabled)
16:14:15  OpenJ9   - 0e3af5dfb24
16:14:15  OMR      - 1bcf9698259
16:14:15  JCL      - e746df70557 based on jdk-23+21)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=serviceability_jvmti_j9_0,serviceability_jvmti_j9_1,jdk_security3_0,jdk_security3_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=functional%2Cjck&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=fengj%40ca.ibm.com&CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F110%2FOpenJ9-JDKnext-aarch64_linux-20240509-153015.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2FBuild_JDKnext_aarch64_linux_Personal%2F110%2Ftest-images.tar.gz&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=na-public.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=next&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git%2Cgit%40github.ibm.com%3Aruntimes%2Fjck.git&JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk.git&JCK_GIT_BRANCH=main&OPENJ9_BRANCH=master&OPENJ9_SHA=0e3af5dfb24f6c8d9c2aefd560f01b195a106ac2&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master%2Cmain&OPENJ9_REPO=git%40github.com%3Aeclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=sys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=http%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
17:08:19  variation: Mode150
17:08:19  JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

17:26:54  TEST: sun/security/ec/ECDHKeyAgreementParamValidation.java

17:26:54  STDERR:
17:26:54  java.lang.RuntimeException: No exception was thrown. Expected: java.lang.IllegalStateException
17:26:54  	at jdk.test.lib.Asserts.assertThrows(Asserts.java:649)
17:26:54  	at jdk.test.lib.Asserts.assertThrows(Asserts.java:622)
17:26:54  	at ECDHKeyAgreementParamValidation.testInitWithInvalidKey(ECDHKeyAgreementParamValidation.java:69)
17:26:54  	at ECDHKeyAgreementParamValidation.main(ECDHKeyAgreementParamValidation.java:103)
17:26:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:26:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
17:26:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
17:26:54  	at java.base/java.lang.Thread.run(Thread.java:1587)
17:26:54  java.lang.RuntimeException: No exception was thrown. Expected: java.security.InvalidKeyException
17:26:54  	at jdk.test.lib.Asserts.assertThrows(Asserts.java:649)
17:26:54  	at jdk.test.lib.Asserts.assertThrows(Asserts.java:622)
17:26:54  	at ECDHKeyAgreementParamValidation.testDoPhaseWithInvalidKey(ECDHKeyAgreementParamValidation.java:91)
17:26:54  	at ECDHKeyAgreementParamValidation.main(ECDHKeyAgreementParamValidation.java:110)
17:26:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:26:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
17:26:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
17:26:54  	at java.base/java.lang.Thread.run(Thread.java:1587)
17:26:54  java.lang.RuntimeException: Test failed
17:26:54  	at ECDHKeyAgreementParamValidation.main(ECDHKeyAgreementParamValidation.java:117)
17:26:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
17:26:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
17:26:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
17:26:54  	at java.base/java.lang.Thread.run(Thread.java:1587)
17:26:54  
17:26:54  JavaTest Message: Test threw exception: java.lang.RuntimeException

18:03:03  Test results: passed: 947; failed: 2
18:03:20  Report written to /home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17152858802048/jdk_security3_0/report/html/report.html
18:03:20  Results written to /home/jenkins/workspace/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/aqa-tests/TKG/output_17152858802048/jdk_security3_0/work
18:03:20  Error: Some tests failed or other problems occurred.
18:03:20  -----------------------------------
18:03:20  jdk_security3_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/40574/) - same as https://github.com/eclipse-openj9/openj9/issues/19499
- all failed

**Comment by pshipton** [comment]
@jasonkatonica @KostasTsiounis fyi

**Comment by KostasTsiounis** [comment]
I added some code through https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/788 that seemed to fix that. Did you try with the latest `openj9` branch?

**Comment by JasonFengJ9** [comment]
The fix was merged yesterday which wasn't included in the failing JVM.
Just launched another JDK23 build.

**Comment by JasonFengJ9** [comment]
This failure is not seen in [the latest JDK23 build aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_extended.openjdk_aarch64_linux_Personal/18/consoleFull)

Closing
