### ISSUE TITLE
Hash of java.rmi differs to expected hash recorded in java.base 

### ISSUE THREAD

**Issue by koppor** [eclipse-openj9/openj9#19522]
I am trying to use jlink with Eclipse OpenJ9 21

I get (on macOS)

    java.lang.module.FindException: Hash of java.rmi (03f539ebf91c81cfc7a81236d2c1109e0d050c839d03c6f757022b99a10cb819) differs to expected hash (07126a5cefcc6c19d9059cfa4b42ec832f3714a1ef89f103afc2d1ab61b79bc7) recorded in java.base

It works fine on Windows and Linux.

Full MWE project at <https://github.com/koppor/openj9-hash-issue>.

---

```groovy
plugins {
    id 'application'
    id 'org.beryx.jlink' version '3.0.1'
}

repositories {
    mavenCentral()
}

dependencies {
}

testing {
    suites {
        test {
            useJUnitJupiter('5.10.0')
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
        vendor = JvmVendorSpec.IBM
    }
}

application {
    mainClass = 'org.example.App'
}

jlink {
    mergedModule {
        requires 'java.rmi'
    }
}
```

**Comment by pshipton** [comment]
I believe it's a known problem related to signing the builds.
https://github.com/ibmruntimes/Semeru-Runtimes/issues/3

**Comment by pshipton** [comment]
Since it's problem with Semeru packaging and not OpenJ9, I'll go ahead and close this one.
