### ISSUE TITLE
Regression with Euro symbol in String management

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19543]
See the details in https://github.com/ibmruntimes/openj9-openjdk-jdk22/issues/60

**Comment by patric42** [comment]
Would you please offer a snapshot built now that the PR has been merged? Linux amd46/aarch64 Windows amd64?
TIA!

**Comment by pshipton** [comment]
The change was merged too late to make the Friday builds, there will be builds tonight.

**Comment by pshipton** [comment]
The latest Windows and xlinux builds https://openj9-jenkins.osuosl.org/job/Pipeline-Build-JDK11/174/
The latest alinux build https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-JDK11/821/

Click on the `passing` button beside `build` and the downloads are listed near the top. Only JDKs in tar format are available.

**Comment by pshipton** [comment]
Closing since https://github.com/eclipse-openj9/openj9/pull/19607 is merged. If a problem is found we can reopen or open a new issue.
