### ISSUE TITLE
How can I update the information in contributing to the project?

### ISSUE THREAD

**Issue by singh264** [eclipse-openj9/openj9#19616]
How can I update the information in contributing to the project?

> weekly Ask the OpenJ9 community calls It looks like we'll need to update this information, as we no longer have weekly OpenJ9 calls. Instead we have weekly updates in the #planning channel, with calls at the time of new releases.

<img width="748" alt="How can I update the information in contributing to the project?" src="https://github.com/eclipse-openj9/openj9/assets/15883270/bbfd01ac-aa57-41d3-83a2-4a08239cdb85">

**Comment by pshipton** [comment]
Create a PR to update https://github.com/eclipse-openj9/openj9/blob/master/README.md

**Comment by singh264** [comment]
It seems a PR is open and can be merged to update https://github.com/eclipse-openj9/openj9/blob/master/README.md.
