### ISSUE TITLE
serviceability_jvmti_j9_1_FAILED serviceability/jvmti/thread/GetStackTrace/getstacktr07/getstacktr07.java Fatal error: SetBreakpoint failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19691]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.openjdk_aarch64_mac_testList_0/65/)(`macaarch64rt1`):
```
openjdk version "22.0.1-beta" 2024-04-16
IBM Semeru Runtime Open Edition 22.0.1+8-202406120002 (build 22.0.1-beta+8-202406120002)
Eclipse OpenJ9 VM 22.0.1+8-202406120002 (build master-58b586d83e, JRE 22 Mac OS X aarch64-64-Bit 20240612_88 (JIT enabled, AOT enabled)
OpenJ9   - 58b586d83e
OMR      - 873509033
JCL      - ae28e24bf based on jdk-22.0.1+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=serviceability_jvmti_j9_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk22_j9_extended.openjdk_aarch64_mac&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-mac-aarch64-openj9%2F88%2Fibm-semeru-open-jdk_aarch64_mac_JDK22U_2024-06-12-00-01.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk22%2Fjdk22-mac-aarch64-openj9%2F88%2Fibm-semeru-open-testimage_aarch64_mac_JDK22U_2024-06-12-00-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=22&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk22&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=67&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-06-12T09:24:22.047Z] variation: Mode650
[2024-06-12T09:24:22.047Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-06-12T09:25:16.669Z] TEST: serviceability/jvmti/thread/GetStackTrace/getstacktr07/getstacktr07.java

[2024-06-12T09:25:16.671Z] STDERR:
[2024-06-12T09:25:16.671Z] JVMVMUT015W Warning: Extended HCR is disabled, enable with -XX:+EnableExtendedHCR.
[2024-06-12T09:25:16.671Z] 
[2024-06-12T09:25:16.671Z] Fatal error: SetBreakpoint failed.

[2024-06-12T09:26:27.240Z] serviceability_jvmti_j9_1_FAILED
```

It is related to
* https://github.com/eclipse-openj9/openj9/pull/19554

FYI @tajila

**Comment by tajila** [comment]
@JasonFengJ9 @LongyuZhang Do either of you know home to modify the options we run jtreg tests with?

**Comment by JasonFengJ9** [comment]
Assuming this test needs to run with `-XX:+EnableExtendedHCR`, @tajila I will add it.

**Comment by pshipton** [comment]
Options can be added to individual tests.
https://github.com/ibmruntimes/openj9-openjdk-jdk22/blob/openj9/test/hotspot/jtreg/serviceability/jvmti/thread/GetStackTrace/getstacktr07/getstacktr07.java#L42

Options can be added when we run the entire bucket.
https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L409

Isn't it bad that something which is expected to work isn't working without the option?

**Comment by pshipton** [comment]
Test description
```
 *     The test exercises JVMTI function GetStackTrace via breakpoint
 *     and consequent class redefinition.
 *     The test starts a new thread, does some nested calls, stops at breakpoint,
 *     redefines the class and checks if the number of frames in the thread's
 *     stack is as expected and the function returns all the expected frames.
```

**Comment by tajila** [comment]
> Assuming this test needs to run with -XX:+EnableExtendedHCR, @tajila I will add it.

Thanks

**Comment by JasonFengJ9** [comment]
Opened a PR
* https://github.com/adoptium/aqa-tests/pull/5385

**Comment by pshipton** [comment]
@tajila pls explain why it's ok to ignore the failing test.

Do we really want to run all the serviceability tests with `-XX:+EnableExtendedHCR`, which hides any problems caused by turning off the feature by default?

**Comment by tajila** [comment]
I didn't actually look too closely at the test. I assumed it was doing something that required extended capabilities. Ill take another look at it.

**Comment by tajila** [comment]
@JasonFengJ9 did this only fail in JDK22?

**Comment by JasonFengJ9** [comment]
> did this only fail in JDK22?

@tajila `serviceability_jvmti_j9` is enabled for JDK 21+, and it failed at [JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_linux_testList_1/63/) as well
