### ISSUE TITLE
Remote debugging stops with AGENT_ERROR_INVALID_THREAD(203)

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19759]
See https://github.com/ibmruntimes/Semeru-Runtimes/issues/80 for details.

**Comment by babsingh** [comment]
@thallium Please investigate the issue in https://github.com/ibmruntimes/Semeru-Runtimes/issues/80. I was unable to assign https://github.com/ibmruntimes/Semeru-Runtimes/issues/80 to you; you will have to post a comment in the issue for your name to show in the `Assignees` list.

Begin by reproducing the issue locally using the instructions in https://github.com/ibmruntimes/Semeru-Runtimes/issues/80#issuecomment-2197750102. Then, get in touch with @JasonFengJ9 for insights on debugging JDWP issues.

fyi @tajila

**Comment by babsingh** [comment]
Closing as per https://github.com/ibmruntimes/Semeru-Runtimes/issues/80#issuecomment-2247016882.
