### ISSUE TITLE
SharedClasses.SCM01 Copy sharedClasses jar fails

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#19841]
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.system_x86-64_linux_Nightly_testList_0/2/ - [cent7-x64-2](https://openj9-jenkins.osuosl.org/computer/cent7-x64-2)
https://openj9-jenkins.osuosl.org/job/Test_openjdk22_j9_extended.system_x86-64_linux_Nightly_testList_2/3 - [cent7-x64-2](https://openj9-jenkins.osuosl.org/computer/cent7-x64-2)
SharedClasses.SCM01.SingleCL_0
```
07:13:39  STF 07:13:38.688 - +------ Step 1 - Copy sharedClasses jar
07:13:39  STF 07:13:38.688 - | Copy a file to another directory
07:13:39  STF 07:13:38.689 - |   Source file: /home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22/classes.jar
07:13:39  STF 07:13:38.689 - |   Dest dir:    /home/jenkins/workspace/Test_openjdk22_j9_extended.system_x86-64_linux_Nightly_testList_2/aqa-tests/TKG/output_17206066236256/SharedClasses.SCM01.SingleCL_0/20240710-071333-SharedClasses/tmp
07:13:39  STF 07:13:38.689 - |
07:13:39  **FAILED** at step 1 (Copy sharedClasses jar). Expected return value=1 Actual=0 at /home/jenkins/workspace/Test_openjdk22_j9_extended.system_x86-64_linux_Nightly_testList_2/aqa-tests/TKG/../TKG/output_17206066236256/SharedClasses.SCM01.SingleCL_0/20240710-071333-SharedClasses/setUp.pl line 50.
```

07:14:08  FAILED test targets:
07:14:08  	SharedClasses.SCM01.SingleCL_0
07:14:08  	SharedClasses.SCM01.SingleCL_1
07:14:08  	SharedClasses.SCM01.MultiCL_1
07:14:08  	SharedClasses.SCM01.MultiThread_1
07:14:08  	SharedClasses.SCM01.MultiThreadMultiCL_1
07:14:08  	SharedClasses.SCM23.MultiThreadMultiCL_0

**Comment by pshipton** [comment]
@LongyuZhang pls take a look. I suspect this has something to do with the changes to preserve the shared test classes (https://github.com/eclipse-aqavit/openj9-systemtest/pull/156), and cache the system test jar files. 

The xlinux machines weren't available so we've only recently been able to resume testing on this platform. We don't have a last working / first failing build.

**Comment by LongyuZhang** [comment]
I do see console output `09:05:49  GEN /home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22 exists`, suspect the folder exists, but the `classes.jar` doesn't exist inside it. @annaibm Could you run this test, keep Workspace and ReportDir, then reserve the machine to check if `classes.jar` is there, if not check if it generated in other places. thanks.

**Comment by pshipton** [comment]
Both failures occurred on the same machine, I'll take a look at it.

**Comment by pshipton** [comment]
The directory `/home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22` exists, but classes.jar doesn't exist. The subdirectory `net/openj9/sc/classes/` exists and is full of classes. Probably there is a logic error and if the test finds something, it expects classes.jar to exist. There were some machines that ran out of space, this may have been one of them. Deleted `jdk22` and hopefully that fixes it.

**Comment by annaibm** [comment]
Ran the extended.system tests under the following scenarios on the machine `rhel9x86-svl-rt1-1.fyre.ibm`:
1. When `/home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22` did not exist -  [42017](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42017/)  
```
19:43:16  GEN   /home/jenkins/testDependency/system_lib/junit/junit.jar
19:43:16  GEN 16:43:11.743 - Using Mode NoOptions. Values = ''
19:43:16  GEN /home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22 does not exist
19:43:16  GEN 16:43:11.968 - 
```
```
19:45:48  STF 16:45:47.283 - 
19:45:48  STF 16:45:47.283 - +------ Step 2 - Copy sharedClasses jar
19:45:48  STF 16:45:47.283 - | Copy a file to another directory
19:45:48  STF 16:45:47.283 - |   Source file: /home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22/classes.jar
19:45:48  STF 16:45:47.283 - |   Dest dir:    /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17206453097873/SharedClasses.SCM01.SingleCL_0/20240710-164307-SharedClasses/tmp
19:45:48  STF 16:45:47.283 - |
19:45:48  STF 16:45:47.322 - 
```
2. When `/home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22` existed - [42018](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42018)
```
23:55:01  GEN 20:55:00.847 - Using Mode NoOptions. Values = ''
23:55:01  GEN /home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22 exists
23:55:01  GEN 20:55:00.995 - 
```
```
23:55:01  STF 20:55:01.136 - +------ Step 1 - Copy sharedClasses jar
23:55:01  STF 20:55:01.136 - | Copy a file to another directory
23:55:01  STF 20:55:01.136 - |   Source file: /home/jenkins/testDependency/system_lib/sharedClassesTestData/v1/jdk22/classes.jar
23:55:01  STF 20:55:01.136 - |   Dest dir:    /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_1720660287936/SharedClasses.SCM01.MultiCL_0/20240710-205457-SharedClasses/tmp
```

All tests passed in both scenarios.
