### ISSUE TITLE
JVM Crash: hashClassTableAt: Unaligned class value - ASSERTION FAILED openj9\runtime\vm\KeyHashTable.c:73

### ISSUE THREAD

**Issue by Herr-Sepp** [eclipse-openj9/openj9#19878]
Java -version output
--------------------
IBM Semeru Runtime Open Edition 17.0.11.0 (build 17.0.11+9)
Eclipse OpenJ9 VM 17.0.11.0 (build openj9-0.44.0, JRE 17 Windows Server 2019 amd64-64-Bit Compressed References 20240416_709 (JIT enabled, AOT enabled)
OpenJ9   - b0699311c7
OMR      - 254af5a04
JCL      - 5d7d758b682 based on jdk-17.0.11+9)

Summary of problem
------------------

If we want to compile our java programm sometimes the JVM crashed with this error.
Rare, but it has already occurred several times.

Diagnostic files
----------------

Please provide a email where i can send the download to the diagnostic files.

<0000000000DADB00> hashClassTableAt: Unaligned class value 0000022C40448A39
15:04:34.651 0xdadb00    j9vm.249    *   ** ASSERTION FAILED ** at c:\workspace\openjdk-build\workspace\build\src\openj9\runtime\vm\KeyHashTable.c:73: ((0 ))
JVMDUMP039I Speicherauszugsereignis "traceassert", Detail "" um 2024/07/19 17:04:34 - bitte warten.
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von System mit "\core.20240719.170434.8504.0001.dmp" an
JVMDUMP010I Speicherauszug von System in core.20240719.170434.8504.0001.dmp geschrieben
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Java mit "javacore.20240719.170434.8504.0002.txt" an
JVMDUMP010I Speicherauszug von Java in javacore.20240719.170434.8504.0002.txt geschrieben
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Snap mit "Snap.20240719.170434.8504.0003.trc" an
JVMDUMP010I Speicherauszug von Snap in Snap.20240719.170434.8504.0003.trc geschrieben
JVMDUMP013I Speicherauszugsereignis "traceassert", Detail "" wurde verarbeitet.

**Comment by hangshao0** [comment]
This is a dup of https://github.com/eclipse-openj9/openj9/issues/13123. Could you try to see if it still happens on the latest [build](https://openj9-jenkins.osuosl.org/view/Build_Nightly/job/Build_JDK17_x86-64_windows_Nightly/) ?

**Comment by Herr-Sepp** [comment]
@hangshao0 Thanks for the answer and sorry for the dup.
Is it correct that the last nightly is over 2 weeks old? Should I test with that from 05.07.2024?

**Comment by hangshao0** [comment]
Yes, the latest Windows 17 nightly build is over 2 weeks old. The latest one you can try is 05.07.2024.

**Comment by hangshao0** [comment]
@Herr-Sepp Do you have a chance to see if this still happens in the latest build ?

**Comment by Herr-Sepp** [comment]
@hangshao0 We haven't had this error for a very long time, even with the affected version.
I have no idea how to reproduce it and would close the ticket as we are moving to version 0.47.

Thanks for the information and help.
