### ISSUE TITLE
Jenkins line endings check needs to skip metadata.blob files

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19923]
https://openj9-jenkins.osuosl.org/job/PullRequest-LineEndingsCheck-OpenJ9/14543/console
```
15:17:42  test/functional/cmdLineTests/jfr/metadata.blob:164: trailing whitespace.
15:17:42  +�S�����
```
As per https://github.com/eclipse-openj9/openj9/pull/19917#issuecomment-2252925774, there is no way to generate this file dynamically currently. We need to skip the line endings check for this type of file.

**Comment by keithc-ca** [comment]
With the change to `.gitattributes` in #19917, the file metadata.blob will be classified as "data" and not subject to the line-end check.
