### ISSUE TITLE
openJcePlusTests_0_FAILED openJcePlusTests_0/test.xml:69: Test ibm.jceplus.junit.TestMultithread failed (crashed)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#19981]
Failure link
------------

From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.functional_ppc64_aix_testList_0/660/)(`paix816`):
```
java version "17.0.13-beta" 2024-10-15
IBM Semeru Runtime Certified Edition 17.0.13+1-202408031435 (build 17.0.13-beta+1-202408031435)
Eclipse OpenJ9 VM 17.0.13+1-202408031435 (build master-27dac39d2c, JRE 17 AIX ppc64-64-Bit Compressed References 20240803_723 (JIT enabled, AOT enabled)
OpenJ9   - 27dac39d2c
OMR      - 9ccff3cf2
JCL      - fb48a6ea96 based on jdk-17.0.13+1)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=openJcePlusTests_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_extended.functional_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=functional&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F723%2Fibm-semeru-certified-jdk_ppc64_aix_JDK17U_2024-08-03-14-31.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F723%2Fibm-semeru-certified-testimage_ppc64_aix_JDK17U_2024-08-03-14-31.tar.gz+https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-aix-ppc64-openj9-IBM%2F723%2Fibm-semeru-certified-testimage_ppc64_aix_JDK17U_2024-08-03-14-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk17&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=697&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-08-03T17:49:07.136Z] variation: NoOptions
[2024-08-03T17:49:07.136Z] JVM_OPTIONS:  

[2024-08-03T17:50:24.863Z]      [test] 
[2024-08-03T17:50:24.863Z]      [test] BUILD FAILED
[2024-08-03T17:50:24.863Z]      [test] /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_ppc64_aix_testList_0/aqa-tests/TKG/output_17227041744091/openJcePlusTests_0/test.xml:69: Test ibm.jceplus.junit.TestMultithread failed (crashed)
[2024-08-03T17:50:24.863Z]      [test] 
[2024-08-03T17:50:24.863Z]      [test] Total time: 1 minute 10 seconds
[2024-08-03T17:50:24.863Z] 
[2024-08-03T17:50:24.863Z] BUILD FAILED
[2024-08-03T17:50:24.863Z] /home/jenkins/workspace/Test_openjdk17_j9_extended.functional_ppc64_aix_testList_0/aqa-tests/TKG/output_17227041744091/openJcePlusTests_0/test.xml:35: Java returned: 1
[2024-08-03T17:50:24.863Z] 
[2024-08-03T17:50:24.863Z] Total time: 1 minute 12 seconds
[2024-08-03T17:50:24.863Z] -----------------------------------
[2024-08-03T17:50:24.863Z] openJcePlusTests_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/42637/) - 5 failure at `paix816`

**Comment by pshipton** [comment]
@jasonkatonica fyi this failure

**Comment by jasonkatonica** [comment]
There is ongoing work being done to provide a series of fixes for the multithreaded test cases. This cluster of issues has been present since GA, so we can move this issue to the next release target.

**Comment by jasonkatonica** [comment]
Closing this issue since tests have been adjusted to support a multi-threading environment. Closing until this issue resurfaces again.
