### ISSUE TITLE
addToLibpath() does not work on z/OS

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#20060]
`addToLibpath()` does not work on z/OS. The problematic code is here:

https://github.com/eclipse-openj9/openj9/blob/91b5703ea59e75ae6c72e4c65123ba13bc06488a/runtime/j9vm/jvm.c#L2968-L2969

`putenv()` does not copy the `putenvPath` string. The `putenvPath` string becomes part of the environment variable. The code frees `putenvPath` after `putenv()` call, which will mess up the environment variable.

From the z/OS [documentation](https://www.ibm.com/docs/en/zos/3.1.0?topic=functions-putenv-change-add-environment-variable):

`Note: Starting with, z/OS® V1R2, the storage used to define the environment variable pointed to by envvar is added to the array of environment variables. Previously, the system copied the string into system allocated storage. `

**Comment by keithc-ca** [comment]
Perhaps `setenv()` should be used on z/OS, like in [jvm.c](https://github.com/eclipse-openj9/openj9/blob/master/runtime/j9vm/jvm.c#L548).

**Comment by hangshao0** [comment]
Yes, `setenv()` copies the string and it is safer to use.

**Comment by hangshao0** [comment]
I find out that we have redefined `putenv()` on z/OS:
https://github.com/eclipse/omr/blob/35b34b4f36d627d400e7449980aa51eab95cf334/util/a2e/headers/stdlib.h#L85
and the implementation already takes care of string conversion and copying
https://github.com/eclipse/omr/blob/35b34b4f36d627d400e7449980aa51eab95cf334/util/a2e/atoe.c#L327-L337

**Comment by hangshao0** [comment]
Closing this based on https://github.com/eclipse-openj9/openj9/issues/20060#issuecomment-2312946198.
