### ISSUE TITLE
Invoking Class.forName through old reflection failed with ClassNotFound exception

### ISSUE THREAD

**Issue by r30shah** [eclipse-openj9/openj9#20155]
I am looking into running sanity.openjdk tests with setting `-Djdk.reflect.useDirectMethodHandle=false` to switch to old core reflection for method.invoke calls instead of Method Handles. While testing the SDK with that option, it fails test in [1]. I am pasting here simplified version of the test here that reproduces the problem.

```
$ cat Test.java
import java.lang.invoke.*;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.lang.reflect.InvocationTargetException;

public class Test {
    static final String NAME = Test.class.getName();

    public static void main(String[] args) throws Throwable {
	final Method fnMethod = Class.class.getMethod("forName", String.class);
  	final MethodType mt = MethodType.methodType(Object.class, Object.class, Object[].class);

  	final MethodHandle mh = MethodHandles.lookup().bind(fnMethod, "invoke", mt);
	//mh.bindTo(null).bindTo(new Object[]{NAME}).invoke();
	//mh.invoke(null, new Object[]{NAME});
      	try {
  		mh.invokeWithArguments(null, NAME);
      	} catch (InvocationTargetException ex) {
      		ex.getCause().printStackTrace();
      	}
  	//mh.invokeWithArguments(Arrays.asList(null, NAME));
	//Object obj = mh.invokeExact((Object) null, new Object[]{NAME});
    }
}


$ java -Xshareclasses:none -Xint -Djdk.reflect.useDirectMethodHandle=false  Test
java.lang.ClassNotFoundException: Test
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:372)
	at java.base/java.lang.Class.forName(Class.java:350)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:75)
	at java.base/jdk.internal.reflect.MethodAccessorImpl.invoke(MethodAccessorImpl.java:51)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:59)
	at java.base/java.lang.reflect.Method.invoke(Method.java:613)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments(MethodHandleImpl.java:544)
	at Test.main(Test.java:17)
```

I printed bunch of statements in [Class.forName](https://github.com/eclipse-openj9/openj9/blob/cf5af082931e9586299e7ea58980e4ca2d7c6475/jcl/src/java.base/share/classes/java/lang/Class.java#L434) to see why it fails with ClassNotFoundException. 
What I see that in the failing case when it calls the Class.forName with the caller class at [2], it considers `java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments` as the caller class and as that class is being loaded by system class loader, it tries to find Test class in system class loader which did not load Test class hence it fails with ClassNotFoundException. As ways to invoke the Class.forName works in [1], I looked into the difference, also checked out the [getCallerClassJEP176Iterator](https://github.com/eclipse-openj9/openj9/blob/cf5af082931e9586299e7ea58980e4ca2d7c6475/runtime/vm/NativeHelpers.cpp#L85), I see that when we iterate the stack frames, if we reach the depth 0 and the class at that depth is one of the reflection classes or method handle.invoke classes, it keeps iterating the stack. 

I see that we do not check for [MethodHandleImpl$AsVarargsCollector.invokeWithArguments](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/b651e56e50abfe017894fd6bbc89be2c9835aeaa/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java#L537) causing us to think that the caller is that method. 

I am opening up to discuss this failure and potential fix. 

[1]. https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/java/lang/invoke/7196190/ClassForNameTest.java
[2]. https://github.com/eclipse-openj9/openj9/blob/cf5af082931e9586299e7ea58980e4ca2d7c6475/jcl/src/java.base/share/classes/java/lang/Class.java#L406

**Comment by r30shah** [comment]
I added change in OpenJ9 to also check if the method is AsAVarargsCollector.invoke and added it to places where we also give special treatments to MethodHandle.invoke methods in [1].

@babsingh / @TobiAjila   I am testing the fix in [1] to make sure that it passes the functional tests but given that this is in the VM side, would appreciate if I can get your POV on the failure as well. 

[1]. https://github.com/r30shah/openj9/commit/ea51632689246f97c7810833db99958767a79920

**Comment by gacholio** [comment]
Can we do this with the caller sensitive annotation instead?

**Comment by babsingh** [comment]
- The error also persists in the RI. 
- In JDK17+, it will be the `@Hidden` annotation since OJDK MHs are enabled. It should fix the above error.

Note:  `-Djdk.reflect.useDirectMethodHandle=false` is no longer supported in JDK22+ https://bugs.openjdk.org/browse/JDK-8309635.

**Comment by keithc-ca** [comment]
Do we need similar changes for newer (or any other) versions, e.g. https://github.com/ibmruntimes/openj9-openjdk-jdk23 and https://github.com/ibmruntimes/openj9-openjdk-jdk?

**Comment by keithc-ca** [comment]
> Do we need similar changes for newer (or any other) versions?

As https://github.com/eclipse-openj9/openj9/issues/20155#issuecomment-2346553050 notes, `jdk.reflect.useDirectMethodHandle` is only relevant for jdk21.
