### ISSUE TITLE
Build error: "statement has no effect" with J9CLASS_DEPTH() in java_lang_invoke_MethodHandleNatives.cpp

### ISSUE THREAD

**Issue by knn-k** [eclipse-openj9/openj9#20170]
Building OpenJ9 Java 17 with GCC 13.2.0 on Ubuntu 24.04.1 generates the following error:

```
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp: In function 'j
int Java_java_lang_invoke_MethodHandleNatives_getMembers(JNIEnv*, jclass, jclass, jstring, jstring, jint, jclass, jint,
jobjectArray)':
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/oti/j9class.h:35:68: error: statement has no effect [-Werror=unused-value]
   35 | #define J9CLASS_DEPTH(clazz) (((UDATA)(clazz)->classDepthAndFlags) & J9AccClassDepthMask)
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp:1466:49: note: in expansion of macro 'J9CLASS_DEPTH'
 1466 |                                                 J9CLASS_DEPTH(defClass);
      |                                                 ^~~~~~~~~~~~~
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/oti/j9class.h:35:68: error: statement has no effect [-Werror=unused-value]
   35 | #define J9CLASS_DEPTH(clazz) (((UDATA)(clazz)->classDepthAndFlags) & J9AccClassDepthMask)
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/openj9/openj9-openjdk-jdk17/openj9/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp:1571:49: note: in expansion of macro 'J9CLASS_DEPTH'
 1571 |                                                 J9CLASS_DEPTH(defClass);
      |                                                 ^~~~~~~~~~~~~

$ gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
```

https://github.com/eclipse-openj9/openj9/blob/0985ff3f82bfdf1944c81f6242466fcbae2308b5/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp#L1463-L1467

https://github.com/eclipse-openj9/openj9/blob/0985ff3f82bfdf1944c81f6242466fcbae2308b5/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp#L1568-L1572

**Comment by knn-k** [comment]
The results of `J9CLASS_DEPTH(defClass)` are not used at all in these places.
I guess these lines should be changed to `classDepth = J9CLASS_DEPTH(defClass)`, but I am not sure.

**Comment by knn-k** [comment]
Another build error with GCC 13.2.0: #20171

**Comment by knn-k** [comment]
I opened a draft PR: #20173

**Comment by keithc-ca** [comment]
> The following part is never executed because `classDepth` is unchanged after initialized by 0 at L.1463.
> 
> https://github.com/eclipse-openj9/openj9/blob/0985ff3f82bfdf1944c81f6242466fcbae2308b5/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp#L1514-L1515
> 
> It is the same for L.1626-1627.

I think that is just a bug. However, it will only affect Java 17. Earlier versions do not use OpenJDK method handles (`J9VM_OPT_OPENJDK_METHODHANDLE`) by default, and later versions don't have that native method.
