### ISSUE TITLE
DaaLoadTest_daa1_5m_0_FAILED Invalid JIT return address && j9vm.249 ASSERTION FAILED at openj9/runtime/vm/swalk.c:1633: ((0 ))

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20180]
From [an internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_testList_2/752/)(`ubu22lert-3`):
```
java version "11.0.25-beta" 2024-10-15
IBM Semeru Runtime Certified Edition 11.0.25+5-202409140109 (build 11.0.25-beta+5-202409140109)
Eclipse OpenJ9 VM 11.0.25+5-202409140109 (build master-0c6cdfd79f, JRE 11 Linux ppc64le-64-Bit Compressed References 20240914_946 (JIT enabled, AOT enabled)
OpenJ9   - 0c6cdfd79f
OMR      - 10fdf657a
JCL      - 49008fb73c based on jdk-11.0.25+5)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=DaaLoadTest_daa1_5m_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_sanity.system_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna-public.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-openj9-IBM%2F946%2Fibm-semeru-certified-jdk_ppc64le_linux_JDK11U_2024-09-14-01-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=11&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=792&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2024-09-14T02:39:29.458Z] variation: Mode110
[2024-09-14T02:39:29.458Z] JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

[2024-09-14T02:40:54.906Z] DLT 02:40:51.671 - Completed 26.7%. Number of tests started=7352 (+2227)
[2024-09-14T02:41:12.106Z] DLT stderr 
[2024-09-14T02:41:12.106Z] DLT stderr 
[2024-09-14T02:41:12.106Z] DLT stderr *** Invalid JIT return address 0000796355711514 in 00007963F0ADA900
[2024-09-14T02:41:12.106Z] DLT stderr 
[2024-09-14T02:41:12.106Z] DLT stderr 02:41:08.552 0x7963f0ada600    j9vm.249    *   ** ASSERTION FAILED ** at ../../../../../openj9/runtime/vm/swalk.c:1633: ((0 ))
[2024-09-14T02:41:12.106Z] DLT stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2024/09/14 02:41:08 - please wait.

[2024-09-14T02:41:15.320Z] DaaLoadTest_daa1_5m_0_FAILED
```

[50x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/43295/) - passed

**Comment by hangshao0** [comment]
Should be the same issue as https://github.com/eclipse-openj9/openj9/issues/19249.

**Comment by JasonFengJ9** [comment]
The same assertion, just the line number was changed.
Closing as dup of 
* https://github.com/eclipse-openj9/openj9/issues/19249
