### ISSUE TITLE
Value Types: crash when System.arrayCopy sets null in null-restricted array

### ISSUE THREAD

**Issue by theresa-m** [eclipse-openj9/openj9#20253]
Related to https://github.com/eclipse-openj9/openj9/issues/20223 I also tried the following to see whether or not I can copy null into a null-restricted array. This test results in a segmentation error.

java --enable-preview --add-exports java.base/jdk.internal.vm.annotation=ALL-UNNAMED --add-exports java.base/jdk.internal.value=ALL-UNNAMED -XX:ValueTypeFlatteningThreshold=99999 -XX:+EnableArrayFlattening -Xint TestNullRestrictedArray
```
        static private void test1(int x) {
           SomeValueClass1[] array1 = (SomeValueClass1[])ValueClass.newArrayInstance(NullRestrictedCheckedType.of(SomeValueClass1.class), ARRAY_SIZE);
           SomeValueClass1[] array2 = new SomeValueClass1[ARRAY_SIZE];
                
                for (int i=0; i < ARRAY_SIZE; i++) {
                        array1[i] = new SomeValueClass1(i*x);
                        array2[i] = null;
                }
                
                System.arraycopy(array2, 0, array1, 0, ARRAY_SIZE);
        }
```

Changes from https://github.com/eclipse-openj9/openj9/pull/20250 are needed to reproduce this.

**Comment by dmitripivkine** [comment]
Speculating, but please be aware it is possible we do not have proper implementation for some cases for Flattened Arrays copy. Traditional array copy functions might have deal with hardcoded element sizes 1, 2, 4 , 8. Copy of different size element byte by byte might be not sufficient due possible object references embedded to the element. Coping object reference should be done size-atomic. Also it might require triggering of GC barriers. Please do not hesitate to ask if there is one of this cases or you need help with investigation.

**Comment by hangshao0** [comment]
There is a comment in the code:

https://github.com/eclipse-openj9/openj9/blob/e425dbfb6065d12ed3c80ee59262160a70aa926d/runtime/vm/createramclass.cpp#L3455-L3458

The flag `J9ClassIsFlattened` is expected to be removed from nullable array.

**Comment by theresa-m** [comment]
Oh yea... that was me wasn't it 😅. Thanks, I'll start there.
