### ISSUE TITLE
Unexpected result for Class.isInstance() given nullable array instance and non-nullable array class

### ISSUE THREAD

**Issue by hzongaro** [eclipse-openj9/openj9#20305]
Given the class of a non-nullable array and a nullable array instance the `Class.isInstance()` method for the OpenJ9 value types prototype implementation yields a different result from that of the Reference Implementation.  For the following test:

```
$ cat TestIsInstance.java
import jdk.internal.value.NullRestrictedCheckedType;
import jdk.internal.value.ValueClass;
import jdk.internal.vm.annotation.ImplicitlyConstructible;

public class TestIsInstance {
    @ImplicitlyConstructible
    public static value class Point {
        public final int i, j;

        public Point(int i, int j) {
            this.i = i;
            this.j = j;
        }
    }

    public static final void main(String[] args) throws ClassNotFoundException {
        Point[] nonNullableArray = (Point[]) ValueClass.newArrayInstance(NullRestrictedCheckedType.of(Point.class), 1);
        Point[] nullableArray = new Point[1];

        System.out.println("nonNullableArray.getClass().isInstance(nonNullableArray) == "+nonNullableArray.getClass().isInstance(nonNullableArray));
        System.out.println("nullableArray.getClass().isInstance(nullableArray) == "+nullableArray.getClass().isInstance(nullableArray));
        System.out.println("nonNullableArray.getClass().isInstance(nullableArray) == "+nonNullableArray.getClass().isInstance(nullableArray));
        System.out.println("nullableArray.getClass().isInstance(nonNullableArray) == "+nullableArray.getClass().isInstance(nonNullableArray));
    }
}
```

OpenJ9 yields:

```
nonNullableArray.getClass().isInstance(nonNullableArray) == true
nullableArray.getClass().isInstance(nullableArray) == true
nonNullableArray.getClass().isInstance(nullableArray) == true
nullableArray.getClass().isInstance(nonNullableArray) == true
```

while the Reference Implementation yields:

```
nonNullableArray.getClass().isInstance(nonNullableArray) == true
nullableArray.getClass().isInstance(nullableArray) == true
nonNullableArray.getClass().isInstance(nullableArray) == false
nullableArray.getClass().isInstance(nonNullableArray) == true
```

@theresa-m, @hangshao0, @a7ehuo - FYI

**Comment by theresa-m** [comment]
Thanks @hzongaro I opened a change to fix this.

I think it would be useful to have some checkcast tests for arrays as well since my change will impact that as well, I will write those later this week.

**Comment by hzongaro** [comment]
At the suggestion of @jdmpapin, I also tried a variation of this test using `Class.isAssignableFrom(Class)` instead.  That exhibited a similar difference in behaviour between OpenJ9 and the Reference Implementation.  I just thought I'd mention it in case that would entail any additional changes to your pull request.

**Comment by theresa-m** [comment]
> isAssignableFrom

Thanks! I believe my changes will fix Class.isAssignableFrom as well.

**Comment by theresa-m** [comment]
> I think it would be useful to have some checkcast tests for arrays as well since my change will impact that as well, I will write those later this week.

I think the only way to do this right now is with the CheckedType api which is not supported yet https://github.com/eclipse-openj9/openj9/issues/19764
