### ISSUE TITLE
JDK17 Windows jdk_security4_0_FAILED ProviderException: Could not load dependent ock library

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20321]
**Failure link**
---
From internal [Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1/2/) (win19x86-rtp-rt7-1)

```**Java Version**
openjdk version "17.0.13" 2024-10-15
IBM Semeru Runtime Open Edition 17.0.13.0-m1 (build 17.0.13+10)
Eclipse OpenJ9 VM 17.0.13.0-m1 (build v0.48.0-release-8899b66789, JRE 17 Windows Server 2019 amd64-64-Bit Compressed References 20241015_811 (JIT enabled, AOT enabled)
OpenJ9   - 8899b66789
OMR      - f8f0d789a
JCL      - 8e2f05376ed based on jdk-17.0.13+10)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_security4_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=9f50c848-8764-440d-b95a-1d295c21713e&amp;TEST_FLAG=FIPS140_3_OpenJCEPlusFIPS&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;LABEL=&amp;JCK_VERSION=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fhyc-runtimes-jenkins.swg-devops.com%2Fjob%2Fbuild-scripts%2Fjob%2Fopenjdk17-pipeline%2F1047%2Fartifact%2Ftarget%2Fwindows%2Fx64%2Fopenj9%2F*.zip%2F*zip*%2Fopenj9.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.4-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;BUILD_TYPE=release&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=docker-na.artifactory.swg-devops.com%2Fsys-rt-docker-local&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JCK_GIT_BRANCH=&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=2&amp;CONFIG_JSON=%5B%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22NONE%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22aarch64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22aarch64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_2%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS.FIPS140-3%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%0A%5D%0A&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=f3b78d91-4db0-4a87-b4d8-32164430cfdc&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;separator-87e3a7db-4843-4907-ad26-40f469fe3204=&amp;TIME_LIMIT=36&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-10-07T18:13:11.907Z] variation: Mode150
[2024-10-07T18:13:13.269Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS

[2024-10-07T18:17:50.191Z] TEST: sun/security/krb5/auto/principalProperty/PrincipalSystemPropTest.java

[2024-10-07T18:17:50.219Z] Caused by: java.lang.ExceptionInInitializerError
[2024-10-07T18:17:50.219Z] 	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:206)
[2024-10-07T18:17:50.219Z] 	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:195)
[2024-10-07T18:17:50.219Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.OCKContext.createContext(OCKContext.java:38)
[2024-10-07T18:17:50.219Z] 	at openjceplus/com.ibm.crypto.plus.provider.OpenJCEPlusFIPS.initializeContext(OpenJCEPlusFIPS.java:760)
[2024-10-07T18:17:50.219Z] 	... 43 more
[2024-10-07T18:17:50.220Z] Caused by: java.security.ProviderException: Could not load dependent ock library
[2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface.preloadOCK(NativeInterface.java:314)
[2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface$1.run(NativeInterface.java:54)
[2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface$1.run(NativeInterface.java:47)
[2024-10-07T18:17:50.220Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
[2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface.<clinit>(NativeInterface.java:47)
[2024-10-07T18:17:50.220Z] 	... 45 more
[2024-10-07T18:17:50.220Z] 
[2024-10-07T18:17:50.220Z] JavaTest Message: Test threw exception: java.lang.ExceptionInInitializerError

[2024-10-07T18:53:34.541Z] Test results: passed: 147; failed: 1
[2024-10-07T18:54:08.137Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1\aqa-tests\TKG\output_17283221842901\jdk_security4_0\report\html\report.html
[2024-10-07T18:54:08.137Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1\aqa-tests\TKG\output_17283221842901\jdk_security4_0\work
[2024-10-07T18:54:08.137Z] Error: Some tests failed or other problems occurred.
[2024-10-07T18:54:08.137Z] -----------------------------------
[2024-10-07T18:54:08.137Z] jdk_security4_0_FAILED
```
There was a similar issue 
* https://github.com/eclipse-openj9/openj9/issues/19986

**Comment by pshipton** [comment]
@jasonkatonica pls take a look. This is from 0.48 M1 testing.

**Comment by jasonkatonica** [comment]
This test should be ignored once the two remaining PRs for the windows ignore lists are merged into Java 17 and 11:

Windows specific list on 17:
- https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/376

Windows specific list on 11:
- https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/821

I did validate that the FIPS libraries load OK by manually using the [builds found here for the M1 .48 release](https://hyc-runtimes-jenkins.swg-devops.com/job/build-scripts/job/openjdk17-pipeline/1047/artifact/target/windows/x64/openj9/) to ensure this is not the same issue we ran into with  https://github.com/eclipse-openj9/openj9/issues/19986 where the libraries were completely missing.

**Comment by pshipton** [comment]
The jdk17 exclude list is merged now, and also included in the v0.48.0-release branch.

**Comment by sebm123** [comment]
> ## **Failure link**
> From internal [Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1/2/) (win19x86-rtp-rt7-1)
> 
> ```
> openjdk version "17.0.13" 2024-10-15
> IBM Semeru Runtime Open Edition 17.0.13.0-m1 (build 17.0.13+10)
> Eclipse OpenJ9 VM 17.0.13.0-m1 (build v0.48.0-release-8899b66789, JRE 17 Windows Server 2019 amd64-64-Bit Compressed References 20241015_811 (JIT enabled, AOT enabled)
> OpenJ9   - 8899b66789
> OMR      - f8f0d789a
> JCL      - 8e2f05376ed based on jdk-17.0.13+10)
> ```
> 
> [Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=jdk_security4_0&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=9f50c848-8764-440d-b95a-1d295c21713e&TEST_FLAG=FIPS140_3_OpenJCEPlusFIPS&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=true&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&LABEL=&JCK_VERSION=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fhyc-runtimes-jenkins.swg-devops.com%2Fjob%2Fbuild-scripts%2Fjob%2Fopenjdk17-pipeline%2F1047%2Fartifact%2Ftarget%2Fwindows%2Fx64%2Fopenj9%2F*.zip%2F*zip*%2Fopenj9.zip&BUILD_IDENTIFIER=&JENKINS_KEY=Jenkins+4096+key&ADOPTOPENJDK_BRANCH=v1.0.4-release&LIGHT_WEIGHT_CHECKOUT=false&BUILD_TYPE=release&USE_JRE=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&JDK_VERSION=17&DOCKER_REGISTRY_URL=docker-na.artifactory.swg-devops.com%2Fsys-rt-docker-local&ITERATIONS=1&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=2&CONFIG_JSON=%5B%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22NONE%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22aarch64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22aarch64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_2%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS.FIPS140-3%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%0A%5D%0A&DOCKERIMAGE_TAG=&TEST_TIME=&JDK_IMPL=openj9&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=f3b78d91-4db0-4a87-b4d8-32164430cfdc&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&OPENJDK_SHA=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&separator-87e3a7db-4843-4907-ad26-40f469fe3204=&TIME_LIMIT=36&JVM_OPTIONS=&PARALLEL=None) - Change TARGET to run only the failed test targets
> 
> ## **Optional info**
> ## Failure output (captured from console output)
> ```
> [2024-10-07T18:13:11.907Z] variation: Mode150
> [2024-10-07T18:13:13.269Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog  -Dsemeru.fips=true -Dsemeru.customprofile=OpenJCEPlusFIPS
> 
> [2024-10-07T18:17:50.191Z] TEST: sun/security/krb5/auto/principalProperty/PrincipalSystemPropTest.java
> 
> [2024-10-07T18:17:50.219Z] Caused by: java.lang.ExceptionInInitializerError
> [2024-10-07T18:17:50.219Z] 	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:206)
> [2024-10-07T18:17:50.219Z] 	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:195)
> [2024-10-07T18:17:50.219Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.OCKContext.createContext(OCKContext.java:38)
> [2024-10-07T18:17:50.219Z] 	at openjceplus/com.ibm.crypto.plus.provider.OpenJCEPlusFIPS.initializeContext(OpenJCEPlusFIPS.java:760)
> [2024-10-07T18:17:50.219Z] 	... 43 more
> [2024-10-07T18:17:50.220Z] Caused by: java.security.ProviderException: Could not load dependent ock library
> [2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface.preloadOCK(NativeInterface.java:314)
> [2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface$1.run(NativeInterface.java:54)
> [2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface$1.run(NativeInterface.java:47)
> [2024-10-07T18:17:50.220Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
> [2024-10-07T18:17:50.220Z] 	at openjceplus/com.ibm.crypto.plus.provider.ock.NativeInterface.<clinit>(NativeInterface.java:47)
> [2024-10-07T18:17:50.220Z] 	... 45 more
> [2024-10-07T18:17:50.220Z] 
> [2024-10-07T18:17:50.220Z] JavaTest Message: Test threw exception: java.lang.ExceptionInInitializerError
> 
> [2024-10-07T18:53:34.541Z] Test results: passed: 147; failed: 1
> [2024-10-07T18:54:08.137Z] Report written to C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1\aqa-tests\TKG\output_17283221842901\jdk_security4_0\report\html\report.html
> [2024-10-07T18:54:08.137Z] Results written to C:\Users\jenkins\workspace\Test_openjdk17_j9_sanity.openjdk_x86-64_windows_fips140_3_openjceplusfips_testList_1\aqa-tests\TKG\output_17283221842901\jdk_security4_0\work
> [2024-10-07T18:54:08.137Z] Error: Some tests failed or other problems occurred.
> [2024-10-07T18:54:08.137Z] -----------------------------------
> [2024-10-07T18:54:08.137Z] jdk_security4_0_FAILED
> ```
> 
> There was a similar issue
> 
> * [jdk_security1_0_FAILED java/security/Provider/DefaultProviderList.java  ProviderException: Could not load dependent jgskit library #19986](https://github.com/eclipse-openj9/openj9/issues/19986)

**Comment by JasonFengJ9** [comment]
> Eclipse OpenJ9 VM 17.0.13.0-m1 (build v0.48.0-release-8899b66789, JRE 17 Windows Server 2019 amd64-64-Bit Compressed References 20241015_811 (JIT enabled, AOT enabled)

This is a m1 build. The test has been excluded in release and head streams.
