### ISSUE TITLE
jdk_foreign_1_FAILED java/foreign/StdLibTest.java IllegalArgumentException: Unsupported charset: windows-1252

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20337]
**Failure link**
---
From internal [Test_openjdk23_j9_sanity.openjdk_x86-64_windows_testList_6](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk23_j9_sanity.openjdk_x86-64_windows_testList_6/14/) (win10x86-rtp-rt5-1)

```**Java Version**
openjdk version "23" 2024-09-17
IBM Semeru Runtime Open Edition 23.0.1.0-m1 (build 23+37)
Eclipse OpenJ9 VM 23.0.1.0-m1 (build v0.48.0-release-8899b66789, JRE 23 Windows 10 amd64-64-Bit Compressed References 20240917_1 (JIT enabled, AOT enabled)
OpenJ9   - 8899b66789
OMR      - f8f0d789a
JCL      - bad8ef27634 based on jdk-23+37)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_foreign_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=9f50c848-8764-440d-b95a-1d295c21713e&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk23_j9_sanity.openjdk_x86-64_windows&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;separator-f6d5c789-dd25-4194-b271-9092c7ac7f8d=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;LABEL=&amp;JCK_VERSION=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fhyc-runtimes-jenkins.swg-devops.com%2Fjob%2Fbuild-scripts%2Fjob%2Fopenjdk23-pipeline%2F63%2Fartifact%2Ftarget%2Fwindows%2Fx64%2Fopenj9%2F*.zip%2F*zip*%2Fopenj9.zip&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=v1.0.4-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;BUILD_TYPE=release&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=23&amp;DOCKER_REGISTRY_URL=docker-na.artifactory.swg-devops.com%2Fsys-rt-docker-local&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JCK_GIT_BRANCH=main&amp;JDK_REPO=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=35&amp;CONFIG_JSON=%5B%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22NONE%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22aarch64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22aarch64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultTestTargets%2Cdev.external%22+%7D%2C%0A++++++++++++%7B+%22x86-64_mac%22+%3A+%22defaultTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_2%22%2C+%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%2C%0A++++%7B%0A++++++++%22TEST_FLAG%22+%3A+%22FIPS140_3_OpenJCEPlusFIPS.FIPS140-3%22%2C%0A++++++++%22PLATFORM_TARGETS%22+%3A+%5B%0A++++++++++++%7B+%22ppc64_aix%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22ppc64le_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22s390x_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_linux%22+%3A+%22defaultFipsTestTargets%22+%7D%2C%0A++++++++++++%7B+%22x86-64_windows%22+%3A+%22defaultFipsTestTargets%22+%7D%0A++++++++%5D%0A++++%7D%0A%5D&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=f3b78d91-4db0-4a87-b4d8-32164430cfdc&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;separator-87e3a7db-4843-4907-ad26-40f469fe3204=&amp;TIME_LIMIT=36&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2024-10-10T02:40:29.755Z] variation: Mode650
[2024-10-10T02:40:32.352Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-10-10T02:46:19.963Z] TEST: java/foreign/StdLibTest.java

[2024-10-10T02:46:19.966Z] STDOUT:
[2024-10-10T02:46:19.966Z] NativeTestHelper::DEFAULT_RANDOM.seed = -1056041501
[2024-10-10T02:46:19.967Z] Re-run with '-DNativeTestHelper.DEFAULT_RANDOM.seed=-1056041501' to reproduce
[2024-10-10T02:46:19.967Z] test StdLibTest.testSystemLibraryBadLookupName(): success
[2024-10-10T02:46:19.967Z] test StdLibTest.test_printf([LONG, STRING, STRING, STRING]): failure
[2024-10-10T02:46:19.967Z] java.lang.IllegalArgumentException: Unsupported charset: windows-1252
[2024-10-10T02:46:19.967Z] 	at java.base/jdk.internal.foreign.StringSupport$CharsetKind.of(StringSupport.java:304)
[2024-10-10T02:46:19.967Z] 	at java.base/java.lang.foreign.SegmentAllocator.allocateFrom(SegmentAllocator.java:138)
[2024-10-10T02:46:19.967Z] 	at StdLibTest$StdLibHelper.printf(StdLibTest.java:318)
[2024-10-10T02:46:19.967Z] 	at StdLibTest.test_printf(StdLibTest.java:143)

[2024-10-10T02:46:19.994Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 34100
[2024-10-10T02:46:19.994Z] --------------------------------------------------
[2024-10-10T03:24:59.811Z] Test results: passed: 91; failed: 1
[2024-10-10T03:27:15.912Z] Report written to C:\Users\jenkins\workspace\Test_openjdk23_j9_sanity.openjdk_x86-64_windows_testList_6\aqa-tests\TKG\output_1728524697271\jdk_foreign_1\report\html\report.html
[2024-10-10T03:27:15.912Z] Results written to C:\Users\jenkins\workspace\Test_openjdk23_j9_sanity.openjdk_x86-64_windows_testList_6\aqa-tests\TKG\output_1728524697271\jdk_foreign_1\work
[2024-10-10T03:27:15.912Z] Error: Some tests failed or other problems occurred.
[2024-10-10T03:27:17.275Z] -----------------------------------
[2024-10-10T03:27:17.275Z] jdk_foreign_1_FAILED
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/44101/) - all failed

**Comment by r30shah** [comment]
This must be due to my change in https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/52 which gets the native encoded string before calling native printf through downcall.

I will take a look at this on Tuesday.

**Comment by r30shah** [comment]
Looking at the JDK23 failing stack, it fails in [1], and I do not see support for any charset other than UTF , ISO-8859. I need go through the code to see how to fix this properly (I believe, on windows, having standard UTF-8 charset should be fine, but given that we pass in native charset on windows, it fails. 


@JasonFengJ9 / @pshipton  is this going to block 0.48 ? If yes, I can go ahead and revert the changes to ensure it works fine and work on more concrete fix.

Similar change went in JDK21 but it is OK there as we simply get the bytes in native encoding from given string and allocate segment using that, so we would not hit the issue. 

FYI, @keithc-ca 

[1]. https://github.com/ibmruntimes/openj9-openjdk-jdk23/blob/fe73bf0e7b4616ff17847da7a6c29acdb3df8b72/src/java.base/share/classes/jdk/internal/foreign/StringSupport.java#L289-L306

**Comment by keithc-ca** [comment]
The test will need to be updated; `SegmentAllocator.allocateFrom(String, Charset)` says

     * throws IllegalArgumentException if charset is not a standard charset

**Comment by r30shah** [comment]
Yes, this was my first instinct. If native charset is not standard, it should go on and allocate using default charset (Which is UTF-8), this would resolve current failure. And update the code for z/OS later.

**Comment by JasonFengJ9** [comment]
> is this going to block 0.48 ? If yes, I can go ahead and revert the changes to ensure it works fine and work on more concrete fix.

This is a test issue, it won't block 0.48.
