### ISSUE TITLE
80 FVT_Serviceability.diagnostics.xdump_throw.Mode112.1 Incorrect JIT Version Information in ENVINFO section

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20407]
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=94540612)(`win19x64-rtp-2-1`):
```
java version "1.8.0_431"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pwa6480sr9-20240925_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit 20241023_80221 (JIT enabled, AOT enabled)
OpenJ9   - 2c7141fa0cf
OMR      - d2f915f
IBM     - dd9cff8)
JCL - 20240920_02 based on Oracle jdk8u431-b09
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
>> 2024 Thu Oct 24 00:13:26 throw test failed...
>> 2024 Thu Oct 24 00:13:26 javacore.20241024.001131.7564.0003.txt: ERROR: Incorrect JIT Version Information in ENVINFO section. JIT informa
tion in javacore was 'tr.open_20241022_131113_2c7141f', expected it to contain '2c7141fa0cf'
```

There was a similar failure
* https://github.com/eclipse-openj9/openj9/issues/19550

**Comment by pshipton** [comment]
I think it's a case that not all Windows machines received the update to remove the test, and possibly the master source distributed to Windows didn't get updated. I can roll out the change again.

**Comment by pshipton** [comment]
For future reference see infrastructure/issues/9118

**Comment by pshipton** [comment]
Machine updated to remove the test.
