### ISSUE TITLE
JDK next compilation error: incompatible types: Class<CAP#1> cannot be converted

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#20428]
https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_OpenJDK/665/consoleFull
```
00:52:25  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/src/java.base/share/classes/java/lang/Double.java:462: error: incompatible types: Class<CAP#1> cannot be converted to Class<Double>
00:52:25      public static final Class<Double> TYPE = Class.getPrimitiveClass("double");
00:52:25                                                                      ^
00:52:25    where CAP#1 is a fresh type-variable:
00:52:25      CAP#1 extends Object from capture of ?

00:52:25  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_OpenJDK/src/java.base/share/classes/java/lang/Short.java:82: error: incompatible types: Class<CAP#1> cannot be converted to Class<Short>
00:52:25      public static final Class<Short> TYPE = Class.getPrimitiveClass("short");
00:52:25                                                                     ^
00:52:25    where CAP#1 is a fresh type-variable:
00:52:25      CAP#1 extends Object from capture of ?
00:52:25  Note: Some input files additionally use or override a deprecated API.
00:52:25  Note: Some input files additionally use or override a deprecated API that is marked for removal.
00:52:25  Note: Some input files additionally use unchecked or unsafe operations.
00:52:25  9 errors
```

This is due to openjdk change https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0995dd6a3f4eefa02280e10754ceeffc3eb85c69

**Comment by pshipton** [comment]
I assume this is related to not using the latest bootjdk. We can back out the change until we are ready to move the bootjdk up.
@keithc-ca agreed?

**Comment by JasonFengJ9** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0995dd6a3f4eefa02280e10754ceeffc3eb85c69 
from:
```
    /*
     * Return the Virtual Machine's Class object for the named
     * primitive type.
    static native Class<?> getPrimitiveClass(String name);
```
to:
```
    /*
     * Returns the Class object for the named primitive type. Type parameter T
     * avoids redundant casts for trusted code.
     */
    static native <T> Class<T> getPrimitiveClass(String name);
```
I think similar change is needed at 
https://github.com/eclipse-openj9/openj9/blob/17ee5e7dd4e0b5b52321966907125d88aef13380/jcl/src/java.base/share/classes/java/lang/Class.java#L865

**Comment by pshipton** [comment]
Oh ok. Are you going to fix it?

**Comment by keithc-ca** [comment]
I don't understand your comment about `getComponentType()`: I don't see how it could change and being public API, the signature must not change.

**Comment by JasonFengJ9** [comment]
`getPrimitiveClass()` invokes `getComponentType()`.
https://github.com/eclipse-openj9/openj9/blob/6fd3a8c00b62646484eaa7a79b6062920b54a520/jcl/src/java.base/share/classes/java/lang/Class.java#L2950-L2952

A quick way to unblock the build is to do a cast there `return (Class<T>) new float[0].getClass().getComponentType();` along with the API change `static <T> Class<T> getPrimitiveClass(String name)`.

**Comment by keithc-ca** [comment]
I was hoping the solution could follow the pattern of `forPrimitiveName(String)` (using e.g. `int.class`), but that has bootstrap problems.

**Comment by keithc-ca** [comment]
> I assume this is related to not using the latest bootjdk.

No, the same problem happens whether the bootjdk is Java 21 or Java 23.
