### ISSUE TITLE
jdk/incubator/vector and other tests timing out

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20435]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_OMR_testList_2/110 - [cent7-x64-4](https://openj9-jenkins.osuosl.org/computer/cent7-x64-4)
jdk/incubator/vector/Double128VectorTests.java
timeout
```
11:04:50  "MainThread" prio=5 Id=23 RUNNABLE
11:04:50  	at java.base@21.0.5-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
11:04:50  	at java.base@21.0.5-internal/java.lang.reflect.Method.invoke(Method.java:586)
11:04:50  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
11:04:50  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
11:04:50  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
11:04:50  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
11:04:50  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
11:04:50  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
11:04:50  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
11:04:50  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
11:04:50  	at java.base@21.0.5-internal/java.util.ArrayList.forEach(ArrayList.java:1596)
11:04:50  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
11:04:50  	at app//org.testng.TestRunner.run(TestRunner.java:585)
11:04:50  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
```

jdk/incubator/vector/Int128VectorTests.java
timeout
```
11:46:25  "MainThread" prio=5 Id=23 RUNNABLE
11:46:25  	at java.base@21.0.5-internal/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
11:46:25  	at java.base@21.0.5-internal/java.lang.reflect.Method.invoke(Method.java:586)
11:46:25  	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
11:46:25  	at app//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
11:46:25  	at app//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
11:46:25  	at app//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
11:46:25  	at app//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
11:46:25  	at app//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
11:46:25  	at app//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
11:46:25  	at app//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
11:46:25  	at java.base@21.0.5-internal/java.util.ArrayList.forEach(ArrayList.java:1596)
11:46:25  	at app//org.testng.TestRunner.privateRun(TestRunner.java:764)
11:46:25  	at app//org.testng.TestRunner.run(TestRunner.java:585)
11:46:25  	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
```

**Comment by pshipton** [comment]
The new change under test is https://github.com/eclipse/omr/pull/7501
"x86: Support BMI2 instructions"

Not sure if this could be the cause of these failures, but I haven't seen them before afaik.

@BradleyWood @0xdaryl this is going to block OMR acceptance until we figure it out (fix, revert, or decide the failures are unrelated).

**Comment by pshipton** [comment]
This also appears a hang on non-x86, so the failures may be caused by some other change.

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/176
jdk_vector_short128_j9_0
```
07:39:45  #INFO:  StartTime: Oct 29 11:39:44 2024
07:39:45  #INFO:  Free Physical Memory: 14279 MB 
07:39:45  #INFO:  CPU entitlement = 800.00
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 0000000000024D00, thread ID 4
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 000000000001DD00, thread ID 1
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 0000000000027200, thread ID 5
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 0000000000022700, thread ID 3
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 0000000000029700, thread ID 6
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 000000000001B700, thread ID 0
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 0000000000020200, thread ID 2
07:39:46  #INFO:  Stopping compilation thread, vmThread pointer 000000000002BD00, thread ID 7
```

**Comment by pshipton** [comment]
My bad, actually this failed in the nightly build and I originally missed it, so it's not related to the OMR change.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_aarch64_linux_Nightly_testList_2/94/
jdk/incubator/vector/Byte128VectorTests.java
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_0/23/
jdk/incubator/vector/Float128VectorTests.java
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/23/

**Comment by pshipton** [comment]
Changes from last passing build.
https://github.com/eclipse-openj9/openj9/compare/c67b5f4de4c...0e6e83c585d
https://github.com/ibmruntimes/openj9-openjdk-jdk23/compare/7812a7c8667...7239a750115

**Comment by pshipton** [comment]
I'm not sure what is causing this. @mpirvu could it be https://github.com/eclipse-openj9/openj9/pull/20417

**Comment by mpirvu** [comment]
Hmm, I don't see the connection to the vector tests. I'll look deeper.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/336
jdk_util_0 
java/util/Base64/TestBase64.java
timeout - no diagnostics

https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/336/
jdk_foreign_0
java/foreign/TestByteBuffer.java
java/foreign/TestNulls.java
timeout - no diagnostics

jdk/incubator/vector/Byte64VectorTests.java
timeout
```
21:41:04  "MainThread" prio=5 Id=23 RUNNABLE
21:41:04  	at jdk.incubator.vector@21.0.5-internal/jdk.incubator.vector.ByteVector$ByteSpecies.rvOp(ByteVector.java:4228)
21:41:04  	at jdk.incubator.vector@21.0.5-internal/jdk.incubator.vector.ByteVector.lambda$zero$1(ByteVector.java:565)
21:41:04  	at java.base@21.0.5-internal/jdk.internal.vm.vector.VectorSupport.fromBitsCoerced(VectorSupport.java:210)
21:41:04  	at jdk.incubator.vector@21.0.5-internal/jdk.incubator.vector.ByteVector.zero(ByteVector.java:563)
21:41:04  	at app//Byte64VectorTests.ZeroByte64VectorTests(Byte64VectorTests.java:4722)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64le_linux_Nightly_testList_2/231/
    jdk/incubator/vector/Byte128VectorTests.java.Byte128VectorTests
    jdk/incubator/vector/Double128VectorTests.java.Double128VectorTests
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/240/
jdk/incubator/vector/Byte64VectorTests.java.Byte64VectorTests
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/240/
jdk/incubator/vector/Long128VectorTests.java.Long128VectorTests

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/95/
06:36:17  	jdk_security4_1 - Test results: passed: 154; error: 3 
06:36:17  		Failed test cases: 
06:36:17  			TEST: sun/security/krb5/auto/AlwaysEncPaReq.java
06:36:17          TEST: sun/security/krb5/auto/DiffNameSameKey.java
06:36:17          TEST: sun/security/krb5/auto/DiffSaltParams.java
06:36:17          
06:36:17  	jdk_vector_double128_j9_0 - Test results: error: 1 
06:36:17  		Failed test cases: 
06:36:17  			TEST: jdk/incubator/vector/Double128VectorTests.java

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_linux_Nightly_testList_0/83/
jdk/incubator/vector/Float128VectorTests.java.Float128VectorTests
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_x86-64_linux_Nightly_testList_2/83/
jdk/incubator/vector/Int128VectorTests.java
