### ISSUE TITLE
Timeouts on alinux

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20463]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/324/
    java/util/stream/boottest/java.base/java/util/stream/DoubleNodeTest.java.DoubleNodeTest
    java/util/stream/boottest/java.base/java/util/stream/FlagOpTest.java.FlagOpTest

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_sanity.openjdk_aarch64_linux_Nightly_testList_0/96
    java/lang/Class/forName/ForNameNames.java.ForNameNames
    java/lang/Class/forName/NonLinking/NonLinking.java.NonLinking

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/338
jdk_foreign_0
java/foreign/TestByteBuffer.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_1/338/openjdk_test_output.tar.gz

```
    name:          MainThread
    id:            4030332
    Thread object: java/lang/Thread @ 0xe00d95f0
    ID:            23 (0x17)
    Priority:      -1
    Thread.State:  WAITING
    JVMTI state:   ALIVE WAITING WAITING_INDEFINITELY IN_OBJECT_WAIT
      waiting to be notified on: "Thread public flags mutex" with ID 0xf6a430186ab0 owner name: <unowned>
    Java stack frames:
     bp: 0x000000000022bbc0  method: Class java/lang/reflect/Method.getReturnType()  source: Method.java:<data unavailable>
      objects: 0xe027a6c0 0xe027a6c0 0xe027a6c0
     bp: 0x000000000022bc50  method: jdk.internal.reflect.MethodAccessorImpl jdk/internal/reflect/MethodHandleAccessorFactory.newMethodAccessor(reflect.Method, boolean)  source: MethodHandleAccessorFactory.java:80
      objects: 0xe027a6c0
     bp: 0x000000000022bc90  method: jdk.internal.reflect.MethodAccessor jdk/internal/reflect/ReflectionFactory.newMethodAccessor(reflect.Method, boolean)  source: ReflectionFactory.java:159
      objects: <no objects in this frame>
     bp: 0x000000000022bd30  method: jdk.internal.reflect.MethodAccessor java/lang/reflect/Method.acquireMethodAccessor()  source: Method.java:732
      objects: 0xffda88e8
     bp: 0x000000000022bdf0  method: Object java/lang/reflect/Method.invoke(Object, Object[])  source: Method.java:583
      objects: 0xffda88e8 0xffdcdf28 0xffda8940 0xe0040898
     bp: 0x000000000022be48  method: void TestByteBuffer.testScopedBuffer(java.util.function.Function, reflect.Method, Object[])  source: TestByteBuffer.java:397
      objects: <no objects in this frame>
```

**Comment by pshipton** [comment]
@tajila can someone take a look pls.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_2/337/
jdk_foreign_1
java/foreign/TestByteBuffer.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_Nightly_testList_2/337/openjdk_test_output.tar.gz

**Comment by tajila** [comment]
@babsingh Please take a look

**Comment by babsingh** [comment]
The two previous timeouts have occurred at different points, suggesting that it is not a hang.

https://github.com/eclipse-openj9/openj9/issues/20463#issuecomment-2452063279:
```
<1d3200> 	!j9method 0x000000000014CE48   jdk/internal/reflect/MethodHandleAccessorFactory.getDirectMethod(Ljava/lang/reflect/Method;Z)Ljava/lang/invoke/MethodHandle;
<1d3200> 	!j9method 0x000000000014CDE8   jdk/internal/reflect/MethodHandleAccessorFactory.newMethodAccessor(Ljava/lang/reflect/Method;Z)Ljdk/internal/reflect/MethodAccessorImpl;
<1d3200> 	!j9method 0x00000000000711B8   jdk/internal/reflect/ReflectionFactory.newMethodAccessor(Ljava/lang/reflect/Method;Z)Ljdk/internal/reflect/MethodAccessor;
<1d3200> 	!j9method 0x0000000000055858   java/lang/reflect/Method.acquireMethodAccessor()Ljdk/internal/reflect/MethodAccessor;
<1d3200> 	!j9method 0x0000000000055778   java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
```
https://github.com/eclipse-openj9/openj9/issues/20463#issuecomment-2452077703.
```
<ffffac2cf100> 	!j9method 0x0000FFFF10323FC8   java/nio/MappedMemoryUtils.force0(Ljava/io/FileDescriptor;JJ)V
<ffffac2cf100> 	!j9method 0x0000FFFF10323FC8   java/nio/MappedMemoryUtils.force0(Ljava/io/FileDescriptor;JJ)V
<ffffac2cf100> 	!j9method 0x0000FFFF10323F48   java/nio/MappedMemoryUtils.force(Ljava/io/FileDescriptor;JZJJ)V
<ffffac2cf100> 	!j9method 0x0000FFFFAC239908   java/nio/Buffer$2.force(Ljava/io/FileDescriptor;JZJJ)V
<ffffac2cf100> 	!j9method 0x0000FFFFAC233400   jdk/internal/misc/ScopedMemoryAccess.forceInternal(Ljdk/internal/foreign/MemorySessionImpl;Ljava/io/FileDescriptor;JZJJ)V
<ffffac2cf100> 	!j9method 0x0000FFFFAC2333E0   jdk/internal/misc/ScopedMemoryAccess.force(Ljdk/internal/foreign/MemorySessionImpl;Ljava/io/FileDescriptor;JZJJ)V
<ffffac2cf100> 	!j9method 0x0000FFFF10309680   jdk/internal/foreign/MappedMemorySegmentImpl.force()V
<ffffac2cf100> 	!j9method 0x0000FFFFAC49F010   TestByteBuffer.testMappedSegmentOffset()V
```

No timeouts are seen in a 100x grinder of `TestByteBuffer`: https://openj9-jenkins.osuosl.org/job/Grinder/3945. This reconfirms that there are no hangs with `TestByteBuffer`.

The test suite needs longer to run on `alinux`, so the test suite's timeout should be increased. @llxia Can you help with increasing the timeout?

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_aarch64_linux_OMR_testList_1/182
    java/foreign/TestByteBuffer.java.TestByteBuffer
    java/foreign/TestLayouts.java.TestLayouts

**Comment by llxia** [comment]
Currently, the default is `-timeoutFactor:2`. We can try to increase the timeout factor on alinux to 4.
https://github.com/adoptium/aqa-tests/blob/a2f96a0fc17d206c45eeade3fbea7395dcb13d36/openjdk/openjdk.mk#L120

@LongyuZhang could you take care of this one? Thanks

**Comment by llxia** [comment]
Close this issue as timeout factor is increased via https://github.com/adoptium/aqa-tests/pull/5781
