### ISSUE TITLE
The JVM attempted to checkpoint but was unable to due to code being executed in @NotCheckpointSafe frames.

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20481]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Nightly_testList_0/763
04:37:02  	cmdLineTester_criu_nonPortableRestore_1
04:37:02  	cmdLineTester_criu_nonPortableRestore_2
04:37:02  	cmdLineTester_criu_nonPortableRestore_5
04:37:02  	cmdLineTester_criu_nonPortableRestore_7
04:37:02  	cmdLineTester_criu_nonPortableRestore_8
04:37:02  	cmdLineTester_criu_nonPortableRestore_10

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Nightly_testList_1/762/
03:31:15  	cmdLineTester_criu_nonPortableRestore_0
03:31:15  	cmdLineTester_criu_nonPortableRestore_3
03:31:15  	cmdLineTester_criu_nonPortableRestore_4
03:31:15  	cmdLineTester_criu_nonPortableRestore_6
03:31:15  	cmdLineTester_criu_nonPortableRestore_9

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly/653/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly/910/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_aarch64_linux_Nightly/803/
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.functional_ppc64le_linux_Nightly/712/

`Caused by: openj9.internal.criu.JVMCheckpointException: The JVM attempted to checkpoint but was unable to due to code being executed in @NotCheckpointSafe frames. Retry attempts: 100`

Changes:
https://github.com/eclipse-openj9/openj9/compare/56dfc15a43f...91c7b58e0c8
https://github.com/eclipse-openj9/openj9-omr/compare/205c540402c...be39f059c4e
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/bb64c4c3e9a...2dda5f45462

**Comment by pshipton** [comment]
@tajila is this related to https://github.com/eclipse-openj9/openj9/pull/20421 ?

**Comment by tajila** [comment]
> @tajila is this related to https://github.com/eclipse-openj9/openj9/pull/20421 ?

Yes, Ill revert
