### ISSUE TITLE
x86 timeouts

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#20502]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_0/3 - [ub18-x86-2a](https://openj9-jenkins.osuosl.org/computer/ub18-x86-2a)
DaaLoadTest_all_special_5m_28
`-Xcompressedrefs -Xgcpolicy:gencon -Xshareclasses -Xjit`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_0/3/system_test_output.tar.gz
```
00:59:57  DLT 01:59:55.946 - Completed 26.8%. Number of tests started=391 (+76)
01:00:01  STF 02:00:00.476 - **FAILED** Process DLT has timed out
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_1/3 - [cent7-x64-2](https://openj9-jenkins.osuosl.org/computer/cent7-x64-2)
MathLoadTest_autosimd_special_5m_9 
`-Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_1/3/system_test_output.tar.gz
```
01:59:47  MLT 01:59:45.163 - Completed 86.8%. Number of tests started=5324132 (+434193)
02:00:02  STF 02:00:00.341 - **FAILED** Process MLT has timed out
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_3/3/ - [ub16x64j98](https://openj9-jenkins.osuosl.org/computer/ub16x64j98)
DaaLoadTest_daa3_special_5m_24
`-Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_3/3/system_test_output.tar.gz
```
02:02:34  DLT 02:02:31.654 - Completed 87.5%. Number of tests started=749 (+58)
02:02:42  STF 02:02:41.459 - Heartbeat: Process DLT is still running
02:02:44  STF 02:02:43.465 - **FAILED** Process DLT has timed out
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_4/3 - [cent7-x64-4](https://openj9-jenkins.osuosl.org/computer/cent7-x64-4)
DaaLoadTest_all_special_5m_18 
`-XX:+UseCompressedOops -Xgcpolicy:balanced -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk23_j9_special.system_x86-64_linux_Personal_testList_4/3/system_test_output.tar.gz
```
01:03:49  DLT 02:03:49.024 - Completed 80.8%. Number of tests started=805 (+32)
01:04:07  STF 02:04:05.378 - Heartbeat: Process DLT is still running
01:04:08  STF 02:04:07.385 - **FAILED** Process DLT has timed out
```

More hangs on xmac

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_mac_Personal_testList_0/3/
LambdaLoadTest_special_J9_5m_23
`-Xcompressedrefs -Xjit:count=0 -Xgcpolicy:gencon -Xaggressive -Xconcurrentlevel0`

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_mac_Personal_testList_1/3/
MiniMix_3h_0 

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_mac_Personal_testList_2/3/
DaaLoadTest_all_special_5m_12
`-Xjit -Xgcpolicy:balanced -Xnocompressedrefs`

https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_special.system_x86-64_mac_Personal_testList_3/3/
ParallelStreamsLoadTest_special_J9_15
`-XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:counts=- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000,gcOnResolve,rtResolve,sampleInterval=2,scorchingSampleThreshold=10000,quickProfile -Xcheck:gc:vmthreads:all:quiet`

**Comment by pshipton** [comment]
@0xdaryl is this related to https://github.com/eclipse-openj9/openj9/pull/20431 ?

**Comment by pshipton** [comment]
I suspect this is related to the DST change.

**Comment by 0xdaryl** [comment]
I admit the name sounds suspicious, but I think this is unlikely to cause hangs.  Unless there was some pre-existing race condition where more a more efficient spin loop changed the timing and exposed problems.
