### ISSUE TITLE
Assert from swalk.c when using memory disclaiming on NFS

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse-openj9/openj9#20509]
A customer reported failures with JRE 17 Linux amd64-64 (build 17.0.12+7) and JRE 21 Linux amd64-64 (build 21.0.4+7-LTS) with the symptom of 
```
j9vm.249    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-x64-openj9/workspace/build/src/openj9/runtime/vm/swalk.c:1629: ((0 ))
```

Corefile analysis shows large areas of memory reading as 0, and mmap'd to files with names starting with `.nfs` in the current working directory.

The problem can be avoided with the option `-Xjit:disableDataCacheDisclaiming,disableIprofilerDataDisclaiming`

This relates to issue https://github.com/eclipse-openj9/openj9/issues/20239 however the customer has tested with the 0.48 m1 build and reports that the problem still exists, albeit with a different line number:

```
j9vm.249    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-x64-openj9/workspace/build/src/openj9/runtime/vm/swalk.c:1633: ((0 ))
```

Internal case reference: TS017553893

**Comment by pshipton** [comment]
If you are referring to the fix for 20239, i.e. https://github.com/eclipse-openj9/openj9-omr/pull/215, then it's not in the m1 build.

The rc1 build does include it. I've provided it here https://ibm.box.com/s/3euojkv5pmk3x3yksbz3v9dqzvxrxrc8

**Comment by JamesKingdon** [comment]
Ah, good to know, thank you Peter. I'll pass the info on.

**Comment by JamesKingdon** [comment]
Customer reports success with the RC1 build - many thanks!
I'll close this issue given this information, it can always be reopened if more problems come to light.
