### ISSUE TITLE
Using nightly build's JFR causes Spring app to livelock

### ISSUE THREAD

**Issue by MattAlp** [eclipse-openj9/openj9#20624]
When using the x86 nightly build from Nov 15th, 2024 to run the [DaCapo](https://www.dacapobench.org/) Spring benchmark, the JVM will livelock and throttle the CPU.

To reproduce, run `java -XX:+FlightRecorder -jar dacapo-23.11-chopin.jar spring`. The benchmark will successfully run without flight recorder enabled. Some other benchmarks, such as `cassandra`, appear to execute fine with JFR enabled.

**Comment by gacholio** [comment]
Various potential hangs have been fixed in JFR today, please try with the next nightly.

**Comment by tajila** [comment]
https://github.com/eclipse-openj9/openj9/pull/20640 fixes the livelock that was seen in the Dacapo Spring benchmark
