### ISSUE TITLE
Error in building Valhalla at Reference.java:70

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9#20626]
Found in the internal [build](https://hyc-runtimes-jenkins.swg-devops.com/view/Valhalla%20Tests/job/Build_JDKnext_x86-64_linux_valhalla_Nightly/1607/consoleFull): 

```
21:09:29  /home/jenkins/workspace/Build_JDKnext_x86-64_linux_valhalla_Nightly/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/ref/Reference.java:70: error: <anonymous java.lang.ref.Reference$1> is not abstract and does not override abstract method <T>newNativeReferenceQueue() in JavaLangRefAccess
21:09:29  		SharedSecrets.setJavaLangRefAccess(new JavaLangRefAccess() {
```

**Comment by hangshao0** [comment]
@JasonFengJ9 is working on updating the extension repo to resolve this.

**Comment by JasonFengJ9** [comment]
Updated the valhalla extension repo, the latest [nightly run](https://hyc-runtimes-jenkins.swg-devops.com/view/Valhalla%20Tests/job/Pipeline_Build_Test_JDKnext_x86-64_linux_valhalla/2005/) passed.

Closing

**Comment by hangshao0** [comment]
It is failing again, but in a different place: https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_linux_vt_standard_Personal/29/console

```
12:28:13  /home/jenkins/workspace/Build_JDKnext_aarch64_linux_vt_standard_Personal/src/java.base/share/classes/jdk/internal/classfile/impl/UnboundAttribute.java:515: error: UnboundLoadableDescriptorsAttribute is not abstract and does not override abstract method attributeName() in Attribute
12:28:13      public static final class UnboundLoadableDescriptorsAttribute
```

**Comment by JasonFengJ9** [comment]
> It is failing again, but in a different place

Fixed. Also adopt 
* https://github.com/eclipse-openj9/openj9/pull/20655

The latest [nightly build](https://hyc-runtimes-jenkins.swg-devops.com/view/Valhalla%20Tests/job/Pipeline_Build_Test_JDKnext_x86-64_linux_valhalla/2009/) passed.
