### ISSUE TITLE
jextract/jpackcore not packaged in Java 8 JDK for Windows

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse-openj9/openj9#20661]
A customer reported not being able to find jextract in their Semeru Java 8 installation on Windows, so I downloaded the latest build of the jdk (ibm-semeru-open-jdk_x86-32_windows_8u432b06_openj9-0.48.0.zip) and confirmed that I couldn't find it either.

**Comment by pshipton** [comment]
This might be intentional, since you don't need to run jpackcore on Windows. I find it in the jre/bin directory for other platforms.

**Comment by pshipton** [comment]
The doc indicates AIX, Linux, macOS.
https://eclipse.dev/openj9/docs/tool_jextract/#dump-extractor-jpackcore

**Comment by pshipton** [comment]
We are excluding Windows on jdk8.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/make/CompileLaunchers.gmk#L524

I see in jdk11+ jextract/jpackcore are included.

**Comment by pshipton** [comment]
We could include it, but it does bundle all the dlls on Windows, which afaik aren't needed since the data is included in the core file. 
Any particular reason the customer was looking for it on Windows?

**Comment by keithc-ca** [comment]
It's not present on Linux either (I checked 0.46.0).

**Comment by pshipton** [comment]
I see it in xlinux 0.46. It's in jre/bin and not bin.

**Comment by keithc-ca** [comment]
You're right (I didn't look there). Shouldn't it be in both places (in a JDK)?

**Comment by pshipton** [comment]
> Shouldn't it be in both places (in a JDK)?

It wouldn't hurt but nobody is complaining about that afaik.

**Comment by JamesKingdon** [comment]
> We could include it, but it does bundle all the dlls on Windows, which afaik aren't needed since the data is included in the core file. Any particular reason the customer was looking for it on Windows?

I think because we are used to asking for system cores to be processed with jextract by default. I noticed that the docs for jextract don't mention Windows. I don't know for sure if we get everything we need without using jextract or not - it would be amusing if we've been asking for it for years without needing it.

**Comment by keithc-ca** [comment]
For the record, those tools were explicitly omitted via https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/205.
