### ISSUE TITLE
Relo records not being created properly with inlining and findOrFabricateShadowSymbol

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9#20669]
While running acmeair with `-Xaot:forceAOT`, I noticed that adding `disableInlining` in the cold run reduced the number of AOT failures by around 200, including roughly 150 `compilationSymbolValidationManagerFailure` failures (which are assertion failures in the SVM). If I run with `TR_svmAssertionsAreFatal=1`, I get a crash in `TR_J9SharedCacheVM::getClassFromSignature()` in this method:

https://github.com/eclipse-openj9/openj9/blob/eae6d58876cfd797d0913c623775ce172fa4f850/runtime/compiler/compile/J9SymbolReferenceTable.cpp#L791

Compiling this method without fatal assertions does show that the failure occurs during

```
[     4] O^O INLINER: Inlining qwerty java/util/Locale.equals(Ljava/lang/Object;)Z into java/util/ResourceBundle$CacheKey.equals(Ljava/lang/Object;)Z with a virtual guard kind=DirectMethodGuard type=NonoverriddenTest partialInline=0
```

The assertion is "method ... should have already been validated", and from looking at `findOrFabricateShadowSymbol()` it does seem like the first method of `containingClass` wouldn't necessarily have been validated already. A relo record should be created for this method, or some other way should be found to get `declaringClass`.

----

(EDIT: that other issue is only somewhat related to this, and the issue there wouldn't have been caused by the error here).

~~Actually, this might be related to https://github.com/eclipse-openj9/openj9/issues/20529#issuecomment-2484538171 as well. I was confused why certain values couldn't be looked up in a beholder constant pool while `TR_RelocationRecordValidateStaticClassFromCP` was being validated, and noticed that there weren't any prior records with an `internalVMFunctions` call that would actually resolve the entry at that index, unlike other collections of records. I suspect that if the first method of `containingClass` coincidentally happens to be validated already, the SVM compilation will succeed, but then will fail to load because a record isn't created for `definingClass` and some time later something called `classOfStatic()` on `definingClass`. I mention this because that `ValidateStaticClassFromCP` record was created while inlining `java/util/Locale.equals(Ljava/lang/Object;)Z` too, in what looks like the same the same place as the assertion failure here. (The method being compiled was different, of course).~~

Now that I think about it, `getClassFromSignature()` isn't called with `isVettedForAOT=true` and that would cause an arbitrary class validation to be created without SVM, so the `declaringClass` in `findOrFabricateShadowSymbol()` is probably missing a validation record as well.

**Comment by cjjdespres** [comment]
@mpirvu This is the failure I was seeing during my testing, and @dsouzai this could be related to the constant pool lookup failures I was talking about, which might have been a bug after all.

**Comment by dsouzai** [comment]
>I suspect that if the first method of containingClass coincidentally happens to be validated already, the SVM compilation will succeed, but then will fail to load because a record isn't created for definingClass

I'm not sure how that could happen. The reason is because, if a method gets a SVM validation record, it is 
done via `TR::SymbolValidationManager::addMethodRecord` which calls `appendClassChainInfoRecords(record->definingClass(), chainInfo);` [1]. If the defining class was not already validated, this will define a new ID as part of the `ClassChainRecord` record.

That said, I had run into a "should have already been validated" as part of my AOT MH work, because there was a mismatch between the JIT and AOT FrontEnd/ResolvedMethod APIs [2]. Maybe something similar is happening here?


[1] https://github.com/eclipse-openj9/openj9/blob/ff435327b1ea3f7ee9593545b0ab27c92673edae/runtime/compiler/runtime/SymbolValidationManager.cpp#L742
[2] https://github.com/eclipse-openj9/openj9/pull/20272/commits/9a779e1b096fb80f822c800f825b8ea456e0a439

**Comment by dsouzai** [comment]
> Now that I think about it, getClassFromSignature() isn't called with isVettedForAOT=true and that would cause an arbitrary class validation to be created without SVM, so the declaringClass in findOrFabricateShadowSymbol() is probably missing a validation record as well.

Because `getClassFromSignature()` is not alled with `isVettedForAOT=true`, in non-SVM AOT it will return NULL, which I think just means the compiler treats this symbol as unresolved. So, it's fine that there's no validation record here.

**Comment by cjjdespres** [comment]
> I'm not sure how that could happen.

What I mean is that in this issue, the `method` here:

https://github.com/eclipse-openj9/openj9/blob/ff435327b1ea3f7ee9593545b0ab27c92673edae/runtime/compiler/env/VMJ9.cpp#L9075-L9077

 was not previously validated, so the SVM assert triggers and the AOT warm compilation fails. It looks like that's because `firstMethod` here:

https://github.com/eclipse-openj9/openj9/blob/eae6d58876cfd797d0913c623775ce172fa4f850/runtime/compiler/compile/J9SymbolReferenceTable.cpp#L829-L852

is just the first method in the pool, and there wouldn't be any reason for a method record to have been created for it at this point. My idea was that in https://github.com/eclipse-openj9/openj9/issues/20529#issuecomment-2484538171, the method would coincidentally have been validated earlier, so compilation wouldn't have failed. I think that could happen, but after looking at the compilation logs again for https://github.com/eclipse-openj9/openj9/issues/20529#issuecomment-2484538171, I realized that the problem there wouldn't have occurred in `findOrFabricateShadowSymbol`. I was getting the logs of a couple methods mixed up, so the actual issue there is a bit different than what I described. Sorry. The sorts of relocation failures I was talking about do relate to using `getClassFromSignature()` instead of consulting a constant pool like in the failing code above, but I might as well describe exactly what's going on in that other issue.

**Comment by cjjdespres** [comment]
I've tested this a bit more, and I should mention that I get some (but not a very large number of) `compilationSymbolValidationManagerFailure`s with only `-Xaot:forceAOT`, and also with both `-Xjit:disableInlining -Xaot:forceAOT,disableInlining`. It's when I run with `-Xjit:disableInlining -Xaot:forceAOT` that I get as many as I mentioned in the first comment.

**Comment by cjjdespres** [comment]
> Ah I see, well this is fairly easy to solve, but maybe not the easiest to make it clean.

Yeah, I started doing something similar and it was a bit inelegant. I decided to take a stab at implementing `getClassFromSignature()` with a constant pool for JITServer/AOT instead, in https://github.com/eclipse-openj9/openj9/pull/20686, since that comment in `findOrFabricateShadowSymbol()` said it would be a better choice if it were supported.

**Comment by dsouzai** [comment]
Yeah  saw your PR after I made my comment, and what you're doing now is definitely much cleaner than what I suggested.
