### ISSUE TITLE
Spurious PACKED_SUPPORT_ENABLED field in com.ibm.oti.vm.VM

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse-openj9/openj9#2233]
Needed for a legacy version of Java 8 on ARM.

@pshipton or @DanHeidinga do you know if the ARM JCL has been updated?
If you don't know, I can run a personal build to check.

**Comment by DanHeidinga** [comment]
@pdbain-ibm `PACKED_SUPPORT_ENABLED` has never been used by the Extensions repos.

**Comment by pshipton** [comment]
The ARM JCL you refer to will never be updated, all subsequent ARM work will occur at OpenJ9. Once we get regular ARM builds working at OpenJ9, the internal build you refer to can be retired.

**Comment by pdbain-ibm** [comment]
Thanks.  That's the purpose of this issue (replacing an internal work item).
