### ISSUE TITLE
Setup eclipse CI integration for ibmruntimes/openj9-openjdk-jdk repo

### ISSUE THREAD

**Issue by jdekonin** [eclipse-openj9/openj9#2527]
Please can we setup CI integration for the openjdk extensions "head" repository, similar to the jdk11 setup.

    copyright/line end checks
    nightly builds, build/sanity/extended
    PR builds for both openjdk (next) and openj9

fyi @vsebe

**Comment by vsebe** [comment]
Created PRs (compile, extended, sanity) for OpenJ9 and OpenJDK.

**Comment by vsebe** [comment]
No groovy script available for testing linux x86 large heap, e.g. openjdk_x86-64_linux_largeHeap (see openjdk-test repository).

**Comment by vsebe** [comment]
@smlambert @llxia fyi

**Comment by llxia** [comment]
Issue is created in AdoptOprnJDK https://github.com/AdoptOpenJDK/openjdk-tests/issues/504 to add missing generic Jenkins file.

fyi, please use generic Jenkins file (not java version specific ones). For example, openjdk11_xxx will not be created.

**Comment by vsebe** [comment]
Tested PRs triggers - see https://github.com/eclipse/openj9/pull/2557
