### ISSUE TITLE
Test-sanity.functional-JDK11-linux_390-64_cmprssptrs CondyPrimitive_2 Invalid JIT return address

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#3082]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/34

===============================================
Running test CondyPrimitive_2 ...
===============================================
CondyPrimitive_2 Start Time: Sun Sep 30 15:35:51 2018 Epoch Time (ms): 1538336151328
test with '-Xjit:count=0,disableAsyncCompilation'
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

*** Invalid JIT return address 0000000000154088 in 000003FFB347E368

19:36:07.642 0x14d400    j9vm.249    *   ** ASSERTION FAILED ** at swalk.c:1622: ((0 ))

**Comment by irinarada** [comment]
@fjeremic @NigelYiboYu we need an assessment if this is mustfix ASAP

**Comment by fjeremic** [comment]
> @fjeremic @NigelYiboYu we need an assessment if this is mustfix ASAP

@r30shah can you please take a look with high priority? @pshipton is the core file saved anywhere?

**Comment by fjeremic** [comment]
@r30shah @NigelYiboYu I'm really wondering about the comment in https://github.com/eclipse/openj9/pull/2972#issuecomment-423513741. It seems we set this on Power and x86. As far as I can see we don't on Z. You may be more familiar with the details but I assume we cannot reach back to the snippet from our helper calls? We retrun to the mainline in all cases? i.e. we set R14 to return back to the mainline all the time?

I'm wondering if we're missing a GC map (and hence stack walker is unable to find a return point). I suppose a core file should be the tell tale.

**Comment by pshipton** [comment]
@fjeremic the core file is part of the functional_test_output.tar.gz file which is an artifact of the build. Its found from the link to the build in the first comment, but here is the directly link https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/34/artifact/functional_test_output.tar.gz

**Comment by pshipton** [comment]
Sorry, this is functional testing, not system. There is no core file saved.

**Comment by fjeremic** [comment]
> Sorry, this is functional testing, not system. There is no core file saved.

So what are the options here? Try to reproduce in a grinder? Will the core file be saved then?

**Comment by pshipton** [comment]
@smlambert ^

**Comment by pshipton** [comment]
Another occurrence https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/36

**Comment by irinarada** [comment]
@jdekonin we need access to the machines.
@fjeremic - please confirm.

**Comment by fjeremic** [comment]
> @jdekonin we need access to the machines.
> @fjeremic - please confirm.

I confirm. Can we also get @r30shah access as well? I'm assuming we're talking about the Jenkins Shelley posted about since the Eclipse CI Jenkins does not save core files as per Peter's comment.

**Comment by jdekonin** [comment]
Contacted @fjeremic direct.  There is nothing left on the machines as the grinder jobs cleanup after themselves.

**Comment by r30shah** [comment]
Opened up PR https://github.com/eclipse/openj9/pull/3089 to fix the issue.
