### ISSUE TITLE
Investigate 2.2% AcmeAir throughput drop with JITaaS

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#3620]
After merging the code from openj9/master into jitaas we observed a 2.2% througput drop for AcmeAir. The non-jitaas build is stable.

**Comment by dmitry-ten** [comment]
This commit 534f7485b06dadd2e5ba31341eb96548a792af2c is causing a regression in JITaaS throughput, but, somehow, mainline is unaffected. Investigating.

**Comment by mpirvu** [comment]
Throughput has been stable for a long time now, so closing this issue
