### ISSUE TITLE
Enable OMR's DDR support for OpenJ9

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse-openj9/openj9#378]
The OMR project has been implementing Direct Dump Reader (DDR) support on top of libdwarf.  

OpenJ9 needs to enable DDR support and ensure that the functionality in the OMR project is sufficient to provide the rich debug & introspection capabilities J9 has historically supported.

OpenJ9 issues are difficult to debug without this support.

OMR links
----------
https://github.com/eclipse/omr/blob/f4394252018f04074cb375cbbd7f1f00f41a106c/doc/ddr.md

https://github.com/eclipse/omr/blob/f4394252018f04074cb375cbbd7f1f00f41a106c/doc/ddr/DDR.md

https://github.com/eclipse/omr/pull/1222

**Comment by DanHeidinga** [comment]
This task is to drive the enablement of DDR across the OpenJ9 platforms.

**Comment by hangshao0** [comment]
I have an impression DDR is short for "Direct Dump Reader" :-)

**Comment by deesebas** [comment]
Yeah I think it's Direct Dump Reader too.  And [this ](https://github.com/eclipse/omr/blob/f4394252018f04074cb375cbbd7f1f00f41a106c/doc/ddr.md)page title calls it "DDR: The Data Dump Reader"! :)

**Comment by keithc-ca** [comment]
https://github.com/eclipse/openj9/blob/master/runtime/ddr/ddr.readme says:
```
DDR (Direct Dump Reader)
```

**Comment by DanHeidinga** [comment]
Updated the description to use the correct term.

**Comment by keithc-ca** [comment]
#432 allows blob stubs to compile cleanly if DDR is enabled (but generated blob tables are not available).

**Comment by keithc-ca** [comment]
#461 updates the docker image descriptions in anticipation of the requirement for libdwarf-dev.

**Comment by keithc-ca** [comment]
Generated DDR code is incomplete.

The hand-written code to support DDR should be able to make references to historical constants and features so that debugging core files produced by older JVMs is possible: the fact that #495 was needed is a sign that this is broken.

The set of types, etc. should include everything mentioned in `DDR_Artifacts/supersets/29/superset.ibuild.dat`.

The change for #495 should be reverted, catching `NoSuchFieldError` when that constant is not available at runtime.

**Comment by DanHeidinga** [comment]
@keithc-ca I know from talking with you (and watching the PRs) that you've made a lot of progress on this.  Can you provide a brief update on state of DDR?  What's done and what work still remains?

**Comment by keithc-ca** [comment]
Things are looking good.

The OMR layer is nearly complete. We're awaiting merge of these PRs:
- https://github.com/eclipse/omr/pull/2259 - constant folding
- https://github.com/eclipse/omr/pull/2322 - field offsets

I have been decomposing my work on openj9 into smaller logically related pieces:
- https://github.com/eclipse/openj9/pull/1221 - relocate DDR test code
- https://github.com/eclipse/openj9/pull/1223 - export access to DDR for b165+
- #? - adjustments to DDR namespace annotations
- #? - DDR code changes to remove dependencies on obsolete concepts
- #? - code to connect DDR into the build process

Once these land, we can begin to consider the changes necessary in the extensions repositories. For a preview, see:
- https://github.com/keithc-ca/openj9-openjdk-jdk8/tree/ddr - Java 8
- https://github.com/keithc-ca/openj9-openjdk-jdk9/tree/ddr - Java 9

For each, there is a new configuration option, `--enable-ddr`. The default is disabled except for Linux x86-64. I have lightly tested Linux ppc64le as well: it seems to work as well as x86-64.

**Comment by keithc-ca** [comment]
OpenJ9 connective changes are in https://github.com/eclipse/openj9/pull/1399.

**Comment by keithc-ca** [comment]
OpenJ9 jdk8 enablement is in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/59.

**Comment by keithc-ca** [comment]
OpenJ9 jdk9 enablement is in ibmruntimes/openj9-openjdk-jdk9#137.

**Comment by JasonFengJ9** [comment]
Not sure if it is still relevant, i.e., if `OpenJ9` still replies on https://github.com/eclipse/openj9/blob/master/debugtools/DDR_Artifacts/supersets/29/superset.base.dat and its `superset` friends?

If so, these `superset` files haven't been updated since switching to GIT repo. Previously, they are updated during each ibuild to capture latest changes.

**Comment by JasonFengJ9** [comment]
@keithc-ca explained that `OpenJ9 DDR` doesn't reply on these `superset` files.

**Comment by SueChaplain** [comment]
@keithc-ca - I am preparing the release notes for 0.9.0. Looks like there is still some work to do, so please can you confirm which platforms do have / don't have DDR support enabled? Thx

**Comment by pshipton** [comment]
I don't think AIX support is going to be ready for the 0.10.0 release, deferring.

**Comment by pshipton** [comment]
This was completed some time ago, for all platforms.
