### ISSUE TITLE
Print a JIT compilation thread shutdown message in a verbose log

### ISSUE THREAD

**Issue by fjeremic** [eclipse-openj9/openj9#421]
It would be useful if the JIT printed when a compilation thread is shutting down right in the verbose log. This can be used as an indication that a particular JVM has terminated in a multi-JVM environment where multiple verbose logs are collected.

**Comment by fjeremic** [comment]
@dsouzai / @mpirvu FYI.

**Comment by mpirvu** [comment]
When a compilation thread is terminating there is this message printed under verbose={compilePerformance}
```
   if (TR::Options::getCmdLineOptions()->getVerboseOption(TR_VerbosePerformance))
      {
       TR_VerboseLog::writeLineLocked(TR_Vlog_PERF,"Time spent in compilation thread =%u ms",
          (unsigned)(j9thread_get_self_cpu_time(j9thread_self())/1000000));
      }
```
@fjeremic   Is this enough? would you want additional information like the thread ID or vmThread pointer?

**Comment by fjeremic** [comment]
@mpirvu I did not know this. Thanks! TIL. This should be enough, though a proper "shutdown" message may be more intuitive to users such as myself. Adding in the thread ID and `J9VMThread*` could also prove to be useful in the future.

**Comment by mstoodle** [comment]
This looks like a reasonable beginner issue to me; please remove the label if anyone disagrees.
