### ISSUE TITLE
Add a validation record for isClassVisible

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9#4765]
`TR_J9SharedCacheVM::isClassVisible` currently only checks if `sourceClass` and `destClass` have been validated before calling the runtime frontend query `TR_J9VMBase::isClassVisible`. However, the class chains being valid in multiple runs doesn't necessarily imply visibility. Therefore, for AOT w/ SVM, a new validation record should be generated for this front end query. 

This work is a good exercise for anyone who wants to become familiar with OpenJ9's AOT and SVM infrastructure; it is a relatively straightforward task if you use the existing validation records as examples

- [ ] Add new `TR_ExternalRelocationTargetKind` enum, and associated string to `_externalRelocationTargetKindNames`, in OMR
- [ ] Add new `SymbolValidationRecord` subclass to the SVM
- [ ] Add _add_/_validate_ methods to the SVM for the new Validation Record
- [ ] Write the relocation header info for this new validation record in `J9::AheadOfTimeCompile::initializeCommonAOTRelocationHeader` (and debug info in `J9::AheadOfTimeCompile::dumpRelocationHeaderData`)
- [ ] Create a new `TR_RelocationRecord` subclass (and associated binary template)
- [ ] Call the _add_ method in `TR_J9SharedCacheVM::isClassVisible` and _validate_ method in the `applyRelocation` method of the `TR_RelocationRecord` subclass

Setting priority to low, because the one caller of `isClassVisible` does so only for non-AOT compilations; however, if ever there is another caller, or this code path is enabled under AOT, a validation for this query becomes functionally necessary.

**Comment by dylanjtuttle** [comment]
Hi, I would like to work on this! This is my first introduction to the OpenJ9 project. I have familiarized myself with the high-level concepts of JIT vs. AOT compilation, and have a basic understanding of what validation and relocation records do with regards to AOT. My question is, what would this particular validation record be verifying, and where should I look if I want to begin working on it?

Thank you!!

**Comment by dsouzai** [comment]
Hi @dylanjtuttle, thanks for your interest :). 

> what would this particular validation record be verifying
This validation record just checks if the answer returned `isClassVisible` for a given set of inputs is the same in an AOT load run as it was during the AOT compile run. All front end queries (i.e. all queries that ask questions about the JVM environment) in an AOT compile have to be validated before the code can be loaded in another JVM instance.

> where should I look if I want to begin working on it?
The description of this issue gives a pretty straightforward guide on how to tackle this. However, if you want to see something similar, check out `TR_J9SharedCacheVM::stackWalkerMaySkipFrames`, the associated SVM validation record `TR::StackWalkerMaySkipFramesRecord`, and the associated `TR_RelocationRecord` child class `TR_RelocationRecordValidateStackWalkerMaySkipFrames`. Also check out https://github.com/eclipse-openj9/openj9/blob/master/doc/compiler/aot/AddingNewRelocation.md.

**Comment by dylanjtuttle** [comment]
@dsouzai Thank you so much for the nudge in the right direction!

I've made a [PR in the OMR repo](https://github.com/eclipse/omr/pull/6726) which I believe should complete the first task.
