### ISSUE TITLE
Test failure doesn't show up in TAP output

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#5115]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/550
'''
06:39:56  FAILED test targets:
06:39:56  	UnsafeTests_0
06:39:56  
06:39:56  TOTAL: 211   EXECUTED: 129   PASSED: 128   FAILED: 1   SKIPPED: 82
'''

TAP output shows 111 results.

  | Duration | Status | Skip | Todo
-- | -- | -- | -- | --
1 - - testDDRExt_General_win_0 | 27 ms | OK | Yes | No
2 - - testDDRExt_Callsites_win_0 | 27 ms | OK | Yes | No
3 - - finalizerTest_0 | 28 ms | OK | Yes | No
4 - - stringConcatOptTest_0 | 15 sec | OK | No | No
5 - - jit_jitt_0 | 18 sec | OK | No | No
6 - - jit_jitt_1 | 19 sec | OK | No | No
7 - - jit_jitt_2 | 19 sec | OK | No | No
8 - - jit_jitt_3 | 19 sec | OK | No | No
9 - - jit_jitt_XCEEHDLR_0 | 26 ms | OK | Yes | No
10 - - jit_jitt_XCEEHDLR_1 | 26 ms | OK | Yes | No
11 - - jit_jitt_XCEEHDLR_2 | 26 ms | OK | Yes | No
12 - - jit_jitt_XCEEHDLR_3 | 25 ms | OK | Yes | No
13 - - jit_jar_0 | 41 sec | OK | No | No
14 - - jit_tr_0 | 2 min 51 sec | OK | No | No
15 - - StringPeepholeTest_0 | 1 min 30 sec | OK | No | No
16 - - jit_ra_0 | 2.9 sec | OK | No | No
17 - - jit_vich_0 | 26 sec | OK | No | No
18 - - JLM_Tests_interface_0 | 9.1 sec | OK | No | No
19 - - JLM_Tests_interface_1 | 9.1 sec | OK | No | No
20 - - JLM_Tests_class_0 | 2.5 sec | OK | No | No
21 - - JLM_Tests_class_1 | 2.5 sec | OK | No | No
22 - - JLM_Tests_IBMinternal_0 | 2.2 sec | OK | No | No
23 - - JLM_Tests_IBMinternal_1 | 2.2 sec | OK | No | No
24 - - String_CompactStrings_0 | 2.2 sec | OK | No | No
25 - - Nestmate_virtual_private_0 | 2.6 sec | OK | No | No
26 - - Nestmate_virtual_private_1 | 2.5 sec | OK | No | No
27 - - Nestmate_virtual_private_2 | 2.6 sec | OK | No | No
28 - - Nestmate_virtual_private_3 | 2.5 sec | OK | No | No
29 - - CondyPrimitive_0 | 1.5 sec | OK | No | No
30 - - CondyPrimitive_1 | 10 sec | OK | No | No
31 - - CondyPrimitive_2 | 27 sec | OK | No | No
32 - - CondyPrimitive_3 | 28 sec | OK | No | No
33 - - CondyPrimitive_4 | 1.5 sec | OK | No | No
34 - - CondyGarbageCollection_0 | 1.4 sec | OK | No | No
35 - - CondyGarbageCollection_1 | 6.6 sec | OK | No | No
36 - - CondyGarbageCollection_2 | 1.4 sec | OK | No | No
37 - - CondyGarbageCollection_3 | 1.6 sec | OK | No | No
38 - - CondyGarbageCollectionMetronomeLinux_0 | 26 ms | OK | Yes | No
39 - - CondyGarbageCollectionMetronomeAIX_0 | 1.4 sec | OK | No | No
40 - - NestAttributeTest_0 | 1.6 sec | OK | No | No
41 - - generalSanityTest_0 | 1.6 sec | OK | No | No
42 - - truncatedReturnTest_0 | 1.6 sec | OK | No | No
43 - - regressionFastresolve_mode110_0 | 26 ms | OK | Yes | No
44 - - regressionFastresolve_mode150_0 | 4.3 sec | OK | No | No
45 - - jsr335_interfacePrivateMethod_mode100_0 | 28 ms | OK | Yes | No
46 - - AttachAPISanity_0 | 12 sec | OK | No | No
47 - - CtorBCVTests_0 | 1.8 sec | OK | No | No
48 - - JCL_Test_0 | 53 sec | OK | No | No
49 - - JCL_Test_1 | 52 sec | OK | No | No
50 - - JCL_Test_OutOfMemoryError_0 | 4.8 sec | OK | No | No
51 - - JCL_Test_OutOfMemoryError_1 | 2 sec | OK | No | No
52 - - J9VMInternals_Test_0 | 3.4 sec | OK | No | No
53 - - JCL_TEST_Java-Security_0 | 10 sec | OK | No | No
54 - - JCL_Test_JITHelpers_0 | 4.1 sec | OK | No | No
55 - - JCL_TEST_MathMethods_0 | 2.6 sec | OK | No | No
56 - - TestArrayCopy_0 | 29 ms | OK | Yes | No
57 - - TestArrayCopy_1 | 28 ms | OK | Yes | No
58 - - TestArrayCopy_2 | 2 min 2 sec | OK | No | No
59 - - TestArrayCopy_3 | 2 min 1 sec | OK | No | No
60 - - pthreadDestructor_0 | 6.8 sec | OK | No | No
61 - - testReflectInvoke_0 | 1.5 sec | OK | No | No
62 - - testInvokeSpecialInsideInterface_0 | 1.5 sec | OK | No | No
63 - - reflect_0 | 1.7 sec | OK | No | No
64 - - NoSuchMethodTests_0 | 1.7 sec | OK | No | No
65 - - reattachAfterExit_0 | 1.5 sec | OK | No | No
66 - - JCL_Test_Package_0 | 1.5 sec | OK | No | No
67 - - hanoiTest_0 | 1.5 sec | OK | No | No
68 - - hanoiTestTM_NATIVE_0 | 26 ms | OK | Yes | No
69 - - hanoiTestTM_MEDIUM_0 | 29 ms | OK | Yes | No
70 - - hanoiTestTM_HEAVY_0 | 28 ms | OK | Yes | No
71 - - hanoiTestTM_SHOULDFAIL_0 | 28 ms | OK | Yes | No
72 - - memleaksTest_0 | 1 min 41 sec | OK | No | No
73 - - fibTest_0 | 10 sec | OK | No | No
74 - - testStringInterning_0 | 27 ms | OK | Yes | No
75 - - testStringInterning_1 | 1.9 sec | OK | No | No
76 - - testStringIndexOfString_0 | 1.5 sec | OK | No | No
77 - - testStringIndexOfString_1 | 3 sec | OK | No | No
78 - - testStringStreams_0 | 1.6 sec | OK | No | No
79 - - floatSanityTests_0 | 3.2 sec | OK | No | No
80 - - floatSanityTests_1 | 27 ms | OK | Yes | No
81 - - floatSanityTests_2 | 2.8 sec | OK | No | No
82 - - FileSystem-isAccessUserOnlyTests_0 | 1.5 sec | OK | No | No
83 - - Test_Class_0 | 1.3 sec | OK | No | No
84 - - TestFlushReflectionCache_0 | 1.5 sec | OK | No | No
85 - - TestFlushReflectionCache_1 | 26 ms | OK | Yes | No
86 - - TestFlushReflectionCache_2 | 27 ms | OK | Yes | No
87 - - TestRefreshGCSpecialClassesCache_NOBCI_0 | 1.5 sec | OK | No | No
88 - - TestRefreshGCSpecialClassesCache_NOBCI_1 | 28 ms | OK | Yes | No
89 - - jsr335tests_0 | 26 ms | OK | Yes | No
90 - - jsr335tests_1 | 26 ms | OK | Yes | No
91 - - jsr335tests_2 | 26 ms | OK | Yes | No
92 - - jsr335tests_3 | 29 ms | OK | Yes | No
93 - - jsr335tests_4 | 29 ms | OK | Yes | No
94 - - jsr335tests_defendersupersends_0 | 26 ms | OK | Yes | No
95 - - jsr335_interfaceStaticMethod_0 | 34 ms | OK | Yes | No
96 - - algotest2_0 | 1.4 sec | OK | No | No
97 - - ctest_0 | 0.2 sec | OK | No | No
98 - - jniargtests_0 | 0.44 sec | OK | No | No
99 - - vmtest_0 | 0.2 sec | OK | No | No
100 - - jsigjnitest_0 | 0.45 sec | OK | No | No
101 - - gc_rwlocktest_0 | 1 min 20 sec | OK | No | No
102 - - gc_rwlocktest_win_0 | 26 ms | OK | Yes | No
103 - - shrtest_linux_0 | 26 ms | OK | Yes | No
104 - - shrtest_zos_0 | 26 ms | OK | Yes | No
105 - - shrtest_aix_0 | 20 sec | OK | No | No
106 - - shrtest_win_0 | 27 ms | OK | Yes | No
107 - - thrstatetest_0 | 0.45 sec | OK | No | No
108 - - openj9_jsr292Test_0 | 2 sec | OK | No | No
109 - - openj9_jsr292Test_JitCount0_0 | 30 sec | OK | No | No
110 - - SharedCPEntryInvokerTests_0 | 6.7 sec | OK | No | No
111 - - SharedCP | 0 ms | OK | No | No

**Comment by pshipton** [comment]
@smlambert @llxia

**Comment by llxia** [comment]
Generated TAP file looks fine to me. It has all 211 tests listed.
[TestTargetResult.tap.txt](https://github.com/eclipse/openj9/files/2971022/TestTargetResult.tap.txt)

fyi @renfeiw

**Comment by smlambert** [comment]
06:40:00  Recording test results
[Pipeline] sh
06:40:06  + tar -zcf functional_test_output.tar.gz ./openjdk-tests/TestConfig/test_output_15526415013599
[Pipeline] sh
06:40:09  + find ./jvmtest/functional/work -name *.jtr
06:40:09  + tar -zcf jtr_test_output.tar.gz -T -
06:40:09  find: 0652-019 The status on ./jvmtest/functional/work is not valid.

Has it been seen as a problem on other machines?  
The status on ./jvmtest/functional/work is not valid.

**Comment by llxia** [comment]
> Has it been seen as a problem on other machines?
The status on ./jvmtest/functional/work is not valid.

It should not be related to the TAP rendering as `TAP Reports Processing: FINISH` was printed out before this line.

However, I do not see this error `find: 0652-019 The status on ./jvmtest/functional/work is not valid.` in previous passed builds.
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/549/console

```
01:57:19.022  TAP Reports Processing: FINISH
[Pipeline] junit
01:57:19.244  Recording test results
01:57:23.063  None of the test reports contained any result
[Pipeline] fileExists
[Pipeline] echo
01:57:23.231  ARTIFACTORY_SERVER is not set. Artifacts are not uploaded onto artifactory server.
```

**Comment by llxia** [comment]
Close this issue. Please reopen if the problem occurs.
