### ISSUE TITLE
Cache result of JIT objectAlignmentInBytes()

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#5972]
Each time `TR::Compiler->om.objectAlignmentInBytes()` is queried (or the deprecated `FrontEnd->getObjectAlignmentInBytes()`) it results in a call back into the JVM to query the answer.  This answer does not change for a particular JVM instance, hence the answer should be cached to avoid the overhead of the callback.

**Comment by 0xdaryl** [comment]
Related: #5904

**Comment by singh264** [comment]
https://github.com/eclipse/omr/issues/6248
