### ISSUE TITLE
Create env vars to set JITaaS options

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#6019]
Current code accepts -XX: command line options to set the JITaaS mode, machine and port. Example: `-XX:JITaaSClient,server=xxx,port=xxx`
When running in docker it's much more convenient to change these parameters with command line options like:
TR_JITaaSServerMode = 1
TR_JITaaSClientMode = 1
TR_JITaaSPort = xxx
TR_JITaaSServerAddress = ...
The question is: if both command line options and env vars are present which ones should take precedence.

**Comment by mstoodle** [comment]
> The question is: if both command line options and env vars are present which ones should take precedence.

Typically command line would take preference in the case both are set, I believe.

**Comment by a7ehuo** [comment]
@mpirvu I'll work on this one.

**Comment by caohaley** [comment]
I will work on this.

**Comment by chrisc66** [comment]
I will work on this issue

**Comment by chrisc66** [comment]
I have added above four environment variables to our code, and it seems working fine. 

A few questions to discuss:
* If both `TR_JITaaSServerMode = 1` and `TR_JITaaSClientMode = 1` are set, I guess it makes sense to just ignore these two env vars. i.e. run in Non-JITaaS mode.
* Some other env vars could also be useful, should we implement:
   * `TR_JITaaSTimeout` = xxx 
   * `TR_JITaaSsslKey` = xxx 
   * `TR_JITaaSsslCert` = xxx 
   * `TR_JITaaSsslRootCerts` = xxx 
   * `TR_XjitCount` = xxx   -->  ` -Xjit:count = xxx`
   * `TR_XjitVerbose` = 1   -->   `-Xjit:verbose`

@mpirvu

**Comment by mpirvu** [comment]
> If both TR_JITaaSServerMode = 1 and TR_JITaaSClientMode = 1 are set, I guess it makes sense to just ignore these two env vars. i.e. run in Non-JITaaS mode.

I am ok with that solution provided there is some message informing the user.
For the other env vars let's limit ourselves to JITaaS one, i.e. ignore TR_XjitCount and TR_XjitVerbose.
Do you have a link to the PR?

**Comment by chrisc66** [comment]
Yes, messages informing the user and `TR_JITaaSXXX` env vars are both added. The PR is not yet ready to be merged, but please look at #6138 .
