### ISSUE TITLE
Provide common implementation of AheadOfTimeCompile::processRelocations

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#6265]
Each code generator provides their own version of `AheadOfTimeCompile::processRelocations` whose logic is nearly identical.  This code should be refactored such that all backends share a single implementation.

**Comment by dsouzai** [comment]
This is what https://github.com/eclipse/openj9/issues/4803 is attempting to address :) There's already been some work on this front in terms of the writing of the relo headers.
