### ISSUE TITLE
Support and enable arraycopy transformations for AArch64

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#6438]
This issue tracks the work to enable the arraycopy transformations in value propagation.  It will require AArch64 backend support for the `TR::arraycopy` and `TR::ArrayCHK` opcodes.

**Comment by knn-k** [comment]
#13263 enables primitive arraycopy on AArch64.

**Comment by knn-k** [comment]
https://github.com/eclipse-openj9/openj9/pull/13279 enabled reference arraycopy on AArch64.
I think this issue can be closed now.
