### ISSUE TITLE
Support AutoSIMD on AArch64

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#6453]
The AArch64 JIT needs to enable the CodeGenerator feature `SupportsAutoSIMD`. This issue will track the work to ensure what the requirements are and to complete any work on AArch64.

**Comment by 0xdaryl** [comment]
@alvee-unb FYI

**Comment by knn-k** [comment]
AutoSIMD was enabled on AArch64 in 2021.  Closing.
