### ISSUE TITLE
Enable atomic free JNI for AArch64

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#6608]
Implement support for AArch64.  See #2576.

**Comment by 0xdaryl** [comment]
DirectToJNI is disabled for AArch64 here:
https://github.com/eclipse/openj9/blob/84db769ba38ffc9db90691fa80fd47c98115a04c/runtime/compiler/control/J9Options.cpp#L2119

**Comment by knn-k** [comment]
I merged #12703 for this.
