### ISSUE TITLE
AArch64: Implement string compression

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#7129]
A placeholder to figure out the work needed to implement String compression on AArch64 and then implement it.

**Comment by knn-k** [comment]
I see nothing in the VM nor in the JIT that is platform-specific for supporting `CompactStrings`.
I can run OpenJ9 for AArch64 with `-XX:+CompactStrings`.
It is disabled by default in OpenJ9 on all the platforms.  See https://github.com/eclipse/openj9/blob/79f0cfb39698fb883eedcc1dc776d5dfc9e2c460/runtime/vm/jvminit.c#L6007

**Comment by knn-k** [comment]
x and z platforms have some code for compressed string.
`CaseConversionManager` for x looks at `isCompressedString` in upper/lowerCase conversion, for example.
https://github.com/eclipse/openj9/blob/8a09d26dbd5caeda37718369e6e591c5e7302be6/runtime/compiler/x/codegen/J9TreeEvaluator.cpp#L11843

**Comment by knn-k** [comment]
PR #16452 has been merged, and string compression is enabled by default for Java 11+.

**Comment by knn-k** [comment]
x and z platforms recognize `com_ibm_jit_JITHelpers_toUpperIntrinsic*/toLowerIntrinsic*` methods, and they use `isCompressedString` for optimizaiton.  aarch64 and p platforms don't use these intrinsics.

https://github.com/eclipse-openj9/openj9/blob/7498dc04cb47b81c0de33713c1f99a5df375c629/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L4789-L4797
