### ISSUE TITLE
AArch64: Implement fast versions of Unsafe compareAndSwap recognized methods

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#7132]
Provide a fast, inlined version of the following recognized Unsafe methods:
```
sun_misc_Unsafe_compareAndSwapInt_jlObjectJII_Z
sun_misc_Unsafe_compareAndSwapLong_jlObjectJJJ_Z
sun_misc_Unsafe_compareAndSwapObject_jlObjectJjlObjectjlObject_Z
```

**Comment by knn-k** [comment]
`sun_misc_Unsafe_compareAndSwapInt_jlObjectJII_Z` was implemented and enabled by #6752, #10127, and #10102

**Comment by knn-k** [comment]
I opened #12655 for `sun_misc_Unsafe_compareAndSwapLong_jlObjectJJJ_Z`.

**Comment by knn-k** [comment]
#12671 implements inlining of `Unsafe_compareAndSwapObject`.

**Comment by knn-k** [comment]
This issue can be closed.
