### ISSUE TITLE
sanity.openjdk Windows Access is denied

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#7522]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Nightly/1
```
Execution failed: `main' threw exception: java.io.IOException: Access is denied.    

Execution failed: `main' threw exception: java.nio.file.AccessDeniedException: C:\Windows\7939526392057814672.tmp  
```
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_Nightly/1
```
Execution failed: `main' threw exception: j7ava.nio.file.AccessDeniedException: C:\Windows\1406889845721675710.tmp
```

**Comment by pshipton** [comment]
@llxia @smlambert @jdekonin @AdamBrousseau 
any ideas?

**Comment by smlambert** [comment]
Do we know if these OpenJ9 windows machines are configured same as Adopt and internal machines (re: cygwin, bash and Jenkins user access?)

**Comment by llxia** [comment]
I think this issue is resolved and we are running OpenJDK on windows.
