### ISSUE TITLE
Investigate implicit NULLCHKs on AArch64

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#8036]
Investigate implementing implicit NULLCHKs on AArch64.  That is, where the test for NULLness is either handled implicitly through a memory access or through a trap instruction, and the signal handler catches and routes the hardware exception accordingly so that a Java NullPointerException is thrown.  If this is feasible, implement it.

**Comment by knn-k** [comment]
I think we can close this issue.
#11347 has enabled implicit NULLCHK on AArch64.

**Comment by 0xdaryl** [comment]
Done
