### ISSUE TITLE
Cleaning up magic numbers in returnCleanup method in estimate code size

### ISSUE THREAD

**Issue by cathyzhyi** [eclipse-openj9/openj9#8664]
the `returnCleanup` method ECS has magic numbers as its argument used to identify the location of error return. It's better to clean this up and replace the number with enum or find a cleaner way to represent the location info.
See https://github.com/eclipse/openj9/pull/8598#discussion_r382764052

**Comment by singh264** [comment]
requesting to work on issue

**Comment by fjeremic** [comment]
> @fjeremic requesting to work on issue

Go for it! Let me know if you need any help.
