### ISSUE TITLE
Experiment with collaborators and what they can do

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse-openj9/openj9#9180]
@tajila Since you're a collaborator on the project and have been added to a github collaborator team, I can immediately assign items to you.  

Are you able to add labels?  Can you add a label to this issue and @ me in it so I can confirm?

**Comment by DanHeidinga** [comment]
Can you also try setting the Projects / Milestone settings on it?  I'd like to know what extra abilities collaborators get

**Comment by tajila** [comment]
@DanHeidinga I am unable to add labels or set Project/Milestone settings

**Comment by DanHeidinga** [comment]
Thanks for testing Tobi.  That's unfortunate as I was hoping to use that to expand the set of people who can set labels

**Comment by DanHeidinga** [comment]
I think the next step is to ask Eclipse if they can add the `Triage` role to the collaborator list:

> Triage: Recommended for contributors who need to proactively manage issues and pull requests without write access

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

**Comment by DanHeidinga** [comment]
Looking through https://bugs.eclipse.org/bugs/show_bug.cgi?id=483563 which added contributor teams, I see the following:
> Contributors, please make sure to include your github id in your Eclipse account since we need to know who you are on github before we can add you to a contributor team!

As far as I can tell, your account is set up correctly.

I've now opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=562071 to request that contributors have the "triage" role at the project.  We'll see what the Foundation says.

**Comment by DanHeidinga** [comment]
Issue tracking changes to the Eclipse github sync script: https://github.com/EclipseFdn/eclipsefdn-github-sync/issues/50

**Comment by DanHeidinga** [comment]
Should be resolved by https://bugs.eclipse.org/bugs/show_bug.cgi?id=562071#c16
