### ISSUE TITLE
Merge compressedrefs and non-compressedrefs tests builds into one

### ISSUE THREAD

**Issue by llxia** [eclipse-openj9/openj9#9231]
Related to the work of combining compressedrefs and non-compressedrefs SPECS into the same build, we are planning to merge two tests builds into one (removing _xl). Below are some todos:

- [x] No jvm option will be added for `NoOptions`. Remove the logic in TKG that adds jvm option -Xcompressedrefs or -Xnocompressedrefs
https://github.com/AdoptOpenJDK/TKG/blob/6ad0667a194152ba7a5a98d68b39731d6c2922a3/openj9Settings.mk#L23-L29

- [x] Update ottawa.csv to merge compressedrefs and non-compressedrefs into one SPEC. 

- [ ] And clean up ottawa.csv if possible (not required for this issue)

- [ ] Check to see if we can use the same ottawa.csv for internal vmfarm build

FYI @jdekonin @AdamBrousseau @pshipton @smlambert @DanHeidinga

**Comment by DanHeidinga** [comment]
fyi @gacholio - for awareness

**Comment by llxia** [comment]
As suggested by @pshipton , we will update NoOptions to Mode110 and Mode610 in [system tests ](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/system/) to cover all cases in mixedref SDK. (Remove the duplicates if it is in special.system)

**Comment by llxia** [comment]
As discussed with @renfeiw , list of items that we need to update:

- [ ] update ottawa.csv (see above) - we will start with `linux_x86-64_mxdptrs` 
- [ ] auto-detection: temporarily support mixedref in spec detect
- [ ] platform map:

- in Jenkins script: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests#L3
- in TKG


- [ ] platformRequirements in playlist.xml. Instead of using vm.cmprssptrs to limit the platform, use Mode.
https://github.com/eclipse/openj9/blob/d61567612953eafa234c124c3cc875f2b589f513/test/functional/JIT_Test/playlist.xml#L601

**Comment by llxia** [comment]
This issue is completed
