### ISSUE TITLE
IBM_JAVA_COMMAND_LINE environment variable not set

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9#947]
I find references to the environment variable IBM_JAVA_COMMAND_LINE in OpenJ9 debugtools/DDR_VM, the openj9.dtfj module, rasdump/javadump.cpp, but OpenJ9 does not set this environment variable. I believe for IBM Java the IBM Java launcher would set it to the command line options specified. Since its not set for OpenJ9, the RAS code may not provide these command line details as intended.

**Comment by DanHeidinga** [comment]
@fengxue-IS Can you take a look at this?  At least to figure out what we need to do here.

**Comment by fengxue-IS** [comment]
the original input is only available to the Java launcher, the best / near identical information can be reconstructed from the `vm_args` passed to `JNI_CreatedJavaVM()`, I am looking at rebuilding the input string in `addLauncherArgs()`

**Comment by DanHeidinga** [comment]
Another option is to look at the OS and the info it provides:
* https://msdn.microsoft.com/en-us/library/windows/desktop/ms683156(v=vs.85).aspx
* /proc/$PPID/cmdline (linux)

This will get the exact commandline used to start the process, not just the version passed to the VM as some options get modified by the launcher

**Comment by fengxue-IS** [comment]
tested with different approaches on all platforms,
Windows GetCommandLine works well,
AIX don't have command line stored under /proc/$PID/cmdline or a system call to retrieve that info
Linux systems have /proc/$PID/cmdline, though the file size is zero, so this have to be read/parsed in blocks
MacOS same as aix

for unix systems, this info can also be retrieved with `ps -o [cmd|command] -ww $PID` (requires shell command, not sure if this is a good idea)

**Comment by DanHeidinga** [comment]
> AIX don't have command line stored under /proc/$PID/cmdline or a system call to retrieve that info

@zl-wang Is there a way to get the command line from the OS on AIX?  The /proc filesystem on linux provides this info and we need the equivalent on AIX.

> (requires shell command, not sure if this is a good idea)

I agree this isn't a great idea.  Let's see if we can find an alternative.

One option is to see if we can define an API for the Java launcher to support that provides this info.  Might be worth a discussion with @andrew-m-leonard to see what can be added to the launcher.

**Comment by tajila** [comment]
@keithc-ca Can you please take a look at this?

**Comment by keithc-ca** [comment]
Sure, I'll add it to the list.

**Comment by keithc-ca** [comment]
For AIX, this looks promising: https://www.ibm.com/docs/en/aix/7.2?topic=g-getargs-subroutine.

**Comment by pshipton** [comment]
All the pieces are merged, I expect this can be closed.

**Comment by pshipton** [comment]
Re-opening due to https://github.com/eclipse-openj9/openj9/pull/14766
