### ISSUE TITLE
Find and archive any core / dmp files in post test step 

### ISSUE THREAD

**Issue by smlambert** [eclipse-openj9/openj9#969]
In Jenkins builds, we should be collecting and archiving any unexpected dump/core files that are produced during a test run.

**Comment by smlambert** [comment]
related to #968

**Comment by smlambert** [comment]
Awaiting #851 so that we make this change in scripts in a repo versus in scripts in Jenkins.

**Comment by sehirst** [comment]
Note that for core dumps on z/OS, an extra step is needed. The dump is initially written to the MVS file system. It needs to be copied to the unix filesystem by the test framework in order to be included in the archive which gets uploaded.

**Comment by AdamBrousseau** [comment]
Would be good to archive these to Artifactory (if available). Please see #2637, #2272.

**Comment by llxia** [comment]
@dutingda Could you take a look? Thanks.

**Comment by llxia** [comment]
fyi @JennyChenyj

**Comment by llxia** [comment]
There are two parts for this issue:

- [ ] catch cores during test execution. 
In [resultsSum.pl](https://github.com/eclipse/openj9/blob/200fc549e0400c6d25820866220d85507df77394/test/TestConfig/scripts/resultsSum.pl#L133), if the test failed with core on zos, move the core under `REPORTDIR/<testname>`.


- [ ] catch cores during test compilation. 
In [makefile](https://github.com/eclipse/openj9/blob/master/test/TestConfig/makefile#L81), run compile target in `REPORTDIR/<compile>`. If the compilation failed with core on zos, move the core under `REPORTDIR/<compile>`. 
This will also help catch cores for other platforms during test compilation. If the compilation failed with core on other platforms, core will be generated under `REPORTDIR/<compile>` and it will be archived in the post stage by default.

**Comment by JennyChenyj** [comment]
Hey @llxia! I opened a pr for the first part of the issue: https://github.com/eclipse/openj9/pull/7707
It was tested: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/3209/console
Thanks for reviewing it!

**Comment by llxia** [comment]
This issue is resolved.
