### ISSUE TITLE
Spec clarification: Final fields in records are not reflectively modifiable

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse-openj9/openj9#9929]
OpenJDK has clarified the specification for reflection to state that "Final fields in records are not reflectively modifiable" [0]

We need to validate the OpenJ9 applies this constraint on reflection correctly and Unsafe.  

MethodHandles and VarHandles already disallow setting final fields, though there may be a `setAccessible` path through MethodHandles.unreflect() that allows it - need some testing to confirm.

This inability to reflectively write final fields also applies to JDK 15 hidden classes, to Records, and to static final fields in all classes and interfaces.

[0] https://bugs.openjdk.java.net/browse/JDK-8247517

**Comment by DanHeidinga** [comment]
FYI @theresa-m @hangshao0 for records and hidden classes
FYI @andrewcraik @vijaysun-omr for the JIT aspect and potential performance benefits

**Comment by DanHeidinga** [comment]
From the Record CSR review in https://bugs.openjdk.java.net/browse/JDK-8247444

> This patch also proposes `sun.misc.Unsafe::objectFieldOffset` and `sun.misc.Unsafe::staticField{Offset/Base}` not to support records. 

We'll need to write some tests to validate the expected behaviour of Unsafe with respect to Hidden classes and Records

**Comment by DanHeidinga** [comment]
> FYI @andrewcraik @vijaysun-omr for the JIT aspect and potential performance benefits

 @andrewcraik @vijaysun-omr Do you want to keep this item open as a reminder to take advantage of the new rules around final fields?

**Comment by andrewcraik** [comment]
@DanHeidinga yes please - we just haven't had time to look at this yet.

**Comment by DanHeidinga** [comment]
Ok.  Rolling forward to the next release then

**Comment by andrewcraik** [comment]
Roll forward again due to lack of time - still needs to be looked at.

**Comment by tajila** [comment]
Moving this to Jan refresh release

**Comment by tajila** [comment]
We need to add testcases to validate our behaviour when using reflection to write final fields in hidden classes, Records, and static final fields in all classes and interfaces. 

Testing records, classes and interfaces can be done simply by writing java source code. For hidden classes one may need to use ASM or another bytecode generator.

The test needs to define a final field in the class and attempting to modify it using Reflection. That is, `setAccesible(true)` on java.lang.reflect.Field ref and attempting to write it. Also by using the `Field` with `Lookup.unreflectVarHandle(ref)` and checking if the var handle can write the final field. 

The behaviour should be validated with the reference implementation
