### ISSUE TITLE
Eliminate vlog line that says "#JITServer: Chain exists ..."

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9#9961]
The JITServer verbose log contains way too many lines of the form:
`#JITServer: Chain exists (00007F2DFF81B24C) so nothing to store`
These lines don't have much value, they add overhead and increase the size of the vlog, therefore it's better if we just remove them.

**Comment by mpirvu** [comment]
This is the line that needs to be removed: https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/env/J9SharedCache.cpp#L890
Attn @despresc

**Comment by AlexeyKhrabrov** [comment]
> This is the line that needs to be removed: https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/env/J9SharedCache.cpp#L890

This line is for relocation tracing, not the JIT verbose log. The actual vlog line that this issue is about was removed a long time ago in #10971, and another similar line was removed recently in #13956.

**Comment by mpirvu** [comment]
> This line is for relocation tracing, not the JIT verbose log

My bad. It seems that we had two issues for the same problem and one remained open. I guess we can close this issue and the PR created for it.
